Add Neighbors and test
sxs-collaboration/spectre pull request #100
Opened 2017-07-11 21:22 UTC by gsb76

2017-07-11 21:30 UTC, gsb76 commented on tests/Unit/Domain/Test_Neighbors.cpp
> +
`// Test size`

2017-07-11 21:30 UTC, gsb76 commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  CHECK(get_output(custom_neighbors) ==
`// Test output`

2017-07-11 21:30 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +    static_assert(std::is_nothrow_move_constructible<Neighbors>::value and
Might not be needed if this doesn't do anything.

2017-07-11 21:30 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +  Neighbors<VolumeDim>& operator=(const Neighbors<VolumeDim>& rhs) = delete;
set `= default` ?

2017-07-11 21:30 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +  void set_ids_to(const std::unordered_set<ElementId<VolumeDim>>& new_ids) {
needs testing

2017-07-11 21:30 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +  void add_ids(const std::unordered_set<ElementId<VolumeDim>>& additional_ids);
needs testing

2017-07-11 21:30 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +  typename std::unordered_set<ElementId<VolumeDim>>::iterator begin() {
does this need to be tested (in a particular way) ?

2017-07-11 21:30 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +  friend bool operator==(const Neighbors<N>& lhs,  // NOLINT
Delete if we no longer have == operators

2017-07-11 21:30 UTC, gsb76 commented on src/Domain/Neighbors.cpp
> +  os << "Ids = " << n.ids() << "; orientation = " << n.orientation();
This confuses the compiler when a line break comes after the `;`

2017-07-11 21:30 UTC, fmahebert requested changes

2017-07-11 21:30 UTC, fmahebert commented on src/Domain/BlockNeighbor.hpp
> +>>>>>>> Addition of BlockNeighbor and test
Oops

2017-07-11 21:54 UTC, wthrowe commented on src/Domain/Neighbors.cpp
> +                                const Orientation<VolumeDim> orientation)
orientation non-const

2017-07-11 21:54 UTC, wthrowe commented on src/Domain/Neighbors.hpp
> +/// Information about the neighbors of an object in a particular direction.
Do we use this for any objects other then Elements?

2017-07-11 21:54 UTC, wthrowe commented on src/Domain/Neighbors.hpp
> +  // Neighbors<VolumeDim>(std::unordered_set<ElementId<VolumeDim>> ids,
What's this comment about?

2017-07-11 21:54 UTC, wthrowe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  auto segment1_ids = std::array<SegmentId, 3>(
`std::array<...> segment1_ids{{...}};` seems clearer.  (Also for the following cases.)

2017-07-11 22:05 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +  // Neighbors<VolumeDim>(std::unordered_set<ElementId<VolumeDim>> ids,
left over from debugging constructor - will be deleted

2017-07-11 22:09 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +/// Information about the neighbors of an object in a particular direction.
will be changed to "neighbors of an Element in a particular direction"

2017-07-13 22:16 UTC, gsb76 commented on tests/Unit/Domain/Test_Neighbors.cpp
> +        "([B1,(L2I1,L1I0,L1I1)],[B3,(L2I2,L1I1,L1I0)],[B0,(L2I3,L1I0,L1I1)],["
Cannot check output on `unordered_sets` as they print out in different orders depending on the compiler - Travis build failed

2017-07-14 18:51 UTC, kidder requested changes

2017-07-14 18:51 UTC, kidder commented on src/Domain/Neighbors.hpp
> +    static_assert(std::is_nothrow_move_constructible<Neighbors>::value and
remove the private_asserts

2017-07-14 18:51 UTC, kidder commented on src/Domain/Neighbors.hpp
> +#include <memory>
don't need to include <memory> anymore

2017-07-14 18:51 UTC, kidder commented on src/Domain/Neighbors.hpp
> +  Neighbors<VolumeDim>& operator=(const Neighbors<VolumeDim>& rhs) = delete;
change delete to default

2017-07-14 18:51 UTC, kidder commented on src/Domain/Neighbors.hpp
> +  void set_ids_to(const std::unordered_set<ElementId<VolumeDim>>& new_ids) {
pass by value and then move in the next line

2017-07-14 18:51 UTC, kidder commented on src/Domain/Neighbors.hpp
> +  template <size_t N>
doesn't need to be a friend

2017-07-14 18:51 UTC, kidder commented on src/Domain/Neighbors.cpp
> +
add implementation of operator== (use the accessor functions as in operator<< so you don't need to declare it as a friend)

2017-07-14 18:51 UTC, kidder commented on src/Domain/Neighbors.cpp
> +#include "Parallel/CharmPupable.hpp"
I don't think this include is necessary; I think you need to include Parallel/PupStlCpp11.hpp

2017-07-14 18:51 UTC, kidder commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  static_cast<void>(test_neighbors);
remove

2017-07-14 18:51 UTC, kidder commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  CHECK(get_output(custom_neighbors) ==
remove the output checks for now until we decide about deterministic printing of unordered containers

2017-07-14 18:51 UTC, kidder commented on tests/Unit/Domain/Test_Neighbors.cpp
> +}
test equivalence operator, copy semantics and move semantics

2017-07-17 19:06 UTC, nilsdeppe requested changes
Could you rebase this against develop after we've merged BlockNeighbor (there's just a tiny fixup there, so it should be easy to do)? That way it'll be easy to just check the relevant Neighbor bits and make sure everything works together.

2017-07-17 19:06 UTC, nilsdeppe commented on src/Domain/Neighbors.hpp
> +  void set_ids_to(const std::unordered_set<ElementId<VolumeDim>> new_ids) {
`noexcept`

2017-07-17 19:06 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  test_move_semantics(custom_neighbors, custom_copy);
need to `std::move(custom_neighbors)` now

2017-07-17 19:06 UTC, nilsdeppe commented on src/Domain/Neighbors.hpp
> +  const std::unordered_set<ElementId<VolumeDim>>& ids() const { return ids_; }
`noexcept`

2017-07-17 19:06 UTC, nilsdeppe commented on src/Domain/Neighbors.hpp
> +  const Orientation<VolumeDim>& orientation() const { return orientation_; }
`noexcept`

2017-07-17 19:06 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  /*CHECK(get_output(custom_neighbors) ==
Add comment that this is related to issue #112, eg `// Issue #112`

2017-07-17 19:06 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  /*CHECK(get_output(custom_neighbors) ==
Add comment that this is related to issue #112, eg `// Issue #112`

2017-07-17 19:06 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  /*CHECK(get_output(custom_neighbors) ==
Add comment that this is related to issue #112, eg `// Issue #112`

2017-07-17 19:06 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  // Test default constructor:
Add same comment as for BlockNeighbors about not testing values because of serialization

2017-07-17 19:06 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  std::unordered_set<ElementId<3>> custom_ids;
make `const` by sticking initialization into a lambda

2017-07-17 19:06 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  std::unordered_set<ElementId<3>> more_custom_ids;
Again make `const` by using a lambda

2017-07-17 19:06 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  auto custom_copy = custom_neighbors;
make `const`

2017-07-17 19:06 UTC, nilsdeppe commented on src/Domain/Neighbors.cpp
> +#include <algorithm>
I don't think we need algorithm in here

2017-07-17 19:16 UTC, gsb76 commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  test_move_semantics(custom_neighbors, custom_copy);
Is this a new change? Because my Travis builds are failing and complaining about this even though it builds on my local Wheeler (I haven't rebased)

2017-07-17 19:30 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Neighbors.cpp
> +  test_move_semantics(custom_neighbors, custom_copy);
Yes, you should rebase

2017-07-19 21:40 UTC, kidder requested changes

2017-07-19 21:40 UTC, kidder commented on src/Domain/Neighbors.hpp
> +#include <iosfwd>
`#include <pup.h>` or forward declare 
namespace PUP {
class er;
}

2017-07-19 21:40 UTC, kidder commented on tests/Unit/Domain/Test_Neighbors.cpp
> +TEST_CASE("Unit.Domain.Neighbors", "[Domain][Unit]") {
add tests for 1D and 2D

2017-07-19 21:40 UTC, kidder commented on src/Domain/Neighbors.cpp
> +#include <pup.h>
if you included this in the hpp file, don't include it here;

2017-07-21 20:58 UTC, gsb76 commented on src/Domain/Neighbors.hpp
> +  typename std::unordered_set<ElementId<VolumeDim>>::iterator begin() {
with test_iterators in TestHelpers you'll be able to

2017-07-25 23:18 UTC, nilsdeppe approved these changes

2017-07-26 02:34 UTC, kidder approved these changes

2017-07-26 02:35 UTC, merged