Add Interpolatee_Tags and Interpolatee_Initialize.
sxs-collaboration/spectre pull request #1000
Opened 2018-09-26 23:11 UTC by markscheel

This is one of several PRs that will implement parallel interpolation.
Each Interpolatee will be able to tell the Interpolator which points
to interpolate to, and then will have a callback function that will
be called on those interpolated points.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-28 06:30 UTC, fmahebert commented
@markscheel you are #1000!

2018-10-01 16:29 UTC, markscheel commented
The tests that fail (Strahlkorper things, limiter things) appear to have nothing to do with the changes in this PR.

2018-10-01 20:23 UTC, nilsdeppe requested changes
Reviewed with @kidder 

We're happy for you to squash changes

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Tags.hpp
> +// Distributed under the MIT License.
No `_` in name of file

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Tags.hpp
> +struct Domain : db::SimpleTag {
I feel like this should be in the `Domain/Tags.hpp`

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +// Distributed under the MIT License.
No `_` in file name

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Tags.hpp
> +struct TimeSteps : db::SimpleTag {
`TimeSteps` -> `TemporalIds`

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Tags.hpp
> +/// Keeps track of which points on the Strahlkorper have been filled
Is this `Strahlkorper` specific or will this be general for any surface/line we interpolate to?

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +// Distributed under the MIT License.
@kidder and I think this should all go into `NumericalAlgorithms/Interpolation` (maybe a subdirectory?). We are reserving `Parallel` for low-level things that interact with Charm++ directly.

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Tags.hpp
> +template <size_t Dim, typename Frame>
Please add a Doxygen comment when you move the Domain tag.

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Tags.hpp
> +/// Time steps on which to interpolate.
Temporal ids on which to interpolate

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Tags.hpp
> +namespace Tags {
Can you add tests for the `name()` function of the tags?

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +///   vars_to_interpolate_to_target - a tmpl::list of variables tags.
a list of variables tags or a list of tags corresponding to variables?

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +///                                   is complete. DbItems includes everything
`DbItems` -> `DbTags`?

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +/// InterpolateeTag must contain the following type aliases:
This should follow the format of the actions documentation we've been using elsewhere (see for example, ComputeVolumeDuDt, the flux communication actions, or anything in `Time/Actions`)

This comment could use more ticks, .eg. `InterpolateeTag`, `tmpl::list`, `Metavariables::interpolator_source_vars`... :)

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +///   vars_to_interpolate_to_target - a tmpl::list of variables tags.
The rendering of this list is not a list. You'll need to make it a list (add `-` to the front)

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +  /// Two interpolator-specific type aliases must be in Metavariables:
You'll need to make this a list too (and add ticks) :)

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +                    Domain<3, Frame::Inertial>&& domain) noexcept {
Can we template the domain on Dim and Frame? (Or whatever InitializeElement does)

2018-10-01 20:23 UTC, nilsdeppe commented on src/Parallel/Interpolatee_Initialize.hpp
> +#include "DataStructures/DataBox/DataBoxTag.hpp"
Needs more includes like `DataBox.hpp`, `ConstGlobalCache`, all the tags things, `TaggedTuple.hpp`

2018-10-01 20:23 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Interpolatee_Initialize.cpp
> +// Distributed under the MIT License.
Too many `_` in the name

2018-10-01 20:23 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Interpolatee_Initialize.cpp
> +  template <size_t Dim, typename Frame> struct Domain;
formatting :(

2018-10-01 20:23 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Interpolatee_Initialize.cpp
> +  using LocalAlgTag =
We've recently updated the name of this from `LocalAlgTag` to `MockDistributedObjectsTag`

2018-10-01 20:23 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Interpolatee_Initialize.cpp
> +  auto domain = test_factory_creation<DomainCreator<3, Frame::Inertial>>(
Why not just `domain::creators::Shell<Frame::Inertial>(0.9, 4.9, 1, {{5, 5}}, false).create_domain();`?

2018-10-01 20:23 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Interpolatee_Initialize.cpp
> +  const auto test_domain =
Why not just have the domain creator be an object and call `create_domain()` on it twice?

2018-10-03 00:22 UTC, markscheel commented
Rebased and squashed.  

Not sure what namespaces the tags and actions should be in.

2018-10-03 05:56 UTC, fmahebert commented
I've previously communicated this to @markscheel, but I'll note it here: I find the name "Interpolatee" unhelpful because a) the name doesn't tell me what this thing is, and b) whatever intuition the name _does_ give me (from analogy with, e.g., employer vs employee, interviewer vs interviewee) makes me think the Interpolatee is being interpolated ... which is wrong.

Can/should we find a more intuitive name?

Based on 
> Each Interpolatee will be able to tell the Interpolator which points to interpolate to, and then will have a callback function that will be called on those interpolated points.

I would personally want to call this an InterpolatorManager, InterpolatorCoordinator, or similar. Likely there are better options, as I do not fully understand everything this code will do.

2018-10-03 17:09 UTC, markscheel commented
@fmahebert I'm fine with finding a better name than "Interpolatee" but I don't like "InterpolatorManager" or "InterpolatorCoordinator" because those names imply that there is a single "manager/coordinator" that is the boss controlling multiple subordinates but it's the other way around.  There will be many instances of what I currently call Interpolatees (each one a singleton Chare), and all of these will interact with the same Interpolator Chare (a group chare).  One Interpolatee might do wave extraction on a sphere of radius 1000M, another might do wave extraction on a sphere of radius 900M (or even better there can be an Interpolatee whose points are multiple Strahlkorpers).  Another Interpolatee might observe the density on the x-y plane, and another might observe the Lapse along the z-axis.   And eventually (after combining Interpolator code and horizon code) AhA, AhB, and AhC will be three additional Interpolatees or something similar to an Interpolatee.  And all of the Interpolatees will request data from the same Interpolator.

2018-10-03 20:31 UTC, markscheel commented on src/NumericalAlgorithms/Interpolation/InterpolateeInitialize.hpp
> +namespace Parallel {
namespace intrp.

2018-10-03 20:41 UTC, markscheel commented on src/NumericalAlgorithms/Interpolation/InterpolateeInitialize.hpp
> +namespace Interpolatee {
Remove namespace.

2018-10-03 20:55 UTC, markscheel reviewed
Wednesday meeting comments

2018-10-03 20:55 UTC, markscheel commented on src/NumericalAlgorithms/Interpolation/InterpolateeInitialize.hpp
> +/// - DataBox:
This should be things you need to get from the DataBox.

2018-10-03 20:55 UTC, markscheel commented on src/NumericalAlgorithms/Interpolation/InterpolateeInitialize.hpp
> +/// `InterpolateeTag` must contain the following type aliases:
Put component into this PR, and put this documentation there.

/// For requirements on `InterpolateeTag`, see InterpolateeComponent

2018-10-03 20:59 UTC, markscheel commented
Interpolatee->InterpolationTarget

2018-10-03 21:42 UTC, markscheel commented
I also added the component in the file InterpolationTargetComponent.  The documentation is there, but the component is not tested.

2018-10-04 02:48 UTC, kidder requested changes

2018-10-04 02:48 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetComponent.hpp
> +// Distributed under the MIT License.
commit message needs to reflect new names

2018-10-04 02:48 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetComponent.hpp
> +// Distributed under the MIT License.
I would prefer not to have Component in the file name

2018-10-04 02:48 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetInitialize.hpp
> +// Distributed under the MIT License.
I would prefer the file name to be the same as the action

2018-10-04 02:48 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetTags.hpp
> +// Distributed under the MIT License.
I would prefer just Tags.hpp for the file name

2018-10-04 03:01 UTC, wthrowe requested changes
Also, doxygen is giving warnings.

2018-10-04 03:01 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetComponent.hpp
> +      /*global_cache*/) noexcept {};
Extra `;`.

2018-10-04 03:01 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetComponent.hpp
> +namespace interp {
`intrp`

2018-10-04 03:01 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetComponent.hpp
> +namespace interp {
`intrp`

2018-10-04 03:01 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetComponent.hpp
> +///                           const Metavariables::temporal_id&) noexcept
Separate this function signature from the surrounding text somehow.  Probably backticks will look fine.

2018-10-04 03:01 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetInitialize.hpp
> +/// For requirements on InterpolationTargetTag, see InterpolationTargetComponent
`InterpolationTarget` and then make sure doxygen links it correctly.

2018-10-04 03:01 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetInitialize.hpp
> +  /// For requirements on Metavariables, see InterpolationTargetComponent
Again.

2018-10-05 17:33 UTC, markscheel commented
Made changes and squashed.  The only doxygen warning I did not fix was one unrelated to this PR about a \cite command to Kopriva in Spectral.hpp, which I assume will be or has been addressed in a different PR.

2018-10-05 17:36 UTC, markscheel commented
Oh, I didn't see @kidder s changes.  Will make them now...

2018-10-05 20:03 UTC, kidder requested changes
squash

2018-10-05 20:03 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +///   - Tags::TemporalIds<
one-line

2018-10-05 20:03 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +///   - ::Tags::Domain
one-line

2018-10-05 20:03 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +///                   InterpolationTargetTag::vars_to_interpolate_to_target>>
too many `>`

2018-10-05 20:03 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/Tags.hpp
> +/// Keeps track of which points have been filled with interpolated
one-line

2018-10-05 20:43 UTC, markscheel commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +///   - Tags::TemporalIds<
If I do it on one line, doxygen doesn't link to Tags::TemporalIds.

2018-10-05 20:43 UTC, markscheel commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +///   - ::Tags::Domain
Same here.  Doing it on one line spoils the doxygen link.

2018-10-05 20:49 UTC, markscheel commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +///   - Tags::TemporalIds<
Tags::TemporalIds<\`Metavariables\`> works, with ticks around Metavariables.

2018-10-05 20:52 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +///   - Tags::TemporalIds<
put the whole thing in `` ?

2018-10-05 20:53 UTC, markscheel commented
Ok, the doxygen links required ticks in strange places but I got it to work with moving on one line.

2018-10-08 18:39 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +///   - Tags::IndicesOfFilledInterpPoints
```
///   - `Tags::IndicesOfFilledInterpPoints`
///   - `Tags::TemporalIds<Metavariables>`
///   - `::Tags::Domain<VolumeDim, Frame>`
///   - `::Tags::Variables<typename
///                   InterpolationTargetTag::vars_to_interpolate_to_target>`
```
works correctly on my machine.

"Mark please squash this now" - Larry

2018-10-08 22:00 UTC, kidder approved these changes

2018-10-08 22:00 UTC, nilsdeppe approved these changes

2018-10-08 22:02 UTC, wthrowe approved these changes

2018-10-08 22:03 UTC, merged