Rename variables_tags to variables_tag for consistency.
sxs-collaboration/spectre pull request #1007
Opened 2018-09-30 19:36 UTC by kidder

## Proposed changes

Rename `variables_tags` to `variables_tag` to be consistent with other uses of `varaiables_tag`

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-30 20:27 UTC, nilsdeppe submitted a review, later dismissed
Travis failure is the documentation on develop

@wthrowe whenever you have time, this should be ready for you to look :)

2018-10-01 01:10 UTC, wthrowe requested changes
A number of these (indicated individually) should not be changed.  Things called `variables_tag` should be tags, but many of these are lists of tags (for which `variables_tags` seems an appropriate name).

2018-10-01 01:10 UTC, wthrowe commented on src/Evolution/Systems/CurvedScalarWave/Equations.cpp
>      typename CurvedScalarWave::System<Dim>::variables_tag::tags_list;
This was correct before.

2018-10-01 01:10 UTC, wthrowe commented on src/Evolution/Systems/GeneralizedHarmonic/System.hpp
>        brigand::list<gr::Tags::SpacetimeMetric<Dim>, Pi<Dim>, Phi<Dim>>;
This was correct before.

2018-10-01 01:10 UTC, wthrowe commented on src/Evolution/Systems/ScalarWave/Equations.cpp
>      typename ScalarWave::System<Dim>::variables_tag::tags_list;
This was correct before.

2018-10-01 01:10 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.hpp
>        tmpl::list<hydro::Tags::RestMassDensity<DataType>,
This was correct before.

2018-10-01 01:10 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.hpp
> +      db::wrap_tags_in<Tags::dt, variables_tag<DataType>>;
Again.

2018-10-01 01:10 UTC, wthrowe commented on tests/Unit/DataStructures/DataBox/Test_DataBox.cpp
>        tmpl::list<test_databox_tags::ScalarTag2, test_databox_tags::VectorTag2>;
Correct before.

2018-10-01 01:57 UTC, kidder commented
@wthrowe please clarify what you think should be `variables_tag` and what should be `variables_tags` because it seems there must be some `variables_tag` in the code that need to be `variables_tags` according to what you use above...

2018-10-01 02:13 UTC, wthrowe commented
I'm not sure how to clarify what I said above any further: `variables_tag` if it's a tag, `variables_tags` if it's a list of tags.

I don't see any inappropriate uses of `variables_tag` in the code.  Can you point out what cases you think should be changed?

2018-10-01 02:26 UTC, nilsdeppe commented
So in the current context in the code (until we have something like Variables for doubles, which might just be a TaggedTuple):

`Tags::Variables` -> `variables_tag`

`tmpl::list<Tags...>` -> `variables_tags`

Just to be reiterate what I think @wthrowe is saying but in terms type (correct me if I've misunderstood).

This is reasonable and I think what we had "agreed" upon at some stage (quotes because I cannot remember how formal of a discussion it was)

2018-10-01 03:10 UTC, kidder commented
@wthrowe you are correct, I was confused

2018-10-01 22:35 UTC, kidder commented
@wthrowe @nilsdeppe I've updated this

2018-10-01 23:49 UTC, nilsdeppe approved these changes

2018-10-02 18:01 UTC, wthrowe approved these changes

2018-10-02 18:02 UTC, wthrowe commented
Travis failures are upstream or timeouts.

2018-10-02 18:02 UTC, merged