Add Interpolator_Tags and Interpolator_Initialize.
sxs-collaboration/spectre pull request #1015
Opened 2018-10-01 19:55 UTC by markscheel

## Proposed changes

Another PR towards adding parallel interpolator step by step.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-09 21:40 UTC, kidder requested changes
Also fix line 30 of InitializeInterpolationTarget.hpp (remove the inner of set of ticks)

2018-10-09 21:40 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolatedVars.hpp
> +/// `Interpolator` for use by by `InterpolationTarget`s
by by

2018-10-09 21:40 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/Tags.hpp
> +    Mesh<3> mesh;
template on dim?

2018-10-09 21:40 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/Tags.hpp
> +                                  std::unordered_map<ElementId<3>, Info>>;
template on dim

2018-10-09 21:40 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/Tags.hpp
> +struct wrapper {
try to use `db::wrap_tags_in` from DataBoxTag.hpp

2018-10-09 21:40 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/Tags.hpp
> +struct NumElements : db::SimpleTag {
NumberOfElements

2018-10-09 21:40 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolatedVars.hpp
> +      IdPair<domain::BlockId, tnsr::I<double, 3, typename ::Frame::Logical>>>
3 -> dim

2018-10-09 21:40 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolatedVars.hpp
> +  std::unordered_set<ElementId<3>> element_has_communicated{};
3 -> dim

2018-10-09 21:40 UTC, kidder commented
you can squash the changes

2018-10-10 20:12 UTC, kidder submitted a review, later dismissed

2018-10-10 20:15 UTC, wthrowe submitted a review, later dismissed

2018-10-10 20:38 UTC, fmahebert submitted a review, later dismissed

2018-10-11 00:56 UTC, nilsdeppe commented
include what you use is sad :(

2018-10-11 16:13 UTC, markscheel commented
IWYU is fickle too, but not sad anymore.The changes it wanted this time (adding an include and removing forward declarations) were opposite of what it wanted the last time...

2018-10-11 17:36 UTC, nilsdeppe approved these changes

2018-10-11 17:38 UTC, kidder approved these changes

2018-10-11 22:22 UTC, kidder commented
travis failures are timeouts

2018-10-11 22:22 UTC, merged