Add support for Block orientations in Minmod and limiter actions
sxs-collaboration/spectre pull request #1025
Opened 2018-10-03 04:54 UTC by fmahebert

## Proposed changes

* Enable `OrientationMap` to re-orient a `Mesh`. This may need discussion: is `OrientationMap` the correct place to put this function? (i.e., do we want `OrientationMap` to depend on `Mesh`?) Alternatives might be in `Mesh`, in a new "MeshHelpers", or similar.
* Enable limiter actions to pass an `OrientationMap` to the limiter's `package_data` function.
* Use `OrientationMap` in `Minmod::package_data` to re-orient the element's size data.

Depends on #999. Order of new commits:
1. Clean up whitespace and ordering in OrientationMap test
2. Enable OrientationMap to reorient a Mesh
3. Support orientations in limiter actions
4. Support orientations in Minmod

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2018-10-03 14:46 UTC, fmahebert commented
Rebased now that #999 is merged

2018-10-05 20:26 UTC, kidder requested changes
squish it

2018-10-05 20:26 UTC, kidder commented on src/Domain/OrientationMap.cpp
> +    const Mesh<VolumeDim>& mesh) const {
noexcept

2018-10-05 20:26 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/SlopeLimiters/LimiterActions.hpp
> +          [&limiter, &orientation ](const auto&... args) noexcept {
don't need to capture and do the thing (we discussed)

2018-10-05 20:26 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/SlopeLimiters/LimiterActions.hpp
>            box);
`, orientation`

2018-10-06 01:47 UTC, fmahebert commented
rebased it and squished it

2018-10-06 02:38 UTC, kidder approved these changes

2018-10-07 03:59 UTC, nilsdeppe approved these changes
@wthrowe could you please look at this whenever you have some time? Thanks :)

2018-10-07 17:51 UTC, wthrowe approved these changes

2018-10-07 17:51 UTC, merged