Silence clang7 self-assignment warnings in tests
sxs-collaboration/spectre pull request #1027
Opened 2018-10-03 16:25 UTC by nilsdeppe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-03 17:43 UTC, wthrowe requested changes

2018-10-03 17:43 UTC, wthrowe commented on tests/Unit/DataStructures/Test_Variables.cpp
> +#pragma GCC diagnostic push
pop

2018-10-03 17:43 UTC, wthrowe commented on tests/Unit/TestHelpers.hpp
> +#pragma GCC diagnostic push
pop

2018-10-03 17:55 UTC, nilsdeppe commented
@wthrowe derp, sorry about that. Fixed now :)

2018-10-03 18:22 UTC, wthrowe submitted a review, later dismissed

2018-10-03 18:43 UTC, kidder submitted a review, later dismissed

2018-10-04 02:40 UTC, kidder commented
@nilsdeppe this didn't compile in the clang builds

2018-10-04 16:47 UTC, nilsdeppe commented
@kidder @wthrowe this should be ready to go now :)

2018-10-04 17:24 UTC, kidder approved these changes

2018-10-04 19:10 UTC, wthrowe approved these changes

2018-10-04 19:11 UTC, merged