Add generalized harmonic 3-index constraint
sxs-collaboration/spectre pull request #1034
Opened 2018-10-07 16:15 UTC by geoffrey4444

## Proposed changes

Begin adding generalized harmonic constraint equations, starting with the one that's the most straightforward, the 3-index constraint.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-07 22:56 UTC, osheamonn submitted a review, later dismissed

2018-10-08 00:39 UTC, nilsdeppe requested changes

2018-10-08 00:39 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Constraints.cpp
> +  for (size_t i = 0; i < SpatialDim; ++i) {
```
for (auto cons_it = constraint.begin(), phi_it = phi.begin(); const_it != constraint.end(); ++cons_it, (void)++phi_it) {
  *cons_it -= *phi_it;
}
```

2018-10-08 00:39 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Constraints.cpp
> +tnsr::iaa<DataType, SpatialDim, Frame> three_index_constraint(
Can you also add a return-by-reference overload?

2018-10-08 22:48 UTC, nilsdeppe approved these changes

2018-10-08 22:48 UTC, mar-celine approved these changes

2018-10-08 22:49 UTC, wthrowe approved these changes

2018-10-09 04:01 UTC, merged