Allow disabling debug flags
sxs-collaboration/spectre pull request #1049
Opened 2018-10-11 19:28 UTC by nilsdeppe

## Proposed changes

- Disabling debug symbols reduces memory usage by ~1.5x with GCC (clang it also is reduced but I can't remember how much)
- Disable debug symbols on TravisCI to avoid OOM errors and timeouts.

### Types of changes:

- [x] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-11 19:47 UTC, fmahebert requested changes
Minor rewording for clarity :)

2018-10-11 19:47 UTC, fmahebert commented on .travis/BuildLinux.sh
> +# We don't need debug symbols during CI and we are able to reduce memory
"during CI and we are" -> "during CI, so, by turning off the symbols, we are"

(same in MacOsBuild.sh)

2018-10-11 21:23 UTC, nilsdeppe commented
Not worth the minor rewording. I'd rather have the builds fail than fight over three word changes.

2018-10-11 21:42 UTC, fmahebert commented
I don't believe my suggestion amounted to a fight, but I would rather see the builds pass than insist that you make the change.

2018-10-11 21:43 UTC, nilsdeppe commented
No, I'm not mad I just don't want to put the effort in to change it.

2018-10-11 22:00 UTC, nilsdeppe commented
Just to be clear, I don't care what happens to this. It can be merged as is, left closed, or someone else can work on it how they see fit. I have enough other things to do that I personally don't warrant the clarification worth my time at this moment.

2018-10-11 22:01 UTC, fmahebert commented
Understood. I am happy for you to reopen this PR and dismiss my review. (Apparently I can't do that myself?)

2018-10-12 01:26 UTC, kidder approved these changes

2018-10-12 02:58 UTC, fmahebert commented on .travis/BuildLinux.sh
> +# We don't need debug symbols during CI and we are able to reduce memory
Marking this comment as resolved because it was deemed too nitpicky.

2018-10-12 02:58 UTC, fmahebert approved these changes

2018-10-12 18:46 UTC, merged