Interpolator receive volume data
sxs-collaboration/spectre pull request #1082
Opened 2018-10-17 23:35 UTC by markscheel

## Proposed changes
 
Add InterpolatorReceiveVolumeData.
This also adds the function that actually does the interpolation.
And it does some minor fixes to previous PRs (renaming a variable to a clearer name).

This is another PR towards parallel interpolation.
This is independent of #1075

### Types of changes:

- [ ] New feature

### Component:

- [ ] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-21 20:37 UTC, nilsdeppe requested changes
A few minor comments, I'm happy for you to squash :+1:

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/InterpolatorReceiveVolumeData.hpp
> +      const Variables<typename Metavariables::interpolator_source_vars>&&
vars should be non-const

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/InterpolatorReceiveVolumeData.hpp
> +        [&box, &cache, &temporal_id](auto x) {
`noexcept`

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +    const typename Metavariables::temporal_id& temporal_id) {
`noexcept`

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +                      const typename Metavariables::temporal_id& temporal_id) {
`noexcept`

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +              volume_vars_info) {
`noexcept`

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +                [&new_box, &local_vars](auto x) {
`noexcept`

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +                holders_l) {
`noexcept`

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +    db::DataBox<DbTags>& box, Parallel::ConstGlobalCache<Metavariables>& cache,
please use `gsl::not_null` for the non-const reference variables

2018-10-21 20:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +          // HorizonId, and which have not yet been interpolated.
I don't see a `HorizonId`. What am I missing?

2018-10-22 16:18 UTC, markscheel commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +          // HorizonId, and which have not yet been interpolated.
Oops, comment was leftover from when I took this piece of code from the horizon finder.

2018-10-22 21:01 UTC, wthrowe submitted a review, later dismissed

2018-10-22 21:07 UTC, nilsdeppe submitted a review, later dismissed

2018-10-22 21:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/TryToInterpolate.hpp
> +    gsl::not_null<db::DataBox<DbTags>*> box,
You could mark these `const gsl::not_null`

2018-10-23 15:51 UTC, nilsdeppe commented
@kidder could you please look at this whenever you have some time? Thanks! :)

2018-10-23 16:04 UTC, kidder submitted a review, later dismissed

2018-10-23 19:05 UTC, markscheel commented
Added const for the gsl::not_null arguments.

2018-10-23 19:07 UTC, nilsdeppe approved these changes
:+1: @kidder

2018-10-23 19:07 UTC, kidder approved these changes

2018-10-24 03:58 UTC, merged