Add CleanUpInterpolator.
sxs-collaboration/spectre pull request #1088
Opened 2018-10-19 21:05 UTC by markscheel

This is a PR towards parallel interpolation.

This is independent of #1075 and #1082 (and should be easier to review than those).

### Types of changes:

- [ ] New feature

### Component:

- [ ] Code
### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-22 16:01 UTC, nilsdeppe requested changes
I'm happy for you to squash the minor comments I have :+1:

2018-10-22 16:01 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/CleanUpInterpolator.hpp
> +                holders) {
`noexcept`

2018-10-22 16:01 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/CleanUpInterpolator.hpp
> +        [&](auto tag) {
`noexcept`

2018-10-22 16:01 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/CleanUpInterpolator.hpp
> +                             volume_vars_info) {
`noexcept`

2018-10-22 16:01 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/CleanUpInterpolator.hpp
> +                  holders_l) {
`noexcept`

2018-10-22 16:01 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/CleanUpInterpolator.hpp
> +                [&](auto tag) {
`noexcept`

2018-10-22 21:14 UTC, wthrowe requested changes

2018-10-22 21:14 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/CleanUpInterpolator.hpp
> +            }
Isn't this loop just `volume_vars_info->erase(temporal_id);`?

2018-10-23 20:01 UTC, markscheel commented
Fixed loop, and added a new commit where I fixed includes according to a manual IWYU run on files that Travis doesn't run IWYU on.

2018-10-24 03:25 UTC, kidder approved these changes

2018-10-24 03:27 UTC, nilsdeppe approved these changes
@wthrowe could you please look at this when you get a chance? Thanks :)

2018-10-24 15:52 UTC, nilsdeppe commented
Restart GCC job that failed with random segfaults.

2018-10-24 17:57 UTC, wthrowe approved these changes

2018-10-24 18:00 UTC, merged