Add GMRES linear solver
sxs-collaboration/spectre pull request #1090
Opened 2018-10-19 21:58 UTC by nilsleiffischer

## Proposed changes

### Types of changes:

- [x] New feature

### Component:

- [x] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

- [ ] TODO: Add tests for individual actions

2018-10-23 00:02 UTC, wthrowe requested changes
I only reviewed the first two commits.

Check Travis: Tests are failing and gcc is giving warnings.

2018-10-23 00:02 UTC, wthrowe commented on src/DataStructures/DenseMatrix.hpp
> +    size_t num_cols = std::numeric_limits<size_t>::signaling_NaN();
size_t doesn't have NaNs.  And if it did the rest of this function wouldn't work because `x == NaN` is false for all x.

2018-10-23 00:02 UTC, wthrowe commented on tests/Unit/DataStructures/Test_DenseMatrix.cpp
> +  CHECK(opts.get<ColumnMajorMatrix>() == expected);
Check no rows, no columns, and inconsistent row lengths.

2018-10-23 00:02 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/LinearSolver/DistributedLinearSolverAlgorithmTestHelpers.hpp
> +  using type = std::vector<DenseMatrix<double, blaze::columnMajor>>;
Add a comment somewhere explaining why these are vectors.

2018-10-23 15:05 UTC, nilsleiffischer commented
Thanks @wthrowe, I addressed your comments. Also refactored a couple of things so ended up rebasing.

2018-11-13 04:07 UTC, nilsdeppe requested changes
I'd prefer fixup commits since this is a bit on the larger side as far as PRs go :)

2018-11-13 04:07 UTC, nilsdeppe commented on src/DataStructures/DenseVector.hpp
> +    DenseVector<T, TF> result(data.size());
Is there no constructor for `DenseVector` that takes a begin and end iterator like there is for std::vector?

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Tags.hpp
> +    return "LinearOrthogonalization(" + Tag::name() + ")";
Why `LinearOrth` instead of just `Orth`?

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Tags.hpp
> +    return "LinearOrthogonalizationHistory(" + Tag::name() + ")";
same comment about `linear`

2018-11-13 04:07 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/DistributedLinearSolverAlgorithmTestHelpers.hpp
> +#include "Parallel/Printf.hpp"
Should be either removed (if unused) or joined with other includes

2018-11-13 04:07 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/DistributedLinearSolverAlgorithmTestHelpers.hpp
> +struct NumberOfElements {
These should go in a nested `OptionTags` namespace (i.e. `Distrib...::OptionTags`)

2018-11-13 04:07 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/DistributedLinearSolverAlgorithmTestHelpers.hpp
> +  using type = int;
`size_t`? I assume you can't have a negative number of elements :)

2018-11-13 04:07 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/DistributedLinearSolverAlgorithmTestHelpers.hpp
> +// Here we compute A(p)=sum_elements(A_element(p_element)) in a global reduction
I worry that the word `Here` is a bit unclear. Could you please name the actions so that if code gets moved around there'll be some hope of being able to reattach this comment to the correct code

2018-11-13 04:07 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/DistributedLinearSolverAlgorithmTestHelpers.hpp
> +        break;
Why not `ERROR` in the default case?

2018-11-13 04:07 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/LinearSolverAlgorithmTestHelpers.hpp
> +  static auto apply(db::DataBox<tmpl::list<DbTags...>>& box,
auto -> void

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +  static auto apply(db::DataBox<tmpl::list<DbTags...>>& box,
auto -> void

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ElementActions.hpp
> +  static auto apply(db::DataBox<tmpl::list<DbTags...>>& box,
auto -> void ? This doesn't return anything

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +  static auto apply(db::DataBox<tmpl::list<DbTags...>>& box,
auto -> void

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +  static auto apply(db::DataBox<tmpl::list<DbTags...>>& box,
auto -> void

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +    const auto& orthogonalization_history =
A comment here stating that you are now doing the `QR` decomp would be useful

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +    qr(orthogonalization_history, qr_Q, qr_R);
Is this calling into blaze? If so, let's not rely on ADL where we don't need to and use `blaze::qr`

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +    const double residual = length(beta - orthogonalization_history * minres) /
is `length` a blaze call again?

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +    if (static_cast<int>(get<::Tags::Verbosity>(box)) >=
`if (UNLIKELY(...))` (and you'll need to make sure you have `Gsl.hpp` included from Utilities

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +    DenseVector<double> beta(H_rows, 0.);
I would find a comment as to what the next little bit is doing useful. Doesn't need to be long, just a short reminder about what is in the long dox

2018-11-13 04:07 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +            mutable_orthogonalization_history->resize(
why the `mutable` prefix here? Is there some shadowing or something going on? (GCC likes to get that wrong)

2018-11-13 04:07 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file ${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/${EXECUTABLE_NAME}.input
Can this be broken up over a few lines to get it to 80 chars?

2018-11-13 04:07 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    TIMEOUT 30
30 seconds is longer than it takes all the tests to run on my machine right now. I think 5 is a more reasonable hard upper bound.

2018-11-15 14:46 UTC, nilsleiffischer commented on src/DataStructures/DenseVector.hpp
> +    DenseVector<T, TF> result(data.size());
I haven’t seen one in the documentation: 
https://bitbucket.org/blaze-lib/blaze/wiki/Vector%20Operations#!constructors

2018-11-15 14:49 UTC, nilsleiffischer commented on src/NumericalAlgorithms/LinearSolver/Tags.hpp
> +    return "LinearOrthogonalization(" + Tag::name() + ")";
I meant to add a prefix that abbreviates the namespace for uniqueness (see also the other tags in this namespace). Do you think I should omit the prefix?

2018-11-15 14:52 UTC, nilsleiffischer commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +            mutable_orthogonalization_history->resize(
Yes, I get shadowing complaints.

2018-11-15 15:53 UTC, nilsleiffischer commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file ${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/${EXECUTABLE_NAME}.input
It's one long path to the input file. I could move that to a new line, but it's still over 80 chars long. It's probably better formatting to keep it in one line?

2018-11-15 15:55 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file ${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/${EXECUTABLE_NAME}.input
I would find it better on two lines so it's a little less annoying to deal with

2018-11-15 15:55 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file ${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/${EXECUTABLE_NAME}.input
Can you use `\` to break the input file name across lines? Or use a variable to absorb some of the path?

2018-11-15 15:56 UTC, nilsleiffischer commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file ${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/${EXECUTABLE_NAME}.input
So end the line with a space + `\`, then start the next line at column 0 (not indented)

2018-11-15 15:59 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file ${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/${EXECUTABLE_NAME}.input
I think:
```cmake
  set(PATH
      "${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres")
  add_test(
    NAME "\"${TEST_IDENTIFIER}\""
    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file
    ${PATH}/${EXECUTABLE_NAME}.input
```

2018-11-15 16:04 UTC, nilsleiffischer commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file ${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/${EXECUTABLE_NAME}.input
How about
```
    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file
    ${CMAKE_CURRENT_SOURCE_DIR}/${EXECUTABLE_NAME}.input
```

2018-11-15 16:06 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +    COMMAND ${CMAKE_BINARY_DIR}/bin/${EXECUTABLE_NAME} --input-file ${CMAKE_SOURCE_DIR}/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres/${EXECUTABLE_NAME}.input
Sure :)

2018-11-15 16:40 UTC, nilsleiffischer commented
@nilsdeppe addressed your comments

2018-11-15 16:53 UTC, nilsdeppe commented on src/DataStructures/DenseVector.hpp
> +    DenseVector<T, TF> result(data.size());
Okay, sad, but nothing we can do about it :)

2018-11-15 16:54 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Tags.hpp
> +    return "LinearOrthogonalization(" + Tag::name() + ")";
That's an interesting idea. I think if you add a C++ comment then it won't be surprising :)

2018-11-15 17:00 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +            mutable_orthogonalization_history->resize(
I think we've been using `local_` to have a consistent naming convention when we get these false shadowing warnings (we should add this to the code review guidelines probably)

2018-11-15 17:01 UTC, nilsdeppe commented
Okay, replied to the two that were still outstanding (because of conversation). I'm happy for you to squash the existing ones and add new fixups for the couple small changes left :)

2018-11-15 21:26 UTC, kidder reviewed
I am happy for you to squash @wthrowe please look at

2018-11-16 10:25 UTC, nilsvu commented
@wthrowe @nilsdeppe @kidder fixed the remaining issues, squashed and rebased

2018-11-16 14:10 UTC, nilsdeppe submitted a review, later dismissed
Restart GCC debug build

2018-11-16 18:01 UTC, kidder submitted a review, later dismissed

2018-11-16 18:22 UTC, nilsdeppe commented
@nilsleiffischer this has conflicts and needs a rebase :)

2018-11-16 19:18 UTC, wthrowe requested changes

2018-11-16 19:18 UTC, wthrowe commented on tests/Unit/DataStructures/Test_DenseMatrix.cpp
> +  SECTION("ParseFromOptions") {
This is not the proper way to use `SECTION`.  You're running the tests above three times now.  See https://github.com/catchorg/Catch2/blob/master/docs/tutorial.md#test-cases-and-sections

2018-11-16 21:55 UTC, nilsleiffischer commented
fixed @wthrowe @nilsdeppe @kidder

2018-11-16 21:58 UTC, nilsleiffischer commented on tests/Unit/DataStructures/Test_DenseMatrix.cpp
> +  SECTION("ParseFromOptions") {
Thanks for the pointer, I thought the sections were more of a label than actual control flow.

2018-11-16 22:25 UTC, kidder approved these changes

2018-11-17 18:13 UTC, kidder commented
@wthrowe and @nilsdeppe please look at

2018-11-17 19:20 UTC, nilsdeppe approved these changes

2018-11-17 20:46 UTC, wthrowe commented on tests/Unit/DataStructures/Test_DenseMatrix.cpp
> +  SECTION("ParseFromOptions") {
Are the other tests actually testing what you want?

2018-11-19 15:45 UTC, nilsleiffischer commented on tests/Unit/DataStructures/Test_DenseMatrix.cpp
> +  SECTION("ParseFromOptions") {
yes. `SECTION` is used as intended everywhere else, except in one case in `Test_IterationId.cpp` that I fixed in #1188.

2018-11-19 20:05 UTC, wthrowe commented on tests/Unit/DataStructures/Test_DenseMatrix.cpp
> +  SECTION("ParseFromOptions") {
Sounds good!

2018-11-19 20:05 UTC, wthrowe approved these changes

2018-11-19 20:05 UTC, merged