Spinweight
sxs-collaboration/spectre pull request #1091
Opened 2018-10-20 00:13 UTC by moxcodes

## Proposed changes

Add spin-weight wrapper and convenience functions for random values used in the spin-weighted tests. The spin-weight wrapper ensures that math operations are permitted only for valid combinations of spin-weight. Unwrapped objects are treated as spin-weight 0 (this might be a concerning choice; it is definitely looser than insisting that spin-weights are always consistent).

### Types of changes:

- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2018-10-20 18:23 UTC, nilsdeppe requested changes
I'm happy for you to squash the changes

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> +SPECTRE_ALWAYS_INLINE SpinWeighted<Ret, Spin> operator+(
What you can do to set the return type without a template parameter is:
```
SPECTRE_ALWAYS_INLINE auto operator+(const SpinWeighted<T1, Spin>& lhs,
                        const SpinWeighted<T2, Spin>& rhs) noexcept
                    -> SpinWeighted<decltype(std::declval<T1>() + std::declval<T2>()), Spin> {
```
You can do the same to all the ones below :)

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> +SPECTRE_ALWAYS_INLINE bool operator==(
Could you add `operator!=` too? It can just do `return not(lhs == rhs);` (no data, so this way if `operator==` were to be updated, `!=` gets it for free)

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> +// @{
You don't need the `// @{` and `// @}` since you only have once function the Doxygen comment is being applied to. The `// @{` means "Apply the first Doxygen comment to all functions inside the `// @{` and `// @}`."

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> + * \brief A wrapper for a spin-weighting wrapper which limits math operations to
I find this sentence difficult to parse. Maybe something like:

  Make a spin-weighted type `T` with spin-weight `Spin`. Mathematical operators are restricted to addition, subtraction, multiplication and division.

would be clearer?

2018-10-20 18:23 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +  auto v1 = make_with_random_values<SpinWeighted<double, 0>>(
I think all these can be `const`.

2018-10-20 18:23 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +  auto gen = make_generator();
Could you factor out the operations an just `double` and template on the type, then do double, int and long?

2018-10-20 18:23 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +  auto v3 = make_with_random_values<SpinWeighted<double, 2>>(
Could you add one with a negative spin-weight?

2018-10-20 18:23 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +  CHECK(spin == 0);
The spin checks should be `static_assert` to verify that it could be evaluated at compile time.

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
The summary line in the commit message is a bit long

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> +SPECTRE_ALWAYS_INLINE SpinWeighted<T, 0> operator+
The formatting looks off here

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> +SPECTRE_ALWAYS_INLINE bool operator==(SpinWeighted<T, 0> lhs, T rhs) noexcept {
Can you add `operator!=` for the two new ones?

2018-10-20 18:23 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +/// \cond HIDDEN_SYMBOLS
Can you put the classes in an anonymous namespace?

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> +(T lhs, SpinWeighted<T,0> rhs) noexcept {
It's standard to use `const T& lhs, const SpinWeighted<T, 0>& rhs` (const references).

2018-10-20 18:23 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> +    SpinWeighted<T1, Spin> lhs, SpinWeighted<T2, Spin> rhs) noexcept {
It's standard to use `const SpinWeighted<T1, Spin>& lhs, const SpinWeighted<T2, Spin>& rhs` (const &) for these

2018-10-20 18:23 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +                "static_assert failed, " #LHSTYPE #OP #RHSTYPE " had a type");
remove `;`

2018-10-20 18:23 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +                                   std::declval<SpinTwo>()), SpinOne)
add `;`

2018-10-21 01:11 UTC, moxcodes commented
Fixups squashed in.
Cheers!

2018-10-21 01:48 UTC, nilsdeppe reviewed
Couple minor things I'm again happy for you to squash :)

2018-10-21 01:48 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +
only one blank line

2018-10-21 01:48 UTC, nilsdeppe commented on src/DataStructures/SpinWeighted.hpp
> + * Make a spin-weighted type `T` with spin-weight `Spin`. Mathematical operators
You'll need a `\brief` at the beginning of this line.

2018-10-21 04:39 UTC, moxcodes commented
Minor fixups squashed in.
Cheers!

2018-10-21 14:51 UTC, nilsdeppe submitted a review, later dismissed

2018-10-22 22:56 UTC, moxcodes reviewed
group code review with @markscheel @fmahebert @mgiesler

2018-10-22 22:56 UTC, moxcodes commented on src/DataStructures/SpinWeighted.hpp
> + *
remove

2018-10-22 22:56 UTC, moxcodes commented on src/DataStructures/SpinWeighted.hpp
> +    decltype(std::declval<T1>() + std::declval<T2>()), Spin1 + Spin2>
+->* (oops)

2018-10-22 22:56 UTC, moxcodes commented on src/DataStructures/SpinWeighted.hpp
> +    SpinWeighted<decltype(std::declval<T1>() + std::declval<T2>()), Spin>
+->- (oops)

2018-10-22 22:56 UTC, moxcodes commented on src/DataStructures/SpinWeighted.hpp
> +    decltype(std::declval<T1>() + std::declval<T2>()), Spin1 - Spin2>
again ops

2018-10-23 02:01 UTC, fmahebert reviewed
A small word fix, if you haven't already done the other changes

2018-10-23 02:01 UTC, fmahebert commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +  // check the plain data types act as spin 0
the -> that

2018-10-23 06:40 UTC, moxcodes commented
Fixups squashed.
Cheers!

2018-10-23 15:48 UTC, nilsdeppe submitted a review, later dismissed
Before you try to write a special vector for this we should talk because I don't think that'll be necessary. The way you've coded things here I think just beefing up the SpinWeighted class a bit in a separate PR will allow you to do `SpinWeighted<DataVector, SPIN>` and have everything work the way you want.

2018-10-23 15:54 UTC, kidder requested changes

2018-10-23 15:54 UTC, kidder commented on src/DataStructures/SpinWeighted.hpp
> +    decltype(std::declval<T1>() / std::declval<T2>()), Spin1 - Spin2>
this (and the similar fixes) should be in previous commit, or the last two commits should be squashed into one

2018-10-23 16:41 UTC, moxcodes commented
Changes re-allocated to appropriate commits.
Cheers!

2018-10-24 03:17 UTC, nilsdeppe submitted a review, later dismissed
@kidder @wthrowe could you please look at this when you get a chance? Thanks! :)

2018-10-24 03:21 UTC, kidder submitted a review, later dismissed

2018-10-24 18:39 UTC, wthrowe requested changes

2018-10-24 18:39 UTC, wthrowe commented on tests/Unit/TestHelpers.hpp
> +  INFO("Seed is: " << seed);
This won't work.  INFO creates an RAII-style object, so it needs to be in a scope enclosing the tests.

2018-10-24 18:39 UTC, wthrowe commented on tests/Unit/DataStructures/Test_SpinWeighted.cpp
> +  // check compile-timee spin values
`time`

2018-10-24 18:39 UTC, wthrowe commented on src/DataStructures/SpinWeighted.hpp
> + */
There is a change here that is in the wrong commit.

2018-10-25 14:35 UTC, nilsdeppe submitted a review, later dismissed
@kidder @wthrowe could you please look at this when you get a chance? Thanks!

2018-10-25 18:38 UTC, wthrowe commented
Update your commit message.

2018-10-25 22:34 UTC, moxcodes commented
commit message updated for the `MAKE_GENERATOR` macro.
Thanks!

2018-10-25 22:45 UTC, wthrowe approved these changes

2018-10-25 22:46 UTC, nilsdeppe approved these changes
@kidder

2018-10-26 03:54 UTC, kidder approved these changes

2018-10-26 03:55 UTC, merged