Prevent git constraint circumvention
sxs-collaboration/spectre pull request #1098
Opened 2018-10-23 09:49 UTC by hrueter

by actually checking the files as they are in the staging area

## Proposed changes

- the pre-commit tests now parse the files in the staging area instead of working directory
- addresses #1085 

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [x] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

- Constraints by clang-format are only suggestions and are not enforced

2018-10-23 14:52 UTC, nilsdeppe reviewed
This is definitely @wthrowe's territory, so I'll defer for him for feedback. Thanks for putting in the work on this!

2018-10-23 17:49 UTC, wthrowe requested changes
This causes issues with the `CheckFiles.sh` script, which is intended to run on the working directory, so that will have to switch to the normal grep somehow.  Other than that (and the indicated minor change) this looks very nice.

2018-10-23 17:49 UTC, wthrowe commented on tools/FileTestDefs.sh
> +    echo -n -e "\033[0;35m$2\033[0m:"
`${@: -1}`

2018-10-26 17:40 UTC, wthrowe requested changes
The scripts all work now, so that look good.  One more small thing.  You can squash your fixups.

2018-10-26 17:40 UTC, wthrowe commented on tools/FileTestDefs.sh
> +        staged_grep -q std::enable_if $1
Lost some quotes.

2018-10-27 08:20 UTC, hrueter commented
All requests have been addressed and fixups have been squashed.

2018-10-27 15:31 UTC, nilsdeppe approved these changes
Thanks for doing this :+1: Really appreciate it!

2018-10-27 21:00 UTC, wthrowe approved these changes

2018-10-27 21:39 UTC, merged