Add python script for generating XDMF files for ParaView
sxs-collaboration/spectre pull request #1101
Opened 2018-10-23 19:14 UTC by nilsdeppe

## Proposed changes

Add python script for generating XDMF files for ParaView. This will hopefully also work with VisIt.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-23 20:56 UTC, kidder requested changes
group review with @osheamonn and @wthrowe

2018-10-23 20:56 UTC, kidder commented on tools/GenerateXdmf.py
> +            grids = [x for x in h5temporal.keys()]
list()

2018-10-23 20:56 UTC, kidder commented on tools/GenerateXdmf.py
> +            for grid in grids:
iterate directly

2018-10-23 20:56 UTC, kidder commented on tools/GenerateXdmf.py
> +                components = [x for x in h5temporal.get(grid).keys()]
list

2018-10-23 20:56 UTC, kidder commented on tools/GenerateXdmf.py
> +    xdmf_output += "</Grid>\n</Domain>\n</Xdmf>"
close h5files

2018-10-23 20:56 UTC, kidder commented on tools/GenerateXdmf.py
> +        help="View only the stride'th time step")
the -> every

2018-10-23 20:56 UTC, kidder commented on tools/GenerateXdmf.py
> +        "value is not included.")
is not -> is

2018-10-23 20:56 UTC, kidder commented on tools/GenerateXdmf.py
> +        "included.")
is -> is not

2018-10-23 20:56 UTC, kidder commented on tools/GenerateXdmf.py
> +    return vars(parser.parse_args())
remove vars

2018-10-23 20:58 UTC, kidder approved these changes

2018-10-23 21:28 UTC, osheamonn approved these changes

2018-10-24 03:59 UTC, merged

2018-10-24 09:07 UTC, nilsleiffischer commented
You requested a review from me, so I had some comments pending but this was merged after only 9 hours. Please give us a bit more time to review, in particular when you request a review from someone in another timezone.

I meant to suggest using [`xml.etree.ElementTree`](https://docs.python.org/3/library/xml.etree.elementtree.html) to construct the XML instead of string formatting (and where you need to do string formatting, prefer [`str.format`](
https://docs.python.org/3/library/stdtypes.html)).

2018-10-24 13:09 UTC, nilsdeppe commented
You're right, my apologies. Regarding your concerns:
- We discussed using an XML lib but since this is something temporary to hold us over until the undergrads have their code done in a few weeks we decided to defer using an XML lib until then. Thanks for the example code, that'll be super useful :)
- Because the majority of the python code in the repo right now doesn't use `str.format` we decided to leave it as is and run some sort of python 2->3 converter once later on. There are also a few things we'd like to figure out with Travis regarding python:
  * How can we run a pep8 enforcer?
  * Is there a linter we can run that would tell those of us who are less familiar with python some of these suggestions.

2018-10-24 13:24 UTC, nilsvu commented
👍 could you open/link issues for these things?

2018-10-24 13:36 UTC, nilsdeppe commented
- conversion #1103
- travis targets #1104