Test parallel interpolator
sxs-collaboration/spectre pull request #1113
Opened 2018-10-26 19:11 UTC by markscheel

## Proposed changes

This tests that all of the Actions in Interpolator and InterpolationTarget work together as
they are supposed to.  The test sets up two InterpolationTargets with different points and
different ComputeItems, and runs both of them "simultaneously", and then checks that the
interpolated data has the correct values.

Two additional commits fix the names and/or template parameters of a few of
the Actions that are called inside other Actions (in previous tests the called Actions didn't exist and were mocked).

Currently depends on and includes a commit from #1106.

### Types of changes:

- [ ] New feature

### Component:

- [ ] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2018-10-31 21:49 UTC, kidder requested changes

2018-10-31 21:49 UTC, kidder commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +// and the function that should be called (chosen by hand to agree
and and

2018-10-31 21:49 UTC, kidder commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +      get<>(test_lapse)[n] = TestFunctionHelper<DbTagToRetrieve>::apply(
don't need <> for get of a scalar

2018-10-31 21:49 UTC, kidder commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +  INFO("seed" << seed);
use `CAPTURE(seed)` instead of INFO

2018-11-01 21:02 UTC, kidder requested changes
please rebase and squash

2018-11-01 21:46 UTC, markscheel commented
Rebased/squashed.

Is there currently a better way to do the "execute queued action from one of these random components" that I did very hackily?  If there isn't such a thing in current code, I can redo it in a nicer way.

2018-11-01 22:16 UTC, kidder submitted a review, later dismissed

2018-11-01 22:16 UTC, kidder commented
@wthrowe @nilsdeppe please look at

2018-11-01 22:57 UTC, moxcodes reviewed
group code review with @markscheel @fmahebert @geoffrey4444

2018-11-01 22:57 UTC, moxcodes commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +      get(test_lapse)[n] = TestFunctionHelper<DbTagToRetrieve>::apply(
`expected_interpolation_result` instead of `test_lapse` and `interpolation_result` instead of `lapse`

2018-11-01 22:57 UTC, moxcodes commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +    auto test_lapse = make_with_value<Scalar<DataVector>>(lapse, 0.0);
put lines 131-140 into a lambda for readability.

2018-11-01 22:57 UTC, moxcodes commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +template <typename InterpolateeTag, typename DbTagToRetrieve>
`InterpolationTargetTag`

2018-11-01 22:57 UTC, moxcodes commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +  using interpolator_source_vars = tmpl::list<gr::Tags::Lapse<DataVector>>;
make a new tag instead of `Lapse`, because the value being computed isn't really a lapse.

2018-11-01 22:57 UTC, moxcodes commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +    get<>(lapse) = 2.0 * get<0>(inertial_coords) +
these `<>` can also be removed.

2018-11-01 23:15 UTC, markscheel commented
Squashed again after making changes after Caltech code review.

2018-11-02 03:26 UTC, wthrowe requested changes

2018-11-02 03:26 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +  for (const auto& element_id : element_ids) {
Change this so it won't be included in "Warning cleanup 2018-11-XX".  (See #1109.)

2018-11-02 03:26 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +  };
No semicolon on the while loop.

2018-11-02 18:07 UTC, markscheel commented
Fixed everything that was flagged, and squashed.

2018-11-02 20:44 UTC, wthrowe approved these changes

2018-11-02 21:20 UTC, kidder approved these changes

2018-11-02 21:43 UTC, nilsdeppe approved these changes

2018-11-02 21:43 UTC, merged