Build python bindings only if requested
sxs-collaboration/spectre pull request #1114
Opened 2018-10-26 19:32 UTC by kidder

## Proposed changes

Do not build python bindings, unless requested by specifying `-D BUILD_PYTHON_BINDINGS` when invoking cmake

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-26 20:02 UTC, wthrowe requested changes

2018-10-26 20:02 UTC, wthrowe commented on cmake/SpectreSetupPython.cmake
> +  endif()
Logic is reversed.

2018-10-26 21:54 UTC, wthrowe approved these changes

2018-10-27 01:53 UTC, nilsdeppe approved these changes

2018-10-27 01:53 UTC, merged