Add documentation for WhichWedges to Shell
sxs-collaboration/spectre pull request #1115
Opened 2018-10-26 20:35 UTC by gsb76

## Proposed changes
Addresses issue #1112 
### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-27 01:57 UTC, nilsdeppe requested changes

2018-10-27 01:57 UTC, nilsdeppe commented on src/Domain/DomainCreators/Shell.hpp
> +      "the radial gridpoints will be spaced uniformly in log(r). The user may\n"
`\f$\log(r)\f$`

2018-10-27 01:57 UTC, nilsdeppe commented on src/Domain/DomainCreators/Shell.hpp
> +      "four wedges along the x-y plane using the WhichWedges option."};
ticks around `WhichWedges`

2018-10-29 19:23 UTC, kidder approved these changes

2018-10-30 14:38 UTC, nilsdeppe approved these changes

2018-10-30 16:35 UTC, kidder commented
@wthrowe please look at

2018-10-31 01:51 UTC, wthrowe approved these changes

2018-10-31 01:51 UTC, merged