Minor fixes to Wedge3D documentation
sxs-collaboration/spectre pull request #1130
Opened 2018-10-31 17:16 UTC by gsb76

## Proposed changes

Clarification of the log radial scaling used in Wedge3D, as well as a typo fix.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-10-31 21:52 UTC, kidder requested changes

2018-10-31 21:52 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> + *  \mathrm{log}r = \frac{1-\zeta}{2}\mathrm{log}R_{inner} +
`\log`

2018-11-01 17:59 UTC, kidder approved these changes

2018-11-01 17:59 UTC, kidder commented
@nilsdeppe @wthrowe please look at

2018-11-01 18:15 UTC, nilsdeppe approved these changes

2018-11-01 18:49 UTC, wthrowe approved these changes

2018-11-01 21:01 UTC, merged