Enable fallback primitive variable inversion schemes.
sxs-collaboration/spectre pull request #1144
Opened 2018-11-06 17:42 UTC by kidder

Must specify an ordered list of inversion schemes in the metavariables.
Newman Hamlin now returns boost::none instead of aborting on failures.
More information is output on failure of inversion.

Note: PalenzuelaEtAl still needs to be updated to fail gracefully.

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-11-06 17:57 UTC, nilsdeppe requested changes
I'm happy for you to squash changes :)

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Conservative/UpdatePrimitives.hpp
> +    using f =
Since we usually use `f` for continuation-style metafunctions, maybe the name `PrimFromCon` would be better

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Conservative/UpdatePrimitives.hpp
> +            typename Metavariables::ordered_list_of_primitive_recovery_schemes>;
Could you please document the requirement on metavariables?

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.cpp
>      if (max_iterations_ == iteration_step and not converged) {
`UNLIKELY` (I have a commit that does this, but if you want to add it that would be nice :) )

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.cpp
> +    if (a_in_cubic < 0.0) {
`UNLIKELY`

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.cpp
> +    if (rho_h_w_squared <= 0.0) {
`UNLIKELY`

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/NewmanHamlin.cpp
> +    if (v_squared < 0.0 or v_squared >= 1.0) {
`UNLIKELY`

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
> +         &equation_of_state, &s](auto scheme) {
`noexcept`

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
> +          if (!primitive_data) {
`!` -> `not`

2018-11-06 17:57 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.cpp
> +          MakeString{}
I think you can just do:
```cpp
ERROR("All primitive...");
```

2018-11-06 20:57 UTC, nilsdeppe submitted a review, later dismissed
@wthrowe could you please look at this when you get a chance? Thanks! :)

2018-11-06 22:21 UTC, wthrowe commented
IWYU is unhappy.  Otherwise looks good.

2018-11-06 23:36 UTC, wthrowe submitted a review, later dismissed

2018-11-06 23:37 UTC, nilsdeppe submitted a review, later dismissed

2018-11-07 19:32 UTC, kidder commented
@wthrowe @nilsdeppe this is ready now

2018-11-07 19:36 UTC, nilsdeppe approved these changes

2018-11-07 21:50 UTC, wthrowe approved these changes

2018-11-07 22:17 UTC, merged