Make ParallelInfo executable display info about parallelism
sxs-collaboration/spectre pull request #115
Opened 2017-07-15 13:55 UTC by nilsdeppe

2017-07-15 14:58 UTC, kidder requested changes

2017-07-15 14:58 UTC, kidder commented on src/Executables/ParallelInfo/ParallelInfo.cpp
> +    ERROR("Expected zero messages, not " << msg->argc - 1);
messages -> command line options
and print the ones received

2017-07-15 15:01 UTC, kidder commented
Also, I think it might be clearer to define callbacks instead of counting; thoughts?

2017-07-15 15:19 UTC, nilsdeppe commented
I agree, I'll make the change to use a reduction with a callback.

2017-07-17 19:18 UTC, kidder requested changes

2017-07-17 19:18 UTC, kidder commented on src/Executables/ParallelInfo/ParallelInfo.cpp
> +  const int digits_in_node = compute_digits(Parallel::number_of_nodes() - 1);
how about using log10

2017-07-18 14:23 UTC, nilsdeppe commented
Updated, squashed commits since there was only the one change.

2017-07-18 16:37 UTC, wthrowe commented on src/Executables/ParallelInfo/ParallelInfo.cpp
> +                                 std::ceil(std::log10(std::abs(number))));
Incorrect for powers of 10.  Should be `std::ceil(std::log10(std::abs(number) + 1))`.

2017-07-18 18:03 UTC, nilsdeppe commented
Good catch! I had talked to Larry about adding a non-constexpr math header file, since some of these functions we will want in general. So far the best we could come up with is `Utilities/Math.hpp`, but if you have a better suggestion I'd be happy to move it. I'm not sure if we'll want one test per math function, one for all of them, or some middle ground. This will likely be answered as we add more. I was thinking that these remain basic math functions that only depend on `<cmath>` and type traits, at least until we find a need for more complicated things.

2017-07-21 01:34 UTC, kidder approved these changes

2017-07-21 01:34 UTC, merged