Add finite amplitude correction to AlfvenWave
sxs-collaboration/spectre pull request #1154
Opened 2018-11-08 22:11 UTC by gsb76

## Proposed changes
Follows [the ECHO paper](https://arxiv.org/pdf/0704.3206.pdf) in setting up the correct Alfven speeds for finite amplitude waves.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-11-18 16:45 UTC, nilsdeppe requested changes

2018-11-18 16:45 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
> + * The Alfv&eacute;n wave phase speed that solves the grmhd equations, even for
grmhd -> GRMHD

2018-11-18 16:45 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
> + * \f$\vec{B_0}\f$, and the transverse magnetic field vector at \f$x=y=z=t=0\f$
Can you say `vector B_1 at ...`. It currently looks very strange rendered

2018-11-18 16:45 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
> + * \brief Circularly polarized Alfvén wave solution in Minkowski
please no unicode...

2018-11-18 16:45 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
> +  struct BkgdMagneticField {
I think you can name the class `BackgroundMagneticField` and specify a custom option name. Then you can make the variable name `backgroun_...` as well.

2018-11-18 16:45 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.cpp
> +         lhs.background_spacetime_ == rhs.background_spacetime_ and
Why does the pup function get more added than this?

2018-11-20 03:20 UTC, nilsdeppe submitted a review, later dismissed

2018-11-20 03:21 UTC, nilsdeppe commented
I'm happy for you to squash into the appropriate commits and rebase on develop :) :+1:

2018-11-26 20:52 UTC, wthrowe requested changes

2018-11-26 20:52 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
> + * \brief Circularly polarized Alfven wave solution in Minkowski
Don't change this.

2018-11-26 20:52 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/GrMhd/AlfvenWave.hpp
>   * An analytic solution to the 3-D GrMhd system. The user specifies the
Fix GrMhd -> GRMHD since you're touching lots of this anyway.

2018-11-29 05:06 UTC, gsb76 commented
I think the review process here is mostly concluded, I just need the OK to squash if @wthrowe  is happy with the fixes :smile:

2018-11-29 18:00 UTC, wthrowe commented
Go ahead.

2018-11-29 18:16 UTC, gsb76 commented
@kidder @nilsdeppe @wthrowe squashed :octopus:

2018-11-29 18:21 UTC, nilsdeppe approved these changes

2018-11-29 18:27 UTC, wthrowe approved these changes

2018-11-29 20:54 UTC, kidder approved these changes

2018-11-30 00:53 UTC, merged