Improve interpolation target kerr horizon
sxs-collaboration/spectre pull request #1175
Opened 2018-11-15 18:22 UTC by markscheel

## Proposed changes

InterpolationTarget::compute_target_points can add DataBox tags.
    
In particular, InterpolationTargetKerrHorizon
now adds a Strahlkorper and associated ComputeItems to the DataBox.
This allows `post_interpolation_callback` to get the Strahlkorper from
the DataBox to do things like surface integrals.

Also adds a test where a `post_interpolation_callback` does a surface integral.

### Types of changes:

- [x] New feature

### Component:

- [x] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-11-15 22:38 UTC, moxcodes reviewed
group code review with @markscheel @fmahebert @geoffrey4444 and Rob.

2018-11-15 22:38 UTC, moxcodes commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +    has_initialization_tags<T>::value and
this probably isn't needed for the desired behavior.
and if not, `has_initialization_tags` probably isn't needed.

2018-11-15 22:38 UTC, moxcodes commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +                     typename initialization_tags<T>::value>::value;
`tmpl::size` might make this marginally shorter.

2018-11-15 23:47 UTC, markscheel commented
Improved TMPL stuff (and squashed).

2018-11-16 21:12 UTC, wthrowe requested changes

2018-11-16 21:12 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +    static constexpr OptionString help = {"Options for InterpolationTargetC"};
Remove (as in A and B).

2018-11-17 20:00 UTC, wthrowe commented
Looks good.  Squash.

2018-11-19 15:46 UTC, markscheel commented
Squished.

2018-11-20 03:04 UTC, kidder submitted a review, later dismissed

2018-11-20 03:04 UTC, kidder commented
@wthrowe please look at

2018-11-20 05:22 UTC, wthrowe submitted a review, later dismissed

2018-11-20 06:05 UTC, kidder commented
@nilsdeppe please look at

2018-11-26 17:37 UTC, nilsdeppe reviewed
I have one minor renaming request that I'm happy for you to squash and to do a rebase immediately :) I'm also fine with someone else verifying it's been done if I don't get to it quickly enough :)

2018-11-26 17:37 UTC, nilsdeppe commented on src/NumericalAlgorithms/Interpolation/InitializeInterpolationTarget.hpp
> +  using value = tmpl::list<>;
I think `value` should be `type` since it's a type and not a value. The STL uses `type` for what you've called "value" and `value` for variables.

2018-11-26 17:37 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ParallelInterpolator.cpp
> +    // The interpolation is not perfect because I use too few grid points.
:+1: on the useful comment :)

2018-11-26 19:12 UTC, markscheel commented
Fixed value->type, rebased, squashed.

2018-11-26 19:13 UTC, nilsdeppe approved these changes

2018-11-26 20:08 UTC, kidder approved these changes

2018-11-26 22:50 UTC, wthrowe approved these changes

2018-11-26 22:53 UTC, merged