Terminate linear solver algorithm based on convergence flag in DataBox
sxs-collaboration/spectre pull request #1192
Opened 2018-11-21 16:40 UTC by nilsleiffischer

## Proposed changes

This PR changes the termination behaviour of the linear solvers (CG and GMRES). Instead of terminating the algorithm directly when they have converged, they now set a flag in `LinearSolver::Tags::HasConverged`. A new action `LinerSolver::Actions::TerminateIfConverged` handles the termination of the algorithm. This is necessary to do observations also after convergence, as well as to embed the linear solver into the (not yet implemented) non-linear solver.

I also add a `LinearSolver::Tags::Initial` prefix that is used to store the initial guess. This allows GMRES to update the solution in every step, as opposed to only after convergence, which is useful for observations.

### Types of changes:

- [x] New feature

### Component:

- [x] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2018-11-26 23:28 UTC, wthrowe submitted a review, later dismissed

2018-11-27 01:23 UTC, kidder commented
@nilsdeppe please look at

2018-11-27 02:04 UTC, nilsdeppe requested changes

2018-11-27 02:04 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/ConjugateGradient/ElementActions.hpp
> +                    tuples::TaggedTuple<InboxTags...>& /*inboxes*/,
inboxes can be `const`

2018-11-27 02:04 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/ConjugateGradient/InitializeElement.hpp
> +template <typename>
This is a general comment, not for this PR, but for decls are much easier to read if you name the template parameters. I'm not sure where this bad habit originated, I think it happened even in BitBucket.

2018-11-27 02:04 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/ConjugateGradient/ResidualMonitorActions.hpp
> +    // want to check for convergence here.
Is this an issue-worthy thing? I worry that it's effectively a `TODO` comment, which tend to never get done.

2018-11-27 02:04 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/ConjugateGradient/ResidualMonitorActions.hpp
> +    bool has_converged = equal_within_roundoff(residual, 0.);
can this be const?

2018-11-27 02:04 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +    // When more sophisticated convergence criteria are implemented we may also
Again should this be an issue?

2018-11-27 02:04 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +    bool has_converged = equal_within_roundoff(relative_residual, 0.);
can this be const?

2018-11-27 02:04 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Actions/Test_TerminateIfConverged.cpp
> +    {
Why not just write `CHECK(db::get<LinearSolver::Tags::HasConverged>(get_box()));` and save yourself 3 lines?

2018-11-27 02:04 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Actions/Test_TerminateIfConverged.cpp
> +      const auto& box = get_box();
Why not just write `CHECK_FALSE(db::get<LinearSolver::Tags::HasConverged>(get_box()));` and save yourself 3 lines?

2018-11-27 02:04 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearSolver/Actions/Test_TerminateIfConverged.cpp
> +    const auto& box = get_box();
Why not just write `CHECK(db::get<LinearSolver::Tags::HasConverged>(get_box()));`?

2018-11-27 12:01 UTC, nilsleiffischer commented on src/NumericalAlgorithms/LinearSolver/ConjugateGradient/ResidualMonitorActions.hpp
> +    // want to check for convergence here.
I'm going to add convergence criteria in an upcoming PR. At that point I'll definitely revisit this.

2018-11-27 12:02 UTC, nilsleiffischer commented on src/NumericalAlgorithms/LinearSolver/Gmres/ResidualMonitorActions.hpp
> +    // When more sophisticated convergence criteria are implemented we may also
see above

2018-11-27 12:07 UTC, nilsleiffischer commented
@nilsdeppe fixed

2018-11-27 15:18 UTC, nilsdeppe commented
Okay, I'm happy with the changes. Please go ahead and squash and rebase on develop :)

2018-11-27 15:30 UTC, nilsdeppe approved these changes

2018-11-27 16:09 UTC, nilsleiffischer commented
@kidder @wthrowe this should be ready

2018-11-27 22:40 UTC, kidder approved these changes

2018-11-28 04:34 UTC, kidder commented
@wthrowe please look at

2018-11-28 05:10 UTC, wthrowe approved these changes

2018-11-28 05:10 UTC, merged