Irreducible mass
sxs-collaboration/spectre pull request #1222
Opened 2018-12-05 01:17 UTC by jennifersanchez

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-12-06 22:52 UTC, jennifersanchez commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * of Hartle page 325. This function computes the irreducible
git rid of page number and add title

2018-12-06 22:52 UTC, jennifersanchez commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * \f$M_{irr}=\sqrt{\frac{A}{16\pi}\f$
add closed brace for sqrt

2018-12-06 22:54 UTC, jennifersanchez commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * \f$M_{irr}=\sqrt{\frac{A}{16\pi}\f$
M_\mathrm{irr}

2018-12-06 22:56 UTC, jennifersanchez commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * mass from the area of a horizon
add period

2018-12-06 23:04 UTC, jennifersanchez commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +  CHECK_ITERABLE_APPROX(irreducible_mass, expected_irreducible_mass);
`CHECK(irreducible_mass== expected_irreducible_mass)`

2018-12-21 14:34 UTC, geoffrey4444 requested changes
Please run `git-clang-format -f` on your changed *pp files (StrahlkorperGr.cpp, StrahlkorperGr.hpp, Test_StrahlkorperGr.cpp), and fix the minor issue. Then I think this is ready for a second reviewer to look at besides me! Once you make those changes, I'll remove the "in progress" tag and ask for someone else to review this.

2018-12-21 14:34 UTC, geoffrey4444 commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +  CHECK(irreducible_mass== expected_irreducible_mass);
small thing, but space before ==. I would have thought clang-format would have gotten that for you.

2019-01-03 17:06 UTC, geoffrey4444 commented
Ping @jennifersanchez @GitSamm @denyzamelchor @trami18 ... do you think you can take a stab at my latest change requests today or tomorrow?

2019-01-03 19:25 UTC, jennifersanchez commented
Yes. We’ll work on that today.

> On Jan 3, 2019, at 9:06 AM, Geoffrey Lovelace <notifications@github.com> wrote:
> 
> Ping @jennifersanchez <https://github.com/jennifersanchez> @GitSamm <https://github.com/GitSamm> @denyzamelchor <https://github.com/denyzamelchor> @trami18 <https://github.com/trami18> ... do you think you can take a stab at my latest change requests today or tomorrow?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/sxs-collaboration/spectre/pull/1222#issuecomment-451209126>, or mute the thread <https://github.com/notifications/unsubscribe-auth/Af8cI9Y3ZVEeaRsn1_TKkM7hqFb1HJn7ks5u_jh7gaJpZM4ZB0bL>.
>

2019-01-09 01:52 UTC, closed without merging