Transplant easily generalized tests to VectorImplTestHelper from Test_DataVector
sxs-collaboration/spectre pull request #1236
Opened 2018-12-11 19:25 UTC by moxcodes

## Proposed changes

Move tests which are easy to reformulate as general template tests from `Test_DataVector.cpp` to `VectorImplTestHelper.hpp`, and make use of the new test utilities instead. Also, the tests have been modernized to use random values and variable names and structure of the tests have been adjusted for clarity.
This is the 6th commit from #935.

### Depends on:
- [x] #1225 

### Types of changes:

- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2018-12-12 15:04 UTC, nilsdeppe reviewed
A couple minor things that were missed in the "fixup". I'm happy for you to squash. @kidder could you please look at this when you get a chance? Thanks!

2018-12-12 15:04 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_DataVector.cpp
> +  SECTION("test DataVector math operations") { test_datavector_math(); }
Is this unintentionally a section?

2018-12-12 15:04 UTC, nilsdeppe commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +    ref_vector.set_data_ref(make_not_null(&original_vector));
don't need `make_not_null` here

2018-12-12 15:04 UTC, nilsdeppe commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +  ref_generated_vector.set_data_ref(make_not_null(&generated_vector));
I don't think you need the `make_not_null` anymore

2018-12-12 17:16 UTC, kidder requested changes

2018-12-12 17:16 UTC, kidder commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +/// \brief test construction and assignment of a `VectorType` with a `ValType`
ValType -> ValueType

2018-12-12 17:16 UTC, kidder commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +template <typename VectorType, typename ValType>
ValType -> ValueType

2018-12-12 17:16 UTC, kidder commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +          typename ValType = typename VectorType::ElementType>
ValueType

2018-12-12 17:16 UTC, kidder commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +template <typename VectorType, typename ValType>
ValueType

2018-12-12 18:52 UTC, kidder reviewed
I am happy for you to squash if @nilsdeppe is

2018-12-12 18:58 UTC, nilsdeppe commented
I'm fine with a squash

2018-12-12 19:02 UTC, moxcodes commented
squashed.
Cheers!

2018-12-12 20:20 UTC, kidder submitted a review, later dismissed

2018-12-12 20:21 UTC, nilsdeppe submitted a review, later dismissed

2018-12-12 20:24 UTC, moxcodes commented
This'll need a rebase following #1225, due to the template fix there

2018-12-13 18:50 UTC, wthrowe reviewed
Also note the Travis Doxy failure.

2018-12-13 18:50 UTC, wthrowe commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +// Three types of tests are provided and one must be provided as the first
Missing `/`.

2018-12-14 03:09 UTC, nilsdeppe commented
@moxcodes this can be rebased now :)

2018-12-14 09:45 UTC, fmahebert reviewed
I really like the more descriptive variable names you are using now 👍. Here's two small naming things I found but that could be ignored.

2018-12-14 09:45 UTC, fmahebert commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +template <typename VectorType, typename ValType>
Should these ValTypes go back to ValueTypes?

2018-12-14 09:45 UTC, fmahebert commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +  const auto generated_val1 = make_with_random_values<ValType>(
I have a mild preference for the `x_val` variable names to become `x_value` to match the use of `ValueType` as the template parameter. But feel free to veto.

2018-12-14 15:26 UTC, moxcodes commented on tests/Unit/DataStructures/VectorImplTestHelper.hpp
> +template <typename VectorType, typename ValType>
oh no! I have done git so very bad.

2018-12-14 15:27 UTC, moxcodes commented
rebased, now with the actual edits in place. (thanks @fmahebert for noticing that)

2018-12-14 15:47 UTC, nilsdeppe approved these changes

2018-12-14 16:25 UTC, fmahebert approved these changes

2018-12-14 18:22 UTC, kidder approved these changes

2018-12-14 18:36 UTC, wthrowe approved these changes

2018-12-14 18:37 UTC, merged