Add ocean_gcc.sh environment
sxs-collaboration/spectre pull request #1252
Opened 2018-12-19 20:05 UTC by geoffrey4444

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-12-19 20:27 UTC, kidder requested changes
I realize we have not been doing this yet, but I think we should add some information about the machines for these files.  So let's start adding this info with this PR and I'll make an issue to update the existing files.

I'm thinking: 
- Location of the machine
- How to get access (and if access is restricted, who is it restricted to)
- Either a contact person or a weblink

This way we have a chance of pruning these files in the future as machines disappear.

Also please update `docs/Installation/InstallationOnClusters.md`

2018-12-20 21:05 UTC, kidder reviewed
thanks, please squash

2018-12-21 00:10 UTC, kidder submitted a review, later dismissed

2018-12-21 14:52 UTC, geoffrey4444 commented
@nilsdeppe can you please take a look?

2018-12-21 16:20 UTC, nilsdeppe reviewed
One minor comment, I can't test on the system though if you want me to I can. I have access to Orca so you could just take my SSH keys from there. If you don't think that's necessary I'm fine with it :)

2018-12-21 16:20 UTC, nilsdeppe commented on support/Environments/ocean_gcc.sh
> +spectre_unload_modules() {
We've generally been doing 4 space indentations inside these functions. Would you mind doing that? Thanks :)

2018-12-21 16:28 UTC, geoffrey4444 commented on support/Environments/ocean_gcc.sh
> +spectre_unload_modules() {
No problem, @nilsdeppe. Is the 4-space convention written anywhere o could have seen before now? Just curious if I missed something. 

It’s not necessary for you to test, because the cluster hasn’t even shipped yet :) If other users like my students run into trouble, I’ll file a fix then.

I’ll try to get the spaces fix in this afternoon.

2018-12-21 16:33 UTC, nilsdeppe commented on support/Environments/ocean_gcc.sh
> +spectre_unload_modules() {
It's not documented, I'm planning a PR with more code review things that I'll add it too. All the current env files do that, though.

Alright, sounds good :)

2018-12-24 18:31 UTC, nilsdeppe approved these changes

2019-01-08 21:17 UTC, kidder approved these changes

2019-01-09 02:40 UTC, geoffrey4444 commented
Some Travis checks unrelated to this PR error out...can this PR be merged, or should something change first?

2019-01-09 03:33 UTC, nilsdeppe commented
I restarted the two builds that timed out, including their first stage since I assume they timed out because of cache was tainted. Should be good to merge pretty soon :)

2019-01-11 23:22 UTC, merged