Improve Wedge3D documentation of halves_to_use
sxs-collaboration/spectre pull request #1281
Opened 2019-01-22 23:02 UTC by gsb76

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-01-23 18:57 UTC, nilsdeppe commented
If this closes an issue could you please update the comment to say `closes #...` so that GitHub automatically closes the issue when this gets merged?

2019-01-24 21:45 UTC, wthrowe commented
Doesn't render correctly.

2019-01-24 22:26 UTC, wthrowe submitted a review, later dismissed

2019-01-24 22:31 UTC, nilsdeppe commented
@markscheel since you're the author of the issue this fixes would you mind being the second reviewer on this?

2019-01-28 19:57 UTC, kidder commented
@markscheel please look at

2019-01-28 23:51 UTC, markscheel requested changes
Only minor changes.  Much much better than previous documentation!

2019-01-28 23:51 UTC, markscheel commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> +   * points returned from the inverse map function call lie in the range [-1,1]
Minor: please reword to "...points returned by the inverse map will lie in the range..."

2019-01-28 23:51 UTC, markscheel commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> +   * case of `Both`, no intermediate map is applied. In all cases, the logical
How about change to "The case of `Both` means a full wedge, with no intermediate map applied."

2019-01-28 23:51 UTC, markscheel commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> +   * \param halves_to_use Determines whether to split the Wedge3D in half. If
How about "split the Wedge3D in half" -> "construct a full wedge or only half a wedge."

And similarly below in two places "If the wedge is split in half" -> "If constructing only half a wedge".

(reasoning: "split a wedge in half" sounds like you are constructing two halves, but this class constructs only one half).

2019-01-31 23:25 UTC, kidder commented
@markscheel please look at

2019-02-01 18:53 UTC, markscheel reviewed
One small additional change; please squash.

2019-02-01 18:53 UTC, markscheel commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> +   * wedge is split in half, an intermediate affine map is applied to the
"the wedge is split in half" -> "constructing half a wedge".

2019-02-05 13:49 UTC, markscheel submitted a review, later dismissed

2019-02-05 14:58 UTC, nilsdeppe commented
@gsb76 please rebase this on the latest develop so travis will build.

2019-02-07 22:20 UTC, kidder approved these changes

2019-02-07 22:20 UTC, nilsdeppe approved these changes

2019-02-07 22:20 UTC, merged