Temporary computation buffer
sxs-collaboration/spectre pull request #1285
Opened 2019-01-23 23:05 UTC by markscheel

## Proposed changes

Adds TempBuffer, a buffer to store temporary variables in a way to reduce allocations.

Resolves #1275

### Types of changes:

- [ ] New feature

### Component:

- [ ] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-01-23 23:12 UTC, kidder requested changes
group review with @nilsdeppe and @wthrowe

2019-01-23 23:12 UTC, kidder commented on src/DataStructures/TempBuffer.hpp
> +      : tuples::tagged_tuple_from_typelist<TagList>::TaggedTuple(){};
extra ;

2019-01-24 00:05 UTC, moxcodes submitted a review, later dismissed

2019-01-24 08:47 UTC, nilsvu submitted a review, later dismissed

2019-01-24 13:03 UTC, markscheel commented
Does anyone understand why IWYU wants me to include `<complex>` in KerrSchild.cpp?

2019-01-24 14:52 UTC, nilsdeppe commented
It's confused and thinks the math functions like `sin`, etc. are in `<complex>` (which they are, but only for complex numbers...)

2019-01-24 17:41 UTC, markscheel commented
Removed semicolon and added pragmas to make IWYU happy; squashed since changes are trivial.

2019-01-24 17:56 UTC, moxcodes submitted a review, later dismissed

2019-01-24 18:26 UTC, nilsdeppe submitted a review, later dismissed

2019-01-24 22:22 UTC, kidder submitted a review, later dismissed

2019-01-25 04:59 UTC, wthrowe commented
You squashed incorrectly.  I'll let the rest of you all decide whether you want it fixed or you don't care.

2019-01-25 16:52 UTC, markscheel commented
I fixed my squash (the first time, I squashed a fixup into the wrong commit); it was easy to fix.

2019-01-25 16:53 UTC, moxcodes submitted a review, later dismissed

2019-01-25 18:23 UTC, wthrowe submitted a review, later dismissed

2019-01-25 18:35 UTC, kidder submitted a review, later dismissed

2019-01-25 20:12 UTC, kidder commented
@markscheel this has a conflict

2019-01-25 22:12 UTC, markscheel commented
rebased on develop, no more conflicts.

2019-01-25 22:22 UTC, nilsdeppe approved these changes

2019-01-25 22:27 UTC, moxcodes approved these changes

2019-01-25 22:31 UTC, kidder approved these changes

2019-01-25 22:31 UTC, wthrowe approved these changes

2019-01-25 22:37 UTC, moxcodes approved these changes

2019-01-26 13:32 UTC, nilsvu approved these changes

2019-01-26 13:33 UTC, nilsleiffischer commented
That's a lot of approvals for 64 lines of added code

2019-01-28 19:18 UTC, markscheel commented
The failing test, a gcc debug test, actually passes all the tests but exceeds the time limit for some reason.

2019-01-28 19:19 UTC, kidder commented
travis failure is timeout after tests passed

2019-01-28 19:19 UTC, merged