Travis Static Analysers
sxs-collaboration/spectre pull request #129
Opened 2017-07-21 03:29 UTC by nilsdeppe

Add the clang-tidy and cppcheck static analysis tools as targets on Travis. Also, split the checking of commit messages from checking "push hooks" on files.

2017-07-23 17:31 UTC, wthrowe requested changes

2017-07-23 17:31 UTC, wthrowe commented on tools/CheckCommits.sh
> -COMMIT_LINES=`git log -n 300 --oneline`
Update the comment.

2017-07-23 20:25 UTC, nilsdeppe commented on tools/CheckCommits.sh
> -COMMIT_LINES=`git log -n 300 --oneline`
Okay, updated, since it's just a single comment change I rebased right away. Please let us know when you think it's good to merge :)

2017-07-24 18:52 UTC, wthrowe commented on tools/CheckCommits.sh
> -COMMIT_LINES=`git log -n 300 --oneline`
Looks fine now.

2017-07-24 19:24 UTC, kidder approved these changes

2017-07-24 19:25 UTC, merged