Add return-by-ref versions for derivs of lapse
sxs-collaboration/spectre pull request #1321
Opened 2019-02-06 03:37 UTC by prayush

## Proposed changes

This PR adds return-by-reference counterparts to existing return-by-value functions that compute temporal and spatial derivatives of lapse.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-02-06 03:48 UTC, kidder requested changes
you can squash these

2019-02-06 03:48 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +        if (a != 0 or b != 0) {
LIKELY

2019-02-06 03:48 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +      if (a != 0 or b != 0) {
LIKELY

2019-02-06 22:59 UTC, kidder submitted a review, later dismissed

2019-02-07 02:36 UTC, kidder submitted a review, later dismissed

2019-02-07 02:36 UTC, kidder commented
@wthrowe @nilsdeppe please look at

2019-02-07 04:30 UTC, nilsdeppe submitted a review, later dismissed

2019-02-07 05:00 UTC, wthrowe submitted a review, later dismissed

2019-02-07 18:22 UTC, nilsdeppe commented
Travis failure is legit, documentation check is failing.

2019-02-07 22:18 UTC, kidder requested changes

2019-02-07 22:18 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
> + * where we used the equation from spatial_deriv_of_lapse() for
fix typo in the commit message

2019-02-08 03:11 UTC, kidder approved these changes

2019-02-08 16:15 UTC, nilsdeppe approved these changes

2019-02-08 16:15 UTC, merged