Add Ability to Loop over Directions
sxs-collaboration/spectre pull request #133
Opened 2017-07-25 21:52 UTC by gsb76

2017-07-25 23:23 UTC, nilsdeppe commented on src/Domain/Direction.hpp
> +  // An array of Directions.
I'm not sure this comment is useful. Maybe `An array of all logical Directions for a given dimensionality`?

2017-07-25 23:24 UTC, nilsdeppe requested changes

2017-07-25 23:24 UTC, nilsdeppe commented on src/Domain/Direction.hpp
> +  // An array of Directions.
I'm not sure this comment is useful. Maybe `An array of all logical Directions for a given dimensionality`?

2017-07-26 00:51 UTC, wthrowe commented on src/Domain/Direction.hpp
> +  static std::array<Direction<VolumeDim>, 2 * VolumeDim> directions() noexcept;
Perhaps name this something like `all_directions` to make what it does more obvious.

2017-08-01 19:26 UTC, kidder approved these changes

2017-08-01 19:26 UTC, nilsdeppe approved these changes

2017-08-01 19:26 UTC, merged