Add ObservationType argument to ObservationId constructor.
sxs-collaboration/spectre pull request #1367
Opened 2019-02-19 19:26 UTC by markscheel

This allows distinguishing between different classes that are
observing, so that there are no collisions when communicating
to ObserverWriter.  (Changing ObserverWriter will be done in a separate PR).

This is the first of several PRs that will address #1284.
I am adding these as several PRs because some of them (like this one) touch a large number
of files but should be easy to review.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-02-20 01:05 UTC, markscheel commented
Tests fail because I didn't rebase to current develop; fixing shortly.

2019-02-21 02:51 UTC, kidder requested changes

2019-02-21 02:51 UTC, kidder commented on src/IO/Observer/ObservationId.hpp
> +                             const ObservationType& /*meta*/) noexcept
add an optional string argument and hash the concat of the strings

2019-02-21 23:49 UTC, kidder reviewed
I am happy with the fixup @wthrowe @nilsdeppe ?

2019-02-22 02:15 UTC, nilsdeppe submitted a review, later dismissed
LGTM! :+1: thanks for doing this @markscheel!

2019-02-22 15:18 UTC, markscheel commented
squashed

2019-02-22 15:43 UTC, nilsdeppe approved these changes

2019-02-22 20:55 UTC, kidder approved these changes

2019-02-22 20:57 UTC, kidder commented
@wthrowe please merge this if you are happy with it

2019-02-24 00:28 UTC, wthrowe approved these changes

2019-02-24 00:29 UTC, merged