Construct ObservationId directly from a value
sxs-collaboration/spectre pull request #1408
Opened 2019-03-01 16:49 UTC by nilsleiffischer

## Proposed changes

This PR changes the constructor of `ObservationId` to take a `double value` directly, instead of a type that has a `value()` member function. This allows me to remove the wrapper around `size_t` that I used for the `LinearSolver::IterationId`. I haven't propagated the change to the other places that call `ObservationId` yet, so opening this as a draft PR to confirm the design.

### Types of changes:

- [x] New feature

### Component:

- [x] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-03-01 17:21 UTC, wthrowe commented
Yes, this looks good.

2019-03-04 05:16 UTC, nilsdeppe commented
I'll review, but might not have time until Tuesday or Wednesday :)

2019-03-04 13:29 UTC, nilsleiffischer commented
@wthrowe How should we handle time here, should I just call `time.value()` and pass it to construct the `ObservationId`s everywhere? I saw that you removed the `TimeValue` compute tag in some PR, which could have been used otherwise. Or we keep the generic constructor of `ObservationId` that calls a `.value()` member function if the `Id` template argument is not static-castable to `double`?

2019-03-04 19:43 UTC, wthrowe commented
Use `time.value()`.  This is a temporary solution until dense output is implemented.

2019-03-05 09:22 UTC, nilsleiffischer commented
@wthrowe I made the changes, this should be ready for review now

2019-03-05 21:33 UTC, wthrowe requested changes

2019-03-05 21:33 UTC, wthrowe commented on tests/Unit/IO/Observers/Test_ObservationId.cpp
> +  ObservationId time0(Time(Slab{0.0, 1.0}, 0).value(),
This section (everything with the `timeN` objects) is a duplicate of the preceding section now.

2019-03-06 14:22 UTC, nilsvu commented
fixed @wthrowe. @nilsdeppe and/or @markscheel please review

2019-03-06 17:59 UTC, wthrowe commented
Looks good.

2019-03-06 19:48 UTC, nilsleiffischer commented
Rebased and squashed

2019-03-11 16:19 UTC, nilsleiffischer commented
Rebased on #1385

2019-03-11 20:04 UTC, nilsdeppe approved these changes

2019-03-11 20:06 UTC, markscheel approved these changes

2019-03-11 21:31 UTC, kidder approved these changes

2019-03-11 21:32 UTC, kidder commented
@wthrowe please look at; you previously gave the go ahead for a squash, so it should be quick; please merge if you are happy with it.

2019-03-12 01:59 UTC, wthrowe approved these changes

2019-03-12 01:59 UTC, merged