Christodouloumass
sxs-collaboration/spectre pull request #1410
Opened 2019-03-02 00:44 UTC by trami18

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-03-06 00:10 UTC, geoffrey4444 requested changes

2019-03-06 00:10 UTC, geoffrey4444 commented on docs/References.bib
> +      url            = "https://arxiv.org/pdf/1607.05377.pdf"
url -> "https://doi.org/10.1088/0264-9381/33/24/244002"

2019-03-06 00:10 UTC, geoffrey4444 commented on docs/References.bib
> +@article{Lovelace:2016uwp,
No colon

2019-03-06 00:10 UTC, geoffrey4444 commented on docs/References.bib
> +@article{Lovelace:2016uwp,
Please put this reference in alphabetical order with the other entries by the key

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * \details See Eq. (1) of e.g \cite Lovelace:2016uwp.
@trami18 says no colon here

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * \details See Eq. (1) of e.g \cite Lovelace:2016uwp.
"See e.g. Eq. (1) of \cite Lovelace:2016uwp"

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * \brief Christodulou Mass of a 2D `Strahlkorper`.
Christodoulou here and throughout the PR

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * This function computes the Christodulou mass from the spin angular momentum
spin angular momentum -> dimensionless spin angular momentum

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.hpp
> + * \f$M_{Chris}= \sqrt{\frac{M_{irr}^2+\chi^2}{4M_{irr}^2}}
M^2 = Mirr^2 + \chi^2 M^4 / 4 Mirr^2, solve for M, make sure this function gives M. \chi = S / M^2, so you have to solve for S and plug into Eq. (1) then solve for M.

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +double christodoulou_mass(const double  spin_magnitude) noexcept {
spin_magnitude -> dimensionless_spin_magnitude, const double irreducible_mass

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.hpp
> +                          irreducible_mass) noexcept;
double irreducible_mass

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  return sqrt(square(irreducible_mass)+ square(dimensionless_spin_magnitude)/ (4.0 * square(irreducible_mass)));
Always run git-clang-format -f on your code before committing. In this case, add a space after the line to change it, so git-clang-format -f sees that this is a modified line.

2019-03-06 00:10 UTC, geoffrey4444 commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +double square(double a) {
Don't need square()
Just need to `#include Utilities/ConstantExpressions.hpp`

2019-03-06 00:10 UTC, geoffrey4444 commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +               const double expected_christodouloumass) noexcept {
expected_christodoulou_mass (add underscore)

2019-03-06 00:10 UTC, geoffrey4444 commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +      dimensionless_spin_magnitude, irreducible_mass);
pass dimensionless_spin_magnitude to test_area(), or pass spin and take magnitude here

2019-03-12 03:28 UTC, kidder commented
Current status:

- [ ] @geoffrey4444 needs to look at the fix ups
- [ ] @geoffrey4444 will help with the rebase and squash when happy with the fix ups

2019-03-12 23:27 UTC, closed without merging

2019-03-13 00:08 UTC, geoffrey4444 commented
Open