Option parsing
sxs-collaboration/spectre pull request #142
Opened 2017-08-03 21:18 UTC by wthrowe

I have made many changes from the original code.  Some of the highlights:
* Most of the documentation and error output has been rewritten, including more checks for incorrect input.
* The parser-enforced value checks have been simplified: bounds checks on individual container elements are gone, fixed size vectors are gone (but could still be obtained using min size=max size), and all remaining constraints are shown in the help output.
* Formatting checks are done on option help.  (These existed before but were not run due to a bug.)
* `MAKE_CREATABLE_FROM_YAML` macro for non-factory stuff as discussed elsewhere.
* A "forwarding" form for `MAKE_CREATABLE_FROM_YAML` to allow parsing simple types without using full option parsing (e.g., parsing an old-style Point class as `Center: [1, 2, 3]` or an enum as `Norm: L2`).
* Constructors called from Factory and MCFY now take an `OptionContext` parameter that can be passed to the `PARSE_ERROR` macro to include information about the input file location in an error message (generally for doing more complex checks on input values).
* `OptionsList` in factory/MCFY classes has been renamed to `options` because it should be camel case and it isn't a list in MCFY forwarding.
* Added `Options<...>::apply

I've put some examples of parsing error output at http://astro.cornell.edu/~wthrowe/parsing_errors (executable at http://astro.cornell.edu/~wthrowe/parsing_errors.cpp).

2017-08-04 18:02 UTC, wthrowe commented
Builds are failing because yaml-cpp is too old.  The latest release can't handle non-copyable types.  We need something more recent than November 2016.

2017-08-04 18:03 UTC, nilsdeppe commented
Okay, I can update the container we run on Travis

2017-08-04 18:17 UTC, wthrowe commented
I've prepared a commit documenting the yaml-cpp version requirement, but I'll hold off pushing until it can trigger a Travis run with the update.

2017-08-07 15:47 UTC, nilsdeppe commented on src/Options/Options.hpp
> +/// file parsing errors.
Could you add a brief explanation of what `YAML::Mark` is used for or link to the yaml-cpp documentation? The yaml-cpp documentation is not exactly super complete or easy to navigate. If I understand correctly, `YAML::Mark` used to store the line and column in the file where a parsing error occurred?

2017-08-07 21:59 UTC, nilsdeppe requested changes

2017-08-07 21:59 UTC, nilsdeppe commented on src/Utilities/ConstantExpressions.hpp
> -SPECTRE_ALWAYS_INLINE constexpr size_t cstring_length(const char* str) {
Can the place that caused the error use a `std::string` instead which actually supports these features?

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +/// Defined classes and functions that handle parsing of input parameters.
"Defines"

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +inline std::ostream& operator<<(std::ostream& s, const OptionContext& c) {
blank line

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  Option_t() = delete;
add comment saying we don't want a default constructor

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  Option_t(YAML::Node node, OptionContext context = OptionContext())
explicit

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  Option_t(OptionContext context) : context_(std::move(context)) {}
explicit

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  const YAML::Node& Node() const { return node_; }
noexcept

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  const YAML::Node& Node() const { return node_; }
lower case first letter

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +/// \code
Could we use snippets from the tests to replace this code block?

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +/// \details Options is templated on OptionsList, which must be a
`OptionsList`

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  void parse(const std::string& options);
blank line

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +                                   const OptionContext& context) const;
indentation

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  inline typename T::type get_default() const {
remove redundant inlines

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  void check_upper_bound_on_size(const typename T::type& /*t*/,
`constexpr` empty functions

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  for (auto it = options.begin(); it != options.end(); ++it) {
range-based for loop

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +    parsed_options_.emplace(std::make_pair(key, value));
don't need `make_pair`

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +}
`// namespace Options_details`

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  const auto size = t.end() - t.begin();
use `t.size()` if possible

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  const auto size = t.end() - t.begin();
`t.size()`

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  if (static_cast<size_t>(size) > T::upper_bound_on_size()) {
Then remove static_cast

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/Options.hpp
> +}
`// namespace YAML`

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/OptionsDetails.hpp
> +template <typename S, typename U = void>
`U = void` -> `= cpp17::void_t<>`

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/OptionsDetails.hpp
> +    ss << "  " << std::setw(max_label_size_) << std::left << T::label
look at `setw` things

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/OptionsDetails.hpp
> +  value_type value{};
blank line above

2017-08-07 21:59 UTC, nilsdeppe commented on src/Options/OptionsDetails.hpp
> +template <typename T>
move to `TypeTraits.hpp`

2017-08-07 21:59 UTC, nilsdeppe commented on tests/Unit/Options/Test_Options.cpp
> +  const std::string yaml = "Defaulted: 20";
inline short strings

2017-08-07 22:39 UTC, nilsdeppe requested changes

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +///  static std::string class_id() { return "BaseClass"; }
Could experiment with using `pretty_type` to replace `class_id()`

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +/// and a type \code
`\code` to next line

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +/// from Factory<BaseClass> and define a static method \code
`\code` on next line

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +/// 3) define a type options as a typelist of option structs required
define a type alias `options`

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +      typename CreateLs,
`CreateLs` to `CreateList`

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +      typename CreateLs,
`CreateLs`

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +template <typename CreateLs,
`CreateLs`

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +  if (derived) {
`derived != nullptr` for clarity

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +      ss << std::setw(0) << "\n" << std::setw(help_col - 1) << "";
Don't need to `setw(0)`

2017-08-07 22:39 UTC, nilsdeppe commented on src/Options/Factory.hpp
> +}
`// namespace YAML`

2017-08-07 22:39 UTC, nilsdeppe commented on tests/Unit/Options/Test_Factory.cpp
> +struct OptionsVecArg {
clean up

2017-08-08 00:03 UTC, kidder requested changes

2017-08-08 00:03 UTC, kidder commented on src/Options/Options.hpp
> +                "Cannot set an lower bound for a bool.");
an -> a

2017-08-10 20:40 UTC, wthrowe commented
The new commits fall into a few groups:
1. Minor fixes, largely based on above comments
2. Removing class_id and option labels in favor of using the name of the class/struct.  Assuming we don't run into any issues with compiler/library support, I think the class_id changes are a clear win.  The option label changes sometimes force you to name option structs in ways that may conflict with other names.  This can be avoided by wrapping options in an additional struct, so I think we're still OK, but the change is not completely downside free.
3. Redesigning MAKE_CREATABLE_FROM_YAML, since in trying to write an example I found some serious problems with the previous version.  (This does mean that `T::options` is always a typelist again, so it can be changed back to `T::options_list` if anyone cares.)

There was discussion of adding support for giving the option parser a small set of values allowed for an option.  There is currently support for adding parsability to an enum (see example on MCFY) and for providing parsing errors from factory class constructors.  The only additional feature that I think the parser could add would be displaying options in the help text, but we're trying to keep that short so I'm kind of leery of printing arbitrary lists of values there.

2017-08-10 21:08 UTC, wthrowe commented
And looks like yaml-cpp is broken on the clang Travis setups.

2017-08-10 21:28 UTC, wthrowe commented
Trying to clean up the doxygen warnings, I've hit two issues:
1. It looks like doxygen doesn't understand `decltype(auto)` return type.
2. One of the corrected `\snippet` lines is over 80 characters, and doxygen doesn't allow the line to be broken.  I guess we just have to use short tag names in files with long names?

2017-08-11 01:37 UTC, kidder requested changes

2017-08-11 01:37 UTC, kidder commented on src/Options/Options.hpp
> +  /// Convert to an object ot type `T`.
ot -> of

2017-08-11 01:37 UTC, kidder commented on src/Options/Options.hpp
> +  for (const auto& kv : node) {
while I've used kv for the range-based key-value pair, others  (  @gsb76 , @osheamonn ) have voiced other opinions

2017-08-11 01:37 UTC, kidder commented on src/Utilities/PrettyType.hpp
> +std::string extract_base_name(std::string name);
I cannot think of an alternative at the moment, but when I first saw base_name I thought about the name of a base class...

2017-08-11 01:37 UTC, kidder commented on src/Options/Factory.hpp
> +/// 1) define static OptionString_t help containing class-specfic help
doxygen does have a syntax for [enumerated list](https://www.stack.nl/~dimitri/doxygen/manual/lists.html) (having to relabel the comments made me think of this...)

2017-08-11 01:37 UTC, kidder commented on src/Options/MakeCreatableFromYaml.hpp
> +/// instead.
merge to previous line?

2017-08-11 01:37 UTC, kidder commented on src/Options/MakeCreatableFromYaml.hpp
> +/// it must additionally declare a tnpl::list of Options-style option
tnpl -> tmpl

2017-08-11 03:01 UTC, wthrowe commented
Speculation on the Travis yaml-cpp problem: using a libstdc++-linked yaml-cpp for a libc++ build.

2017-08-11 03:25 UTC, nilsdeppe commented
Yes, that is what it is.

2017-08-23 21:45 UTC, kidder requested changes

2017-08-23 21:45 UTC, kidder commented on src/Options/Options.hpp
> +  /// Parse an file containing options
Parse a

2017-08-23 21:45 UTC, kidder commented on src/Options/Options.hpp
> +  /// Check for an iterable type that the size is above the upper bound
above -> below

2017-08-23 21:45 UTC, kidder commented on src/Options/Options.hpp
> +  /// \tparam T the option "type"
"type" -> something clearer

2017-08-23 21:45 UTC, kidder commented on src/Options/Options.hpp
> +  /// \tparam T the option "type"
ditto

2017-08-23 21:45 UTC, kidder commented on src/Options/Options.hpp
> +template <typename OptionsList>
OptionsList -> OptionList

2017-08-23 21:45 UTC, kidder commented on tests/Unit/Options/Test_Options.cpp
> +
test that a out-of-bounds default fails

2017-09-01 18:52 UTC, nilsdeppe requested changes
squash

2017-09-01 18:52 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  /// Check for an that the size is not smaller than the lower bound
`Check that the....`

2017-09-01 18:52 UTC, nilsdeppe commented on src/Options/Options.hpp
> +  /// Check for an that the size is not larger than the upper bound
again

2017-09-01 18:52 UTC, nilsdeppe commented on src/Options/Options.hpp
>              std::enable_if_t<Options_details::has_default<T>::value>* = nullptr>
Change all to `Requires<...> = nullptr`

2017-09-04 19:56 UTC, kidder commented
Will, can you rebase on the latest commit that attempted to fix Travis stuff

2017-09-05 19:39 UTC, nilsdeppe commented
I'll look at what the heck Travis is doing

2017-09-07 13:37 UTC, nilsdeppe commented
Could you rebase to get the new Travis things that uses libstdc++ with Clang?

2017-09-08 12:44 UTC, nilsdeppe commented
@wthrowe could you try applying the changes in this commit https://github.com/nilsdeppe/spectre/commit/0dfcc1563353219b7debcc59a31dd3d905249ece ?

2017-09-08 16:34 UTC, nilsdeppe approved these changes

2017-09-08 17:25 UTC, kidder approved these changes

2017-09-08 17:25 UTC, merged