Factor Minmod tests into TCI tests and limiter tests
sxs-collaboration/spectre pull request #1433
Opened 2019-03-14 22:54 UTC by fmahebert

## Proposed changes

Portions of the (old) tests that were doing detailed tests of "when and how" the limiter triggered are not grouped as tests of the TCI. Portions dealing with the packaging of neighbor data, the interaction of multiple tensors to limit, etc, remain as tests of the limiter.

Also groups remaining Minmod TEST_CASES for faster testing on clusters.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-03-22 18:16 UTC, wthrowe requested changes

2019-03-22 18:16 UTC, wthrowe commented on tests/Unit/Evolution/DiscontinuousGalerkin/SlopeLimiters/Test_MinmodTci.cpp
> +      &free);
This is a test.  Unless it *really* slows things down just do the extra `VolumeDim` allocations and avoid the 15 lines of pointer-heavy code.

2019-03-22 18:16 UTC, wthrowe commented on tests/Unit/Evolution/DiscontinuousGalerkin/SlopeLimiters/Test_MinmodTci.cpp
> +  // Compute the slice indices once since this is (surprisingly) expensive
You only use this once, so I'm not sure what this comment is about.

2019-03-22 18:16 UTC, wthrowe commented on tests/Unit/Evolution/DiscontinuousGalerkin/SlopeLimiters/Test_MinmodTci.cpp
> +    const SlopeLimiters::MinmodType& minmod_type, double tvbm_constant,
`const double`

2019-03-22 19:02 UTC, fmahebert commented
Thanks for taking a look @wthrowe, fixups are posted.

2019-03-24 01:09 UTC, kidder submitted a review, later dismissed

2019-03-24 01:10 UTC, kidder commented
@fmahebert IWYU isn't happy

2019-03-24 23:02 UTC, fmahebert commented
Test failure looks like #1392

2019-03-26 13:41 UTC, nilsdeppe reviewed
I'm fine with this. @wthrowe  could you please look at it when you get a chance? Thank you! :)

2019-03-26 17:17 UTC, wthrowe commented
Looks fine.  Squash.

2019-03-26 18:48 UTC, fmahebert commented
Squashed and rebased

2019-03-26 18:55 UTC, wthrowe approved these changes

2019-03-26 19:18 UTC, kidder approved these changes

2019-03-30 11:50 UTC, nilsdeppe approved these changes

2019-03-30 11:50 UTC, merged