fill in name of wrapped tag in prefix dt's name
sxs-collaboration/spectre pull request #1438
Opened 2019-03-18 07:31 UTC by prayush

## Proposed changes

Change output of member function `name` for the prefix tag `dt`, to include the name of the tag that `dt` wraps.

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-03-18 07:40 UTC, nilsvu submitted a review, later dismissed

2019-03-18 14:11 UTC, geoffrey4444 submitted a review, later dismissed

2019-03-19 10:55 UTC, nilsdeppe requested changes
We should add a test for this

2019-03-20 03:09 UTC, prayush commented
> We should add a test for this

Added

2019-03-20 08:39 UTC, nilsvu requested changes

2019-03-20 08:39 UTC, nilsleiffischer commented on tests/Unit/DataStructures/DataBox/Test_DataBoxPrefixes.cpp
> +  /// [next_name]
Remove this line. Also, squash both commits into one please.

2019-03-20 17:49 UTC, nilsdeppe approved these changes

2019-03-24 01:04 UTC, kidder commented
@nilsleiffischer this has been updated

2019-03-24 12:09 UTC, nilsvu approved these changes

2019-03-24 16:39 UTC, merged