Add wrapper that applies minmod TCI to an entire Variables
sxs-collaboration/spectre pull request #1439
Opened 2019-03-19 00:40 UTC by fmahebert

## Proposed changes

Adds a wrapper checks whether the minmod TCI triggers for any component of the Variables, which can be used to trigger WENO or other more sophisticated limiters.

Depends on #1433  

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-03-19 05:01 UTC, fmahebert commented on src/Evolution/DiscontinuousGalerkin/SlopeLimiters/MinmodTci.hpp
> +// neighbor, as in SlopeLimiters::Minmod.
I should document what types these are expected to have, in addition to the names given now.

2019-03-19 05:01 UTC, fmahebert commented on src/Evolution/DiscontinuousGalerkin/SlopeLimiters/MinmodTci.hpp
> +}
These three helper functions (`allocate_buffers`, `compute_effective_neighbor_sizes`, `compute_effective_neighbor_means`) don't need to be in the MinmodTci file. I will move them into a MinmodHelpers file, for a cleaner organization.

2019-03-21 08:08 UTC, fmahebert commented
I've force-pushed some adjustments as new commits, because no one had looked at this yet. This PR is ready to review.

2019-03-21 22:55 UTC, fmahebert commented
Updated with new interface (originally: check a variables; now: check tensors).

Now actually ready to review :slightly_smiling_face:

2019-03-26 14:04 UTC, nilsdeppe requested changes
I just have one request of adding another couple tests

2019-03-26 14:04 UTC, nilsdeppe commented on tests/Unit/Evolution/DiscontinuousGalerkin/SlopeLimiters/Test_MinmodTci.cpp
> +  // Case where the vector triggers limiting
It would be good to test that any of the 3 components of the vector cause the limiter to trigger

2019-03-29 20:02 UTC, fmahebert commented
- rebased
- made some small improvements to the includes (was led astray by IWYU) that I squashed
- added new commit with tiny improvement, removing an unneeded copy of some data
- added the requested test as a fixup

2019-03-30 11:55 UTC, nilsdeppe commented
Could you please rebase this now that the dependencies have been merged?

2019-03-30 16:59 UTC, fmahebert commented
Rebased

2019-04-04 16:58 UTC, nilsdeppe reviewed
:+1: go ahead and squash :)

2019-04-04 17:13 UTC, fmahebert commented
Rebased and squashed

2019-04-04 17:16 UTC, nilsdeppe approved these changes

2019-04-19 20:32 UTC, kidder approved these changes

2019-04-19 20:32 UTC, merged