Add test ensuring that two surface integral methods are equivalent.
sxs-collaboration/spectre pull request #1453
Opened 2019-03-25 20:08 UTC by markscheel

These two methods are derived by considering a conservation law
expressed using coordinate integrals (which explicitly include
factors of sqrt(g)) and considering the same conservation law
expressed using integrals over volume forms.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-03-26 03:56 UTC, fmahebert reviewed
Small suggestions on the documentation

2019-03-26 03:56 UTC, fmahebert commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +// and where euclidean_area_element is passed into surface_integral_of_scalar.
Define g (spacetime metric?), and perhaps (I don't feel strongly) also define J^i (a flux through the surface?)

2019-03-26 03:56 UTC, fmahebert commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +// This tests that P=Q for an arbitrary 3-vector J^i.
Very minor, feel free to ignore: the comment uses P vs. Q, but the code uses 1 vs. 2. Can these be made consistent? For example, by changing P to "I1" and Q to "I2", or whatever else you prefer.

2019-03-26 03:56 UTC, fmahebert commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +  for(size_t i=0;i<3;++i) {
clang-format is needed here

2019-03-26 03:56 UTC, fmahebert commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +  // Check that this still works for a surface inside and outside the horizon
"this still works" -> "the two expressions giving the surface integral are still equal" or some rephrasing that increases clarity.

2019-03-26 03:56 UTC, fmahebert commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
>  SPECTRE_TEST_CASE("Unit.ApparentHorizons.StrahlkorperGr.SurfaceInteralOfScalar",
Consider adding a new commit that fixes the typo ("Interal") in this test name.

2019-04-01 10:19 UTC, hrueter requested changes
group review by @hrueter (main) , @nilsleiffischer

2019-04-01 10:19 UTC, hrueter commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +// normalized with the 3 metric s_i s_j \gamma^{ij} = 1, and where
spatial metric

2019-04-01 10:19 UTC, hrueter commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +template <typename Solution, typename Fr>
`Fr` -> `Frame`

2019-04-01 10:19 UTC, hrueter commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +  auto normal_one_form_curved = normal_one_form;
`unit_normal_one_form_flat` and `unit_normal_one_form_curved`

2019-04-01 10:19 UTC, hrueter commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +        sqrt(get<>(normal_one_form_euclidean_magnitude));
`get` without `<>`

2019-04-02 21:49 UTC, fmahebert commented
LGTM, I am happy for a squash once @hrueter is ready.

2019-04-08 21:47 UTC, kidder commented
@hrueter can you confirm if you are happy with the fixup

2019-04-09 08:45 UTC, hrueter submitted a review, later dismissed

2019-04-09 08:46 UTC, hrueter commented
We are happy with the fixup.

2019-04-19 20:46 UTC, kidder reviewed
@markscheel I think this just needs to be squashed and it can be merged...

2019-05-22 17:08 UTC, hrueter approved these changes

2019-05-22 17:16 UTC, fmahebert approved these changes

2019-05-24 14:32 UTC, nilsdeppe approved these changes

2019-05-24 14:32 UTC, merged