Compute items for Lapse, Shift and InverseSpacetimeMetric
sxs-collaboration/spectre pull request #1470
Opened 2019-04-03 19:03 UTC by prayush

## Proposed changes

Adds compute tags for Lapse, Shift and InverseSpacetimeMetric. This PR includes changes added in #1468 and #1469 as the first two commits. Therefore, please review the **most recent** commit only.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-04-07 02:41 UTC, carmaza commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeSpacetimeQuantities.cpp
> +  CHECK(gr::Tags::InverseSpacetimeMetric<3, Frame::Inertial,
`gr::Tags::InverseSpacetimeMetricCompute`

2019-04-23 04:08 UTC, carmaza reviewed
You can squash the fixup!

2019-04-24 19:07 UTC, carmaza submitted a review, later dismissed

2019-05-17 14:06 UTC, geoffrey4444 requested changes
I suggest updating the documentation to agree with #1494 , though I'm happy to approve even if we decide to do the documentation change later.

Other than that, please rebase (the dependent commits are now merged) and make sure Travis is happy. Then I'm happy to approve.

2019-05-17 14:06 UTC, geoffrey4444 commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
> + * \brief Compute item for inverse spacetime metric \f$\psi^{ab}\f$
We are standardizing to \f$g^{ab}\f$ for inverses spacetime metric, \f$\alpha\f$ for lapse, and \f$\beta\f$ for shift. Might as well make this PR consistent with that. See #1494

2019-05-17 14:06 UTC, geoffrey4444 commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
> + * \f$\psi_{ab}\f$ and the inverse spatial metric \f$g^{ij}\f$.
#1494 : inverse spatial metric is \f$\gamma^{ij}\f$

2019-05-17 16:54 UTC, prayush commented
> I suggest updating the documentation to agree with #1494 , though I'm happy to approve even if we decide to do the documentation change later.
> 
> Other than that, please rebase (the dependent commits are now merged) and make sure Travis is happy. Then I'm happy to approve.

@geoffrey4444 - Throughout `GeneralizedHarmonic`, we have used `psi` for spacetime metric and `g` for spatial metric. This needs to be altered to agree with #1494, but If I change notation in this PR, then the file this PR adds code to will have inconsistent notations. Therefore, I believe this change is best done in a single go in a different PR.

2019-05-17 18:39 UTC, prayush commented
@sxs-collaboration/spectre-core-devs - this PR is ready to be merged

2019-05-17 18:44 UTC, nilsdeppe approved these changes

2019-05-17 18:44 UTC, nilsdeppe commented
@geoffrey4444 can you please look at this and respond to @prayush? Thanks!

2019-05-17 19:07 UTC, geoffrey4444 approved these changes
I'm OK with postponing and updating all notation all at once! Just wanted to consider it and mark those places in the PR so we have a record.

2019-05-17 21:36 UTC, nilsdeppe commented
GCC6 debug timed out during backing up of cache. All tests passed.

2019-05-17 21:36 UTC, merged