Fix linking on some systems and remove unused statements
sxs-collaboration/spectre pull request #1488
Opened 2019-04-21 03:59 UTC by nilsdeppe

## Proposed changes

- Adds instantiations for some TensorExpressions related code
- Removes unused break statements in Spectral.cpp

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-04-21 04:51 UTC, kidder submitted a review, later dismissed

2019-04-21 10:44 UTC, nilsvu requested changes

2019-04-21 10:44 UTC, nilsleiffischer commented on src/DataStructures/Tensor/Expressions/TensorExpression.cpp
> +TensorIndex<0> ti_a;
In the hpp file there is a note saying that these do not need to be instantiated. What changed? Please update the documentation

2019-04-21 16:31 UTC, nilsdeppe commented
I decided that the right way to fix this is to have the variables be `static constexpr` in the header file since they technically do need to be constructed at least this way they will be inlined.

2019-04-25 14:34 UTC, nilsdeppe commented
@nilsleiffischer @kidder this should be ready now

2019-04-25 17:00 UTC, nilsvu approved these changes

2019-04-25 19:52 UTC, kidder approved these changes

2019-04-25 19:52 UTC, merged