Update GH `System` with tags needed for evolution
sxs-collaboration/spectre pull request #1497
Opened 2019-04-29 15:34 UTC by prayush

## Proposed changes

Add members to GeneralizedHarmonic's `System` struct that will be needed to evolve the system. These are used to specify evolution / gradient variables, computation of fluxes, gauge determination etc.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-05-08 14:07 UTC, nilsdeppe requested changes

2019-05-08 14:07 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/System.hpp
>  namespace brigand {
If you're going to include `tmpl` then remove this forward declaration.

2019-05-08 14:07 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/System.hpp
> +#include "DataStructures/DataBox/DataBox.hpp"
A lot of these includes are not needed. Please fix that and just add the appropriate forward declarations.

2019-05-08 14:07 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/System.hpp
> +  using extras_tag = ::Tags::Variables<
I'm not sure what you're trying to do here, but this solution seems rather sketchy to me. The reason being is that this seems to be a GH specific hack, and that's really not what we should do. We need to make design decisions that add general flexibility.

2019-05-16 21:39 UTC, geoffrey4444 approved these changes
Looks fine to me, but @nilsdeppe should take another look

2019-05-16 22:09 UTC, nilsdeppe approved these changes

2019-05-16 22:10 UTC, nilsdeppe commented
Travis failure is GCC6 debug and release timing out during backup of cache. All tests passed.

2019-05-16 22:10 UTC, merged