Fix magnetic field term in BondiMichel
sxs-collaboration/spectre pull request #1519
Opened 2019-05-08 20:09 UTC by gsb76

## Proposed changes

The magnetic field terms in the BondiMichel accretion solution do not include any mass terms, so this solution currently only works for M=1. This PR fixes that.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-05-09 01:57 UTC, kidder requested changes

2019-05-09 01:57 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/GrMhd/BondiMichel.cpp
> +  result.get(0) = mag_field_strength_factor * x.get(0) * square(mass_);
just put the `square(mass_)` factor into `mag_field_strength_factor`

2019-05-14 20:58 UTC, nilsdeppe approved these changes
Travis failure is gcc6-debug timeout during cache backing up. All tests passed

2019-05-16 19:44 UTC, kidder approved these changes

2019-05-16 19:45 UTC, kidder commented
travis timed out uploading the cache

2019-05-16 19:45 UTC, merged