Swsh filtering
sxs-collaboration/spectre pull request #1524
Opened 2019-05-14 15:25 UTC by moxcodes

## Proposed changes

Add the necessary utilities and filtering functions for filtering spin-weighted spherical harmonic based volume data. This function is needed for effective CCE evolution.

### Types of changes:

- [ ] New feature

### Component:

- [ ] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Dependencies
- [ ] #1522 
- [ ] #1523

2019-05-20 22:03 UTC, wthrowe requested changes
There is some apparently minor thing causing one of the first-stage Travis runs to fail as well.

2019-05-20 22:03 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Spectral/CMakeLists.txt
> +  Test_SwshFiltering.cpp
This change is in the wrong commit.

2019-05-20 22:03 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_ApplyMatrices.cpp
> +        CHECK(approx(imag(p)) == 0.);
The imaginary part of a real number is zero, so why not check this unconditionally and avoid the control flow?  Or use the macro from one of the PRs this is on top of.

2019-05-20 22:03 UTC, wthrowe commented on tests/Unit/Evolution/DiscontinuousGalerkin/Test_Filtering.cpp
> +void test_exponential_filter_action(const size_t min_pts, const double alpha,
What is this change for?  It looks like the function is only being called with the values that would have been chosen with the old logic.

2019-05-20 22:03 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_CoefficientTransforms.cpp
> +    // Iterable approx used for generality with complex types.
Why not `CHECK_COMPLEX_APPROX`?

2019-05-20 22:03 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Spectral/Test_SwshCoefficients.cpp
> +#include <complex>
I think this is in the wrong commit.

2019-05-20 22:03 UTC, wthrowe commented on src/NumericalAlgorithms/Spectral/SwshFiltering.hpp
> + * `exponential_half_power` (see `exponential_filter` for details on these
Can you get "exponential_filter" to link to whatever it is referring to?

2019-05-21 01:47 UTC, moxcodes commented on tests/Unit/Evolution/DiscontinuousGalerkin/Test_Filtering.cpp
> +void test_exponential_filter_action(const size_t min_pts, const double alpha,
hmm, this appears to be a git mishap, this isn't my change. I'll have to work out what went wrong in my rebasing.

2019-08-21 19:21 UTC, moxcodes commented
This PR is no longer dependent and ready for re-review.
Cheers!

2019-09-14 18:17 UTC, nilsdeppe requested changes
I'm happy for you to squash.

@wthrowe could you look at the apply matrices commit please when you get a chance? Thanks!

2019-09-14 18:17 UTC, nilsdeppe commented on tests/Unit/Evolution/DiscontinuousGalerkin/Limiters/Test_Krivodonova.cpp
> +    to_nodal_coefficients(make_not_null(&get(nodal_scalar_data_to_limit)),
I'm confused why you need `make_not_null` here when you haven't changed `to_nodal_coefficients`

2019-09-14 18:17 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearOperators/CoefficientTransforms.hpp
> +void to_modal_coefficients(gsl::not_null<ModalVectorType*> modal_coefficients,
Just make an overload then we don't need the `make_not_null` everywhere in the code...

2019-09-14 18:17 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearOperators/CoefficientTransforms.cpp
> +std::array<Matrix, Dim> make_transform_matrices(
Please stop copying `Matrix` here everywhere. We cache them partly so we can avoid this type of code. You can return a `std::array<std::cref<Matrix>, Dim>`-ish type (std::reference_wrapper<const Matrix&>)

2019-09-14 18:17 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearOperators/CoefficientTransforms.cpp
> +#define INSTANTIATE(r, data)                                       \
Is it possible to condense this a bit more with more arguments to `GENERATE_INSTANTIATIONS` and possible two macros, one for n->m and the other for m->n?

2019-09-14 18:17 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_CoefficientTransforms.cpp
> +        typename NodalVectorType::ElementType{1.0} *
For complex numbers does this actually make `1+i` or is it `1+ 0i`? If it's the latter this isn't really testing more than that it compiles with complex numbers, which is necessary but not sufficient :)

2019-09-14 18:17 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/SwshFiltering.hpp
> + * `exponential_half_power` of 8, `exponential_alpha` of 108, and `limit_l` of
I would put the SpEC CCE as a note at the end. Since only SXS members can use SpEC it won't help all that many people out in a public code, but I think it is a useful not :) It would also be good to not that these radial filter values are absurdly aggressive.

2019-09-14 18:17 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/SwshFiltering.hpp
> + * details on these parameters). Next, a sharp angular filter is applied which
What is a `sharp filter`? I sort of view this as a Heaviside filter

2019-09-14 18:17 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/SwshFiltering.hpp
> + * direction (as that is the representation for CCE evolution). If that is too
Could you add a `\warning` about whether or not there is caching and how the matrices are cached with regards to the arguments?

2019-09-14 18:17 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_CoefficientTransforms.cpp
>  #include "Utilities/Algorithm.hpp"
`Speed` -> `Speedup` in commit message

2019-09-17 01:17 UTC, wthrowe requested changes

2019-09-17 01:17 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_ApplyMatrices.cpp
>      // factor of 6 or so.
Check if this comment is still true.

2019-09-17 01:17 UTC, wthrowe commented on src/NumericalAlgorithms/LinearOperators/CoefficientTransforms.hpp
> +    Requires<not cpp17::is_same_v<ModalVectorType, ModalVector>> = nullptr>
Since there's a ModalVector/DataVector overload below, these can only be ComplexModalVector/ComplexDataVector and you don't need to template.

2019-09-17 01:17 UTC, wthrowe commented on src/NumericalAlgorithms/LinearOperators/CoefficientTransforms.hpp
> +    Requires<not cpp17::is_same_v<ModalVectorType, ModalVector>> = nullptr>
Reduce templating, as for to_modal_coefficients.

2019-09-17 01:17 UTC, wthrowe commented on src/NumericalAlgorithms/LinearOperators/ApplyMatrices.hpp
> +// @}
Move this to a different commit or drop it.  (It is the only change to this file in this commit.)

2019-09-17 20:27 UTC, moxcodes commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_ApplyMatrices.cpp
>      // factor of 6 or so.
depending on how you time, the factor might be ~5, but morally the statement still holds.

2019-09-17 20:38 UTC, moxcodes commented
fixups posted.
Cheers!

2019-09-18 17:01 UTC, wthrowe commented
Looks good.  Squash.

2019-09-18 19:04 UTC, moxcodes commented
Squashed.
Cheers!

2019-09-18 19:34 UTC, wthrowe approved these changes

2019-09-20 17:17 UTC, nilsdeppe approved these changes
Tests timed out in stage 2 so restarted.

2019-09-22 15:05 UTC, nilsdeppe commented
Travis failure is #1663

2019-09-22 15:05 UTC, merged