Make types appear explicitly in input files
sxs-collaboration/spectre pull request #1525
Opened 2019-05-14 16:04 UTC by nilsleiffischer

## Proposed changes

This PR is a follow-up to #1483, making use of the new option groups feature to add more structure to our input files. Mainly, it proposes the following change to how options for classes chosen at compile-time appear in the input file:

**Old:**
```yaml
AnalyticSolution:
  BhMass: 1.0
  ...
```

**New:**
```yaml
AnalyticSolution:
  FishboneMoncriefDisk:
    BhMass: 1.0
    ...
```

Note that this is backwards-compatible: If we choose to allow specifying the analytic solution in the input file in the future, as we do for the time stepper, for instance, then no changes to the input file are needed. On the other hand, if the user tries to change the `FishboneMoncriefDisk` to something else without the executable supporting it, a standard parse error is shown.

The reason for this change I also commented on in https://github.com/sxs-collaboration/spectre/pull/1483#issuecomment-482456502.

- [ ] Depends on #1483 

### Types of changes:

- [x] New feature

### Component:

- [x] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-05-14 21:52 UTC, fmahebert commented
I like this improvement to the human-readability of the input files :+1:

2019-05-15 18:31 UTC, wthrowe requested changes
I like these changes as well.  I just have one minor code request.  (Also Travis is failing, but I think that's because of the PR this is on top of, and I see you're working on that.)

2019-05-15 18:31 UTC, wthrowe commented on src/Options/Options.hpp
> +  return Options_detail::name<T>();
Use `name_helper` directly and get rid of the `name` detail function.  (Everything can just call `option_name`.)

2019-05-22 14:36 UTC, nilsleiffischer commented
Fixed @wthrowe. @nilsdeppe do you want to review this, since you brought up some points in #1482?

2019-05-22 15:28 UTC, nilsdeppe commented
Yes, I'll look later today or tomorrow :)

2019-05-23 14:45 UTC, nilsdeppe reviewed
LGTM, just some documentation comments :)

2019-05-23 14:45 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/Tags.hpp
> +struct AnalyticDataGroup {
I think you documented some of the other groups already, so let's document these ones too

2019-05-23 14:45 UTC, nilsdeppe commented on src/Evolution/DiscontinuousGalerkin/SlopeLimiters/Tags.hpp
> +struct SlopeLimiterGroup {
doxy

2019-05-23 14:45 UTC, nilsdeppe commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Tags.hpp
> +struct NumericalFluxGroup {
doxy?

2019-05-23 14:45 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Tags.hpp
> +struct ValenciaDivCleanGroup {
doxy?

2019-05-23 14:45 UTC, nilsdeppe commented on src/Evolution/Tags.hpp
> +struct EvolutionSystemGroup {
doxy?

2019-05-24 14:36 UTC, nilsleiffischer commented
@nilsdeppe @wthrowe could you check the fixup please?

2019-05-24 17:56 UTC, wthrowe commented
Looks good.

2019-05-24 18:16 UTC, nilsdeppe commented
fine by me

2019-05-24 19:05 UTC, kidder approved these changes

2019-05-24 19:33 UTC, nilsdeppe approved these changes

2019-05-28 08:04 UTC, nilsleiffischer commented
@wthrowe could you look at this and merge if you're happy?

2019-05-28 14:56 UTC, wthrowe approved these changes

2019-05-28 14:58 UTC, merged