Get CoordinateMap to work with time dependent maps
sxs-collaboration/spectre pull request #1538
Opened 2019-05-22 21:53 UTC by osheamonn

## Proposed changes

Fix implementation of CoordinateMap so that it works with time dependent maps. Issues were: 

- The implementation of jacobian and inverse jacobian was computing the source coords assuming a time independent map. it wasn't compiling with time dependent maps. 
- In the implementation of the inverse, the inverse is applied by applying each of the maps in the reverse order. However the time dependence of the constituent maps was being checked in the forward order, so didn't compile in the case of `CoordMap<TimeIndependent, TimeDependent>`

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-05-23 16:42 UTC, wthrowe requested changes

2019-05-23 16:42 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/Test_CoordinateMap.cpp
> +  const tnsr::I<double, 1, Frame::Logical> tnsr_double_logical{{3.2}};
Clang wants another set of `{}` here, and twice more 4 and 5 lines below.

2019-05-23 16:42 UTC, wthrowe commented on src/Domain/CoordinateMaps/CoordinateMap.hpp
> +        auto map_overload = make_overloader(
It looks like this overloader occurs twice.  Can it be factored out into a struct or overloaded functions?

2019-05-23 16:42 UTC, wthrowe commented on src/Domain/CoordinateMaps/CoordinateMap.hpp
> +              return nullptr;
I don't thing you need returns here.

2019-05-24 22:42 UTC, osheamonn commented
Added in progress label since serialization fails.

2019-05-28 15:08 UTC, wthrowe commented
I am happy with the fixups for my comments.

2019-05-28 18:08 UTC, osheamonn commented
Serialization has been sorted, removed in progress label.

2019-06-12 21:56 UTC, nilsdeppe requested changes
Group review with @kidder and @wthrowe

2019-06-12 21:56 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/CoordinateMap.hpp
> +                make_not_null(&mapped_point), map_in_loop, time, f_of_t_list,
since `f_of_t_list` is not a list but an unordered map, would you mind renaming to say `functions_of_time`?

2019-06-12 21:56 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/CoordinateMap.hpp
> +                make_not_null(&mapped_point), map_in_loop, time, f_of_t_list,
Here too, rename `f_of_t_list` please

2019-06-12 21:56 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_CoordinateMap.cpp
> +  FunctionsOfTime::PiecewisePolynomial<deriv_order> f_of_t_derived(initial_time,
Let's rename `f_of_t*` to `function_of_time*`

2019-06-12 21:56 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_CoordinateMap.cpp
> +  const std::unordered_map<std::string, FunctionOfTime&> f_of_t_list = {
Let's rename `f_of_t_list` to `functions_of_time`

2019-06-12 21:56 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_CoordinateMap.cpp
> +  test_serialization(time_dependent_map_first);
Can you also do all the above `CHECK`s with the deserialized map to make sure that nothing breaks in a subtle manner?

2019-07-09 21:52 UTC, osheamonn commented
Comments have been addressed.

2019-08-30 20:49 UTC, nilsdeppe reviewed
review with @kidder 

looks good to squash and rebase :+1:

2019-09-09 21:29 UTC, kidder commented
@wthrowe @nilsdeppe please look at

2019-09-09 22:51 UTC, wthrowe approved these changes

2019-09-10 01:03 UTC, nilsdeppe approved these changes

2019-09-10 01:03 UTC, merged