Add constant density M1 solution
sxs-collaboration/spectre pull request #1541
Opened 2019-05-23 17:26 UTC by ffoucart

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [x ] New feature

### Component:

- [x ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-05-23 17:27 UTC, ffoucart commented
@nilsdeppe @kidder : I'm pushing a trivial initial condition for the M1 code, so that we can hopefully build an evolution system next week... let me know if this looks like a reasonable implementation.

2019-05-29 13:52 UTC, nilsdeppe submitted a review, later dismissed

2019-05-29 17:47 UTC, kidder requested changes

2019-05-29 17:47 UTC, kidder commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/RadiationTransport/M1Grey/TestFunctions.py
> +# Functions for testing SmoothFlow.cpp
SmoothFlow -> ConstantM1 here and below

2019-05-29 17:51 UTC, kidder approved these changes

2019-05-29 17:53 UTC, nilsdeppe approved these changes

2019-05-30 01:08 UTC, merged