Add Python Wrapper to Access Build Info Available Before Linking
sxs-collaboration/spectre pull request #1569
Opened 2019-06-13 14:30 UTC by isaaclegred

## Proposed changes
This pull request splits the `InfoFromBuild.cpp` into two new `.cpp` files, `InfoFromBuild.cpp` and `MakeTimeInfoFromBuild.cpp` which distinguish between Information which is made available at link time, which cannot be linked into a library, and information which is available at CMake time, which can be (open for suggestions on naming improvements).  The `MakeTimeInfoFromBuild.cpp`, accessing info available after "cmaking" is then  compiled and linked into the library `Informer`, and the functions in it can then be given python wrappers which allow the cmake info to be accessed from python.   This information is important because 1: it allows python tests have access to the `unit_test_path()` function and 2:  in the future it will allow more transparency as the version of the `spectre` python modules will be available in python.  

### Types of changes:

- [ ] Bugfix
- [ x] New feature

### Component:

- [ x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-06-17 20:33 UTC, wthrowe commented
The implementation looks fine to me.

Regarding names, in SpEC we have:
* InfoAtCompile: hostname, build directory, build mode (debug or release)
* InfoAtLink: git revision, link date, executable name
* InfoAtRuntime: collects the other two and the command-line arguments

We're not storing exactly the same information in SpECTRE, but using "Compile" vs. "Link" in the file names still seems reasonable.

2019-06-19 16:35 UTC, isaaclegred commented
@wthrowe Correct me if I'm wrong, but it seems like renaming `InfoFromBuild.cpp` to `InfoAtLink.cpp` and `MakeTimeInfoFromBuild.cpp` to `InfoAtCompile.cpp` is probably the correct identification, even though as you said these don't store exactly the analogous information.

2019-06-19 16:54 UTC, wthrowe commented
Yeah, I think that's fine.

2019-06-26 16:21 UTC, isaaclegred commented
@nilsdeppe and @kidder can you take a look at this?  I feel like changing the names of these files requires changing some of the CMake infrastructure, and I'd prefer to know what you and @wthrowe think is the optimal solution to the implementation before trying to change things in places they may break from me not changing them correctly.

2019-07-03 22:49 UTC, nilsdeppe commented
Discussion with @wthrowe and @kidder:
- Use `InfoAtCompile` for CMake generated info such as the version numbers, etc.
- Use `InfoAtLink` for the other

2019-07-08 15:57 UTC, isaaclegred commented
@kidder @nilsdeppe and @wthrowe I've changed the file names in places where they appear.  The original intent was to only have a single `.hpp` file (even though there are two `.cpp` files) and I think this is probably a good idea.  I've left it named as `InfoFromBuild.hpp`, but this can be changed pretty easily.

2019-07-08 20:30 UTC, wthrowe commented
The fixup looks good to me.

2019-07-13 16:03 UTC, nilsdeppe commented
Same here! Please go ahead and squash

2019-07-15 20:09 UTC, nilsdeppe requested changes
Review with @wthrowe and @kidder

2019-07-15 20:09 UTC, nilsdeppe commented on src/Informer/Python/MakeTimeInfoFromBuild.cpp
> +// Distributed under the MIT License.
Can you please rename this file as well? Maybe `InfoAtCompile.cpp`?

2019-07-15 20:09 UTC, nilsdeppe commented on src/Informer/Python/Bindings.cpp
> +void bind_infofrombuild();
Can you rename this to `bind_info_at_compile();`?

2019-07-15 20:09 UTC, nilsdeppe commented on tests/Unit/Informer/CMakeLists.txt
> +  "unit;Informer;python")
can you make the capitalization here consistent? We seem to be capitalizing the first letter up above (line 14)

2019-07-15 20:09 UTC, nilsdeppe commented on tests/Unit/Informer/Test_MakeTimeInfoFromBuild.py
> +# Distributed under the MIT License.
Can you rename this file as well?

2019-07-15 20:09 UTC, nilsdeppe commented on tests/Unit/Informer/Test_MakeTimeInfoFromBuild.py
> +        self.assertEqual(Info.unit_test_path()[-12:], '/tests/Unit/')
Could you add a comment about that the twelve is` 5 + 4 + 3` in terms of `tests/unit` things?

2019-07-16 20:53 UTC, nilsdeppe approved these changes
@wthrowe @kidder could you take a quick look at this please when you get a chance? Thanks!

2019-07-16 22:18 UTC, wthrowe approved these changes

2019-07-17 15:38 UTC, kidder approved these changes

2019-07-17 15:38 UTC, merged