Remove StrahlkorperGr::unit_normal_one_form()
sxs-collaboration/spectre pull request #1571
Opened 2019-06-13 18:08 UTC by geoffrey4444

## Proposed changes

StrahlkorperGr::unit_normal_one_form() simply divides a one form by its magnitude, but DataStructures/Tensor/EagerMath/DivideBy.hpp does the same thing more generically.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-06-17 20:48 UTC, wthrowe commented
My interpretation of the relevant comments on #1322 (so people don't have to dig through the unrelated comments there): The discussion has not established a clear consensus about whether to
1. leave code as is, with `StrahlkorperGr::unit_normal_one_form`
2. move `unit_normal_one_form` somewhere else (possibly with a rename/generalization)
3. switch to `divide_by`
4. remove both and use explicit loops

2019-06-17 21:34 UTC, kidder commented
On the spectre slack channel, I suggested to go with 4) remove both and use explicit loops

2019-08-19 14:41 UTC, nilsdeppe requested changes
This shouldn't use `divide_by`

2019-11-24 16:22 UTC, nilsdeppe commented
@geoffrey4444 are you working on this or should we close it?

2019-11-24 23:58 UTC, geoffrey4444 commented
I got sidetracked, and I'm not actively working on this. Is it a priority, or can we just close it? I'm fine either way

2019-11-25 00:24 UTC, nilsdeppe commented
`divide_by` has been removed, so everything could be switched to explicit loops, but I'm fine leaving this in

2020-08-26 16:27 UTC, nilsdeppe commented
@geoffrey4444 ping on this PR

2020-09-03 16:26 UTC, closed without merging