Add TerminatePhase action
sxs-collaboration/spectre pull request #1576
Opened 2019-06-14 20:21 UTC by nilsleiffischer

## Proposed changes

We'll need this action to terminate the initialisation phase once it is composed of individual actions (see #1575).

I also add a commit in this PR that uses it for the `RegisterWithObservers` phase so that more registering actions can be done in that phase. An example is registering with the upcoming numeric data importer.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-06-14 20:34 UTC, nilsdeppe requested changes
One small request

2019-06-14 20:34 UTC, nilsdeppe commented on src/Parallel/Actions/TerminatePhase.hpp
> +// Distributed under the MIT License.
There's also a `GotoAction.hpp` that's just in `src/Parallel/`. I'm fine with either having the `Actions` subdir or having the actions just in `src/Parallel` (though the `Actions` is more consistent). Would you mind moving the `Goto` header into the `Actions` directory?

2019-06-15 14:06 UTC, kidder submitted a review, later dismissed

2019-06-15 15:56 UTC, nilsdeppe submitted a review, later dismissed
Thanks for moving the `GoTo` action! :)

2019-06-15 23:26 UTC, kidder commented
@nilsleiffischer one of the tests is failing all builds...

2019-06-16 15:13 UTC, kidder approved these changes

2019-06-16 15:28 UTC, nilsdeppe approved these changes

2019-06-16 15:28 UTC, merged