Observe MassFlux in EvolveValenciaDivClean
sxs-collaboration/spectre pull request #1585
Opened 2019-06-25 19:01 UTC by markscheel

## Proposed changes

Adds observation of mass flux in the ValenciaDivClean executable, plus other Actions/Events/Components to make this work.

Several commits:
 - Allow tags to be preprocessed before being sent to constructors (changes to Main.hpp including bugfix by @nilsdeppe, which give a handle for ParallelComponents to process Options.  In my case I need it for passing Domain into a component constructor, when DomainCreator is the thing returned by Options)
 - InitializeInterpolationTarget: preprocess option tags.  (uses functionality in previous commit to get Domain into the DataBox).
 - Add RegisterElementWithInterpolator.  New Action.
 - Add RegisterTargetWithObserver. New Action. Before PDALs, this was part of execute_next_phase.
 - Add intrp::Events::Interpolate. New Event.
 - PDALs changes to Interpolator and InterpolationTarget ParallelComponents.
 - EvolveValenciaDivClean: now observe mass flux.

      

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-06-26 03:00 UTC, markscheel commented
Tests failed before because I hadn't rebased onto develop. I did so, and fixed what didn't compile.

2019-06-26 18:00 UTC, markscheel commented
clang-format change only.

2019-08-01 20:36 UTC, markscheel commented
Rebased.

I separated 3 of the commits here into separate PRs that must be merged first, before this one.

2020-02-24 22:23 UTC, kidder requested changes

2020-02-24 22:23 UTC, kidder commented on src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
> +  using compute_items_on_target = tmpl::append<
tmpl::push_front<list,A,B>

2020-03-05 21:08 UTC, kidder commented
I am happy for you to squash if @nilsdeppe is

2020-03-05 22:44 UTC, nilsdeppe reviewed
I'm happy for you to squash

2020-03-05 22:44 UTC, nilsdeppe commented on src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
> +  ApparentHorizons
These aren't needed for all the executables

2020-03-06 21:45 UTC, markscheel commented on src/Evolution/Executables/GrMhd/ValenciaDivClean/CMakeLists.txt
> +  ApparentHorizons
So I should just remove them?  Does cmake link them through another mechanism?

2020-03-09 18:30 UTC, markscheel commented
Squashed, and added another commit changing AddSpectreExecutable.cmake

2020-03-09 18:34 UTC, nilsdeppe approved these changes
![image](https://user-images.githubusercontent.com/13531030/76245892-1980e600-6213-11ea-88cd-1b282afc1d04.png)

2020-03-09 18:46 UTC, kidder approved these changes

2020-03-10 15:58 UTC, merged