Use .clang-format style for git-clang-format
sxs-collaboration/spectre pull request #1618
Opened 2019-07-19 16:10 UTC by nilsleiffischer

## Proposed changes

I occasionally had git-clang-format report differences when committing, although I ran clang-format over the code. I think that's because git-clang-format wasn't set up to use the `.clang-format` style file. Perhaps this fixes that issue.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-09-16 17:51 UTC, kidder commented
I would happier if you were confident this fixed your issue...

2019-09-19 17:11 UTC, geoffrey4444 approved these changes

2019-09-20 21:34 UTC, nilsdeppe requested changes
@wthrowe @kidder and @nilsdeppe all agree that being confident this does what you want it to would be valuable...

2019-09-27 13:19 UTC, geoffrey4444 approved these changes

2019-11-01 20:44 UTC, kidder commented
reopen when you can reproduce the problem (in person conversation with @nilsleiffischer )

2019-11-01 20:44 UTC, closed without merging