Make 'parse' an explicit input file test
sxs-collaboration/spectre pull request #1628
Opened 2019-07-24 22:12 UTC by nilsdeppe

## Proposed changes

Rather than implicitly adding `parse` to all input file checks, require they be added explicitly. This is an issue for PR #1611 

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-07-24 22:52 UTC, wthrowe commented
I am opposed to this change.  Any program that takes an input file should be able to verify that input file.

2019-07-25 00:56 UTC, kidder submitted a review, later dismissed

2019-07-25 05:54 UTC, nilsvu submitted a review, later dismissed

2019-07-25 13:16 UTC, nilsdeppe commented
@wthrowe would you be okay with CMake checking and hitting an error if `parse` is not present? Then a descriptive message can be printed to clarify what the check does. This would remove the magic while still requiring programs can perform a (hopefully cheap) check of the input file.

2019-07-25 15:36 UTC, wthrowe commented
Yes, I would be fine with requiring it to be explicitly listed as long as the build system still makes sure it is there.

2019-10-07 18:01 UTC, kidder commented
marking this as `in_progress` until it is updated

2019-11-23 20:04 UTC, nilsdeppe commented
@wthrowe I pushed a fixup commit where CMake checks that `parse` is specified and gives a (hopefully useful) error messages if it is not.

2019-11-25 18:55 UTC, wthrowe requested changes
Looks fine.  Squash.

2019-11-25 18:55 UTC, wthrowe commented on cmake/AddInputFileTests.cmake
> +        " should check that the input file parses correctly at that"
at -> and

2019-11-25 19:06 UTC, nilsdeppe commented
Okay, squashed and rebased on develop. Thanks @wthrowe !

2019-11-25 19:53 UTC, kidder approved these changes

2019-11-26 02:41 UTC, wthrowe approved these changes

2019-12-02 19:22 UTC, kidder commented
ignoring travis timeouts

2019-12-02 19:22 UTC, merged