Add step controllers
sxs-collaboration/spectre pull request #164
Opened 2017-08-23 18:44 UTC by wthrowe

2017-08-23 19:26 UTC, osheamonn commented on src/Time/StepControllers/StepController.hpp
> +namespace StepControllers {}
Merge with line 16

2017-08-23 19:26 UTC, osheamonn commented on src/Time/StepControllers/StepController.hpp
> +
Add to TimeSteppers doxygen group, or later create StepControllers doxygen group.

2017-08-23 19:26 UTC, osheamonn commented on src/Time/StepControllers/FullSlab.hpp
> +/// A StepController that always chooses to step a full slab,
Add comment explaining that this is to be used for global timestepping.

2017-08-23 19:26 UTC, osheamonn commented on src/Time/StepControllers/SplitRemaining.hpp
> +/// A StepController that chooses steps to be 1/n of the remander of the slab.
remander -> remainder

2017-08-23 19:26 UTC, osheamonn commented on src/Time/StepControllers/SplitRemaining.hpp
> +  //     "Chooses steps by dividing the reminder of the slab evenly.\n"
reminder -> remainder

2017-08-23 19:26 UTC, osheamonn commented on src/Time/StepControllers/SimpleTimes.hpp
> +/// A StepController roughly splits the remaining time, but prefers simpler
"A StepController `which` roughly"

2017-08-23 19:26 UTC, osheamonn commented on src/Time/StepControllers/SimpleTimes.hpp
> +    const auto max_magnitude = [](const double& a, const double& b) {
max_magnitude seems like something which is generally useful and we would want.

2017-08-23 20:04 UTC, kidder commented on src/Utilities/FractionUtilities.hpp
> +template <typename Fraction, typename T1, typename T2>
doxygen

2017-08-31 15:05 UTC, wthrowe commented
The Travis OSX failure is due to Boost rewriting rational.  I'll work on a fix.

2017-09-01 19:07 UTC, nilsdeppe requested changes
squash

2017-09-01 19:07 UTC, nilsdeppe commented on src/Utilities/ConstantExpressions.hpp
> +//@{
can you check if this group comment needs to go before the doxygen comment?

2017-09-01 19:07 UTC, nilsdeppe commented on src/Utilities/FractionUtilities.hpp
> +//@{
check about `//@{` placement

2017-09-01 19:07 UTC, nilsdeppe commented on src/Utilities/FractionUtilities.hpp
> +/// \brief Compute the continued fraction representation of a number
`\ingroup Utilities`

2017-09-01 19:07 UTC, nilsdeppe commented on src/Utilities/FractionUtilities.hpp
> +/// \brief Sum a continued fraction
`\ingroup Utilities`

2017-09-01 19:07 UTC, nilsdeppe commented on src/Utilities/FractionUtilities.hpp
> +/// \brief Find the fraction in the supplied interval with the
`\ingroup Utilities`

2017-09-01 21:19 UTC, wthrowe commented on src/Utilities/ConstantExpressions.hpp
> +//@{
We use both forms in the code and they both produce the desired doxygen output, so it appears to not matter.

2017-09-04 19:57 UTC, kidder commented
Probably want to rebase this as well on the Travis fixes

2017-09-06 18:07 UTC, nilsdeppe approved these changes

2017-09-06 18:07 UTC, nilsdeppe commented
The Travis issue is actually a Travis issue in the sense that they are having trouble with their macOS machines.

2017-09-06 18:07 UTC, merged