Change VolumeData tests to be more general
sxs-collaboration/spectre pull request #1642
Opened 2019-07-26 15:37 UTC by isaaclegred

## Proposed changes

This Pull makes mild improvements to the tests for the `VolumeData` class which will hopefully be useful as examples for how to efficiently use the new class in practice (given that the way the data is written in order to maximize efficiency, at the cost, perhaps, of intuitive data layout).  I also hope this pull request will generate some discussion and I'm looking for comments on suggested improvements to the logic involved in checking the data.  

### Types of changes:

- [ ] Bugfix
- [ x] New feature

### Component:

- [ x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-09-02 15:09 UTC, nilsdeppe requested changes
I'm happy for you to squash immediately

2019-09-02 15:09 UTC, nilsdeppe commented on tests/Unit/IO/Observers/Test_VolumeObserver.cpp
> +                                          1, std::multiplies<>{}));
I believe moving the `static_cast<size_t>` around the `1` is better since then internally `size_t`s will be used everywhere

2019-09-02 15:09 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +#include <iostream>
can you please remove this include?

2019-09-02 15:09 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +    const auto read_grid_names = volume_file.get_grid_names(observation_id);
You can sort the read grid and the expected grid, then compare them. That would be much easier to digest:
```cpp
auto read_grid_names = ...;
std::sort(read_grid_names.begin(), read_grid_names.end(), std::less<std::string>{});
CHECK(read_grid_names == grid_names);
```
where I'm assuming you have done the same sort on `grid_names` earlier.

I think it would be clearer to separate out the code that builds up the map from `read` -> `expected` separately from checking the grid names. I would suggest doing the grid names by sorting and separately build up this map if you still need it.

2019-09-02 15:09 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +    auto accumulate_extents = [](std::vector<size_t> grid_extents) {
`const auto acc...` and `const std::vector<size_t>&`

2019-09-02 15:09 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +    auto read_points_by_element = [&element_num_points]() {
can this be `const auto`?

2019-09-02 15:09 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +    // Given a datavector, corresponding to contiguous data read out of a
`datavector` -> `DataVector`

2019-09-02 15:09 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +                                   DataVector all_data,
I believe this better be `DataVector&`, as it stands I don't know how this is actually working...

2019-09-02 15:09 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +      const auto component = expected_components[i];
`const auto&`

2019-09-13 14:53 UTC, isaaclegred commented
@nilsdeppe I pushed these changes

2019-09-15 04:23 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +    const auto accumulate_extents = [](const std::vector<size_t> grid_extents) {
Still need an `&` after `std::vector<size_t>` to make it a reference

2019-09-15 04:23 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +    auto read_points_by_element = [&element_num_points]() {
Did you test this?

2019-09-15 04:24 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +                                   DataVector all_data,
ping

2019-09-16 13:20 UTC, isaaclegred commented on tests/Unit/IO/Test_VolumeData.cpp
> +                                   DataVector all_data,
@nilsdeppe I'm confused by this too, but I think it has to do with the fact that when the lambda is called it takes as it's argument the output of `volume_file.get_tensor_component`; it works if I use `DataVector&&`

2019-09-16 13:24 UTC, isaaclegred commented on tests/Unit/IO/Test_VolumeData.cpp
> +    auto read_points_by_element = [&element_num_points]() {
First time I tested this it didn't seem to work, but now everything seems to be fine with making it const

2019-09-16 14:37 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +      return DataVector(&all_data[read_points_by_element[grid_index]],
To make the hidden copy that prevents the bug we should use:
```cpp
  DataVector result(element_num_points[grid_index]);
  std::copy(&all_data[read_points_by_element[grid_index]],
            &all_data[read_points_by_element[grid_index]] +
                element_num_points[grid_index],
            result.begin());
  return result;
```

2019-09-16 17:15 UTC, isaaclegred commented
@nilsdeppe  I added the extra change and squashed the fixups

2019-09-16 17:52 UTC, nilsdeppe submitted a review, later dismissed
LGTM :+1: 

Just one note that I suspect clang-tidy will dislike some pointer math you're doing. We silence clang-tidy in these cases as follows:
```cpp
      // clang-tidy: no pointer arithmetic (we have no other option)
      std::copy(&all_data[read_points_by_element[grid_index]],
                // NOLINTNEXTLINE
                &all_data[read_points_by_element[grid_index]] +
```
where the clang-tidy comment is used to tell other devs why the `NOLINTNEXTLINE` comment is present

2019-09-16 17:52 UTC, nilsdeppe commented on tests/Unit/IO/Test_VolumeData.cpp
> +                &all_data[read_points_by_element[grid_index]] +
I suspect clang-tidy will dislike the pointer arithmetic on this line, just a heads up :)

2019-09-30 17:36 UTC, isaaclegred commented
@nilsdeppe I changed this after our previous convo but before I saw your comments, let me know if you think anything needs to be changed

2019-10-04 14:23 UTC, nilsdeppe submitted a review, later dismissed

2019-10-04 14:34 UTC, kidder requested changes

2019-10-04 14:34 UTC, kidder commented on tests/Unit/IO/Test_VolumeData.cpp
> -    const auto get_first = [&volume_file,
remove the preceeding comment

2019-10-04 14:34 UTC, kidder commented on tests/Unit/IO/Test_VolumeData.cpp
> +    {
make the scoped code a lambda `check_grid_names`

2019-10-04 14:34 UTC, kidder commented on tests/Unit/IO/Test_VolumeData.cpp
> +      size_t index = 1;
why not use a for loop?

2019-10-04 16:43 UTC, isaaclegred commented
@kidder I pushed a fixup

2019-10-04 16:57 UTC, kidder reviewed
okay, you can squash

2019-10-07 17:57 UTC, kidder approved these changes

2019-10-07 17:58 UTC, kidder commented
Travis timed out trying to update caches

2019-10-07 17:58 UTC, kidder commented
@nilsdeppe this should be ready

2019-10-07 18:09 UTC, nilsdeppe approved these changes

2019-10-07 18:09 UTC, merged