Add intrp::Events::Interpolate.
sxs-collaboration/spectre pull request #1649
Opened 2019-08-01 19:04 UTC by markscheel

## Proposed changes

This is an Event that triggers an interpolation.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-08-01 19:45 UTC, wthrowe requested changes

2019-08-01 19:45 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/Interpolate.hpp
> +    db::item_type<::Tags::Variables<tmpl::list<Tensors...>>> interp_vars(
No reason to reference the tag here.  Just use `Variables<tmpl::list<Tensors...>>`.

2019-08-01 19:45 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolateEvent.cpp
> +    Variables<tmpl::list<gr::Tags::Lapse<DataVector>>> vars{};
Make a new tag so this test doesn't depend on GR stuff.

2019-08-01 19:45 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolateEvent.cpp
> +      const typename Metavariables::temporal_id::type& temporal_id,
`db::item_type`

2019-08-01 19:45 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolateEvent.cpp
> +  // roundoff error.
You're not doing any math, so this comment doesn't apply.

2019-08-01 19:45 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolateEvent.cpp
> +      db::AddComputeTags<Tags::Time>>(
Do you need `Tags::Time`?

2019-08-01 19:45 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolateEvent.cpp
> +  auto event = std::make_unique<InterpolationEvent>(InterpolationEvent{});
No need for a pointer unless you are casting to the base class.

2019-08-01 21:46 UTC, kidder reviewed
I have nothing in addition to what @wthrowe has commented

2019-08-02 17:56 UTC, markscheel commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolateEvent.cpp
> +      db::AddComputeTags<Tags::Time>>(
Nope, not anymore. Gone now.

2019-08-02 19:13 UTC, wthrowe commented
Looks good.  Squash.

2019-08-05 19:57 UTC, wthrowe approved these changes

2019-08-08 01:14 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolateEvent.cpp
> +  std::iota(vars.data(), vars.data() + vars.size(), 1.0);
Just an FYI, a lot of the `std::` algorithms are wrapped in `Utilities/Algorithm.hpp` and `Utilities/Numeric.hpp` (mirroring the STL) and allow the simpler `alg::iota(var, 1.0);`. I'm happy to merge as is, please let me know whether or not you want to change it :)

2019-08-08 17:19 UTC, nilsdeppe approved these changes

2019-08-08 17:19 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_InterpolateEvent.cpp
> +  std::iota(vars.data(), vars.data() + vars.size(), 1.0);
Talked offline. Doesn't work since Variables doesn't have begin and end

2019-08-08 17:19 UTC, merged