Improvements to ConstGlobalCache tag lists
sxs-collaboration/spectre pull request #1676
Opened 2019-09-10 05:00 UTC by kidder

## Proposed changes

- Unify name used for tag lists
- Eliminate empty lists
- Tags from actions in phase-dependent action lists of components are collected in the metafunction that collects all ConstGlobalCache tags instead of in each component.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-09-10 22:01 UTC, nilsdeppe requested changes

2019-09-10 22:01 UTC, nilsdeppe commented on src/Parallel/ConstGlobalCache.hpp
> +///    `phase_dependent_action_list` of each `Component` of
Unsure if losing my mind, but is the indentation changing here? 4 spaces vs. 3?

2019-09-10 22:01 UTC, nilsdeppe commented on src/Parallel/ConstGlobalCache.hpp
> +///    tags that cannot be added from the following tag lists:
having the colon at the end makes it seem like the next two items should be sub-elements. Is this intended or should it just say something like `from the lists below.`?

2019-09-10 22:01 UTC, nilsdeppe commented on src/Parallel/ParallelComponentHelpers.hpp
> +struct get_const_global_cache_tags_from_parallel_struct {
What *is* a `parallel_struct`? A C++ comment would be helpful :)

2019-09-10 22:01 UTC, nilsdeppe commented on src/Parallel/ParallelComponentHelpers.hpp
> +            tmpl::bind<detail::component_const_global_cache_tags, tmpl::_1>>,
Isn't this the same as `get_const_global_cache_tags_from_parallel_struct<tmpl::_1>`?

2019-09-10 22:01 UTC, nilsdeppe commented on src/Parallel/ParallelComponentHelpers.hpp
> +using component_const_global_cache_tags =
Since all these eager metafunctions are turned into lazy metafunctions below, why not just make them lazy right away?

2019-09-10 22:01 UTC, nilsdeppe commented on docs/DevGuide/Parallelization.md
> +5. `using const_global_cache_tags` is set to a `tmpl::list` of tags
What if I want `allocate_array` to use something but I don't want it in the cache?

2019-09-10 22:01 UTC, nilsdeppe commented on docs/DevGuide/CreatingExecutables.md
> +constant global cache (by specifying tags in the
`constant global cache` -> `ConstGlobalCache`?

2019-09-12 02:27 UTC, kidder commented
@nilsdeppe fixup pushed

2019-09-12 03:27 UTC, nilsdeppe reviewed
LGTM, happy for you to squash :+1:

2019-09-12 17:19 UTC, kidder commented
@markscheel please look at

2019-09-12 18:45 UTC, markscheel requested changes
A few documentation comments.

2019-09-12 18:45 UTC, markscheel commented on docs/DevGuide/CreatingExecutables.md
> +Parallel::ConstGlobalCache (by specifying tags in the
It sounds like there are only two ways that options specified in the input file can get into the executable. But there's a 3rd way: specifying initialization_tags.

2019-09-12 18:45 UTC, markscheel commented on docs/DevGuide/Parallelization.md
> +   least one `PhaseAction`, even it if is empty, must be specified.
typo: 'it if' -> 'if it'

2019-09-12 18:45 UTC, markscheel commented on docs/DevGuide/Parallelization.md
> +   `allocate_array` function that will not create items for the
'function that will not create items for the' -> 'function; these `array_allocation_tags` will not be put in the'

2019-09-12 18:45 UTC, markscheel commented on docs/DevGuide/Parallelization.md
> +action.
I realize that this was a whitespace change only, but perhaps this should be clarified if people other than me think this is unclear. I have a few questions (for my own understanding):

1. Is the only difference between the two calls that the bad one uses `Parallel::get_parallel_component<ParallelComponent>(cache).ckLocal()` and the good one (which is not spelled out explicitly) uses `Parallel::get_parallel_component<ParallelComponent>(cache)` without the `ckLocal()`?  
2. Is the call with the `ckLocal()` executed immediately? (instead of deferred and queued)
3. Is the problem that the action is calling itself, or is it equally bad to call ActionA from ActionB using `ckLocal()` if ActionA and ActionB are in the same ParallelComponent?
4. Under what circumstances can `ckLocal()` be used legitimately?  Presumably you cannot use it to call an Action on a different ParallelComponent.

2019-09-12 20:01 UTC, kidder commented on docs/DevGuide/Parallelization.md
> +action.
1) yes; the former directly calls the local object, the latter is handled by Charm++
2) yes
3) calling any action is disallowed (this is stated on line 308 and tested in Test_AlgorithmNestedApply2.cpp)

2019-09-12 20:06 UTC, kidder commented
@markscheel I pushed a fixup and answered your questions (let me know if you want changes in the doc based on the answers)

2019-09-12 20:31 UTC, markscheel submitted a review, later dismissed
Thanks!  Please squash.

I also have questions as to the difference between `ckLocal()` and `ckLocalBranch()` (and what are legitimate usages of each) but that is getting very very tangential to this PR.

2019-09-12 22:25 UTC, kidder commented
@markscheel @nilsdeppe squashed

2019-09-12 22:26 UTC, nilsdeppe approved these changes

2019-09-13 14:50 UTC, markscheel approved these changes

2019-09-14 18:05 UTC, nilsdeppe commented
Travis GCC6 debug timed out while backing up cache in final build. All tests passed.

2019-09-14 18:05 UTC, merged