Rewrite WENO reconstruction to better match references
sxs-collaboration/spectre pull request #1678
Opened 2019-09-10 21:01 UTC by fmahebert

The old and new expressions are (should be) arithmetically equivalent, but the new
expression is a better match to many references.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-09-10 21:46 UTC, nilsdeppe requested changes
A couple variable naming suggestions. I'm happy for you to squash anything :)

2019-09-10 21:46 UTC, nilsdeppe commented on src/Evolution/DiscontinuousGalerkin/Limiters/Weno.hpp
> +        auto tag, const auto& tensor) noexcept {
Since `tensor` is a pointer, I would have found `const auto` easier to read and less redundant since we don't need pointers to pointers here :)

2019-09-10 21:46 UTC, nilsdeppe commented on src/Evolution/DiscontinuousGalerkin/Limiters/Weno.hpp
> +          DataVector& component_to_correct = get<decltype(tag)>(kv.second)[i];
I would've found this code slightly easier to parse had the naming been `nhbr_component_to_correct` and `mean_nhbr`. In the helpers file below you name them `local_mean` and `neighbor_mean`. I'm not picky about the exact wording or consistency across files, but would briefer something indicating `neighbor` in the name :)

2019-09-10 23:18 UTC, fmahebert commented
Thanks for the suggestions, @nilsdeppe. I've updated the commit, and also added a new commit to remove refs-to-ptrs in a few other places.

2019-09-11 00:45 UTC, nilsdeppe approved these changes
LGTM! :+1:

2019-09-11 21:08 UTC, kidder approved these changes

2019-09-11 21:09 UTC, merged