Automatically dereference unique_ptrs in the DataBox
sxs-collaboration/spectre pull request #1711
Opened 2019-10-06 19:35 UTC by wthrowe

The interesting stuff is in the first commit.  The fixup is changing calls to item_type and has been separated out for ease of reviewing.

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-10-07 15:57 UTC, kidder requested changes
reviewed with @nilsdeppe 
You can squash everything immediately

2019-10-07 15:57 UTC, kidder commented on tests/Unit/DataStructures/DataBox/Test_DataBox.cpp
> +    static void apply(const int& s, const int& c, const int& cm, const int& sb,
please use more descriptive variable names (here and below)

2019-10-07 22:46 UTC, wthrowe commented
Squashed, along with additional changes for changes on develop:
```patch
diff --git a/src/NumericalAlgorithms/Spectral/SwshDerivatives.hpp b/src/NumericalAlgorithms/Spectral/SwshDerivatives.hpp
index f60787d90..1d36725a6 100644
--- a/src/NumericalAlgorithms/Spectral/SwshDerivatives.hpp
+++ b/src/NumericalAlgorithms/Spectral/SwshDerivatives.hpp
@@ -197,7 +197,8 @@ struct AngularDerivativesImpl<tmpl::list<DerivativeTags...>,
           DerivativeTags>>*>... transform_of_derivative_scalars,
       const gsl::not_null<db::item_type<Tags::SwshTransform<
           DeDuplicatedDifferentiatedFromTags>>*>... transform_of_input_scalars,
-      const db::item_type<DeDuplicatedDifferentiatedFromTags>&... input_scalars,
+      const db::const_item_type<DeDuplicatedDifferentiatedFromTags>&...
+          input_scalars,
       const size_t l_max, const size_t number_of_radial_points) noexcept {
     apply_to_vectors(make_not_null(&get(*transform_of_derivative_scalars))...,
                      make_not_null(&get(*transform_of_input_scalars))...,
@@ -224,8 +225,8 @@ struct AngularDerivativesImpl<tmpl::list<DerivativeTags...>,
       const gsl::not_null<typename db::item_type<Tags::SwshTransform<
           DeDuplicatedDifferentiatedFromTags>>::type*>... transform_of_inputs,
       const gsl::not_null<
-          typename db::item_type<DerivativeTags>::type*>... derivatives,
-      const typename db::item_type<
+          typename db::const_item_type<DerivativeTags>::type*>... derivatives,
+      const typename db::const_item_type<
           DeDuplicatedDifferentiatedFromTags>::type&... inputs,
       const size_t l_max, const size_t number_of_radial_points) noexcept {
     // perform the forward transform on the minimal set of input nodal
```

2019-10-07 22:51 UTC, kidder approved these changes

2019-10-07 23:36 UTC, nilsdeppe approved these changes

2019-10-08 13:20 UTC, kidder commented
ignoring Travis timeouts

2019-10-08 13:20 UTC, merged