Add characteristic transform matrices for NewtonianEuler
sxs-collaboration/spectre pull request #1729
Opened 2019-10-19 13:10 UTC by fmahebert

## Proposed changes

Adds the matrices that transform a set of NewtonianEuler evolved/conserved fields to (or from) a set of characteristic fields.

This is a prerequisite for limiting the characteristic fields of the NewtonianEuler system.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-10-19 17:45 UTC, fmahebert commented
Test failure is #1730

2019-10-20 17:40 UTC, carmaza commented
Some clarifications prior to a review:

- The title says to/from chars, but I'm missing the transformation from.

- For everyone's clarity, please document the equations you implemented.

- It seems that this PR implements a "bad" form of the characteristics, in the sense that you need to divide by n_i to get the left eigenvectors. While I understand your attempt in the code to divide by the largest component of n in order to avoid dividing by zero, my question is: why is this better than just implementing the "good" form of the characteristics, which is valid for any normal and doesn't require to divide by n_i at all? This "good" form was worked out by @teukolsky, and implemented by myself in #636. It's also in the bitbucket branch (also mine) that you pointed me to when looking for the form of the equations.

- In #636, I attempted to merge these matrices, but that was ultimately rejected as part of the PR because, at that time, it was pointed out that they had no apparent immediate use. While a (valid) reason to not have the characteristic matrices was that, sometimes, you care about function-specific algebra that should be hard-coded for higher efficiency, it was suggested to add the matrices as a separate PR should we ever need them. My question is: why was it better to implement them from scratch rather than just having us use what was in #636 ?

2019-10-21 13:31 UTC, fmahebert commented
@carmaza:

- The function `right_eigenvectors` provides the char-to-cons transformation matrix. I see that I forgot to mention this in the documentation, so I will add it.
- Sure, will do.
- The form is only badly behaved if you divide by a normal vector component that is ~zero. But there is freedom to divide by any component (n_x, n_y, or n_z), so I make sure I do not divide by a ~zero component. As a result, the form is not badly behaved, just slightly inelegant. The reason I opt not to rotate the conserved variables into a reference frame aligned with the normal is that I want to avoid having to align/unalign the coordinates every time I use characteristic variables.
- I can't see what you originally implemented in #636 but then removed from the PR (maybe it's possible, and I just don't know how?). If you wish to open a new PR with your original code from #636 to replace this PR, I am happy with that course of action. I have no desire to step on your toes! :)

2019-10-21 13:58 UTC, teukolsky commented
The most elegant way to write the eigenvectors is to take the given normal and use it to define two tangent vectors (in 3-d) by Gram-Schmidt. There are no problematic divisions. The nice thing about this is that it works also in the GR case, and was implemented in the Bitbucket version for RelativisticEuler. So coding it that way would keep everything consistent. On the other hand, this version with dividing by the biggest n_i will work too.

By the way, the eigenvectors have not yet been coded in the current RelativisticEuler. I have even better expressions for them than in the Bitbucket version.

2019-10-21 18:25 UTC, fmahebert commented
@carmaza Did you compute the transform using the eigenvectors from Gram-Schmidt? If so, we can replace this PR with your code.

2019-10-21 21:09 UTC, carmaza commented
@fmahebert Yes, I implemented the tangent vectors and all that. However, my code only gives the transformation vars->chars, and the return type is a `std:array`.

I don't see the point of replacing a PR that is already open and fully working. For the sake of optimizing your time visiting, I'm fine with you going ahead with this PR. Don't worry about stepping on my toes.

2019-10-29 15:52 UTC, nilsdeppe requested changes

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> +Matrix left_eigenvectors(const tnsr::I<double, Dim>& velocity,
For some reason that is not at all clear to me when I render the dox I don't get the comment being applied to the `left_eigenvectors`. Can you confirm? I'm not sure what/if there is a solution.

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> + * \f$A_x = \partial F^x_j(u) / \partial u_i\f$. The indices \f$i, j\f$
I think we should use `\alpha` and `\beta` for field indices. This is what the GH and dual frames papers do.

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> + * and \f$c\f$ is the sound speed. The characteristic fields \f$c\f$ are then
You use `c` for  both the sound speed and the char fields. I've seen (and used) `w` for the char fields :man_shrugging:

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> + * \f$A\f$ as \f$\Lambda = diag(v_n, v_n, v_n, v_n - c, v_n + c)\f$. Here
Is `\diag` a thing? Since `diag` is an operator/function maybe `\mathrm` is better?

Why this ordering? I would have expected `v_n - c, v_n, v_n, v_n, v_n + c`.

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  result(2, 0) = get(specific_enthalpy) -
Toro has this equation as `V^2=v^iv_i`. Could you explain to me the reason they differ please?

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  // the denominator, as this avoids division by zero. Here we make the
[nitpick feel free to ignore] I find `as` -> `because` easier to read

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  const size_t index_of_largest = static_cast<size_t>(
since you're never using `index_of_largest` to index into a data structure you could do `const auto ... = std::dist` to avoid the cast. Up to you :)

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  const double theta = get(dot_product(velocity, velocity)) -
What is `theta`? Could you add a brief comment, even if it's just a temp.

2019-10-29 15:52 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +#ifdef SPECTRE_DEBUG
Why are the `ASSERT` inside this `ifdef`? They have this `ifdef` inside of them.

2019-10-29 15:52 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
> +      n_i /= normal_magnitude;
This could divide by zero (though likely). More of an FYI in case you want to do anything about it. Could just add a small constant to the x-component of the normal vector :)

2019-10-29 15:52 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
> +  Approx local_approx = Approx::custom().epsilon(1e-12).scale(1.0);
I think this was brought up before in a different PR, but the scale here means an absolute tolerance of `1e-12`. Is that what you want?

2019-10-29 15:52 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
> +  const Matrix a_x = blaze::DynamicMatrix<double>{
Question: Is it not possible to do `Matrix a_x{{...}, ...};`?

2019-10-29 16:24 UTC, fmahebert commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +#ifdef SPECTRE_DEBUG
Oops, this is left over from a previous iteration that had precomputations for the assertion... I will remove the `ifdefs`.

2019-10-29 16:24 UTC, fmahebert commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  result(2, 0) = get(specific_enthalpy) -
Equation number please?

2019-10-29 16:27 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  result(2, 0) = get(specific_enthalpy) -
Derp, sorry! 11.49

2019-10-29 18:03 UTC, teukolsky commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> + * and \f$c\f$ is the sound speed. The characteristic fields \f$c\f$ are then
I like cs for the sound speed. This is pretty unambiguous and looks like c_s, which is what one would type in Latex.

2019-10-29 18:07 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> + * and \f$c\f$ is the sound speed. The characteristic fields \f$c\f$ are then
since it is latex rendered documentation, I would use `c_s`

2019-10-29 18:16 UTC, teukolsky commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  result(2, 0) = get(specific_enthalpy) -
The Toro formula assumes a polytropic eqn of state. The form here holds for a general eqn of state.

2019-11-01 14:02 UTC, fmahebert commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
> +  Approx local_approx = Approx::custom().epsilon(1e-12).scale(1.0);
The "zeroes" of the identity can be up to ~1e-12 for small `specific_internal_energy`, so yes, I think this is what I want? I'm open to alternate suggestions if you think this should be done differently.

2019-11-01 14:33 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  result(2, 0) = get(specific_enthalpy) -
Okay, thank you!

2019-11-01 14:34 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
> +  Approx local_approx = Approx::custom().epsilon(1e-12).scale(1.0);
Okay, I'm not suggesting anything, just making sure that you are getting what you intended :)

2019-11-04 22:56 UTC, fmahebert commented
Fixups posted

- I've added a reference to a brief discussion about the characteristics. If anyone has a preferred reference I am happy to point to it. If we want to show the entire computation, we may need to include a latex document.
- I've not yet worked towards a decomposition of the characteristics w.r.t. the normal and tangents.

2019-11-04 22:58 UTC, fmahebert commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> +Matrix left_eigenvectors(const tnsr::I<double, Dim>& velocity,
Building locally, I do see (on the current version of this PR after fixups to your comments) the comment applying to both functions.

2019-11-05 17:33 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> +Matrix left_eigenvectors(const tnsr::I<double, Dim>& velocity,
Hmm, okay :man_shrugging: no idea why mine is being weird...

2019-11-05 17:34 UTC, nilsdeppe commented
LGTM! Please squash :)

2019-11-05 22:24 UTC, fmahebert commented
Squashed & rebased

2019-11-06 03:12 UTC, nilsdeppe approved these changes

2019-11-07 22:38 UTC, kidder approved these changes

2019-11-07 22:38 UTC, merged