Fix cce equations random fail
sxs-collaboration/spectre pull request #1750
Opened 2019-10-31 21:07 UTC by moxcodes

## Proposed changes

Solves #1719 and #1743 

ran locally for 10^5 iterations without fail, previous range failed after ~10^3 attempts.

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2019-10-31 23:57 UTC, kidder requested changes

2019-10-31 23:57 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Sources/UniformAcceleration.hpp
> +#include <pup.h>
you need to rebase... a forward declaration was added in #1736

2019-11-01 00:21 UTC, moxcodes commented
rebased, removed pup commit.

2019-11-01 00:42 UTC, nilsdeppe approved these changes

2019-11-01 01:52 UTC, kidder approved these changes

2019-11-01 17:52 UTC, kidder commented
ignoring travis timeout

2019-11-01 17:52 UTC, merged