Rename frames
sxs-collaboration/spectre pull request #1776
Opened 2019-11-09 17:49 UTC by nilsleiffischer

## Proposed changes

Taken over from #1753 

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-11-09 18:03 UTC, nilsdeppe requested changes
Please fill out the `Proposed changes` section to contain a summary of what is actually being changed.

2019-11-09 18:09 UTC, nilsleiffischer commented
@nilsdeppe done. Do you want to get in #1777 quickly so only one of us has to rebase? :)

2019-11-09 18:12 UTC, nilsdeppe commented
Sure :) 

One question I have about this PR: the diff line count is different from what I had. Do you have an idea of what I missed or why this is?

2019-11-09 18:24 UTC, nilsleiffischer commented
@nilsdeppe I think it's because `physical` is the same length as `inertial`, but `system` is slightly shorter, so more code got reformatted.

2019-11-28 02:38 UTC, nilsleiffischer commented
Since this is running clang-tidy over a lot of files, it turned up two clang-tidy warnings that were probably ignored when they were merged. One is in `boost/math/tools/toms748_solve.hpp` and the other in `ValenciaDivClean/TagsDeclarations.hpp`. Any suggestions what to do with those?

2019-11-28 03:22 UTC, kidder commented
you can ignore the first one (about boost code); it is a warning that we (@wthrowe @kidder @nilsdeppe) have never been able to fix or tell clang-tidy to ignore.

2019-12-04 03:49 UTC, wthrowe requested changes
When this is done, file an issue for us to figure out where "ElementLogical" should be changed to "BlockLogical".

2019-12-04 03:49 UTC, wthrowe commented on src/DataStructures/Tensor/IndexType.hpp
> +  return "System_";
If you're changing the behavior here, change the documentation above to match.  (And really changes like this should be in a separate commit.)

2019-12-04 03:49 UTC, wthrowe commented on src/DataStructures/Tensor/IndexType.hpp
> +/// \cond
`\endcond`

2019-12-04 03:52 UTC, nilsdeppe commented on src/DataStructures/Tensor/IndexType.hpp
> +  return "System_";
I'd argue even a separate PR... A major rename like this should only do that rename and nothing else to keep things as simple as possible.

2023-02-13 17:56 UTC, closed without merging