Update Valencia CharSpeeds
sxs-collaboration/spectre pull request #1799
Opened 2019-11-17 05:11 UTC by carmaza

## Proposed changes

Part of the update to the characteristic speeds, this PR also adds a free function to compute the relativistic sound speed, along with a corresponding compute item. If the reviewers are OK with part of all of these features, we can also use them in ValenciaDivClean. 

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-11-19 17:00 UTC, nilsdeppe requested changes

2019-11-19 17:00 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/SoundSpeedSquared.hpp
> + * \brief Computes the relativistic sound speed squared
This seems like a very long "brief". Could you add a line break here?

2019-11-19 17:00 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/SoundSpeedSquared.hpp
> +#include "PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp"
You only need the forward decl for EoS:
```cpp
template <bool IsRelativistic, size_t ThermodynamicDim>
class EquationOfState;
```

2019-11-19 17:00 UTC, nilsdeppe commented on tests/Unit/PointwiseFunctions/Hydro/Test_SoundSpeedSquared.cpp
> +  EquationsOfState::PolytropicFluid<true> eos_1d(0.003, 4.0 / 3.0);
Can the EOS be `const`?

2019-11-19 17:00 UTC, nilsdeppe commented on tests/Unit/PointwiseFunctions/Hydro/Test_SoundSpeedSquared.cpp
> +  EquationsOfState::IdealFluid<true> eos_2d(5.0 / 3.0);
Can the EOS be `const`?

2019-11-22 06:02 UTC, carmaza commented
Rebased on develop.

2019-11-23 16:02 UTC, nilsdeppe reviewed
LGTM! Please squash

2019-11-25 20:26 UTC, carmaza commented
Squashed and rebased on develop.

2019-11-25 20:52 UTC, nilsdeppe approved these changes

2019-11-25 21:01 UTC, kidder approved these changes

2019-11-27 16:31 UTC, nilsdeppe commented
I've restarted Travis several times and it keeps timing out... Merging anyway since GH CI is passing at least.

2019-11-27 16:31 UTC, merged