Setup linear elliptic executables
sxs-collaboration/spectre pull request #1812
Opened 2019-11-22 21:32 UTC by nilsleiffischer

## Proposed changes

Add executables for the existing Poisson problems, as is done for some of the evolution problems. Since the Metavariables is not specific to the Poisson system anymore (as of #1671), the system is now also chosen when setting up the executable.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-11-26 01:11 UTC, geoffrey4444 requested changes
Just some quick minor things, and I'm ok for you to make those changes and then squash, then I'll approve

2019-11-26 01:11 UTC, geoffrey4444 commented on src/Elliptic/Executables/Linear/CMakeLists.txt
> +function(add_linear_eliptic_executable
elliptic

2019-11-26 01:11 UTC, geoffrey4444 commented on src/Elliptic/Executables/Linear/CMakeLists.txt
> +# Poisson system with Moustache solution
Comment that this is only a 1D/2D solution

2019-11-26 01:11 UTC, geoffrey4444 commented on src/Elliptic/Executables/Linear/SolveLinearEllipticProblem.hpp
> +  // to check anything. This will be generalized ASAP to handle analytic data
Clarify what "anything" is

2019-11-26 20:34 UTC, nilsleiffischer commented
Done @geoffrey4444. @kidder could you review or assign a second reviewer?

2019-12-04 14:39 UTC, kidder submitted a review, later dismissed

2019-12-04 14:40 UTC, kidder commented
@geoffrey4444 please look at
@nilsleiffischer this needs a rebase

2019-12-09 21:10 UTC, kidder commented
@geoffrey4444 please look at

2019-12-11 23:43 UTC, nilsleiffischer commented
@geoffrey4444 please take a quick look, this PR seems ready to merge. Thanks for reviewing!

2019-12-13 22:19 UTC, kidder commented
@geoffrey4444 please look at ASAP

2019-12-17 21:02 UTC, kidder commented
@geoffrey4444 this should be quick to look at, please do so ASAP

2019-12-18 23:14 UTC, geoffrey4444 approved these changes

2019-12-20 17:36 UTC, kidder approved these changes

2019-12-20 17:37 UTC, kidder commented
Ignoring travis failure

2019-12-20 17:38 UTC, merged