Add CI target that doesn't use python bindings
sxs-collaboration/spectre pull request #1836
Opened 2019-12-05 19:30 UTC by nilsdeppe

## Proposed changes

We've had a few instances where PRs break builds that don't use the python bindings (e.g. see issue #1834). This PR changes the clang-8 release target to not build python bindings. It also disables some python tests that currently require the bindings. However, since I don't know enough about the tests @nilsleiffischer should check if this requirement can be relaxed.

I'm intentionally not closing #1834 as part of this PR because this PR is meant to be a temporary solution to the break.

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-12-06 05:19 UTC, nilsvu requested changes
Instead of wrapping the `add_subdirectory` calls, please just replace the `spectre_add_python_test` in the respective `Python/CMakeLists.txt` files with `spectre_add_python_bindings_test` (its does the check for pybindings enabled). It was my mistake to not do that in the first place, and the bug wasn't caught by the CI because we didn't have a build with disabled bindings.
Edit: I opened #1837 to fix this quickly

2019-12-06 05:19 UTC, nilsleiffischer commented on .github/workflows/Tests.yaml
> +          fi
You can use the `strategy.matrix.include` configuration on line 166 to achieve what these `if` statements do (see [these docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-including-configurations-in-a-matrix-build)). I think all that needs to be done is this:
- Add this item to the list on line 166:
    ```yaml
    - compiler: clang-8
      build_type: Release
      BUILD_PYTHON_BINDINGS: OFF
    ```
- In line 228 you can use the variable in the bash script:
    ```bash
    BUILD_PYTHON_BINDINGS=${{ matrix.BUILD_PYTHON_BINDINGS }}
    ```
- The variable is empty for the other configurations, so you can default it to `'ON'` in the `cmake` call:
    ```
    -D BUILD_PYTHON_BINDINGS=${BUILD_PYTHON_BINDINGS:-'ON'}
    ```
When I'm back, I'll expand this configuration to {Py2, Py3, Off} spread across the compilers.

2019-12-06 21:09 UTC, kidder approved these changes

2019-12-06 21:50 UTC, wthrowe approved these changes
These tests are no longer showing up under the correct ctest labels, but that appears to be a preexisting bug affecting all the python binding tests.

2019-12-06 22:10 UTC, wthrowe commented
Filed #1839 about the labels.

2019-12-06 23:12 UTC, nilsvu approved these changes

2019-12-07 15:01 UTC, nilsdeppe commented
Travis is being travis with weird Blaze errors...

2019-12-07 15:01 UTC, merged