Don't remove output files when a test fails
sxs-collaboration/spectre pull request #1838
Opened 2019-12-06 20:03 UTC by wthrowe

Fixes #1726

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2019-12-06 21:06 UTC, kidder submitted a review, later dismissed

2019-12-12 18:34 UTC, nilsdeppe commented
@nilsleiffischer please look at this when you have a moment.

2019-12-13 19:56 UTC, nilsvu requested changes

2019-12-13 19:56 UTC, nilsleiffischer commented on tools/CleanOutput.py
> +        logging.basicConfig(level=1000)
Can we add this feature in a way that doesn’t disable logging? How about you just pass the `force` flag to the `clean_output` function and  use it in line 56 by replacing the `else` with `elif not force`? I think that‘ll do what you want, and still provide useful output.

You can then also add the `-v` flag to where you call the script, so the log will report „Removed file ...“ messages.

2019-12-13 21:40 UTC, wthrowe commented
Squashed because it was basically a complete rewrite of the patch to the python script.

As a mostly unrelated question, is there a reason this warns if a test doesn't produce any output?  There's nothing wrong with that situation and producing extra warnings is bad.  If the list is actually missing you're going to find out because the test explodes the second time you run it.

2019-12-14 01:43 UTC, nilsvu approved these changes
LGTM 👍

About your question: Input files can specify an empty list of expected outputs to explicitly state they don‘t produce any.
I think when I wrote the script my intention was to warn of a „hidden default“: When a user doesn‘t add the list to the input file because they don’t know about the feature, no outputs are checked even though the executable may have some. If you disagree, please open an issue.

2019-12-16 01:18 UTC, kidder approved these changes

2019-12-16 01:18 UTC, merged