Variable slab sizes
sxs-collaboration/spectre pull request #1875
Opened 2019-12-18 01:52 UTC by wthrowe

There will be one more PR in this series that will add code to explicitly place slab boundaries so useful observations can be made without dense output.

Ping @geoffrey4444, because you expressed interest in this.

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-01-07 21:48 UTC, kidder requested changes
joint review with @nilsdeppe and @wthrowe

2020-01-07 21:48 UTC, kidder commented on src/Time/Actions/ChangeSlabSize.hpp
> +    if (not time_stepper.can_change_step_size(
Can you please add a comment why this check is done

2020-01-07 21:48 UTC, kidder commented on src/Time/Actions/ChangeSlabSize.hpp
> +  using type = std::map<temporal_id,
comment on use of multiset (i.e. Event can be called multiple times>

2020-01-07 21:48 UTC, kidder commented on src/Time/Actions/ChangeSlabSize.hpp
> +  using type = std::map<temporal_id,
comment that this is effectively a counter...

2020-01-07 21:48 UTC, kidder commented on src/Time/Actions/ChangeSlabSize.hpp
> +struct NewSizeInbox {
NewSlabSizeInbox

2020-01-07 21:48 UTC, kidder commented on src/Time/Actions/ChangeSlabSize.hpp
> +struct ChangeTimesInbox {
NumberOfTimesCalledByEventInbox

2020-01-07 21:48 UTC, kidder commented on src/Time/Actions/ChangeSlabSize.hpp
> +    auto& new_size_inbox =
new_slab_size_inbox

2020-01-07 21:48 UTC, kidder commented on src/Time/Actions/ChangeStepSize.hpp
>  #include <tuple>
typo in commit message `Those that care`

2020-01-07 21:48 UTC, kidder commented on src/Evolution/Executables/Burgers/EvolveBurgers.hpp
> +  using step_choosers_step_only =
..._for_step_only . (and for_slab_only)

2020-01-10 02:55 UTC, wthrowe commented
I decided to go with NumberOfExpectedMessagesInbox instead of NumberOfTimesCalledByEventInbox.

2020-01-10 17:30 UTC, nilsdeppe commented
review with @kidder LGTM, please squash

2020-01-10 19:34 UTC, kidder approved these changes

2020-01-10 19:34 UTC, nilsdeppe approved these changes

2020-01-10 19:34 UTC, merged