Slab size changing utilities
sxs-collaboration/spectre pull request #1878
Opened 2019-12-22 22:34 UTC by wthrowe

Depends on #1875 only for adding to the executables and input files.

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-01-07 22:09 UTC, kidder requested changes
joint review with @wthrowe and @nilsdeppe

2020-01-07 22:09 UTC, kidder commented on src/Time/Triggers/SpecifiedTimes.hpp
> +    const double sloppiness =
look into whether this can be factored out somewhere to be consistent throughout time classes

2020-01-07 22:09 UTC, kidder commented on tests/InputFiles/Burgers/Step.yaml
> +      Range: 5
make one of the 5s a 4

2020-01-29 02:25 UTC, wthrowe commented
The commit "Add slab_rounding_error function" is new.

2020-01-29 19:18 UTC, kidder reviewed
with @nilsdeppe , looks good squash

2020-01-31 17:38 UTC, kidder approved these changes

2020-01-31 17:49 UTC, nilsdeppe approved these changes

2020-01-31 17:49 UTC, merged