Boundary gauge transform
sxs-collaboration/spectre pull request #1892
Opened 2020-01-07 20:00 UTC by moxcodes

## Proposed changes

Adds the gauge transformation utilities to perform regularity-preserving Cauchy Characteristic Extraction.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2020-01-09 21:16 UTC, kidder reviewed
can you split this into multiple commits (basically by file + associated tests)?   We've reviewed all bit this commit

2020-01-09 21:16 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshTags.hpp
> +  using type = SwshInterpolator;
test the tag

2020-01-09 21:16 UTC, kidder commented on src/DataStructures/SpinWeighted.hpp
> +/// Take the exponential of the spin-weighted quantity; only valid for
split this into separate commit with its test

2020-01-09 23:10 UTC, moxcodes commented
Commits split/reorganized. The commits that have changed or are new:
- `Add tag for SwshInterpolator` - put in a change that was in a later commit erroneously
- `Add exp, sqrt for spin-weight 0`
- `move boundary test utility to shared test helpers`
- `Minor SwshInterpolator tweaks`
- `Add gauge-related CCE tags`
- `Add regularity-preserving gauge transforms` (other commits moved out of this one)
- `fixup: Test SwshTags`

2020-01-10 21:12 UTC, kidder requested changes
joint with @nilsdeppe

2020-01-10 21:12 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshInterpolation.cpp
> +  libsharp_modes.set_data_ref(const_cast<std::complex<double>*>(  // NOLINT
maybe just make the buffer mutable?

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/Tags.hpp
> +  static std::string name() noexcept { return "GaugeOmega"; }
remove the name functions that are just the name of the struct

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> +#include "DataStructures/DataBox/Prefixes.hpp"
are these all the includes you need?

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> +template <typename Tag>
cond the declaration;  should these go in a doxygen group?

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * \details The evolution gauge quantity \f$\hat J\f$ obets
obeys

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> +    DataVector one_over_cartesian_r =
const

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * \hat c = \hat q^{\hat A} \partial_{\hat A} x^A q_A,
it is not clear if `q_A` is being differentiated in either of the two equations

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> +    auto angular_derivative_cartesian_source_coordinates =
`auto&` these two

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> +  static void apply(
please move the implementation to a cpp file (by declaring an _impl function in a detail namespace)

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  auto eth_r = Spectral::Swsh::angular_derivative<Spectral::Swsh::Tags::Eth>(
const

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  SpinWeighted<ComplexDataVector, 0> r_buffer =
const

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * + 2 \hat c \bar{\hat d} K(\hat x^{\hat A}) \right)
should K be J?

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  *evolution_gauge_q =
we cannot connect the documentation to the math here ...

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  get(*evolution_gauge_u) =
again the math and documentation don't match...

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  *evolution_gauge_w +=
again math != doc

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +void GaugeUpdateTimeDerivatives::apply(
we have no clue halp

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +void GaugeAdjustedBoundaryValue<Tags::BondiH>::apply_impl(
math != doc

2020-01-10 21:12 UTC, kidder commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + */
document what this means in terms of numbers

2020-01-10 21:12 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +          auto rootfind = boost::math::tools::bisect(
why not use the toms rootfind that we have wrapped

2020-01-10 21:12 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +  gr::Solutions::KerrSchild solution{mass, spin, center};
const

2020-01-10 21:12 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +    auto check_rhs =
const auto&

2020-01-10 21:12 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +        ComplexDataVector minus_u =
const

2020-01-10 21:12 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +        ComplexDataVector time_transform = 10.0 * get(boundary_u).data();
const

2020-01-10 21:12 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +  Spectral::Swsh::SwshInterpolator omega_interpolator{
const

2020-01-10 21:12 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +  SpinWeighted<ComplexDataVector, 0> omega_comparison_rhs =
const

2020-01-10 21:12 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshDerivatives.hpp
> +void angular_derivatives(size_t l_max, size_t number_of_radial_points,
nope clang-tidy is wrong...

2020-01-10 21:29 UTC, moxcodes commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> +template <typename Tag>
I could make a Cce group, there isn't one currently; I've been using the namespace to collect things together.

2020-01-10 21:30 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> +template <typename Tag>
Up to :) We just wanted to check

2020-01-10 21:31 UTC, moxcodes commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * + 2 \hat c \bar{\hat d} K(\hat x^{\hat A}) \right)
nope, but I'll add the clarification here that K = sqrt(1 + J \bar J).

2020-01-10 21:39 UTC, moxcodes commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +void GaugeUpdateTimeDerivatives::apply(
hmmm. Yeah, I see how the documentation is a little sparse for verifying what's going on here :P

2020-01-12 05:31 UTC, moxcodes commented
fixups posted. I'll rebase on develop when I squash.
Cheers!

2020-01-21 21:07 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> +template <typename Tag>
ping on cond the declaration

2020-01-21 22:40 UTC, nilsdeppe requested changes
Reviewed with @kidder and @moxcodes

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +          (-1.0 + (evolution_gauge_dy_j * conj(evolution_gauge_dy_j) -
Check this `-1.0` since it is a +1.0 in the dox

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +                       (1.0 + evolution_gauge_j * conj(evolution_gauge_j)))) /
use `evolution_gauge_k`

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * implies the need for an interpolation operation.
Can you please define `K` here too?

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * - \frac{\partial_{\hat y}(\hat J \hat{\bar{J}})^2}{4 \hat K^2}\right)
Can you square the whole fraction to make it clear that its the deriv squared and not the deriv of the squared quantity?

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +          exp(2.0 * evolution_gauge_beta) *
factor out e^(2beta)/(omega r^2) prefactor (division is expensive) for last two terms

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * + \hat{\bar{\eth}} \hat \omega \left(-\frac{\hat J \partial_{\hat y}
no bar on \eth in omega deriv

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * \mathcal U = \frac{1}{2\hat \omega} \left(\hat{\bar d} U(\hat x^{\hat A})
check power of omega in denom on first term

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * \left(\hat \eth \hat \omega \hat K
Can you move non-differentiated to left of derivative

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +      (conj(eth_omega) * (evolution_gauge_u - evolution_gauge_u_at_scri) +
Can you add a code comment what u - u_at_scri is and how it relates to the dox?

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * \left(\hat{\bar \eth} \hat \omega^2 \hat J
Can you add parens to make it clear whether the deriv is squared or the thing being operated on is squared? Also can you make non-differentiated quantities be on the left of the operator for clarity?

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +      2.0 * cauchy_du_omega / omega * (evolution_gauge_dy_j) +
Can you factor this and the next line as they are in the dox?

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  *evolution_gauge_h =
remove extra parens please

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * + \hat{\bar d} c \frac{H(\hat x^{\hat A}) \bar J(\hat x^{\hat A})
missing `\hat` on `c`

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * the explicit \f$\hat x^{\hat A}\f$ arguments on the right-hand side imply
can you clarify what `K` and `\hat{K}` are?

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +      du_tilde_omega - 0.5 * (evolution_gauge_u_at_scri * conj(eth_omega) +
Get rid of `tilde` in name

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +      eth_evolution_gauge_u_at_scri_bar_j_tilde -
remove tilde

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * \note Before this update call the quantity stored in the tag
Let's make this `note` a warning since if one is not aware of it things will be bad.

Can you also expand on the relation between \hat{U} and U^{(0)}?

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  x.data() =
Add comment like `// Switch to complex so we can take spin-weighted derivatives`

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * \partial_{\hat u} x^A = \partial_{\hat A} x^{A} \mathcal U^{(0) \hat A},
move U^0 to left of deriv

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  x.data() =
Please add same comment as above

2020-01-21 22:40 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +  get(*gauge_factor_spin_2).data() =
Add comment that these are basically `c` and `d` in the dox

2020-01-21 22:40 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +  const double extraction_radius = 100;
100.0 (find others)

2020-01-21 22:40 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/Cce/Test_GaugeTransformBoundaryData.cpp
> +  const double target_time = 50 * value_dist(*gen);
50.0

2020-01-22 00:11 UTC, moxcodes commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.cpp
> +          (-1.0 + (evolution_gauge_dy_j * conj(evolution_gauge_dy_j) -
Checked with the expressions in my paper draft, and -1.0 is correct, so I'll update the dox

2020-01-22 00:20 UTC, moxcodes commented on src/Evolution/Systems/Cce/GaugeTransformBoundaryData.hpp
> + * \mathcal U = \frac{1}{2\hat \omega} \left(\hat{\bar d} U(\hat x^{\hat A})
checked against derivation and \omega^2 is correct, so I'll fix the dox.

2020-01-22 00:48 UTC, moxcodes commented
rebased, old fixups squashed, and new fixup posted.
Cheers!

2020-01-22 03:41 UTC, kidder reviewed
I am happy with the fixups

2020-01-22 03:42 UTC, kidder commented
but you do have clang-tidy and compiling issues...

2020-01-22 05:08 UTC, nilsdeppe commented
I'm also happy for you to squash

2020-01-22 06:34 UTC, moxcodes commented
Squashed, and added one more fixup for the CI compile fix. The clang-tidy is something in the toms 748 rootfind in the boost library, so I don't think we can do anything about that.

2020-01-22 16:46 UTC, nilsdeppe commented
LGTM. Yes, that's clang-tidy and boost being annoying so we just ignore that error :)

2020-01-22 17:04 UTC, kidder commented
yes squash

2020-01-22 17:07 UTC, moxcodes commented
squashed.
Cheers!

2020-01-22 17:55 UTC, nilsdeppe approved these changes

2020-01-22 19:41 UTC, kidder commented
ignoring boost clang-tidy issue

2020-01-22 19:41 UTC, kidder approved these changes

2020-01-22 19:42 UTC, merged