Worldtube component
sxs-collaboration/spectre pull request #1898
Opened 2020-01-09 02:06 UTC by moxcodes

## Proposed changes
Add worldtube h5 component and initializer. The remaining actions to interface between components will have to wait until after the PRs introducing the other CCE singletons. 

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Dependencies
- [ ] #1869 
- [ ] #1892

2020-01-10 21:12 UTC, nilsdeppe requested changes

2020-01-10 21:12 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Actions/InitializeWorldtubeBoundary.hpp
> +// Distributed under the MIT License.
Can you factor the changes in this commit into several smaller commits? There appear to be a lot of fairly independent changes.

2020-01-12 05:40 UTC, moxcodes commented
split into several commits.
Cheers!

2020-01-22 22:46 UTC, nilsdeppe requested changes
Group review with @kidder @fmahebert @moxcodes @markscheel @geoffrey4444

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Components/WorldtubeBoundary.hpp
> + * \brief ParallelComponent for the management and reporting of CCE worldtube
Component that supplies...

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Components/WorldtubeBoundary.hpp
> + * \details The \ref DataBoxGroup associated with the worldtube boundary
Can we split the first sentence into multiple?

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Components/WorldtubeBoundary.hpp
> + * is assumed that the simple action `BoundaryComputeAndSendToExtractor` will
`SendToExtractor` -> `SendToEvolution`

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Components/WorldtubeBoundary.hpp
> + * only be called during the `Extraction` phase.
`Extraction` -> `Evolution` (or `Evolve`, whatever is currently done in the execs)

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Tags.hpp
> +  static std::string name() noexcept {
can remove now

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Tags.hpp
> +};
Can you add a test that checks the name and sticks one of these into a DataBox and gets it back out?

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +  using type = size_t;
cstddef

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +      "maximum l value for spin-weighted spherical harmonics"};
`Maximum` repeat

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +    return std::numeric_limits<double>::quiet_NaN();
`quiet_NaN` -> `infinity`

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +  using type = double;
Can you stick all the option tags into an option group for CCE?

"Your double offends me." - @fmahebert 2012

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +      "h5 file to read the wordltube data from."};
h5 -> H5

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +  static constexpr OptionString help{"Start time for the Cce Evolution."};
Make default some standard value (-inf or quiet NaN), in which case it chooses a "reasonable" start time (and document what that means)

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +struct H5LookaheadPoints {
Points -> Times

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +      "Number of points to cache on each file read operation."};
Number of _____ to cache
(time steps from H5 file)

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +  static std::string name() noexcept { return "H5Interpolator"; }
no name()

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +      "Number of points to interpolate for at scri+."};
`Order of time interpolation at scri+`

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +struct ScriInterpolationPoints {
Points -> Order

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +  static std::string name() noexcept { return "ScriInterpPoints"; }
Again

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +  static std::string name() noexcept {
Can you remove this?

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +};
Can you add tests for the tags?

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Actions/InitializeWorldtubeBoundary.hpp
> + * \details Uses: initialization tag
Can you make this a bulleted list?

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Actions/InitializeWorldtubeBoundary.hpp
> +      tmpl::append<h5_boundary_manager_simple_tags<Metavariables>>;
you can remove the append here

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Actions/InitializeWorldtubeBoundary.hpp
> +    const auto& l_max = Parallel::get<Spectral::Swsh::Tags::LMax>(cache);
`const size_t`

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Actions/InitializeWorldtubeBoundary.hpp
> +                                     initialization_data_manager) {
noexcept

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Actions/InitializeWorldtubeBoundary.hpp
> +
<tuple>

2020-01-22 22:46 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Actions/InitializeWorldtubeBoundary.hpp
> +#include "ParallelAlgorithms/Initialization/MergeIntoDataBox.hpp"
tmpl, requires, tagged tuple, gsl, DataBox.hpp, <utility> (for std::move), cstddef

2020-01-22 22:46 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeWorldtubeBoundary.cpp
> +    "[Unit]") {
Is there a `Cce` thingy for the tests? e.g. `[Unit][Cce]`? We could add one

2020-01-22 22:46 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeWorldtubeBoundary.cpp
> +#include "PointwiseFunctions/AnalyticSolutions/GeneralRelativity/KerrSchild.hpp"
I'll let you figure out the includes :D

2020-01-22 22:46 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/Cce/Actions/WorldtubeBoundaryMocking.hpp
> +#include "tests/Unit/ActionTesting.hpp"
includes

2020-01-23 01:14 UTC, moxcodes commented
fixups posted.
Cheers!

2020-01-29 19:10 UTC, kidder requested changes
joint with @nilsdeppe 

squash everything including the new comments; make sure the file add/deletion of `Test_InitializeCharacteristicExtractor` doesn't appear in any of the commits

2020-01-29 19:10 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeCharacteristicExtractor.cpp
> +#include "Evolution/Systems/Cce/Actions/InitializeWorldtubeBoundary.hpp"
fix the includes

2020-01-29 19:10 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_OptionTags.cpp
> +#include <string>
need cstddef, check includes

2020-01-29 19:10 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_OptionTags.cpp
> +  CHECK(TestHelpers::test_creation<size_t, Cce::OptionTags::LMax>("8") == 8u);
in `Utilities/Literals.hpp` there is code to make `8u` -> `8_st` for `size_t`, please use that

2020-01-29 19:10 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_OptionTags.cpp
> +  const std::string filename = "CceR0100.h5";
have the name of the file include the test name so we don't get conflicts when running tests in parallel

2020-01-29 23:20 UTC, moxcodes commented
Squashed.
Cheers!

2020-01-30 02:30 UTC, nilsdeppe approved these changes

2020-01-30 02:31 UTC, nilsdeppe commented
clang-tidy failure is because of boost root finder internals warning that we can't fix

2020-01-30 06:27 UTC, kidder approved these changes

2020-01-30 06:29 UTC, kidder approved these changes

2020-01-30 06:29 UTC, merged