Adjust time infrastructure
sxs-collaboration/spectre pull request #1904
Opened 2020-01-11 21:15 UTC by moxcodes

## Proposed changes
For Cce, and especially for a combined Cce/GH evolution system, we need a bit more flexibility with the time stepper actions. This PR introduces the changes that I think will be sufficient to get those pieces working.

I'm open to alternative suggestions for how to better accomplish the same task. This version does have the unfortunate side-effect of introducing the empty tensor args in several existing executables.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2020-01-11 22:03 UTC, wthrowe commented
Is there a reason you are avoiding Variables?  This is one of the things it was designed for.

2020-01-11 22:11 UTC, moxcodes commented
My plan was to put the things I need to evolve in a Variables, but there's a couple of design challenges that could probably be worked around in different ways
- For most of the Cce hypersurface, the 'evolved' quantity and its corresponding dt counterpart are treated similarly and so far I've been putting them in the same Variables along with the other quantities that share similar properties. There's some inclination that having them all in the same memory block might help performance of spin-weighted derivatives, but I'm honestly not sure how much that gains us.
- I'll need to evolve both a real tensor quantity (the coordinates) and a complex scalar quantity (the Bondi evolved value), and our current architecture forbids things with different vector types being in the same variables.

So, I could probably get away with only the simpler of these two changes (just templating the existing utility) in exchange for making my Cce typelists somewhat more messy by ensuring that the evolved quantity and its time derivative have to be split out into two additional `Variables`

2020-01-15 21:20 UTC, wthrowe commented
I'll ping @nilsdeppe for his thoughts on memory layout.

In the partial derivative code we do math on portions of Variables.  I don't know if that would be useful for the spatial derivatives.  I think the current time-stepping code is too high level to do that without some wrapping.

In any case, having both real and complex values pretty much rules out doing this with a single call to the time stepper.

Templating UpdateU, etc., makes sense.

2020-01-15 21:28 UTC, nilsdeppe commented
Yes, the current partial derivatives code supports operating on a subset of a Variables. I will point out that it's done via pointer manipulation directly and not using a non-owning `Variables` (which I think we probably want at some point, actually).

I think in theory we could support Variables with mixed complex<double> and double, my only concern is that it would need to be tested extremely well because there'll be spooky memory things happening like reinterpret_cast.

Is that helpful?

2020-01-15 21:43 UTC, moxcodes commented
I think the only reason to try to keep the swsh derivatives acting on a consistent Variables object is a rough reasoning with trying to keep caches warm when doing a bunch of transforms; the way we need to do it in different steps of the hypersurface computation, there's little hope of managing the transforms as true memory blocks, even if libsharp was optimized for it.

I wouldn't mind creating mixed variables, but that's going to be far harder than just templating the steppers.

Are we in agreement then that the best course here is to drop the tensor version from this PR and just work with templated `UpdateU` and `RecordTimeStepperData`?

2020-01-30 18:15 UTC, moxcodes commented
This has been updated, dropping the tensor version of the generalization and just templating the existing `RecordTimeStepperData` and `UpdateU` to apply to general pairs of tags.

2020-02-03 17:21 UTC, kidder commented
@wthrowe can you look at this?

2020-02-03 19:38 UTC, wthrowe requested changes
The design looks fine.

2020-02-03 19:38 UTC, wthrowe commented on tests/Unit/Time/Actions/Test_RecordTimeStepperData.cpp
> +  UniformCustomDistribution<double> value_dist{1.0, 5.0};
These are unused.

2020-02-03 21:11 UTC, nilsdeppe commented on src/DataStructures/Tensor/Tensor.hpp
> +      const size_t& size, const double value) noexcept {
Can this just be `const size_t size` without a reference?

2020-02-03 23:11 UTC, moxcodes commented
fixups posted.
Cheers!

2020-02-03 23:19 UTC, nilsdeppe commented
LGTM! I'm happy for you to squash once @wthrowe has had a chance to look :)

2020-02-04 00:02 UTC, wthrowe commented
Looks good.

2020-02-04 07:35 UTC, moxcodes commented
Squashed.
Cheers!

2020-02-04 17:02 UTC, nilsdeppe approved these changes

2020-02-04 17:35 UTC, wthrowe approved these changes

2020-02-04 21:12 UTC, merged