Add Ocean batch submit script
sxs-collaboration/spectre pull request #1906
Opened 2020-01-13 14:12 UTC by geoffrey4444

## Proposed changes

Adds a standard submission script for running jobs on the Ocean cluster at Cal State Fullerton.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [x] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-01-14 23:03 UTC, nilsdeppe submitted a review, later dismissed

2020-01-18 04:53 UTC, kidder commented
@nilsdeppe told me this needs updating to use singularity...

2020-01-21 13:52 UTC, geoffrey4444 commented
@kidder I will create a separate submit script for singularity. This PR is for running spectre with a non-singularity build, which I still want to maintain

2020-01-21 18:19 UTC, kidder commented
okay, then please have one of your students verify that it works and provide a review for this PR

2020-02-21 18:24 UTC, kidder commented
@geoffrey4444 should I close this?

2020-02-21 18:29 UTC, geoffrey4444 commented
No, please give me a bit more time to update it using singularity

2020-03-05 22:37 UTC, geoffrey4444 commented
@nilsdeppe I just updated this to use our singularity container, and I tested it on latest develop, that it works as expected on ocean.

2020-03-05 23:43 UTC, kidder requested changes

2020-03-05 23:43 UTC, kidder commented on support/SubmitScripts/Ocean.sh
> +mpirun -np 2 --map-by ppr:1:node singularity exec \
instead of 2 use ${SLURM_JOB_NUM_NODES} and they will always be consistent

2020-03-10 21:41 UTC, nilsdeppe commented
@geoffrey4444 this is waiting on you

2020-03-10 22:32 UTC, geoffrey4444 commented
Didn't see @kidder's review until just now...I just pushed a fixup

2020-03-10 23:12 UTC, nilsdeppe commented
LGTM. Please squash :) I'm sure Larry can handle the small change ;)

2020-03-11 02:50 UTC, kidder approved these changes

2020-03-11 13:24 UTC, merged