Configure ccache in cmake (also for macOS)
sxs-collaboration/spectre pull request #1907
Opened 2020-01-13 14:15 UTC by nilsleiffischer

## Proposed changes

This ccache configuration works for PCH on our CIi and in the container,
and it also works for macOS builds (which we had trouble with before).

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-01-15 17:33 UTC, nilsdeppe requested changes
Why are you doing this? I've never needed this on my machine and I'm worried it'll cause problems.

2020-01-15 17:54 UTC, nilsleiffischer commented
I needed this configuration to make ccache work on macOS, and have also tested it in the container. I understand your worry though. Since it‘s the same config we use on CI machines I think we can be fairly confident it works. What do you think?

2020-01-15 18:05 UTC, nilsdeppe commented on cmake/SetupCCache.cmake
> +      "CCACHE_COMPILERCHECK=content "
Okay, so I'm okay with this if we only add the `content` check on macOS and CI and use the default on Linux

2020-01-15 18:06 UTC, nilsleiffischer commented
Let me actually do a few more tests on macOS, marking as in progress

2020-01-15 18:09 UTC, nilsdeppe commented
Okay. I think the way the PCH is handled here is good and correct, just worried about the `content` a bit

2020-01-15 21:45 UTC, nilsleiffischer commented
I can confirm that ccache on macOS works fine without the `CCACHE_COMPILERCHECK=content` option, but the PCH config seems to be necessary.

I pushed an updated configuration. Please take a look.

2020-01-15 22:33 UTC, nilsdeppe submitted a review, later dismissed
Looks reasonable! :)

2020-01-16 08:49 UTC, nilsleiffischer commented
@kidder or @wthrowe could you do the second review?

2020-01-18 04:44 UTC, nilsdeppe approved these changes

2020-01-20 17:47 UTC, kidder approved these changes

2020-01-20 17:47 UTC, merged