Add first of series of tutorials on creating executables
sxs-collaboration/spectre pull request #1909
Opened 2020-01-13 20:13 UTC by kidder

## Proposed changes

This tutorial adds a description of Charm++ and SpECTRE parallel concepts, and shows how to create a minimal SpECTRE executable.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-01-18 21:05 UTC, carmaza reviewed
Mostly comments on style and typos. Feel free to squash or disregard any of them.

On a more general comment, since I personally believe that the SpECTRE documentation (seen as a help guide for new users) would truly benefit from defining (i) the type(s) of readers that the dox is intended for, and (ii) the background knowledge expected from those readers, it is not clear to me how to evaluate the introduction of more conceptual overviews to the documentation, or the content of them.

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/Tutorials.md
> +  metaprogramming that turns user-proivded code into a SpECTRE
user-provided

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +(Note that `pragma once` tells the compiler to only include the file
If readers are expected to know what this directive does, and the purpose of this note is to serve as a reminder, then this note is OK. If, however, this note is intended to explain/clarify what this line does to a reader not familiar with it, it'd be better to write "Here `pragma once` ...."

2020-01-18 21:05 UTC, carmaza commented on src/Executables/Examples/ParallelTutorial/MinimalExecutable.hpp
> +/// \cond
If the reader is taking a look at the actual source code, they might wonder what `\cond` and `\endcond` do here. Maybe add a comment or a note in the text of the tutorial?

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +  against (in the given example the `CMake` list `LIBS_TO_LINK`)
in the given example the `CMake` list `LIBS_TO_LINK`, where `Informer` and `Utilities` are two SpECTRE libraries.

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +empty.
Maybe add a reference to the Charm++ Node and Processor Level Initialization Functions dox?

Tiny question: should this header also `#include <vector>` for consistency?

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +a SpECTRE executable is run, the constructor of `Main` is executed
"is executed that" ->" that is executed" ?

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +- Parses the input file options, poplulating a tagged tuple with their
poplulating ->populating ?

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +Once the list of parallel components is sent to the `ConstGloalCache`
`ConstGlobalCache`

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +exectued.  This will allocate the elements of the array parallel
executed

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +information is printed and the prgram exits gracefully.  Otherwise the
program

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +execute the `Initialization` phase followed by the `Exit` phase.
We should probably mention that the class`Parallel::CProxy_ConstGlobalCache<Metavariables>` will be explained below.

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +that is a `tmpl::list` (a typelist) of the parallel components used by
Since, I believe, we want to explain what each line in this file does, you could say "a typelist defined in `Utilities/TMPL.hpp`"

(Note: `MinimalExample` will also compile and run without this include.)

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +executable.
`"Options/Options.hpp"`contains the definition of `OptionString`.

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/Concepts.md
> +parallel components that represent a collection of distributed
Since (I believe) this is intended to be the first mention to the concept, we should probably emphasize (e.g. LaTeX's \emph) "parallel component".

2020-01-18 21:05 UTC, carmaza commented on docs/Tutorials/ParallelExecutable/Concepts.md
> +actions.  Thus, each element of a parallel component can be thought of
also emphasize "action"

2020-01-29 18:09 UTC, nilsdeppe requested changes

2020-01-29 18:09 UTC, nilsdeppe commented on src/Parallel/AlgorithmMetafunctions.hpp
>  #pragma once
Commit message: "... to AlgorithmMetafunctions"

2020-01-29 18:09 UTC, nilsdeppe commented on docs/Tutorials/ParallelExecutable/Concepts.md
> +SpECTRE's actions do not return any value when called.  Instead when
Now wait a minute. I'm pretty sure what is returned depends on the action.

2020-01-29 18:09 UTC, nilsdeppe commented on docs/Tutorials/ParallelExecutable/Concepts.md
> +\cond NEVER
@kidder and I discussed moving these guides to the Dev Guide. The reason being that I've viewed tutorials and dev guides as:
Dev Guides: how to write SpECTRE code
Tutorials: how to run SpECTRE, visualize output

2020-01-29 18:09 UTC, nilsdeppe commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +Specifically this tutorial will introduce:
[nitpick] comma after specifically

2020-02-26 05:32 UTC, kidder commented
@carmaza @nilsdeppe I've pushed fixups

2020-02-26 14:01 UTC, nilsdeppe commented on src/Parallel/AlgorithmMetafunctions.hpp
>  #pragma once
ping

2020-02-26 14:05 UTC, nilsdeppe reviewed
I'm happy for you to squash once @carmaza has had a chance to look, including the ping and new comment

2020-02-26 14:05 UTC, nilsdeppe commented on docs/Tutorials/ParallelExecutable/MinimalExecutable.md
> +(`Parallel::CProxy_ConstGlobalCache` is an used proxy to the
Can you reword `is an used proxy`, I'm unable to parse this

2020-02-26 14:27 UTC, carmaza commented
Looks good to me.

2020-02-26 17:05 UTC, kidder commented
@nilsdeppe @carmaza squashed, thanks!

2020-02-26 17:06 UTC, nilsdeppe approved these changes

2020-02-26 17:07 UTC, carmaza approved these changes

2020-02-26 19:09 UTC, merged