Add non-Euclidean Poisson system
sxs-collaboration/spectre pull request #1910
Opened 2020-01-14 18:00 UTC by nilsleiffischer

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-01-18 17:25 UTC, nilsleiffischer commented
@fmahebert @prayush could you do the review for this? As always, feel free to forward to another reviewer if you don't have the time.

2020-01-22 23:27 UTC, fmahebert submitted a review, later dismissed

2020-01-27 08:48 UTC, nilsleiffischer commented
@prayush please take a look.

2020-01-31 02:54 UTC, prayush submitted a review, later dismissed

2020-01-31 06:57 UTC, nilsleiffischer commented
@sxs-collaboration/spectre-core-devs This PR is ready for a final look.
Thanks for reviewing @fmahebert @prayush. :)

2020-02-03 18:19 UTC, kidder requested changes

2020-02-03 18:19 UTC, kidder commented on src/Elliptic/Systems/Poisson/Equations.hpp
> +    noneuclidean_fluxes(flux_for_field, inv_spatial_metric, det_spatial_metric,
`non_euclidean_fluxes` to be consistent with `NonEuclideanFluxes`

2020-02-03 18:19 UTC, kidder commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Test_Lorentzian.cpp
> +// [[TimeOut, 10]]
please make the test run faster

2020-02-04 09:57 UTC, nilsleiffischer commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Test_Lorentzian.cpp
> +// [[TimeOut, 10]]
this was left over from an early issue, deleted the line and squashed the change. thanks for catching this

2020-02-04 09:57 UTC, nilsleiffischer commented
done @kidder. Thanks for reviewing!

2020-02-04 15:38 UTC, kidder requested changes
you can squash this

2020-02-04 15:38 UTC, kidder commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/Poisson/Test_Lorentzian.cpp
> -// [[TimeOut, 10]]
this should be in the previous commit...

2020-02-04 18:16 UTC, nilsleiffischer commented
done @kidder

2020-02-04 22:24 UTC, kidder approved these changes

2020-02-04 22:25 UTC, kidder commented
@prayush @fmahebert there were some fixups

2020-02-04 22:26 UTC, fmahebert approved these changes

2020-02-05 11:24 UTC, nilsleiffischer commented
@prayush please take a quick look

2020-02-06 18:42 UTC, nilsleiffischer commented
@kidder do you want to wait for @prayush to re-approve this (he approved earlier)? If so, @prayush could you please take a look?

2020-02-07 21:32 UTC, kidder commented
@prayush this just needs your final approval

2020-02-10 09:16 UTC, nilsleiffischer commented
@prayush please take a look...

2020-02-10 15:19 UTC, kidder commented
@prayush please file an issue if you were not happy with this

2020-02-10 15:19 UTC, merged