Distinguish between "boundary data" and "mortar data"
sxs-collaboration/spectre pull request #1921
Opened 2020-01-18 12:43 UTC by nilsleiffischer

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-01-18 17:21 UTC, nilsleiffischer commented
@nilsdeppe @kidder could you review this or assign another reviewer while @wthrowe is away? This is the first of a series of PRs that's factored out of #1725.

2020-01-24 19:43 UTC, wthrowe requested changes
If I understand correctly, this PR removes (renames) a class called SimpleBoundaryData and then adds a new class with the same name.  I was confused about what was going on for a while.  Perhaps add something to the commit message adding the new version mentioning that something with the same name was removed two commits earlier so that people aren't confused by seeing what appears to be the same class in use before it is added.

2020-01-24 19:43 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_SimpleMortarData.cpp
> +// [[OutputRegex, Only have local data at temporal_id]]
Blank line.

2020-01-24 19:43 UTC, wthrowe commented on src/NumericalAlgorithms/DiscontinuousGalerkin/SimpleBoundaryData.hpp
> +// Distributed under the MIT License.
Typo in commit message: "proojected".

2020-01-24 19:43 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_SimpleBoundaryData.cpp
> +// Distributed under the MIT License.
This file needs to be added to CMakeLists.txt

2020-01-25 00:10 UTC, nilsleiffischer commented
@wthrowe pushed fixups and rephrased the commit messages. Please let me know if the naming is clear now.

2020-01-25 00:11 UTC, nilsleiffischer commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_SimpleBoundaryData.cpp
> +// Distributed under the MIT License.
thanks, good catch 👍

2020-02-04 10:02 UTC, nilsleiffischer commented
@wthrowe @nilsdeppe could you review when you get the chance? #1586 is very high priority for me and I think this series of PRs that factors the DG and fluxcomm code into more free functions and reusable data structures will be helpful for the subcell communication code :)

2020-02-04 17:51 UTC, wthrowe commented
Yes, that's clear now, thanks.

2020-02-04 18:18 UTC, nilsleiffischer commented
👍 squashed the fixup because no-one else has reviewed this yet.

2020-02-06 18:38 UTC, nilsleiffischer commented
@nilsdeppe could you take a look at this one please?

2020-02-10 16:44 UTC, kidder submitted a review, later dismissed

2020-02-10 16:44 UTC, kidder commented
@wthrowe please look at

2020-02-10 16:45 UTC, kidder commented
reviewed jointly (including @nilsdeppe ) during AEI call

2020-02-11 20:05 UTC, wthrowe submitted a review, later dismissed

2020-02-12 15:34 UTC, nilsdeppe reviewed
I'm happy for you to squash immediately

2020-02-12 15:34 UTC, nilsdeppe commented on src/NumericalAlgorithms/DiscontinuousGalerkin/SimpleBoundaryData.hpp
> +#include "DataStructures/Variables.hpp"
you're missing some includes

2020-02-12 15:34 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_SimpleBoundaryData.cpp
> +struct SomeField : db::SimpleTag {
do these need to inherit from SimpleTag

2020-02-12 15:34 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_SimpleBoundaryData.cpp
> +  const size_t num_points = 3;
why not 5 like we normally use?

2020-02-12 16:41 UTC, nilsleiffischer commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_SimpleBoundaryData.cpp
> +  const size_t num_points = 3;
changed

2020-02-12 16:41 UTC, nilsleiffischer commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_SimpleBoundaryData.cpp
> +struct SomeField : db::SimpleTag {
no they don't 👍

2020-02-12 16:42 UTC, nilsleiffischer commented
rebased and squashed. Thanks for reviewing @nilsdeppe @wthrowe @kidder

2020-02-12 19:05 UTC, nilsdeppe commented on src/NumericalAlgorithms/DiscontinuousGalerkin/SimpleBoundaryData.hpp
> +#include "DataStructures/Variables.hpp"
You still need `pup`

2020-02-12 20:17 UTC, nilsleiffischer commented on src/NumericalAlgorithms/DiscontinuousGalerkin/SimpleBoundaryData.hpp
> +#include "DataStructures/Variables.hpp"
fixed

2020-02-12 20:18 UTC, nilsdeppe approved these changes

2020-02-12 20:36 UTC, kidder approved these changes

2020-02-14 04:16 UTC, wthrowe approved these changes

2020-02-14 04:16 UTC, merged