Evolution component
sxs-collaboration/spectre pull request #1931
Opened 2020-01-24 00:56 UTC by moxcodes

## Proposed changes

Add the Evolution component for Cce. This component will handle the bulk of the computation in the volume of the characteristic evolution algorithm.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Dependencies
- [ ] #1904 
- [ ] #1896 
- [ ] #1898

2020-02-03 17:43 UTC, kidder requested changes
with @nilsdeppe

2020-02-03 17:43 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_OptionTags.cpp
> +            std::numeric_limits<double>::infinity(), "CceR0100.h5") == 5.4);
make sure this filename doesn't conflict with other tests...

2020-02-03 17:43 UTC, kidder commented on src/Evolution/Systems/Cce/Components/CharacteristicEvolution.hpp
> +/*!
please add a brief

2020-02-03 17:43 UTC, kidder commented on src/Evolution/Systems/Cce/Components/CharacteristicEvolution.hpp
> +                             Metavariables::Phase::RegisterWithObserver,
please rename this phase to `Register` as it is more general

2020-02-03 17:43 UTC, kidder commented on src/Evolution/Systems/Cce/Components/CharacteristicEvolution.hpp
> +  using registration_action_list =
you don't need to specify these lists for phases in which nothing is done

2020-02-03 17:43 UTC, kidder commented on src/Evolution/Systems/Cce/Components/CharacteristicEvolution.hpp
> +      Parallel::PhaseActions<typename Metavariables::Phase,
just drop this phase from this list since it does nothing

2020-02-03 17:43 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolution.hpp
> +namespace Actions {
the `Actions` namespace is not documented

2020-02-03 17:43 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolution.hpp
> +      typename db::item_type<::Tags::HistoryEvolvedVariables<
don't need `typename`

2020-02-03 17:43 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolution.hpp
> +      typename db::item_type<::Tags::HistoryEvolvedTensor<
don't need leading `typename`

2020-02-03 17:43 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolution.hpp
> +    return std::make_tuple(std::move(box));
This should `ERROR` as it should not be encountered

2020-02-03 17:43 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeCharacteristicEvolution.cpp
> +  const std::string filename = "test_CceR0100.h5";
please make the filename unique

2020-02-04 22:35 UTC, moxcodes commented
Fixups posted along with some changes that were required following the rebase; no longer dependent.
Cheers!

2020-02-04 23:23 UTC, moxcodes commented
Added the fixup I missed regarding the filename in the option tag tester.

2020-02-05 17:27 UTC, nilsdeppe commented
I'm happy for you to squash once @kidder has had a chance to look

2020-02-05 18:04 UTC, kidder commented
squash

2020-02-05 18:28 UTC, moxcodes commented
Squashed.
Cheers!

2020-02-05 19:39 UTC, nilsdeppe approved these changes

2020-02-05 19:47 UTC, kidder approved these changes

2020-02-05 21:05 UTC, merged