Extraction computation actions
sxs-collaboration/spectre pull request #1973
Opened 2020-02-05 01:36 UTC by moxcodes

## Proposed changes

Adds the actions necessary to perform all of the intermediate calculations to perform the hypersurface integration for the CCE evolution system.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Dependencies

- [ ] #1972 
- [ ] #1931

2020-02-07 21:26 UTC, kidder requested changes

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/IntegrandInputSteps.hpp
> + * \note the tag `Tags::DuRDividedByR` is omitted from this list because in the
add a blank line before the note

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_PrecomputeCceDependencies.cpp
> +  using independent_of_integration_variables_tag = ::Tags::Variables<
use `tmpl::push_back<pre_computation_tags, Tags::DuRDividedByR>`

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Test_SwshDerivatives.cpp
> +  using integration_independent_variables_tag = ::Tags::Variables<
push_back

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +struct FilterLMax {
please put these options in an option group say `Filtering` which is inside the `Cce` group
and why are they InitializationTags and not just Tags?

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/FilterSwshVolumeQuantity.hpp
> +    const size_t radial_filter_half_power =
you can just get these from the box and then turn cache into an unused constant variable

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/FilterSwshVolumeQuantity.hpp
> +            const gsl::not_null<db::item_type<BondiTag>*> bondi_quantity) {
noexcept

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolution.hpp
> +                 InitializationTags::FilterLMax,
put these new tags in a `using const_global_cache_tags` type alias in the action that uses them, not the initialization action.

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_FilterSwshVolumeQuantity.cpp
> +      tmpl::append<tmpl::list<InitializationTags::FilterLMax,
you don't need to list the tags here after making the earlier change to add the `const_global_cache_tags` type alias to the filtering action

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_FilterSwshVolumeQuantity.cpp
> +      tmpl::list<InitializationTags::FilterLMax,
remove this

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_FilterSwshVolumeQuantity.cpp
> +                  "[Unit]") {
"[Unit][Cce]"

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_FilterSwshVolumeQuantity.cpp
> +                                                                32u}};
32_st

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/TimeManagement.hpp
> +                    Parallel::ConstGlobalCache<Metavariables>& /*cache*/,
const

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/CMakeLists.txt
> +  Test_TimeManagement.cpp
alphabet

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/InitializeCharacteristicEvolution.hpp
> + *  - `Spectral::Swsh::Tags::SwshInterpolator< Tags::CauchyAngularCoords>`
remove space before `Tags::Cau`

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_BoundaryCommunication.cpp
> -                 Spectral::Swsh::Tags::NumberOfRadialPoints>;
how does this work without this tag here?

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_InitializeCharacteristicEvolution.cpp
> -                 Spectral::Swsh::Tags::NumberOfRadialPoints>;
again with dropping this tag...

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_RequestBoundaryData.cpp
> +                 Spectral::Swsh::Tags::NumberOfRadialPoints,
be consistent with the tags...

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/CharacteristicEvolutionBondiCalculations.hpp
> +                    Parallel::ConstGlobalCache<Metavariables>& /*cache*/,
const

2020-02-07 21:26 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/CharacteristicEvolutionBondiCalculations.hpp
> +    tmpl::for_each<gauge_adjustments_setup_tags>([&box](auto tag_v) {
noexcept

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_CharacteristicEvolutionBondiCalculations.cpp
> +                 InitializationTags::FilterLMax,
shouldn't need the filtering tags here

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_CharacteristicEvolutionBondiCalculations.cpp
> +    "[Unit]") {
`[Cce]` . (check this for all your tests)

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_CharacteristicEvolutionBondiCalculations.cpp
> +  gr::Solutions::KerrSchild solution{mass, spin, center};
const

2020-02-07 21:26 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/BoundaryTestHelpers.hpp
> +    const size_t l_max) noexcept {  // NOLINT
put in the reason for the NOLINT in the syntax `NOLINT(clang tidy error)`

2020-02-07 21:26 UTC, kidder commented
reviewed with @nilsdeppe

2020-02-08 01:37 UTC, moxcodes commented
fixups posted.
Cheers!

2020-02-10 20:17 UTC, kidder requested changes
with @nilsdeppe  and you can squash everything

2020-02-10 20:17 UTC, kidder commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +/// option group
why the case change?  If it was creating a link use `%Option`

2020-02-10 20:17 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/BoundaryTestHelpers.hpp
> +    const size_t l_max) noexcept {  // NOLINT(clang tidy error)
sorry for not being clear, can you put in the actual "error name" that clang-tidy gave you, such as `google-explicit-constructor`

2020-02-10 20:59 UTC, moxcodes commented
Squashed.
Cheers!

2020-02-15 01:26 UTC, moxcodes commented
rebased on develop, added a fixup commit for the changes to new utilities from the rebase.

2020-02-15 01:56 UTC, nilsdeppe commented
fixup LGTM. Please squash once @kidder has had a chance to look :)

2020-02-15 01:57 UTC, kidder commented
you can squash

2020-02-15 04:23 UTC, moxcodes commented
Squashed
Cheers!

2020-02-15 04:30 UTC, nilsdeppe approved these changes

2020-02-15 05:19 UTC, kidder approved these changes

2020-02-15 14:19 UTC, merged