Add normal_dot_flux function for Variables
sxs-collaboration/spectre pull request #1979
Opened 2020-02-06 20:17 UTC by nilsleiffischer

## Proposed changes

Splits the function from the compute item into a free function.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-02-10 17:59 UTC, kidder submitted a review, later dismissed

2020-02-10 18:01 UTC, nilsdeppe requested changes
I'm happy for you to squash immediately

2020-02-10 18:01 UTC, nilsdeppe commented on src/NumericalAlgorithms/DiscontinuousGalerkin/NormalDotFlux.hpp
> +    return normal_dot_flux<tags_list>(normal, flux);
Can you generalize the test to handle testing only the free function too?

2020-02-11 19:50 UTC, nilsleiffischer commented
done @nilsdeppe

2020-02-11 21:17 UTC, kidder approved these changes

2020-02-12 01:04 UTC, nilsdeppe approved these changes

2020-02-12 01:04 UTC, merged