Add 2D time-dependent rotation map
sxs-collaboration/spectre pull request #2012
Opened 2020-02-23 05:34 UTC by geoffrey4444

## Proposed changes

This PR creates a new CoordinateMap that implements a 2D time-dependent rotation. 

Currently, spectre has static 2D and 3D (Euler-angle) rotation maps. This PR adds a 2D time-dependent rotation map. A 3D time-dependent rotation map using quaternions will be added in the future, but not in this PR.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [x] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-03-05 23:34 UTC, kidder requested changes
reviewed with @nilsdeppe

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +/// \file
please leave out the file comment

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +namespace CoordinateMapsTimeDependent {
`CoordMapsTimeDependent`

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +class RotationTimeDep;
RotationTimeDep -> Rotation

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> + * \ingroup CoordinateMapsTimeDependentGroup
fix the group name too

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +  /// Constructor.
you can leave this comment out

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +          std::unique_ptr<domain::FunctionsOfTime::FunctionOfTime>>& map_list)
map_list -> functions_of_time in multiple places

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +#include "DataStructures/Tensor/Tensor.hpp"
just include Tensor/TypeAliases

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +#include <limits>
no limits, but string, memory, unordered_map

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +  std::string f_of_t_name_ = "rotation_angle";
no default value .  (we realize you put it in based on Translation, but that was there before we allowed the name to be specified)

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +  explicit RotationTimeDep(std::string function_of_time_name);
noexcept

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +  const Matrix& matrix{rotation_matrix(f_of_t_name_, time, map_list)};
const Matrix rot_matrix = rotation_matrix...   in multiple places

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +  //
remove these two blank lines

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +          dereference_wrapper(source_coords[0]), 0.0)};
set to matrix(0, 0); then you only have to set the off-diagonal terms

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +          dereference_wrapper(source_coords[0]), 0.0)};
same as above

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +void RotationTimeDep<2>::pup(PUP::er& p) { p | f_of_t_name_; }
noexcept

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +// Explicit instantiations
remove

2020-03-05 23:34 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +#include "Domain/FunctionsOfTime/FunctionOfTime.hpp"
include DataVector and check if anything else is missing

2020-03-05 23:34 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/Test_RotationTimeDep.cpp
> +  constexpr size_t spatial_dim{2};
please be consistent

2020-03-05 23:34 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/Test_RotationTimeDep.cpp
> +  // Then at t = -1.0, f = 1.0, df/dt = -2.0, d^2f/dt^2 = 2.0
remove this comment

2020-03-06 13:21 UTC, geoffrey4444 commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +/// \file
Do we ever use these comments anymore, or are they only present in older files? Any plan to remove them all if the latter?

2020-03-06 13:58 UTC, geoffrey4444 commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +// Explicit instantiations
I presume you just want me to remove the comment, not the explicit instantiations themselves?

2020-03-06 21:14 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/RotationTimeDep.hpp
> +/// \file
We have decided to go with "If the file name basically matches what's inside, no need for the comment, if the file name is very generic then the comment is useful." Yes, we'd like to remove them, but that's also time taken away from our other tasks :)

2020-03-06 21:24 UTC, kidder requested changes
squash including the one fix

2020-03-06 21:24 UTC, kidder commented on src/Domain/CoordinateMaps/RotationTimeDep.cpp
> +#include <algorithm>
get std::move from <utility> not <algorithm>

2020-03-07 17:32 UTC, nilsdeppe approved these changes

2020-03-07 17:33 UTC, kidder approved these changes

2020-03-07 17:33 UTC, merged

2020-03-07 17:34 UTC, nilsdeppe commented
Sorry @geoffrey4444, here's your seal!

![image](https://user-images.githubusercontent.com/13531030/76147999-04b81d00-6070-11ea-89a3-1905324a463b.png)