Begin to factor DataBoxTag.hpp
sxs-collaboration/spectre pull request #2043
Opened 2020-03-01 06:06 UTC by kidder

## Proposed changes

Starting to factor DataBoxTag.hpp into smaller parts.
This PR factors the empty structs that DataBox are inherited from, along with tag traits and `db::tag_name`.  More factoring will occur in a subsequent PR.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

2020-03-02 21:22 UTC, kidder commented
clang-tidy error is boost root-finder

2020-03-03 15:55 UTC, nilsdeppe requested changes

2020-03-03 15:55 UTC, nilsdeppe commented on tests/Unit/DataStructures/DataBox/TestTags.hpp
> +namespace test {
Why not `TestHelpers` for consistency? Then do a nested `namespace db`

2020-03-03 15:55 UTC, nilsdeppe commented on tests/Unit/DataStructures/DataBox/Test_TagName.cpp
> +#include "DataStructures/DataBox/TagName.hpp"
Also need `DataBox/Tag.hpp`

2020-03-05 15:03 UTC, kidder commented
squashed in the fixups

2020-03-05 15:09 UTC, nilsdeppe submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/13531030/75994748-70ac5100-5ec9-11ea-8192-c990542ae516.png)

2020-03-06 00:27 UTC, kidder commented
@fmahebert @moxcodes can one of you review this please?

2020-03-06 00:28 UTC, fmahebert approved these changes

2020-03-06 00:28 UTC, kidder commented
wow fastest review ever 😛

2020-03-06 00:29 UTC, kidder commented
@nilsdeppe I had to rebase

2020-03-06 00:32 UTC, fmahebert commented
@kidder I'd been scrolling through it for a while already when you pinged 🙂

2020-03-06 00:33 UTC, kidder commented
thanks @fmahebert !

2020-03-06 01:49 UTC, nilsdeppe approved these changes
@kidder you probably only rebased to get more seals ;)

![image](https://user-images.githubusercontent.com/13531030/76042428-bcd7af80-5f22-11ea-82f0-84698581c8cb.png)

2020-03-06 14:19 UTC, nilsdeppe commented
Clang-tidy failure is boost root finder nonsense.

2020-03-06 14:19 UTC, merged