Instantiate moving mesh maps
sxs-collaboration/spectre pull request #2054
Opened 2020-03-04 17:28 UTC by nilsdeppe

## Proposed changes

- Allow specifying source frame for map instantiation macros
- Instantiate moving mesh maps

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-03-05 21:47 UTC, kidder requested changes
you can squash immediately

2020-03-05 21:47 UTC, kidder commented on src/Domain/CoordinateMaps/MapInstantiationMacros.hpp
> + * contains the frames to instantiate for, typically `Frame::Grid` and
the target frames

2020-03-05 21:47 UTC, kidder commented on src/Domain/CoordinateMaps/MapInstantiationMacros.hpp
> + * contains the frames to instantiate for, typically `Frame::Grid` and
the target frames

2020-03-05 23:00 UTC, nilsdeppe commented
Rebased on develop and squashed in changes

2020-03-05 23:36 UTC, kidder approved these changes

2020-03-06 17:40 UTC, moxcodes approved these changes

2020-03-06 18:29 UTC, merged