Local time stepping (time steppers)
sxs-collaboration/spectre pull request #208
Opened 2017-09-15 18:55 UTC by wthrowe

This adds support to the AdamsBashforthN TimeStepper for local time stepping.  RungeKutta3 continues to only work with global time stepping, but implements the same interface.  This does not cover the driver and communication routines because we don't have the infrastructure for those in place yet.

2017-09-15 18:59 UTC, wthrowe commented
Known question: Where does LagrangePolynomial belong?

2017-09-15 22:29 UTC, kidder requested changes
for some of the commits

2017-09-15 22:29 UTC, kidder commented on src/DataStructures/GeneralIndexIterator.hpp
> +/// make_GeneralIndexIterator is provided for easier construction.
check doc (may need ())

2017-09-15 22:29 UTC, kidder commented on src/DataStructures/GeneralIndexIterator.hpp
> +  iterator_type cbegin() const { return current_.cbegin(); }
noexcept everything that is noexcept

2017-09-15 22:29 UTC, kidder commented on src/DataStructures/GeneralIndexIterator.hpp
> +GeneralIndexIterator<std::decay_t<Container>> make_GeneralIndexIterator(
make_general_...

2017-09-15 22:29 UTC, kidder commented on src/Numerical/Spectral/LagrangePolynomial.hpp
> +double LagrangePolynomial(const Iterator& index_point,
lagrange_polynomial

2017-09-15 22:29 UTC, kidder commented on src/Numerical/Spectral/LagrangePolynomial.hpp
> +double LagrangePolynomial(size_t j, double x,
snake_case

2017-09-15 22:29 UTC, kidder commented on tests/Unit/Numerical/Spectral/Test_LagrangePolynomial.cpp
> +      CHECK(LagrangePolynomial(std::next(control.begin(),
use + instead of next

2017-09-15 22:29 UTC, kidder commented on src/Utilities/CachedFunction.hpp
> +  using Input = typename Map::key_type;
input

2017-09-15 22:29 UTC, kidder commented on src/Utilities/CachedFunction.hpp
> +  using Output = typename Map::mapped_type;
output

2017-09-15 22:29 UTC, kidder commented on src/Utilities/CachedFunction.hpp
> +auto make_CachedFunction(Function function,
make_cached_function

2017-09-15 22:29 UTC, kidder commented on src/Utilities/CachedFunction.hpp
> +  using Output = std::result_of_t<Function&(const Input&)>;
output

2017-09-15 22:29 UTC, kidder commented on tests/Unit/Utilities/Test_CachedFunction.cpp
> +  // [make_CachedFunction_example]
check if need ///

2017-09-18 19:57 UTC, wthrowe commented
Addressed comments and clang-tidy, reset all the author dates so the commits show up in order in GitHub.  Changes to commits that have not been reviewed yet were immediately squashed.

One of the Travis builds had (and presumably will again have) a -Werror failure related to boost::optional that appears to just be the compiler's static analyzer not understanding the class.  I'm not sure of a way to fix that other than adding warning pragmas.

2017-09-19 21:57 UTC, nilsdeppe requested changes

2017-09-19 21:57 UTC, nilsdeppe commented on src/Time/Time.hpp
> +  /// physically meaningful.
"So this can be used as the key to a map"

2017-09-19 21:57 UTC, nilsdeppe commented on src/Time/TimeSteppers/TimeStepper.hpp
> +  /// defined to allow that.
`vector` -> neighbors, first value is self

`deque` -> time history

2017-09-19 21:57 UTC, nilsdeppe commented on src/Time/TimeSteppers/RungeKutta3.hpp
> +  std::vector<std::reference_wrapper<const FluxVars>> coupling_args;;
remove extra `;`

2017-09-19 21:57 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +  /// Convert an iterator over history entries to one over their times.
one -> an iterator

2017-09-19 21:57 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +  /// Find the step on a give side containing the given time.  Steps
give -> given

2017-09-19 21:57 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +  // Start and end of the stepwe are trying to take
step we

2017-09-19 21:57 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +          return TimeSteppers::AdamsBashforthN::get_coefficients(
reduce qualifiers?

2017-09-20 20:00 UTC, fmahebert commented on src/Time/Time.hpp
> +  /// use as the comparitor in a map.  The returned ordering does not
comparator

2017-09-21 22:42 UTC, nilsdeppe requested changes

2017-09-21 22:42 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +    // preious call) and the times of the side data being coupled
previous call

2017-09-21 22:42 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +    // Step on each side containing the boundary step we are currently
"The step on each side"

2017-09-21 22:42 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +      // Advance any side step where we've moved into the next one.
Advance the step of any side where we've moved into the next step

2017-09-21 22:42 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +          const auto make_lagrange_iterator = [&](const HistoryIterator& it) {
only capture what's needed

2017-09-21 22:42 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +  }
add namespace style comments at end of long for loops

2017-09-21 22:42 UTC, nilsdeppe commented on tests/Unit/Time/TimeSteppers/Test_AdamsBashforthN.cpp
> +double quartic_side1(double x) { return c10 + x * c11; }
how are these related to each other?

2017-09-21 22:42 UTC, nilsdeppe commented on tests/Unit/Time/TimeSteppers/Test_AdamsBashforthN.cpp
> +    history[side].emplace_back(t, NCd(unused),
indent

2017-09-21 22:42 UTC, nilsdeppe commented on tests/Unit/Time/TimeSteppers/TimeStepperTestUtils.hpp
> +  // Make sure history is being cleaned up.
Mention that twenty is arbitrary, won't be exceeded in general cases

2017-09-21 22:42 UTC, nilsdeppe commented on src/Time/Time.hpp
> +  /// the temporal ordering, so is useful when an ordering is
so it's useful

2017-09-27 21:25 UTC, wthrowe commented
Trying to silence the warnings causing the Travis build failure with pragmas is somewhat problematic.  Some of them can be eliminated without trouble, but some of the warnings are nonlocal: they appear not in the time stepper but in the class used to represent the data.  For now that means some random function in the test, but this presumably means we will get warnings from DataVector or something when we try to use this in a simulation.

GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635

2017-09-28 01:13 UTC, kidder commented
So, to be sure I understand, you are talking about the maybe-uninitialized warnings caused by the use of boost::optional.  Or are there other warnings?  Given the link you posted, I would suggest turning the maybe-uninitialized warnings off via compiler flag rather than pragmas if this is problematic

2017-10-02 17:31 UTC, wthrowe commented
That was what I was talking about, but I've realized I can avoid the optional by using make_arithmetic_value or the thing it's being replaced with, so silencing the warnings shouldn't be necessary.

2017-10-12 14:58 UTC, wthrowe commented
The fact that there are unsuppressable clang-tidy warnings that you can't fix is apparently intentional and not considered a bug: https://reviews.llvm.org/D26418#655058 (bullet 3).

2017-10-12 20:33 UTC, kidder requested changes

2017-10-12 20:33 UTC, kidder commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +    // as deriv_coef.
(i.e. the sum of the capital i s)

2017-10-12 20:33 UTC, kidder commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +   * An explanation of the computation being performed by this
define k as the order of AB

2017-10-18 19:51 UTC, nilsdeppe approved these changes

2017-10-18 19:52 UTC, kidder approved these changes

2017-10-18 19:52 UTC, merged