Have compute tags in GeneralRelativity use mutating functions 1/2
sxs-collaboration/spectre pull request #2107
Opened 2020-03-16 22:51 UTC by carmaza

## Proposed changes

This set of commits allow compute items in GR to use the mutating (return-by-reference) version of the corresponding functions.

The treatment for ComputeSpacetimeQuantities will be left for a separate PR.

### Types of changes:

- [ ] Bugfix
- [ x] New feature
- [ ] Refactor

### Component:

- [x ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-03-16 23:18 UTC, kidder requested changes
Thank you for doing this!

2020-03-16 23:18 UTC, kidder commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Test_Ricci.cpp
> +      gr::Tags::SpatialRicciCompute<3, Frame::Inertial, DataVector>>(
DataVector -> DataType

2020-03-16 23:18 UTC, kidder commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Test_WeylElectric.cpp
> +  test_compute_item_in_databox<3>(dv);
test with double

2020-03-16 23:18 UTC, kidder commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Test_Ricci.cpp
> +  test_compute_item_in_databox<3, IndexType::Spatial>(dv);
test with double

2020-03-16 23:18 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
> +    gsl::not_null<tnsr::a<DataType, SpatialDim, Frame>*> gauge_source,
note clang-tidy complains about `gauge_source` here vs `gauge_source_h` in the cpp

2020-03-16 23:52 UTC, nilsdeppe requested changes
I very much echo @kidder's thank you! This is a huge help and I really appreciate it :) 

I have a couple minor suggestions about using `destructive_resize` + for loop to zero some of the tensor at the beginning of the functions instead of using `make_with_value`. This'll help reduce allocations even more.

I'm happy for you to squash any changes to my comments immediately.

2020-03-16 23:52 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +  *gauge_source_h =
would `destructive_resize` work here? This current does a bunch of allocations even if the tensor is already allocated. You might have to zero the data after the `destructive_resize` call, but that's still cheaper than the allocations

2020-03-16 23:52 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/Ricci.cpp
> +  *result = make_with_value<tnsr::aa<DataType, SpatialDim, Frame, Index>>(
would `destructive_resize` work here? This current does a bunch of allocations even if the tensor is already allocated

2020-03-16 23:52 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +  *ex_curv = make_with_value<tnsr::ii<DataType, SpatialDim, Frame>>(pi, 0.);
would `destructive_resize` work here? This current does a bunch of allocations even if the tensor is already allocated

2020-03-16 23:52 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Constraints.cpp
> +  destructive_resize_components(constraint, get_size(get(gamma2)));
:+1: I think this code  combining `destructive_resize` with the for loop is exactly what would reduce allocations in other place :)

2020-03-17 15:56 UTC, nilsdeppe approved these changes
![image](https://user-images.githubusercontent.com/13531030/76875022-5ddd3900-6846-11ea-8e27-65d6b6674a9d.png)

2020-03-17 18:41 UTC, kidder approved these changes

2020-03-18 15:55 UTC, merged