Support volume base tags in InterfaceComputeTags
sxs-collaboration/spectre pull request #2111
Opened 2020-03-17 19:53 UTC by nilsdeppe

## Proposed changes

Adds support for volume_tags that are base tags with no known type to the
interface tags for mutating compute tags. This cannot be done with non-mutating
compute tags, but since we are moving to mutating compute tags everywhere it
doesn't really matter.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-03-17 22:08 UTC, nilsvu requested changes
LGTM, thanks for making these changes! please squash directly

2020-03-17 22:08 UTC, nilsleiffischer commented on tests/Unit/Domain/Test_InterfaceItems.cpp
> +                                 const double& x, const int& y) noexcept {
remove `&`s?

2020-03-19 18:04 UTC, nilsdeppe commented
@nilsleiffischer squashed and rebased on develop. Thanks for the review!

2020-03-19 19:21 UTC, kidder approved these changes

2020-03-19 19:21 UTC, kidder commented
@wthrowe  can you please look at this

2020-03-19 19:48 UTC, wthrowe approved these changes

2020-03-19 20:53 UTC, nilsvu approved these changes

2020-03-19 20:59 UTC, merged