Support volume base tags in elliptic code
sxs-collaboration/spectre pull request #2112
Opened 2020-03-17 21:53 UTC by nilsleiffischer

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-03-18 00:54 UTC, nilsdeppe requested changes
LGTM! Some suggestions on TMPL things that I'm happy for you to squash immediately

2020-03-18 00:54 UTC, nilsdeppe commented on src/Elliptic/DiscontinuousGalerkin/NumericalFluxes/FirstOrderInternalPenalty.hpp
> +  using argument_tags = tmpl::append<
I think this is:
```cpp
tmpl::push_front<typename FluxesComputer::argument_tags,
                 ::Tags::NormalDotFlux<AuxiliaryFieldTags>...,
                 ::Tags::div<::Tags::Flux<AuxiliaryFieldTags, tmpl::size_t<Dim>,
                                          Frame::Inertial>>...,
                 ::Tags::Normalized<domain::Tags::UnnormalizedFaceNormal<Dim>>,
                 fluxes_computer_tag>;
```

2020-03-18 00:54 UTC, nilsdeppe commented on src/Elliptic/DiscontinuousGalerkin/NumericalFluxes/FirstOrderInternalPenalty.hpp
> +  using volume_tags = tmpl::append<tmpl::list<fluxes_computer_tag>,
This is:
```cpp
tmpl::push_front<get_volume_tags<FluxesComputer>,
                 fluxes_computer_tag>;
```

2020-03-18 00:54 UTC, nilsdeppe commented on src/Elliptic/FirstOrderComputeTags.hpp
> +  using argument_tags = tmpl::append<tmpl::list<vars_tag, fluxes_computer_tag>,
This is:
```cpp
tmpl::push_front<typename FluxesComputer::argument_tags,
                 vars_tag, fluxes_computer_tag>;
```

2020-03-18 00:54 UTC, nilsdeppe commented on src/Elliptic/FirstOrderComputeTags.hpp
> +  using volume_tags = tmpl::append<tmpl::list<fluxes_computer_tag>,
This is:
```cpp
tmpl::push_front<get_volume_tags<FluxesComputer>,
                 fluxes_computer_tag>;
```

2020-03-18 00:54 UTC, nilsdeppe commented on src/Elliptic/FirstOrderComputeTags.hpp
> +  using argument_tags = tmpl::append<tmpl::list<vars_tag>,
`tmpl::push_front`

2020-03-18 00:54 UTC, nilsdeppe commented on src/Elliptic/DiscontinuousGalerkin/ImposeInhomogeneousBoundaryConditionsOnSource.hpp
> +        tmpl::append<
`tmpl::push_front`

2020-03-18 00:54 UTC, nilsdeppe commented on src/Elliptic/DiscontinuousGalerkin/ImposeInhomogeneousBoundaryConditionsOnSource.hpp
> +        tmpl::append<
`tmpl::push_front`

2020-03-18 10:27 UTC, nilsleiffischer commented
done @nilsdeppe, thanks for reviewing!

2020-03-18 13:35 UTC, nilsdeppe submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/13531030/76966079-c63a2200-68fb-11ea-86b0-996544644f3c.png)

LGTM! I have submitted a fix for CI in #2113

2020-03-19 02:02 UTC, nilsdeppe approved these changes

2020-03-19 09:29 UTC, nilsleiffischer commented
@kidder or @wthrowe could you provide the second review?

2020-03-19 19:39 UTC, kidder approved these changes

2020-03-19 19:52 UTC, wthrowe approved these changes

2020-03-19 21:00 UTC, merged