Add option to replace object files with stubs during linking
sxs-collaboration/spectre pull request #2123
Opened 2020-03-19 17:53 UTC by nilsdeppe

## Proposed changes

- After linking object files into a library or executable the object files are no longer needed (except if you are frequently rebuilding, then they can be helpful) but still take up a lot of disk space. This adds two CMake flags to have the linker replace object files with empty stubs. While not recommended to be used during normal development, on CI enabling these flags reduces disk usage of the GCC6 debug target by ~2.6GB and of the clang debug targets by ~1.5GB. I think the main way to further reduce disk usage would be to switch to shared libraries.

@wthrowe this implements the stubbing that I talked with you about on the call on Wednesday. Any feedback is greatly appreciated!

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [x] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-03-19 20:28 UTC, wthrowe requested changes

2020-03-19 20:28 UTC, wthrowe commented on tools/WrapExecutableLinker.sh
> +    # preserves times), then use touch to create a new file empty
Too many "file"s, I think.  Probably you want to remove this one.

2020-03-19 20:28 UTC, wthrowe commented on tools/WrapExecutableLinker.sh
> +            rm ${temp_file}
This script is at least mostly quoting things correctly, so quote the variables in this section, too.

2020-03-19 20:42 UTC, nilsdeppe commented
Thanks for the review @wthrowe! Pushed two fixups for the linker scripts

2020-03-19 20:45 UTC, wthrowe commented
Looks good.  Squash.

2020-03-19 20:57 UTC, nilsdeppe commented
Squashed. Thanks again @wthrowe!

2020-03-19 21:00 UTC, wthrowe approved these changes

2020-03-20 13:20 UTC, nilsvu requested changes
<s>please squash directly</s> actually, nvm, let's just merge this

2020-03-20 13:20 UTC, nilsvu commented on cmake/SetupBuildInfo.cmake
> +  "Replace executable object files with stubs to reduce disk usage."
<s>add "after linking"</s>

2020-03-20 13:20 UTC, nilsvu approved these changes

2020-03-21 22:33 UTC, kidder approved these changes

2020-03-21 23:47 UTC, merged