Add constexpr and noexcept to SegmentId and ElementId where applicable
sxs-collaboration/spectre pull request #214
Opened 2017-09-19 17:18 UTC by gsb76

2017-09-19 19:56 UTC, gsb76 commented on src/Domain/ElementId.hpp
> +  constexpr ElementId() noexcept = default;
This doesn't compile - figure out noexcept-ness of make_array as this is used to default construct a member variable of ElementId

2017-09-19 20:21 UTC, fmahebert commented on src/Domain/SegmentId.hpp
> +    return {refinement_level_ + 1, index_ << 1};
ditto

2017-09-19 20:21 UTC, fmahebert commented on src/Domain/SegmentId.hpp
> +  return {refinement_level_ + 1, 1 | (index_ << 1)};
ditto

2017-09-19 20:21 UTC, fmahebert commented on src/Domain/SegmentId.hpp
> +  return {refinement_level_ - 1, index_ >> 1};
Was this bit magic used here to solve performance problems? If not, I'd favor the much more readable `floor(index_/2)` given in the comment.

2017-09-25 21:18 UTC, nilsdeppe requested changes

2017-09-25 21:18 UTC, nilsdeppe commented on src/Utilities/MakeArray.hpp
> +        indexes...> /* unused */) noexcept(noexcept(std::array<typename std::
`std::decay_t`

2017-09-25 21:18 UTC, nilsdeppe commented on src/Utilities/MakeArray.hpp
> +make_array_impl(
Use `// clang-format off` and `// clang-format on`, then format this to something sane

2017-09-25 21:18 UTC, nilsdeppe commented on src/Utilities/MakeArray.hpp
>    return std::array<typename std::decay<T>::type, size>{
`typename std::decay<T>::type` to `std::decay_t<T>`

2017-09-25 21:18 UTC, nilsdeppe commented on src/Utilities/MakeArray.hpp
> +    T&& value) noexcept(noexcept(MakeArray_detail::
override clang-format

2017-09-25 21:18 UTC, nilsdeppe commented on src/Utilities/MakeArray.hpp
>        cpp17::conjunction_v<std::is_same<std::decay_t<T>, std::decay_t<V>>...>,
`tmpl2::flat_all_v<cpp17::is_same_v<std::decay_t<T>, std::decay_t<V>>`

2017-09-25 21:18 UTC, nilsdeppe commented on tests/Unit/Domain/Test_SegmentId.cpp
> -  std::cout << noexcept(make_array<3>(0)) << std::endl;
????

2017-09-25 21:18 UTC, nilsdeppe commented on tests/Unit/Domain/Test_SegmentId.cpp
>  #include <iostream>
Write tests to check noexcept-ness of make_array inside the make array tests.

2017-09-28 01:16 UTC, kidder requested changes
t

2017-09-28 01:16 UTC, kidder commented on tests/Unit/Domain/Test_SegmentId.cpp
> +#include <iostream>
remove

2017-09-28 01:16 UTC, kidder commented on tests/Unit/Domain/Test_SegmentId.cpp
> +#include <iostream>
this is flagged by the second build on Travis...

2017-10-03 21:27 UTC, kidder requested changes

2017-10-03 21:27 UTC, kidder commented on tests/Unit/Domain/Test_SegmentId.cpp
> +
remove blank line

2017-10-05 01:04 UTC, kidder approved these changes

2017-10-05 02:35 UTC, nilsdeppe approved these changes

2017-10-05 02:35 UTC, merged