Add Main chare
sxs-collaboration/spectre pull request #215
Opened 2017-09-19 18:33 UTC by kidder

2017-09-19 20:29 UTC, nilsdeppe requested changes

2017-09-19 20:29 UTC, nilsdeppe commented on src/Parallel/Main.hpp
> +constexpr void typelist_fold(const typelist<Elements...>& /*meta*/,
Do something with this

2017-09-19 20:29 UTC, nilsdeppe commented on src/Parallel/Main.hpp
> +#include "Utilities/TaggedTuple.hpp"
TaggedTuple before TMPL? clang-format

2017-09-19 20:29 UTC, nilsdeppe commented on src/Parallel/Main.hpp
> +/// \tparam Metavariables a struct containing metavariables
remove this

2017-09-19 20:29 UTC, nilsdeppe commented on src/Parallel/Main.hpp
> +/// Metavariables must define the following:
finish this

2017-09-19 20:29 UTC, nilsdeppe commented on src/Parallel/Main.hpp
> +  explicit Main(CkArgMsg* msg);
noexcept

2017-09-19 20:29 UTC, nilsdeppe commented on tests/Unit/Parallel/ParallelTestChares.hpp
> +
The `// template definitions` comment would be helpful

2017-09-19 20:29 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Main.cpp
> +std::unique_ptr<const Parallel::CProxy_ConstGlobalCache<TestMetavariables>>
raw pointer?

2017-09-19 20:29 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Main.cpp
> +std::unique_ptr<const Parallel::CProxy_ConstGlobalCache<TestMetavariables>>
and a comment as to why this is a thing at all

2017-09-19 20:29 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Main.cpp
> +  const auto& cache = *(*global_cache_proxy).ckLocalBranch();
`global_cache_proxy->`

2017-09-20 15:42 UTC, kidder commented on src/Parallel/Main.hpp
> +#include "Utilities/TaggedTuple.hpp"
clang-format orders upper-case before lower-case

2017-09-20 15:42 UTC, nilsdeppe commented on src/Parallel/Main.hpp
> +#include "Utilities/TaggedTuple.hpp"
Okay, that's what I figured, thanks for checking!

2017-09-21 00:58 UTC, nilsdeppe approved these changes

2017-09-21 00:59 UTC, merged