Have AH compute tags function return by reference
sxs-collaboration/spectre pull request #2150
Opened 2020-03-26 03:59 UTC by carmaza

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [x ] New feature
- [ ] Refactor

### Component:

- [x ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-03-30 17:21 UTC, markscheel submitted a review, later dismissed
Looks good to me.

2020-03-30 17:29 UTC, markscheel commented
You asked about prolonged_coords.  Currently you are doing no more allocations than previously. An alternative (probably left to a future PR if we want to do it) would be to have InterpolationTargetApparentHorizon store a Variables containing all the intermediate results, and then there would be a single allocation at initialization of the InterpolationTarget ParallelComponent.

2020-03-30 17:31 UTC, markscheel commented
Actually, yet another alternative would be to allocate a Variables (containing all the intermediate results) just before computing prolonged_coords.  Then there would be no persistent storage, and there would be a single allocation instead of several.

@nilsdeppe opinions on these possibilities for reducing allocations?

2020-03-30 17:35 UTC, nilsdeppe commented
@markscheel using a `Variables` is exactly what I was thinking while looking through this PR :) I also agree that it doesn't need to be done as part of this PR

2020-03-30 17:53 UTC, kidder requested changes
Thank you for doing this!  reviewed with @nilsdeppe

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/ComputeItems.hpp
> +    *result = GeneralizedHarmonic::extrinsic_curvature(
you should be able to call the mutating version of `GeneralizedHarmonic::extrinsic_curvature`

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/ComputeItems.hpp
> +    *result = raise_or_lower_first_index(
should be able to call mutating version of `raise_or_lower_first_index`

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +  static void function(const gsl::not_null<DataVector*> radius,
let's just move the definition of this to the cpp file to avoid including ContainerHelpers.hpp

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  *result = trace(spatial_ricci_tensor, upper_spatial_metric);
is there a mutating version of `trace`?

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  *result = Scalar<DataVector>{square(radius)};
`get(*result) = square(radius);`

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  *result = Scalar<DataVector>{square(radius)};
get(*result) = square(radius);

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  destructive_resize_components(result, normal_one_form.begin()->size());
should not need to do the destructive_resize_components when setting `*result =` an existing object as operator= should do any resize it needs, so omit it here

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  destructive_resize_components(result, unit_normal_vector.begin()->size());
don't need

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  destructive_resize_components(result, grad_normal.begin()->size());
don't need

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  destructive_resize_components(result, spatial_ricci_tensor.begin()->size());
shouldn't need if mutating version calls `destructive_resize_components` or if there is not a mutating version

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  destructive_resize_components(result, radius.size());
don't need

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  destructive_resize_components(result, radius.size());
don't need

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  DataVector& extrinsic_curvature_dot_normal = get(*result);
add comment // using result as temporary

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  DataVector& sin_theta = get(*result);
add comment // using result as temporary

2020-03-30 17:53 UTC, kidder commented on src/ApparentHorizons/StrahlkorperGr.cpp
> +  get(*result) =
add comment // now computing actual result

2020-03-31 18:04 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetApparentHorizon.hpp
> +    auto& radius = get(get<::Tags::TempScalar<2>>(temp_buffer));
Thanks for doing this ❤️

2020-03-31 18:05 UTC, kidder reviewed
you can squash

2020-03-31 20:06 UTC, carmaza commented
Squashed and rebased on develop.

2020-03-31 20:34 UTC, kidder approved these changes

2020-03-31 20:48 UTC, nilsdeppe approved these changes
![image](https://user-images.githubusercontent.com/13531030/78073714-69188480-736f-11ea-9b52-cac07e8fd316.png)

Thank you so much doing this :) Again, very much appreciated :D

2020-04-01 04:33 UTC, merged