Fix default constructor for Orientation, add tests
sxs-collaboration/spectre pull request #219
Opened 2017-09-21 19:05 UTC by gsb76

2017-09-21 23:05 UTC, nilsdeppe requested changes

2017-09-21 23:05 UTC, nilsdeppe commented on src/Domain/Orientation.hpp
> +  Orientation();
add Doxygen comment stating what the default orientation is

2017-09-21 23:05 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Orientations.cpp
> +  CHECK(!custom2.is_aligned());
`CHECK_FALSE`

2017-09-21 23:05 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Orientations.cpp
> +  test_move_semantics(std::move(custom1), custom_copy);  // NOLINT
add comment stating why NOLINT

2017-09-21 23:05 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Orientations.cpp
> +  CHECK(!custom2.is_aligned());
CHECK_FALSE

2017-09-21 23:05 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Orientations.cpp
> +  CHECK(!rotated2d_neg_eta_pos_xi.is_aligned());
`CHECK_FALSE`s

2017-09-21 23:05 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Orientations.cpp
> +  test_move_semantics(std::move(rotated2d_neg_eta_pos_xi),  // NOLINT
why NOLINT?

2017-09-21 23:05 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Orientations.cpp
> +  CHECK(!custom2.is_aligned());
CHECK_FALSE

2017-09-21 23:05 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Orientations.cpp
> +  CHECK(!custom_orientation.is_aligned());
CHECK_FALSE

2017-09-21 23:05 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Orientations.cpp
> +  test_move_semantics(std::move(custom_orientation), custom_copy);  // NOLINT
// clang-tidy: why...?

2017-09-25 21:44 UTC, nilsdeppe approved these changes

2017-09-26 00:45 UTC, kidder approved these changes

2017-09-26 00:45 UTC, merged