Fix Element Frame in ObserveVolumeIntegrals
sxs-collaboration/spectre pull request #2207
Opened 2020-04-11 20:32 UTC by carmaza

## Proposed changes

I've been carrying this fix for a while, but now that I've been changing branches on a daily basis, I'd like it to get merged. It is not clear to me how this will affect `Elliptic` systems, but I'd be happy to discuss that here or in a future PR.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-04-12 09:37 UTC, nilsleiffischer commented
How about you template the event on the frame? That should be enough to keep it compatible with elliptic systems. Is it actually the right thing to do to take the integral in the grid frame for evolution systems?

2020-04-12 16:39 UTC, nilsdeppe commented
@fmahebert any progress on getting the Jacobian determinant into the DataBox or should I do that quick? That would resolve this problem

2020-04-13 18:40 UTC, fmahebert commented
@nilsdeppe This hasn't made it to the top of my priority queue, so it's likely quickest if you do it. I'm happy to be assigned to review it.

2020-04-23 20:21 UTC, carmaza commented
Now that we have a compute tag for the determinant of the inverse Jacobian, we can simply retrieve it from the databox and use it in the action. This should be enough to use the Event.

2020-04-23 20:47 UTC, kidder requested changes
reviewed with @nilsdeppe ; please squash

2020-04-23 20:47 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveVolumeIntegrals.hpp
> +      const Scalar<DataVector> logical_to_inertial_det_jacobian,
det_inv_jacobian

2020-04-23 20:47 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveVolumeIntegrals.hpp
> +    const DataVector inertial_to_logical_det_jacobian =
det_jacobian

2020-04-23 20:47 UTC, kidder commented on tests/Unit/ParallelAlgorithms/Events/Test_ObserveVolumeIntegrals.cpp
> +  const DataVector inertial_to_logical_det_jacobian =
det_jacobian

2020-04-23 20:47 UTC, kidder commented on tests/Unit/ParallelAlgorithms/Events/Test_ObserveVolumeIntegrals.cpp
> +  auto logical_to_inertial_det_jacobian =
det_inv_jacobian

2020-04-23 21:02 UTC, carmaza commented
Squashed. I also fixed a clang-tidy error related to unused variables in the test of the event.

2020-04-23 21:51 UTC, kidder approved these changes

2020-04-23 21:52 UTC, nilsdeppe approved these changes
:+1: LGTM!

![image](https://user-images.githubusercontent.com/13531030/80153228-25d6bd80-858b-11ea-9ae9-09a5c2a97954.png)

2020-04-24 01:03 UTC, merged