Feature/transpose
sxs-collaboration/spectre pull request #221
Opened 2017-09-23 03:24 UTC by kidder

2017-09-23 20:51 UTC, nilsdeppe requested changes

2017-09-23 20:51 UTC, nilsdeppe commented on src/Numerical/LinearOperators/Transpose.hpp
> +#include "DataStructures/Variables.hpp"
This include isn't needed, nothing refers to Variables.

2017-09-23 20:51 UTC, nilsdeppe commented on src/Numerical/LinearOperators/Transpose.hpp
> +               const size_t number_of_chunks, gsl::not_null<T*> transpose) {
take a `const` pointer to a non-`const` object

2017-09-23 20:51 UTC, nilsdeppe commented on src/Numerical/LinearOperators/Transpose.hpp
> +/// \requires `transpose.size()` to be the product of `number_of_chunks` and
`u` has `.data()`

2017-09-23 20:51 UTC, nilsdeppe commented on tests/Unit/Numerical/LinearOperators/Test_Transpose.cpp
> +  for (auto& p : transposed_data) {
use `std::fill`

2017-09-23 20:51 UTC, nilsdeppe commented on tests/Unit/Numerical/LinearOperators/Test_Transpose.cpp
> +      CHECK(ref_to_data[i + chunk_size * j] ==
Should also check the referred to data

2017-09-23 21:34 UTC, fmahebert commented on src/Numerical/LinearOperators/Transpose.hpp
> +/// \tparam T the type of the transposed data
~~Why two template parameters? In the tests the input and output are of the same type. Will there be use cases with different types?~~ Edit: Nevermind, the partial transpose test uses different Variable types...

2017-09-25 16:42 UTC, nilsdeppe submitted a review, later dismissed

2017-09-25 16:42 UTC, nilsdeppe commented
Squash please :)

2017-09-25 21:38 UTC, nilsdeppe approved these changes

2017-09-25 21:38 UTC, merged