Swsh regrid
sxs-collaboration/spectre pull request #2230
Opened 2020-04-21 22:25 UTC by moxcodes

## Proposed changes

Adds a handful of SWSH utilities that I'll need to make future CCE parts easier.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2020-04-21 23:10 UTC, moxcodes commented on src/NumericalAlgorithms/Spectral/SwshTransform.hpp
> +void interpolate_to_collocation(
This should be moved to the cpp

2020-04-22 18:48 UTC, kidder requested changes
reviewed with @nilsdeppe you can squash

2020-04-22 18:48 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshTransform.hpp
> +      while (source_coefficient_metadata_iterator !=
can you add a comment stating what this sets `source_coefficient_metadata_iterator` to so we don't have to figure it out...

2020-04-22 18:48 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshTransform.hpp
> +  auto source_modes =
should be const

2020-04-22 18:48 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshFiltering.cpp
> +  if (exponential_alpha != 0.0) {
use LIKELY

2020-04-22 18:48 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshFiltering.cpp
> +  if (limit_l < l_max) {
and if applicable here LIKELY or UNLIKELY

2020-04-22 18:48 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshFiltering.cpp
> +  if (limit_l < l_max) {
again if applicable LIKELY/UNLIKELY

2020-04-22 18:48 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshCoefficients.cpp
> +  template void goldberg_to_libsharp_modes(                                   \
you only need to instantiate the one that calls the other

2020-04-22 23:10 UTC, moxcodes commented
fixups squashed in.
Cheers!

2020-04-22 23:33 UTC, nilsdeppe approved these changes
![image](https://user-images.githubusercontent.com/13531030/80043583-22323080-84d0-11ea-8640-fd03da127d7a.png)

2020-04-23 00:57 UTC, kidder approved these changes

2020-04-23 19:28 UTC, merged