Change Domain compute tags to use mutating functions
sxs-collaboration/spectre pull request #2231
Opened 2020-04-22 03:59 UTC by carmaza

## Proposed changes

Mostly, this PR changes compute tags in Domain to use `function` members that return by reference. In addition, this PR adds a compute item for the determinant of the inverse Jacobian.

Some of these changes might not be necessary, so I split them into several commits so it is easier for me to `drop` the ones we do not need.

I left some `const_item_type` in the tags because I'm not sure if they can be removed at all. I didn't try super hard though, so feel free to point me to where the change is effectively possible.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-04-22 19:10 UTC, kidder requested changes
squash!  Thank you for doing this!
reviewed with @nilsdeppe

2020-04-22 19:10 UTC, kidder commented on src/DataStructures/Tensor/EagerMath/Determinant.hpp
> +                 const Tensor<T, Symm, index_list<Index0, Index1>>& tensor) {
noexcept

2020-04-22 19:10 UTC, kidder commented on src/DataStructures/Tensor/EagerMath/Determinant.hpp
> +    const Tensor<T, Symm, index_list<Index0, Index1>>& tensor) {
noexcept

2020-04-22 19:10 UTC, kidder commented on src/Domain/LogicalCoordinates.hpp
> +//@}
`// @}`

2020-04-22 19:10 UTC, kidder commented on src/Domain/LogicalCoordinates.hpp
> +//@{
`// @{`

2020-04-22 19:10 UTC, kidder commented on src/Domain/InterfaceComputeTags.hpp
> +      result->emplace(d, d);
`emplace` will not overwrite an existing element, so please use `insert_or_assign`

2020-04-22 23:11 UTC, carmaza commented
Squashed! thanks for the quick review.

2020-04-22 23:29 UTC, nilsdeppe approved these changes
LGTM! Thank you so much for making these changes :smile:

2020-04-23 01:22 UTC, kidder approved these changes

2020-04-23 19:29 UTC, merged