Compute elliptic DG penalty from element geometry
sxs-collaboration/spectre pull request #2269
Opened 2020-05-12 14:43 UTC by nilsleiffischer

# Proposed changes

This PR allows the elliptic internal penalty flux to compute the penalty from the element geometry. This is possible as of #1725, since we can communicate non-tensor quantities across element boundaries in numerical fluxes now.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-06-09 07:18 UTC, nilsleiffischer commented
@wthrowe @geoffrey4444 could you review this one?

2020-06-09 20:00 UTC, wthrowe commented
I'll do it, but I don't know if I'll get to it today.

2020-06-11 23:40 UTC, wthrowe requested changes

2020-06-11 23:40 UTC, wthrowe commented on src/Elliptic/DiscontinuousGalerkin/NumericalFluxes/FirstOrderInternalPenalty.hpp
> +DataVector penalty(const DataVector& element_size,
This documentation is not showing up.

2020-06-12 02:03 UTC, geoffrey4444 requested changes

2020-06-12 02:03 UTC, geoffrey4444 commented on src/Elliptic/DiscontinuousGalerkin/NumericalFluxes/FirstOrderInternalPenalty.hpp
> -    // This will improve conditioning on non-uniform meshes.
Why not add a comment saying what good values for C are now that N^2/h doesn’t have to be included?

2020-06-12 15:44 UTC, nilsleiffischer commented
Thanks for reviewing @wthrowe @geoffrey4444. I pushed a fixup in response to your comments, please take a look.

2020-06-12 16:24 UTC, wthrowe commented on src/Elliptic/DiscontinuousGalerkin/NumericalFluxes/FirstOrderInternalPenalty.hpp
> +DataVector penalty(const DataVector& element_size,
Maybe I'm missing something, but I still don't see it.

2020-06-23 08:43 UTC, nilsleiffischer commented
@wthrowe @geoffrey4444 could you take a look at the fixup?

2020-06-23 08:49 UTC, nilsleiffischer commented on src/Elliptic/DiscontinuousGalerkin/NumericalFluxes/FirstOrderInternalPenalty.hpp
> +DataVector penalty(const DataVector& element_size,
For me it shows up in search and here `docs/html/namespaceelliptic_1_1dg_1_1NumericalFluxes.html#abc7d2e4d1a8be9fd29f5fda8c9dcd7c8`

I did occasionally have the issue that new documentation didn't show up in search; deleting the `docs` directory helped, though I haven't investigated the issue in any detail

2020-06-23 16:11 UTC, wthrowe requested changes
clang-tidy has a legitimate complaint.  Otherwise this looks good.

2020-06-23 16:11 UTC, wthrowe commented on src/Elliptic/DiscontinuousGalerkin/NumericalFluxes/FirstOrderInternalPenalty.hpp
> +DataVector penalty(const DataVector& element_size,
Looks like it was a doxygen version issue.  I upgraded to 1.8.17 and the problem went away.  Sorry about that.

2020-06-24 08:43 UTC, nilsleiffischer commented
@geoffrey4444 please take a look

2020-07-02 11:50 UTC, nilsleiffischer commented
@geoffrey4444 please take a look

2020-07-02 14:05 UTC, geoffrey4444 submitted a review, later dismissed

2020-07-03 08:22 UTC, nilsleiffischer commented
Squashed and rebased. Thanks for reviewing @geoffrey4444 @wthrowe!

2020-07-09 10:25 UTC, nilsleiffischer commented
This looks like it's ready to go @wthrowe

2020-07-12 18:12 UTC, wthrowe submitted a review, later dismissed
Looks good, but there's a conflict now.

2020-07-13 17:15 UTC, nilsleiffischer commented
@wthrowe rebased and ready to go

2020-07-13 18:26 UTC, wthrowe approved these changes

2020-07-16 17:36 UTC, nilsleiffischer commented
@wthrowe I think this is ready to go

2020-07-16 18:36 UTC, wthrowe commented
Needs a second approval.

@geoffrey4444 ping

2020-07-16 19:38 UTC, geoffrey4444 approved these changes

2020-07-16 19:51 UTC, merged