Enable clang-tidy CI checks on private branches
sxs-collaboration/spectre pull request #2270
Opened 2020-05-12 17:14 UTC by nilsleiffischer

## Proposed changes

For pull requests we check code that changed relative to the base
branch and for pushes to private branches we check code that changed
relative to the repository's `develop` branch.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-05-19 14:59 UTC, nilsleiffischer commented
@kidder @nilsdeppe this is ready for you to review whenever you get the chance

2020-05-20 02:39 UTC, kidder commented
@nilsleiffischer can you push a change that removes a nolint so I can see clang-tidy failing CI on your branch...

2020-06-01 14:55 UTC, kidder commented
you can squash

2020-06-03 21:36 UTC, nilsdeppe requested changes

2020-06-03 21:36 UTC, nilsdeppe commented on .github/workflows/Tests.yaml
> +  # to the base branch and for pushes we check code that changed relative to the
let's just compare to sxs-collaboration/develop. That's what Travis was doing and worked really well.

2020-06-05 13:01 UTC, nilsdeppe reviewed
LGTM, please go ahead and squash

2020-06-06 00:10 UTC, kidder reviewed
yes, squash

2020-06-09 17:37 UTC, kidder approved these changes

2020-06-09 17:37 UTC, kidder commented
@nilsdeppe I think this just needs your approval

2020-06-11 20:33 UTC, nilsdeppe approved these changes

2020-06-11 20:33 UTC, merged