Add named tags for the temporary tags used inside GH RHS
sxs-collaboration/spectre pull request #2274
Opened 2020-05-14 14:55 UTC by nilsdeppe

## Proposed changes

- I find that having the tags be named makes the code a lot easier to read.
- In the future, with the gauge computed inside the GH RHS it'll be easier to avoid duplicate computations if tags are named, rather than having the gauge code say "Oh, I want `temp::A<5>`"

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-05-14 17:01 UTC, geoffrey4444 submitted a review, later dismissed
This makes this code much nicer...thanks!

2020-05-14 21:32 UTC, moxcodes submitted a review, later dismissed

2020-05-17 01:51 UTC, kidder requested changes

2020-05-17 01:51 UTC, kidder commented on src/Evolution/Systems/GeneralizedHarmonic/DuDtTempTags.hpp
> +struct Gamma12 : db::SimpleTag {
Gamma1Gamma2 just in case someone introduces more damping parameters...

2020-05-17 14:35 UTC, geoffrey4444 approved these changes

2020-05-18 00:38 UTC, moxcodes approved these changes

2020-05-18 01:42 UTC, kidder approved these changes

2020-05-18 01:43 UTC, merged