Output DetInvJac in ExportCoordinates
sxs-collaboration/spectre pull request #2286
Opened 2020-05-18 17:31 UTC by geoffrey4444

## Proposed changes

Have ExportCoordinates*D output not only the inertial coordinates but also the determinant of the inverse Jacobian. This is a useful diagnostic for grid quality; values far from one indicate compression or expansion of the grid.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-05-18 17:45 UTC, nilsdeppe submitted a review, later dismissed

2020-05-18 18:14 UTC, nilsvu requested changes

2020-05-18 18:14 UTC, nilsleiffischer commented on src/Executables/ExportCoordinates/ExportCoordinates.hpp
> +    components.emplace_back(element_name + "DetInvJacobian", get(det_inv_jac));
It's probably better to replace `"DetInvJacobian"` -> `db::tag_name<domain::Tags::DetInvJacobian<Frame::Logical, Frame::Inertial>>()` (this is how we label fields in `ObserveFields`, for instance)

2020-05-18 23:57 UTC, nilsdeppe approved these changes

2020-05-19 14:54 UTC, nilsvu approved these changes

2020-05-20 17:14 UTC, merged