Add pre- and post-commit hooks
sxs-collaboration/spectre pull request #23
Opened 2017-05-27 14:18 UTC by nilsdeppe

2017-05-27 14:53 UTC, kidder requested changes

2017-05-27 14:53 UTC, kidder commented on tools/Hooks/CheckFileSize.py
> +    like "3.5 MB" for it's given 'num'-parameter.
it's -> its

2017-05-27 14:53 UTC, kidder commented on tools/Hooks/ClangFormat.py
> +    """ used to find the binary if it does not exist returns None """
binary if  ->   binary; if

2017-05-27 14:53 UTC, kidder commented on tools/Hooks/ClangFormat.py
> +
remove this blank line

2017-05-27 14:53 UTC, kidder commented on tools/Hooks/pre-commit.sh
> +# If commit_files is empty, then no_license_found search standard input, which
search -> searches

2017-06-02 00:21 UTC, kidder commented on tools/Hooks/ClangFormat.py
> +
two blank lines

2017-06-02 00:24 UTC, kidder requested changes
please remove one of the blank lines

2017-06-02 00:24 UTC, nilsdeppe commented on tools/Hooks/ClangFormat.py
> +
This is mandated by python style guide, pep8...

2017-06-02 00:26 UTC, nilsdeppe commented on tools/Hooks/ClangFormat.py
> +
Here's the link: https://www.python.org/dev/peps/pep-0008/#blank-lines

2017-06-23 18:56 UTC, kidder approved these changes

2017-06-23 21:44 UTC, merged