Move snippet end marker to cover entire 'EventsAndTriggers' section, …
sxs-collaboration/spectre pull request #2303
Opened 2020-05-29 19:14 UTC by erfz

…change Completion event to occur on final slab (slab 100)

## Proposed changes

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [x] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-05-29 19:15 UTC, erfz commented
@isaaclegred

2020-05-29 19:23 UTC, isaaclegred commented
@kidder do you want to look at this?

2020-05-29 20:14 UTC, kidder reviewed
This change looks good.  Could you please also modify `docs/Tutorials/Visualization.md` to add something like "Be sure to keep the Completion event, as without it the executable will run indefinitely.  In this case, it will terminate after 100 slabs."  after the sentence that "This will observe ... 100."  

Also please check that you do get volume output at both slab 0 and 100 with these settings.  You may need to terminate at 101...

2020-06-01 21:41 UTC, erfz commented
@kidder I've included your suggestion and I've checked that the resultant xdmf generates grid data at time 0 and another at time 1e-1. So I believe that slabs 0 and 100 are both being included.

2020-06-02 05:31 UTC, kidder commented
@erfz you can squash your two commits.  

But shouldn't the final time be 1.0?  (100 slabs of size 0.1)  You can look do `h5dump -g element_data.dat ObserveExample1DPlaneWavePeriodicReductions.h5` to look at the contents of the h5 file.  Each ObservationId should have a group with an attribute `observation_value` with the value of the time.  You should get 2 groups one whose value will be 0 and the other 1.  
If the xdmf is giving different times, there is a problem with whatever is generating the xdmf.

2020-06-02 16:59 UTC, erfz commented
@kidder I've squashed the commits. As for the time discrepancy, turns out I just mixed up the output xdmf files I was looking at (I previously was looking at a run of EvolvePlaneWave with only 10 slabs). All is good in the xdmf.

2020-06-02 17:05 UTC, kidder submitted a review, later dismissed

2020-06-02 17:18 UTC, isaaclegred requested changes

2020-06-02 17:18 UTC, isaaclegred commented on tests/InputFiles/ScalarWave/ObserveExample.yaml
>    VolumeFileName: "ObserveExample1DPlaneWavePeriodicVolume"
@erfz can you update the tutorial (`spectre/docs/Tutorials/Visualization.md`) to reflect the fact that the executables are now called `EvolvePlaneWave...` and no longer `EvolveScalarWave...`

2020-06-02 17:19 UTC, nilsvu submitted a review, later dismissed

2020-06-02 18:11 UTC, isaaclegred commented
@erfz looks good to me, feel free to squash!

2020-06-02 19:06 UTC, isaaclegred approved these changes

2020-06-02 19:15 UTC, kidder approved these changes

2020-06-02 19:16 UTC, nilsvu approved these changes

2020-06-03 15:08 UTC, merged