Cce weyl time transform
sxs-collaboration/spectre pull request #2313
Opened 2020-06-04 21:46 UTC by moxcodes

## Proposed changes

Include a missing coordinate transformation to the Weyl scalars, ensuring that their frame is consistent with the asymptotic inertial time that they are interpolated to before being output to the h5.

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2020-07-09 21:52 UTC, kidder requested changes
reviewed with @nilsdeppe

2020-07-09 21:52 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/ScriObserveInterpolated.hpp
> +      double interpolation_time = 0;
0. (add decimal)

2020-07-09 21:52 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/ScriObserveInterpolated.cpp
> +  get(psi_3) = get(psi_3) + 0.5 * get(eth_u) * get(psi_4);
use `+=` for these expressions

2020-07-09 21:52 UTC, kidder commented on src/Evolution/Systems/Cce/Actions/ScriObserveInterpolated.cpp
> +  const auto& eth_u =
comment that this is eth_u_prime in the documentation

2020-07-09 21:52 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_ScriObserveInterpolated.cpp
> +  ;
remove this

2020-07-09 21:52 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_ScriObserveInterpolated.cpp
> +  return get(get<Tags::ScriPlus<Tags::Psi0>>(random_values)).data() *
could all of these NP quantities be tested with python instead of reimplementing the c++?

2020-07-09 21:52 UTC, kidder commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_ScriObserveInterpolated.cpp
> +  // TOOD the expected file checks
ping?

2020-07-10 02:38 UTC, moxcodes commented
fixups posted.
Cheers!

2020-07-10 02:52 UTC, nilsdeppe reviewed
Just a couple string manipulation suggestions. I'm happy for you to squash everything once @kidder has a chance to look

2020-07-10 02:52 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_ScriObserveInterpolated.cpp
> +  for(auto& char : tag_name) {
Can you use Boost's replace algorithms? https://www.boost.org/doc/libs/1_73_0/doc/html/string_algo/usage.html#id-1.3.3.5.7

2020-07-10 02:52 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/Cce/Actions/Test_ScriObserveInterpolated.cpp
> +  while(tag_name[tag_name.size() - 1] == '_') {
You may be able to use Boost's trimming https://www.boost.org/doc/libs/1_73_0/doc/html/string_algo/reference.html#header.boost.algorithm.string.trim_hpp to achieve this, or just `tag_name.erase(tag_name.find_last_not_of('_'))`

2020-07-10 03:35 UTC, moxcodes commented
Added another fixup that simplifies the string manip with boost functions.
Cheers!

2020-07-10 03:39 UTC, nilsdeppe reviewed
LGTM!

2020-07-10 04:18 UTC, kidder reviewed
you can squash

2020-07-10 05:53 UTC, moxcodes commented
squashed.
Cheers!

2020-07-10 15:04 UTC, nilsdeppe submitted a review, later dismissed
The macOS error is something that actually uses macOS will need to deal with, if it persists.

2020-07-10 17:44 UTC, nilsdeppe commented
@moxcodes this needs to be rebased

2020-07-10 17:45 UTC, kidder commented
@moxcodes this needs a rebase; I cannot reproduce the mac os error on my laptop;

2020-07-10 18:01 UTC, moxcodes commented
Rebased on develop.
Cheers!

2020-07-10 18:09 UTC, kidder submitted a review, later dismissed

2020-07-10 20:49 UTC, nilsdeppe submitted a review, later dismissed

2020-07-10 20:50 UTC, nilsdeppe commented
Restarted CI because of an unrelated test timeout

2020-07-13 18:19 UTC, moxcodes commented
force-pushed to fix a conflict. In the process, also dropped the resolution on the ScriObserveInterpolated test slightly to make it a bit faster (it had a timeout on the most recent CI run).
Cheers!

2020-07-15 02:21 UTC, nilsdeppe approved these changes

2020-07-15 03:35 UTC, kidder approved these changes

2020-07-15 03:36 UTC, merged