Replace make_overloader as wrapper for EquationOfState
sxs-collaboration/spectre pull request #2331
Opened 2020-06-19 21:26 UTC by fmahebert

## Proposed changes

Equation of state calls different interfaces based on the ThermodynamicDim of the equation of state. Previously, switching between different interfaces was done by wrapping the calls inside lambdas inside `make_overloader`. Now we have access to c++17 and `if constexpr`, so this PR updates the equation of state call wrappers to `if constexpr`.

This is usually a very simple change, except in the (non-MHD) Valencia characteristic test, where I had to change a lambda to a function to expose the ThermodynamicDim template parameter.

Also fix a few clang-tidy complaints... but I still expect this PR to fail clang-tidy due to the usual boost rootfinder false-positives.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-06-20 23:11 UTC, kidder requested changes
missed one clang-tidy about nested namespaces in RelativisticEuler/Valencia/Characteristics.cpp

2020-06-21 02:31 UTC, fmahebert commented
😞 Squashed in the fix to the clang-tidy commit.

2020-06-22 17:01 UTC, kidder approved these changes

2020-06-22 17:02 UTC, kidder commented
clang-tidy errors are the boost ones we've never figured out

2020-06-22 19:48 UTC, nilsdeppe approved these changes
Thanks for doing this! :D

2020-06-23 04:46 UTC, merged