Fix noexcept-ness in MakeArray
sxs-collaboration/spectre pull request #234
Opened 2017-09-28 17:57 UTC by gsb76

2017-09-28 17:59 UTC, gsb76 commented
I will rebase #214 off of this PR

2017-09-28 19:38 UTC, kidder requested changes

2017-09-28 19:38 UTC, kidder commented on src/Utilities/MakeArray.hpp
> +    // clang-format off
where is the matching clang-format on

2017-09-28 20:32 UTC, nilsdeppe commented
Need to test that the calculations work correctly

2017-09-29 18:44 UTC, nilsdeppe requested changes

2017-09-29 18:44 UTC, nilsdeppe commented on tests/Unit/Utilities/Test_MakeArray.cpp
> +              "The assumed noexcept-ness is not what was calculated.");
Failed Unit.Utilities.MakeArray testing noexcept calculation of make_array.

2017-09-29 21:00 UTC, nilsdeppe commented
Squash the two commits into one, please.

2017-09-29 21:01 UTC, nilsdeppe requested changes

2017-09-29 21:01 UTC, nilsdeppe commented on tests/Unit/Utilities/Test_MakeArray.cpp
> +static_assert(!noexcept(make_array<2>(DoesThrow{})),
please use `not`

2017-10-03 19:42 UTC, kidder approved these changes

2017-10-03 19:42 UTC, nilsdeppe approved these changes

2017-10-03 19:42 UTC, merged