Add std::sort and std::transform wrappers
sxs-collaboration/spectre pull request #2340
Opened 2020-06-25 23:40 UTC by nilsdeppe

## Proposed changes

- More STL wrappers to make life easier.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-06-25 23:50 UTC, fmahebert submitted a review, later dismissed

2020-06-26 01:05 UTC, geoffrey4444 requested changes

2020-06-26 01:05 UTC, geoffrey4444 commented on src/Utilities/Algorithm.hpp
> +/// Convenience wrapper around std::min_element
std::sort?

2020-06-26 01:20 UTC, nilsdeppe commented on src/Utilities/Algorithm.hpp
> +/// Convenience wrapper around std::min_element
Whoops, thanks! I squashed this in

2020-06-26 02:32 UTC, geoffrey4444 approved these changes

2020-06-26 02:41 UTC, kidder approved these changes

2020-06-26 04:07 UTC, fmahebert approved these changes

2020-06-27 17:47 UTC, merged