Add If and Unless control flow actions
sxs-collaboration/spectre pull request #2356
Opened 2020-07-06 14:09 UTC by nilsleiffischer

## Proposed changes

Add `If` and `Unless` actions to run action lists based on runtime conditions. Also allow multiple `RepeatUntil` loops in an action list by labeling them.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-07-06 21:38 UTC, wthrowe requested changes

2020-07-06 21:38 UTC, wthrowe commented on tests/Unit/Parallel/Actions/Test_Goto.cpp
> +        3);
Test the other cases.

2020-07-06 22:03 UTC, nilsdeppe requested changes
I think we should actually try to remove the `Repeat` code because:
- Then we don't need to have a bool in the DataBox as often
- I think the code is clearer if the actions themselves determine when they are done
- We want to move to have actions only for sending and receiving data wherever possible. This is because the resulting code is much simpler to work with.

The If-Else I am completely against, for the same reasons as above. I don't see why we should add something that will ultimately, in my experience, make the control flow much harder to follow. I think it is the actions themselves that need to decide what to call next. Why can't that be done in this case?

@kidder your thoughts?

2020-07-07 07:25 UTC, nilsleiffischer commented
@nilsdeppe I need a way to run the preconditioner action list in every step of the linear solver (current use of `RepeatUntil`) and to run the linear solver actions only on the finest multigrid level (current use of `If`/`Unless`). More specifically, here's the current action list for the Multigrid-Schwarz preconditioned linear solve:

```cpp
using solve_actions = tmpl::list<
    // Prepare linear solver step
    ::Actions::If<
        LinearSolver::multigrid::Tags::IsFinestLevel,
        tmpl::list<LinearSolver::Actions::TerminateIfConverged<linear_solver>,
                   typename linear_solver::prepare_step>,
        PrepareLinearSolverStepLabel>,
    // Run multigrid preconditioner
    typename preconditioner::prepare_solve,
    ::Actions::RepeatUntil<
        LinearSolver::Tags::HasConverged<preconditioner>,
        tmpl::list<typename preconditioner::prepare_step_down,
                   smooth_actions<pre_smoother,
                                  LinearSolver::multigrid::VcycleDownLabel>,
                   build_linear_operator_actions,
                   typename preconditioner::perform_step_down,
                   typename preconditioner::prepare_step_up,
                   smooth_actions<post_smoother,
                                  LinearSolver::multigrid::VcycleUpLabel>,
                   build_linear_operator_actions,
                   typename preconditioner::perform_step_up>,
        PreconditioningLabel>,
    // Perform linear solver step
    ::Actions::If<LinearSolver::multigrid::Tags::IsFinestLevel,
                  tmpl::list<typename linear_solver::perform_step,
                             Actions::RunEventsAndTriggers>,
                  PerformLinearSolverStepLabel>>;
```

If find this action list actually quite nicely readable, don't you? The reason the control flow is not built into the actions is that the components (GMRES, multigrid, Schwarz solver) don't (need to) know that they are used as outer linear solver, preconditioner and smoother, respectively. Each component can be used as a standalone solver. An alternative to the control flow actions that I can think of is to build a wrapper metafunction such as `run_multigrid` that basically implements `RepeatUntil` itself and returns an action list. Do you have another suggestion?

2020-07-08 17:40 UTC, nilsdeppe commented
- No, I don't think this is easy to read. I don't understand it at all. I have no idea where any communication is happening. The entire point of the actions was to demarcate communication.
- Just get rid of things like `RepeatUntil` and `If`, passing in as template parameters to the control flow action what it needs to decide. I do this for subcell and it's significantly easier to read than this.

Talking with @kidder we think it would be worth having a call to discuss why we don't like what you're doing. We would be okay if you keep `If` and `RepeatUntil` isolated to the elliptic code, but we think a discussion first would be useful. How about Monday after the spectre call?

2020-07-08 18:04 UTC, nilsleiffischer commented
@nilsdeppe I appreciate the offer to discuss, Monday after the meeting works!

2020-07-13 16:56 UTC, nilsleiffischer commented
A few notes from our call with @nilsdeppe @moxcodes @fmahebert:

1. We would like to write control-flow logic in C++ instead of our own action-list language. Actions can do the control-flow and need only be split at communication points. Actions call into functions that do all of the heavy lifting.
2. It would be good to make loops visible in the action list instead of hiding them in GOTOs. Perhaps we can adjust `RepeatUntil` to work better with 1.

Marking as _in progress_. Will need to investigate how I can improve the action-list structure of the Multigrid solver.

2020-09-21 13:39 UTC, nilsleiffischer commented
Superseded by #2495

2020-09-21 13:39 UTC, closed without merging