Modernize CMakeLists 5
sxs-collaboration/spectre pull request #2359
Opened 2020-07-06 17:18 UTC by fmahebert

## Proposed changes

Update more CMakeLists.txt

To verify in particular:
- In `src/Parallel`, there are two `.ci` files (`ConstGlobalCache.ci` and `Main.ci`). If I correctly understand things, there is no need for these, or the resulting generated code, to be part of the library targets because we wrap the generated code in via our `ConstGlobalCache.hpp` and `Main.hpp` headers. Is this correct?
- In `src/ParallelAlgorithms`, I've added a new library `ParallelAlgorithms` to contain everything except the `LinearSolver` headers, which already had their own library. Is this a reasonable choice?

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2020-07-08 17:55 UTC, kidder requested changes

2020-07-08 17:55 UTC, kidder commented on src/ParallelAlgorithms/LinearSolver/ConjugateGradient/CMakeLists.txt
> +  ResidualMonitorActions.hpp
I think `.` is before `A` in the alphabet. (it was in `src/ParallelAlgorithms/EventsAndTriggers/CMakeLists.txt` in the previous commit... so one needs to be fixed)

2020-07-08 17:55 UTC, kidder commented on src/ParallelAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +  ResidualMonitorActions.hpp
again

2020-07-08 18:50 UTC, fmahebert commented
@kidder I've squashed in the fix (thanks for catching that!) and rebased

2020-07-08 19:16 UTC, nilsdeppe commented
To answer your questions:

- Yes
- Yes, we'll likely adapt it in the future, but currently that directory doesn't have any libs. One option that would be slightly better is having a `ParallelDg`, `Events`, and `EventsAndTriggers` libs. I'm not sure what the heck the `Actions` directory is supposed to be, I didn't write anything in there

2020-07-08 19:49 UTC, kidder submitted a review, later dismissed

2020-07-08 20:08 UTC, fmahebert commented
@nilsdeppe I've added a fixup that splits the ParallelAlgorithms into multiple libraries. Can you check the split is what you had in mind?

2020-07-08 20:54 UTC, nilsdeppe reviewed
LGTM please squash!

2020-07-08 20:58 UTC, fmahebert commented
Thanks for the feedback, @kidder and @nilsdeppe! This should be ready to go now.

2020-07-09 14:33 UTC, nilsdeppe approved these changes

2020-07-09 19:25 UTC, kidder approved these changes

2020-07-09 19:28 UTC, merged