Add OneOverOneFormMagnitudeTag
sxs-collaboration/spectre pull request #2376
Opened 2020-07-16 22:26 UTC by MarloMo

## Proposed changes

Add OneOverOneFormMagnitudeTag and OneOverOneFormMagnitudeCompute for computing the OneOverOneFormMagnitude normal vector to the horizon.

### Types of changes:

- [ ] Bugfix
- [ x] New feature
- [ ] Refactor

### Component:

- [ x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-07-17 01:58 UTC, geoffrey4444 submitted a review, later dismissed

2020-07-20 16:58 UTC, kidder requested changes

2020-07-20 16:58 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +/// The OneOverOneFormMargnitude is the reciprocal of the magnitude of the
typo  Margnitude -> Magnitude

2020-07-20 16:58 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +  static DataVector function(
Please change this to a void function that takes as a first argument `const gsl::not_null<DataVector*> one_over_magnitude`.   We are making all compute items follow this convention

2020-07-20 16:58 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +    return 1.0 / get(magnitude(normal_one_form, inverse_spatial_metric));
here you will need to say `*one_over_magnitude = 1.0 ...` instead of returning something

2020-07-21 05:52 UTC, kidder reviewed
looks good, you can squash

2020-07-24 04:24 UTC, geoffrey4444 approved these changes

2020-08-10 19:11 UTC, kidder approved these changes

2020-08-11 00:46 UTC, merged