Change how prefix and variable tags interact with each other
sxs-collaboration/spectre pull request #2399
Opened 2020-07-31 21:59 UTC by kidder

## Proposed changes

Change the behavior of  `db::add_prefix<Prefix, Tag, Args...>` when `Tag` is a `::Tags::Variables<TagsList>` (with `TagsList = tmpl::list<Tag0,...,TagN>`) from producing a new tag `Prefix<::Tags::Variables<PrefixedTagsList, Args...>` with `PrefixedTagsList` = `tmpl::list<Prefix<Tag0, Args...>, ...,Prefix<TagN, Args...>>` to producing a new tag `::Tags::Variables<PrefixedTagsList, Args...>`.

I am making this change because it simplifies the code in `DataStructures/DataBox/PrefixHelpers.hpp` and because I found the tag `deriv<Variables<deriv<Var0>,...,deriv<VarN>>` to be potentially confusing as I read it to hold second derivatives...   In addition, there are several prefix tags that set `type = typename Tag::type` which is incorrect if `Tag` is a `::Tags::Variables`.

In cases where `db::add_prefix<Prefix, Tag, Args...>`  was never called on a `::Tags::Variables`, change to `Prefix<Tag, Args...>`.

In cases where `db::add_prefix<Prefix, Tag, Args...>` was always called on a
`::Tags::Variables`, rename the type alias to`db::variables_tag_with_tags_prefixed_by<Prefix, Tag, Args...>`

Remove `db::get_variables_tags_list` and `db::variables_tag_with_tags_list`
as they no longer need to handle a `::Tag::Variables` with both an outer and inner prefixes.

In addition, there are a few cleaning commits, and a couple of added `static_assert`s based on errors triggered when making these changes.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [x] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

@wthrowe there are two remaining uses of `db::add_tag_prefix` in `src/Time/Actions/RecordTimeStepperData.hpp` and `tests/Unit/Time/Actions/Test_SelfStartActions.cpp` because tests don't use a `Variables` as the `type` of the tag that is being wrapped.  Is this intentional, or can I update the tests to use a `Variables`?

@nilsleiffischer there are still many remaining uses of `db::add_tag_prefix` in the linear solver code, again because tests don't use a `Variables` as the `type` of the tag that is being wrapped.  Is this intentional?

2020-07-31 22:00 UTC, kidder commented
- clang-tidy errors are from the boost root-finder that we have not been able to ignore
- mac build is broken (see #2397)

2020-08-03 21:17 UTC, wthrowe requested changes
The use of the time-stepping code on non-Variables is intentional and I would prefer if it continued to work.

2020-08-03 21:17 UTC, wthrowe commented on src/DataStructures/Variables.hpp
> +      tmpl2::flat_all<tt::is_a_v<Tensor, typename Tags::type>...>::value);
`flat_all_v`

2020-08-03 21:17 UTC, wthrowe commented on src/Evolution/Actions/ComputeTimeDerivative.hpp
> + * `db::variables_tag_with_tags_prefixed_by<step_prefix, variables_tag>`, where
This comment is out-of-date.  The action doesn't do any prefixing of anything anymore.

2020-08-03 21:17 UTC, wthrowe commented on src/Time/Tags.hpp
> +#include "Utilities/TypeTraits/IsA.hpp"
You don't use this.

2020-08-05 14:34 UTC, wthrowe commented
Thinking about this more, what I really want is to ensure that we can integrate a stack-based data structure in the future.  We've sort of been using double and array for that and I was thinking of adding a new container type with tags, but maybe it should be a "Variables\<double>" specialization.  If that idea seems sane, I retract my objection to the time changes.

2020-08-05 15:39 UTC, nilsvu requested changes
The linear solver uses `db::add_tag_prefix` because it doesn't care if the tag holds a Variables or some vector type such as `DataVector` or `DenseVector`. It only requires the type supports addition, scalar multiplication and an inner product.

2020-08-05 15:39 UTC, nilsvu commented on src/ParallelAlgorithms/LinearSolver/Tags.hpp
> -    // operator
Could you keep this comment around? E.g. add this:

```cpp
// No "Linear" prefix is added to the tag's `name()` because a Krylov subspace always refers to a linear operator
```

2020-08-05 15:39 UTC, nilsvu commented on src/DataStructures/Tags/TempTensor.hpp
> +// Distributed under the MIT License.
We don't have separate `Tags/` directories anywhere else in the code as far as I'm aware. What do you think about naming this file `DataStructures/TempTensorTags.hpp` instead?

2020-08-05 15:39 UTC, nilsvu commented on tests/Unit/Helpers/DataStructures/TestTags.hpp
> +struct PrependIndex : ::db::PrefixTag, ::db::SimpleTag {
Template this class on `UpLo` and `Dim`?

2020-08-05 15:39 UTC, nilsvu commented on tests/Unit/Helpers/DataStructures/TestTags.hpp
> +struct ContractFirst : ::db::PrefixTag, ::db::SimpleTag {
"Contract" implies another index to contract with, but the `type` just removes the first index. Name `RemoveFirstIndex` instead?

2020-08-05 15:39 UTC, nilsvu commented on src/DataStructures/Variables.hpp
> +        (std::is_same_v<typename Tags::type, typename WrappedTags::type> &&
Can you replace `&&` -> `and` here and below?

2020-08-05 15:39 UTC, nilsleiffischer commented on src/DataStructures/DataBox/PrefixHelpers.hpp
> +using variables_tag_with_tags_prefixed_by =
Isn't this metafunction just `db::add_tag_prefix` with the restriction that it accepts nothing but a Variables tag? I think you can just delete it and we use `db::add_tag_prefix` everywhere.

2020-08-05 15:39 UTC, nilsleiffischer commented on src/Elliptic/Actions/InitializeSystem.hpp
> +        db::variables_tag_with_tags_prefixed_by<
You can leave these as-is, just using `db::add_tag_prefix` (same applies to many occurrences below)

(If your reasoning for this change is that you want to assert the tag is actually a variables tag: I think it's not the responsibility of the prefix utility metafunction to assert that. The class working with the tag, in this case `InitializeSystem`, should assert that what it receives is a variables tag if it expects one.)

2020-08-05 15:39 UTC, nilsleiffischer commented on src/NumericalAlgorithms/RootFinding/TOMS748.hpp
> +  auto result = boost::math::tools::toms748_solve(f, lower_bound, upper_bound,
This change seems unrelated to the rest of the commit. Better factor it into a separate commit if that's not too painful to do.

2020-08-05 15:39 UTC, nilsleiffischer commented on src/ParallelAlgorithms/LinearSolver/Gmres/Gmres.hpp
> +   * `LinearSolver::Tags::Orthogonalization< LinearSolver::Tags::IterationId>`
nitpick: delete space, same in line 214

2020-08-06 05:03 UTC, nilsdeppe commented
The idea of a `Variables<double>` specialization is something that I would be happy to see. I've thought a bit about that in the past, since we could continue to get vector instructions through Blaze that way by using the static vector class. Adding a `Requires` specilization on Variables for the tag type is probably the way to go unless someone has a better idea. That way at least the memory layout is hidden from users.

2020-08-07 16:03 UTC, wthrowe commented
After looking into it, it looks like "Variables\<double>" (whether a specialization of Variables or not) is impossible to write without absurd tradeoffs.  We can't do Blaze math on Tensors because accessing the contents of multiple tensors as a big array violates C++'s stupid aliasing rules.  Allowing non-owning Tensors would work, but that has a memory overhead of more than a factor of 2.

I need to think a bit about how this affects what changes I'm OK with to the time stepping code.  It's nice to be able to integrate a few ODEs without having to go through the DataVector infrastructure (I've done it with our std::array math), but this now looks like it will be useless for any real runs.

2020-08-07 19:01 UTC, wthrowe commented
Actually, I have one more idea.  I need to flesh out the details.

2020-08-12 20:09 UTC, kidder commented on src/DataStructures/Tags/TempTensor.hpp
> +// Distributed under the MIT License.
The plan is to move towards having separate `Tags/` directories with separate files per tag in order to reduce dependencies.  This is the first step...

2020-08-13 03:24 UTC, kidder commented on tests/Unit/Helpers/DataStructures/TestTags.hpp
> +struct PrependIndex : ::db::PrefixTag, ::db::SimpleTag {
I just removed this and `ContractFirst` as I don't use them

2020-08-13 04:35 UTC, kidder commented
@wthrowe @nilsleiffischer I've pushed fixups.  In the interest of getting this merged sooner (as DataBox simplifications depend upon this) I've reverted the places I had replaced `add_tag_prefix` with `variables_tag_with_tags_prefixed_by` so they will work as before on either Variables or a non-Variables.  We can revisit this in the future as this does not affect the DataBox simplifications I am working on

2020-08-13 08:45 UTC, nilsvu submitted a review, later dismissed
Ok LGTM @kidder. Please don't wait for my re-approval if anything gets changed, since I'll be on vacation.

2020-08-13 08:45 UTC, nilsleiffischer commented on src/Elliptic/Actions/InitializeSystem.hpp
> + * fields_tag>`
The revert commit left over a bunch of these formatting changes

2020-08-13 18:01 UTC, wthrowe commented
Looks good.  Squash, etc.

2020-08-13 19:42 UTC, kidder commented
@wthrowe I've squashed, etc.

2020-08-13 21:11 UTC, wthrowe submitted a review, later dismissed
Clang-tidy failure is Boost internals.

2020-08-13 23:04 UTC, nilsdeppe reviewed
I'm happy with this. Just one missing include, the rest looks fine to me

2020-08-13 23:04 UTC, nilsdeppe commented on src/DataStructures/Tags.hpp
> +           db::tag_name<RhsTag>() + ")";
Need an include for tagname

2020-08-14 00:33 UTC, kidder commented
@nilsdeppe @wthrowe fixed the include

2020-08-14 00:41 UTC, nilsdeppe submitted a review, later dismissed

2020-08-14 00:46 UTC, wthrowe submitted a review, later dismissed

2020-08-14 15:16 UTC, nilsdeppe approved these changes
CI error is clang-tidy in boost internals

2020-08-14 15:59 UTC, wthrowe approved these changes

2020-08-14 15:59 UTC, merged