Clean up file-checking scripts
sxs-collaboration/spectre pull request #240
Opened 2017-09-29 21:13 UTC by wthrowe

2017-09-30 04:37 UTC, kidder requested changes

2017-09-30 04:37 UTC, kidder commented on tools/FileTestDefs.sh
> +# This file defined the framework for running simple textual checks on
defines

2017-09-30 23:15 UTC, kidder approved these changes

2017-10-01 01:22 UTC, nilsdeppe approved these changes

2017-10-01 01:23 UTC, merged