Focally lifted flat endcap
sxs-collaboration/spectre pull request #2401
Opened 2020-08-02 23:16 UTC by markscheel

## Proposed changes

This adds a map to be used for blocks of a cylindrical binary domain: the blocks that are between the two excised regions.

It uses the infrastructure of #2373 (and currently depends on and includes #2373).

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2021-03-05 23:13 UTC, markscheel commented
Had to modify the restrictions on map parameters. Now `ctest -R CylindricalFlatEndcap --repeat-until-fail 1000` passes.

2021-03-12 17:34 UTC, nilsdeppe requested changes
feel free to squash things immediately

2021-03-12 17:34 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/FocallyLiftedFlatEndcap.hpp
> +      const gsl::not_null<std::array<tt::remove_cvref_wrap_t<T>, 3>*>&
Why not take the `not_null` by value like we normally do? It's just a pointer

2021-03-12 17:34 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/FocallyLiftedFlatEndcap.cpp
> +        // The equal_within_roundoff below has an implicit scale of 1,
might be good to move the info in this C++ comment into the `ASSERT` message

2021-03-12 17:34 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/FocallyLiftedFlatEndcap.cpp
> +    : center_(center), radius_([&]() noexcept {
`&` -> `&radius`

2021-03-12 17:34 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/CylindricalFlatEndcap.cpp
> +         "The map has only been tested for the case "
line break seems a bit early on this line :shrug:

2021-03-17 20:19 UTC, markscheel commented
Made changes and squashed.  

Also added another commit that fixes the not_null arguments to functions in FocallyLiftedEndcap.

2021-03-17 23:53 UTC, nilsdeppe submitted a review, later dismissed
LGTM!

2021-03-17 23:53 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/FocallyLiftedFlatEndcap.cpp
> +            "Cannot have zero radius.  Note that this ASSERT implicitly"
[only if there are any "real" change requests] add space after `implicitly`

2021-03-23 14:13 UTC, markscheel commented
Rebased (since I had to rebase other PRs in this series because of CI problems unrelated to this PR).

2021-03-23 16:27 UTC, nilsdeppe submitted a review, later dismissed

2021-03-24 20:45 UTC, markscheel commented
Rebased to remove conflicts.

2021-03-25 01:21 UTC, moxcodes reviewed
Looks good -- feel free to squash any change immediately.

2021-03-25 01:21 UTC, moxcodes commented on src/Domain/CoordinateMaps/FocallyLiftedFlatEndcap.hpp
> + * For `FocallyLiftedFlatEndcap`, \f$x^i\f$ is always between
`FocallyLiftedInnerMaps::FlatEndcap`, I think.

2021-03-25 01:21 UTC, moxcodes commented on docs/Images/Domain/CoordinateMaps/CylindricalFlatEndcap.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
I very much appreciate these figures, they make a world of difference in understanding the maps.

2021-03-25 21:57 UTC, markscheel commented
Fixed doc issue and squashed.

2021-03-25 22:01 UTC, nilsdeppe approved these changes

2021-03-25 22:08 UTC, moxcodes approved these changes

2021-03-30 16:51 UTC, merged