Time-dependence in block_logical_coordinates
sxs-collaboration/spectre pull request #2408
Opened 2020-08-06 22:30 UTC by markscheel

## Proposed changes

Allow block_logical_coordinates to work with time-dependent maps,
and allow it to work for points in the grid frame, not just the inertial frame.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-08-13 22:50 UTC, nilsdeppe commented
@markscheel CI exploded here...

2020-08-14 15:41 UTC, markscheel commented
Ugh. It's complaining that I'm passing a parameter 'time' that isn't used.  It is used in one `if constexpr` branch but not in the other :cry: I guess I need to make two functions and not use `if constexpr`.

2020-08-14 15:46 UTC, nilsdeppe commented
you can do one of two things that are cleaner:
- mark the parameter as `[[maybe-unused]]`
- do `(void)time` in the `else` branch
I personally prefer the second since then you always know why/how you are using the argument

2020-08-20 19:06 UTC, kidder requested changes
squash everything into a single commit; reviewed with @nilsdeppe

2020-08-20 19:06 UTC, kidder commented on src/Domain/BlockLogicalCoordinates.cpp
> +          // Currently the only map that a Block can return is GridToInertial.
Currently we only support Grid and Inertial frames in the block, so make sure Frame is ::Frame::Grid. ( The Inertial case was handled above.)

2020-08-20 22:26 UTC, markscheel commented
changed comment, squashed, rebased on develop.

2020-08-20 22:33 UTC, kidder submitted a review, later dismissed

2020-08-20 22:35 UTC, nilsdeppe submitted a review, later dismissed

2020-08-21 03:31 UTC, kidder commented
@markscheel can you force push, CI seems to have failed to start for some reason and I can't figure out how to get it out of its current state...

2020-08-21 15:55 UTC, kidder approved these changes

2020-08-21 16:11 UTC, nilsdeppe approved these changes

2020-08-21 19:10 UTC, merged