Add root bracketing for a function that may be undefined at some points.
sxs-collaboration/spectre pull request #2429
Opened 2020-08-13 23:51 UTC by markscheel

This brackets a root that is known to live in a given interval.
The function being bracketed returns a boost::optional and might
be invalid at some points in the interval.

This will be useful to bracket roots that are near an excision region.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-08-18 23:19 UTC, moxcodes reviewed
A few suggestions and concerns, many of which might just indicate that I require clarification.

2020-08-18 23:19 UTC, moxcodes commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +  if (not(y1 and y2 and y1.get() * y2.get() <= 0.0)) {
to be explicit, it's probably better to either `static_cast<bool>(y1)` to make it totally clear that you're evaluating the boost::optional in the argument of the if, or if that's bulky to define a `bool y1_defined = static_cast<bool>(y1);` before the if to be used in condition checking.

2020-08-18 23:19 UTC, moxcodes commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +    std::vector<double> xx(x.size() * 2 - 1);
I think it would be nice to come up with a better set of names for the `xx` and `yy` - maybe `subdivided_x` or `bisected_x` or similar?

2020-08-18 23:19 UTC, moxcodes commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +
(mostly a style point, feel free to disagree) I'd find this helper routine easier to understand if it were broken up into two routines - one that found a pair of valid points in the domain, and one that given the pair of valid points tries to find the root by exploring relative to those points. I think (based on my understanding of this function) that should largely just be breaking this up into its intuitive first and second parts. Or have I misunderstood the control flow of this function's recursion?

2020-08-18 23:19 UTC, moxcodes commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +  if (first_valid_index > 0) {
I'm a little bit confused about the logic here -- what happens when the first valid index is 0 and the last valid index is y.size() - 1? It appears that currently this would fall through and recurse on empty arrays, or am I missing something subtle?

2020-08-18 23:19 UTC, moxcodes commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> + * \brief Brackets the single root of the
[nitpick] somewhat unusual line break choice

2020-08-18 23:19 UTC, moxcodes commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> + *
document the erroring conditions: the range of sign change is smaller than 1/2^depth of the interval, or no root exists, and any other error conditions that would be valuable to know but I've overlooked.

2020-08-18 23:19 UTC, moxcodes commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +    ERROR("Too many iterations in bracket_by_contracting");
Should this suggest that the initial guesses be refined or maybe `max_level` be increased?

2020-08-18 23:19 UTC, moxcodes commented on tests/Unit/NumericalAlgorithms/RootFinding/Test_RootBracketing.cpp
> +
Is it true that this does not test the case where the control flow reaches the bounds-contracting helper function and all of the array members are valid, but of the same sign? If not, I think that case (where the sign changes multiple times in the domain and all of the bounds and guess start with the same sign in the valid region) should be tested.

2020-08-19 18:55 UTC, fmahebert requested changes

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> + * some points in the interval.
The phrasing "at some points", to me, implies that `f` could be undefined at any random points in the interval.. but if I correctly understood the rest of the dox, it sounds like the undefined points have to be in contiguous regions on the left and/or right side(s) of the interval.

If this understanding is correct, why not phrase this as "and that `f` may be undefined at the sides of the interval" or similar?

My hope is to make it clearer from the brief what the assumptions are, but if getting the phrasing to be concise and correct is too hard, then perhaps this suggestion is best ignored.

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +  // invalid.
Since you're making an optimization (delaying the evaluation of `f(*lower_bound)`) based on expected input patterns for the guess, I would suggest documenting (around line 187 above) how to take advantage of the optimization. This could help ensure the intended "typical usage" is actually typical.

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> + *
Can this unused comment line be removed? Or is it actually needed by Doxygen?

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +    } else if (y2 and y3 and y2.get() * y3.get() <= 0.0) {
I'm confused by this logic branch. I'll lay out my understanding and perhaps you can tell me where I went wrong.

To reach this point, i.e. to fail the `ifs` on lines 210 and 215, either
- one or more of (y1,y2,y3) are invalid. if either y2 or y3 are invalid, this "else if" branch doesn't help. if y1 is invalid, doesn't that put is in a situation where (y_lower, y_upper) are valid, but y_guess is invalid, thereby violating the assumption stated on line 181?
- all points are valid, but the earlier ifs didn't bracket. this means (y1, y2) have the same sign and (y1, y3) have the same sign. in this case (y2, y3) will have the same sign and this "else if" branch doesn't help either.

Did I misunderstand something?

If my understanding is correct, I would suggest removing the "else if" case and adding a short comment saying why it's not necessary to check it before falling back to the general algorithm.

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +    // First try lower_bound.
I didn't find this comment terribly useful. I would suggest either removing or expanding to give a little more detail, perhaps like "Try remaining simple checks from input points, before moving to the general algorithm" or similar.

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +// containing points that have already been tried fro bracketing.
typo: fro -> for

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +    std::vector<double> xx(x.size() * 2 - 1);
Suggestion: xx -> x_bisected, or similar.

Same for y below

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +        }
I see this check being done in several different locations in the function. Why not replace these multiple checks with a single check on entering the function, at line 53ish?

2020-08-19 18:55 UTC, fmahebert commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +  std::vector<double> xx;
Perhaps x_near_valid_point? and similar for y?

2020-08-21 15:51 UTC, markscheel commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +  if (first_valid_index > 0) {
That case should never occur based on the assumptions. I am adding a check that calls ERROR if that case does occur.

2020-08-21 15:51 UTC, markscheel commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +
I thought about doing this, but the problem is you need to look at more than pairs, and you have to look at more than valid points. For the case "X o X" (where X represents an invalid point and o represents a valid point) you need to look both between points 0 and 1 and between points 1 and 2, because the root can be in either place.  If you consider the 0,1 and 1,2 pairs separately, one of those will fail so you would need an extra condition and many extra iterations if the pair you tried first was the failing one.  Similarly for "X o o o o X" (assuming all the 'o's are the same sign) the root can only be between points 0 and 1 or between points 4 and 5, and it is easiest to check both at once.

2020-08-21 15:51 UTC, markscheel commented on tests/Unit/NumericalAlgorithms/RootFinding/Test_RootBracketing.cpp
> +
I'm prohibiting the case where sign changes multiple times in the domain, because that would mean there is more than one root, but we are assuming only one root. This case now calls an ERROR.

2020-08-21 15:52 UTC, markscheel commented
@fmahebert @moxcodes thanks for the review!  I pushed a fixup commit (and rebased the whole thing on develop).

2020-08-21 15:53 UTC, markscheel commented on src/NumericalAlgorithms/RootFinding/RootBracketing.hpp
> +    } else if (y2 and y3 and y2.get() * y3.get() <= 0.0) {
Nope, you are correct. Fixed now.

2020-08-21 18:19 UTC, moxcodes reviewed
Thanks! I think this definitely makes the code more readable. I'm happy for you to squash once @fmahebert has a chance to look at it.

2020-08-21 18:20 UTC, moxcodes commented
(there's a dox error also about unbalanced f$ that I'm happy for you to squash in as well)

2020-08-21 18:21 UTC, fmahebert reviewed
I am happy with the fixup. I think the documentation clarity is much improved by the expanded examples. Thank you for doing this!

2020-08-23 21:53 UTC, markscheel commented
Fixed doc problem, squashed, rebased.

2020-08-24 15:09 UTC, moxcodes approved these changes

2020-08-24 15:10 UTC, fmahebert approved these changes

2020-08-25 20:54 UTC, moxcodes commented
@sxs-collaboration/spectre-core-devs I think this is ready for final review.
Cheers!

2020-08-27 19:38 UTC, wthrowe approved these changes

2020-08-27 19:38 UTC, merged