Global cache rename
sxs-collaboration/spectre pull request #2433
Opened 2020-08-15 11:23 UTC by markscheel

## Proposed changes

Renames ConstGlobalCache to GlobalCache.

This looks like a huge PR, but should be easy to review commit-by-commit.  Most of the changed lines are from the
first commit that just does a `git mv` of many files.  The next commit does a global-replace ConstGlobalCache->GlobalCache, another commit does 'const_global_cache' -> 'global_cache' (except for some places where the 'const' will remain), and then other commits make Clang-tidy happy because this PR touches many files.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-08-15 17:40 UTC, kidder requested changes
fails to compile (looks like from something merged earlier today)

2020-08-15 17:40 UTC, kidder commented on docs/DevGuide/ParallelExecutable/MinimalExecutable.md
> +- Creates the `GlobalCache` (a nodegroup chare) that holds
another doc place mentioning constant

2020-08-15 17:40 UTC, kidder commented on docs/DevGuide/ParallelExecutable/Concepts.md
> +`GlobalCache` which provides global access to read-only objects,
not `read-only` anymore

2020-08-15 17:42 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmCore.cpp
>        case Phase::AnyOrderFinish:
I think there is a `[[fallthrough]]` attribute to mark that this is intentional...

2020-08-15 20:44 UTC, markscheel commented
Rebased on develop, added fixup commits to make it compile again and addressing PR comments.

2020-08-17 17:38 UTC, nilsdeppe reviewed
LGTM please go ahead and squash

2020-08-17 17:42 UTC, kidder reviewed
yes squash

2020-08-17 20:00 UTC, markscheel commented
Thanks!  Squashed.

2020-08-17 20:05 UTC, nilsdeppe approved these changes

2020-08-18 00:34 UTC, kidder approved these changes

2020-08-18 00:35 UTC, merged