Add UnitNormalVectorTag
sxs-collaboration/spectre pull request #2441
Opened 2020-08-21 04:17 UTC by MarloMo

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ x] New feature
- [ ] Refactor

### Component:

- [ x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-08-21 23:14 UTC, geoffrey4444 requested changes

2020-08-21 23:14 UTC, geoffrey4444 commented on src/ApparentHorizons/Tags.hpp
> +  static tnsr::I<DataVector, 3, Frame> function(
I think you must return by not_null not by value

2020-08-22 04:06 UTC, MarloMo commented on src/ApparentHorizons/Tags.hpp
> +  static tnsr::I<DataVector, 3, Frame> function(
I'm not sure how to change that. Should it be something like:

  using base = OneOverOneFormMagnitude;
  using return_type = DataVector;

'taken from a previous tag'

@geoffrey4444

2020-08-22 17:14 UTC, kidder requested changes

2020-08-22 17:14 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +  using base = UnitNormalVectorCompute;
this should be `UnitNormalVector<Frame>` (i.e. the base struct from which this struct is derived)

2020-08-22 17:14 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +  static tnsr::I<DataVector, 3, Frame> function(
`static void function(gsl::not_null<return_type*> result, ... ) noexcept { ` where the `...` is replaced by the current arguments you have

2020-08-22 17:14 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +    return raise_or_lower_index(unit_normal_one_form, inverse_spatial_metric);
here just call the gsl::not_null version of the function `raise_or_lower_index(result, unit_normal_one_form, inverse_spatial_metric);`

2020-08-22 17:14 UTC, kidder commented on tests/Unit/ApparentHorizons/Test_Tags.cpp
> +  TestHelpers::db::test_compute_tag<
test the new tag (you've duplicated the previous line)

2020-09-01 05:15 UTC, MarloMo commented on src/ApparentHorizons/Tags.hpp
> +  static tnsr::I<DataVector, 3, Frame> function(
`static void function(gsl::not_null<tnsr::I<DataVector, 3, Frame>*> result, one_form ) noexcept { ` is this correct?

2020-09-01 05:41 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +  static tnsr::I<DataVector, 3, Frame> function(
change line 336 to be
```
static void function(gsl::not_null<tnsr::I<DataVector, 3, Frame>*> result,
```

2020-09-03 03:27 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +/// and \f$g^{ij}\f$ is the inverse spatial metric.
okay, the compute item looks good; one more thing I noticed; we are using \gamma^{ij} for the inverse spatial metric, (g is the spacetime metric); you can squash everything when fixing this

2020-09-04 04:03 UTC, kidder commented
okay looks good. please squash

2020-09-07 16:01 UTC, kidder approved these changes

2020-09-07 16:01 UTC, kidder commented
@geoffrey4444 please look at

2020-09-07 16:52 UTC, geoffrey4444 approved these changes

2020-09-07 18:58 UTC, merged