Generalize input file representations of time sequences
sxs-collaboration/spectre pull request #2488
Opened 2020-09-08 16:30 UTC by wthrowe

Everything that wants several times can now take either an explicit list or an infinite evenly spaced sequence.

@geoffrey4444 I think this should add what you need to try adaptive time stepping.

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-09-18 17:56 UTC, nilsdeppe requested changes
Couple minor things. This is really nice! Cleans up a lot of code :) Please go ahead and squash any changes you make

2020-09-18 17:56 UTC, nilsdeppe commented on src/Time/TimeSequence.hpp
> +  /// to that exact or roundoff matches can be handles however the
`handles` -> `handled`? 
`to` -> `so`?

2020-09-18 17:56 UTC, nilsdeppe commented on src/Time/TimeSequence.hpp
> +/// Represents a sequence of times.
Could you explain how the template parameter `T` is used in the documentation? E.g. do I choose it to be a `double`, `size_t`, `int`, `Time`, etc? And in what cases would I want to choose which type

2020-09-18 17:56 UTC, nilsdeppe commented on src/Time/TimeSequence.cpp
> +  p | interval_;
If I remember correctly you should call `TimeSequence<T>::pup(p);` first. https://charm.readthedocs.io/en/latest/charm++/manual.html#allocation-outside-pup

2020-09-18 17:56 UTC, nilsdeppe commented on src/Time/TimeSequence.cpp
> +  p | values_;
Same comment about `TimeSequence<T>::pup(p)`

2020-09-22 20:32 UTC, nilsdeppe reviewed
fixup looks good. Please go ahead and squash :)

2020-10-03 00:06 UTC, nilsdeppe approved these changes

2020-10-05 18:20 UTC, kidder approved these changes

2020-10-05 18:20 UTC, merged