Add rms_separation to DomainHelpers
sxs-collaboration/spectre pull request #254
Opened 2017-10-04 20:23 UTC by gsb76

2017-10-04 22:08 UTC, kidder requested changes

2017-10-04 22:08 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +/// The rms distance in the TargetFrame between corners shared by
between all shared corners in two blocks.

2017-10-04 22:08 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +template <size_t VolumeDim, typename SourceFrame, typename TargetFrame>
Remove SourceFrame template argument; just use Frame::Logical

2017-10-04 22:08 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +template <size_t VolumeDim, typename SourceFrame, typename TargetFrame>
Rewrite this function to take two Blocks; it will return something that contains for each corner that should be shared, the logical coordinates in each Block, and the distance between them in the TargetFrame (may also want the TargetFrame coordinates)

2017-10-04 22:08 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +template <size_t VolumeDim, typename SourceFrame, typename TargetFrame>
Move these functions to Test_DomainCreators.cpp

2017-10-20 21:49 UTC, kidder requested changes

2017-10-20 21:49 UTC, kidder commented on src/DataStructures/IndexIterator.hpp
> +  IndexIterator<Dim>& operator=(IndexIterator<Dim>&&) = default;
Test that these work

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +#include <iostream>
remove

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +#include "DataStructures/IndexIterator.hpp"
move to list above

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  CornerIterator();
document the two constructors .  (i.e. the first iterates over all 2^Dim corners; the second over the 2^(Dim-1) corners of the face in the given direction)

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  operator bool() {
explicit

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +    : index_iterator_([]() {
index_iterator_(Index<VolumeDim>(2))

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +      index_iterator_([]() {
ditto

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +};
no ;

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +      }()){};
no ;

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +template <size_t VolumeDim>
put all the stuff in an anonymous namespace

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +    const Block<VolumeDim, TargetFrame>& nhbr_block) {
nhbr -> neighbor

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +     return neighbor.second.orientation();
clang-format

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  for (CornerIterator<3> cid(direction()); cid; ++cid) {
3 -> VolumeDim

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +    size_t i = cid.index();
inline i in the next line

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +    size_t i = cid.index();
ditto on 3 and i

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  for (size_t i = 0; i < two_to_the(VolumeDim - 1); i++) {
instead of rms, use L_inf norm

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  // Tests for CornerIterator:
remove

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +SPECTRE_TEST_CASE("Unit.Domain.DomainCreators.Find", "[Domain][Unit]") {
test in 1 and 2 dimensions

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  CHECK(mapped<3>(custom_orientation, test_point) == expected);
no <3>  and better name than mapped (e.g. point_in_neighbor_frame)

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +SPECTRE_TEST_CASE("Unit.Domain.DomainCreators.Find", "[Domain][Unit]") {
Find -> TestHelperFunctions

2017-10-20 21:49 UTC, kidder commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +/*
delete

2017-10-20 21:49 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +/*
remove

2017-10-20 21:49 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +
remove

2017-10-20 21:49 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +/*
remove

2017-10-20 21:49 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +#include "Domain/Block.hpp"
check if these includes are still needed

2017-10-26 20:25 UTC, kidder requested changes

2017-10-26 20:25 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +template <size_t VolumeDim>
🔔

2017-10-26 20:25 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +// This constructor is for iterating over all 2^VolumeDim corners.
move this to the declaration above

2017-10-26 20:25 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +// This constructor is for iterating over he 2^(VolumeDim-1) corners of the face
ditto

2017-10-26 21:29 UTC, kidder requested changes

2017-10-26 21:29 UTC, kidder commented on src/DataStructures/IndexIterator.cpp
> +}
compare everything (make it a friend)

2017-10-26 21:29 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +
remove this

2017-10-26 21:29 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  };
no ;

2017-10-26 21:29 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  };
no ;

2017-10-26 21:29 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  };
no ; after functions...

2017-10-26 21:29 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +};
keep this one!

2017-10-27 01:21 UTC, kidder requested changes

2017-10-27 01:21 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
>    size_t index() { return index_; };
missed this one

2017-10-27 20:21 UTC, kidder requested changes

2017-10-27 20:21 UTC, kidder commented on src/DataStructures/IndexIterator.hpp
> +  friend bool operator==(const IndexIterator& lhs, const IndexIterator& rhs) {
definition in cpp file (don't need to say friend there)  noexcept declaration, definition and operator!=

2017-10-27 20:21 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +Point<VolumeDim, Frame::Logical> point_in_neighbor_frame(
Point<...> -> tnsr::I<double,...>

2017-10-27 20:21 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  CornerIterator();
noexcept everything

2017-10-27 20:21 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +class CornerIterator {
remove the bool has_direction and split this into two classes:  VolumeCornerIterator and FaceCornerIterator
Also add operator* to dereference

2017-10-27 20:21 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  CornerIterator();
and we mean EVERYTHING, like literally EVERYTHING (but not the doxygen comments, right Nils?)

2017-10-27 20:42 UTC, kidder requested changes

2017-10-27 20:42 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +Direction<VolumeDim> find_direction(
find_direction_to_neighbor

2017-10-27 20:42 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +Orientation<VolumeDim> find_orientation(
find_neighbor_orientation

2017-10-27 20:42 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +std::array<Direction<VolumeDim>, VolumeDim> as_directions(
get_orthant

2017-10-27 20:42 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +Point<VolumeDim, Frame::Logical> as_point(
get_corner_of_orthant

2017-10-27 20:42 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +    if (max_separation <
replace if statement with
max_separation = std::max(max_separation, magnitude(...));

2017-10-31 20:52 UTC, gsb76 commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +Point<VolumeDim, Frame::Logical> point_in_neighbor_frame(
:bell:

2017-10-31 21:28 UTC, kidder requested changes

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> -  explicit operator bool() {
keep this

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  bool operator*() noexcept { return index_ < two_to_the(VolumeDim); }
this should replace operator()() using its body

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +      corner_[i] = 2 * static_cast<int>(get_nth_bit(index_, i)) - 1;
update corner in operator++; just return it here

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  std::array<int, VolumeDim> corner_;
= make_array<VolumeDim>(-1);

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  VolumeCornerIterator() noexcept;
= default

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +template <size_t VolumeDim>
delete

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +// Iterates over the 2^(VolumeDim-1) logical corners of the face of a
move above previous line

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  bool operator*() noexcept { return index_ < two_to_the(VolumeDim); }
use the operator()() body

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  bool operator*() noexcept { return index_ < two_to_the(VolumeDim); }
move operator* body to explicit bool (which you need to add)

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +    index_++;
remove

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +    while (get_nth_bit(index_, direction_.dimension()) ==
replace with do {} while()

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
>      std::array<int, VolumeDim> result;
add corner_ member and update it in the operator++

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +                 : 0) {}
corner_ needs to be initialized correctly

2017-10-31 21:28 UTC, kidder commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  for (VolumeCornerIterator<3> vci; *vci; ++vci) {
🙄

2017-11-02 22:34 UTC, kidder requested changes

2017-11-02 22:34 UTC, kidder commented on src/DataStructures/IndexIterator.cpp
> +// template <size_t Dim>
template and explicit instantiations

2017-11-03 12:57 UTC, nilsdeppe requested changes
please squash right away, this was the only thing I could find.

2017-11-03 12:57 UTC, nilsdeppe commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +  for (auto neighbor : host_block.neighbors()) {
`const auto&`

2017-11-03 16:56 UTC, nilsdeppe approved these changes

2017-11-03 18:10 UTC, kidder approved these changes

2017-11-04 01:38 UTC, merged