Add tag for DG formulation
sxs-collaboration/spectre pull request #2549
Opened 2020-10-12 01:32 UTC by nilsdeppe

## Proposed changes

Add an option tag and tag so we can store the DG formulation in the DataBox.

Note that I add a `dg::Tags` namespace so I have to add `::` in a bunch of places that use `::Tags` but are inside the `dg` namespace.

Depends on:
- [ ] #2548 

Only the following commits are new:
- Add tags for dg::Formulation (with 167 additions and 22 deletions.)

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-10-12 04:57 UTC, nilsdeppe commented
Did some silly CMake stuff that I need to clean up before this should be looked at...

2020-10-12 22:32 UTC, nilsdeppe commented
I've sorted out my CMake goofs...

2020-10-20 20:48 UTC, fmahebert requested changes

2020-10-20 20:48 UTC, fmahebert commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Tags/Test_Formulation.cpp
> +          "Strong") == dg::Formulation::StrongInertial);
I would strongly prefer for the creation string to match the actual name of the enum -- having these differ is just inviting confusion down the line. I don't care if you rename the string or the enum :)

2020-10-20 20:48 UTC, fmahebert commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Tags/Formulation.hpp
> +      const dg::Formulation& quadrature) noexcept;
`quadrature` -> `formulation` ?

2020-10-20 20:48 UTC, fmahebert commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Tags/Formulation.cpp
> +    const dg::Formulation& quadrature) noexcept {
`quadrature` -> `formulation` ?

2020-11-06 22:29 UTC, nilsdeppe commented
@fmahebert I forgot to push the fixup... I rebased too. Thanks for the review!

2020-11-07 01:01 UTC, fmahebert reviewed
I am happy with fixup, please squash

2020-11-10 19:44 UTC, kidder reviewed
I have no change requests

2020-11-10 20:12 UTC, nilsdeppe commented
Squashed and rebased on develop. Thanks for the reviews!

2020-11-10 20:28 UTC, kidder approved these changes, later dismissed

2020-11-10 21:17 UTC, fmahebert approved these changes, later dismissed

2020-11-10 23:50 UTC, nilsdeppe commented
Rebased on develop to resolve conflicts., no longer dependent

2020-11-11 00:03 UTC, kidder approved these changes

2020-11-11 00:14 UTC, fmahebert approved these changes

2020-11-11 16:29 UTC, merged