Add ObserveTimeStep observer
sxs-collaboration/spectre pull request #2580
Opened 2020-11-04 20:31 UTC by wthrowe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-11-05 16:43 UTC, nilsdeppe requested changes
This is great. Thank you for adding this observer! I just have 3 minor comment/dox-type things. Please feel free to squash any changes you make :)

2020-11-05 16:43 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveTimeStep.hpp
> +template <typename Metavariables, typename EventRegistrars>
should this forward decl be `/// \cond`ed as well?

2020-11-05 16:43 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveTimeStep.hpp
> +                 typename Metavariables::system::variables_tag>;
Could you add a C++ comment as to why you are using the Variables instead of the Mesh to get the number of grid points?

2020-11-05 16:43 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveTimeStep.hpp
> + * method that would perform a similar amount of work.
would you mind noting what this measure is in terms of an equation? It looks like its 
```
1 / ( (sum_{elements} pts_per_element / element_step_size) / total_points)
```
if I've followed the code correctly

2020-11-05 21:04 UTC, kidder reviewed
I have no additional comments

2020-11-07 05:16 UTC, nilsdeppe approved these changes

2020-11-07 05:26 UTC, kidder approved these changes

2020-11-07 05:26 UTC, merged