Gab fix block
sxs-collaboration/spectre pull request #259
Opened 2017-10-04 22:49 UTC by gsb76

closes #258

2017-10-04 22:54 UTC, osheamonn submitted a review, later dismissed

2017-10-05 01:16 UTC, kidder requested changes
Also update docs/GroupDefs.hpp by removing the EmbeddingMaps group and comment.  Thanks!

2017-10-05 21:25 UTC, kidder requested changes

2017-10-05 21:25 UTC, kidder commented on docs/GroupDefs.hpp
> + * \defgroup CoordinateMaps Coordinate Maps
Please delete these two lines; there is already a group above for coordinate maps

2017-10-06 02:08 UTC, kidder approved these changes

2017-10-06 02:08 UTC, merged