Send boundary data from ComputeTimeDerivative
sxs-collaboration/spectre pull request #2590
Opened 2020-11-12 17:09 UTC by nilsdeppe

## Proposed changes

Have the ComputeTimeDerivative action send the flux data for the boundary corrections currently in develop. This is an intermediate step to replacing the code used in develop and will be removed once everything is working with the new infrastructure. For this reason I didn't document anything, but am happy to if the conclusion is it's worthwhile.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2020-11-13 18:27 UTC, kidder requested changes

2020-11-13 18:27 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/Actions/ComputeTimeDerivative.hpp
> +      auto remote_boundary_data_on_mortar =
remote_boundary_data_on_mortar -> mortar_data_to_send_to_neighbor

2020-11-13 18:27 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/Actions/ComputeTimeDerivative.hpp
> +  for (const auto& direction_and_neighbors : element.neighbors()) {
structured binding [direction, neighbors_in_direction]

2020-11-13 21:12 UTC, nilsdeppe commented
pushed a fixup. Thanks for the review!

2020-11-13 21:35 UTC, kidder reviewed
you can squash

2020-11-13 21:38 UTC, nilsdeppe commented
squish squashed!

2020-11-16 17:15 UTC, kidder submitted a review, later dismissed

2020-11-19 22:08 UTC, kidder commented
@fmahebert please look at

2020-12-01 02:07 UTC, kidder commented
@fmahebert please look at

2020-12-02 22:40 UTC, fmahebert submitted a review, later dismissed

2020-12-02 23:17 UTC, nilsdeppe commented
rebased on develop to resolve the conflict. The issue was that `const_global_cache_tags` type alias was on the same line as the `inbox_tags` type alias added in another PR.

2020-12-03 02:44 UTC, kidder approved these changes

2020-12-03 02:45 UTC, kidder commented
@fmahebert this was rebased...

2020-12-03 02:49 UTC, fmahebert approved these changes

2020-12-03 03:29 UTC, merged