Parse options for ConstGlobalCache and Tentacles
sxs-collaboration/spectre pull request #260
Opened 2017-10-05 17:28 UTC by wthrowe

2017-10-06 20:17 UTC, kidder requested changes

2017-10-06 20:17 UTC, kidder commented on src/Parallel/Main.hpp
> +            -> cpp17::void_t<decltype(decltype(mv)::type::input_file)> {
decltype(mv)::type -> tmpl::type_from<decltype(mv)>

2017-10-06 20:17 UTC, kidder commented on src/Parallel/Main.hpp
> +      command_line_parser.allow_unregistered();
// split above comment into what each part of if-else is doing

2017-10-10 02:58 UTC, nilsdeppe approved these changes

2017-10-11 20:57 UTC, kidder approved these changes

2017-10-11 20:57 UTC, merged