Add serialization for ScriPlusInterpolationManager
sxs-collaboration/spectre pull request #2612
Opened 2020-12-02 07:39 UTC by moxcodes

## Proposed changes

Adds a missing pup function to the `ScriPlusInterpolationManager`. Split out from #2374.

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2020-12-02 16:40 UTC, fmahebert approved these changes, later dismissed

2020-12-02 17:21 UTC, nilsdeppe requested changes
you can squash :)

2020-12-02 17:21 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/ScriPlusInterpolationManager.hpp
> +  size_t vector_size_ = 0_st;
need include `Utilities/Literals.hpp`

2020-12-02 18:04 UTC, moxcodes commented
@nilsdeppe done.
Cheers!

2020-12-02 18:54 UTC, kidder requested changes
you can squash

2020-12-02 18:54 UTC, kidder commented on src/Evolution/Systems/Cce/ScriPlusInterpolationManager.hpp
> +  void pup(PUP::er& p) noexcept {  // NOLINT
also need to include the appropriate pup includes

2020-12-02 20:13 UTC, moxcodes commented
@kidder done.
Cheers!

2020-12-02 23:47 UTC, nilsdeppe approved these changes

2020-12-03 02:59 UTC, kidder approved these changes

2020-12-03 02:59 UTC, merged