Add Sinusoid MathFunction
sxs-collaboration/spectre pull request #262
Opened 2017-10-06 05:47 UTC by osheamonn

2017-10-06 13:28 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/MathFunctions/Test_Sinusoid.cpp
> +  const MathFunctions::Sinusoid gauss{amplitude, wavenumber, phase};
Change variable name.

2017-10-06 18:41 UTC, kidder requested changes

2017-10-06 18:41 UTC, kidder commented on src/PointwiseFunctions/MathFunctions/Sinusoid.hpp
> + *  \details Input file options are: Amplitude, Width, and Center
Width -> Phase and ...

2017-10-08 17:46 UTC, nilsdeppe approved these changes

2017-10-08 21:13 UTC, kidder approved these changes

2017-10-08 21:13 UTC, merged