Print git description and hashes consistently in CMake
sxs-collaboration/spectre pull request #2673
Opened 2020-12-17 18:37 UTC by nilsleiffischer

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2020-12-17 22:24 UTC, wthrowe requested changes
I have verified that this fixes #2646.

2020-12-17 22:24 UTC, wthrowe commented on cmake/CodeCoverage.cmake
> +      --title `cd ${CMAKE_SOURCE_DIR} && ${GIT_HASH}`
GIT_HASH is not a command.

2020-12-17 22:24 UTC, wthrowe commented on cmake/SetupDoxygen.cmake
> +      --title `cd ${CMAKE_SOURCE_DIR} && ${GIT_HASH}`
GIT_HASH is not a command.

2020-12-17 23:04 UTC, nilsleiffischer commented
Also I missed a few occurrences in `WrapExecutableLinker.sh`, will fix tmrw

2020-12-18 10:03 UTC, nilsleiffischer commented
Done, please check the fixup @wthrowe

2020-12-18 16:13 UTC, nilsdeppe approved these changes, later dismissed

2020-12-18 17:23 UTC, wthrowe commented
Looks good.  Squash.

2020-12-18 22:23 UTC, nilsdeppe approved these changes

2020-12-21 18:08 UTC, wthrowe approved these changes

2020-12-21 18:09 UTC, merged