Algorithm chare
sxs-collaboration/spectre pull request #268
Opened 2017-10-09 19:56 UTC by nilsdeppe

Implements a wrapper around Charm++, effectively eliminating ci (interface) files from user code

The outstanding problems I am currently aware of are:

1. Name replacement for Tentacle, Larry and I have come up with `ParallelComponent`
2. Where to document how to use the infrastructure.

2017-10-09 22:45 UTC, kidder requested changes

2017-10-09 22:45 UTC, kidder commented on src/DataStructures/DataBox.hpp
> +// clang-tidy: does not define copy or move assignment operator
indicate it is a false positive

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +    return hash<int>{}.operator()(t.i);
omit operator()

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +    db::mutate<CountActionsCalled>(box)++;
mutate should take a lambda lock/unlock bla bla bla

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +    return ++a >= 5
nils on drugs

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +  static bool is_ready(
do magic to get rid of this function if it is always true

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +    return ++a >= 5
do the thing

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +      -> std::enable_if_t<
can you replace with Requires

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +    return ++a >= 5
collapse

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +    db::mutate<Int1>(const_cast<db::DataBox<DbTags>&>(box))++;  // NOLINT
comment that this is for testing only

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +  using explicit_single_actions_list = tmpl::list<
add a test with args for an action

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
> +SPECTRE_TEST_CASE("Unit.Parallel.Algorithm.local_Order", "[Unit][Parallel]") {
what happens when a snake interacts with a camel

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +    Parallel::printf("InitializeSingleton %d\n\n", Parallel::my_proc());
get rid of printing

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +    Parallel::printf("InitializeArray %d %d\n\n", Parallel::my_proc(),
no print

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +    if (db::get<Tags::CountActionsCalled>(box) >= 15) {
collapse

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +struct ReduceInt {
??????????? ?  reduce through a nodegroup?

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +struct Initialize {
pretty terrible have it do something

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +  using action_list = Parallel::action_list<SingletonActions::CountReceives>;
back to typelist

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +  using explicit_single_actions_list =
check if an empty list is required if there are no single_actions

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +    } else if (current_phase == Phase::Run0) {
better name than Runn

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +    auto& array_proxy = local_cache.template get_tentacle<ArrayTestChare>();
make get_tentacle a non-member

2017-10-09 22:45 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +  using inbox_tag_list = Parallel::inbox_tag_list<Tags::IntReceiveTag>;
never used

2017-10-09 22:45 UTC, kidder commented on tests/Unit/TestHelpers.hpp
> +#define SPECTRE_PARALLEL_CHECK(expr)                                    \
SPECTRE_PARALLEL_REQUIRE to mimic Catch's REQUIRE

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +        help="One of 'chare', 'array', 'group', or 'nodegroup'")
check that you get one of the expected types .  choices

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +    if args['algorithm_type'].lower() == "array":
might not need lower() if choices restrict stuff

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +        "    template <typename Action>\n"
move next to other explicit_single_action

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +    if (args['algorithm_type'].lower() == "group" or
comment why this is needed

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +            "    entry void receive_data(TemporalId&,\n"
try to add [inline]

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +                       (args['algorithm_name'])).replace("//", "/"))
no replace and no Algorithms/

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +    # Write include files and decl.h
fix  comment and improve

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +        "  using Parallel::AlgorithmImpl<Tentacle,algorithm,\n"
why?

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmModuleFunctions.cmake
> +
check the RESULT_VARIABLE

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmModuleFunctions.cmake
> +  # General replacements for all chare types
?

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmModuleFunctions.cmake
> +  # blocks, each block is section off by a blank line
sectioned

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmModuleFunctions.cmake
> +    OUTPUT_VARIABLE CMAKE_IS_SHIT
oops

2017-10-09 22:45 UTC, kidder commented on cmake/SetupCharmModuleFunctions.cmake
> +        "Failed to patched generated ${ALGORITHM_TYPE} files")
patch

2017-10-09 22:45 UTC, kidder commented on cmake/SetupClangTidy.cmake
> +    module_Main
alphabetize

2017-10-09 22:45 UTC, kidder commented on cmake/SpectreParseTests.py
> +                "Evolution",
?

2017-10-09 22:45 UTC, kidder commented on src/Parallel/CharmMain.cpp
> +/// Defines macros to allow serialization of abstract template base classes
wATT???

2017-10-11 19:48 UTC, kidder requested changes

2017-10-11 19:48 UTC, kidder commented on cmake/SetupCharmAlgorithm.py
> +                      "#include \"Algorithms/Algorithm%s.def.h\"\n"
?

2017-10-11 19:48 UTC, kidder commented on cmake/SetupCharmModuleFunctions.cmake
> +  # Run the charmc script over the generate ci file to generate the decl.h
generated ci

2017-10-11 19:48 UTC, kidder commented on tests/Unit/Parallel/Test_Algorithm.cpp
>      // we use the const_cast only so we can test that this function is called.
remove

2017-10-11 19:48 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +    // NOLINT
?

2017-10-11 19:48 UTC, kidder commented on src/DataStructures/DataBox.hpp
> +               "list of the lamba or the constructor of a class, this "
lambda

2017-10-11 19:48 UTC, kidder commented on src/DataStructures/DataBox.hpp
> + * retrieved from the DataBox `t`. This is to avoid confusing subtleties with
rename t -> box

2017-10-11 19:48 UTC, kidder commented on src/DataStructures/DataBox.hpp
> +             "list of the lamba or the constructor of a class, this "
lamb chops

2017-10-11 19:48 UTC, kidder commented on tests/Unit/DataStructures/Test_DataBox.cpp
> +SPECTRE_TEST_CASE("Unit.DataStructures.DataBox.mutate_locked_get",
add a test for mutate_locked_mutate

2017-10-11 21:56 UTC, kidder requested changes

2017-10-11 21:56 UTC, kidder commented on src/Parallel/ConstGlobalCache.hpp
> +    // return tuples::get<TentacleTag>(tentacles_);
remove

2017-10-11 21:56 UTC, kidder commented on src/Parallel/ConstGlobalCache.hpp
> +    // return tuples::get<TentacleTag>(tentacles_);
remove

2017-10-11 21:56 UTC, kidder commented on src/Parallel/Main.hpp
> +  using single_component_list =
single -> singleton

2017-10-11 21:56 UTC, kidder commented on src/Parallel/TentacleHelpers.hpp
> +  using f = int;
cpp17::void_type

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +void setup_error_handling() {
let's move this to a Parallel/InitializationFunctions.hpp

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +    std::unique_ptr<char[]> result(new char[size()]);
make_unique

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +  std::size_t size() noexcept {
size_t

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +    for (const auto& kv : current.maxima_map) {
kv -> descriptive_descriptive

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +  using spatial_id = int;
remove spatial_id everywhere but arrays

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +        Parallel::index_from_tentacle<SingletonTestChare<Metavariables>>::
yuck!

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +    cache.template get_tentacle<ArrayTestChare<Metavariables>>()[spatial_id]
think about wrapping this (not as critical as yuck)

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +struct ReductionData {
template this bad boy

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +    if (next_phase == Metavariables::Phase::Run0) {
Run0 -> descriptive

2017-10-11 21:56 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmReduction.cpp
> +    // NOLINT
?

2017-10-12 22:43 UTC, kidder requested changes

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +std::string get_template_parameters_as_string() {
Please comment what this does with an example . 🔔

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +std::string get_template_parameters_as_string() {
and test this!

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * \brief The array index used for indexing Chare Arrays
group

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  // clang-tidy: usupicious use of sizeof
👎

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  // clang-tidy: usupicious use of sizeof
👎 👎

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +                "alignment must match the alignment of an int");
int -> the internal Charm...

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +    // clang-tidy: usupicious use of sizeof
👎 👎 👎

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +/// `ActionList`, and possibly typelist to append the return types to
possibly a typelist

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +/// Given the first input parameter of the first function
of the first function -> the apply function of the first Action in the `ActionList`

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +/// the arguments after the first, \code using result =
fix formatting of code block

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +/// \metareturns
blank line before

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +/// `Ts...`, then \code result = typelist<Ts...,
formatting of code block

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +          typename... LActions>
LActions -> ActionPack

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +class AlgorithmImpl;
reorder stuff please

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +    ERROR("Cannot call apply function of '"
test the error message

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +    typename Invokable, typename Elem, typename... Variants, typename... Args,
Elem -> ThisVariant

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  bool already_visited = false;
// already_visited ensures that the visitor is not invoked twice

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  int iter = 0;
// iter is the element of the variant

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * Charm++ chares can be of four types, which is specified by the first template
one of four

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * memory parallelism) builds a node corresponds to the usually definition of a
usual

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * node on a super computer. However, for non-SMP builds nodes and cores are
supercomputer

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * entry methods (remote calls to functions) are not threadsafe. It is up to the
on nodegroups

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +
add threaded single action

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * Charm++: late entry method registration happened after init
explain this

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * InboxTags, typename Metavariables, typename SpatialId, typename TemporalId,
code block formatting

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * The DataBox, `box` is used to store
?

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +          typename... LActions, typename... LInboxTags, typename TemporalId,
LActions -> ActionPack
LInboxTags -> InboxTagPack

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  /// Needed for serialization
///  -> //

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  template <typename Action, typename Arg>
document

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +   * \brief Receive data and store it in the Inbox: see more for important
see more ?

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +   * Explicit instantiations of this function must be added to the Charm
remove

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  template <typename ReceiveTag, typename ReceiveData_t>
document the bool

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  /// returns false, or an Action returns with 'terminate' set to 'true'
`s

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  /// as the second argument to the 'receive_data` method.
drunk `

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  static constexpr bool is_chare_proxy =
is_singleton

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +    spatial_id_ = static_cast<typename ChareType::template cbase<
// downcast upcast

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +        actions_list{}, std::move(std::get<Is>(args))...);
think about movement

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +              InitialDataBox>::AlgorithmImpl() {
noexcept

2017-10-12 22:43 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +      "typelist<typelist<singletod_reduce, double>>");
singleton_reduce

2017-10-13 04:14 UTC, wthrowe commented
I think it will be necessary to be able to call explicit single actions on other chares from within the is_ready function of an action, but I don't think that is currently possible (without const_casting things).  An example of this would be an action that used data from a group or nodegroup chare, which should query the data source chare to see if the data is available in its is_ready function.

2017-10-14 03:26 UTC, nilsdeppe commented
To record @wthrowe and my in person conversation: `is_ready` can take `ConstGlabalCache` as a non-const reference so that actions can be called on Parallel Components, eg checking a result on the local nodegroup. The example given was interpolating using threaded methods on a nodegroup, then checking in `is_ready` if the interpolation has completed.

2017-10-19 21:21 UTC, kidder requested changes

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +SpECTRE builds a layer on top Charm++ that performs various safety checks and
on top of

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +is used by SpECTRE to setup the Charm++ chares and allowed communication
set up

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +3. `using action_list` is a `typelist` of the Actions that the Algorithm
make consistent  `using bla` is set to a

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +4. `using inbox_tag_list` is a typelist of the Tags that can sent to the
can be sent

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +   %Tag needs to have some temporal locality, then an optional typealias
type alias

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +   to a member function. The typelist is a of typelist, where the inner
Charm++ allows arrays to be 1-6 dimensional or be indexed by a custom type.  The Charm++ provided indexes are wrapped as `Parallel::ArrayIndex1D` through `6D`.  When writing custom array indices, the Charm++ manual tells you to write your own `CkArrayIndex`, but we have written a general implementation that provides this functionality; all that you need to provide is a plain-old-data struct of size at most 3 integers.

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +2. `using explicit_single_actions` is a typelist of Actions that are not part
is a typelist of typelists for Actions that...

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +   to a member function. The typelist is a of typelist, where the inner
For each Action, a typelist is specified with the Action as their...

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +3. `using reduction_actions_list` is a typelist of typelists, similar to
don't mention `explicit_single_actions`

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +   `explicit_single_actions`. However, all nested typelists must have exactly
The nested typelists

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +   Parallel::CProxy_ConstGlobalCache<Metavariables>& global_cache, opts...);
metavariables

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +    const typename Metavariables::Phase next_phase,
metavariables

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +Elements are inserted into the Array by using the `insert` function member
drop function

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +Elements are inserted into the Array by using the `insert` function member
Charm++ `insert` member function of the proxy for the array

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +   elements each of which is a distributed object on some core. An array can
each of which is an object distributed to some core

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +   another array. That is, the bound array has the same number of elements as
array.  A bound array

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +   one element per core and they are not able to be moved around between
per core which are not able

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +3. A Parallel::Algorithms::Group, which is an array with
no which

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +2. Entry methods that iterate of the Algorithm's algorithm.
iterate the actions in the Algorithm's `action_list`

2017-10-19 21:21 UTC, kidder commented on docs/GroupDefs.hpp
> +- Actions
finish or remove

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +#include "Parallel/Printf.hpp"
remove

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +template <class...>
remove

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +inline void try_lock(const gsl::not_null<CmiNodeLock*> node_lock) noexcept {
Nils says "oh, yeah, shit"

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * \brief Returns 0 if lock was successfully acquired and 1 if the lock is
return a bool, that is true if we are able to lock (document this)

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * \brief Returns a typelist of the return types of all Actions in ActionList
Clean this up and shrink it...

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> + * The DataBox, `box` is used to store
ping

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  /// Call an Action on a local nodegroup requiring the Action to handle thtread
thread

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  /// ActionList as a `const gsl::not_null<CmiNodelock*>&`.The node lock can be
.  The node

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  const gsl::not_null<CmiNodeLock*> node_lock{&node_lock_};
remove

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +      static_cast<const spatial_id&>(spatial_id_), temporal_id_, node_lock,
node_lock_

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +  lock(&node_lock_);
move lock later

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Reduction.hpp
> + * A variable number of `CkReductionMsg*`s is passed to the reducer, and so it
is -> are

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Reduction.hpp
> + * The function must receive an up-to-date `ConstGlobalCache` and `SpatialId` of
remove up-to-date

2017-10-19 21:21 UTC, kidder commented on src/Parallel/Reduction.hpp
> +                                  reduction_data.packed().get());
is this a problem?

2017-10-19 22:02 UTC, kidder requested changes

2017-10-19 22:02 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmParallel.cpp
> +    auto& array_proxy = local_cache.template get_tentacle<ArrayTestChare>();
ping

2017-10-19 22:02 UTC, kidder commented on src/DataStructures/DataBox.hpp
> +struct TD;
Nils "Ah, RIP"

2017-10-19 22:02 UTC, kidder commented on tests/Unit/DataStructures/Test_DataBox.cpp
> +          // & compute_tag0 = static_cast<const double&>(
RIP

2017-10-20 01:59 UTC, nilsdeppe commented on src/Parallel/Algorithm.hpp
> +      static_cast<const spatial_id&>(spatial_id_), temporal_id_, node_lock,
never mind, I'm dumb, this does what I want

2017-10-20 02:00 UTC, nilsdeppe commented on src/Parallel/Reduction.hpp
> +                                  reduction_data.packed().get());
Checked, it's not.

2017-10-20 03:03 UTC, kidder requested changes

2017-10-20 03:03 UTC, kidder commented on docs/GroupDefs.hpp
> +4. `using inbox_tag_list` is a typelist of the Tags that can be sent to the
is set to

2017-10-20 03:03 UTC, kidder commented on docs/GroupDefs.hpp
>  5. `using initial_databox` is the type of the DataBox that will be passed to
is set to

2017-10-20 03:12 UTC, kidder requested changes

2017-10-20 03:12 UTC, kidder commented on docs/GroupDefs.hpp
>     = Parallel::Algorithms::Array`) and is the type that indexes the array.
is set to

2017-10-20 03:12 UTC, kidder commented on docs/GroupDefs.hpp
>  5. `using initial_databox` is the type of the DataBox that will be passed to
and in the sixth bullet

2017-10-20 03:12 UTC, kidder commented on docs/GroupDefs.hpp
> +2. `using explicit_single_actions` is a typelist of typelists for Actions that
is set to

2017-10-20 03:12 UTC, kidder commented on docs/GroupDefs.hpp
> +3. `using reduction_actions_list` is a typelist of typelists. The nested
is set to

2017-10-20 03:12 UTC, kidder commented on docs/GroupDefs.hpp
>      const typename Metavariables::Phase next_phase,
another Metavariables to metavariables

2017-10-20 03:12 UTC, kidder commented on docs/GroupDefs.hpp
> +   elements each of which is an object  distributed to some core. An array can
remove extra space

2017-10-20 15:48 UTC, kidder approved these changes
rebase and squash

2017-10-20 17:54 UTC, kidder requested changes

2017-10-20 17:54 UTC, kidder commented on src/Parallel/Reduction.hpp
> + * The function must receive an `ConstGlobalCache` and `SpatialId` of
an -> a

2017-10-20 17:54 UTC, kidder commented on docs/GroupDefs.hpp
> +1. `using spatial_id` is set to the type that indexes the %Parallel Component
spatial_id -> array_index

2017-10-20 21:07 UTC, kidder requested changes
fix and squash

2017-10-20 21:07 UTC, kidder commented on tests/Unit/Parallel/Test_ConstGlobalCache.cpp
> +struct TD;
RIP

2017-10-20 21:07 UTC, kidder commented on src/Parallel/Main.hpp
> +/// ParallelComponent in Metavariables::component_list must define the following
Each Pa...

2017-10-21 03:33 UTC, kidder approved these changes

2017-10-21 03:34 UTC, merged