Fix SetupJemalloc with CMake 3.12
sxs-collaboration/spectre pull request #2684
Opened 2020-12-18 23:35 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2020-12-18 23:38 UTC, nilsleiffischer approved these changes, later dismissed

2020-12-19 00:23 UTC, geoffrey4444 approved these changes, later dismissed
Works with cmake 3.13.1 on ocean

2020-12-19 11:41 UTC, nilsleiffischer requested changes

2020-12-19 11:41 UTC, nilsleiffischer commented on cmake/SetupJemalloc.cmake
> +  string(FIND "${JEMALLOC_LIB_NAME}" ".so" FOUND_SHARED)
Can you use `string(REGEX MATCH ... ".so$" ...)` instead to make sure this is the last extension? If this is more complicated for some reason, please add a code comment.

2020-12-21 11:30 UTC, nilsleiffischer commented
@nilsdeppe since Ocean now runs cmake 3.18, should be just drop CMake 3.12 and go a few versions up? Let me know which version you prefer. I would suggest 3.15 or 3.16.

2020-12-21 17:40 UTC, nilsdeppe commented
Okay, added a comment explaining why we need a find

2020-12-21 18:26 UTC, nilsleiffischer approved these changes

2020-12-23 18:18 UTC, kidder approved these changes

2020-12-23 18:18 UTC, merged