Fix some PUP includes
sxs-collaboration/spectre pull request #2692
Opened 2020-12-20 18:20 UTC by nilsleiffischer

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2020-12-20 18:42 UTC, kidder requested changes
you can squash

2020-12-20 18:42 UTC, kidder commented on src/NumericalAlgorithms/Spectral/SwshInterpolation.cpp
> +#include <pup.h>
SwshInterpolation.hpp file needs a forward declaration of PUP::er

2020-12-20 19:23 UTC, kidder approved these changes

2020-12-21 16:29 UTC, nilsdeppe approved these changes

2020-12-21 17:51 UTC, merged