Derive elliptic solutions from base classes and add trivial solutions
sxs-collaboration/spectre pull request #2698
Opened 2020-12-21 17:48 UTC by nilsleiffischer

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-01-11 11:51 UTC, nilsleiffischer commented
@fmahebert and @nilsdeppe would you be able to review this one? It was split out of #2603 a while ago

2021-01-19 22:55 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticData/AnalyticData.hpp
> +/// Provides analytic tensor data as a function of the spatial coordinates
I suggest to add a little "\note" to this Doxygen to clarify..
1. There are now two base classes in this file. When should I use which base class? Is this new one for use primarily in the elliptic code?
2. The AnalyticSolutions for evolution problems are marked as AnalyticSolutions only, and not also as AnalyticData, but here it seems you are deriving the elliptic AnalyticSolution from the AnalyticData base class. Can you add a note to document this design?

2021-01-19 22:55 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticSolutions/Elasticity/BentBeam.hpp
> +  const ConstitutiveRelations::IsotropicHomogeneous<2>& constitutive_relation_;
Stylistic nitpick: I believe we use trailing underscores on private members, so these should have no trailing underscore.

2021-01-19 22:55 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticSolutions/Elasticity/HalfSpaceMirror.hpp
> +  const double relative_tolerance_;
[same stylistic nitpick]

2021-01-20 23:54 UTC, nilsleiffischer commented on src/PointwiseFunctions/AnalyticData/AnalyticData.hpp
> +/// Provides analytic tensor data as a function of the spatial coordinates
Added some more docs to address both points. I expect the `MarkAsAnalyticData` struct will be deleted once all executables factory-create the analytic data classes.

2021-01-21 00:04 UTC, nilsleiffischer commented
Thanks for reviewing @fmahebert! I pushed fixups, please take a look when you get the chance.

@nilsdeppe or @wthrowe could you do the second review?

2021-01-21 22:12 UTC, wthrowe requested changes

2021-01-21 22:12 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/Elasticity/AnalyticSolution.hpp
> + * cast to `AnalyticSolution`.
This doesn't make sense.  You can't factory create something that isn't an AnalyticSoltuon using an AnalyticSoluton factory.  (And again in another file.)

2021-01-23 16:09 UTC, nilsleiffischer commented on src/PointwiseFunctions/AnalyticSolutions/Elasticity/AnalyticSolution.hpp
> + * cast to `AnalyticSolution`.
You're right, reworded the docs slightly

2021-01-23 22:41 UTC, nilsleiffischer commented
@wthrowe reworded the docs in the fixup, please take another look. Cheers!

2021-01-25 17:40 UTC, wthrowe commented
OK, I think I understand now.  You don't actually want an AnalyticSolution factory, the registrars are serving the same purpose they do in the most-derived classes.

In that case, the AnalyticSolution class should not define a `creatable_classes` type alias.  (Although, if I remember the rules correctly, it will inherit the one from AnalyicData, so this is more documentation than a functional change to the class.)

2021-01-25 17:44 UTC, nilsleiffischer commented
@wthrowe I kept the `creatable_classes` alias in `AnalyticSolution` so the class can be used for factory-creation in the case where only all registrars are analytic solutions. Does that make sense?

2021-01-26 00:27 UTC, wthrowe commented
OK, I see.  Let's stick with your most recent edits, then.  Go ahead and squash.

2021-01-26 09:05 UTC, nilsleiffischer commented
Rebased and squashed. Thanks for your reviews @fmahebert and @wthrowe!

2021-01-27 02:17 UTC, wthrowe approved these changes

2021-01-27 20:11 UTC, fmahebert approved these changes

2021-01-28 20:49 UTC, merged