Run Python executables in correct environment
sxs-collaboration/spectre pull request #2712
Opened 2020-12-26 15:54 UTC by nilsleiffischer

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2020-12-29 21:34 UTC, nilsdeppe approved these changes, later dismissed

2021-01-04 22:04 UTC, kidder requested changes

2021-01-04 22:04 UTC, kidder commented on cmake/SpectreSetupPythonPackage.cmake
> +#                 bin/. Note that any Python script can be executed from its
`bin` -> `${CMAKE_BINARY_DIR}/bin`

2021-01-04 22:04 UTC, kidder commented on cmake/SpectreSetupPythonPackage.cmake
> +    # Write an executable in bin/ that runs the Python script in the correct
`bin` -> `${CMAKE_BINARY_DIR}/bin`

2021-01-04 22:04 UTC, kidder commented on docs/DevGuide/PythonBindings.md
> +latter exposes them in `bin/`. For example, the arguments `PYTHON_FILES Hello.py
`bin` -> `${CMAKE_BINARY_DIR}/bin`

2021-01-04 22:04 UTC, kidder commented on docs/DevGuide/PythonBindings.md
> +files, but `HelloWorld.py` can be run directly as `bin/HelloWorld`. Finally, the
add `from the SpECTRE build directory`

2021-01-04 22:11 UTC, nilsleiffischer commented
pushed a fixup @nilsdeppe @kidder

2021-01-04 22:16 UTC, kidder submitted a review, later dismissed

2021-01-04 22:37 UTC, nilsdeppe approved these changes, later dismissed
LGTM

2021-01-04 23:15 UTC, kidder approved these changes

2021-01-05 00:35 UTC, nilsleiffischer commented
@nilsdeppe could you give this another look?

2021-01-05 00:38 UTC, nilsdeppe approved these changes

2021-01-05 09:46 UTC, merged