Add ChristodoulouMassTag to Tags.hpp
sxs-collaboration/spectre pull request #2752
Opened 2021-01-11 06:42 UTC by MarloMo

## Proposed changes

The ChristodoulouMassTag and ChristodoulouMassTagCompute calculate the magnitude of the spin angular momentum of a Strahlkorper. 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-01-12 03:16 UTC, kidder requested changes
you can squash the changes

2021-01-12 03:16 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +/// The magnitude of the spin angular momentum of a Strahlkorper.
update the comment

2021-01-12 03:16 UTC, kidder commented on src/ApparentHorizons/Tags.hpp
> +/// Computes the magnitude of the spin angular momentum of a Strahlkorper.
update the comment

2021-01-14 19:55 UTC, kidder reviewed
you can squash

2021-01-16 02:37 UTC, geoffrey4444 approved these changes

2021-01-16 02:58 UTC, kidder approved these changes

2021-01-16 02:58 UTC, merged