Fix protocol assert_conforms_to with clang-11
sxs-collaboration/spectre pull request #2763
Opened 2021-01-12 19:40 UTC by nilsleiffischer

## Proposed changes

Newer compilers optimize out the unused type alias.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-01-13 03:25 UTC, kidder requested changes
All the compilers are complaining (I assume about something not conforming to a protocol, but the error messages are not immediately enlightening...)

2021-01-13 03:25 UTC, kidder commented on src/Utilities/ProtocolHelpers.hpp
> +  // The `decltype` makes sure the conformance test is not optimized out by
I am surprised if this ever worked as a the type alias you deleted does not require a definition of `Protocol::test`. I would change the comment to `// Implicitly instantiate Protocol::test in order to test conformance`

2021-01-14 20:04 UTC, kidder approved these changes

2021-01-14 22:26 UTC, nilsdeppe approved these changes

2021-01-15 22:03 UTC, merged