Print back trace from ERROR and ASSERT macros, add ERROR_NO_TRACE macro
sxs-collaboration/spectre pull request #2766
Opened 2021-01-12 20:54 UTC by nilsdeppe

## Proposed changes

- Prints 10 frames (excluding the internals of the macros) when an ERROR or ASSERT is triggered
- This would be annoying for input file adjustments, so an `ERROR_NO_TRACE` macro is added and used in `PARSE_ERROR`
- Replaces the `sys::abort` call with `ERROR` in `std::set_terminate`. The most common place where a back trace is useful is when an uncaught exception causes `std::terminate` to be called.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-01-12 22:17 UTC, wthrowe requested changes
I like the design decisions of printing the backtrace first and avoiding it entirely during option parsing.

2021-01-12 22:17 UTC, wthrowe commented on src/Utilities/ErrorHandling/AbortWithErrorMessage.cpp
> +  void* trace_elems[max_stack_depth_printed];
Use a `std::array` and pass `.data()` below.

2021-01-13 16:50 UTC, nilsdeppe commented
Thanks for the review @wthrowe!

I rebased on develop, changed `std::array` and switched the `char**` to a `std::unique_ptr<char*, free*>` to have that managed for us. I made these changes in a fixup

2021-01-13 20:01 UTC, wthrowe commented
Looks good.

2021-01-13 20:16 UTC, nilsdeppe commented
Okay, squashed. Thanks for the review!

2021-01-13 20:24 UTC, wthrowe submitted a review, later dismissed

2021-01-14 06:17 UTC, moxcodes approved these changes, later dismissed
I only have extremely minor nitpicks. Please squash any changes immediately.
Thanks for adding this! I've verified that it appropriately gives a useful backtrace (some symbols end up undemangled, but that's a harder problem...)

2021-01-14 06:17 UTC, moxcodes commented on src/Utilities/ErrorHandling/AbortWithErrorMessage.cpp
> +  // Start at 2 to ignore stream operator and abort_with_error_message
comment says 2 but loop starts at 3

2021-01-14 06:17 UTC, moxcodes commented on src/Utilities/ErrorHandling/AbortWithErrorMessage.hpp
> +/// Compose an error message including a back trace and abort the program.
some dox strings call it a `back trace`, others say `backtrace` - best to be consistent.

2021-01-14 16:01 UTC, nilsdeppe commented
Updated and squashed. Thanks for the reviews :)

2021-01-14 16:03 UTC, moxcodes approved these changes

2021-01-14 20:09 UTC, kidder commented
@wthrowe please look at

2021-01-14 20:54 UTC, wthrowe approved these changes

2021-01-14 21:30 UTC, merged