Add Rusanov boundary correction to Newtonian Euler
sxs-collaboration/spectre pull request #2768
Opened 2021-01-13 16:53 UTC by nilsdeppe

## Proposed changes

Adds a Rusanov solver for Newtonian Euler, but implemented in the new boundary corrections framework.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-01-19 18:55 UTC, fmahebert approved these changes, later dismissed

2021-01-26 20:12 UTC, kidder requested changes
you can squash fixing the typo

2021-01-26 20:12 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/BoundaryCorrections/Rusanov.hpp
> + * \{\lambda_\text{ext}|\}\right)}{2} \left(U_\text{ext} - U_\text{int}\right),
missing `|` before exterior char speed

2021-01-26 23:28 UTC, nilsdeppe commented
Rebased and squashed. Thanks for the reviews!

2021-01-27 01:52 UTC, kidder approved these changes, later dismissed

2021-01-27 02:39 UTC, nilsdeppe commented
I squashed in the `need_normal_vector` removal

2021-01-27 18:31 UTC, kidder approved these changes

2021-01-27 18:31 UTC, kidder commented
@fmahebert this has been updated

2021-01-27 19:41 UTC, fmahebert approved these changes

2021-01-27 19:44 UTC, merged