Make linear solver the identity when skipped
sxs-collaboration/spectre pull request #2788
Opened 2021-01-21 01:00 UTC by nilsleiffischer

## Proposed changes

Make the solve the identity operation if no steps are going to be
performed, i.e. assume A=1 so Ax=b solves to x=b. This is useful when the
solver is used as preconditioner, because then we can disable
preconditioning by just not iterating the preconditioner, i.e. by setting
its number of iterations to 0 in the input file. The alternative would be
to keep the fields at their initial guess x=x0, but that's not as useful.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-01-24 15:05 UTC, kidder requested changes

2021-01-24 15:05 UTC, kidder commented on src/ParallelAlgorithms/LinearSolver/AsynchronousSolvers/ElementActions.hpp
> +    // Make the solve the identity operation if no steps are going to be
Please make this handled by a new flag and not the number of iterations.  I would absolutely not expect this behavior

2021-01-24 17:47 UTC, nilsleiffischer commented
Thanks for pointing that out @kidder, I converted this feature to an action.

2021-02-01 22:36 UTC, kidder commented
is the db::mutate in the new action tested by your changes to the test code, or do the tests so far skip that code?

2021-02-01 23:33 UTC, nilsleiffischer commented
@kidder no the tests don't currently run hit the condition. I can add a separate action unit test though.

2021-02-08 12:50 UTC, nilsleiffischer commented
@kidder added the test

2021-02-09 18:56 UTC, kidder approved these changes

2021-02-09 19:29 UTC, fmahebert approved these changes

2021-02-09 19:37 UTC, merged