Documentation: threaded_action is an entry method.
sxs-collaboration/spectre pull request #2802
Opened 2021-01-27 22:33 UTC by markscheel

## Proposed changes

Fixes documentation, which previously said that threaded_action is a non-entry method.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-01-27 22:46 UTC, moxcodes approved these changes, later dismissed

2021-01-27 22:46 UTC, moxcodes commented on docs/DevGuide/Parallelization.md
> +      except it passes a node lock to the `Action`'s apply function.
I think this is the only part of this documentation where threaded actions are mentioned, so maybe it is worth also pointing out that threaded actions are the only case where the runtime system permits multiple actions executing simultaneously on the same component? (that's somewhat hinted at here, but not explicitly stated.)

2021-01-28 19:16 UTC, markscheel commented
Updated docs (and squashed since this is only a few-line PR).

2021-01-28 19:24 UTC, moxcodes submitted a review, later dismissed

2021-01-28 20:48 UTC, wthrowe requested changes

2021-01-28 20:48 UTC, wthrowe commented on docs/DevGuide/Parallelization.md
> +      executing simultaneously on the same component.
This document seems to be using "component" to refer to the entire array or similar and "element" or occasionally "chare" to refer to the parts of them.  I think "element" reads oddly here, so I'd replace this with "chare".

2021-01-28 21:55 UTC, markscheel commented
Changed component to chare and squashed.

2021-01-28 22:12 UTC, wthrowe approved these changes

2021-01-29 21:16 UTC, nilsdeppe commented
@moxcodes would you mind looking to see if you're happy with what @wthrowe requested?

2021-01-29 21:21 UTC, moxcodes approved these changes

2021-02-01 20:12 UTC, merged