Add interval
sxs-collaboration/spectre pull request #281
Opened 2017-10-16 21:28 UTC by osheamonn

2017-10-17 02:26 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +    const Map map_derived = dynamic_cast<const Map&>(map_base);
reference

2017-10-17 02:26 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  catch(const std::bad_cast& e){
`e` unused (not sure why clang-tidy didn't catch that)

2017-10-17 02:26 UTC, wthrowe commented on src/Domain/DomainCreators/DomainCreator.hpp
> +  static std::string class_id();
Remove

2017-10-17 02:26 UTC, wthrowe commented on src/Domain/DomainCreators/DomainCreator.hpp
> +                      public PUP::able {
I believe we decided DomainCreators would not be pupable.

2017-10-17 02:26 UTC, wthrowe commented on src/Domain/DomainCreators/DomainCreator.hpp
> +  virtual std::unique_ptr<Domain<VolumeDim, TargetFrame>> create_domain()
Domain isn't abstract, so no need for the unique_ptr.

2017-10-17 02:26 UTC, wthrowe commented on tests/Unit/Domain/CMakeLists.txt
> +    Domain/DomainCreators/Test_Interval.cpp
Alphabetize.

2017-10-17 21:14 UTC, kidder requested changes

2017-10-17 21:14 UTC, kidder commented on tests/Unit/Domain/TestDomainHelpers.hpp
> +#include "Domain/Domain.hpp"
#include all the stuff

2017-10-17 21:14 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  try {
replace try-catch to checking a nullptr

2017-10-21 03:26 UTC, kidder approved these changes

2017-10-21 15:54 UTC, nilsdeppe approved these changes

2017-10-21 15:54 UTC, merged