Add variables for Neumann boundary conditions to elliptic solutions
sxs-collaboration/spectre pull request #2828
Opened 2021-02-02 08:43 UTC by nilsleiffischer

## Proposed changes

These will be used to impose Neumann-type boundary conditions from the analytic solutions.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-02-02 17:33 UTC, kidder requested changes
you can squash immediately

2021-02-02 17:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/Elasticity/CMakeLists.txt
> +  ElasticPotentialEnergy
should come before Elasticity

2021-02-02 18:42 UTC, fmahebert submitted a review, later dismissed

2021-02-02 21:16 UTC, nilsleiffischer commented
Rebased and squashed. Thanks for your reviews @kidder and @fmahebert!

2021-02-02 21:41 UTC, kidder submitted a review, later dismissed

2021-02-02 21:41 UTC, fmahebert submitted a review, later dismissed

2021-02-04 15:49 UTC, nilsleiffischer commented
Rebased on blaze upgrade

2021-02-04 15:49 UTC, fmahebert approved these changes

2021-02-04 21:28 UTC, kidder approved these changes

2021-02-04 21:28 UTC, merged