Update Ocean to blaze 3.8
sxs-collaboration/spectre pull request #2835
Opened 2021-02-03 16:07 UTC by geoffrey4444

## Proposed changes

Update Blaze on ocean to v3.8.

### Upgrade instructions

This PR just switches to use blaze 3.8 on the cluster Ocean at Cal State Fullerton, which is needed after spectre switched to requiring blaze 3.8.

### Code review checklist

- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [x] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-02-03 20:08 UTC, fmahebert commented
[not a change request] What about the other Ocean environments? Are they still supported?

2021-02-03 20:19 UTC, kidder commented
@geoffrey4444 this needs a rebase

2021-02-04 01:21 UTC, moxcodes submitted a review, later dismissed

2021-02-04 17:08 UTC, geoffrey4444 commented
Thanks for taking the quick looks, @kidder and @fmahebert ! I rebased on latest develop and made the following changes:

1) I continue to support ocean_clang.sh and ocean_gcc.sh. Both use the same modules but the clang one uses clang instead of gcc when compiling spectre. Both of these are suitable for running jobs on ocean's orca-1 queue (the newer, faster queue).
2) I dropped support for ocean_orca0_gcc.sh. This let us run on our older compute nodes but required compiling on those older, slower compute nodes, which was a big pain. Once we're doing a lot of production runs with spectre, I might bring this support back with updated modules, but until then, I decided it's not worth the time, since no one was actually running spectre on the orca0 queue as long as I can remember.

2021-02-04 21:27 UTC, kidder requested changes
you can squash

2021-02-04 21:27 UTC, kidder commented on support/Environments/ocean_gcc.sh
> +    module unload charm-6.10.2-libss
fix this

2021-02-08 21:37 UTC, fmahebert approved these changes

2021-02-09 18:06 UTC, kidder approved these changes

2021-02-09 18:06 UTC, merged