Cce file lock
sxs-collaboration/spectre pull request #2904
Opened 2021-02-18 18:57 UTC by moxcodes

## Proposed changes

This PR adds a 'local sync action' that calls a function to extract a `Parallel::NodeLock` from a component -- this is mostly to be used with the `ObserverWriter`s, as they hold most of the interesting node locks so far.
Then, I use that method to borrow the file lock from the observer writer during a CCE evolution so that we can guarantee that the h5 read and write never happen simultaneously on a given node.
This relieves the requirement of CCE needing thread-safe hdf5, and therefore ensures that any CCE user does not need to alter their environment from the globally accepted spectre env or to use work-arounds like forcing the entire file to be read at CCE startup.

The commit `Move first surface data to Evolve phase` is shared with #2323 . I'll drop that commit from whichever PR is merged later.

### Upgrade instructions

No need for thread-safe hdf5 for CCE runs anymore.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Dependencies
- [ ] #2902 
- [ ] #2903

2021-02-19 19:02 UTC, wthrowe requested changes
The first commit will also have to be updated to match #2902.

2021-02-19 19:02 UTC, wthrowe commented on src/IO/Observer/Actions/GetLockPointer.hpp
> +      node_lock->lock();
Not really related to this PR in particular, but we should consider using the STL classes like lock_guard for lock management.

2021-02-19 19:02 UTC, wthrowe commented on src/Evolution/Systems/Cce/Actions/BoundaryComputeAndSendToEvolution.hpp
> +    auto node_lock =
How about `hdf5_lock`?  What it is for is more useful than just repeating the type.  (Same elsewhere.)

2021-02-22 23:15 UTC, moxcodes commented
rebased on develop, propagated changes from #2902, and squashed in the name change to `hdf5_lock`, as it was a pretty small change.
Cheers!

2021-02-24 18:02 UTC, nilsdeppe approved these changes, later dismissed

2021-02-25 21:51 UTC, wthrowe approved these changes, later dismissed
Needs another rebase, otherwise good.

2021-02-26 03:02 UTC, moxcodes commented
rebased.
Cheers!

2021-02-27 00:41 UTC, wthrowe commented on tests/Unit/Framework/MockDistributedObject.hpp
> +  // original implementation template <typename Action, typename... Args>
Looks like some debugging got reformatted in here.

2021-02-27 00:48 UTC, moxcodes commented
squashed in fixing the comment mistake.
Cheers!

2021-02-27 00:53 UTC, wthrowe submitted a review, later dismissed

2021-03-01 20:25 UTC, nilsdeppe submitted a review, later dismissed
Looks good, just a small question about the test that I'm not sure what the answer to is

2021-03-01 20:25 UTC, nilsdeppe commented on tests/Unit/IO/Observers/Test_GetLockPointer.cpp
> +  ActionTesting::emplace_component<array_component>(&runner, 0);
should these use the new `emplace_array_com`... calls?

2021-03-03 05:16 UTC, moxcodes commented
rebased and squashed in the change to the new chare-specific `emplace` functions.
Cheers!

2021-03-03 16:57 UTC, nilsdeppe approved these changes

2021-03-03 20:00 UTC, wthrowe approved these changes

2021-03-03 20:00 UTC, merged

2021-03-24 10:41 UTC, AntoniRamosBuades commented
Hi @moxcodes , I would like to ask you if this PR means that the thread-safe requirement for CCE as currently explained in the tutorial https://github.com/sxs-collaboration/WelcomeToSXS/wiki/CCETutorial is no longer required ?

2021-03-24 16:42 UTC, moxcodes commented
@AntoniRamosBuades Yes, that is correct. Thanks for pointing that out, I'll update the tutorial.