Relax HwenoImpl test tolerance
sxs-collaboration/spectre pull request #2909
Opened 2021-02-19 19:23 UTC by fmahebert

## Proposed changes

When testing the Hweno limiter with Gauss points, I needed to loosen the tolerance in one of the 2D tests. In another test I saw the error increase but remain within tolerance... but issue #2905 suggests the tolerance can be exceeded on some machines. So here I'm bumping the tolerance for that test as well.

Should resolve issue #2905

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-02-19 19:36 UTC, nilsdeppe submitted a review, later dismissed

2021-02-19 21:05 UTC, wthrowe approved these changes
Test passes for me after this change.

2021-02-20 06:01 UTC, wthrowe requested changes
OK, I spoke too soon.  This fixes the unoptimized builds, but I still get failures in optimized ones:
```
/home/wthrowe/spectre/tests/Unit/Framework/TestingFramework.hpp:147: FAILED:
  CHECK( a == appx(b) )
with expansion:
  0.93664803375774386
  ==
  Approx( 0.93664803377920813 )
with messages:
  Testing Weno_detail::solve_constrained_fit in 1D
  quadrature := Gauss
  One external neighbor on lower_xi side
  /home/wthrowe/spectre/tests/Unit/Evolution/DiscontinuousGalerkin/Limiters/
  Test_HwenoImpl.cpp:255: constrained_fit == expected
  a := (1.39579,1.09223,0.936648)
  b := (1.39579,1.09223,0.936648)

/home/wthrowe/spectre/tests/Unit/Framework/TestingFramework.hpp:147: FAILED:
  CHECK( a == appx(b) )
with expansion:
  -0.18759760834731756
  ==
  Approx( -0.1875976096379402 )
with messages:
  Testing Weno_detail::solve_constrained_fit in 2D
  quadrature := Gauss
  One external, two excluded neighbors
  /home/wthrowe/spectre/tests/Unit/Evolution/DiscontinuousGalerkin/Limiters/
  Test_HwenoImpl.cpp:587: constrained_fit == expected
  a := T(0)=(1.80559,1.59124,0.850077,-0.187598,1.72813,1.51378,0.772618,-0.
  265057,1.65067,1.43632,0.695158,-0.342517)
  T(1)=(1.09964,1.41823,2.29538,3.43728,1.09964,1.41823,2.29538,3.43728,1.
  09964,1.41823,2.29538,3.43728)
  b := T(0)=(1.80559,1.59124,0.850077,-0.187598,1.72813,1.51378,0.772618,-0.
  265057,1.65067,1.43632,0.695158,-0.342517)
  T(1)=(1.09964,1.41823,2.29538,3.43728,1.09964,1.41823,2.29538,3.43728,1.
  09964,1.41823,2.29538,3.43728)
  a := (1.80559,1.59124,0.850077,-0.187598,1.72813,1.51378,0.772618,-0.265057,
  1.65067,1.43632,0.695158,-0.342517)
  b := (1.80559,1.59124,0.850077,-0.187598,1.72813,1.51378,0.772618,-0.265057,
  1.65067,1.43632,0.695158,-0.342517)

/home/wthrowe/spectre/tests/Unit/Framework/TestingFramework.hpp:147: FAILED:
  CHECK( a == appx(b) )
with expansion:
  -0.26505727803214985
  ==
  Approx( -0.26505727656208855 )
with messages:
  Testing Weno_detail::solve_constrained_fit in 2D
  quadrature := Gauss
  One external, two excluded neighbors
  /home/wthrowe/spectre/tests/Unit/Evolution/DiscontinuousGalerkin/Limiters/
  Test_HwenoImpl.cpp:587: constrained_fit == expected
  a := T(0)=(1.80559,1.59124,0.850077,-0.187598,1.72813,1.51378,0.772618,-0.
  265057,1.65067,1.43632,0.695158,-0.342517)
  T(1)=(1.09964,1.41823,2.29538,3.43728,1.09964,1.41823,2.29538,3.43728,1.
  09964,1.41823,2.29538,3.43728)
  b := T(0)=(1.80559,1.59124,0.850077,-0.187598,1.72813,1.51378,0.772618,-0.
  265057,1.65067,1.43632,0.695158,-0.342517)
  T(1)=(1.09964,1.41823,2.29538,3.43728,1.09964,1.41823,2.29538,3.43728,1.
  09964,1.41823,2.29538,3.43728)
  a := (1.80559,1.59124,0.850077,-0.187598,1.72813,1.51378,0.772618,-0.265057,
  1.65067,1.43632,0.695158,-0.342517)
  b := (1.80559,1.59124,0.850077,-0.187598,1.72813,1.51378,0.772618,-0.265057,
  1.65067,1.43632,0.695158,-0.342517)
```

With different compilers, I also get the second failure with -0.18759760834731803, and the third with -0.26505727803215029.

2021-02-22 21:05 UTC, fmahebert commented
Pushed a change to bump more tolerances

2021-02-22 21:07 UTC, nilsdeppe approved these changes

2021-02-22 21:13 UTC, fmahebert commented on tests/Unit/Evolution/DiscontinuousGalerkin/Limiters/Test_HwenoImpl.cpp
> +    Approx local_approx = Approx::custom().epsilon(gauss_tol * 1e-10).scale(1.);
To explain this change: this was the only test that failed on my system when I first generalized to Gauss points, so an earlier commit had bumped the tolerance from 1e-10 to 1e-9. Now that there's more of these tests and I don't want to loosen the GaussLobatto tolerances excessively, I'm going back to 1e-10 times the correction.

2021-02-26 02:38 UTC, wthrowe approved these changes
Now it actually passes all my configurations.

2021-02-27 16:31 UTC, merged