Add orient variables on slice
sxs-collaboration/spectre pull request #291
Opened 2017-10-22 06:31 UTC by osheamonn

2017-10-24 20:19 UTC, kidder requested changes

2017-10-24 20:19 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> +inline std::vector<size_t> oriented_offset(
move to cpp

2017-10-24 20:19 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> +  const Direction<3> first_nbr_axis = orientation_of_neighbor.mapped(
nbr -> neighbor

2017-10-24 20:19 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> +  const bool first_nbr_axis_flipped = (Side::Lower == first_nbr_axis.side());
neighbor_first_axis

2017-10-24 20:19 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> +  const Direction<3> second_nbr_axis = orientation_of_neighbor.mapped(
neighbor_second_axis

2017-10-24 20:19 UTC, kidder commented on tests/Unit/DataStructures/Test_OrientVariablesOnSlice.cpp
> +struct PhysicalCoords : db::DataBoxTag {
don't need tag

2017-10-24 20:19 UTC, kidder commented on tests/Unit/DataStructures/Test_OrientVariablesOnSlice.cpp
> +  static constexpr db::DataBoxString_t label = "PhysicalCoords";
don't need label

2017-10-24 20:19 UTC, kidder commented on tests/Unit/DataStructures/Test_OrientVariablesOnSlice.cpp
> +    const Block<SpatialDim, Frame::Grid>& nbr_block,
nbr -> neighbor

2017-10-24 20:19 UTC, kidder commented on tests/Unit/DataStructures/Test_OrientVariablesOnSlice.cpp
> +    const Block<SpatialDim, Frame::Grid>& nbr_block,
in the whole file!

2017-10-24 20:19 UTC, kidder commented on tests/Unit/DataStructures/Test_OrientVariablesOnSlice.cpp
> +  using Tag = Tags::PhysicalCoords<SpatialDim>;
Tag -> tag

2017-10-25 19:43 UTC, nilsdeppe requested changes
rebase and squash

2017-10-25 19:43 UTC, nilsdeppe commented on src/DataStructures/VariablesHelpers.hpp
> +std::vector<size_t> oriented_offset(
noexcept all of these

2017-10-25 19:58 UTC, nilsdeppe approved these changes

2017-10-26 01:57 UTC, kidder approved these changes

2017-10-26 01:57 UTC, merged