Fix linearized bondi sachs
sxs-collaboration/spectre pull request #2918
Opened 2021-02-23 19:12 UTC by moxcodes

## Proposed changes

Split from #2609 -- this is just the part that fixes up the `LinearizedBondiSachs` solution.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Dependencies

- [ ] #2609

2021-02-24 18:09 UTC, nilsdeppe reviewed
Looks good, feel free to squash things immediately

2021-02-24 18:09 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Initialize/RegisterInitializeJWithCharm.hpp
> +namespace Cce {
`/// \cond` around forward decl

2021-02-25 02:22 UTC, moxcodes commented
fixup squashed in (and rebased so no longer dependent)
Cheers!

2021-02-25 02:33 UTC, nilsdeppe submitted a review, later dismissed

2021-03-02 15:40 UTC, nilsleiffischer requested changes

2021-03-02 15:40 UTC, nilsleiffischer commented on src/Evolution/Systems/Cce/AnalyticSolutions/LinearizedBondiSachs.cpp
> +  mode_constant_copy.resize(2, std::complex<double>(0.0, 0.0));
What does this resizing do? Is the intention that the user may specify only one mode, and the other defaults to zero? In that case I suggest you just remove the default behavior, which means you can switch the `std::vector` to a `std::array`. If I misunderstood this, I suggest to add a comment what's going on :)

2021-03-03 20:57 UTC, moxcodes commented
squashed in the change to std::array input option.
Cheers!

2021-03-03 21:59 UTC, nilsdeppe approved these changes

2021-03-04 21:51 UTC, nilsleiffischer approved these changes

2021-03-04 21:51 UTC, merged