Add DirichletAnalytic and Periodic boundary conditions for GRMHD
sxs-collaboration/spectre pull request #2923
Opened 2021-02-24 17:15 UTC by nilsdeppe

## Proposed changes

Exactly what the description/title says :shrug: 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-02-26 06:55 UTC, fmahebert submitted a review, later dismissed

2021-02-27 16:24 UTC, kidder requested changes
you can squash the minor fixes

2021-02-27 16:24 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/BoundaryCondition.hpp
> +/// \brief Boundary conditions for the scalar wave system
fix system

2021-02-27 16:24 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/Test_Periodic.cpp
> +                  "[Unit][Burgers]") {
fix label

2021-03-01 18:15 UTC, nilsdeppe commented
Squashed in the fixes. Thanks for the reviews :)

2021-03-01 21:25 UTC, fmahebert approved these changes

2021-03-02 00:22 UTC, kidder approved these changes

2021-03-02 00:22 UTC, merged