Add DG to FD projection function
sxs-collaboration/spectre pull request #2925
Opened 2021-02-25 01:21 UTC by nilsdeppe

## Proposed changes

Adds the function to project the DG solution to the FD grid. Really should project `u J` to get conservation perfect when `J` varies spatially.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-02-27 16:17 UTC, kidder requested changes

2021-02-27 16:17 UTC, kidder commented on tests/Unit/Evolution/DgSubcell/Test_Projection.cpp
> +}
test the case where the tags lists are prefixed differently

2021-03-02 00:20 UTC, kidder submitted a review, later dismissed

2021-03-02 19:18 UTC, fmahebert requested changes

2021-03-02 19:18 UTC, fmahebert commented on src/Evolution/DgSubcell/Projection.hpp
> +      "are removed.");
1. For my understanding, can you explain here in Github what I expect the prefixes to be for DG vs Subcell vars?
2. I suggest documenting this requirement on the tag lists... mildly awkward because the documentation is shared with non-Variables interfaces... but I think adding a `\note` with a sentence like "In the Variables interface,..." might still be helpful.

2021-03-02 19:18 UTC, fmahebert commented on src/Evolution/DgSubcell/Projection.cpp
> +  }
isn't this `destructive_resize` ?

2021-03-02 19:18 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_Projection.cpp
> +                "points per element");
Is this out-of-date? It's not clear how the message is related to the code...

2021-03-02 19:18 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_Projection.cpp
> +    const auto check_impl = [&dg_mesh,
I suggest `check_impl` -> `check_each_field_in_vars` or `wrap_check_iterable_approx` or something that hints a little more at the contents

2021-03-02 19:18 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_Projection.cpp
> +                                                         logical_coords);
Isn't this `nodal_coeffs` ?

2021-03-02 19:18 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_Projection.cpp
> +                          dg_mesh.extents(0) - 2, logical_coords);
Isn't this `nodal_coeffs` ?

2021-03-02 19:18 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_Projection.cpp
> +            dg_mesh.extents(0) - 2, logical_coordinates(subcell_mesh)));
I suggest assigning this to a variable (perhaps `expected_subcell_coeffs` or whatever you like), so you can reuse here + twice below in the Vars helper lambda

2021-03-02 19:18 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_Projection.cpp
> +    evolution::dg::subcell::fd::project(
I'm confused about what these last three projections are checking. Can you add short comments as you did for the DataVector and the first Vars case?

2021-03-02 19:37 UTC, nilsdeppe commented on src/Evolution/DgSubcell/Projection.hpp
> +      "are removed.");
1. `evolution::dg::subcell::Tags::Inactive`

2021-03-02 19:53 UTC, nilsdeppe commented
Rebased on develop and pushed a fixup. Thanks for the reviews :)

2021-03-02 20:10 UTC, fmahebert reviewed
The fixups are a good clarity improvement. Thanks! Please squash

2021-03-02 20:42 UTC, kidder commented
LGTM

2021-03-02 22:04 UTC, nilsdeppe commented
I have done the squashing. Thanks for the reviews :)

2021-03-02 22:05 UTC, kidder approved these changes

2021-03-02 22:44 UTC, fmahebert approved these changes

2021-03-03 04:05 UTC, merged