Time actions
sxs-collaboration/spectre pull request #294
Opened 2017-10-24 00:47 UTC by wthrowe

2017-10-24 21:25 UTC, kidder requested changes

2017-10-24 21:25 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmNodelock.cpp
> +          // This, and the similarly names variables below, cause
names -> named

2017-10-24 21:25 UTC, kidder commented on src/Time/TimeTags.hpp
> +// Distributed under the MIT License.
move to Time/Tags.hpp

2017-10-24 21:25 UTC, kidder commented on src/Time/TimeTags.hpp
> +/// \ingroup DataBoxTags
also (if it works) \ingroup Time

2017-10-24 21:25 UTC, kidder commented on src/Time/Actions/AdvanceTime.hpp
> +/// \ingroup Actions
ActionsGroup

2017-10-24 21:25 UTC, kidder commented on tests/Unit/ActionTesting.hpp
> +/// handles most of the arguments to the apply and is_readu action
ready

2017-10-24 21:25 UTC, kidder commented on tests/Unit/ActionTesting.hpp
> +/// handles most of the arguments to the apply and is_readu action
\ingroup TestingSomething

2017-10-24 21:25 UTC, kidder commented on tests/Unit/ActionTesting.hpp
> +  const T& as_const(const T& t) noexcept { return t; }
put into ConstantExpressions

2017-10-24 21:25 UTC, kidder commented on tests/Unit/ActionTesting.hpp
> +  using initial_databox = int;  // type irrelevant
int -> NoSuchType

2017-10-24 21:25 UTC, kidder commented on src/Time/Actions/UpdateU.hpp
> +///
Adds to DataBox:
Removes to DataBox:

2017-10-24 21:25 UTC, kidder commented on src/Time/Actions/AdvanceTime.hpp
> +/// DataBox type is unmodified.
Adds to DataBox:
Removes from DataBox:
Modifies in DataBox:

2017-10-24 21:25 UTC, kidder commented on src/Time/TimeTags.hpp
> +struct dt : db::DataBoxPrefix {
move to DataBox/Prefixes.hpp

2017-10-24 21:25 UTC, kidder commented on src/Time/Actions/FinalTime.hpp
> +    return std::make_tuple(
std::tuple<db::DataBox<DbTags>&&, bool> (std::move....

2017-10-25 02:55 UTC, kidder submitted a review, later dismissed

2017-10-25 02:55 UTC, kidder commented on tests/Unit/Parallel/Test_AlgorithmNodelock.cpp
> +          if (static_cast<int>(array_indexs.size()) !=
:+1:

2017-10-25 19:38 UTC, nilsdeppe submitted a review, later dismissed
squash and rebase :+1:

2017-10-26 01:51 UTC, nilsdeppe approved these changes

2017-10-26 01:51 UTC, merged