Add add_slice_to_data
sxs-collaboration/spectre pull request #295
Opened 2017-10-24 15:05 UTC by wthrowe

2017-10-24 15:12 UTC, osheamonn commented on src/DataStructures/VariablesHelpers.hpp
> + * quantity `data`. The slice has a constant grid coordinate in
Is it not the case that the slice has constant logical coordinate and not grid coordinate on that slice?

2017-10-24 17:36 UTC, kidder requested changes

2017-10-24 17:36 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
>   * slice has a constant grid coordinate in direction `sliced_dim`, and slices
this should be logical coordinate as well

2017-10-24 20:27 UTC, kidder requested changes

2017-10-24 20:27 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> +                       const Variables<TagsList>& slice,
slice -> vars_on_slice

2017-10-24 20:27 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> +void add_slice_to_data(const gsl::not_null<Variables<TagsList>*> data,
volume_vars

2017-10-24 20:27 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> +  const size_t number_of_independent_components =
get constexpr

2017-10-25 03:17 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> + * and slices the volume through the point `slice_point` of this
I find "the point `slice_point` of this coordinate" to be confusing as you are not supposed to pass the value of the fixed coordinate, but instead the index that is fixed in `sliced_dim`.  

How about something like:
 "and slices the volume at `fixed_index` in `sliced_dim`.  For example, to get the lower boundary of `sliced_dim`,  pass `0` for `fixed_index`; to get the upper boundary, pass `extents[sliced_dim] - 1`"

Thoughts?

2017-10-25 03:17 UTC, kidder commented on src/DataStructures/VariablesHelpers.hpp
> + * and slices the volume through the point `slice_point` of this
see comment above

2017-10-25 19:57 UTC, nilsdeppe submitted a review, later dismissed
squash

2017-10-26 16:40 UTC, nilsdeppe approved these changes

2017-10-26 19:41 UTC, kidder approved these changes

2017-10-26 19:41 UTC, merged