Add Rectangle and test
sxs-collaboration/spectre pull request #296
Opened 2017-10-24 21:25 UTC by gsb76

2017-10-24 21:51 UTC, osheamonn commented on src/Domain/DomainCreators/Rectangle.cpp
> +  using affine_map = CoordinateMaps::AffineMap;
Since this is being used as a type as opposed to a metavariable I'd recommend `using AffineMap`

2017-10-24 22:07 UTC, gsb76 commented on tests/Unit/Domain/DomainCreators/Test_Rectangle.cpp
> +void test_periodic_rectangle(
need to test other periodic boundaries as well (only periodic in x, periodic in x and y, etc)

2017-10-24 22:09 UTC, wthrowe commented on src/Domain/DomainCreators/Rectangle.hpp
> +    static constexpr OptionString_t label = {"LowerBound"};
Remove `label` from all the option structs.

2017-10-24 22:09 UTC, wthrowe commented on src/Domain/DomainCreators/Rectangle.hpp
> +    static size_t size() { return 2; }
Remove `size` from all the option structs.

2017-10-25 02:32 UTC, kidder requested changes

2017-10-25 02:32 UTC, kidder commented on tests/Unit/Domain/DomainCreators/Test_Rectangle.cpp
> +
remove blank line

2017-10-25 02:32 UTC, kidder commented on tests/Unit/Domain/DomainCreators/Test_Rectangle.cpp
> +  const DomainCreators::Rectangle periodic_x_rectangle{
add blank line

2017-10-25 02:32 UTC, kidder commented on tests/Unit/Domain/DomainCreators/Test_Rectangle.cpp
> +  const DomainCreators::Rectangle periodic_y_rectangle{
add blank line

2017-10-25 19:27 UTC, nilsdeppe requested changes

2017-10-25 19:27 UTC, nilsdeppe commented on src/Domain/DomainCreators/Rectangle.hpp
> +/// Create a 2D Domain consisting of a single Block.
Doxygen group

2017-10-25 19:27 UTC, nilsdeppe commented on src/Domain/DomainCreators/Rectangle.hpp
> +  Domain<2, Frame::Inertial> create_domain() const override;
noexcept the member functions

2017-10-25 19:27 UTC, nilsdeppe commented on src/Domain/DomainCreators/Rectangle.hpp
> +  Rectangle(
noexcept

2017-10-25 19:27 UTC, nilsdeppe commented on src/Domain/DomainCreators/Rectangle.cpp
> +    : lower_xy_(lower_xy),
make non-const, use std::move

2017-10-25 19:27 UTC, nilsdeppe commented on src/Domain/DomainCreators/Rectangle.cpp
> +std::array<size_t, 2> Rectangle::initial_extents(
add tests for `ASSERT`s

2017-10-25 19:27 UTC, nilsdeppe commented on tests/Unit/Domain/DomainCreators/Test_Rectangle.cpp
> +void test_rectangle(const DomainCreators::Rectangle& rectangle,
simplify all these functions into one, or even just a loop.

2017-10-26 01:10 UTC, nilsdeppe requested changes

2017-10-26 01:10 UTC, nilsdeppe commented on src/Domain/DomainCreators/Rectangle.hpp
> +/// \ingroup DomainCreatorsGroup
Please properly propagate this change throughout the code base.

2017-10-26 01:10 UTC, nilsdeppe commented on src/Domain/DomainCreators/Rectangle.hpp
> +  Domain<2, Frame::Inertial> create_domain() const override;
bump

2017-10-26 01:10 UTC, nilsdeppe commented on src/Domain/DomainCreators/Rectangle.hpp
> +  Rectangle(
bump

2017-10-26 20:06 UTC, kidder requested changes
fix the DomainCreatorsGroup and squash

2017-10-27 00:29 UTC, nilsdeppe commented
Please fix clang-tidy warnings

2017-10-27 12:17 UTC, nilsdeppe requested changes

2017-10-27 12:17 UTC, nilsdeppe commented on tests/Unit/Domain/DomainCreators/Test_Rectangle.cpp
> +// [[OutputRegex, index = 1]]
Check more of the ASSERT message, ie the condition that failed. I believe that is printed.

2017-10-27 17:56 UTC, nilsdeppe approved these changes

2017-10-27 17:56 UTC, nilsdeppe commented on tests/Unit/Domain/DomainCreators/Test_Rectangle.cpp
> +// [[OutputRegex, index = 1]]
I changed my mind on this: these functions are going away anyway, so all is good.

2017-10-27 18:51 UTC, kidder approved these changes

2017-10-27 18:51 UTC, merged