Add apparent-horizon boundary conditions
sxs-collaboration/spectre pull request #2961
Opened 2021-03-04 18:55 UTC by nilsleiffischer

## Proposed changes

The first commit is from #2915. The second is from #2667 and might as well be merged in this PR.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-03-04 18:56 UTC, nilsleiffischer commented
@haraldp271 and @markscheel would you mind reviewing this one? Please ignore the first two commits for now, they are cherry-picked from other PRs.

2021-03-25 19:23 UTC, kidder commented
@haraldp271 and @markscheel do you have time to review this PR, or should I look for other reviewers?

2021-04-06 16:18 UTC, haraldp271 reviewed
I think this MR does require more discussion first, including with @markscheel 
 - are we ok with requiring the excision boundary to be a coordinate sphere?  (I think not)
 - Nils, can you explain the relationship between options (Center / Spin / Mass) and the actual BC applied on the tangential shift and lapse?
 - do we need advance planning for the slightly-inside-the horizon (negative expansion) BCs?
 
This may be best discussed either in a Wed SXS BBH call (but note that I cannot participate tomorrow), or a stand-alone call with Mark, and other recent initial data contributors.

2021-04-06 16:18 UTC, haraldp271 commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> +      "boundary must be a coordinate-sphere.";
Well, many of our excision boundaries are *not* coordinate spheres.  In fact, SpEC had technically a bug because of a broken assumption of coordinate spheres, which only got fixed a few years ago by @markscheel . 

We probably want a version that's correct even if not a coord sphere.

2021-04-06 16:18 UTC, haraldp271 commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> +    static constexpr Options::String help = "The spin parameter on the surface";
'spin parameter' usually refers to the dimensionless spin, 0<=S/M^2<=1.  

I think the free data here is more related to the angular frequency of the horizon generators.   Perhaps ``HorizonAngularFrequency``  or ``HorizonRotationVector``.  I prefer the latter, since this vector is *not* precisely the angular frequency of an event horizon.

2021-04-06 16:18 UTC, haraldp271 commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> +  };
explain 'corresponding Kerr solution' - different coordinates will lead to different values of lapse, won't they?

2021-04-06 16:21 UTC, nilsleiffischer commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> +      "boundary must be a coordinate-sphere.";
Agreed, I'll generalize this to non-coord-spheres.

2021-04-23 02:24 UTC, nilsdeppe requested changes

2021-04-23 02:24 UTC, nilsdeppe commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> +      const gsl::not_null<Scalar<DataVector>*> conformal_factor,
remove const in declarations?

2021-04-23 02:24 UTC, nilsdeppe commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> +  std::array<double, 3> center_{};
set to signaling nan with `make_array`?

2021-04-23 02:24 UTC, nilsdeppe commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * \brief Impose the surface is a quasi-equilibrium apparent horizon. The
`is a` -> `as a`? The first sentence reads weird

2021-04-23 02:24 UTC, nilsdeppe commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * + \epsilon^{ijk}Omega^\mathrm{spin}_j\hat{n}_k
missing `\` in front of `Omega`

2021-07-09 23:08 UTC, nilsleiffischer commented
@markscheel and @haraldp271 I have updated this PR and generalized it to non-coordinate-spheres. It supports two choices for the lapse boundary condition, and can be extended to support negative-expansion boundary conditions in a follow-up PR. Could you provide a review when you find the time?

2021-08-03 19:39 UTC, nilsleiffischer commented
@markscheel I'd appreciate your review here

2021-08-19 15:47 UTC, haraldp271 approved these changes, later dismissed
Fine with me. @nilsleiffischer please note I did not check any of the equations -- if you'd like me to do that, let me know.

2021-08-22 02:45 UTC, nilsdeppe approved these changes, later dismissed
My comments have been adequately addressed, but I have not gone through the updated code in any detail

2021-08-25 19:25 UTC, markscheel requested changes

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> +        "The center of the coordinate sphere representing the apparent-horizon "
Is the horizon still a coordinate sphere?

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * the outer horizon are \f$\boldsymbol{Omega} =
Omega -> \Omega

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * \cite BaumgarteShapiro or section B.1 of \cite Varma2018sqd. In these
B.1 -> II.B.1

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * section B.2 of \cite Varma2018sqd by taking a Kerr solution as additional
B.2 -> II.B.2

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * horizon, \f$\bar{m}^ij=\bar{\gamma}^{ij}-\bar{s}^i\bar{s}^j\f$ is the induced
\bar{m}^ij -> \bar{m}^{ij}

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * + \epsilon_{ijk}\Omega^j x^k
Point out that the \epsilon_{ijk} is the flat-space epsilon.

Also, the index i does not line up on LHS vs RHS (ok for flat space, but makes GR people cringe).

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * \beta_\mathrm{excess}^i &= \frac{\alpha}{\psi^2}\bar{s}^i
In ref [111], equation 19, there is no conformal factor in the normal component of the shift, but here a \psi^2 appears in the denominator.  Is this a typo in ref [111], or a typo here, or am I not understanding something?

(If there is a typo in ref [111], then that should be mentioned in the dox here).

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * This class also support negative-expansion boundary conditions following
support -> supports

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * negative-expansion quantities can be pre-computed at initialization time and
This is about a future optimization, right?  So please change to something like

"...in which case a future optimization might be to pre-compute the negative-expansion quantities at initialization time and store them in the DataBox".

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + *
Could you please add equations for the negative expansion BC?

Also, for negative expansion BC and Dirichlet lapse, it might be useful to point out that there are two different Kerr-Schild analytic solutions being specified, and the user should probably make sure they have the same parameters.

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.cpp
> +void normal_gradient_term_flat_cartesian(
Perhaps add a comment explaining what this term is in equations.

2021-08-25 19:25 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.cpp
> +void normal_gradient_term_curved(
Comment explaining what this term is, in equations.

2021-08-25 19:28 UTC, nilsvu commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> +        "The center of the coordinate sphere representing the apparent-horizon "
it is not, fixed

2021-08-25 19:34 UTC, nilsvu commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * + \epsilon_{ijk}\Omega^j x^k
Added a brief note. The Levi-Civita symbol is just a collection of numbers, so I think I leave the indices as-is.

2021-08-25 19:41 UTC, nilsvu commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * \beta_\mathrm{excess}^i &= \frac{\alpha}{\psi^2}\bar{s}^i
In Varma2018 Eq. (16) appears the horizon-normal `s^i`, not the _conformal_ horizon normal `\bar{s}^i = \psi^2 s^i`. Added a note.

2021-08-25 20:08 UTC, nilsvu commented
Thanks for the detailed review @markscheel ! pushed a fixup.

2021-08-27 14:56 UTC, nilsvu commented
@markscheel could you take a quick look at the fixup?

2021-08-27 15:20 UTC, markscheel reviewed
Please squash

2021-08-27 15:20 UTC, markscheel commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * is the Levi-Civita symbol.
Would you mind changing "the Levi-Civita symbol" to "the flat-space Levi-Civita symbol"?  I'm worried that someone will think that there is a `sqrt(det g)` in there.

2021-08-27 15:22 UTC, nilsvu commented on src/Elliptic/Systems/Xcts/BoundaryConditions/ApparentHorizon.hpp
> + * is the Levi-Civita symbol.
ok, done

2021-08-27 18:26 UTC, markscheel submitted a review, later dismissed

2021-08-29 13:47 UTC, nilsleiffischer commented
@kidder or @wthrowe could you take this over from Nils? It has approvals from Nils, Harald and Mark.

2021-09-02 15:05 UTC, nilsleiffischer commented
@nilsdeppe Could you take another look at this one?

2021-09-02 15:07 UTC, nilsdeppe commented
Yep! If I don't get time today, I'll do it tomorrow morning :)

2021-09-02 17:28 UTC, nilsleiffischer commented
Rebased

2021-09-03 16:20 UTC, nilsdeppe approved these changes
Looks good. I did not compare the equations in the dox to the cpp file. Did you want me to do this?

2021-09-04 21:12 UTC, nilsleiffischer commented
I think Mark did 🤷‍♂️

2021-09-05 16:45 UTC, nilsdeppe commented
Okay, I vote we merge :)

2021-09-05 21:21 UTC, merged