Gab add brick
sxs-collaboration/spectre pull request #297
Opened 2017-10-24 22:03 UTC by gsb76

2017-10-24 22:06 UTC, gsb76 commented on tests/Unit/Domain/DomainCreators/Test_Brick.cpp
> +    const DomainCreators::Brick& brick,
need to test other periodic boundaries as well (only periodic in x, periodic in x and y, etc)

2017-10-25 02:43 UTC, kidder requested changes
There is no reason you need to have the Rectangle commits in this PR as they are independent.

2017-10-25 02:43 UTC, kidder commented on src/Domain/DomainCreators/Brick.hpp
> +        "Sequence of [x,y] for lower bounds."};
x,y,z

2017-10-25 02:43 UTC, kidder commented on src/Domain/DomainCreators/Brick.hpp
> +        "Sequence of [x,y] for upper bounds."};
x,y,z

2017-10-25 02:43 UTC, kidder commented on src/Domain/DomainCreators/Brick.hpp
> +        "Sequence for [x,y], true if periodic."};
x,y,z

2017-10-25 02:43 UTC, kidder commented on src/Domain/DomainCreators/CMakeLists.txt
> +    Brick.cpp
alphabetical

2017-10-25 19:31 UTC, nilsdeppe requested changes
make same style changes that you're making to rectangle

2017-10-26 20:15 UTC, kidder requested changes

2017-10-26 20:15 UTC, kidder commented on src/Domain/DomainCreators/Brick.cpp
> +    : lower_xyz_(lower_xyz),
std::move the things you moved in rectangle

2017-10-26 20:15 UTC, kidder commented on src/Domain/DomainCreators/CMakeLists.txt
>      Interval.cpp
ABCDEFGHIJKLMNOPQRSTUVWXYZ

2017-10-26 21:21 UTC, kidder requested changes

2017-10-26 21:21 UTC, kidder commented on src/Domain/DomainCreators/Brick.cpp
> +    : lower_xyz_(std::move(lower_xyz)),
remove consts from the variables you are moving out of

2017-10-27 12:16 UTC, nilsdeppe requested changes

2017-10-27 12:16 UTC, nilsdeppe commented on tests/Unit/Domain/DomainCreators/Test_Brick.cpp
> +// [[OutputRegex, index = 1]]
doesn't the ASSERT print more than this? i.e. I would expect it to print the condition that failed as well. If so, you should check that as part of the regex. The same applies for the test below, and in rectangle and interval.

2017-10-27 17:57 UTC, nilsdeppe submitted a review, later dismissed

2017-10-27 17:57 UTC, nilsdeppe commented on tests/Unit/Domain/DomainCreators/Test_Brick.cpp
> +// [[OutputRegex, index = 1]]
Changed my mind, function will disappear anyway.

2017-10-27 18:51 UTC, kidder submitted a review, later dismissed

2017-10-27 20:54 UTC, kidder approved these changes

2017-10-27 20:55 UTC, merged