Add interpolation of Gauss points to GL points for Bjorhus boundary conditions
sxs-collaboration/spectre pull request #2975
Opened 2021-03-09 03:12 UTC by nilsdeppe

## Proposed changes

I don't know how to do Bjorhus boundary conditions when using Gauss points other than to interpolation the boundary time derivative correction to the Gauss points from a Gauss-Lobatto grid. This PR adds the interpolation functions and matrix calculations.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-03-16 02:17 UTC, kidder requested changes
you can squash these

2021-03-16 02:17 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/InterpolateFromBoundary.hpp
> +#include "DataStructures/Tensor/Tensor.hpp"
is this include needed?

2021-03-16 02:17 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/InterpolateFromBoundary.cpp
> +#include "DataStructures/Tensor/Tensor.hpp"
not needed

2021-03-16 02:17 UTC, kidder commented on tests/Unit/Evolution/DiscontinuousGalerkin/Test_InterpolateFromBoundary.cpp
> +#include "NumericalAlgorithms/Interpolation/IrregularInterpolant.hpp"
unused

2021-03-16 02:17 UTC, kidder commented on tests/Unit/Evolution/DiscontinuousGalerkin/Test_InterpolateFromBoundary.cpp
> +#include "Domain/LogicalCoordinates.hpp"
unused

2021-03-17 23:29 UTC, nilsdeppe commented
I've rebased and squashed. Thanks for the review :)

2021-03-18 02:18 UTC, fmahebert commented on src/NumericalAlgorithms/Spectral/Spectral.hpp
> + * discontinuous Galerkin scheme.
1. Is it true that this is only needed when evolving on Gauss points? If so, I would add that clarification here, perhaps: "... in a discontinuous Galerkin scheme using Gauss points." or similar.

2. I would also add a new paragraph (or perhaps expand the paragraph below?) where you clarify what "interpolating from boundary into volume" means, because it's not obvious and didn't make sense to me at first. I think it would help to say that you start from data on the boundary, you interpret this data as being a Lagrange polynomial with the correct amplitude on the bdry and value of 0 at every other LGL grid point, then you interpolate from this Lagrange polynomial onto the set of Gauss points. This is maybe slightly too much detail, but should hopefully clear up any confusion. Thoughts?

3. I think it would also be nice to add another new (short) paragraph clarifying how this is different from lifting. As far as I can tell, it's the same idea (boundary => volume) but with different amplitudes?

2021-03-18 02:18 UTC, fmahebert commented on src/NumericalAlgorithms/Spectral/Spectral.hpp
> + * \f}
I did not find this math helpful... there's no `=`, and I don't know what is being described... what's going on?

2021-03-18 02:18 UTC, fmahebert commented on src/NumericalAlgorithms/Spectral/Spectral.cpp
> +      "We only compute the boundary lifting for Gauss quadrature "
Update this comment (this is not the lifting term)

2021-03-18 02:18 UTC, fmahebert commented on src/NumericalAlgorithms/Spectral/Spectral.cpp
> +                local_num_points == 1 ? local_num_points + 1 : local_num_points,
trivial, but I'd suggest `local_num_points + 1` => `2` which is easier to parse

2021-03-18 02:18 UTC, fmahebert commented on src/NumericalAlgorithms/Spectral/Spectral.cpp
> +         "We only compute the boundary lifting for Gauss quadrature "
Update this comment

2021-03-22 17:55 UTC, nilsdeppe commented
I've rebased on develop and pushed a fixup that hopefully addresses the comments. I reworked the documentation a decent amount, so it didn't strictly follow the suggestions, but hopefully the correct information is now available :)

2021-03-22 18:34 UTC, fmahebert reviewed
I think the new docs are well improved. Thanks!

You have my permission to squash, including this typo

2021-03-22 18:34 UTC, fmahebert commented on src/NumericalAlgorithms/Spectral/Spectral.hpp
> + * evaluated an the Gauss grid points. The returned pair of `DataVector`s stores
"an" -> "at"

2021-03-22 18:44 UTC, nilsdeppe commented
Squashed. Thanks for the reviews :)

2021-03-22 18:56 UTC, fmahebert approved these changes

2021-03-23 02:55 UTC, kidder approved these changes

2021-03-23 03:07 UTC, merged