Allow different boundary conditions on bases and mantle of cylinder
sxs-collaboration/spectre pull request #2986
Opened 2021-03-15 21:00 UTC by nilsleiffischer

## Proposed changes

Extend boundary condition support for the Cylinder domain creator to allow for different boundary conditions on each base and on the mantle. Also add support for boundary conditions when the cylinder is partitioned radially and along its height into extra blocks.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-03-17 22:06 UTC, nilsdeppe reviewed
overall looks good. One question, feel free to squash immediately.

The review would've been a bit easier had this been split into multiple commits, but :shrug: I survived :)

2021-03-17 22:06 UTC, nilsdeppe commented on src/Domain/Creators/Cylinder.cpp
> +  lower_boundary_condition_ = std::move(lower_boundary_condition);
do you get warnings if you move these initialization calls into the list initialization after the constructor delegation?

2021-03-18 12:02 UTC, nilsleiffischer commented on src/Domain/Creators/Cylinder.cpp
> +  lower_boundary_condition_ = std::move(lower_boundary_condition);
Yes, apparently C++ doesn't allow list initialization after constructor delegation

2021-03-18 15:38 UTC, nilsdeppe commented on src/Domain/Creators/Cylinder.cpp
> +  lower_boundary_condition_ = std::move(lower_boundary_condition);
okay, thanks!

2021-03-18 15:38 UTC, nilsdeppe approved these changes, later dismissed

2021-03-23 02:49 UTC, kidder requested changes
you can squash immediately

2021-03-23 02:49 UTC, kidder commented on src/Domain/Creators/Cylinder.hpp
> +        "cylinder, i.e. at the `LowerBound` in z-direction.";
in the z-direction

2021-03-23 02:49 UTC, kidder commented on src/Domain/Creators/Cylinder.hpp
> +        "cylinder, i.e. at the `UpperBound` in z-direction.";
in the z-direction

2021-03-23 02:49 UTC, kidder commented on src/Domain/Creators/Cylinder.hpp
> +        "cylinder, i.e. at the `OuterRadius` in radial direction.";
in the radial direction

2021-03-23 18:38 UTC, kidder approved these changes

2021-03-23 18:41 UTC, nilsdeppe approved these changes

2021-03-23 21:04 UTC, merged