AddTemporalIdsToInterpolationTarget now works with time-dependent maps
sxs-collaboration/spectre pull request #3005
Opened 2021-03-18 22:15 UTC by markscheel

## Proposed changes
There are multiple commits in this PR. Most of them do small things:
 - Add 'frame' type alias to InterpolationTargets
 - Add a new tag PendingTemporalIds to the DataBox of InterpolationTarget
 - Adds new functions to InterpolationTargetDetail, for determining when maps are time-dependent.
And then some make larger changes
 - Add intrp::Actions::VerifyTemporalIdsAndSendPoints (as described in the documentation)
 - Update AddTemporalIdsToInterpolationTarget, and its test, to work with time-dependent maps.

This PR includes #2943.  Not sure if #2943 should be merged separately or if this one should be merged.

### Upgrade instructions

Functionality for time-independent maps should be unchanged.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-03-24 20:18 UTC, markscheel commented
Rebased. No longer dependent on another PR.

2021-04-02 21:08 UTC, wthrowe requested changes

2021-04-02 21:08 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/Actions/VerifyTemporalIdsAndSendPoints.hpp
> +  std::vector<TemporalId> new_temporal_ids{};
Move this down to where it is used.

2021-04-02 21:08 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetDetail.hpp
> +      return true;
Probably clearer as `return alg::any_of(domain.blocks(), [](const auto& block) noexcept { return block.is_time_dependent(); }))`.

2021-04-02 21:08 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_AddTemporalIdsToInterpolationTarget.cpp
> +        1);
Use the ActionTesting::* helper functions (several places).

2021-04-02 21:08 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_AddTemporalIdsToInterpolationTarget.cpp
> +          new domain::creators::time_dependence::UniformTranslation<3>(
Use make_unique.

2021-04-05 19:54 UTC, markscheel commented
Made fixups.

2021-04-08 19:17 UTC, wthrowe commented
Squash.

2021-04-09 15:08 UTC, markscheel commented
Squashed (and rebased).

2021-04-23 01:01 UTC, nilsdeppe approved these changes

2021-04-23 01:02 UTC, nilsdeppe commented
@wthrowe this was squashed and rebased

2021-04-23 18:19 UTC, wthrowe approved these changes

2021-04-23 18:20 UTC, merged

2021-04-24 09:55 UTC, nilsleiffischer commented
@markscheel Could you update the upgrade instructions in the PR description, so they give instructions what to do when rebasing or delete them if nothing must be done?

2021-05-03 13:11 UTC, nilsleiffischer commented
@markscheel I deleted the upgrade instructions that said "do nothing" because I'm preparing the release now. Please add upgrade instructions if you think they would be useful here.