Add infinity to the evolution comparators
sxs-collaboration/spectre pull request #3007
Opened 2021-03-19 01:37 UTC by wthrowe

This can be used to simplify #2983 and some upcoming dense output code.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-03-20 18:51 UTC, kidder requested changes
you can squash the fix

2021-03-20 18:51 UTC, kidder commented on tests/Unit/Time/Test_EvolutionOrdering.cpp
> +#include <limits>
alphabet (this is what clang-tidy is unhappy with)

2021-03-22 18:49 UTC, kidder approved these changes, later dismissed

2021-03-23 02:13 UTC, kidder commented
needs a rebase to include #3018 so CI passes

2021-03-23 09:22 UTC, nilsleiffischer requested changes

2021-03-23 09:22 UTC, nilsleiffischer commented on src/Time/EvolutionOrdering.hpp
>    constexpr auto operator()(T&& t, U&& u) const noexcept {
I think it would be clearer to change `auto` -> `bool` here.

2021-03-23 09:22 UTC, nilsleiffischer commented on src/Time/EvolutionOrdering.hpp
> +/// \copydoc evolution_less
Wrap these in `// @{` instead?

2021-03-23 09:23 UTC, nilsleiffischer commented
Please squash this directly while you're rebasing.

2021-03-23 17:05 UTC, wthrowe commented on src/Time/EvolutionOrdering.hpp
> +/// \copydoc evolution_less
Tried that.  Didn't work.

2021-03-23 17:05 UTC, wthrowe commented on src/Time/EvolutionOrdering.hpp
>    constexpr auto operator()(T&& t, U&& u) const noexcept {
It doesn't have to be bool.  Should actually probably be `decltype(auto)`, though.  I'll fix that. 
 https://en.cppreference.com/w/cpp/utility/functional/less_void

2021-03-23 18:51 UTC, wthrowe commented
The last commit is new.

2021-03-23 18:54 UTC, nilsleiffischer approved these changes

2021-03-23 19:03 UTC, kidder approved these changes

2021-03-24 06:02 UTC, merged