Add Interval to doxygen group DomainCreatorsGroup and add noexcept
sxs-collaboration/spectre pull request #302
Opened 2017-10-26 17:58 UTC by gsb76

2017-10-26 20:17 UTC, kidder requested changes
rebase when adding the \

2017-10-26 20:17 UTC, kidder commented on src/Domain/DomainCreators/Interval.hpp
> +/// ingroup DomainCreatorsGroup
\ingroup

2017-10-26 21:22 UTC, kidder requested changes
squash

2017-10-27 12:11 UTC, nilsdeppe requested changes
please squash right away

2017-10-27 12:11 UTC, nilsdeppe commented on src/Domain/DomainCreators/Interval.cpp
> -    const OptionContext& /*context*/)
While you're here, might as well make these non-const and move (remember clang-tidy)

2017-10-27 17:57 UTC, nilsdeppe approved these changes

2017-10-27 18:52 UTC, kidder approved these changes

2017-10-27 18:52 UTC, merged