(De)registration during serialization
sxs-collaboration/spectre pull request #3026
Opened 2021-03-23 18:02 UTC by moxcodes

## Proposed changes

Adds the ability to deregister from observers, and adds the framework of performing that deregistration and re-registration during serialization

### Upgrade instructions

Any new registration structs should define the new `perform_registration` and `perform_deregistration` functions to conform to the interface expected by the `DgElementArray` pup. 

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

2021-03-23 21:26 UTC, wthrowe requested changes

2021-03-23 21:26 UTC, wthrowe commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +                    reduction_observers_registered_nodes->at(observation_key)
[optional] You use this value a lot.  Maybe look it up once and store a reference or an iterator.

2021-03-23 21:26 UTC, wthrowe commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +                  "unregistered observation key"
`key: "`

2021-03-23 21:26 UTC, wthrowe commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +            if (LIKELY(reduction_observers_registered->at(observation_key)
Swap the if and else blocks for consistency with the rest of your error checks.  (And then the else indentation isn't needed.)

2021-03-23 21:26 UTC, wthrowe commented on src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
> +          typename check = std::void_t<>>
`typename = std::void_t<>`

2021-03-23 21:26 UTC, wthrowe commented on src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
> +constexpr bool has_registration_list =
Maybe `has_registration_list` and `has_registration_list_v`?

2021-03-25 01:11 UTC, moxcodes commented
fixups posted.
Cheers!

2021-03-25 19:30 UTC, wthrowe commented
Squash.

2021-03-25 21:23 UTC, kidder requested changes
reviewed with @nilsdeppe

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +struct DeregisterVolumeContributorWithObserverWriter {
document

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +struct DeregisterReductionNodeWithWritingNode {
document

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +struct DeregisterReductionContributorWithObserverWriter {
document

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +struct DeregisterContributorWithObserver {
document

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +                             array_component_ids->at(observation_key).end())) {
please separate into two ifs as for the actions above; @nilsdeppe says separate error messages were very helpful when debugging the registration

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +        // if the observation key is not registered, no need to re-call the
We found the comment confusing.  We find the code would be clearer if the bool was named either `all_array_components_have_been_deregistered` or `deregister_with_observer_writer`

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/ObserverRegistration.hpp
> +              "Attempting to Deregistering an unknown TypeOfObservation. "
to deregister

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/RegisterEvents.hpp
> + * member functions `perform_registriation` and `perform_deregistration` that
perform_registration

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/RegisterEvents.hpp
> + * are needed for either deregistering when an element is being eliminated from
keep the descriptions in the same order as the member function names

2021-03-25 21:23 UTC, kidder commented on src/IO/Observer/Actions/RegisterWithObservers.hpp
> + * member functions `perform_registriation` and `perform_deregistration` that
same fixes to this paragraph

2021-03-25 21:23 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +#include "Utilities/TypeTraits/CreateIsCallable.hpp"
alphabet

2021-03-25 21:23 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +        ParallelComponent::pup(p, boost::get<ThisVariant>(box), phase_,
pass box with `std::as_const` and add comment that if a non-const box is needed then the `Algorithm::pup` function needs to call this before  pupping `box_` when `p.isPacking()`

2021-03-25 21:23 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
> +      using registration_list =
This seems pretty generic, can this be moved into Algorithm?

2021-03-26 01:50 UTC, moxcodes commented
fixups posted (prefixed with `fixup2`).
Cheers!

2021-03-26 01:52 UTC, wthrowe commented
I am fine with the fixups.

2021-03-26 02:13 UTC, kidder requested changes

2021-03-26 02:13 UTC, kidder commented on src/Parallel/Algorithm.hpp
> +#include "Utilities/TypeTraits/CreateIsCallable.hpp"
I don't think this is used anymore

2021-03-26 02:13 UTC, kidder commented on src/Parallel/Algorithm.hpp
>      invoke_component_pup_with_current_box(p, box_);
can we rename this function to something like `perform_registration_or_deregistration` to reflect what it is actually doing (currently)?

2021-03-26 02:48 UTC, moxcodes commented
Another fixup added for the last couple of `Algorithm.hpp` suggestions.
Cheers!

2021-03-26 02:49 UTC, kidder commented
I am happy with the fixups

2021-03-26 03:08 UTC, wthrowe commented
Squash.

2021-03-26 16:34 UTC, moxcodes commented
Squashed.
Cheers!

2021-03-26 17:39 UTC, nilsdeppe approved these changes

2021-03-26 17:59 UTC, kidder approved these changes

2021-03-26 18:55 UTC, wthrowe approved these changes

2021-03-26 20:55 UTC, merged