Improve YlmSpherepack documentation
sxs-collaboration/spectre pull request #3029
Opened 2021-03-24 14:06 UTC by nikwit

## Proposed changes
Adds some general documentation to `YlmSpherepack`, explaining how the spherical expansions are represented. This would have saved me a lot of digging through fortran documentation.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-03-24 17:26 UTC, markscheel commented
Failing test is that docs don't render properly.

2021-03-24 18:02 UTC, nikwit commented
sorry for that, I fixed a typo with another typo.

2021-03-30 21:05 UTC, nilsdeppe requested changes
please squash directly

2021-03-30 21:05 UTC, nilsdeppe commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * +\sum_{l=1}^{l_{max}}\sum_{m=1}^{min(l, m_{max})}\bar P_l^m(\cos\theta)\{
`min` -> `\min` or `\mathrm{min}` (same with `max`)

2021-03-30 21:05 UTC, nilsdeppe commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * returning an expansion of form 2. To evaluate the function at arbitrary
sorry, what do you mean by `expansion of form 2`?

2021-03-31 12:17 UTC, nikwit commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * returning an expansion of form 2. To evaluate the function at arbitrary
I mean the second representation of SPHEREPACK as I defined it in the enumeration above. I made it a bit clearer.

2021-03-31 16:30 UTC, nilsdeppe commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * returning an expansion in the second representation of SPHEREPACK. To
sorry, I have no idea from the documentation here that there are two representations. Are you talking about modal vs nodal? If so, I would use that wording

2021-04-02 16:58 UTC, nikwit commented
I changed it to modal and nodal form now.

2021-04-05 16:12 UTC, nilsdeppe approved these changes, later dismissed

2021-04-05 22:57 UTC, markscheel requested changes
Just minor changes. Please squash directly.

2021-04-05 22:57 UTC, markscheel commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * as expected by this interface use the class `SpherepackIterator`.
comma after 'interface'

2021-04-05 22:57 UTC, markscheel commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * function evaluated at collocation angles \f$g(\theta_i, \phi_j)\f$, where
Wording sounds like the collocation angles are called 'g'.  How about
`This is an array of the expanded function \f$g(\theta,\phi)\f$ evaluated at collocation values \f$(\theta_i,\phi_j)\f$, where...`  with no 'g' in the 2nd formula.

2021-04-05 22:57 UTC, markscheel commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * convert to spectral coefficients first so it is in general more efficient to
comma after 'first'

2021-04-05 22:57 UTC, markscheel commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * function at arbitrary angles \f$\theta\f$, \f$\phi\f$ these values have to be
comma after phi

2021-04-05 22:57 UTC, markscheel commented on src/ApparentHorizons/YlmSpherepack.hpp
> + * the collocation points can be computed wth the method `theta_phi_points`.
wth -> with

2021-04-06 08:00 UTC, nikwit commented
squashed, thanks for your reviews :)

2021-04-06 16:25 UTC, nilsdeppe approved these changes

2021-04-06 19:55 UTC, markscheel approved these changes

2021-04-06 20:00 UTC, merged