Disallow step changes when slab number is negative
sxs-collaboration/spectre pull request #3034
Opened 2021-03-24 23:19 UTC by moxcodes

## Proposed changes

There are some edge cases where the `can_change_step_size` check in `AdamsBashforthN` doesn't manage to identify self-start, and the step ends up changing, which causes surprising breaks when evolution starts.
This fix makes the assumption that self-start has negative slab numbers, which is true for the current implementation, but may need to be changed in future.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

2021-03-24 23:24 UTC, nilsdeppe approved these changes, later dismissed
I can confirm this fixes the issues I was having with the LTS evolutions. Thank you! :)

2021-03-24 23:24 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +  return time_id.slab_number() > 0 and
Should this be `>=`? I'm not sure when we can start allowing. I also remember there being some discussion on an function to check `is_self_starting` but I seem to have yet again forgotten if that got added :P

2021-03-24 23:27 UTC, moxcodes commented
I think the `is_self_starting` isn't in `develop` yet, but I could add that free function.
Also, there is some freedom in where this check can be placed, and if it's philosophically better to put it in `ChangeStepSize` or `take_step`, it should be similarly effective and a very quick change.

2021-03-24 23:29 UTC, nilsdeppe commented
:+1: I cannot comment as to where the right place to put it is, though :)

2021-03-25 00:22 UTC, moxcodes commented
Factored the check to a helper function. For now, I've left the check in `AdamsBashforthN`, under the rough motivation that if it is checked in the stepper itself it is less likely to be overlooked in future features that want to check whether the step can be changed.
Cheers!

2021-03-25 00:28 UTC, nilsdeppe submitted a review, later dismissed

2021-03-25 02:56 UTC, wthrowe requested changes
We used to completely avoid running this check during self-start by not running the ChangeStepSize action, which is why this problem appeared now.  I agree with this method of fixing it.

2021-03-25 02:56 UTC, wthrowe commented on src/Time/SelfStart.hpp
> +/// self-start is in progress. If self start is modified to alter that behavior,
You're missing something about slabs somewhere in here.

2021-03-25 03:21 UTC, moxcodes commented
Yeah, I mistakenly introduced the need for this check when I moved the step-taking routines into `take_step` in `ComputeTimeDerivatives`, so it occurred even during the self-start action list, and I overlooked that the check in the time stepper wouldn't capture all cases in self start.

I've squashed in the modification of the sentence to "... assumes that the slab number of the `time_id` will be...".
Cheers!

2021-03-25 15:25 UTC, nilsdeppe approved these changes

2021-03-25 19:26 UTC, wthrowe approved these changes

2021-03-25 20:13 UTC, merged