Add using_subcell type trait
sxs-collaboration/spectre pull request #3036
Opened 2021-03-24 23:26 UTC by nilsdeppe

## Proposed changes

Adds a type trait that can be used to check if we are using subcell. This is not part of the `DgSubcell` library so that not all executables will need to link against `DgSubcell`

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-03-25 02:43 UTC, fmahebert requested changes
You can squash directly

2021-03-25 02:43 UTC, fmahebert commented on src/Evolution/DiscontinuousGalerkin/UsingSubcell.hpp
> + * \brief If `Metavars` has a `SubcellOptions` member struct and that
"and that" -> "and" (or some other fix to the english?)

2021-03-25 02:43 UTC, fmahebert commented on src/Evolution/DiscontinuousGalerkin/UsingSubcell.hpp
> + * \brief If `Metavars` has a `SubcellOptions` member struct and that
"and that" -> "and"

2021-03-25 15:21 UTC, nilsdeppe commented
rebased and squashed in the wording change. Thanks for the review :)

2021-03-25 15:24 UTC, fmahebert approved these changes

2021-03-26 20:53 UTC, kidder approved these changes

2021-03-26 20:53 UTC, merged