Subcell: add relaxed discrete maximum principle TCI
sxs-collaboration/spectre pull request #3039
Opened 2021-03-25 02:25 UTC by nilsdeppe

## Proposed changes

- Add the TCI function
- Add a helper function to compute the max/min over the grid. This needs to be done in a couple different places so it's factored into a separate function

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-03-26 19:44 UTC, kidder requested changes

2021-03-26 19:44 UTC, kidder commented on src/Evolution/DgSubcell/RdmpTci.hpp
> + * Let the candidate solution be denoted by \f$u^\star_{\alpha i}(t^{n+1})\f$.
drop the i subscript (or define what it means...)

2021-03-26 19:44 UTC, kidder commented on src/Evolution/DgSubcell/RdmpTci.hpp
> + * \f$u^\star_\alpha\f$ are always computed over both the DG and the subcell
this sentence seems to contradict the previous one

2021-03-26 19:44 UTC, kidder commented on src/Evolution/DgSubcell/RdmpTci.hpp
> + * \f$u^\star_\alpha\f$ are always computed over both the DG and the subcell
and the code seems to be using both grids

2021-03-29 17:53 UTC, nilsdeppe commented
I've rebased and pushed a fixup commit. Thanks for the review :)

2021-03-29 23:30 UTC, kidder reviewed
you can squash

2021-03-30 16:49 UTC, nilsdeppe commented
I've rebased and squashed. Thanks for the review :)

2021-03-31 17:38 UTC, fmahebert submitted a review, later dismissed
LGTM, I have just two tiny wording suggestions on the docs. Feel free to squash or ignore.

2021-03-31 17:38 UTC, fmahebert commented on src/Evolution/DgSubcell/RdmpTci.hpp
> + * minimum at time level \f$t^n\f$ over the subcells only. Note that the maximum
I suggest removing "at time level \f$t^n\f$" from this sentence, since AFAICT the time isn't the important thing here. If you did want to clarify that the t^n notation is referring to time levels, I would instead edit line 23 to say "Let the candidate solution at time level t^{n+1} ..." or similar

2021-03-31 17:38 UTC, fmahebert commented on src/Evolution/DgSubcell/RdmpTci.hpp
> + * DG and the subcell grid, even when using the RDMP to check if the
I suggest "grid" -> "grids"

2021-03-31 18:32 UTC, nilsdeppe commented on src/Evolution/DgSubcell/RdmpTci.hpp
> + * minimum at time level \f$t^n\f$ over the subcells only. Note that the maximum
I think this was a clarification that @kidder  wanted. Basically, the confusion is that when running on subcell, the `max/min` over the candidate is computed both over the reconstructed DG grid and the subcell grid, while only the subcell grid values are used for the previous time max/min. With that knowledge, how do you suggest making sure that the difference is clear?

2021-04-01 00:05 UTC, fmahebert commented on src/Evolution/DgSubcell/RdmpTci.hpp
> + * minimum at time level \f$t^n\f$ over the subcells only. Note that the maximum
Ah, then an alternative I would suggest is "at time level tn" -> "of u_alpha".

This way you have two sentences describing u_alpha, and then one sentence describing u_alpha^star. There is no longer a confusing statement about time. And, to me at least, saying "the max and min of u_alpha" here is clear because the equation was pretty clear about what times went with which u/ustar.

What do you think of this suggestion?

2021-04-01 18:02 UTC, nilsdeppe commented
I've rebased and squashed in the wording changes. Let me know if this is clearer :)

2021-04-01 19:54 UTC, kidder approved these changes

2021-04-02 03:16 UTC, fmahebert approved these changes
Yeah I like this better, thanks!

2021-04-02 04:47 UTC, merged