Adding SphericalHarmonic basis
sxs-collaboration/spectre pull request #3047
Opened 2021-03-29 17:25 UTC by isha1810

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-09 18:45 UTC, nilsdeppe reviewed
LGTM, just one tiny thing. Please go ahead and rebase on the latest develop and squash things into one commit :)

2021-06-09 18:45 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/Mesh.hpp
> +#include "Utilities/ErrorHandling/Assert.hpp"
I think this can be grouped in with the includes above, no?

2021-06-11 17:16 UTC, nilsdeppe approved these changes

2021-06-11 17:17 UTC, nilsdeppe requested changes
can you squash the commits into one?

2021-06-11 17:17 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/Mesh.hpp
> +#include "Utilities/ErrorHandling/Assert.hpp"
It looks like alphabet is wrong here

2021-06-14 22:57 UTC, nilsdeppe approved these changes
@kidder can you please review this?

2021-06-15 00:28 UTC, kidder approved these changes

2021-06-15 17:15 UTC, merged