Add overlaying to the option parser
sxs-collaboration/spectre pull request #3058
Opened 2021-03-31 18:11 UTC by wthrowe

## Proposed changes

This allows parsed options to be partially overridden by a new input file.  This is intended to be used for restarts that can change parameters.

This is on top of #3049.  The first three commits (the ones not related to the parser) are from that PR.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-04-01 18:02 UTC, wthrowe commented
All the test failures are #3060.  I'll rebase once that's fixed.

2021-04-06 20:22 UTC, kidder requested changes
you can squash

2021-04-06 20:22 UTC, kidder commented on src/Options/ParseOptions.hpp
> +  /// Overlay data from a TAML node
TAML -> YAML

2021-04-27 17:03 UTC, kidder approved these changes, later dismissed

2021-04-27 17:03 UTC, kidder commented
@fmahebert do you have time to review this?

2021-04-30 16:14 UTC, kidder commented
@fmahebert should I find another reviewer for this?

2021-05-10 00:01 UTC, fmahebert commented
I can review this Mon-Tue this week.

2021-05-11 20:24 UTC, fmahebert approved these changes
I'm no expert on the parsing code, but to me this looks good and is well documented.

2021-05-11 20:59 UTC, wthrowe commented
Do you think this looks like a good interface for using in the restart code?

2021-05-14 19:45 UTC, kidder approved these changes

2021-05-14 19:45 UTC, kidder commented
@wthrowe I don't remember if we agreed to merge this now, or wait

2021-05-14 20:00 UTC, fmahebert commented
My memory of the discussion earlier this week is that we can merge this now. We might find we need tweaks later as I adapt the restart procedure to use this new feature, but it looks close to what we need 👍.

2021-05-15 17:12 UTC, merged