Find horizon for time-dependent maps.
sxs-collaboration/spectre pull request #3074
Opened 2021-04-07 14:44 UTC by markscheel

## Proposed changes

Test_ApparentHorizonFinder now works when finding horizons in the Inertial frame, for time-dependent maps.
Future PRs will add the ability for horizon finding in the Grid frame.

To make the test easier, we also add TimeDependence to the Shell DomainCreator.

Depends on #3073 (and includes commits from #3073).

### Upgrade instructions

The Shell DomainCreator now takes a TimeDependence, and requires TimeDependence in the input file.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-04-29 21:37 UTC, kidder requested changes

2021-04-29 21:37 UTC, kidder commented on src/Domain/Creators/Shell.cpp
> +  const size_t blocks_per_layer =
why is this moved outside the loop? isn't the number of blocks equal to the size of coord_maps?

2021-04-29 21:37 UTC, kidder commented on src/Domain/Creators/Shell.cpp
> +          std::move(time_dependence_->block_maps(number_of_blocks)[block]));
doesn't this create the block_maps `block` times?

2021-04-29 21:37 UTC, kidder commented on tests/Unit/Domain/Creators/Test_Shell.cpp
>    const double outer_radius = 3.0;
add a test with a time dependence other than None

2021-04-30 00:12 UTC, markscheel commented
Added fixup commits.

2021-04-30 16:03 UTC, kidder reviewed
you can squash

2021-04-30 19:00 UTC, markscheel commented
squashed

2021-04-30 21:03 UTC, moxcodes submitted a review, later dismissed

2021-04-30 21:05 UTC, moxcodes commented on tests/Unit/ApparentHorizons/Test_ApparentHorizonFinder.cpp
> +        auto& cache = ActionTesting::cache<target_component>(runner, 0_st);
(Only if you need to make changes for CI failures) This can be `const auto&` I think

2021-04-30 23:40 UTC, markscheel commented
Rebased, fixed CI failures (incompatibility with #3084) , made Jordan's change, squashed.

2021-04-30 23:43 UTC, moxcodes approved these changes

2021-05-04 20:25 UTC, nilsdeppe commented
ping @kidder this got rebased and squashed

2021-05-04 20:27 UTC, kidder approved these changes

2021-05-05 21:24 UTC, merged