Add higher-dim projection operators, child_size function for AMR
sxs-collaboration/spectre pull request #3082
Opened 2021-04-08 17:30 UTC by nilsleiffischer

## Proposed changes

These operators can be used to project data across AMR levels. They are essentially moved from `MortarHelpers`.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-04-08 19:38 UTC, wthrowe requested changes

2021-04-08 19:38 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Spectral/Test_Projection.cpp
> +SPECTRE_TEST_CASE("Unit.Numerical.Spectral.Projection.p.mortar_to_element",
Update the test name for the merged tests.

2021-04-08 19:43 UTC, kidder requested changes

2021-04-08 19:43 UTC, kidder commented on src/Domain/Structure/ChildSize.hpp
> +#include "NumericalAlgorithms/Spectral/Projection.hpp"
please change the include of Matrix.hpp to a forward declaration in Projection.hpp

2021-04-08 19:43 UTC, kidder commented
also fix the clang-tidy error

2021-04-08 19:51 UTC, nilsleiffischer commented
Pushed the forward-declaration as extra commit and squashed in the test name change and the clang-tidy fix. Cheers!

2021-04-08 19:53 UTC, wthrowe submitted a review, later dismissed

2021-04-08 20:06 UTC, kidder submitted a review, later dismissed

2021-04-09 16:32 UTC, nilsleiffischer commented
Added a missing `<ostream>` include

2021-04-09 16:42 UTC, kidder approved these changes

2021-04-09 17:20 UTC, wthrowe approved these changes

2021-04-13 13:39 UTC, merged