Add multigrid hierarchy functions
sxs-collaboration/spectre pull request #3096
Opened 2021-04-14 13:35 UTC by nilsleiffischer

## Proposed changes

Functions to set up a hierarchy of coarsened grids for the multigrid linear solver.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-04-20 14:47 UTC, nilsleiffischer commented
@kidder and @fmahebert would you be willing to take this one?

2021-04-23 02:05 UTC, nilsdeppe requested changes
Please squash directly :)

2021-04-23 02:05 UTC, nilsdeppe commented on src/ParallelAlgorithms/LinearSolver/Multigrid/Hierarchy.hpp
> +#include "Domain/Structure/ElementId.hpp"
I think you only need a forward decl

2021-04-23 02:05 UTC, nilsdeppe commented on src/ParallelAlgorithms/LinearSolver/Multigrid/Hierarchy.cpp
> +  for (size_t block_id = 0; block_id < initial_refinement_levels.size();
could this just be a range-based for loop?

2021-04-23 02:05 UTC, nilsdeppe commented on src/ParallelAlgorithms/LinearSolver/Multigrid/Hierarchy.cpp
> +          gsl::at(initial_refinement_levels.at(block_id), d);
`levels.at` -> `levels[block_id]`

2021-04-23 02:05 UTC, nilsdeppe commented on src/ParallelAlgorithms/LinearSolver/Multigrid/Multigrid.hpp
> +/// Items related to the multigrid linear solver
should this be in the `Linear solver` group?

2021-04-23 15:18 UTC, nilsleiffischer commented
Rebased and squashed in those few changes. Cheers @nilsdeppe!

2021-04-23 16:29 UTC, nilsdeppe approved these changes

2021-05-02 00:12 UTC, fmahebert approved these changes

2021-05-03 08:01 UTC, merged