Compile InfoAtLink.cpp with appropriate flags
sxs-collaboration/spectre pull request #3103
Opened 2021-04-16 01:02 UTC by nilsleiffischer

## Proposed changes

Determine the correct flags for compiling InfoAtLink.cpp and use them in WrapExecutableLinker.sh.

This makes InfoAtLink more robust, enabling #2690 and #2680.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-04-16 16:26 UTC, nilsdeppe requested changes
Have you tested that things like:
- rerunning CMake without any setting changes doesn't require everything to be relinked
- rebuilding an executable several times without changes results in no link/build

2021-04-16 16:26 UTC, nilsdeppe commented on src/Informer/InfoAtLinkExtractFlags.py
> +parser.add_argument("compiler")
some comments as to why you use argparse and these arguments would be helpful, I think

2021-04-17 15:09 UTC, nilsleiffischer commented
@nilsdeppe Seems to work ok, at least the scenarios that I tested. Pushed a few fixups to smooth things out. Before, the script re-ran at every build, but executables didn't re-link. Now, re-building with no changes does nothing.

2021-04-19 16:57 UTC, nilsdeppe reviewed
LGTM, please go ahead and squash :)

2021-04-23 01:25 UTC, nilsdeppe submitted a review, later dismissed

2021-05-11 09:10 UTC, nilsleiffischer commented
@kidder or @wthrowe could you take a look at this one?

2021-05-11 21:38 UTC, wthrowe commented on src/Informer/InfoAtLinkExtractFlags.py
> +parser.add_argument("-c", required=False)
I think the purpose of this code is to remove known options that we don't care about, but -o takes an argument and -c doesn't, so why are these lines the same?

2021-05-12 09:34 UTC, nilsleiffischer commented on src/Informer/InfoAtLinkExtractFlags.py
> +parser.add_argument("-c", required=False)
Thanks for pointing this out. Pushed a fixup to handle this better.

2021-05-13 19:45 UTC, wthrowe requested changes
You can squash this directly.

2021-05-13 19:45 UTC, wthrowe commented on src/Informer/InfoAtLinkExtractFlags.py
> +parser.add_argument("-o", required=False)
This should be `required=True` because you use it unconditionally on line 37.

2021-05-17 20:05 UTC, wthrowe commented
Looks good.  Squash.

2021-05-17 21:55 UTC, wthrowe approved these changes

2021-05-17 22:42 UTC, nilsdeppe approved these changes

2021-05-18 10:19 UTC, merged