Subcell: Cartesian flux divergence, compute boundary terms
sxs-collaboration/spectre pull request #3125
Opened 2021-04-27 15:24 UTC by nilsdeppe

## Proposed changes

- Add a function that computes the flux divergence on a time-independent Cartesian grid
- Add a function to do pack expansion and all `dg_boundary_terms` for the subcell solver

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-04-27 17:26 UTC, kidder requested changes
you can squash

2021-04-27 17:26 UTC, kidder commented on tests/Unit/Evolution/DgSubcell/Test_CartesianFluxDivergence.cpp
> +    dt_var = 0.0;
isn't this redundant with line 34?

2021-04-27 17:26 UTC, kidder commented on tests/Unit/Evolution/DgSubcell/Test_CartesianFluxDivergence.cpp
> +    DataVector dt_var{subcell_extents.product(), 0.0};
can you make this non-zero to test that `add_cartesian_flux_divergence` adds instead of sets

2021-04-28 06:46 UTC, fmahebert reviewed
I only have this additional nitpick, which you may also squash

2021-04-28 06:46 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_CartesianFluxDivergence.cpp
> +        1.0 / (logical_coords.get(0)[1] - logical_coords.get(0)[0]);
[nitpick] use compile-time `get<0>(logical_coords)[...]`

2021-04-28 22:28 UTC, nilsdeppe commented
I've rebased and squashed in the changes. Thanks so much for the reviews! :D

2021-04-29 00:17 UTC, fmahebert approved these changes

2021-04-29 19:55 UTC, kidder approved these changes

2021-04-29 19:55 UTC, merged