Subcell: Add action TciAndSwitchToDg
sxs-collaboration/spectre pull request #3133
Opened 2021-04-30 00:37 UTC by nilsdeppe

## Proposed changes

Add an action that runs the TCI on the subcell grid and then decides whether or not to switch back to DG. The decision making process is a bit tedious because we ultimately need to support substep, multistep, one high-order one-step (ADER) methods

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-01 23:22 UTC, fmahebert commented on src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp
> + *    TCI or try to go back to DG. We need to avoid reconstructing the time
By "reconstructing the time stepper history", I assume you mean reconstructing the DG soln from the subcell values? Do you think it would be useful to clarify this (e.g., like in item 2 below)? I'm just thinking that "reconstruction" can also be used as a FD-only operation, which isn't really the one you're performing here I think?

2021-05-01 23:22 UTC, fmahebert commented on src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp
> + *    (TCI), checking both the subcell solution at \f$t^{n+1}\f$ and the
t^{n+1} meaning that you're checking the "candidate" solution for the next time step before considering the time step to be complete? It would be nice to discuss somewhere (perhaps before this list of steps in the algorithm) where the action fits into the DG-subcell scheme.

2021-05-01 23:22 UTC, fmahebert commented on src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp
> +S * 4. If the RDMP TCI marked the DG solution as admissible, run the
Sremove the extra 'S' at the beginning of this line

2021-05-01 23:22 UTC, fmahebert commented on src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp
> +    if (db::get<::Tags::TimeStepId>(box).substep() != 0 or
Why not `time_step_id.substep()` since you've already assigned a variable for this?

2021-05-01 23:22 UTC, fmahebert commented on src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp
> +            // Project the time stepper history to the subcells.
Isn't this backwards? Based on item 5 from the main docs above and the code below, I was expecting this to say something like "Reconstruct the DG solution for each time in the time stepper history"

2021-05-03 19:15 UTC, nilsdeppe commented
I've rebased and pushed a fixup. Thanks for the review!

2021-05-03 19:24 UTC, fmahebert reviewed
LGTM, please squash

2021-05-03 19:40 UTC, nilsdeppe commented
Thanks for looking at the fixup so quickly! I've squashed that in :)

2021-05-06 17:33 UTC, nilsdeppe commented
I've rebased this on develop and also added a fixup that resets the `DidRollback` to `false` in this action. The change is needed to avoid unintentionally recomputing primitives when they aren't needed.

2021-05-06 17:41 UTC, fmahebert commented
Seems good. But can you add action's action on `DidRollback` to the documentation? I'm thinking at least in the list of Databox quantities modified, and perhaps also in words above (up to you).

2021-05-06 18:42 UTC, nilsdeppe commented
Agreed! Pushed a fixup that adds some documentation on that front. Please let me know if you have any suggestions for improving the documentation :)

2021-05-06 19:25 UTC, fmahebert commented
No further comments, the doc fixup looks good! Please squash.

2021-05-06 22:03 UTC, nilsdeppe commented
Rebased and squashed. Thanks for reviewing :)

2021-05-07 01:52 UTC, kidder requested changes
you can squash immediately

2021-05-07 01:52 UTC, kidder commented on src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp
> + * 1. if we are using a substep time integrator and are not at the end of a
if -> If

2021-05-07 01:52 UTC, kidder commented on tests/Unit/Evolution/DgSubcell/Actions/Test_TciAndSwitchToDg.cpp
> +  // 5. Check if RDMP is not triggered, but tci_mutator is, we stay SCL
SCL -> on subcell

2021-05-07 16:27 UTC, nilsdeppe commented
I've rebased (conflict in  CMakeLists.txt) and squashed. Thanks for the reviews :)

2021-05-07 16:42 UTC, fmahebert approved these changes

2021-05-07 21:19 UTC, kidder approved these changes

2021-05-07 21:19 UTC, merged