Subcell: add functions for the DG actions to call to support subcell
sxs-collaboration/spectre pull request #3137
Opened 2021-04-30 03:41 UTC by nilsdeppe

## Proposed changes

The DG actions `ComputeTimeDerivative` and `ApplyBoundaryCorrections` need to be aware that subcell exists. However, the DG library doesn't depend on DG-subcell because we just forward declare the functions and hide them behind an `if constexpr (using_subcell)`. This means that non-subcell executables shouldn't need to link against DG-subcell.

Note that currently the DG-FD interface are not conservative. While making them be conservative wouldn't be too terribly difficult, so far I have no evidence that this actually matters since if we are doing DG the solution is smooth anyway.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-07 00:22 UTC, fmahebert reviewed
Code looks good, but I have some clarification requests on the documentation

2021-05-07 00:22 UTC, fmahebert commented on src/Evolution/DgSubcell/PrepareNeighborData.hpp
> + * troubled-cell indicator, and compute and slice data needed for the neighbor
[super nitpicky] It may be helpful to clarify "Add local data for the neighbor's relaxed discrete maximum principle troubled-cell indicator, ..." because it can be easy to forget how this hangs together.

2021-05-07 00:22 UTC, fmahebert commented on src/Evolution/DgSubcell/NeighborReconstructedFaceSolution.hpp
> + * combined with the data from element and stored in
"from element" -> "from the neighbor element" I assume? or local?

2021-05-07 00:22 UTC, fmahebert commented on src/Evolution/DgSubcell/NeighborReconstructedFaceSolution.hpp
> + * `subcell::Tags::NeighborDataForReconstructionAndRdmpTci`.
I would favor switching the order of sentences, I think this will make the description match the name (and therefore prior expectation) better so be less surprising: "The data needed for reconstruction... Additionally, the max/min of the evolved variables...". Could also help to add a short note of why you're handling the RDMP data at this time... it's not obvious how it's related to the reconstruction. I'm guessing you're handling it now because it's convenient but isn't needed for the reconstruction?

2021-05-07 00:22 UTC, fmahebert commented on src/Evolution/DgSubcell/NeighborReconstructedFaceSolution.hpp
> +  // algorithm is left untouched.
I have no idea what this sentence is trying to say... can you rephrase?

2021-05-07 00:22 UTC, fmahebert commented on src/Evolution/DgSubcell/NeighborReconstructedFaceSolution.hpp
> +          // since we might be doing a step unwind.
Can you expand on this a little? does `neighbor_ghost_and_subcell_data` get erased when unwinding? I'm not quite sure what is meant here so a few more words would help I think.

2021-05-07 00:22 UTC, fmahebert commented on src/Evolution/DgSubcell/NeighborReconstructedFaceSolution.hpp
> +                  2 * static_cast<std::ptrdiff_t>(number_of_evolved_vars)));
Help what is going on? Is this copying the first (ghost) part of `neighbor_ghost_and_subcell_data`, and omitting the subcell part? What is the "2" here? I think a comment might be useful.

2021-05-07 16:00 UTC, nilsdeppe commented
I've pushed fixups that try to clarify the comments and dox. Please let me know if it is now actually clear :)

2021-05-07 16:45 UTC, fmahebert reviewed
Fixups LGTM, you can squash. Thanks for the clarifications!

2021-05-07 16:50 UTC, nilsdeppe commented
Rebased and squashed. Thanks for the review :D

2021-05-07 16:53 UTC, fmahebert approved these changes, later dismissed

2021-05-07 21:55 UTC, kidder requested changes
you can squash immediately

2021-05-07 21:55 UTC, kidder commented on src/Evolution/DgSubcell/PrepareNeighborData.hpp
> +  for (const auto& direction_neighbors : element.neighbors()) {
use structured binding?

2021-05-07 21:55 UTC, kidder commented on src/Evolution/DgSubcell/PrepareNeighborData.hpp
> +    std::vector<double>& neighbor_scl_data =
scl -> subcell

2021-05-11 16:07 UTC, nilsdeppe commented
I've rebased and squashed, thanks for the reviews :)

2021-05-11 19:13 UTC, fmahebert approved these changes

2021-05-12 01:37 UTC, kidder approved these changes

2021-05-12 01:38 UTC, merged