Add action to take time step on FD grid
sxs-collaboration/spectre pull request #3139
Opened 2021-04-30 05:05 UTC by nilsdeppe

## Proposed changes

Exactly as the name says.

The action basically farms out to a system-specific implementation since if we've fallen back to FD the generic solvers just aren't robust enough. 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-07 01:59 UTC, fmahebert commented on src/Evolution/DgSubcell/Actions/TakeTimeStep.hpp
> +/// \brief %Actions specific to using a finite-difference subcell method.
Can the namespace documentation be moved to a more generic header?

2021-05-07 01:59 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Actions/Test_TakeTimeStep.cpp
> +  // using system = System<Dim>;
Delete

2021-05-07 16:59 UTC, nilsdeppe commented
I've:
- rebased
- squashed in the removal of the commented out line
- prepended a commit that documents the namespace in `DgSubcell/Actions/Actions.hpp`

Thanks for the review :)

2021-05-07 17:03 UTC, fmahebert submitted a review, later dismissed

2021-05-08 00:01 UTC, kidder requested changes
you can squash immediately

2021-05-08 00:01 UTC, kidder commented on src/Evolution/DgSubcell/Actions/TakeTimeStep.hpp
> + * DataBox:
blank line to render correctly

2021-05-11 16:33 UTC, nilsdeppe commented
I've rebased and squashed. Thanks for the reviews :)

2021-05-11 20:25 UTC, fmahebert approved these changes

2021-05-12 01:55 UTC, kidder approved these changes

2021-05-12 01:55 UTC, merged