Subcell: Add function to correct packaged data for conservation
sxs-collaboration/spectre pull request #3140
Opened 2021-04-30 15:55 UTC by nilsdeppe

## Proposed changes

Add a function that overwrites the packaged data computed by reconstruction with the data sent from neighboring elements and optionally, if the step is being retaken, with the DG data sent to the neighboring elements. This doesn't quite get us to strict conservation, the remaining part is computing the boundary corrections on the DG elements on the subcell interface and then reconstructing that back to the element.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-12 00:41 UTC, fmahebert requested changes

2021-05-12 00:41 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * correction's packaged data.
- This brief makes it appear the main job of this function is a copy, but the PR name, file name, the text below and the function name emphasize the correction for conservation. I'm not sure whether the copy / projection / correction is the fundamental concept here, but I'd suggest using the fundamental concept as the name in all these places to help the reader.
- I don't quite understand the "to or from a DG neighbor into the subcell bdry corr packaged data" clause...
  - in the "to" part ("to a DG neighbor into the subcell bdry corr packaged data") doesn't make any sense to me
  - in the "from" part ("from a DG neighbor into the subcell bdry corr packaged data") does seem consistent with the code, because I understood you were receiving DG neighbor data regardless of rollback or no.

It's quite likely it's just my understanding is broken. So feel free to elaborate in a github comment.. but it might be helpful to rephrase the brief either way.

2021-05-12 00:41 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * DG element must also compute \f$G+D\f$ on the subcells.
After reading this paragraph I want to know where the other half of the correction is done. Can you add a sentence expanding on this? Is there (or will there be) another function to do that other correction, or do we simply not do that other part of the correction?

2021-05-12 00:41 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * element doing subcell by projecting the neighbor's DG data onto the subcells.
If I'm understanding this right, I would suggest a change like "on an element doing subcell by projecting..." -> "received by an element doing subcell by projecting...".

It's a bit pedantic, but I think this is important here.

2021-05-12 00:41 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * then projected to the subcells.
1. Typo: "gaurantee" -> "guarantee" (at beginning of sentence)
2. Please clarify if this sentence is describing what is done or what should be (but is not) done.

2021-05-12 00:41 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> +      element.neighbors().at(upper_direction).size() != 0;
I think this is simpler as `element.neighbors().contains(upper_direction);` (and same below)

2021-05-12 00:41 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_CorrectPackagedData.cpp
> +      // Check upper data
Is this out of date? I think `direction_to_check` means this works for lower and upper data?

2021-05-12 00:41 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_CorrectPackagedData.cpp
> +    // Reset volume data and then check that we can bring back both local and
I don't know what you mean by "bring back"

2021-05-12 00:41 UTC, fmahebert commented on tests/Unit/Evolution/DgSubcell/Test_CorrectPackagedData.cpp
> +    // overwritten that we don't overwrite it.
"that" -> "then"

2021-05-12 00:41 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> +        std::vector<double> projected_data{};
Can't this be declared/initialized inside the `if constexpt`?

2021-05-12 00:41 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> +  const auto copy_dg_data_to_subcells =
[nitpick] I suggest "copy_dg_data_to_subcells" -> "project_dg_data_to_subcells" or similar... depending on how you decide to name everything.

2021-05-12 16:17 UTC, nilsdeppe commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * correction's packaged data.
I think the following is maybe clearer:
```
Project the DG package data from a boundary correction to the subcells. Projects the data sent by neighboring elements doing DG and if `OverwriteInternalMortarData` is `true`, the local DG package data sent to the neighbor is projected in the case that we are retaking a time step.
```

2021-05-12 16:20 UTC, nilsdeppe commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> +        std::vector<double> projected_data{};
nope, then the pointer `slice_data` becomes invalid because the vector goes out of scope at the end of the `if constexpr` and is deallocated.

2021-05-12 16:44 UTC, nilsdeppe commented
I've rebased and pushed a fixup. Thanks for the review :)

2021-05-13 03:18 UTC, fmahebert reviewed
Thanks for clarifying things! You can squash including these suggestions

2021-05-13 03:18 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * \brief Project the DG package data to the subcells. Data sent by a
I suggest "sent by" -> "received from" to keep things w.r.t. the local element

2021-05-13 03:18 UTC, fmahebert commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * Note that we currently do not currently do the other half of the correction
Fix "we currently do not currently do"

2021-05-13 17:57 UTC, nilsdeppe commented
Rebased and squashed in changes. Thanks for the review! :D

2021-05-14 19:43 UTC, kidder reviewed
either suggestions for clarification of the documentation, or showing my confusion which will lead to suggestions for clarification...

2021-05-14 19:43 UTC, kidder commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * our neighbors before doing a rollback is only projected if
... roll back from DG to subcell is ...

2021-05-14 19:43 UTC, kidder commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * both grids. In practice this means the boundary corrections \f$G+D\f$ must be
both elements?

2021-05-14 19:43 UTC, kidder commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * `true` then the local (the element doing subcell) ingredients into \f$G+D\f$
this is the element that switched from DG to subcell?  if so, "(the element switching from DG to subcell)"

2021-05-14 19:43 UTC, kidder commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * are projected and overwrite the data computed from reconstruction. However,
what reconstruction?  I thought we were on an element that switched from DG to subcell

2021-05-14 21:03 UTC, nilsdeppe commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * are projected and overwrite the data computed from reconstruction. However,
yes, but you still need to do reconstruction on the FD grid to get data on the mortar. Would `from the FD reconstruction to the interface` be clear?

2021-05-14 21:08 UTC, kidder commented on src/Evolution/DgSubcell/CorrectPackagedData.hpp
> + * are projected and overwrite the data computed from reconstruction. However,
yes

2021-05-14 23:34 UTC, nilsdeppe commented
I've rebased on develop and squashed in the documentation updates.Thanks for the reviews :)

2021-05-15 17:12 UTC, kidder approved these changes

2021-05-15 18:31 UTC, fmahebert approved these changes

2021-05-16 17:13 UTC, merged