Allow reference tags to list multiple arguments
sxs-collaboration/spectre pull request #3142
Opened 2021-04-30 21:47 UTC by nilsvu

## Proposed changes

Remove `parent_tag`s and use `argument_tag`s instead. This removes the restriction that reference tags can only have a single argument. My use case for this is to store an elastic constitutive relation _per block_ in the global cache and reference the correct one in the element's DataBox, which needs both the global cache tag and the element ID.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-04-30 21:51 UTC, nilsvu commented
@kidder The unit tests pass, but could you make sure I didn't majorly mess up the compute-item dependency tracking? I'll also add more tests.

2022-01-18 22:01 UTC, nilsdeppe reviewed
Looks good. I would like to see this feature merged :)

Might be good to add a reference tag that depends on a reference tag? Something like if some bool is `true` then choose tag `Scalar1` otherwise `Scalar2` where `Scalar1` and `Scalar2` are in two different `Variables`. Then test that mutating the bool, or either of the `Variables` tags has the tag be updated. I think this will test the new functionality. You could do something similar with compute tags + subitems to be extra sure since probably any bug in this will be horrible to track down in an executable.

2023-02-13 23:42 UTC, nilsvu commented
@kidder I have rebased this PR, simplified it, and added some more tests. Could you take a look please?

2023-02-20 20:57 UTC, kidder requested changes
you can squash

2023-02-20 20:57 UTC, kidder commented on src/DataStructures/DataBox/Tag.hpp
> + * - static function `get` that, given the item fetched by `argument_tags`,
item -> items

2023-02-20 21:00 UTC, nilsvu commented on src/DataStructures/DataBox/Tag.hpp
> + * - static function `get` that, given the item fetched by `argument_tags`,
done

2023-02-21 17:57 UTC, kidder approved these changes

2023-02-21 18:29 UTC, merged