Subcell: tags LowerSpatialFourVelocity, OnSubcells, OnSubcellFaces, SubcellSolver option group
sxs-collaboration/spectre pull request #3156
Opened 2021-05-11 21:37 UTC by nilsdeppe

## Proposed changes

These are tags needed for doing GRMHD. The `OnSubcells` will be used to mark the analytic spacetime variables as being the ones on the subcells. We also need spacetime vars on the subcell faces.

The `LowerSpatialFourVelocity` (`u_i`) will be what we reconstruct since this is what SpEC and most other (M)HD codes do nowadays.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-12 03:11 UTC, kidder requested changes
you can squash immediately

2021-05-12 03:11 UTC, kidder commented on src/Evolution/DgSubcell/Tags/OnSubcells.hpp
> +#include "DataStructures/DataBox/DataBoxTag.hpp"
just Tag

2021-05-12 03:11 UTC, kidder commented on src/Evolution/DgSubcell/Tags/OnSubcellFaces.hpp
> +#include "DataStructures/DataBox/DataBoxTag.hpp"
just Tag

2021-05-12 03:11 UTC, kidder commented on src/PointwiseFunctions/Hydro/Tags.hpp
> +/// The lower index spatial for velocity \f$u_i\f$.
try again :). I'd suggest `The spatial components of the four-velocity one-form`

2021-05-12 16:09 UTC, nilsdeppe commented
I rebased on develop and squashed in the changes. Thanks for the review :)

2021-05-12 20:02 UTC, kidder approved these changes

2021-05-13 05:03 UTC, fmahebert approved these changes

2021-05-13 15:01 UTC, merged