Subcell NewtEul: Add subcell directory and DgInitialDataTci mutator
sxs-collaboration/spectre pull request #3176
Opened 2021-05-17 20:55 UTC by nilsdeppe

## Proposed changes

- Adds the subcell directory for Newtonian Euler
- Adds the TCI run on the initial data to figure out where the initial data is already bad

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-18 00:17 UTC, fmahebert submitted a review, later dismissed

2021-05-22 23:00 UTC, kidder requested changes
you can squash

2021-05-22 23:00 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/InitialDataTci.hpp
> +#include "DataStructures/VariablesTag.hpp"
unused

2021-05-22 23:00 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/InitialDataTci.hpp
> +/// \endcond
forward declare Variables

2021-05-24 17:39 UTC, nilsdeppe commented
I've rebased and squashed the changes. Thanks for the reviews :)

2021-05-24 17:42 UTC, fmahebert approved these changes

2021-05-24 21:33 UTC, kidder approved these changes

2021-05-25 15:51 UTC, merged