Add Grmhd riemann problems analytic data
sxs-collaboration/spectre pull request #3180
Opened 2021-05-18 15:31 UTC by nilsdeppe

## Proposed changes

Add the GRMHD Riemann problems as an analytic data. The exact solution is not easy to compute.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-21 01:37 UTC, fmahebert reviewed
Some nitpicks, feel free to squash directly.

2021-05-21 01:37 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticData/GrMhd/RiemannProblem.cpp
> +  p | background_spacetime_;
[nitpick] move eos and background to top of list so the pup order matches declaration order + initialization order, makes it easier to read.

2021-05-21 01:37 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticData/GrMhd/RiemannProblem.hpp
> + * index than the rest.
Would be helpful to add a discussion of the background spacetime. Why are the lapse and shift options if they have the same values in all these problems? why are they options if the background spacetime is set to minkowski always?

I would organize this as 3 short paragraph: First, the current sentences about the domain. Then, new sentences about the background. Last, the current sentences explaining the initial conditions from the reference.

2021-05-21 01:37 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticData/GrMhd/RiemannProblem.hpp
> + * \f$y\f$ and \f$z\f$. The problems are usually run at a resolution of 1600
Say somewhere in the discussion of the domain that the discontinuity is initially at x = 0.

2021-05-21 15:29 UTC, nilsdeppe commented
I've squashed in the changes. Thanks for the review and let me know if the sentences I've added aren't clear :)

2021-05-21 17:00 UTC, fmahebert approved these changes, later dismissed
LGTM, thanks!

2021-05-22 23:18 UTC, kidder reviewed
you can squash

2021-05-22 23:18 UTC, kidder commented on docs/References.bib
> +  month =        {jan},
`Jan` or remove the braces?

2021-05-24 05:38 UTC, kidder requested changes
not sure why my comment about the reference didn't make a request change

2021-05-24 18:06 UTC, nilsdeppe commented
I've rebased and squashed in the braces removal. Thanks for reviewing :)

2021-05-24 18:30 UTC, fmahebert approved these changes

2021-05-24 20:56 UTC, kidder commented on docs/References.bib
> +  month =        {jan},
This fixed the month, but now the year isn't rendering correctly, but I notice this happens for several entires and it is not obvious to me what is different about them.  So I suggest merging this PR and opening an issue about the incorrect rendering...

2021-05-24 20:56 UTC, kidder approved these changes

2021-05-24 22:53 UTC, merged