Grmhd spherical blast wave analytic data
sxs-collaboration/spectre pull request #3181
Opened 2021-05-19 18:00 UTC by nilsdeppe

## Proposed changes

Generalizes the cylindrical blast wave analytic data to be able to choose either a cylindrical or a spherical explosion

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-21 01:47 UTC, fmahebert reviewed
A nice generalization 👍 

Edit to add: you can squash changes directly

2021-05-21 01:47 UTC, fmahebert commented on src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivCleanFwd.hpp
> +class BlastWave;
Alphabetize perhaps?

2021-05-21 01:47 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticData/GrMhd/CMakeLists.txt
> +  BlastWave.cpp
Alphabetize (and headers below)

2021-05-21 01:47 UTC, fmahebert commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/CMakeLists.txt
> +  Test_BlastWave.cpp
Alphabetize

2021-05-21 01:47 UTC, fmahebert commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_BlastWave.cpp
> +      outer_pressure, magnetic_field, adiabatic_index, geometry);
if `geometry` is specifiable, the variable should be renamed `cylindrical_blast_wave` -> `blast_wave`

2021-05-21 01:47 UTC, fmahebert commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_BlastWave.cpp
> +      outer_pressure, magnetic_field, adiabatic_index, geometry);
if `geometry` is specifiable, the variable should be renamed `cylindrical_blast_wave` -> `blast_wave`

2021-05-21 01:47 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticData/GrMhd/BlastWave.cpp
> +    const grmhd::AnalyticData::BlastWave::Geometry geometry,
[super nitpick, feel free to veto] Put the Geometry argument last to match all other functions

2021-05-21 15:57 UTC, nilsdeppe commented
I've pushed fixups. Thanks for reviewing :)

2021-05-21 17:03 UTC, fmahebert reviewed
LGTM, I think I see just one comment not yet addressed. Please squash including this last one

2021-05-21 17:03 UTC, fmahebert commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_BlastWave.cpp
> +      outer_pressure, magnetic_field, adiabatic_index, geometry);
ping on this one

2021-05-21 20:07 UTC, nilsdeppe commented
Done and squashed. Thanks for reviewing :)

2021-05-22 00:31 UTC, fmahebert commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_BlastWave.cpp
> +  BlastWaveProxy cal_blast_wave(inner_radius, outer_radius, inner_density,
maybe the third time will be the charm 🙃

2021-05-23 03:42 UTC, kidder requested changes
you can squash

2021-05-23 03:42 UTC, kidder commented on docs/References.bib
> +  journal =      {\aap},
fix (either supply the journal or add whatever file is missing that defines `\aap`

2021-05-23 03:42 UTC, kidder commented on docs/References.bib
> +  journal =      {\aap},
fix

2021-05-23 03:42 UTC, kidder commented on docs/References.bib
> +  doi =          {10.1088/1361-6382/ab8be8},
this needs the url added

2021-05-24 18:05 UTC, nilsdeppe commented
I have tried again :D Thanks for reviewing :)

2021-05-24 20:20 UTC, kidder approved these changes

2021-05-24 22:55 UTC, merged