Add interpolation target for user-specified points
sxs-collaboration/spectre pull request #3191
Opened 2021-05-21 23:18 UTC by fmahebert

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-23 20:33 UTC, kidder requested changes
you can squash

2021-05-23 20:33 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetSpecifiedPoints.cpp
> +  p | points;
include pup

2021-05-23 20:33 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetSpecifiedPoints.cpp
> +    : points(std::move(points_in)) {}
include utility

2021-05-23 20:33 UTC, kidder commented on src/NumericalAlgorithms/Interpolation/InterpolationTargetSpecifiedPoints.hpp
> +#include "Utilities/TaggedTuple.hpp"
unused

2021-05-24 15:32 UTC, fmahebert commented
I've updated the includes. Thanks for catching these @kidder

2021-05-24 15:39 UTC, kidder approved these changes

2021-05-25 15:56 UTC, nilsdeppe approved these changes

2021-05-25 15:56 UTC, merged