Convert Event to use factory map
sxs-collaboration/spectre pull request #3196
Opened 2021-05-25 00:57 UTC by wthrowe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-25 10:00 UTC, nilsleiffischer requested changes

2021-05-25 10:00 UTC, nilsvu commented on src/Elliptic/Executables/Xcts/SolveXcts.hpp
> +                                  volume_dim, linear_solver_iteration_id,
`linear_solver_iteration_id` -> `nonlinear_solver_iteration_id`

2021-05-25 10:00 UTC, nilsvu commented on src/ParallelAlgorithms/EventsAndTriggers/CMakeLists.txt
> +
This dependency should be added to `Parallel` instead

2021-05-25 19:02 UTC, nilsleiffischer approved these changes, later dismissed

2021-05-25 19:02 UTC, nilsleiffischer commented on src/Parallel/CMakeLists.txt
> +  module_GlobalCache
(optional) this could reasonably be a separate commit

2021-05-25 19:04 UTC, nilsleiffischer commented on src/Parallel/CMakeLists.txt
> +  module_GlobalCache
Oh actually you just have to rebase, I added this already in #3144

2021-05-26 20:55 UTC, nilsdeppe approved these changes

2021-05-26 21:19 UTC, nilsleiffischer approved these changes

2021-05-26 23:15 UTC, merged