Subcell GRMHD: add VariablesNeededFixing tag and TCI options
sxs-collaboration/spectre pull request #3197
Opened 2021-05-25 15:39 UTC by nilsdeppe

## Proposed changes

- The `VariablesNeededFixing` is used when on the subcells to tell the TCI if the solution was bad and we shouldn't go back to DG. 
- And `TciOptions` struct that houses the system-specific TCI options. At some point it might be worth revisiting the input file layout for all the subcell code, but I think that's best done after we can do evolutions and know what features we need.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-25 17:03 UTC, kidder requested changes

2021-05-25 17:03 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOptions.hpp
> +  /// \brief Safety factor \f$\epsilon_B\f$.
Please include a bit more information; I have no idea reading this if it should be big or small (it's fine to point to some other more detailed documentation)

2021-05-26 16:38 UTC, fmahebert commented
I have no additional requests

2021-05-26 17:51 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOptions.hpp
> +  /// \brief Safety factor \f$\epsilon_B\f$.
I can't link to the `TciOnDgGrid` yet because it's not merged. I'll add a sentence that this is where the documentation will be

2021-05-26 17:52 UTC, nilsdeppe commented
I've rebased and squashed in the additional sentence pointing to the (not yet merged) documentation of the TciOnDgGrid mutator. Thanks for the reviews :)

2021-05-26 20:23 UTC, kidder approved these changes

2021-05-26 20:27 UTC, fmahebert approved these changes

2021-05-27 15:05 UTC, merged