Subcell: Add TciOnDgGrid mutator for NewtonianEuler
sxs-collaboration/spectre pull request #3198
Opened 2021-05-25 20:03 UTC by nilsdeppe

## Proposed changes

Add the troubled-cell indicator on the DG grid for NewtonianEuler.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-26 21:01 UTC, fmahebert commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.hpp
> + * \f$10^{-18}\f$, and runs the Persson TCI on the density and pressure. The
Can you explain this check (density vs 1e-18, pressure vs 1e-18) and this magic number? Can you also clarify the wording as to when the TCI reports "troubled" vs "okay"... I think I find the words "checks that the min density [is] above X" unclear because if the density is indeed above X, I'm not sure if the TCI returns true or false.

2021-05-26 21:01 UTC, fmahebert commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.cpp
> +                                             persson_exponent, 1.0e-18) or
Should this be `min_density_allowed` (and pressure below)? Or is it a coincidence that these numbers match? If a coincidence, it would be useful to assign a new `constexpr double blah = 1e-18` to help disambiguate.

2021-05-26 21:01 UTC, fmahebert commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnDgGrid.cpp
> +       {TestThis::AllGood, TestThis::SmallDensity, TestThis::PerssonDensity}) {
I'd like to see corresponding checks for TCI triggers based on pressure, because as-is you're only testing half of the TCI's logic. For the NE system at least, I would expect it would be reasonable to construct inputs such that the post-recovery pressure has the needed "bad" behavior... but perhaps I'm missing something?

2021-05-27 00:30 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnDgGrid.cpp
> +       {TestThis::AllGood, TestThis::SmallDensity, TestThis::PerssonDensity}) {
I'll try it. I need to change from a polytrope to an ideal gas, but that should be fine

2021-05-27 00:53 UTC, nilsdeppe commented
I've rebased and pushed a fixup. Thanks for the review :)

2021-05-27 03:03 UTC, kidder requested changes

2021-05-27 03:03 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.cpp
> +    const gsl::not_null<Variables<
`#include "Utilities/Gsl.hpp"`

2021-05-27 03:03 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.cpp
> +        tmpl::list<MassDensity, Velocity, SpecificInternalEnergy, Pressure>>*>
`#include "Utilities/TMPL.hpp"`

2021-05-27 03:03 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.cpp
> +    const EquationsOfState::EquationOfState<false, ThermodynamicDim>& eos,
include for EoS

2021-05-27 03:03 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.hpp
> +      const gsl::not_null<Variables<
forward declare Variables and gsl::not_null

2021-05-27 03:03 UTC, kidder commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnDgGrid.cpp
> +#include "Evolution/DgSubcell/Mesh.hpp"
not used

2021-05-27 03:03 UTC, kidder commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnDgGrid.cpp
> +#include "Evolution/DgSubcell/Tags/Inactive.hpp"
not used

2021-05-27 03:03 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.hpp
> +  template <typename Tag>
where is this used?

2021-05-27 03:03 UTC, kidder commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnDgGrid.cpp
> +using Inactive = evolution::dg::subcell::Tags::Inactive<Tag>;
where is this used?

2021-05-27 06:38 UTC, fmahebert reviewed
LGTM, please squash

2021-05-27 15:33 UTC, nilsdeppe commented
I've rebased and squashed in the changes (got Larry's permission offline)

2021-05-27 17:14 UTC, fmahebert approved these changes

2021-05-27 20:59 UTC, kidder approved these changes

2021-05-27 20:59 UTC, merged