Subcell: Add TciOnDgGrid mutator for NewtonianEuler
sxs-collaboration/spectre pull request #3199
Opened 2021-05-25 22:30 UTC by nilsdeppe

## Proposed changes

Add the troubled-cell indicator on the FD grid for NewtonianEuler.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-27 21:38 UTC, kidder requested changes
you can squash

2021-05-27 21:38 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnFdGrid.hpp
> + * reconstructed to the DG grid, and so `Inactive<Tag>` is updated DG solution.
is the updated

2021-05-27 21:38 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnFdGrid.hpp
> +      gsl::not_null<Variables<
forward declare Variables

2021-05-27 21:38 UTC, kidder commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnFdGrid.cpp
> +        TestThis::SmallDensitySubcell, TestThis::PerssonDensity}) {
add tests for pressure triggers?

2021-05-28 01:54 UTC, fmahebert commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnFdGrid.cpp
> +                                             persson_exponent, 1.0e-18) or
Can you make a `constexpr double persson_tci_epsilon = 1.0e-18;` as in the other TCI?

2021-05-28 01:54 UTC, fmahebert commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnFdGrid.hpp
> + * pressure is to flag cells at contact discontinuities.
Update this to match the newer text in the other TCI

Also, can you explain why you check both grids in a function "TciOnFdGrid" ?

2021-06-01 19:10 UTC, nilsdeppe commented
I've rebased and pushed a fixup. Thanks for the reviews!

2021-06-01 19:24 UTC, kidder requested changes
you have my permission to squash (including the one additional requested change)

2021-06-01 19:24 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TciOnFdGrid.hpp
> + *   cells at contact discontinuities. The Persson TCI is only works with
is only -> only

2021-06-01 19:46 UTC, fmahebert commented
LGTM, please squash

2021-06-01 20:58 UTC, nilsdeppe commented
I've squashed. Thanks for reviewing :)

2021-06-02 19:07 UTC, kidder approved these changes

2021-06-02 21:07 UTC, fmahebert approved these changes

2021-06-02 21:23 UTC, merged