Fix failure in CylindricalSide
sxs-collaboration/spectre pull request #3208
Opened 2021-05-28 01:23 UTC by markscheel

## Proposed changes

Two commits: one fixes #3169 (I ran 20,000 times on my machine without a failure)
The other allows more information to get printed on test failures where inverse maps
return invalid std::optionals.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-05-28 11:16 UTC, nilsleiffischer requested changes
squash directly

2021-05-28 11:16 UTC, nilsleiffischer commented on tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  CHECK(expected_test_point.has_value());
better to replace `CHECK` -> `REQUIRE` here (there's no point continuing the test when this check fails). Same for the test below

2021-05-29 01:49 UTC, geoffrey4444 submitted a review, later dismissed
But please fix test failure

2021-06-01 16:01 UTC, markscheel commented
Made changes and squashed.  The failing test was a timeout in `InputFiles.Xcts.Schwarzschild.yaml.execute_check_output` which has nothing to do with the changes in this PR.

2021-06-03 22:52 UTC, nilsdeppe commented
@nilsleiffischer @geoffrey4444 please take a look at the updated version

2021-06-04 11:47 UTC, nilsleiffischer approved these changes

2021-06-04 18:54 UTC, kidder approved these changes

2021-06-04 18:54 UTC, merged