Add SphericalCompression TimeDependence
sxs-collaboration/spectre pull request #3228
Opened 2021-06-03 04:01 UTC by geoffrey4444

## Proposed changes

This PR adds a TimeDependence for the SphericalCompression time-dependent map, so that it can be used on a spherical shell for single-BH runs. Previously, it only worked hard-coded into the BBH domain, but this will let it work with a shell (provided the map's min and max radii are the inner and outer shell radii, respectively). 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-08 20:37 UTC, fmahebert requested changes

2021-06-08 20:37 UTC, fmahebert commented on src/Domain/Creators/TimeDependence/SphericalCompression.hpp
> +template <size_t MeshDim>
Why is this code templated on dimension when the dimension is required to be 3? I strongly suggest removing the template, but if there's a reason we need it, it should be documented.

2021-06-08 20:37 UTC, fmahebert commented on tests/Unit/Domain/Creators/TimeDependence/Test_SphericalCompression.cpp
> +template <size_t MeshDim>
I think you can hardcode 3 and remove the template parameter.

2021-06-08 20:37 UTC, fmahebert commented on tests/Unit/Domain/Creators/TimeDependence/Test_SphericalCompression.cpp
> +  // The points are all positive to guarantee that they are in the region where
I think this would be clearer rephrased as "The points are drawn from the positive x/y/z quadrant in a way that guarantees that..."

2021-06-08 20:37 UTC, fmahebert commented on src/Domain/Creators/TimeDependence/SphericalCompression.hpp
> +        "Names of SizeMap function of time."};
Should "SizeMap" -> "SphericalCompression" ? And in the comment above, should "size map" -> "spherical compression" ? Do a search for this, it appears in several strings and comments throughout this header file...

2021-06-08 20:37 UTC, fmahebert commented on src/Domain/Creators/TimeDependence/SphericalCompression.cpp
> +      function_of_time_name_(std::move(function_of_time_name)) {}
Should there be a `PARSE_ERROR` that checks min_radius < max_radius?

2021-06-08 20:37 UTC, fmahebert commented on src/Domain/Creators/TimeDependence/SphericalCompression.cpp
> +  ASSERT(number_of_blocks > 0, "Must have at least one block to create.");
[nitpick] But this isn't creating blocks, is it? More like maps? Should this say "Must have at least one block on which to create a map" ?

2021-06-08 20:37 UTC, fmahebert commented on src/Domain/Creators/TimeDependence/SphericalCompression.hpp
> +  struct Center {
Did you want to add a doxygen comment for this one?

2021-06-10 00:02 UTC, nilsdeppe reviewed
Looks good, just a few minor dox suggestions. Feel free to squash my changes directly :)

2021-06-10 00:02 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependence/SphericalCompression.hpp
> +  /// \brief Initial velocity for the function of time for the size map
`velocity` -> `radial velocity`?

2021-06-10 00:02 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependence/SphericalCompression.hpp
> +  /// \brief Initial acceleration for the function of time for the size map
`acceleration` -> `radial acceleration`?

2021-06-10 00:02 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependence/SphericalCompression.hpp
> +    static constexpr Options::String help = {"SizeMap value at initial time."};
`SizeMap` -> `Spherical compression`?

2021-06-27 13:25 UTC, geoffrey4444 commented on src/Domain/Creators/TimeDependence/SphericalCompression.cpp
> +      function_of_time_name_(std::move(function_of_time_name)) {}
I just made this a regular ERROR, because there's no option context available in the constructor

2021-06-27 22:43 UTC, geoffrey4444 commented
Thanks very much for the reviews, @fmahebert @nilsdeppe! My apologies for taking so long to respond.

Because it's been a while, I didn't squash directly. The fixups are ready for a look when you get a chance

2021-06-28 15:31 UTC, nilsdeppe reviewed
I'm happy for you to squash, including the extra comments once @fmahebert has had a chance to look

2021-06-28 15:31 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependence/SphericalCompression.cpp
> +    ERROR(
you can just add the `OptionsContext` as a constructor argument. In the header `const OptionContext& context = {}` and then just `const OptionContext& context` in the cpp

2021-06-28 15:31 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependence/SphericalCompression.hpp
> +  /// \brief Initial velocity for the function of time for the size map
you updated the help string, but it looks like you forgot to update the doxygen comment

2021-06-28 15:31 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependence/SphericalCompression.hpp
> +  /// \brief Initial acceleration for the function of time for the size map
you updated the help string, but it looks like you forgot to update the doxygen comment

2021-06-28 15:38 UTC, fmahebert commented
No further comments, you can squash

2021-06-30 20:42 UTC, nilsdeppe approved these changes

2021-06-30 21:43 UTC, fmahebert approved these changes

2021-06-30 23:58 UTC, merged