Add ObserveNorms event to observe norms of any tensor in the DataBox
sxs-collaboration/spectre pull request #3244
Opened 2021-06-05 01:39 UTC by nilsdeppe

## Proposed changes

Currently supports Max, Min, and L2Norm. More can be easily added as we need them.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-05 01:40 UTC, nilsdeppe commented
@geoffrey4444 here's the PR for observing norms of tensors in the DataBox

2021-06-06 23:05 UTC, geoffrey4444 requested changes
Thanks so much for doing this! Just some questions and minor suggestions

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/EventsAndTriggers/Event.hpp
> +  explicit Event(CkMigrateMessage* msg) noexcept : PUP::able(msg) {}
(not a change request) could you please explain what this line does, so I understand?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> + * for the L2 norm we have (for a vector)
`(for a 3D vector)` ? What would happen if for some reason I was trying to use this in 2D and had 2D vectors? Perhaps clarify in the docs if this works for 1D or 2D, or if it doesn't, or if it just hasn't been tested yet?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +    static constexpr Options::String help = {"Blah"};
Could you please make this help string more helpful and less blah?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +      static constexpr Options::String help = {"The of the tensor to observe."};
missing `name` in help string

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +          "How to handle components. Must be Individual or Sum."};
`How to handle tensor components`?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +    ObserveTensor(std::string in_tensor, std::string in_norm_type,
why the `in_` prefixes on the inputs to this function?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +    std::string tensor{};
Why are these private member variables not named with names ending in underscores?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +      std::vector<double> result(t0.size());
Any reason to avoid {} initialization here (and elsewhere in this file)?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +                                   const double& t1) const noexcept {
double is trivially copyable, so why const ref?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +               std::vector<ObserveTensor> observe_tensors) noexcept;
is `observe_tensors` trivially copyable? If not, why not pass by const ref?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +  bool needs_evolved_variables() const noexcept override { return true; }
(not a change request) Will this prevent this observer from working with elliptic solves? If so, or if you don't know that's fine, but maybe note that somewhere that this is only meant for evolutions?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +  size_t number_of_points = 0;
Why not signaling nan?

2021-06-06 23:05 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> + */
Pointing the observer to the example yaml in the test as a snippet would be helpful to clarify how to use this observer

2021-06-07 18:41 UTC, nilsdeppe commented on src/ParallelAlgorithms/EventsAndTriggers/Event.hpp
> +  explicit Event(CkMigrateMessage* msg) noexcept : PUP::able(msg) {}
Charm++ uses it for something (nothing?) during restarts. We don't really understand what it's for, but we need it for Charm++ compatibility

2021-06-07 18:46 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +  bool needs_evolved_variables() const noexcept override { return true; }
I have no idea how this option works with the elliptic code. I assume it'll work with the elliptic code since `ObserveFields` also specifies this

2021-06-07 18:47 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +  size_t number_of_points = 0;
This is a `size_t` not a float, so no signaling NaN

2021-06-07 18:49 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +    std::string tensor{};
because they are public member variables. Only private members variables end with `_`

2021-06-07 18:50 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +    ObserveTensor(std::string in_tensor, std::string in_norm_type,
because otherwise there's shadowing in the constructor between the argument names and member variable names

2021-06-07 18:52 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +      std::vector<double> result(t0.size());
`std::vector<double>`'s `{}` construction uses an initializer list. That is, `std::vector<double> a{5}` is a 1-element vector with the value `5` while `std::vector<double> a(5)` is a 5-element vector. This is type-dependent, which makes matters even more confusing

2021-06-07 19:26 UTC, nilsdeppe commented
I've pushed a fixup. Thanks for the review :)

2021-06-07 19:34 UTC, wthrowe commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +  bool needs_evolved_variables() const noexcept override { return true; }
This function is only called by the dense-triggers code, so it should be fine.  The non-dense triggers (which are all that appear in elliptic executables) always have the variables available, so they don't check this function.

2021-06-08 12:44 UTC, geoffrey4444 commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +  size_t number_of_points = 0;
O yeah, duh :)

2021-06-08 12:46 UTC, geoffrey4444 approved these changes, later dismissed
Please squash. I don't need to see this again to approve

2021-06-10 22:20 UTC, kidder requested changes
you can squash the changes

2021-06-10 22:20 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> + * L_2(v^i)=\sqrt{\frac{1}{N}\sum_{i=0}^{N} \left[(v^x_i)^2 + (v^y_i)^2
I'd suggest changing `v^i` to `v^k` on the LHS to avoid confusion with the summation subscript `i`

2021-06-10 22:20 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> + */
FYI, you can put snippets in yaml files, see e.g. `docs/Tutorials/Visualization.md:\snippet PlaneWave1DObserveExample.yaml observe_event_trigger` if you want to avoid the quotes and newlines showing up...

2021-06-10 22:20 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +                "Components must Individual or Sum, not " << components);
must be

2021-06-10 22:20 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +        "The tensor to observe and how to do the reduction."};
List specifying each tensor to observe and how it is reduced

2021-06-10 22:20 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +        auto& values_and_names = norm_values_and_names[tensor_norm_types_[i]];
structured binding?

2021-06-10 22:20 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
> +#include "Utilities/TypeTraits/IsA.hpp"
unused?

2021-06-11 16:07 UTC, nilsdeppe commented
I've rebased and squashed in changes. I didn't add `ObserveNorms` to an input file but did switch to raw string literal

2021-06-11 16:24 UTC, kidder approved these changes

2021-06-11 17:20 UTC, geoffrey4444 approved these changes

2021-06-12 03:51 UTC, merged