Add Minkowski
sxs-collaboration/spectre pull request #325
Opened 2017-11-02 20:46 UTC by osheamonn

2017-11-02 21:58 UTC, kidder requested changes

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> +namespace EinsteinSolutions {
don't do what Larry does, move the definitions out of the header file

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> + * \details Flat space has lapse \f$N(x,t)= 1 \f$, shift \f$N^i(x,t) = 0
check the doxygen (math broken across lines)

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> + * \ingroup EinsteinSolutions
did you define this?

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> + * \details Flat space has lapse \f$N(x,t)= 1 \f$, shift \f$N^i(x,t) = 0
Flat space -> The solution has

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> +  Scalar<T> lapse(const tnsr::I<T, Dim>& x, double /*t*/) const noexcept;
try /*t*/ -> t

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> +  void pup(PUP::er& /*p*/){};  // NOLINT
noexcept and no ;

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> +  for (size_t i = 0.; i < Dim; ++i) {
0;

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> +    lower_metric.get(i, i) = make_with_value<T>(x, 1.);
don't need make_with_value

2017-11-02 21:58 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> +    upper_metric.get(i, i) = make_with_value<T>(x, 1.);
ditto

2017-11-02 21:58 UTC, kidder commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Test_Minkowski.cpp
> +#include <limits>
remove

2017-11-02 21:58 UTC, kidder commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Test_Minkowski.cpp
> +
PUP RIP (just call serialize_and_deserialize)

2017-11-04 21:33 UTC, nilsdeppe commented
Once #338 is merged all the member functions can be moved to a cpp file and have explicit instantiations generated similar to the way ScalarWave::Solutions::PlaneWave is done in #338

2017-11-10 21:10 UTC, kidder submitted a review, later dismissed
squash

2017-11-13 19:52 UTC, nilsdeppe requested changes

2017-11-13 19:52 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * \defgroup EinsteinSolutions Einstein Solutions
Please change the group name to `EinsteinSolutionsGroup` to avoid collision with namespace name.

2017-11-14 03:01 UTC, nilsdeppe commented
Uh oh

2017-11-14 17:58 UTC, nilsdeppe approved these changes

2017-11-14 19:41 UTC, kidder approved these changes

2017-11-14 19:41 UTC, merged