Fix RicciScalarScalar Argument Tag
sxs-collaboration/spectre pull request #3250
Opened 2021-06-06 19:31 UTC by MarloMo

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-06 19:53 UTC, geoffrey4444 approved these changes, later dismissed

2021-06-07 02:06 UTC, wthrowe approved these changes, later dismissed

2021-06-09 02:10 UTC, kidder requested changes

2021-06-09 02:10 UTC, kidder commented on tests/Unit/ApparentHorizons/Test_Tags.cpp
> +      "ExtrinsicCurvature");
run `TestHelpers::db::test_compute_tag` on the new compute taags

2021-06-10 16:37 UTC, wthrowe commented
Fixes look good.  The two commits should be squashed before this is merged.

2021-06-10 17:23 UTC, kidder reviewed
yes, please squash

2021-06-10 20:14 UTC, wthrowe approved these changes

2021-06-10 20:16 UTC, kidder approved these changes

2021-06-11 16:47 UTC, merged