Add TciOnFdGrid to ValenciaDivClean
sxs-collaboration/spectre pull request #3257
Opened 2021-06-08 00:27 UTC by nilsdeppe

## Proposed changes

The TCI that checks if the DG solution would be okay again

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-08 20:51 UTC, kidder requested changes

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> +                    bool vars_needed_fixing, const Mesh<3> dg_mesh,
take Mesh by reference?

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> +#include "DataStructures/VariablesTag.hpp"
unused

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> +#include "Evolution/DgSubcell/Tags/OnSubcells.hpp"
unused

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> +#include "Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.hpp"
unused

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> +#include "PointwiseFunctions/GeneralRelativity/TagsDeclarations.hpp"
unused

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> +#include "PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp"
unused

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> +#include "PointwiseFunctions/Hydro/Tags.hpp"
unused

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> +namespace gsl {
unused

2021-06-08 20:51 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp
> +#include <cstddef>
unused

2021-06-08 20:51 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnFdGrid.cpp
> +#include "Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp"
System.hpp -> Tags.hpp

2021-06-08 20:51 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnFdGrid.cpp
> +#include "Evolution/DgSubcell/Mesh.hpp"
unused

2021-06-08 20:51 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnFdGrid.cpp
> +                        grmhd::ValenciaDivClean::Tags::VariablesNeededFixing,
include for this tag

2021-06-09 17:28 UTC, nilsdeppe reviewed
I've rebased on develop and pushed a fixup. Thanks for the review :)

2021-06-09 17:28 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp
> +#include <cstddef>
Mesh has a size_t as a template parameter :shrug:

2021-06-09 17:51 UTC, kidder commented
you can squash

2021-06-09 17:56 UTC, nilsdeppe commented
okay, squashed

2021-06-09 18:13 UTC, kidder approved these changes

2021-06-10 16:47 UTC, fmahebert approved these changes

2021-06-10 16:49 UTC, merged