Add HLL boundary correction to GRMHD
sxs-collaboration/spectre pull request #3262
Opened 2021-06-09 00:17 UTC by nilsdeppe

## Proposed changes

Add the HLL boundary correction for the GRMHD system

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-10 22:57 UTC, moxcodes commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryCorrections/Hll.hpp
> + * grmhd::ValenciaDivClean::characteristic_speeds(). Since the fluid is
[nitpick] backticks for the function

2021-06-10 22:57 UTC, moxcodes commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryCorrections/Hll.hpp
> + *   \lambda_{\pm}&=\pm\alpha-\beta^i n_i,
In this equation the `\pm` is in the subscript, where in the previous descriptions they're in the superscript. I think they mean the same thing, so maybe just make this one a superscript. If it denotes something different, then the prose should clarify.

2021-06-10 22:57 UTC, moxcodes commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryCorrections/Hll.cpp
> +             max(abs(get(*packaged_largest_outgoing_char_speed))));
one of these was probably supposed to be ingoing, I think.

2021-06-11 16:31 UTC, nilsdeppe commented
Rebased and squashed in changes since they're relatively small. Thanks for the review :)

2021-06-11 16:50 UTC, moxcodes approved these changes, later dismissed

2021-06-17 19:26 UTC, kidder requested changes
you can squash

2021-06-17 19:26 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryCorrections/Hll.hpp
> + * \brief A Rusanov/local Lax-Friedrichs Riemann solver
RIP

2021-06-17 19:26 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryCorrections/Hll.cpp
> +#include "Utilities/GenerateInstantiations.hpp"
unused

2021-06-17 19:26 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryCorrections/Test_Hll.cpp
> +#include "PointwiseFunctions/Hydro/EquationsOfState/IdealFluid.hpp"
unused

2021-06-17 19:26 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryCorrections/Test_Hll.cpp
> +#include "Utilities/TMPL.hpp"
unused

2021-06-17 20:18 UTC, kidder requested changes

2021-06-17 20:18 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryCorrections/BoundaryCorrection.hpp
>  namespace grmhd::ValenciaDivClean::BoundaryCorrections {
oh and this is doxygen version dependent on whether `BoundaryCorrections` is documented

2021-06-17 20:39 UTC, nilsdeppe commented
Rebased, squashed, and added a commit moving the namespace comment. Thanks for the reviews :)

2021-06-17 21:19 UTC, kidder approved these changes

2021-06-17 22:02 UTC, moxcodes approved these changes

2021-06-18 18:39 UTC, merged