Add GeneralizedHarmonic Outflow BC
sxs-collaboration/spectre pull request #3288
Opened 2021-06-16 01:22 UTC by moxcodes

## Proposed changes

Adds the outflow boundary correction, which simply checks that all characteristic speeds are directed out of the domain, to the generalized harmonic system.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

2021-06-16 01:22 UTC, moxcodes commented on src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Outflow.hpp
> +  static std::optional<std::string> dg_outflow(
Move to cpp

2021-06-16 17:39 UTC, nilsdeppe requested changes
you can squash immediately

2021-06-16 17:39 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Outflow.hpp
> +class Outflow final : public BoundaryCondition<Dim> {
some Doxygen would be nice so it shows up in the documentation :)

2021-06-16 17:39 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Outflow.hpp
> +#include "DataStructures/Tensor/EagerMath/DeterminantAndInverse.hpp"
you don't need several of the includes here (might be worth double checking in the GRMHD PR now that things got moved to the cpp)

2021-06-16 17:39 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Outflow.cpp
> +#include "Utilities/GenerateInstantiations.hpp"
you definitely need a lot more includes here now

2021-06-18 21:18 UTC, moxcodes commented
fixes squashed in.
Cheers!

2021-06-21 15:14 UTC, nilsdeppe approved these changes

2021-06-21 17:13 UTC, geoffrey4444 approved these changes

2021-06-21 17:13 UTC, geoffrey4444 commented
Code looks good, and I have also successfully used this BC in some BBH evolutions

2021-06-21 17:14 UTC, merged