Add FixConservativesAndComputePrims mutator to ValenciaDivClean
sxs-collaboration/spectre pull request #3292
Opened 2021-06-16 15:59 UTC by nilsdeppe

## Proposed changes

Add a mutator that fixes the conserved variables, records whether or not they needed fixing in `Tags::VariablesNeededFixing`, and then computes the primitives on the subcells.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-21 20:47 UTC, kidder requested changes
you can squash

2021-06-21 20:47 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/FixConservativesAndComputePrims.hpp
> + * Sets `ValenciaDivClean::Tags::VariablesNeededFixing` to the `true` if the
remove the first `the`

2021-06-21 21:32 UTC, nilsdeppe commented
I've rebased and squashed in the dox fix. Thanks for the review :)

2021-06-21 21:39 UTC, kidder submitted a review, later dismissed

2021-06-23 16:04 UTC, fmahebert approved these changes, later dismissed

2021-06-23 17:20 UTC, nilsdeppe commented
Rebased on develop to resolve conflicts

2021-06-23 19:38 UTC, fmahebert approved these changes, later dismissed

2021-06-24 17:57 UTC, nilsdeppe commented
Rebased on develop again to get latest CI fixes

2021-06-24 19:08 UTC, fmahebert approved these changes

2021-06-24 19:32 UTC, kidder approved these changes

2021-06-24 21:38 UTC, merged