Add compute fluxes helpers to GRMHD for subcell
sxs-collaboration/spectre pull request #3293
Opened 2021-06-16 16:00 UTC by nilsdeppe

## Proposed changes

The subcell code needs to call the `ComputeFluxes::apply` a few times, and manually doing all the tag retrieval is rather tedious. This short forwarding function is quite useful.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-21 20:55 UTC, kidder requested changes
you can squash

2021-06-21 20:55 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/ComputeFluxes.hpp
> + * \brief Helper function that call `ComputeFluxes` by retrieving the return and
call -> calls

2021-06-21 20:55 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_ComputeFluxes.cpp
> +      make_not_null(&gen), make_not_null(&dist), num_pts);
`#include "Utilities/Gsl.hpp"`

2021-06-21 21:36 UTC, nilsdeppe commented
I've rebased this and squashed in the changes. Thanks for the review :)

2021-06-21 21:37 UTC, kidder approved these changes, later dismissed

2021-06-23 16:18 UTC, fmahebert approved these changes, later dismissed

2021-06-23 17:22 UTC, nilsdeppe commented
Rebased on #3292 with the hope that when that gets merged this won't need another rebase

2021-06-23 19:05 UTC, kidder approved these changes, later dismissed

2021-06-23 19:37 UTC, fmahebert submitted a review, later dismissed

2021-06-24 17:58 UTC, nilsdeppe commented
Rebased on develop to get latest CI fixes

2021-06-24 19:20 UTC, fmahebert approved these changes, later dismissed

2021-06-24 19:31 UTC, kidder submitted a review, later dismissed

2021-06-24 21:40 UTC, nilsdeppe commented
GitHub for some reason decided there were conflicts even though I could rebase without any conflicts... So I rebased again. Sorry!

2021-06-24 21:45 UTC, kidder approved these changes

2021-06-24 22:58 UTC, fmahebert approved these changes

2021-06-25 15:33 UTC, merged