Add FixedSpeedCubic to BinaryCompactObject
sxs-collaboration/spectre pull request #3307
Opened 2021-06-21 17:39 UTC by geoffrey4444

## Proposed changes

Hard-codes one of the FixedSpeedCubic FunctionOfTimes in the BinaryCompactObject domain to a FixedSpeedCubic FunctionOfTime, instead of hard-coding two FunctionOfTimes for CubicScale. This is typically used to move the outer boundary radially inward at a small, constant velocity, to avoid buildup of constraint violation on the outer boundary.

### Upgrade instructions

When time dependence is enabled in the BinaryCompactObject domain, previously, the options for the ExpansionFactor included options to specify the two FunctionOfTimes used by the CubicScale map, e.g.

~~~
ExpansionMap:
  OuterBoundary: 25.0
  InitialExpansion: [1.0, 1.0]
  InitialExpansionVelocity: [-0.1, -0.01]
  FunctionOfTimeNames: ['ExpansionFactor', 'ExpansionFactorOuterBdry']
~~~

After this PR, instead specify one FunctionOfTime. The second (which is important only near the outer boundary) is now a hard-coded analytic function of time that causes the outer boundary to move radially inward at a constant speed, e.g.

~~~
ExpansionMap:
  OuterBoundary: 25.0
  InitialExpansion: 1.0
  InitialExpansionVelocity: -0.1
  FunctionOfTimeName: 'ExpansionFactor'
  AsymptoticVelocityOuterBoundary: -1.0e-6
  DecayTimescaleOuterBoundaryVelocity: 50.0
~~~

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-07-16 21:01 UTC, wthrowe requested changes

2021-07-16 21:01 UTC, wthrowe commented on src/Domain/Creators/BinaryCompactObject.cpp
> +          decay_timescale_outer_boundary_velocity),
Formatting.

2021-07-24 16:12 UTC, kidder requested changes
you can squash when addressing the comments

2021-07-24 16:12 UTC, kidder commented on src/Domain/Creators/BinaryCompactObject.hpp
>    /// \brief The velocity of the expansion factors.
factors -> factor

2021-07-24 16:12 UTC, kidder commented on src/Domain/Creators/BinaryCompactObject.hpp
>    /// \brief The initial values of the expansion factors.
initial value of the expansion factor

2021-07-24 16:12 UTC, kidder commented on src/Domain/Creators/BinaryCompactObject.hpp
> +  /// \brief The radial velocity of the outer boundary.
radial -> asymptotic radial

2021-07-24 16:12 UTC, kidder commented on src/Domain/Creators/BinaryCompactObject.hpp
>    /// If the two names are same then a linear radial scaling is used instead of
update the comment

2021-08-04 00:11 UTC, geoffrey4444 commented
My apologies for taking so long to respond...thank you very much for the reviews, @kidder @wthrowe ! I just pushed a fix, squashing immediately as @kidder suggested

2021-08-04 19:09 UTC, wthrowe approved these changes

2021-08-07 05:09 UTC, kidder approved these changes

2021-08-07 05:10 UTC, merged