UniformCylindricalEndcap
sxs-collaboration/spectre pull request #3325
Opened 2021-06-27 21:30 UTC by markscheel

## Proposed changes

Adds a new `CoordinateMap` that has exactly the same domain and range as `CylindricalEndcap`: it maps a unit right cylinder to the volume contained between the region near the pole of one spherical shell and the region near the pole of another spherical shell.  But:
 - For `UniformCylindricalEndcap`, points uniform in cylindrical radius on the right cylinder are mapped to points uniform in polar angle on the spherical shell, for **both** the spherical shells; for `CylindricalEndcap` this is true only for one of the spherical shells.
 - As a result, one can map an arbitrary number of nested spherical shells using `UniformCylindricalEndcap`; with `CylindricalEndcap` only 3 shells can be nested, and only for the case where the middle shell of the 3 nested shells is the special one with a uniform mapping from cylindrical radius to polar angle.
 - The map implemented by `UniformCylindricalEndcap` is simpler than that of `CylindricalEndcap` (but the inverse map is more complicated in `UniformCylindricalEndcap`).
 - Like `CylindricalEndcap`, `UniformCylindricalEndcap` can be part of a cylindrical BBH domain; but the `UniformCylindricalEndcap` version will not have exactly the same coordinates as the map in SpEC.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-27 21:32 UTC, markscheel commented
There will be some Clang-tidy failures, but as far as I can tell these are due to the internals of boost's TOMS748 root finding function; I still don't think anyone has figured out how to suppress such errors.

2021-12-16 01:01 UTC, nilsdeppe requested changes
Overall LGTM, some small suggestions. You'll need to rebase and remove ` noexcept` (note the space before)

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +    double rhobar, const std::array<double, 3>& center_one,
more `const ` on te `double`s?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +    const std::array<double, 3>& center_two, double radius_one,
more const on double?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +        ASSERT(not equal_within_roundoff(radius_one, 0.0),
add `ASSERT(radius_one > 0.0`?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +        ASSERT(not equal_within_roundoff(radius_two, 0.0),
add `ASSERT(radius_two > 0.0`?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +               "Plane one must intersect sphere, and at more than one point");
Do you think it would be helpful to expand this `ASSERT` to hint as to how to fix? (Same question for a few lines down)

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +  const auto function_to_zero = [this, &target_coords](double rhobar) noexcept {
`const double rhobar` as argument to lambda?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +      [this, &target_coords](double rhobar) noexcept {
`const double rhobar`?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +        return std::pair<double, double>(func_to_zero,
with C++17 I don't think you need `<double, double>` anymore

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +  double rhobar_min =
`const`?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +  double rhobar_max =
const?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +  if (rhobar_min < 1.e-6 and this_is_small_if_rhobar_is_near_zero() < 1.e-14) {
add comment why `1.e-6` and `1.e-14` or point to dox?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +        // Should we print out warning here, or do we assume that failure
have you decided what the right thing to do here is?

2021-12-16 01:01 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +    const double abs_tol = 1.e-15;
`constexpr`?

2022-01-07 22:07 UTC, markscheel commented
Rebased and addressed Nils's comments.

2022-01-08 00:49 UTC, nilsdeppe reviewed
LGTM! Please go ahead and squash!

2022-01-18 19:56 UTC, nilsdeppe commented
The CylindricalCompact... test timed out. Do you want to increase the timeout in this PR or a separate one?

2022-01-18 19:57 UTC, nilsdeppe approved these changes

2022-01-27 05:20 UTC, merged