Add local time-stepping for CCE
sxs-collaboration/spectre pull request #3326
Opened 2021-06-28 08:09 UTC by moxcodes

## Proposed changes

Performs some restructuring of the storage of time-stepper related tags -- moving several from the global cache to the DataBox, and enables the use of step choosers for the CCE system.
I anticipate that most of the time-related tags have sufficiently small memory footprints that it doesn't make much of a difference that they are in the DataBox, but I'm happy to consider alternative methods of approaching the structuring of the systems -- my main design constraint was that CCE evolution and DG element array should be able to simultaneously access the time-stepping architecture with their own respective time steppers and step choosers.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Dependencies

- [ ] PR #3304

2021-06-28 21:03 UTC, wthrowe requested changes
No complaints from me about moving the time steppers and stuff.

2021-06-28 21:03 UTC, wthrowe commented on tests/Unit/Time/Actions/Test_ChangeStepSize.cpp
> +namespace detail {
You don't need to use `detail` namespaces in tests.  Anonymous should be fine.

2021-06-28 21:07 UTC, moxcodes commented on tests/Unit/Time/Actions/Test_ChangeStepSize.cpp
> +namespace detail {
When it was an in an anonymous namespace, I ended up with surprising linker complaints about undefined entities with internal linkage. If that doesn't sound familiar, I'll rerun to get the exact linker error.

2021-06-28 21:38 UTC, wthrowe commented on tests/Unit/Time/Actions/Test_ChangeStepSize.cpp
> +namespace detail {
That's weird.  I think it should work.

If you do end up needing a named namespace, use something unique like `Test_ChangeStepSize_detail`.

2021-07-01 18:27 UTC, wthrowe commented
Squash and rebase.

2021-07-01 18:33 UTC, moxcodes commented
Squashed and rebased. I didn't see the linker error when running again -- I must have been doing something else wrong somewhere.
Cheers!

2021-07-01 18:36 UTC, wthrowe approved these changes, later dismissed

2021-07-02 00:56 UTC, nilsdeppe approved these changes, later dismissed
LGTM! One very optional idea. If you like it and feel up to it, please implement, otherwise we can merge this as-is :)

2021-07-02 00:56 UTC, nilsdeppe commented on src/Time/Actions/ChangeStepSize.hpp
> +    using tag = typename decltype(tag_v)::type;
what do you think of writing this as:
```cpp
if (not can_change_step_size) {
  return;
}
using tag = typename decltype(tag_v)::type;
const auto& history = db::get<tag>(*box);
can_change_step_size = time_stepper.can_change_step_size(next_time_id, history);
```
? I personally find this pattern easier to understand, but completely optional :)

2021-07-02 00:56 UTC, nilsdeppe commented on src/Evolution/DiscontinuousGalerkin/Actions/ComputeTimeDerivative.hpp
>    using inbox_tags =
If you end up changing anything else there's a type in the middle of the second paragraph: "the a given collection" -> "a given collection"

2021-07-06 18:36 UTC, moxcodes commented
Squashed in the last couple of suggestions, fixed a global cache tag that needed to be removed following a rebase to get CI to pass.
Cheers!

2021-07-06 20:10 UTC, wthrowe approved these changes

2021-07-07 15:58 UTC, nilsdeppe approved these changes

2021-07-07 15:58 UTC, merged