Add GRMHD prims after rollback mutator
sxs-collaboration/spectre pull request #3328
Opened 2021-06-28 23:47 UTC by nilsdeppe

## Proposed changes

I also added a few `ASSERT`s that were useful when debugging an extremely bizarre test failure.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-06-29 19:38 UTC, kidder requested changes
you can squash

2021-06-29 19:38 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/PrimsAfterRollback.hpp
> +#include "Evolution/DgSubcell/ActiveGrid.hpp"
unused

2021-06-29 19:38 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/PrimsAfterRollback.hpp
> +#include "PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp"
forward declare?

2021-06-29 19:38 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/PrimsAfterRollback.cpp
> +    const Scalar<DataVector> fd_pressure =
isn't this the dg pressure?

2021-06-29 19:38 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/PrimsAfterRollback.cpp
> +#include <algorithm>
unused?

2021-06-29 19:38 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_PrimsAfterRollback.cpp
> +  // Compute the conservatives on the DG grid by first computing the primitives
aren't the following computations done on the subcell grid?

2021-07-02 18:44 UTC, fmahebert reviewed
I have no additional comments

2021-07-07 18:02 UTC, nilsdeppe commented
I've rebased and squashed in the changes. Thanks for the reviews! :)

2021-07-07 18:10 UTC, fmahebert approved these changes

2021-07-07 18:24 UTC, kidder approved these changes

2021-07-09 00:15 UTC, merged