Add GRMHD FD time derivative computation
sxs-collaboration/spectre pull request #3331
Opened 2021-06-29 18:49 UTC by nilsdeppe

## Proposed changes

Add class with member function that performs the FD time derivative computation on a static Cartesian grid. 

**Note:** the following commits are new:
- Add missing include to subcell::Mesh tag file
- Move CartesianFluxDivergence to cpp file 
- Add subcell TimeDerivative struct for ValenciaDivClean

Depends on:
- [ ] #3319

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-07-12 18:04 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> +      // Note: assumes isotropic extents
Can you add an ASSERT that checks this? (Probably, as you've said elsewhere, this is assumed all over the code, but it's still nice I think to check where the assumption is used?)

2021-07-12 18:04 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> +          1.0 / (cell_centered_logical_coords.get(0)[1] -
Compile-time `get<0>(cell_centered_logical_coords)` here and on next line

2021-07-12 18:04 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> +          upper_outward_conormal.get(i) = -lower_outward_conormal.get(i);
For my understanding: couldn't the 15ish lines above be replaced with getting `NormalCovectorAndMagnitude` from the databox? is it because this normal is on the subcell grid points and the `NormalCovectorAndMagnitude` is on the DG grid points? if there's a fundamental reason for recomputing it here, can you note it in a comment?

2021-07-12 18:04 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> + * - Assumes the mesh is not moving (grid and inertial frame are the same)
Can you add a note like "Neither of these assumptions is checked in the code" so the users can infer it's their job to be careful?

2021-07-12 18:04 UTC, fmahebert commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
> +  // 4. normal dot fluxes (divide by -1 / sqrt(gamma^xx))
I can't identify what this 0->4 list is trying to tell me, or the 0->3 list below.

Can you reorganize so there's an "unattached" comment summarizing what the steps will be, and then put a simple reminder comment like "0. coords" at the particular code location where that step starts?

2021-07-12 18:04 UTC, fmahebert commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
> +    const domain::CoordinateMap<Frame::Logical, Frame::Inertial, Maps...> map,
Why not take this argument (`map`) by reference?

2021-07-12 18:04 UTC, fmahebert commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
> +  // const Affine affine_map{-1.0, 1.0, -0.5, 0.5};
Remove

2021-07-12 23:14 UTC, kidder requested changes

2021-07-12 23:14 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
> +  const auto dg_face_coords = coordinate_map(interface_logical_coordinates(
This appears to be unused...

2021-07-12 23:14 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
> +  // mortar data.
you do this, but don't use it as far as I can tell...

2021-07-12 23:14 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> +    // The copy of Mesh is intentional to avoid a GCC-7 internal compiler error.
😕

2021-07-13 18:51 UTC, nilsdeppe commented
I've rebased on develop and pushed a fixup. Thanks for the reviews :)

2021-07-13 18:53 UTC, kidder reviewed
LGTM

2021-07-13 19:15 UTC, fmahebert reviewed
LGTM

2021-07-13 19:54 UTC, nilsdeppe commented
I've squashed the fixup. Thanks for reviewing :)

2021-07-13 19:56 UTC, kidder approved these changes

2021-07-13 20:25 UTC, fmahebert approved these changes

2021-07-14 16:49 UTC, merged