Factor out common TensorIndex transformation logic into own file
sxs-collaboration/spectre pull request #3349
Opened 2021-07-09 02:54 UTC by macedo22

## Proposed changes

This PR factors out two functions (`compute_tensorindex_transformation` and `transform_multi_index`) that are commonly used in different parts of the tensor expression implementation to reorder tensor multi-indices according to another generic index (`TensorIndex`) order.

As a result of factoring the two functions out of `TensorAsExpression.hpp` and into `TensorIndexTransformation.hpp`, the test code for `Test_TensorAsExpression.cpp` (along with test implementation in the `TensorAsExpressionRank#TestHelpers.hpp` files) has been moved to `Test_TensorIndexTransformation.cpp` (along with test implementation in the `TensorIndexTransformationRank#TestHelpers.hpp` files).

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-07-16 18:54 UTC, nilsdeppe requested changes, later dismissed
LGTM, one missing include, please go ahead and squash+rebase

2021-07-16 18:54 UTC, nilsdeppe commented on src/DataStructures/Tensor/Expressions/TensorIndexTransformation.hpp
> +#include "Utilities/Gsl.hpp"
I think you need `Utilities/ForceInline.hpp` for `SPECTRE_ALWAYS_INLINE`

2021-07-16 22:30 UTC, macedo22 commented
@nilsdeppe Done!

2021-07-17 18:57 UTC, fmahebert approved these changes

2021-07-24 15:50 UTC, kidder approved these changes

2021-07-24 15:51 UTC, merged