Fix YlmSpherepack
sxs-collaboration/spectre pull request #335
Opened 2017-11-03 22:55 UTC by markscheel

## Proposed changes

Cleanups from Nils' code review.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [X ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."

### Further comments

2017-11-07 17:00 UTC, kidder requested changes

2017-11-07 17:00 UTC, kidder commented on src/ApparentHorizons/YlmSpherepack.cpp
> +  static constexpr double two_pi = 2.0 * M_PI;
why not two_pi_over_n_phi = 2.0 * M_PI/ n_phi_

2017-11-07 17:00 UTC, kidder commented on src/ApparentHorizons/YlmSpherepack.cpp
> +    gsl::not_null<std::vector<double>*> result,
const

2017-11-07 17:00 UTC, kidder commented on src/ApparentHorizons/YlmSpherepack.cpp
> +    gsl::not_null<std::vector<double>*>, const std::vector<double>&,
const

2017-11-07 17:00 UTC, kidder commented on src/ApparentHorizons/YlmSpherepack.hpp
> +      gsl::not_null<DataVector*> spectral_coefs, double c) const noexcept {
const

2017-11-07 17:00 UTC, kidder commented on tests/Unit/ApparentHorizons/YlmTestFunctions.cpp
> +  static const double inv_sqrt_4_pi = 1.0 / sqrt(4.0 * M_PI);
0.5 / sqrt(M_PI)

2017-11-07 17:00 UTC, kidder commented on src/ApparentHorizons/YlmSpherepack.hpp
> +        static_cast<const double*>(collocation_values) + physical_offset,
can't you get the pointer from a gsl::not_null?

2017-11-09 15:27 UTC, wthrowe commented on src/ApparentHorizons/YlmSpherepack.cpp
> +
Oops?

2017-11-09 15:27 UTC, wthrowe commented on src/ApparentHorizons/YlmSpherepack.hpp
> +    // on gsl::not_null<const double*>
Why not `collocation_values.get()`?

2017-11-09 15:27 UTC, wthrowe commented on src/ApparentHorizons/YlmSpherepackHelper.cpp
>    bool found = false;
This bool could be removed by changing the `break` below to a `return`.

2017-11-09 15:27 UTC, wthrowe commented on src/ApparentHorizons/YlmSpherepackHelper.cpp
>    bool found = false;
Ditto.

2017-11-10 21:36 UTC, kidder submitted a review, later dismissed
Nils still needs to look at these

2017-11-13 21:39 UTC, nilsdeppe requested changes
Just a few minor things, thanks for taking care of all this!

2017-11-13 21:39 UTC, nilsdeppe commented on src/ApparentHorizons/YlmSpherepack.cpp
> +  if (err != 0) {
Move error check to before free as is done elsewhere

2017-11-13 21:39 UTC, nilsdeppe commented on src/ApparentHorizons/YlmSpherepack.cpp
> +  if (err != 0) {
move in front of free like elsewhere

2017-11-13 21:39 UTC, nilsdeppe commented on src/ApparentHorizons/YlmSpherepack.cpp
> +    if (err != 0) {
we should annotate all of the error checks with `if (UNLIKELY(err != 0))` to tell the compiler that we do not expect this to evaluate true very frequently (in practice more than once per simulation per core). The macro is defined in `Utilities/Gsl.hpp`

2017-11-13 21:39 UTC, nilsdeppe commented on src/ApparentHorizons/YlmSpherepack.hpp
>    void gradient_from_coefs_all_offsets(
`SPECTRE_ALWAYS_INLINE`

2017-11-13 21:39 UTC, nilsdeppe commented on src/ApparentHorizons/YlmSpherepack.hpp
> +  static constexpr size_t physical_size(const size_t l_max,
mark both `SPECTRE_ALWAYS_INLINE`

2017-11-13 21:39 UTC, nilsdeppe commented on tests/Unit/ApparentHorizons/YlmTestFunctions.hpp
No blank line (this might be because of my extraneous space in my previous comment)

2017-11-14 03:04 UTC, nilsdeppe submitted a review, later dismissed
Let's squash these into one commit named something like "Address late comments from PR for YlmSpherepack"

2017-11-14 21:24 UTC, kidder approved these changes

2017-11-14 21:25 UTC, nilsdeppe approved these changes

2017-11-14 21:26 UTC, merged