Cancel redundant builds on CI
sxs-collaboration/spectre pull request #3351
Opened 2021-07-09 08:18 UTC by nilsleiffischer

## Proposed changes

Our CI is backed up quite a bit, so this PR enables a recently-added GitHub feature to cancel old runs when pushing to a PR or a branch: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
The feature is still in beta, but hasn't changed in a few months and it would be nice to speed up CI.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### Further comments

2021-07-12 20:56 UTC, wthrowe requested changes

2021-07-12 20:56 UTC, wthrowe commented on .github/workflows/Tests.yaml
> +# Cancel redundant builds
Expand on the meaning of "redundant".

2021-07-15 19:43 UTC, nikwit submitted a review, later dismissed

2021-07-19 14:53 UTC, nilsleiffischer commented on .github/workflows/Tests.yaml
> +# Cancel redundant builds
Reworded the comment.

2021-07-19 16:30 UTC, kidder approved these changes

2021-07-19 18:23 UTC, wthrowe approved these changes

2021-07-19 20:14 UTC, merged