Add 3d time dependent rotation matrix
sxs-collaboration/spectre pull request #3364
Opened 2021-07-15 23:01 UTC by knelli2

## Proposed changes
Adds a time dependent 3d rotation map that uses quaternions along with a helper function that actually calculates the rotation matrices.

As of right now the rotation matrix is recalculated every function call unless the time it's being evaluated at is equal (within round-off) to the previous time it was updated. This can be modified later to a better caching system.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Dependencies

- [ ] PR #3327 
- [ ] PR #3321 (included in above PR as well)

(This is a long PR because of the included dependent PRs. The three actual commits total about +680)

2021-07-16 00:49 UTC, wthrowe commented
I haven't gone through the code yet, but why have you decided to cache the result internally?

2021-07-16 02:19 UTC, knelli2 commented
I imagine the map will be called many times successively at the same `time` so caching it internally prevents things from being recomputed redundantly.

2021-07-16 02:40 UTC, wthrowe commented
I don't think there's a reason it would be repeatedly called.  The coordinates are calculated once and stored, same with the Jacobian.  The reverse map might be called a few times to do interpolation, but I'd guess the number of interpolation points per element is small.  Is there another expected use I'm forgetting?

2021-07-16 17:16 UTC, knelli2 commented
No you're probably right. I don't know much about how this is going to be used in the executable and action list so I made an assumption on how it would/should work.

2021-07-29 21:11 UTC, wthrowe requested changes

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.hpp
> +Matrix GetRotationMatrix(
`snake_case` function names.  (Everywhere in PR.)

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.hpp
> +    const std::unordered_map<
`#include <unordered_map>`

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.hpp
> +        std::string, std::unique_ptr<domain::FunctionsOfTime::FunctionOfTime>>&
`#include <string>`, `#include <memory>`

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.cpp
> +                     const DataVector q2, const double coef = 1.0) {
First argument by `gsl::not_null`, second and third by const reference.

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.cpp
> +    const std::string fot_name) noexcept {
`fot_name` by reference.

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.cpp
> +  const auto& fot_ptr = fot_list.at(fot_name).get();
You've got a reference to a pointer here.  You don't want the `.get()`.

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.cpp
> +Matrix GetRotationMatrixDeriv(
Same comments as the previous function.

2021-07-29 21:11 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_RotationMatrixHelpers.cpp
> +  INFO("Rotation about z") {
`INFO` inside the braces.

2021-07-29 21:11 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_RotationMatrixHelpers.cpp
> +    // rotation about z axis
z -> x

2021-07-29 21:11 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_RotationMatrixHelpers.cpp
> +  INFO("Rotation about x") {
These three checks are very similar.  Factor them out into a function/lambda that takes the differing input and expected values (`init_omega`, `rot_z`, and `rot_z_deriv`, I think).  Rename the last two of those to something with "expected" in the name.

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.hpp
> +    std::string fot_name) noexcept;
[optional] These would be a bit more general if they took a `const domain::FunctionsOfTime::FunctionOfTime&` instead of the map and key.

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/RotationMatrixHelpers.cpp
> +#include "Utilities/GenerateInstantiations.hpp"
Check these.

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/CMakeLists.txt
>    Rotation.cpp
'3' > '.' (again below)

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/Rotation3D.cpp
> +  Matrix rot_matrix_deriv =
const

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/Rotation3D.cpp
> +          dereference_wrapper(source_coords[0]), 0.0)};
I think you can `make_with_value` the whole `tnsr::Ij<...>` at once, which is probably easier to read and might be a bit more efficient.

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/Rotation3D.cpp
> +          dereference_wrapper(source_coords[0]), 0.0)};
Same comment about `make_with_value`.

2021-07-29 21:11 UTC, wthrowe commented on src/Domain/CoordinateMaps/TimeDependent/Rotation3D.cpp
> +#define DIM(data) BOOST_PP_TUPLE_ELEM(0, data)
Replace `DIM(data)` with 3 everywhere.  There's no way this class will ever work for a different value.

2021-07-29 21:11 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TimeDependent/CMakeLists.txt
>    Test_Rotation.cpp
Alphabet.

2021-07-29 21:11 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_Rotation3D.cpp
> +}  // namespace domain::FunctionsOfTime
You need actual includes for these, not forward declarations.  (And you already have one of them.)

Forward declarations in cpp files are rarely correct.

2021-07-29 21:11 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_Rotation3D.cpp
> +          2.0 / sqrt(3) * t,
t=0, so these are all just 0.

2021-07-29 21:11 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_Rotation3D.cpp
> +  CHECK_FALSE(rotation_map_deserialized != rotation_map_deserialized);
Construct one that isn't equal and compare that too.

2021-08-02 22:09 UTC, wthrowe reviewed
Squash

2021-09-01 18:14 UTC, knelli2 commented
Rebased on latest develop now that #3327 is merged.

2021-09-03 18:31 UTC, wthrowe approved these changes

2021-09-08 00:20 UTC, merged