Add Freezing boundary conditions for Gh
sxs-collaboration/spectre pull request #3376
Opened 2021-07-21 16:02 UTC by prayush

## Proposed changes

This adds freezing boundary conditions, where the characteristic projections of the RHS of evolution equations are set to 0 if the corresponding characteristic speed indicates an incoming mode.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-07-21 17:15 UTC, nilsleiffischer commented
@prayush how is this related to #3370? Would it be reasonable to add the feature as an input-file option to the existing class? Not making a suggestion yet, just asking to get an idea how things are related.

2021-07-21 17:41 UTC, prayush commented
> @prayush how is this related to #3370? Would it be reasonable to add the feature as an input-file option to the existing class? Not making a suggestion yet, just asking to get an idea how things are related.

@nilsleiffischer in #3370 we are freezing the single mode `Vplus` while applying constraint preserving and physical corrections to the other 3 characteristic fields. This is the behavior of SpEC (see the link in the discussion under "proposed changes" in #3370 ) when one asks it to apply "Constraint preserving" boundary conditions. As Vplus should always be an outgoing mode, currently spectre simply leaves that mode unaltered. But to be completely consistent with SpEC, we need #3370 . The only time Vplus can become incoming is either if the outer boundary is too close to the source or the domain itself is radially moving fast enough.

This PR, on the other hand, simply freezes all modes. This would be equivalent to the "Freezing" boundary condition in SpEC. It applies no correction terms whatsoever, and so I would prefer to keep it separate from "ConstraintPreservingBjorhus".

2021-07-21 20:46 UTC, nilsleiffischer commented
@prayush thanks for explaining!

2021-08-19 00:09 UTC, geoffrey4444 requested changes
I took a look and didn't see anything significant to suggest in terms of code. 

However, before approving, I'd like to see a demonstration that some GH system can actually evolve stably with this BC...in my attempts, it doesn't work, but almost immediately leads to FPEs from constraint growth. Maybe I did something wrong in my tests, though?

My reasoning is that if the BC does not work, then it should not be merged. I could be talked out of that, though

2021-08-19 00:09 UTC, geoffrey4444 commented on src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/Freezing.hpp
> +      // c.f. dg_interior_evolved_variables_tags
I don't understand these comments...please flesh them out

2022-05-23 23:46 UTC, geoffrey4444 commented
Closed because we now have constraint preserving BCs for GH that work even with moving meshes.

2022-05-23 23:46 UTC, closed without merging