Support skipping the preconditioner in elliptic solves
sxs-collaboration/spectre pull request #3379
Opened 2021-07-22 14:34 UTC by nilsleiffischer

## Proposed changes

Sometimes it's useful to skip the preconditioner of the parallel linear solver, e.g. to run with no overhead on small test cases or to compare preconditioned vs un-preconditioned solves. With this change, the preconditioner can be disabled by just setting the number of iterations in the input file to zero.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-07-23 01:02 UTC, kidder requested changes

2021-07-23 01:02 UTC, kidder commented on tests/Unit/ParallelAlgorithms/LinearSolver/Actions/Test_MakeIdentityIfSkipped.cpp
> +  CHECK(get_tag(CheckRunIfSkippedTag{}) == skipped);
add tests where `LinearSolver::Actions::make_identity_if_skipped` is given only one or all three template arguments

2021-07-23 12:23 UTC, nilsleiffischer commented
fixup posted, thanks @kidder !

2021-07-23 12:24 UTC, nilsleiffischer commented
@fmahebert could do the second review here?

2021-07-24 16:45 UTC, kidder reviewed
fixup LGTM

2021-07-24 23:32 UTC, kidder approved these changes

2021-07-27 19:13 UTC, fmahebert approved these changes

2021-07-27 21:28 UTC, merged