Generate instantiations
sxs-collaboration/spectre pull request #338
Opened 2017-11-04 21:26 UTC by nilsdeppe

## Proposed changes

Add a macro for generating many explicit instantiations from a Cartesian product of macro-tuples. This simplifies generation of explicit instantiations for function and class templates with many template parameters, or many values for each template parameter. Here by many I mean more than 2.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."

2017-11-04 21:51 UTC, kidder requested changes

2017-11-04 21:51 UTC, kidder commented on src/DataStructures/Index.cpp
> +#undef GET_DIM
is this supposed to be DIM ?

2017-11-04 21:51 UTC, kidder commented on src/Utilities/GenerateInstantiations.hpp
> + * class templates. Since the total number of explicit instantiation scales the
scales as the

2017-11-04 21:51 UTC, kidder commented on src/Utilities/GenerateInstantiations.hpp
> + * The first argument to the macro is a macro that takes two argument described
two arguments

2017-11-04 21:51 UTC, kidder commented on src/Utilities/GenerateInstantiations.hpp
> + * first argument to the `INSTANTIATION_MACRO` in a Boost.Preprocessor internal
this sentence should be by the macro that uses the `_` as I find it to be confusing here

2017-11-04 21:51 UTC, kidder commented on src/Utilities/GenerateInstantiations.hpp
> + * instantiations using `GENERATE_INSTANTIATIONS` way.
using the

2017-11-04 22:40 UTC, nilsdeppe commented
Updated!

2017-11-04 23:50 UTC, kidder requested changes

2017-11-04 23:50 UTC, kidder commented on src/Utilities/GenerateInstantiations.hpp
> + * described below. The remaining arguments are macro-tuples, e.g. `(1, 2, 3)`.
is described

2017-11-04 23:50 UTC, kidder commented on src/Utilities/GenerateInstantiations.hpp
> + * serves as example. A concrete example is generating explicit instantiations
serves as -> as an

2017-11-05 01:15 UTC, nilsdeppe commented
Okay, another update. Let me know if the documentation can be improved in any other way :)

2017-11-05 01:17 UTC, kidder submitted a review, later dismissed

2017-11-07 15:57 UTC, kidder requested changes
you have a doxygen warning to deal with

2017-11-07 18:45 UTC, kidder requested changes

2017-11-07 18:45 UTC, kidder commented on src/Executables/DebugPreprocessor/DebugPreprocessor.cpp
> +#define GET_DIM(data) BOOST_PP_TUPLE_ELEM(0, data)
// This is an example:  replace the code with what you want to debug

2017-11-07 18:45 UTC, kidder commented on src/Utilities/GenerateInstantiations.hpp
> + * class templates. Since the total number of explicit instantiation scales as
instantiations

2017-11-07 18:45 UTC, kidder commented on src/Utilities/GenerateInstantiations.hpp
> + *   ScalarWave::Solutions::PlaneWave<DIM(data)>::dpsi_dx(                   \
remove the rest

2017-11-07 23:16 UTC, kidder approved these changes

2017-11-08 03:22 UTC, merged