Add Krivodonova and Kuzmin executable to ScalarAdvection
sxs-collaboration/spectre pull request #3405
Opened 2021-08-02 17:21 UTC by yoonso0-0

## Proposed changes

Add [Krivodonova (1D)](https://www.sciencedirect.com/science/article/pii/S0021999107002136?via%3Dihub) and [Kuzmin (2D)](https://www.sciencedirect.com/science/article/pii/S0021999113003161) executables to the ScalarAdvection system.
- [ ] Dependent on #3386.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-08-22 04:12 UTC, nilsdeppe reviewed
The executable additions in this PR look good.

PR still depends on the analytic solutions PR

2021-08-23 20:01 UTC, yoonso0-0 commented
Thanks!

2021-08-26 19:30 UTC, nilsvu requested changes

2021-08-26 19:30 UTC, nilsvu commented on tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
> +# Check: parse;execute
Currently these two input file tests only check that the executables run without error. Since both have analytic solutions, you can make the test a lot stronger by changing the `execute` here to `execute_check_output`. Then, configure the test to output errors to the analytic solution (with `ObserveErrorNorms`) and to check the errors remain below a tolerance for the duration of the simulation. You can look at one of the other input files to get an idea how that works.

2021-08-26 21:46 UTC, yoonso0-0 commented on tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
> +# Check: parse;execute
@nilsleiffischer Thank you for letting me know. Due to the not-so-wonderful performance of the DG limiters currently used in advection system, error norm is not small even if the problem itself is mathematically very simple. If there is a sharp discontinuity in the initial data (such as Krivodonova and Kuzmin initial data here), the situation gets worse. I've just tested with varying options, and it seems that in order to achieve a level of absolute tolerance which seems admissible (maybe < 0.05) for running a separate test for it, one needs more than about 100 grid points for 1D and 100x100 grid points for 2D. This increases the timeout mildly for 1D (~1s) and greatly for 2D (~30s) -- I'm not sure of how much benefit we would get in that case.

2021-08-26 21:55 UTC, yoonso0-0 commented on tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
> +# Check: parse;execute
If this `execute_check_output` testing is intended to run analytic solutions and merely test if nothing went bad (to see if ErrorNorm is okay with previous numerical experiments) in a more handy way, say, incorporating the whole procedure of [ run an executable with an input file -> read it with python -> check ErrorNorms by hand ] into a single test, I think testing with high resolution and large timeout seems to be reasonable though.

2021-08-26 22:41 UTC, nilsvu commented on tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
> +# Check: parse;execute
- Have you tried running with a moving mesh? I just gave that a quick try and it seems to keep the error at least stable. This is what I added to the Krivodonova input file:
    ```yaml
    TimeDependence:
      UniformTranslation:
        InitialTime: 0
        InitialExpirationDeltaT: Auto
        Velocity: [1]
        FunctionOfTimeNames: ["Unused?"]
    ```
- I found curious that the error actually _increased_ when I increased the order / number of points in the elements. Do you have an idea why that is?
- If you find a configuration that runs with a timeout of ~20 seconds or so (better 1-5s) on CI (keep in mind that some CI runs can be a lot slower than your machine) and doesn't have an entirely garbage solution, then adding the `execute_check_output` would be quite valuable. As you say, it just runs the exec, reads the reduction file and checks the norm against your tolerance. This verifies that nothing obviously broke that makes the error diverge immediately or made it worse than before for some reason. I think the 0.05 you mentioned would be nice, but something like 0.1 or 0.2 would be fine as well. You can also decrease the number of time steps to speed up the test. Or enable the check only for the 1D solution.
- If any reasonable resolution is still too slow for CI, then so be it and we can merge this as-is.

2021-08-26 23:18 UTC, yoonso0-0 commented on tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
> +# Check: parse;execute
* I haven't tried it before, so I just did :) The solution itself seems much more stable, but one of the main purposes of writing up this advection system is checking limiter performances to see if they resolve moving discontinuities correctly -- which would not be very evident if we use moving mesh. I'm not clear of whether it would be good to use moving mesh only for this test; it will do make the code to pass tests, but will not be testing the practical cases we frequently use for its original purpose.
* I think the first possibility is that the refinement level / number of grid points before you increased them is out of convergence zone; if there are too few points, they fail to resolve the irregular shape of this peculiar initial data and would remain _relatively_ calm. As an extreme example, if we use 2 grid pts with refinement level 1, they are all hitting the spots with U=0, so we are just evolving zero to zero forever :b.
* The second possibility is that the error increases with the larger number of grid points inside each elements, because unphysical oscillations near discontinuities might grow bigger for using higher-order polynomials. (as if we are trying to Taylor-expand a step function) Still there will be an accuracy gain coming from the increased resolution for smooth parts, but I guess it's possible for a failure near a few steep discontinuities can overrun that. 
* Good. I'll try a few more trade-off games on local machine and look at how much it would take for CI runs.

2021-08-27 00:50 UTC, yoonso0-0 commented
Updated input files pushed. A quick look over test logs tells that it takes 1-2 seconds (upto 3s max) for checking outputs :)

2021-08-27 15:15 UTC, nilsvu approved these changes
Looks good 👍

2021-09-02 13:05 UTC, nilsleiffischer commented
@kidder @wthrowe @nilsdeppe could one of you sign off on this?

2021-09-02 14:37 UTC, nilsdeppe approved these changes

2021-09-02 14:37 UTC, merged