Document stable step sizes for different time steppers
sxs-collaboration/spectre pull request #3406
Opened 2021-08-02 20:22 UTC by nilsdeppe

## Proposed changes

When choosing step sizes manually I found it useful to be able to quickly look up what the stable step size for a particular stepper is, so this PR just adds the step size factor into the documentation. The Adams-Bashforth stepper already has a table.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-02 20:30 UTC, moxcodes approved these changes, later dismissed

2021-08-02 20:49 UTC, wthrowe requested changes

2021-08-02 20:49 UTC, wthrowe commented on src/Time/TimeSteppers/RungeKutta3.hpp
> +/// The CFL factor/stable step size is 1.00764201365733.
`1.25637266330916`

2021-08-02 23:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/RungeKutta3.hpp
> +/// The CFL factor/stable step size is 1.00764201365733.
:facepalm: thanks :) Fixed and squashed

2021-08-02 23:36 UTC, moxcodes approved these changes

2021-08-03 01:06 UTC, wthrowe approved these changes

2021-08-05 22:11 UTC, merged