GRMHD subcell TCI check positivity of TildeD and TildeTau
sxs-collaboration/spectre pull request #3410
Opened 2021-08-03 19:49 UTC by nilsdeppe

## Proposed changes

Add positivity of TildeD and TildeTau as a requirement to the three TCI cases. I found this necessary for high-resolution TOV evolutions. Specifically, the FD solver tried to switch back to DG but the reconstructed TildeD had negative values but did pass the RDMP and Persson TCIs. The min values of TildeD and TildeTau are controlled separately since TildeTau ~ TildeD^2, though this is EOS-dependent.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-03 20:26 UTC, kidder requested changes
you can squash

2021-08-03 20:26 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp
> + *   `min(tilde_tau)` are less than `tci_options.minimum_tilde_tau` then the we
are -> is

2021-08-03 20:26 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp
> + * initialized to the initial data) are less than
are -> is

2021-08-03 20:26 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp
> + * (tci_options.minimum_tilde_tau`), then the element is flagged as troubled.
missing tick before tci_options

2021-08-03 20:31 UTC, nilsdeppe commented
Rebased and squashed. Thanks for the quick review :)

2021-08-03 20:59 UTC, kidder approved these changes

2021-08-06 05:03 UTC, fmahebert approved these changes

2021-08-06 05:05 UTC, merged