Make Averager serializable and constructible from options.
sxs-collaboration/spectre pull request #3424
Opened 2021-08-10 16:36 UTC by osheamonn

## Proposed changes

Adds functionality to the averager that I found I needed for the control systems. 

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-10 17:24 UTC, knelli2 requested changes

2021-08-10 17:24 UTC, knelli2 commented on src/ControlSystem/Averager.cpp
> +         (avg1.tau_k_ == avg2.tau_k_);
Should you also check `raw_qs_`? I don't think there can be a case where all the timescales, weights, averaged values, etc. are the same and the `raw_qs_` are different, but I'm not 100% sure.

2021-08-10 17:24 UTC, knelli2 commented on tests/Unit/ControlSystem/Test_Averager.cpp
> +#include "Framework/TestHelpers.hpp"
Included `TestHelpers` twice.

2021-08-10 17:24 UTC, knelli2 commented on tests/Unit/ControlSystem/Test_Averager.cpp
> +  CHECK(serialize_and_deserialize(averager1) == averager1);
You should also check that two averagers are (not)equal after an update. Here you're just checking that the default values of most members are the same.

Maybe also add a few `CHECK_FALSE`s as well.

2021-08-10 17:24 UTC, knelli2 commented on src/ControlSystem/Averager.cpp
> +/// \endcond
Doxygen doesn't work in cpp files.

2021-08-10 17:24 UTC, knelli2 commented on src/ControlSystem/Averager.hpp
> +
Clang-tidy complaining about duplicates. Maybe because they are public?

2021-08-10 21:11 UTC, wthrowe requested changes

2021-08-10 21:11 UTC, wthrowe commented on src/ControlSystem/Averager.hpp
>  #include "DataStructures/DataVector.hpp"
Alphabetize.

2021-08-10 21:11 UTC, wthrowe commented on src/ControlSystem/Averager.hpp
> +
It's a bug.  Just NOLINT them.

2021-08-10 21:11 UTC, wthrowe commented on src/ControlSystem/Averager.hpp
> +                         const Averager<DDerivOrder>&);
This one doesn't need to be a friend.

2021-08-10 21:11 UTC, wthrowe commented on src/ControlSystem/Averager.hpp
> +  static constexpr Options::String help{"Averager"};
Should probably put something here.

2021-08-10 21:11 UTC, wthrowe commented on tests/Unit/ControlSystem/Test_Averager.cpp
> +                  "[ControlSystem][Unit]") {
Change the test cases in this file into functions and call them all from one test case.  We realized at some point that each test case has a significant overhead on some clusters.

2021-08-10 21:11 UTC, wthrowe commented on src/ControlSystem/Averager.hpp
> +#include <pup_stl.h>
Merge with above block of includes.

2021-08-10 21:11 UTC, wthrowe commented on src/ControlSystem/Averager.cpp
>  template class Averager<2>;
This isn't new, but do you know why this is instantiated only for 2?

2021-08-26 16:55 UTC, wthrowe submitted a review, later dismissed
I'm happy for a squash, but wait for @knelli2's approval.

2021-08-26 17:39 UTC, knelli2 submitted a review, later dismissed
LGTM :)

2021-08-27 17:43 UTC, knelli2 approved these changes

2021-08-27 20:17 UTC, wthrowe approved these changes

2021-08-27 20:17 UTC, merged