Make timescale tuner serializable and constructible from options.
sxs-collaboration/spectre pull request #3425
Opened 2021-08-10 16:42 UTC by osheamonn

## Proposed changes

To construct the timescale tuner from options, I changed the constructor to take a `std::vector<double>` rather than a DataVector. Since this will probably only be constructed from options it seemed like the right thing to do. 

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-10 21:02 UTC, knelli2 commented on src/ControlSystem/TimescaleTuner.cpp
>                                 const double max_timescale,
As long as it will only be created from options, then I think this is ok. If it will be constructed elsewhere, then maybe having both would be good?

2021-08-10 21:24 UTC, wthrowe requested changes
I don't see why we're using DataVectors here at all.  Not asking you to change that, though.

2021-08-10 21:24 UTC, wthrowe commented on src/ControlSystem/TimescaleTuner.hpp
> +}
Wrap in `\cond`.  Clang-tidy or something will also complain about the missing `// namespace PUP` at the end.

2021-08-10 21:24 UTC, wthrowe commented on src/ControlSystem/TimescaleTuner.hpp
> +  friend bool operator!=(const TimescaleTuner& lhs, const TimescaleTuner& rhs);
This one doesn't need to be a friend.

2021-08-10 21:24 UTC, wthrowe commented on tests/Unit/ControlSystem/Test_TimescaleTuner.cpp
> +                  "[ControlSystem][Unit]") {
Convert the (non-error) tests to functions and call them from one test case.  This significantly improves performance on some clusters.

2021-08-10 21:24 UTC, wthrowe commented on src/ControlSystem/TimescaleTuner.cpp
> +TimescaleTuner::TimescaleTuner(std::vector<double> initial_timescale,
`const std::vector<double>&`

2021-08-10 21:24 UTC, wthrowe commented on src/ControlSystem/TimescaleTuner.hpp
> +  static constexpr Options::String help{"TimescaleTuner"};
Write some help.

2021-08-26 11:26 UTC, osheamonn commented on src/ControlSystem/TimescaleTuner.cpp
>                                 const double max_timescale,
So the reason I opted to not have both is the constructor using initializer lists becomes ambiguous and has to be explicitly constructed with either a DataVector or a std::vector in all of the testing code.

2021-08-26 11:27 UTC, osheamonn commented
> I don't see why we're using DataVectors here at all. Not asking you to change that, though.

Just to explain, the control signals and timescales are stored as DataVectors since there is math done with them in Controller.cpp, this decision predates the existence of ModalVector which would probably be a more appropriate data type.

2021-08-26 16:51 UTC, wthrowe requested changes
You can squash, including the argument type change.

2021-08-26 16:51 UTC, wthrowe commented on src/ControlSystem/TimescaleTuner.cpp
> +TimescaleTuner::TimescaleTuner(std::vector<double> initial_timescale,
ping

2021-08-26 17:42 UTC, knelli2 commented on src/ControlSystem/TimescaleTuner.cpp
>                                 const double max_timescale,
Ah ok makes sense

2021-08-26 17:45 UTC, knelli2 commented
After you squash @wthrowe's changes, looks good.

2021-08-27 17:46 UTC, knelli2 approved these changes

2021-08-27 20:11 UTC, wthrowe approved these changes

2021-08-27 20:11 UTC, merged