Add load balancing notes to dev guide
sxs-collaboration/spectre pull request #3426
Opened 2021-08-10 18:48 UTC by moxcodes

## Proposed changes

Co-Authored with @fmahebert

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-08-10 22:40 UTC, nilsleiffischer submitted a review, later dismissed
Thanks for writing this up 👍

2021-08-12 14:14 UTC, nikwit commented
do you actually have to specify the event in the executable or is this done automatically?

2021-08-12 15:25 UTC, moxcodes commented
The load balancing has to be present in the `phase_changes` typelist in the metavariables, and the executable needs to satisfy a few interface requirements for supporting the phase changing infrastructure -- it's similar to, but separate from the events and triggers.
Currently, the set of alterations that need to be made for the phase changes isn't documented thoroughly in a centralized place, but the documentation for `PhaseChanges`, `PhaseControl` and `PhaseChangeAndTriggers` offers some of the technical details, and there are examples of existing executables that have the feature, e.g. ScalarWave.

2021-08-12 15:34 UTC, nilsleiffischer commented
@moxcodes Do you think you'll be able to do #3266, i.e. put the phase-control related metavariables in a struct and add some docs to it? If you find the time, that would be very valuable for future maintenance I think.

2021-08-12 15:50 UTC, moxcodes commented
Yes, I'll try to find the time to add that struct and documentation.

2021-08-21 18:21 UTC, kidder requested changes
Thank you for writing this up; you can squash the one typo

2021-08-21 18:21 UTC, kidder commented on docs/DevGuide/LoadBalancingNotes.md
> +  element during the start of the `Evolve` phase, but that attempt lead to a
lead -> led

2021-08-22 00:42 UTC, moxcodes commented
squashed in the typo fix.
Cheers!

2021-08-22 00:53 UTC, kidder approved these changes

2021-08-22 05:07 UTC, merged