Fix random roundoff cylindrical map errors
sxs-collaboration/spectre pull request #3430
Opened 2021-08-11 19:41 UTC by markscheel

## Proposed changes
Change allowed bounds in cylinder domains to fix occasional roundoff failures in tests.
Fixes #3380 

See detailed comments in commit messages.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-12 18:34 UTC, nilsleiffischer requested changes

2021-08-12 18:34 UTC, nilsleiffischer commented on src/Domain/CoordinateMaps/FocallyLiftedMapHelpers.hpp
> +    bool solve_for_root_minus_one = true) noexcept;
Could you add some docs for the added argument to the function-documentation?

2021-08-16 16:27 UTC, nilsleiffischer commented
LGTM, please squash

2021-08-16 20:09 UTC, markscheel commented
squashed

2021-08-16 21:40 UTC, nilsleiffischer commented
@kidder @wthrowe Would one of you take a brief look and merge this?

2021-08-16 22:46 UTC, wthrowe commented
I'll take it, but you should submit an approval @nilsleiffischer.

2021-08-16 22:48 UTC, nilsleiffischer approved these changes

2021-08-16 22:59 UTC, wthrowe approved these changes

2021-08-17 00:38 UTC, merged