Add action to randomize elliptic initial guess
sxs-collaboration/spectre pull request #3437
Opened 2021-08-14 21:02 UTC by nilsleiffischer

## Proposed changes

Add an action that adds random noise to the initial guess for elliptic solves. The random noise can be toggled and is configurable with input-file options. It is useful to test the convergence of the elliptic solver.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-21 18:08 UTC, kidder requested changes

2021-08-21 18:08 UTC, kidder commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +  static std::tuple<db::DataBox<DbTagsList>&&> apply(
`#include <tuple>`

2021-08-21 18:08 UTC, kidder commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +      return {std::move(box)};
cover this case in the test

2021-08-21 18:08 UTC, kidder commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +    std::seed_seq seeds{std::hash<ElementId<Dim>>{}(element_id),
why are you using this to seed the generator?

2021-08-21 18:08 UTC, kidder commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +              tmpl::list<::Tags::Variables<tmpl::list<ScalarFieldTag>>>>>>,
`#include "DataStructures/VariablesTag.hpp"`

2021-08-21 18:08 UTC, kidder commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +  const DataVector used_for_size{5};
`#include "DataStructures/DataVector.hpp"`

2021-08-21 18:08 UTC, kidder commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +  const ElementId<1> element_id{0, {{SegmentId{2, 1}}}};
`#include "Domain/Structure/SegmentId.hpp"`

2021-08-21 18:08 UTC, kidder commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +  std::uniform_real_distribution<double> dist(-1., 1.);
`#include <random>`

2021-08-21 18:08 UTC, kidder commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +          make_not_null(&generator), make_not_null(&dist), used_for_size);
`#include "Utilities/Gsl.hpp"`

2021-08-21 18:08 UTC, kidder commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +  using type = Scalar<DataVector>;
`#include "DataStructures/Tensor/TypeAliases.hpp"`

2021-08-21 18:08 UTC, kidder commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +          System>::RandomParameters{amplitude, std::nullopt}}};
`#include <optional>`

2021-08-21 18:08 UTC, kidder commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +  const DataVector& fields_randomized = get(get_tag(ScalarFieldTag{}));
`#include "DataStructures/Tensor/Tensor.hpp"`

2021-08-25 20:21 UTC, nilsvu commented
@yoonso0-0 Could you provide the second review for this PR? If you haven't done a review yet, here's a few resources:

- [GitHub's guide on PR reviews](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)
- Our [code review guide](https://spectre-code.org/code_review_guide.html)
- Our [guidelines on the review process](https://spectre-code.org/contributing_to_spectre.html#pull-request-reviews)

Also, feel free to use reviews to ask questions on code you find unclear :)

2021-08-25 20:31 UTC, nilsvu commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +    std::seed_seq seeds{std::hash<ElementId<Dim>>{}(element_id),
Else all elements will have the same data. Added a note.

2021-08-25 20:56 UTC, kidder commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +    std::seed_seq seeds{std::hash<ElementId<Dim>>{}(element_id),
Ah, yes, that makes sense.  Adding the note is good

2021-08-25 21:44 UTC, yoonso0-0 commented
@nilsleiffischer I'd be happy too -- first let me take some time digesting what you shared since this will be my first time doing PR review

2021-08-27 16:21 UTC, yoonso0-0 reviewed
Tried my first review, though I've got many things to understand about the logic itself.

2021-08-27 16:21 UTC, yoonso0-0 commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +      using type = Options::Auto<size_t>;
Q. What's the difference between using `Options::Auto<size_t>` and just `size_t`?

2021-08-27 16:21 UTC, yoonso0-0 commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +    return {std::move(box)};
Q. I see at many places in our code using this phrase returning box - can you explain why we need curly braces?

2021-08-27 16:21 UTC, yoonso0-0 commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +    std::seed_seq seeds{std::hash<ElementId<Dim>>{}(element_id),
`#include <functional>`?

2021-08-27 16:21 UTC, yoonso0-0 commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +    db::mutate<fields_tag>(make_not_null(&box),
`#include "Utilities/Gsl.hpp"`?

2021-08-27 16:21 UTC, yoonso0-0 commented on tests/Unit/Elliptic/Actions/Test_RandomizeInitialGuess.cpp
> +  MAKE_GENERATOR(generator);
`#include "Framework/TestHelpers.hpp"`?

2021-08-27 16:21 UTC, yoonso0-0 commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +  using const_global_cache_tags = tmpl::list<RandomParametersTag>;
Q. Is it possible to parse options with alias `const_global_cache_tags` inside this action, not being directly inside `Metavariables` of SolvePoisson.hpp?

2021-08-29 14:30 UTC, nilsleiffischer commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +      using type = Options::Auto<size_t>;
`Options::Auto<T>` can be either `Auto` or `T` in the input file, and is represented as `std::optional<T>`. So here, the user can either specify a seed, or write "Auto" to use a random seed. More here: https://spectre-code.org/classOptions_1_1Auto.html

2021-08-29 14:34 UTC, nilsleiffischer commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +    return {std::move(box)};
The return value of actions is currently a `std::tuple<db::DataBox&&>`, so actions get a DataBox, can mutate and even add/remove tags, and then pass it along to the next action. The curly braces initialize the `std::tuple`.

In the future we want to change the `std::tuple` to a more descriptive struct, but the idea stays the same.

2021-08-29 14:39 UTC, nilsleiffischer commented on src/Elliptic/Actions/RandomizeInitialGuess.hpp
> +  using const_global_cache_tags = tmpl::list<RandomParametersTag>;
Yes, the `const_global_cache_tags` from actions are collected and joined with the `const_global_cache_tags` in the `Metavariables` :) More here: https://spectre-code.org/classParallel_1_1GlobalCache.html

2021-08-29 14:40 UTC, nilsleiffischer commented
Fixup pushed -- thanks for your reviews @kidder and @yoonso0-0!

2021-09-02 12:48 UTC, nilsleiffischer commented
@kidder and @yoonso0-0 please check the fixup

2021-09-03 00:27 UTC, kidder approved these changes, later dismissed

2021-09-03 00:28 UTC, yoonso0-0 submitted a review, later dismissed

2021-09-03 01:08 UTC, kidder commented
you can squash

2021-09-03 22:46 UTC, nilsleiffischer commented
@kidder this is squashed and rebased. Cheers!

2021-09-03 22:51 UTC, kidder approved these changes

2021-09-03 22:51 UTC, merged