Add previous trigger time to dense triggers
sxs-collaboration/spectre pull request #3445
Opened 2021-08-17 20:11 UTC by moxcodes

## Proposed changes

Make available the previous time a trigger has fired, and store in the `DataBox` when each event is called, so that events may make use of the previous time without altering the events interface

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

This is required for the CCE-GH executable to enforce strict ordering of GH data as discussed in #3422

2021-08-17 21:31 UTC, wthrowe commented
The main trouble I see here is that Events can also be run from EventsAndTriggers (non-Dense).  Maybe we have to start distinguishing between the two types, like we do with StepChoosers.

2021-08-17 21:40 UTC, moxcodes commented
Ah, yes, I agree that's a problem.
Under the current construction, I think it's a runtime problem rather than a compile-time problem -- the tag will be in the databox regardless, but if an event intended to use it is run from non-dense triggers, it won't have any meaningful value. So, I think the changes suggested here will work, but add more of an explicit danger to mixing the events -- I think that there is some similar danger present already, because there are plenty of things (e.g. non-compute tags that aren't evolution tags) that non-dense events are permitted to access but will have incorrect value for dense triggers.

I agree that the right way to restore safety would be to distinguish between the kinds of events -- would you be satisfied if we just opened an issue to suggest that alteration for the future, so that these handful of changes supporting the GH-CCE communication can go in on their own?

2021-08-17 21:43 UTC, wthrowe commented
I think an issue is fine.  I'll do a full review of this PR later.

2021-08-17 21:50 UTC, moxcodes commented
Thanks @wthrowe ! I've opened an issue describing the desired feature.

2021-08-18 00:50 UTC, wthrowe requested changes

2021-08-18 00:50 UTC, wthrowe commented on tests/Unit/Evolution/EventsAndDenseTriggers/DenseTriggers/Test_Times.cpp
> +  }
Check that it didn't get set in the other case.  If this code is obsoleted by changes to `previous_trigger_time()` in the other commit you can ignore this.

2021-08-18 00:50 UTC, wthrowe commented on src/Evolution/EventsAndDenseTriggers/DenseTrigger.hpp
> +  }
(Optional) Half of this function is in the wrong commit.  It won't break bisects and splitting is mildly annoying, so I'll leave it up to you whether to fix it.

2021-08-18 00:50 UTC, wthrowe commented on src/Evolution/EventsAndDenseTriggers/EventsAndDenseTriggers.hpp
> + */
This tag acts a little strangely from a user's perspective, so maybe emphasize that it is for use in an Event to query information about the trigger associated with that event.

2021-08-18 00:50 UTC, wthrowe commented on src/Evolution/EventsAndDenseTriggers/DenseTrigger.hpp
> +            next_previous_trigger_time_ = db::get<::Tags::Time>(box);
This changes the behavior of `previous_trigger_time()` so it does not match its documentation anymore.  Change one or the other.

2021-08-18 04:27 UTC, moxcodes commented
I've pushed a couple of fixups. I moved all the changes to `DenseTriggers.hpp` to the first commit, so that the split isn't as odd anymore.
Cheers!

2021-08-18 18:21 UTC, wthrowe commented
Looks good.  Go ahead and squash.

2021-08-19 04:47 UTC, moxcodes commented
Squashed.
Cheers!

2021-08-20 00:57 UTC, wthrowe approved these changes

2021-08-20 04:06 UTC, kidder approved these changes

2021-08-20 04:06 UTC, merged