Add InitialData base class for advection system
sxs-collaboration/spectre pull request #3448
Opened 2021-08-18 16:52 UTC by yoonso0-0

## Proposed changes

Define `InitialData` base class (which will have `AnalyticSolution`, `AnalyticData`, `NumericInitialDataFromFile` as its derived classes in the upcoming PR) within ScalarAdvection namespace, and add Initial Data group to Groupdefs. Add the base class to factory creation list and its tag to global cache tags.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-08-18 18:17 UTC, wthrowe commented
I think we should wait to add the class until it has some sort of functionality.

2021-08-18 18:21 UTC, yoonso0-0 commented
@wthrowe I'll mark this PR as 'in progress' until there comes a practical change in functionality. How about that?

2021-08-18 22:23 UTC, nilsleiffischer requested changes
Looks good! You can squash these changes directly, and feel free to push more commits to this branch.

2021-08-18 22:23 UTC, nilsvu commented on src/Evolution/Systems/ScalarAdvection/InitialData/InitialData.hpp
> +class InitialDataBase : public PUP::able {
Name this just `InitialData` please. You can make the default-constructor `protected` if you want to make sure the class is abstract (can't be constructed).

2021-08-18 22:23 UTC, nilsvu commented on src/Evolution/Systems/ScalarAdvection/InitialData/InitialData.hpp
> +class Derived : public InitialDataBase {
Delete this class please, since it's just a placeholder. I think you can derive the `Sinusoid` solution from `InitialData` already, without breaking any existing code.

2021-08-18 22:23 UTC, nilsvu commented on src/Evolution/Systems/ScalarAdvection/InitialData/InitialData.hpp
> +struct InitialDataGroup {
You can just name this `InitialData`, and then you can delete the `name()` function.

2021-08-18 22:23 UTC, nilsvu commented on src/Evolution/Systems/ScalarAdvection/InitialData/InitialData.hpp
> +struct InitialData : db::SimpleTag {
My suggestion is to move this tag and the option tag to a new file `Evolution/Tags/InitialData.hpp`. Then template both on `typename InitialDataType` and use it in the `std::unique_ptr`. Finally, add the following:

```cpp
namespace evolution::Tags {
struct InitialDataBase : db::BaseTag {};

template <typename InitialDataType>
struct InitialData : InitialDataBase, db::SimpleTag {
  using type = std::unique_ptr<InitialDataType>;
  /// ...
```

With this setup you can use `db::get<evolution::Tags::InitialDataBase>(box)` to retrieve the initial-data object without knowing its type. This will be useful to write code that's not specific to a particular system.

2021-08-18 22:33 UTC, yoonso0-0 commented
@wthrowe Yes. I marked this PR as 'in progress' -- just wanted to get feedbacks and make sure there's nothing _really_ bad about this base class, before piling up other commits.

2021-08-18 22:56 UTC, yoonso0-0 commented on src/Evolution/Systems/ScalarAdvection/InitialData/InitialData.hpp
> +struct InitialData : db::SimpleTag {
How the global cache tag (which was Tags::InitialData) needs to be modified? We still need the template parameter for that, right?

2021-08-18 23:00 UTC, yoonso0-0 commented on src/Evolution/Systems/ScalarAdvection/InitialData/InitialData.hpp
> +class Derived : public InitialDataBase {
I deleted this class in the current PR.

2021-08-19 06:33 UTC, nilsleiffischer commented on src/Evolution/Systems/ScalarAdvection/InitialData/InitialData.hpp
> +struct InitialData : db::SimpleTag {
In the metavariables you add the tag to the `const_global_cache_tags` like this:

```
evolution::Tags::InitialData<ScalarAdvection::InitialData::InitialData>
```

Note you pass the base class here, not a particular derived class. If at some point we find that we can share the `InitialData` base class between systems then the template parameter can be removed, but that's an easy change.

2021-08-19 06:44 UTC, nilsleiffischer commented
@yoonso0-0 My general advice for how to proceed is: Don't worry about numeric initial data for now. First derive the `Sinusoid` class from `InitialData` so it can be factory-created. Then replace the `SetVariables` action with a new one that traverses the `factory_classes` and calls their `variables` function to get the initial data. That needs to use our `call_with_dynamic_type` mechanism which is probably hard to get right on the first try, so feel free to message me so we can go over it together once you're at that point.

2021-08-24 21:55 UTC, yoonso0-0 commented
@nilsleiffischer Pushed up to today's call. I think you can skip the cosine data commit (it's mostly a copy&paste from sinusoid solution, and also works fine). There are a number of lines marked temporary or 'this needs to be done' -- feel free to suggest any changes to make these look less cluttered.

2021-08-24 22:58 UTC, nilsleiffischer requested changes
Looks good, mostly just the obvious "remove the temporary comments"

2021-08-24 22:58 UTC, nilsleiffischer commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> +  using new_initial_data_tag =
I think it's better to delete this alias and put the tag in the `const_global_cache_tags` list directly, so just drop this change from the commit.

2021-08-24 22:58 UTC, nilsleiffischer commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> +      // note that SetVariables action is replaced to a new one now
thanks for the comment, but from my side it can be deleted :)

2021-08-24 22:58 UTC, nilsleiffischer commented on src/Evolution/Initialization/InitialData.hpp
> +  std::cout << " evolution::ScalarAdvection::initial_data (called)"
delete, and the `<iostream>` include

2021-08-24 22:58 UTC, nilsleiffischer commented on src/Evolution/Initialization/InitialData.hpp
> +decltype(auto) initial_data(const InitialData& initial_data,
You can make the return type explicit: `tuples::TaggedTuple<Tags...>`

2021-08-24 22:58 UTC, nilsleiffischer commented on src/Evolution/Initialization/InitialData.hpp
> +namespace ScalarAdvection {
remove the namespace. I think the new function shouldn't collide with the existing ones, but not entirely sure.

2021-08-24 22:58 UTC, nilsleiffischer commented on src/Evolution/Initialization/SetVariables.hpp
> +namespace ScalarAdvection {
delete

2021-08-24 22:58 UTC, nilsleiffischer commented on src/Evolution/Initialization/SetVariables.hpp
> +struct SetVariables {
How about `SetInitialData`

2021-08-25 20:21 UTC, yoonso0-0 commented
@nilsleiffischer All requested changes updated so far :) The new function did not make conflicts.

2021-08-25 20:28 UTC, nilsvu commented
Nice! I think the only thing that's left is to handle observations of the error to the analytic solution. Now we only know at runtime if we have an analytic solution or not, so we have to store it in a `std::optional`. You can use the existing tag `AnalyticSolutionsOptional` in `PointwiseFunctions/AnalyticSolutions/Tags.hpp` for this. I suggest you create a new compute item for this tag and replace `evolution::Tags::AnalyticCompute` with it. Let me know in case you get stuck.

2021-08-27 18:00 UTC, yoonso0-0 commented on src/Evolution/Initialization/InitialData.hpp
> +        if constexpr (evolution::is_analytic_data_v<derived>) {
@nilsleiffischer If I drop this `constexpr` from if branch, I get the following message:
```
error: no matching member function for call to 'variables'
          return initial_data_derived->variables(
```
what's happening here? Is it related with that we are using `auto*` at the line 43?

2021-08-27 22:51 UTC, kidder requested changes
I am requesting a change as I would like to review this PR.

2021-09-02 23:18 UTC, yoonso0-0 commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> +                    observe_fields>,
This line seems to be reviewed -- should we place `::Tags::AnalyticSolutionsOptional<observe_fields>` instead..?

2021-09-03 09:06 UTC, nilsleiffischer requested changes
Please feel free to squash things directly

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> +#include "PointwiseFunctions/AnalyticData/ScalarAdvection/Cosine.hpp"  // IWYU pragma: keep
I think you can just delete the `Cosine` class now since you added it for testing, right?

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> +  using initial_data_list = tmpl::flatten<tmpl::list<
My suggestion is you split this list and move it to `PointwiseFunctions/Analytic{Solutions,Data}/ScalarAdvection/Factory.hpp`. You'll have to template it on `Dim`. Then do something like this in the `factory_classes` below:

```cpp
tmpl::pair<InitialData, tmpl::append<
  ScalarAdvection::AnalyticSolutions::all_analytic_solutions<Dim>,
  ScalarAdvection::AnalyticData::all_analytic_data<Dim>>>
```

You won't have to `include` all the analytic classes here in the executable anymore, just the two `Factory.hpp` files.

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> -  using analytic_solution_fields =
You can just keep this alias and set it equal to `observe_fields`. In other executables we may want to me more selective about which fields to observe and which we compute errors for, so the alias is a handy way to specify this.

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> +                    observe_fields>,
Drop this particular change (see comment above)

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Initialization/InitialData.hpp
> +        if constexpr (evolution::is_analytic_data_v<derived>) {
Yes it is. The lambda gets instantiated once for every derived class in the list, and the `auto` gets inferred to be that type. Then the `constexpr` means the condition is evaluated at compile-time, so in every instantiation of the lambda the compiler only sees one of the branches of the if-clause. If you remove the `constexpr` then the condition only gets evaluated at runtime, so the compiler tries to compile both branches for every derived class. That fails because analytic data classes have no `variables` function with a `time` argument. Let me know if anything is still unclear.

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Initialization/SetVariables.hpp
> +struct SetInitialData {
Could you move this action into a separate file please?

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Initialization/SetVariables.hpp
> +  using initialization_option_tags =
Just `initialization_tags`, so this gets picked up by the code that assembles options. You can fix the name in the other action as well, or leave it, up to you.

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Initialization/SetVariables.hpp
> +                initial_data, inertial_coords, initial_time,
I think `std::move(inertial_coords)` because it's computed above (not only referenced) and can be forwarded here.

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Systems/ScalarAdvection/InitialData/InitialData.hpp
> +class InitialData : public PUP::able {
I think you can just move this to `Evolution/InitialData.hpp` and into the `evolution` namespace, and we'll use it for all systems. We can still add subclasses for specific systems if we need them.

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Tags/ComputeTags.hpp
> +struct InitializeOptionalAnalyticSolutionCompute
Name this `AnalyticSolutionOptionalCompute`, in line with the naming of other compute tags.

2021-09-03 09:06 UTC, nilsvu commented on src/Evolution/Tags/ComputeTags.hpp
> +// Distributed under the MIT License.
Please name this file `AnalyticSolutionCompute.hpp` (we have started to put tags into individual files if they are likely to be included separately)

2021-09-03 09:06 UTC, nilsvu commented on src/PointwiseFunctions/AnalyticData/ScalarAdvection/Cosine.hpp
> +class Cosine : public ScalarAdvection::InitialData::InitialData,
Can you perhaps think of an analytic data class that would be more useful than the Cosine?

2021-09-03 09:26 UTC, nilsleiffischer commented
I think the things you need to add tests for are: the `SetInitialData` action and the compute tag. But it might be more efficient to wait for a coarse second review before writing those tests.

@kidder I think it would be reasonable to take a look at this point, or perhaps once @yoonso0-0 has squashed in the changes above.

2021-09-03 16:37 UTC, yoonso0-0 commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> -  using analytic_solution_fields =
Got it.

2021-09-03 17:51 UTC, yoonso0-0 commented on src/Evolution/Initialization/SetVariables.hpp
> +  using initialization_option_tags =
Exactly what kind of change would this make on executables?

2021-09-03 18:21 UTC, yoonso0-0 commented on src/PointwiseFunctions/AnalyticData/ScalarAdvection/Cosine.hpp
> +class Cosine : public ScalarAdvection::InitialData::InitialData,
Nothing really 'more useful' -- this is very simple system and analytic solution is given quite trivially for every analytic data, so there is no analytic data which does not have solution. Maybe we can try with a profile a little bit more complicated than cosine function? i.e. half-circle or step.

2021-09-04 07:45 UTC, nilsleiffischer commented on src/Evolution/Initialization/SetVariables.hpp
> +  using initialization_option_tags =
Doesn't change anything because other actions list the InitiaTime Tag already. Currently the misspelled alias is just ignored.

2021-09-07 17:51 UTC, nilsleiffischer commented on src/PointwiseFunctions/AnalyticData/ScalarAdvection/Cosine.hpp
> +class Cosine : public ScalarAdvection::InitialData::InitialData,
Ok, no need to have analytic data classes for the advection system then. The action and compute tag are tested independently of the system anyway.

2021-09-07 17:58 UTC, yoonso0-0 commented
@nilsleiffischer @kidder I squashed the proposed changes and pushed them after doing some rearrangements.

First two commits are minor fixes. The third one (adding cosine initial data) is not something really necessary, but for providing at least one example of how to handle analytic data classes. The commits with `[wip]` are without corresponding tests yet.

2021-09-07 18:02 UTC, nilsleiffischer commented
Looks good! I think you can just remove all things related to analytic data from the scalar advection system, and squash the "Use factory header" commit into the one before. Then I think this is ready to go once the action and compute tag have tests 👍

2021-09-07 21:40 UTC, nilsleiffischer requested changes

2021-09-07 21:40 UTC, nilsleiffischer commented on src/Evolution/Executables/ScalarAdvection/EvolveScalarAdvection.hpp
> +                   tmpl::list<ScalarAdvection::Solutions::
This `tmpl::list` isn't needed

2021-09-07 21:40 UTC, nilsleiffischer commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Factory.hpp
> +using all_analytic_solutions = tmpl::list<
Wrap this in `tmpl::flatten`

2021-09-07 21:41 UTC, nilsleiffischer commented
@kidder this is ready for your review

2021-12-10 23:38 UTC, yoonso0-0 commented
I'm closing this PR since my fork branch is at working state and there is no code here to be merged.

2021-12-10 23:38 UTC, closed without merging