CCE Conformal factor initial data
sxs-collaboration/spectre pull request #3450
Opened 2021-08-20 18:03 UTC by moxcodes

## Proposed changes

Adds a CCE initial data generator based on choosing an angular conformal factor based on the value of the CCE scalar \beta. This is motivated by an attempt to make the time variable approximately asymptotically inertial.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-08-20 18:07 UTC, moxcodes commented
@keefemitman can you give this branch a try and make sure that it generates similarly good (or better) initial data to what you saw on the branch we were working with for a prototype?
The choice of options that should be most similar to our most recent iteration is probably something like:
```
ConformalFactor:
  AngularCoordinateTolerance: 1e-13
  MaxIterations: 1000
  RequireConvergence: True
  OptimizeL0Mode: True
  UseBetaIntegralEstimate: False
  ConfromalFactorIterationHeuristic: SpinWeight1CoordPerturbation
  UseInputModes: False
  InputModes: []
```

2021-08-20 23:17 UTC, keefemitman commented
> @keefemitman can you give this branch a try and make sure that it generates similarly good (or better) initial data to what you saw on the branch we were working with for a prototype?
> The choice of options that should be most similar to our most recent iteration is probably something like:
> 
> ```
> ConformalFactor:
>   AngularCoordinateTolerance: 1e-13
>   MaxIterations: 1000
>   RequireConvergence: True
>   OptimizeL0Mode: True
>   UseBetaIntegralEstimate: False
>   ConfromalFactorIterationHeuristic: SpinWeight1CoordPerturbation
>   UseInputModes: False
>   InputModes: []
> ```

Will do!

2021-08-23 19:17 UTC, keefemitman requested changes
I was able to run the code with the new initial data scheme, but I found that I had to lower the angular tolerance to around 1e-4 instead of its suggested value of 1e-11. Is this ok?

2021-08-23 19:17 UTC, keefemitman commented on src/Evolution/Systems/Cce/Initialize/InitializeJ.hpp
>  }  // namespace Cce
Also need the line `#include "Evolution/Systems/Cce/Initialize/ConformalFactor.hpp"`

2021-08-23 19:17 UTC, keefemitman commented on src/Evolution/Systems/Cce/Initialize/InitializeJ.hpp
>                                   Tags::CauchyAngularCoords>;
Line 413 needs ConformalFactor as a part of the list

2021-08-23 19:53 UTC, moxcodes commented
Thanks for checking that @keefemitman -- I would have anticipated that the algorithm would converge better than that. Can you try changing the OptimizeL0 option to `  OptimizeL0Mode: False`?
How does the value that you need to set for the threshold compare to the printed error measure from the prototype branch?

2021-08-23 19:57 UTC, keefemitman commented
@moxcodes With `OptimizeL0Mode` as false I still fail to obtain the specified tolerance. The print out is
"final maximum over collocation points deviation of J from target of 1.26732e-05"

2021-08-23 20:02 UTC, moxcodes commented
The high tolerance is concerning, but I think not necessarily a deal-breaker if the initial data still seems to be an improvement in terms of the transients we were seeing. Do you have any sense for how the waveform on this one compares with the waveforms you were seeing from the `cce_beta_based_id` branch?

2021-08-23 20:04 UTC, keefemitman commented
I'm still running a waveform right now, but I'll let you know once it finishes!

2021-08-23 23:10 UTC, keefemitman commented
Ok so it looks like the previous version of the conformal factor branch is much better than the new one in that the previous version of the branch largely reduced the transient effects at early times, but the newer version doesn't
<img width="441" alt="Screen Shot 2021-08-23 at 4 08 14 PM" src="https://user-images.githubusercontent.com/53911808/130530831-7d6628f1-c5b4-43cd-9c66-f3c483ae6927.png">

2021-08-24 00:06 UTC, moxcodes commented
Thanks, @keefemitman , I'll look into that and update this PR once I manage to find and fix the bug I must have introduced in the new version.

2021-09-18 17:54 UTC, moxcodes commented
I pushed a fixup and rebased. I believe that I've fixed the regression -- @keefemitman could you please test again and see if the behavior is now similar to the previous branch that has better initial transient results?
Thanks!

2021-09-20 17:07 UTC, keefemitman commented
@moxcodes Unfortunately I'm still seeing the same behavior as before, even with the new changes you made.

2021-10-18 21:19 UTC, keefemitman commented
> @moxcodes Unfortunately I'm still seeing the same behavior as before, even with the new changes you made.

Scratch that, this was just due to a different tolerance that I set in the input file. Everything looks good now!

2022-05-03 17:29 UTC, kidder commented
@nilsdeppe this has been rebased and sqaushed

2022-05-05 19:45 UTC, nilsdeppe requested changes
LGTM, couple easy suggestions, rebase and squash right away please

2022-05-05 19:45 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Initialize/ConformalFactor.hpp
> +  static constexpr Options::String help = {""};
Maybe have some sort of non-empty string?

2022-05-05 19:45 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/Initialize/ConformalFactor.hpp
> +  explicit ConformalFactor(CkMigrateMessage* /*unused*/) {}
move definition to cpp and do `msg) : InitializeJ<false>(msg) {}`

2022-05-09 20:12 UTC, nilsdeppe approved these changes

2022-05-09 20:12 UTC, merged