Add elliptic HasConverged trigger
sxs-collaboration/spectre pull request #3452
Opened 2021-08-21 10:58 UTC by nilsleiffischer

## Proposed changes

Trigger when the solver has converged. Useful to output norms and volume data only of the solution.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-21 17:06 UTC, kidder commented
marking as in progress until it compiles

2021-08-24 21:25 UTC, wthrowe approved these changes, later dismissed

2021-08-25 18:56 UTC, kidder requested changes
you can squash

2021-08-25 18:56 UTC, kidder commented on tests/Unit/Elliptic/Triggers/CMakeLists.txt
> +  EventsAndTriggers
I think we can alphabetize these

2021-08-25 18:56 UTC, kidder commented on src/Elliptic/Triggers/HasConverged.hpp
> +#include <cstddef>
unused

2021-08-25 18:56 UTC, kidder commented on tests/Unit/Elliptic/Triggers/Test_HasConverged.cpp
> +#include "DataStructures/DataBox/Tag.hpp"
unused

2021-08-25 18:56 UTC, kidder commented on tests/Unit/Elliptic/Triggers/Test_HasConverged.cpp
> +#include <initializer_list>
unused

2021-08-25 18:56 UTC, kidder commented on tests/Unit/Elliptic/Triggers/Test_HasConverged.cpp
> +#include <string>
unused

2021-08-25 18:59 UTC, nilsvu commented
Fixed and rebased, thanks for reviewing @kidder and @wthrowe

2021-08-25 19:11 UTC, kidder approved these changes

2021-08-25 19:11 UTC, wthrowe approved these changes

2021-08-25 23:16 UTC, merged