Add PhaseSelection metavariables struct for PhaseControl framework
sxs-collaboration/spectre pull request #3453
Opened 2021-08-21 17:07 UTC by moxcodes

## Proposed changes

Adds a metavariables struct that contains the metavariables type aliases and functions that are used by `PhaseControl` infrastructure, and adds some documentation for them in the protocol associated.
Some of the metavariables changes required additional tweaks to the GeneralizedHarmonic and GhValenciaDivClean executables to accomodate the different order of definitions.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-08-25 17:40 UTC, kidder requested changes
you can squash these changes when rebasing

2021-08-25 17:40 UTC, kidder commented on src/Parallel/PhaseControl/PhaseSelection.hpp
> + * - `template <typename ParallelComponent> registration_list`: A metafunction,
A metafunction that has the type alias...

2021-08-25 17:40 UTC, kidder commented on src/Parallel/PhaseControl/PhaseSelection.hpp
> + * `ParallelComponent` is migrated (note: each item in these lists must be
is migrated.  (Note:

2021-08-25 17:40 UTC, kidder commented on src/Evolution/Executables/Burgers/EvolveBurgers.hpp
> +  struct PhaseSelectionTemplate : tt::ConformsTo<PhaseControl::PhaseSelection> {
can we drop the Template as part of the name?  It's obviously a template 🙂   If it conflicts with the `PhaseControl::PhaseSelection` protocol, I'd rather change that name to `PhaseContol::Selection` or something involving Protocol

2021-08-29 15:33 UTC, nilsleiffischer commented on src/Parallel/PhaseControl/PhaseSelection.hpp
> +// Distributed under the MIT License.
Making a note here so I don't forget: `docs/DevGuide/Parallelization.md` needs an update

2021-09-18 17:13 UTC, moxcodes commented
Rebased and a fixup posted.
Cheers!

2021-09-18 17:37 UTC, kidder requested changes
you can squash with the additional fix

2021-09-18 17:37 UTC, kidder commented on src/Parallel/PhaseControl/PhaseSelection.hpp
> + * that has the type alias, must contain type alias `type` that is the list of
sorry, I wasn't clear before. "A metafunction that has the type alias `type` that is the list..."

2021-09-18 17:41 UTC, kidder commented
@nilsleiffischer can you provide a review?

2021-09-18 18:02 UTC, moxcodes commented
Squashed with the additional fix.
Cheers!

2021-09-18 18:59 UTC, kidder approved these changes

2021-09-21 18:21 UTC, kidder commented
@nilsleiffischer are you going to review this?

2025-08-25 18:26 UTC, kidder commented
I took a look at this, and #3888 made this PR obsolete.  Essentially phase changes are now handled by Main and there is nothing left in the metavariables about phase changes except the inclusion of the ExecutePhaseChange action in the action list.

2025-08-25 18:26 UTC, closed without merging