MutableCache callbacks now work in ActionTesting.
sxs-collaboration/spectre pull request #3465
Opened 2021-08-26 17:02 UTC by markscheel

## Proposed changes

Fixes #3454

Previously, callbacks worked when called on a collection of elements (i.e. a full chare) but not on a single element (i.e. a component of a chare).

Three things needed to be changed:
1. MockDistributedObjectProxy now has a pup function (the pup function errors and should not be used, but needs to be there to compile).  There already was a pup function in MockCollectionOfDistributedObjectsProxy, which is why callbacks worked on a collection of elements.
2. MockCollectionOfDistributedObjectsProxy::operator[] now returns a reference to a stored MockDistributedObjectProxy (previously it created a temporary MockDistributedObjectProxy and returned that temporary by value).  So now the mock proxies have the same interface as the non-mocked proxies (i.e. you can do `auto& proxy = mock_collection_of_distributed_objects_proxy[i];`).
3. Add a test, which is an expanded version of the test @wthrowe posted in #3454.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-08-26 18:23 UTC, wthrowe requested changes
Making sure that I understand: Using `PerformAlgorithmCallback` currently has no observable effect in the mocking framework, correct?  I don't think this is a problem since it will still determine the return value of `mutable_cache_item_is_ready`, I just want to verify.

2021-08-26 18:23 UTC, wthrowe commented on tests/Unit/Framework/ActionTesting.hpp
> +  void pup(PUP::er& /*p*/) noexcept {  // NOLINT
```
// NOLINTNEXTLINE(google-runtime-references)
void pup(PUP::er& /*p*/) noexcept {
```

2021-08-26 22:48 UTC, kidder reviewed
I have no additional requested changes

2021-08-27 19:10 UTC, markscheel commented
Made change (and made a similar change to the other pup function in that file, and squashed since the change was trivial).

Correct, `PerformAlgorithmCallback` has no ultimate effect in the ActionTesting framework: it calls `perform_algorithm` when the MutableCache item is mutated, but `perform_algorithm` itself is a no-op in the ActionTesting framework.   This is because in ActionTesting, all the iterable actions are meant to be called explicitly.

2021-08-27 20:06 UTC, wthrowe approved these changes

2021-08-29 03:11 UTC, merged