Add code to check if functions of time are ready
sxs-collaboration/spectre pull request #3467
Opened 2021-08-26 19:52 UTC by wthrowe

Dependent on #3465, which is included here.  Only the last commit is new.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-27 19:16 UTC, knelli2 requested changes
Only reviewed the last commit.

2021-08-27 19:16 UTC, knelli2 commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +                   << keys_of(functions_of_time) << ")");
ASSERT error message is incorrect if the `function_to_check` is accidentally in `functions_of_time` twice. Are duplicates guaranteed to be removed?

2021-08-27 19:16 UTC, knelli2 commented on tests/Unit/Domain/FunctionsOfTime/Test_FunctionsOfTimeAreReady.cpp
> +    static_cast<domain::FunctionsOfTime::PiecewisePolynomial<2>&>(
`dynamic_cast`

2021-08-27 19:16 UTC, knelli2 commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +            cache, array_index, component, db::get<::Tags::Time>(box));
This action always checks all functions in `domain::Tags::FunctionsOfTime`. Is that the intended use?

2021-08-27 19:16 UTC, knelli2 commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +        std::array<std::string, 0>{}) noexcept {
Just for my understanding, you have to pass in the unused Component* argument so the template parameter can be automatically deduced, correct?

2021-08-27 19:16 UTC, knelli2 commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +              alg::find(functions_to_check, name) == functions_to_check.end()) {
At a glance, the logic of this if is confusing. Maybe add parenthesis to make it clearer?

2021-08-27 19:48 UTC, wthrowe commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +                   << keys_of(functions_of_time) << ")");
It's a map.

2021-08-27 19:50 UTC, wthrowe commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +        std::array<std::string, 0>{}) noexcept {
Correct.

2021-08-27 19:50 UTC, wthrowe commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +              alg::find(functions_to_check, name) == functions_to_check.end()) {
What would you like parenthesized?

2021-08-27 19:50 UTC, wthrowe commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +            cache, array_index, component, db::get<::Tags::Time>(box));
Yes.  We want actions that aren't doing weird things like dense output to be able to assume that they can fetch coordinate-dependent quantities.

2021-08-27 20:48 UTC, knelli2 commented on src/Domain/FunctionsOfTime/FunctionsOfTimeAreReady.hpp
> +              alg::find(functions_to_check, name) == functions_to_check.end()) {
`(not functions_to_check.empty())`
I was reading it as `not (... and ...)` instead of `(not ...) and ...`. I forgot `not` takes precedence over `and`.

2021-08-30 21:07 UTC, wthrowe commented
Rebased, no longer dependent.

Added fixups, including documentation explaining the purpose of the action.

2021-08-31 20:39 UTC, knelli2 approved these changes, later dismissed
Looks good. You can squash.

2021-09-02 19:17 UTC, knelli2 approved these changes

2021-09-07 23:54 UTC, nilsdeppe approved these changes

2021-09-07 23:55 UTC, merged