Add BBH exec
sxs-collaboration/spectre pull request #3468
Opened 2021-08-26 20:29 UTC by geoffrey4444

## Proposed changes

This PR adds an executable for an executable that evolves binary black holes. Depends on #3460 and #3461; the new code is only in the commit labeled "Add exec to evolve binary black holes."

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-08-26 20:30 UTC, geoffrey4444 commented
I tested that I can start a BBH evolution using numeric initial data with the code in this PR. It's waiting for some smaller PRs, but in case there are bigger design changes requested, I thought I'd go ahead and submit this now

2021-08-26 22:30 UTC, kidder requested changes

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHoleFwd.hpp
> +template <size_t VolumeDim, typename InitialData, typename BoundaryConditions>
you don't need any of these template parameters (or the forward includes)

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +template <size_t VolumeDim, typename InitialData, typename BoundaryConditions>
get rid of the template parameters.  VolumeDim = 3, InitialData = evolution::NumericInitialData and you shouldn't use BoundaryConditions

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +  using frame = Frame::Inertial;
Does anything outside this file use this type alias? If not, I would get rid of it

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +  using analytic_solution_fields = typename system::variables_tag::tags_list;
get rid of

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +  using analytic_solution_tag = Tags::AnalyticSolution<BoundaryConditions>;
get rid of

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +      std::conditional_t<volume_dim == 3,
get rid of conditional

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +      return "LoadBalancing";
checkpointing should be in this list

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +                                                          Phase::LoadBalancing>,
checkpointing should be in this list

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +        return evolution::is_numeric_initial_data_v<initial_data>
get rid of conditional

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +          evolution::is_numeric_initial_data_v<initial_data>, tmpl::list<>,
get rid of conditional

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +          evolution::Tags::AnalyticCompute<volume_dim, analytic_solution_tag,
get rid of

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +          tmpl::conditional_t<
get rid of conditional

2021-08-26 22:30 UTC, kidder commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveBinaryBlackHole.hpp
> +      std::conditional_t<evolution::is_numeric_initial_data_v<initial_data>,
get rid of conditional

2021-08-26 22:30 UTC, kidder commented on tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml
> +AnalyticSolution:
shouldn't need this

2021-09-03 04:00 UTC, geoffrey4444 commented
@kidder thanks for your help! I rebased and made your suggested changes, including removing the analytic solution

2021-09-13 18:41 UTC, kidder commented
rebase and squash

2021-09-14 15:03 UTC, kidder commented
@geoffrey4444 this is not compiling...

2021-09-14 17:07 UTC, geoffrey4444 commented
@kidder Thanks for letting me know...when I squashed, I missed that ObserveNorms is now needs ::Tags::Time as an additional template parameter. I only had a few minutes this morning, so I thought I'd try getting away without compiling locally. 🤦‍♂️ 

I just pushed a fix. I made sure this time that it builds locally for me, and I'll keep my eye on GitHub to make sure everything looks good

2021-09-14 18:20 UTC, geoffrey4444 commented
The clang-8 test failure is a timeout in `InputFiles.Poisson.ProductOfSinusoids1D.yaml.execute_check_output`, which I didn't touch in this PR

2021-09-15 01:02 UTC, kidder approved these changes

2021-09-15 20:38 UTC, merged