Convert BoundaryCondition to factory map
sxs-collaboration/spectre pull request #3471
Opened 2021-08-28 02:59 UTC by kidder

## Proposed changes

Converts the system specific BoundaryCondition base classes to using the factory map.  

### Upgrade instructions

- Instead of having a type alias of `creatable_classes` within the system specific BoundaryCondition base classes, specify a type alias of `standard_boundary_conditions` in the BoundaryConditions namespace of the system.  
- In evolution system executables, instead of adding the system specific `BoundaryConditions::register_derived_with_charm` as an argument  to the function `charm_init_node_funcs` , add a `tmpl::pair<SYSTEM::BoundaryConditions::BoundaryCondition, SYSTEM::BoundaryConditions::standard_boundary_conditions>` to the `tmpl::map<>` of type alias `factory_classes` of the `
factory_creation` struct in the metavariables (where SYSTEM should be replaced by the appropriate namespace of the evolution system).

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

This will allow #3468 to not need anything related to an analytic solution

2021-08-29 08:20 UTC, nilsleiffischer requested changes
Looks good. Have you considered deleting the system-specific base classes and just use `domain::BoundaryConditions::BoundaryCondition` as base class everywhere? That removes a lot of boilerplate code and some templating.

2021-08-29 08:20 UTC, nilsvu commented on tests/Unit/Evolution/Systems/Burgers/BoundaryConditions/Test_Outflow.cpp
> -          "Outflow:\n");
Why did you delete this?

2021-08-29 08:20 UTC, nilsvu commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/Test_Outflow.cpp
> -          "Outflow:\n");
Same here

2021-08-29 15:04 UTC, kidder commented on tests/Unit/Evolution/Systems/Burgers/BoundaryConditions/Test_Outflow.cpp
> -          "Outflow:\n");
It is tested inside`helpers::test_boundary_condition_with_python`

2021-08-29 15:50 UTC, kidder commented
> Looks good. Have you considered deleting the system-specific base classes and just use `domain::BoundaryConditions::BoundaryCondition` as base class everywhere? That removes a lot of boilerplate code and some templating.

Yes, I am considering that

2021-09-01 16:55 UTC, nilsleiffischer commented
Needs a rebase to accommodate #3407

2021-09-01 20:39 UTC, wthrowe commented
This looks good, once it is rebased.

2021-09-02 19:16 UTC, kidder commented
@nilsleiffischer updated CurvedScalarWave and rebased

2021-09-02 20:55 UTC, nilsleiffischer approved these changes

2021-09-02 21:00 UTC, nilsleiffischer commented
Something went wrong with CI here. Maybe rebase/push again?

2021-09-02 23:34 UTC, merged