Add DirichletMinkowski GH BC
sxs-collaboration/spectre pull request #3473
Opened 2021-08-28 04:46 UTC by geoffrey4444

## Proposed changes

Add a GH Dirichlet boundary condition that sets the spacetime metric, phi, and pi to Minkowski. This allows you to impose flat space on the outer boundary without supplying an analytic solution, which is necessary for testing Dirichlet boundary conditions in binary-black-hole simulations, which do not have an analytic solution.

Ultimately, we will want to use bjorhus, constraint-preserving boundary conditions in these simulations, but until simulations using the Bjorhus BCs are working, having a flat-space Dirichlet condition as an alternative is helpful for comparing with the Bjorhus conditions.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-09-13 18:15 UTC, kidder requested changes

2021-09-13 18:15 UTC, kidder commented on src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/DirichletMinkowski.hpp
> + * \brief Sets Dirichlet boundary conditions using the analytic solution or
Sets Dirichlet boundary conditions corresponding to a Minkowski spacetime

2021-09-13 18:15 UTC, kidder commented on src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/DirichletMinkowski.hpp
> +    auto boundary_values = [&coords, &time]() noexcept {
just set everything here to their analytical values without calling into the analytic solution, or using the other free functions.  Then you don't need to specify the coordinates or time in the tags above or take them as arguments

2021-09-13 18:15 UTC, kidder commented on src/Evolution/Systems/GeneralizedHarmonic/BoundaryConditions/DirichletMinkowski.hpp
> +    *gamma1 = interior_gamma1;
should be able to move the definition of this function to the cpp file

2021-09-16 19:56 UTC, geoffrey4444 commented
Rebased and pushed a fixup commit...thanks for the review @kidder !

2021-09-16 22:58 UTC, nilsdeppe commented
This seems like a lot of code all to avoid holding the analytic data/solution in the DataBox when doing numerical initial data. Maybe the `Analytic` boundary conditions should hold the solution/data as a member variable instead? I wouldn't be surprised if a `DirichletKerrSchild` BC were added next, adding something like another 800 lines of code.

2021-09-17 01:16 UTC, geoffrey4444 commented
> This seems like a lot of code all to avoid holding the analytic data/solution in the DataBox when doing numerical initial data. Maybe the `Analytic` boundary conditions should hold the solution/data as a member variable instead? I wouldn't be surprised if a `DirichletKerrSchild` BC were added next, adding something like another 800 lines of code.

This is only there for debugging BBH BCs...once Bjorhus works, I plan to remove this. But getting it merged will make it more feasible for my students to help me try different scenarios

2021-09-29 19:18 UTC, kidder reviewed
you can squash

2021-10-11 23:44 UTC, nilsdeppe commented
@geoffrey4444 can you rebase and remove `noexcept`s. We should be good to merge this Wednesday (Larry will be back then) assuming the `noexcept`s are removed :)

2021-10-15 14:59 UTC, geoffrey4444 commented
Is there anything else you'd like me to do with this PR? I thought I got the noexcepts...

2021-10-15 16:53 UTC, kidder approved these changes

2021-10-15 16:53 UTC, merged