Print number of DataBox items on startup
sxs-collaboration/spectre pull request #3476
Opened 2021-08-31 12:53 UTC by nilsleiffischer

## Proposed changes

I found this useful to understand the size of the DataBox and the effect of things like #3248 . Let me know if you think this would be useful to merge. I enabled it only for Debug builds for now.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-09-01 16:36 UTC, nilsdeppe commented
I think this is a useful diagnostic :) I'm not sure what the "right" flag for controlling it is, but only in debug mode is certainly reasonable. Alternatively we could add an optional command line argument `--print-databox-size` or something :) In any case, given that the size of the DataBox is directly related to compile time, I think this is useful info to have easy access too.

2021-09-01 16:48 UTC, nilsleiffischer commented
Thanks! I also made the snippet print the charm type now (Array/Singleton/Group/Nodegroup).

2021-09-01 16:51 UTC, nilsdeppe approved these changes, later dismissed
:+1: yea that's useful info :D Thanks for adding this!

2021-09-08 00:17 UTC, nilsdeppe commented
@wthrowe @kidder would you mind sharing your thoughts on this? If you're both happy, please merge :)

2021-09-08 01:03 UTC, wthrowe requested changes

2021-09-08 01:03 UTC, wthrowe commented on src/Parallel/Main.hpp
> +                     tmpl::size<databox_types>::value);
`tmpl::size<...>::value` isn't a `size_t`.  Either change the format specifier or cast the value.

2021-09-08 08:44 UTC, nilsleiffischer commented on src/Parallel/Main.hpp
> +                     tmpl::size<databox_types>::value);
fixed 👍

2021-09-08 17:44 UTC, wthrowe approved these changes

2021-09-10 23:55 UTC, nilsdeppe approved these changes
@kidder this is pretty short. Would you mind looking to see if you're happy with this feature?

2021-09-11 18:31 UTC, kidder approved these changes

2021-09-11 18:31 UTC, merged