Add StrahlkorperInDifferentFrame.
sxs-collaboration/spectre pull request #3477
Opened 2021-08-31 16:49 UTC by markscheel

## Proposed changes

Given a Strahlkorper in one frame, finds a Strahlkorper in a different frame.
Will be useful for observers when the Strahlkorper is found in a non-Inertial frame but output in an Inertial frame is desired.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

Note that the clang-tidy CI test will fail because of the TOMS748 root finder issue that we still don't know how to suppress.

2021-09-01 21:56 UTC, wthrowe requested changes

2021-09-01 21:56 UTC, wthrowe commented on src/ApparentHorizons/StrahlkorperInDifferentFrame.hpp
> +    const double time) noexcept;
No `const`s for the two non-references in the hpp.

2021-09-01 21:56 UTC, wthrowe commented on src/ApparentHorizons/StrahlkorperInDifferentFrame.cpp
> +          const double theta_src = acos(get<2>(x_src.value()) / r_src);
`atan2(sqrt(x^2 + y^2), z)` (You might also like `std::hypot` to reduce typing, but that's optional.)

2021-09-03 18:41 UTC, wthrowe commented
Squash.

Clang-tidy failure looks like the usual Boost nonsense, so no problem there.

2021-09-03 18:52 UTC, markscheel commented
Squashed.  Is there any way to tell clang-tidy to ignore boost errors (without adding NOLINTS in the boost code itself)?

2021-09-03 19:27 UTC, wthrowe approved these changes
[No](https://reviews.llvm.org/D26418), although it looks like the developers have at least agreed that it is a bug since the last time I checked, so that's something.  (I recall them previously stating that this was intended behavior.)  Unfortunately, it looks like they are refusing to accept any change that fixes the problem without rewriting their entire warning suppression mechanism, so don't hold your breath.

2021-09-13 20:00 UTC, kidder approved these changes

2021-09-13 20:00 UTC, merged