Interface items
sxs-collaboration/spectre pull request #348
Opened 2017-11-10 04:30 UTC by wthrowe

## Proposed changes

Adds infrastructure for handling items and compute items for boundary data more ergonomically and uses them in the flux communication actions.  This fixes the recomputation of the magnitude of the grid normal that we were doing before.

As minor other benefits, it moves the specification of the magnitude function to the system so we're not assuming flat space anymore and adds a missing pin to DataBox.

### Types of changes:

- [X] Bugfix
- [X] New feature

### Component:

- [X] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."

### Further comments

The interface for slicing variables is suboptimal.  It would be best if the sliced version of `VarTag` were `Interface<VarTag>` (where I am eliding unimportant parameters), but I can't think of a way for the code to know whether to compute `Interface<VarTag>` by slicing or by computing it directly on the boundary (as is needed for the magnitude of the grid normal).  Instead it is presented as `Interface<Slice<VarTag>>`, which won't work in general compute items expecting a plain `VarTag` (the non-Euclidean magnitude function fetching the metric will hit this).

I think some tag has to be specialized to deal with this.  We could remove the `Slice` wrapper if we specialized the `Interface` tag (or set a flag of some kind) for each type of variables we wanted sliced, which would have to be done for each system.  Alternatively, we could specialize the compute items using them to act differently on slices.  I am leaning towards the former solution.

2017-11-10 22:18 UTC, kidder requested changes

2017-11-10 22:18 UTC, kidder commented on src/Domain/Tags.hpp
> +/// The directions connected to other elements
/// The (set of) directions to neighboring Elements

2017-11-10 22:18 UTC, kidder commented on src/Domain/Tags.hpp
> +struct InternalBoundaries : db::ComputeItemTag {
InternalDirections

2017-11-10 22:18 UTC, kidder commented on src/Domain/Tags.hpp
> +// Check if a typelist contains a value.  Should be put somewhere more general.
👍

2017-11-12 05:46 UTC, nilsdeppe requested changes

2017-11-12 05:46 UTC, nilsdeppe commented on src/Domain/Tags.hpp
> +template <typename, typename, typename>
Please name things in forward declarations. It gets really annoying trying to find the "correct" definition to figure out what the template parameters are supposed to mean.

2017-11-14 23:00 UTC, kidder requested changes

2017-11-14 23:00 UTC, kidder commented on src/DataStructures/Tags.hpp
> +// Distributed under the MIT License.
Move this into the Magnitude file

2017-11-14 23:00 UTC, kidder commented on src/Domain/Tags.hpp
> +// Check if a typelist contains a value.  Should be put somewhere more general.
stick in TMPL.hpp and in namespace brigand

2017-11-27 23:13 UTC, kidder requested changes

2017-11-27 23:13 UTC, kidder commented on tests/Unit/Domain/Test_InterfaceItems.cpp
> +      std::move(element),
fix formatting

2017-11-27 23:18 UTC, kidder commented
As for the further comments discussion of the PR: we decided to try adding a bool to the Vars that indicates whether or not to slice

2018-02-22 21:22 UTC, wthrowe commented
Except for the base infrastructure, this has been mostly rewritten.  Adding uses of interface items has been dropped from here and will be done in a separate pull request.

2018-02-22 23:59 UTC, mar-celine requested changes

2018-02-22 23:59 UTC, mar-celine commented on src/Domain/Tags.hpp
> +// Add an Interface wrapper to a tag if appropriate
expand on what appropriate means, providing a description as to how it will be used.

2018-02-22 23:59 UTC, mar-celine commented on src/Domain/Tags.hpp
> +    tmpl::bind<interface_compute_item_argument_tag, tmpl::pin<DirectionsTag>,
`interface_compute_item_argument_tag` can be made into a struct, allowing you to get rid of the bind.

2018-02-22 23:59 UTC, mar-celine commented on src/Domain/Tags.hpp
> +struct helper;
`evaluate_compute_item` <- rename to this

2018-02-22 23:59 UTC, gsb76 commented on src/Domain/Tags.hpp
> +                "Can't specify a function for an item tag");
item -> simple_item

2018-02-22 23:59 UTC, gsb76 commented on src/Domain/Tags.hpp
> +      tmpl::append<tmpl::list<DirectionsTag>, forwarded_argument_tags>;
push_front

2018-02-22 23:59 UTC, gsb76 commented on src/Domain/Tags.hpp
> +
typelist to tmpl::list

2018-02-22 23:59 UTC, gsb76 commented on tests/Unit/Domain/Test_InterfaceItems.cpp
> +  static constexpr auto function(int x) noexcept { return x + 3; }
const

2018-02-22 23:59 UTC, gsb76 commented on tests/Unit/Domain/Test_InterfaceItems.cpp
> +  static constexpr auto function(int i, double d, const ::NoCopy<1>& /*unused*/,
const everything

2018-02-22 23:59 UTC, gsb76 commented on tests/Unit/Domain/Test_InterfaceItems.cpp
> +  constexpr const size_t dim = 3;
const is not needed

2018-02-22 23:59 UTC, gsb76 commented on src/Domain/Tags.hpp
> +      auto var_it = sub_var.begin();
var_it -> sub_var_it

2018-02-23 20:57 UTC, kidder requested changes
squash

2018-02-23 20:57 UTC, kidder commented on src/Domain/Tags.hpp
> +/// preforming the slicing.  %Tags for non-sliced Variables will
performing

2018-02-23 20:57 UTC, kidder commented on src/Domain/Tags.hpp
> +/// perform the same action as the non-interface form.
as the volume tag

2018-02-23 20:57 UTC, kidder commented on tests/Unit/Domain/Test_InterfaceItems.cpp
> +using sliced_item_tag = Tags::Variables<tmpl::list<Var<3>>>;
simple_item

2018-02-23 20:57 UTC, kidder commented on tests/Unit/Domain/Test_InterfaceItems.cpp
> +using set_tag = Tags::Variables<tmpl::list<Var<0>>>;
simple_item

2018-02-27 21:16 UTC, kidder approved these changes

2018-02-27 21:17 UTC, mar-celine approved these changes

2018-02-27 23:14 UTC, nilsdeppe approved these changes

2018-02-27 23:14 UTC, merged