Start add Utilities
sxs-collaboration/spectre pull request #35
Opened 2017-06-02 01:52 UTC by nilsdeppe

2017-06-02 03:02 UTC, kidder requested changes

2017-06-02 03:02 UTC, kidder commented on src/ErrorHandling/Error.hpp
> + * \param m error message as a string, may need to use string literals
Please add a similar "However, because ... be" to the description for CASSERT

2017-06-02 03:02 UTC, kidder commented on src/Parallel/Serialize.hpp
> + */
Use either "type to serialize"   or "type to serialize as"  in both the long description and the template parameter description

2017-06-02 03:02 UTC, kidder commented on src/ErrorHandling/Assert.hpp
> +#include "Utilities/Literals.hpp"
#include Parallel/Abort.hpp"

2017-06-02 03:02 UTC, kidder commented on src/ErrorHandling/Assert.hpp
> +
#include <string>  (for std::to_string)

2017-06-02 03:02 UTC, kidder commented on src/ErrorHandling/CMakeLists.txt
alphabetical in list of sources

2017-06-02 03:02 UTC, kidder commented on src/ErrorHandling/Error.hpp
> +#include "Parallel/Parallel.hpp"
#include "Parallel/Abort.hpp"

2017-06-02 03:02 UTC, kidder commented on src/ErrorHandling/Error.hpp
> +
#include <string>  (for std::to_string)

2017-06-02 03:02 UTC, kidder commented on src/ErrorHandling/Error.hpp
> +#include "Parallel/Parallel.hpp"
I don't think you need Parallel/Parallel.hpp
#include "Utilities/Literals.hpp"

2017-06-02 03:02 UTC, kidder commented on src/Parallel/Parallel.hpp
> +// Distributed under the MIT License.
I was thinking to split out the printf function (and its helpers) into a Parallel/Print.hpp  (or Printf.hpp) and have the remaining functions in Parallel/Info.hpp.  What do you think?

2017-06-02 03:02 UTC, kidder commented on tests/Unit/TestHelpers.hpp
> +#include "Parallel/Parallel.hpp"
should be Parallel/Abort.hpp now, but that was already included above  maybe it should only be included here

2017-06-02 03:02 UTC, kidder commented on tests/Unit/TestHelpers.hpp
> +#pragma GCC diagnostic ignored "-Wparentheses"
is this needed?

2017-06-02 04:19 UTC, nilsdeppe commented on src/Parallel/Parallel.hpp
> +// Distributed under the MIT License.
Yea, that makes sense, it is rather special compared to the rest

2017-06-02 20:19 UTC, kidder requested changes

2017-06-02 20:19 UTC, kidder commented on src/ErrorHandling/Error.hpp
> + * functions where ERROR cannot be.
does not use

2017-06-02 20:19 UTC, kidder commented on src/Parallel/Parallel.hpp
> +// Distributed under the MIT License.
what do you think of renaming this file Info.hpp

2017-06-02 20:19 UTC, kidder commented on src/ErrorHandling/Assert.hpp
> + * functions where ASSERT cannot be.
does not use

2017-06-02 20:19 UTC, kidder commented on src/Parallel/Printf.hpp
> +inline const typename std::string::value_type *get_printable_type(
value_type* get_printable_type

2017-06-02 20:19 UTC, kidder commented on src/Parallel/Printf.hpp
> +  std::stringstream ss;
should we static_assert(is_streamable<T>)

2017-06-02 20:19 UTC, kidder commented on src/Parallel/Printf.hpp
> +              std::is_pointer<std::decay_t<T>>::value> * = nullptr>
why is there a decay inside is_pointer here, but not in the convertto__printable_type functions above

2017-06-02 20:19 UTC, kidder commented on src/Parallel/Printf.hpp
> +              std::is_pointer<T>::value> * = nullptr>
So the second clause prints the pointer for any pointer, and the first clause prints either the pointer to a fundamental type, or the fundamental type; so why do I need the remove_pointer ?

2017-06-02 20:32 UTC, nilsdeppe commented on src/Parallel/Printf.hpp
> +  std::stringstream ss;
I'll try it, don't see why we couldn't other than that I didn't want to include type traits until the next PR, but I have the code in on a different branch so I could pull that in no problem if you're okay with increasing the PR size

2017-06-02 20:33 UTC, nilsdeppe commented on src/Parallel/Printf.hpp
> +inline const typename std::string::value_type *get_printable_type(
This is something we can try to control with ClangFormat. Right now it moves all to one, whichever is more prominent in the file. Do you want me to see if there is an option and if it works in CF?

2017-06-02 20:43 UTC, nilsdeppe commented on src/Parallel/Printf.hpp
> +              std::is_pointer<T>::value> * = nullptr>
I'll add comments :)

2017-06-02 21:07 UTC, kidder commented on src/Parallel/Printf.hpp
> +  std::stringstream ss;
you can wait until the next PR

2017-06-02 21:07 UTC, kidder commented on src/Parallel/Printf.hpp
> +inline const typename std::string::value_type *get_printable_type(
yes, please

2017-06-03 05:19 UTC, kidder approved these changes

2017-06-03 05:20 UTC, merged