Add tutorial on events and triggers
sxs-collaboration/spectre pull request #3505
Opened 2021-09-10 21:11 UTC by wthrowe

[Rendered](http://hosting.astro.cornell.edu/~wthrowe/spectre_doc_events_and_triggers/tutorial_events_and_triggers.html)

Short user tutorial on the use of events and triggers.  Probably needs more information on a bunch of things, but it is difficult for me to judge as the code author, so please let me know what to expand on.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-09-10 23:52 UTC, nilsdeppe commented
@knelli2 @yoonso0-0 would you be willing to review this? Feel free to decline :)

2021-09-11 17:24 UTC, yoonso0-0 commented
I can help :)

2021-09-13 18:00 UTC, yoonso0-0 reviewed
Thanks for writing this up, this is concise and clear . Here I listed some points that might be helpful for new users.

2021-09-13 18:00 UTC, yoonso0-0 commented on docs/Tutorials/EventsAndTriggers.md
> +observations and minor adjustments.
I think it'd be good to clarify the meaning of the term 'observation' which we use here and after since this is one of the tutorial docs. Some phrases like 'writing/recording simulation data' would be good.

2021-09-13 18:00 UTC, yoonso0-0 commented on docs/Tutorials/EventsAndTriggers.md
> +slab in an evolution executable, and once per iteration in an elliptic
\ref Slab may help a bit

2021-09-13 18:00 UTC, yoonso0-0 commented on docs/Tutorials/EventsAndTriggers.md
> +time-stepper dense output to provide more precise control of the time
Q. What is the time-stepper dense output?

2021-09-13 18:00 UTC, yoonso0-0 commented on tests/InputFiles/ScalarWave/PlaneWave1DEventsAndTriggersExample.yaml
> +# [multiple_events]
It'd be more clear if the line `EventsAndTriggers:` is included as well.

2021-09-13 18:00 UTC, yoonso0-0 commented on docs/Tutorials/EventsAndTriggers.md
> +
It would help a lot if there is a description on this snippet based on the contents previously introduced -- which one stands for an event, which one stands for a trigger, and which lines are options for an event or a trigger, etc.

2021-09-13 18:00 UTC, yoonso0-0 commented on docs/Tutorials/EventsAndTriggers.md
> +some task, frequently an observation.  With the exception of the \ref
Can you provide some concrete examples of event in casual words? Like 'write data to a file',  'record error norms', or 'exit program'. (I cannot think of other good examples for now)

2021-09-13 20:21 UTC, knelli2 requested changes
I personally like having as many (useful) links as possible in documentation because learning code is a very non-linear process. When learning about events and triggers, I definitely didn't have a good grasp on the parallelization infrastructure. So rather than trying to look up "algorithm" myself, I find it very useful having these large topics embedded in *all* tutorials, regardless of the when someone "should" know something. Something to think about for the future, but I wanted to address it here as well.

Currently this is set up to be a user tutorial, which I think is good. However, I think we also need a dev guide tutorial for this as well because I would have several other questions about events and triggers if I wanted to actually write one or the other, such as:
- What is the general structure for writing a new event/trigger? Are there protocols?
- How do I add them in executables? What is factory creation?
- Do all events/triggers need to be constructable by options?
- Where are evens/triggers actually run? On the elements? Their own chare?

However, just for *using* existing events and triggers in input files and existing executables, I think this is good.

2021-09-13 20:21 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +effects on the flow of the algorithm, but is primarily used for
\ref dev_guide_parallelization_core_algorithm algorithm

2021-09-13 20:21 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +observations and minor adjustments.
I think a \ref would be good here to the base for an observer (if there is one).

2021-09-13 20:21 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +Events::ChangeSlabSize "ChangeSlabSize".)  In most cases, however, their
This was confusing upon a first read. If I understood this correctly, clarify that by "cannot have direct effects on the algorithm" you mean that essentially events can't add actions to the pdal which is specified in the metavariables. But you can (potentially) change things in the databox or cache (like the slab size).

2021-09-13 20:21 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +the entire domain at each check.
This sentence was a bit wordy and confusing, specifically the phrasing of "independent of element-specific state".

2021-09-13 20:21 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +time-stepper dense output to provide more precise control of the time
A \ref would be helpful here as well.

2021-09-13 20:21 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +### What is an event?
I'm personally not a fan of the "question and answer" type of documentation. Also I don't think it's used anywhere else in spectre (if it is used, it's sparse). For consistency I think we should keep it as
- Event
- Trigger
- Dense Trigger
- Input File Syntax

2021-09-13 20:21 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +but we recommend always using the expanded form for consistency.
If you don't want users to use this format for triggers/events with no options, then don't put it in. It'll only confuse them more. What about this for this part:
```suggestion
If an event and trigger both took no options, the recommended syntax is still

\snippet PlaneWave1DEventsAndTriggersExample.yaml no_arguments
```

2021-09-16 20:40 UTC, wthrowe reviewed
> * What is the general structure for writing a new event/trigger? Are there protocols?

As with most things, copy the structure of an existing one.  (They also have abstract base classes.)

> * How do I add them in executables? What is factory creation?

Added a link.

> * Do all events/triggers need to be constructable by options?

That really belongs in the option parsing documentation, not here.  That documentation is, admittedly, out-of-date on the subject.

> * Where are events/triggers actually run? On the elements? Their own chare?

Added some text.

2021-09-16 20:40 UTC, wthrowe commented on docs/Tutorials/EventsAndTriggers.md
> +observations and minor adjustments.
I don't think we have anything appropriate to point to here.  There's a tutorial on visualization, but that's mostly focused on things like ParaView, and we have a dev guide on the really low-level observation code, but you probably don't even need to understand that if you are writing an observer.  (I have added some words to the text here.)

2021-09-16 20:40 UTC, wthrowe commented on docs/Tutorials/EventsAndTriggers.md
> +some task, frequently an observation.  With the exception of the \ref
This is sort of what I was going for with the rest of the paragraph, but it is not ordered in the way that makes sense to think about the concepts, so I'll redo that.

2021-09-16 20:40 UTC, wthrowe commented on docs/Tutorials/EventsAndTriggers.md
> +Events::ChangeSlabSize "ChangeSlabSize".)  In most cases, however, their
Kind of the opposite, actually.  They can't change the DataBox.  I guess they can technically do cache updates, but doing those from an array element seems generally unlikely to work.  They cannot do anything except send messages.  Hopefully the reword here helps.

2021-09-16 20:40 UTC, wthrowe commented on docs/Tutorials/EventsAndTriggers.md
> +the entire domain at each check.
Reversed the clauses.  Any better?

2021-09-16 20:40 UTC, wthrowe commented on docs/Tutorials/EventsAndTriggers.md
> +time-stepper dense output to provide more precise control of the time
Added "(i.e., interpolation or extrapolation)", but I don't think we have any documentation on this topic.

2021-09-16 20:40 UTC, wthrowe commented on docs/Tutorials/EventsAndTriggers.md
> +but we recommend always using the expanded form for consistency.
I was trying to teach something beyond how to cut and paste.  If you think it is really a bad idea I can leave the whole thing out, but I don't see any reason to mention this case if we're not using to to explain something.

2021-09-16 20:40 UTC, wthrowe commented on docs/Tutorials/EventsAndTriggers.md
> +
Done, but unfortunately I can't link one of the events because of doxygen limitations.

2021-09-17 16:39 UTC, knelli2 reviewed
Just a few nitpicks which you can choose to change or not.

Other than that I'm happy with this :)

2021-09-17 16:39 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +"Completion" event), does not directly affect the execution of the
[nitpick] No comma after the parentheses.

2021-09-17 16:39 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +state.  Others, (such as \ref Events::ChangeSlabSize "ChangeSlabSize")
[nitpck] No comma

2021-09-17 16:39 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +but we recommend always using the expanded form for consistency.
This was more of a nitpick so I think it's ok as is.

2021-09-17 16:39 UTC, knelli2 commented on docs/Tutorials/EventsAndTriggers.md
> +events to run, or not.  Triggers must give a consistent result over
[nitpick] "At each check a trigger may fire, causing its associated events to run or not."

2021-09-19 22:16 UTC, yoonso0-0 commented
Fixup LGTM :)

2021-09-21 20:07 UTC, wthrowe commented
Squashed, including the grammar nits.

2021-09-21 21:26 UTC, knelli2 approved these changes

2021-09-21 21:28 UTC, yoonso0-0 approved these changes

2021-09-24 04:24 UTC, nilsdeppe commented
Does this fix #1452?

2021-09-24 06:17 UTC, knelli2 commented
Partially? See one of my previous comments about it and @wthrowe's response.

Basically I think this is a good user tutorial, giving enough background info on events and triggers that users can modify input files without just copy/pasting blindly. However, if this were a dev guide, I'd be very lost on how everything actually works internally, how to write new ones (without just copy/pasting), and how in general these fit into the larger framework (corresponding actions and what they do).

2021-09-28 01:37 UTC, kidder approved these changes

2021-09-28 01:37 UTC, merged