Add reconstructor base class to advection subcell
sxs-collaboration/spectre pull request #3532
Opened 2021-09-20 18:59 UTC by yoonso0-0

## Proposed changes

First commit is from #3530 (not strictly dependent but because lines that changed are close).
* A minor fix on reconstruction namespace documentation
* Add reconstructor base class, its required structures, and option tag to advection subcell.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-09-20 21:44 UTC, nilsdeppe requested changes
You  can squash immediately :)

2021-09-20 21:44 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Reconstruct.hpp
> + * lower side of each cells, while the `reconstructed_lower_side_of_face_vars`
"each" -> "the" to get the English better

2021-09-21 01:05 UTC, yoonso0-0 commented
@nilsdeppe Added a tiny test with the fixup (see the third commit).

2021-09-21 17:09 UTC, nilsdeppe submitted a review, later dismissed

2021-09-21 17:10 UTC, nilsdeppe commented
@yoonso0-0 this is failing CI

2021-09-22 16:10 UTC, yoonso0-0 commented
Dropped the part adding base class to global cache, since there is no derived class now and that makes CI fails.

2021-09-22 21:05 UTC, yoonso0-0 commented
@nilsdeppe It seems I should add MC implementation in this PR to hit the code patch for abstract class.

2021-09-22 21:47 UTC, nilsdeppe commented
I wouldn't worry about that. What you have here is fine, we can merge anyway once @kidder has taken a look. I'd suggest doing the MC reconstruction in a separate PR :)

2021-09-22 23:18 UTC, nilsdeppe approved these changes

2021-09-24 20:18 UTC, kidder approved these changes

2021-09-24 20:18 UTC, merged