Most remaining evolution cleanups from 2779
sxs-collaboration/spectre pull request #3533
Opened 2021-09-20 22:36 UTC by nilsdeppe

## Proposed changes

Does most of the cleanups listed in #2779. The big remaining ones are domain-related, which will likely involve many long debates that I don't have time for. 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-09-21 20:16 UTC, wthrowe requested changes
The test failure is just the ongoing coveralls problem.

2021-09-21 20:16 UTC, wthrowe commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
>  #include "Domain/Protocols/Metavariables.hpp"
The self-start test is fixed now that #3523 was merged.

2021-09-23 01:06 UTC, nilsdeppe commented
rebased and added a commit (combined with the previous one whose message you commented on) to remove the action completely :)

2021-09-23 21:58 UTC, kidder approved these changes

2021-09-24 21:02 UTC, wthrowe approved these changes

2021-09-24 21:03 UTC, merged