Add ghost data routines to advection subcell
sxs-collaboration/spectre pull request #3542
Opened 2021-09-22 17:47 UTC by yoonso0-0

## Proposed changes

Ghost data - related classes for sending out ghost data for reconstruction.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-09-27 18:08 UTC, nilsdeppe requested changes
You can squash immediately

2021-09-27 18:08 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/GhostData.hpp
> +#include "Utilities/GenerateInstantiations.hpp"
you never need `GenerateInstantiations.hpp` in a header file

2021-09-27 18:08 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/GhostData.hpp
> +}  // namespace Tags
need forward decl of `Mesh`

2021-09-27 18:08 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/GhostData.cpp
> +#include "Utilities/GenerateInstantiations.hpp"
include `NumericalAlgorithms/Spectral/Mesh.hpp`

2021-09-27 21:28 UTC, yoonso0-0 commented
Fixed!

2021-09-28 15:26 UTC, nilsdeppe approved these changes

2021-09-28 15:26 UTC, merged