Add compute_spacetime_metric
sxs-collaboration/spectre pull request #355
Opened 2017-11-14 17:51 UTC by osheamonn

We need a lot of these functions which calculate GR quantities. This PR is just to add one such function so that we can decide on directory placement and things like that. I'll add the rest after we've settled on this one.

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ x] New feature

### Component:

- [ x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."

### Further comments

2017-11-14 19:14 UTC, wthrowe commented on src/PointwiseFunctions/GrTensorFunctions/CMakeLists.txt
> +        ComputeSpacetimeQuantities.cpp
...

2017-11-14 19:14 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/GrTensorFunctions/Test_ComputeSpacetimeQuantities.cpp
> +auto make_lapse(const DataType& data) {
All the `data`s in this test are not actually data in our usual sense, but just structure information.

2017-11-14 19:14 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/GrTensorFunctions/Test_ComputeSpacetimeQuantities.cpp
> +  const DataVector dv{2};
I'm guessing you meant `dv(2)` here.

2017-11-14 21:22 UTC, kidder requested changes

2017-11-14 21:22 UTC, kidder commented on src/PointwiseFunctions/CMakeLists.txt
> +add_subdirectory(GrTensorFunctions)
GrTensorFunctions -> GeneralRelativity

2017-11-14 21:22 UTC, kidder commented on src/PointwiseFunctions/GrTensorFunctions/CMakeLists.txt
> +set(library GrTensorFunctions)
GrTensorFunctions -> GeneralRelativity

2017-11-14 21:22 UTC, kidder commented on src/PointwiseFunctions/GrTensorFunctions/ComputeSpacetimeQuantities.hpp
> +* \ingroup GrTensorFunctions
\ingroup GeneralRelativityGroup

2017-11-14 21:22 UTC, kidder commented on src/PointwiseFunctions/GrTensorFunctions/ComputeSpacetimeQuantities.hpp
> +* \ingroup GrTensorFunctions
and define the group

2017-11-14 21:22 UTC, kidder commented on src/PointwiseFunctions/GrTensorFunctions/ComputeSpacetimeQuantities.hpp
> +    const tnsr::ii<DataType, Dim, Fr>& g) noexcept;
spatial_metric

2017-11-14 21:22 UTC, kidder commented on tests/Unit/PointwiseFunctions/GrTensorFunctions/Test_ComputeSpacetimeQuantities.cpp
> +  CHECK(psi.get(3, 3) == approx(9.));
psi(2,3) is not feeling loved

2017-11-16 19:28 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Test_ComputeSpacetimeQuantities.cpp
> +auto make_lapse(const DataType& datavector_for_size) {
These are also called with DataType=double, in which case `datavector_for_size` is a very strange name.  `make_with_value` calls the argument `input`, which is also not great.  I suggest something like `structure`.

2017-11-16 21:58 UTC, kidder requested changes

2017-11-16 21:58 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +  spacetime_metric.get(0, 0) = -lapse.get() * lapse.get();
<> instead of () when values are known (3 times)

2017-11-16 21:58 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +#undef INSTANTIATE
#undef FRAME

2017-11-17 02:40 UTC, kidder approved these changes

2017-11-17 04:20 UTC, nilsdeppe approved these changes

2017-11-17 04:20 UTC, merged