Update dox for INTERFACE, PUBLIC, PRIVATE libraries.
sxs-collaboration/spectre pull request #3562
Opened 2021-09-29 20:02 UTC by markscheel

## Proposed changes

The dox for how to make CMakeLists.txt did not distinguish between INTERFACE, PRIVATE, and PUBLIC libraries. Now the dox mentions these.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-09-29 21:31 UTC, nilsleiffischer requested changes

2021-09-29 21:31 UTC, nilsleiffischer commented on docs/DevGuide/BuildSystem.md
> +least one `.hpp` file and at least one `.cpp` file in `LIBRARY`.
I suggest the following additional sentence:

> Note that a library also counts as being used in a `.cpp` file if the corresponding `.hpp` file includes it.

You could also add something like this:

> In other words, list a dependency as `PRIVATE` if it is only needed to compile the library. List a dependency as `INTERFACE` if it is _not_ needed to compile the library, but only for including headers. List a dependency as `PUBLIC` if it is needed for both.

2021-10-01 12:13 UTC, nilsleiffischer approved these changes, later dismissed
squash

2021-10-08 20:26 UTC, wthrowe requested changes

2021-10-08 20:26 UTC, wthrowe commented on docs/DevGuide/BuildSystem.md
> +  YET_ANOTHER_LIBRARY
Library names are CamelCase.  It's confusing enough having syntax and "variables" to be replaced both in all-caps in this section, and I think we can use the standard capitalization here and still be clear.

2021-10-08 20:26 UTC, wthrowe commented on docs/DevGuide/BuildSystem.md
> +least one `.hpp` file in `LIBRARY` but never used in any `.cpp` files
The library was called `LIB` above.

2021-10-08 20:26 UTC, wthrowe commented on docs/DevGuide/BuildSystem.md
> +Note that a library counts as being "used in a .cpp file" if the
In the text above this point things like `.cpp` and `PRIVATE` are in tics.  Make this part consistent with that.

2021-10-13 17:35 UTC, wthrowe commented
Squash.

2021-10-14 01:01 UTC, nilsleiffischer submitted a review, later dismissed

2021-10-14 03:09 UTC, markscheel commented
squashed

2021-10-14 17:41 UTC, wthrowe approved these changes

2021-10-14 20:42 UTC, nilsvu approved these changes

2021-10-14 20:42 UTC, merged