Add Ricci Scalar compute tags to EvolveGeneralizedHarmonic.hpp
sxs-collaboration/spectre pull request #3576
Opened 2021-10-05 04:24 UTC by MarloMo

## Proposed changes

Adding the Ricci scalar compute tags to `EvolveGeneralizedHarmonic.hpp` that computes the Min and Max Ricci scalar of a Strahlkorper. This PR also adds arguments tags that are dependent on calculating the Ricci scalar quantities. 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-10-08 22:51 UTC, geoffrey4444 approved these changes, later dismissed

2021-10-10 08:56 UTC, nilsleiffischer approved these changes, later dismissed

2021-10-10 08:58 UTC, nilsvu commented
@markscheel could you take an expert-look at this one? :)

2021-10-20 21:58 UTC, markscheel requested changes

2021-10-20 21:58 UTC, markscheel commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                             tmpl::size_t<3>, frame>>;
I don't think you should need this last tag.

2021-10-20 21:58 UTC, markscheel commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                   StrahlkorperTags::RicciScalarCompute<frame>>,
This Tag should be one that computes the Ricci scalar from the Ricci tensor by contracting with the metric (the Ricci tensor is already available, so why recompute it), but I think RicciScalarCompute uses derivs of Christoffel.

2021-10-25 22:13 UTC, markscheel commented
@MarloMo I took another look at this; I was confused by names and frames.  Just one thing, which is changing everything to Inertial in interpolator_source_vars.

2021-10-26 03:08 UTC, MarloMo commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                             tmpl::size_t<3>, frame>>;
Sounds good, so I'm okay to leave this as is? I tried to compile without it but I kept getting an error that said it was required if I was trying to call the Ricci scalar tag.

2021-10-26 03:11 UTC, MarloMo commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                   StrahlkorperTags::RicciScalarCompute<frame>>,
I'm not sure. @geoffrey4444, would you be able to clarify if this computes (2D) or (3D)?

2021-10-26 14:24 UTC, geoffrey4444 commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                   StrahlkorperTags::RicciScalarCompute<frame>>,
Yes, it's 2D

2021-10-26 23:09 UTC, markscheel commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                             tmpl::size_t<3>, frame>>;
Yes, please leave this as is, except please change frame to Frame::Inertial in interpolator_source_vars.  Let me know if you get an error if you do that.

2021-10-26 23:09 UTC, markscheel commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                   StrahlkorperTags::RicciScalarCompute<frame>>,
Ok, sounds good.

2021-10-27 15:27 UTC, MarloMo commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                             tmpl::size_t<3>, frame>>;
Okay, that compiled

2021-10-27 20:59 UTC, markscheel submitted a review, later dismissed
Please squash.

2021-10-28 15:17 UTC, MarloMo commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicWithHorizon.hpp
> +                             tmpl::size_t<3>, frame>>;
Why wouldn't the tag work for other frames? @markscheel

2021-10-28 16:46 UTC, markscheel approved these changes

2021-10-29 14:16 UTC, geoffrey4444 approved these changes

2021-10-29 14:24 UTC, nilsvu approved these changes

2021-10-29 14:24 UTC, merged