Add advection velocity field to FD cell and face tensor in advection subcell
sxs-collaboration/spectre pull request #3578
Opened 2021-10-05 15:40 UTC by yoonso0-0

## Proposed changes

Add velocity field (background field) as `Inactive<>` and `OnSubcellFaces<>` tags for using subcell.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-10-12 00:01 UTC, nilsdeppe requested changes

2021-10-12 00:01 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/VelocityAtFace.hpp
> +namespace Initialization {
you can write all this as `Initialization::subcell::ScalarAdvection` but please do this as `ScalarAdvection::subcell` (you can add `Initialization` at the end if you want). This is system-specific code and should go in the system's namespace. The GR tags are somewhat special because GRMHD and RelEuler ultimately need to share them (along with every other relativistic system, eg scalar wave if that uses subcell)

2021-10-12 00:01 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/VelocityAtFace.hpp
> + * \note This action relies on the `SetupDataBox` aggregated initialization
I'm not sure that the documentation is correct. The `SetupDataBox` would need `using simple_tags` and `using compute_tags` type aliases. You probably copied this from the `GrTagsForHydro`. I think it should read

```cpp
 * This mutator is meant to be used with `Initialization::Actions::AddSimpleTags`, 
 * which uses `Actions::SetupDataBox` the `SetupDataBox` aggregated...
```

2021-10-12 00:01 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/VelocityAtFace.hpp
> +    ::ScalarAdvection::Tags::VelocityFieldCompute<Dim>::function(
maybe add a comment: `// Note: This assumes the velocity field is the hard-coded one in the compute tag`?

2021-10-12 00:01 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/VelocityAtFace.hpp
> +namespace Initialization {
you use the tags here, so you need to include them, I think

2021-10-12 00:01 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_VelocityAtFace.cpp
> +  // apply the action
`action` -> `mutator`

2021-10-12 00:01 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_VelocityAtFace.cpp
> +const size_t num_pts = 5;
move into the `test()` function. While not technically a global variable, it's better to have variables scoped inside functions. Makes the code easier to read :)

2021-10-19 19:32 UTC, nilsdeppe reviewed
LGTM, please squash.

In the future, can you please have fixup commits start with `fixup` instead of `[fixup]` as per our contributing guide: https://spectre-code.org/contributing_to_spectre.html

2021-10-19 20:26 UTC, yoonso0-0 commented
Sure, I will note it. Thanks for the review :)

2021-10-20 00:03 UTC, nilsdeppe approved these changes

2021-10-20 16:16 UTC, merged