Make pup NOLINTs consistent
sxs-collaboration/spectre pull request #3582
Opened 2021-10-06 09:58 UTC by nilsleiffischer

This will hopefully reduce some noise in PR reviews.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-10-08 20:59 UTC, wthrowe submitted a review, later dismissed
Needs a rebase.

2021-10-08 21:09 UTC, nilsvu commented
@wthrowe done

2021-10-08 21:33 UTC, wthrowe submitted a review, later dismissed

2021-10-10 13:47 UTC, nikwit requested changes
some duplicates

2021-10-10 13:47 UTC, nikwit commented on src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DhGaugeParameters.hpp
>    // clang-tidy: google-runtime-references
delete line

2021-10-10 13:47 UTC, nikwit commented on src/ParallelAlgorithms/EventsAndTriggers/LogicalTriggers.hpp
>    // clang-tidy: google-runtime-references
delete

2021-10-10 13:47 UTC, nikwit commented on src/ParallelAlgorithms/EventsAndTriggers/LogicalTriggers.hpp
>    // clang-tidy: google-runtime-references
delete

2021-10-10 13:47 UTC, nikwit commented on src/Utilities/TaggedTuple.hpp
>    // clang-tidy: runtime-references
delete

2021-10-10 17:35 UTC, nilsleiffischer commented
Fixed, thanks @nikwit 👍

2021-10-10 17:51 UTC, nikwit reviewed
Looks good

2021-10-10 17:52 UTC, nikwit approved these changes

2021-10-12 18:49 UTC, wthrowe approved these changes
Clang-tidy failures are Boost.

2021-10-12 18:49 UTC, merged