Add comparison operator for Direction and ElementId
sxs-collaboration/spectre pull request #3585
Opened 2021-10-07 10:20 UTC by nilsleiffischer

## Proposed changes

This is useful for optimizations of the elliptic code that I have on a branch right now. Also probably for other things.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-10-11 23:41 UTC, nilsdeppe requested changes
Overall LGTM, couple minor things. Please squash and rebase immediately

2021-10-11 23:41 UTC, nilsdeppe commented on src/Domain/Structure/Direction.hpp
> +inline bool operator>(const Direction<VolumeDim>& lhs,
templates don't need to be marked as `inline`, they have the linkage already

2021-10-11 23:41 UTC, nilsdeppe commented on src/Domain/Structure/Direction.hpp
> +bool operator<(const Direction<VolumeDim>& lhs,
Maybe document (either dox or C++) what the comparison is and that it's arbitrary without some deep motivation behind it? I worry that in 2 years we'll look at this and ponder why it's comparing in this specific way :)

2021-10-11 23:41 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.hpp
> +bool operator<(const ElementId<VolumeDim>& lhs,
Maybe document (either dox or C++) what the comparison is and that it's arbitrary without some deep motivation behind it? I worry that in 2 years we'll look at this and ponder why it's comparing in this specific way :)

2021-10-11 23:41 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.hpp
> +inline bool operator>(const ElementId<VolumeDim>& lhs,
don't need `inline` on templates (below too)

2021-10-12 07:30 UTC, nilsvu commented
Done, thanks @nilsdeppe!

2021-10-12 17:23 UTC, nilsdeppe approved these changes

2021-10-18 19:30 UTC, kidder approved these changes

2021-10-18 19:30 UTC, merged