Add NeighborPackagedData to advection subcell
sxs-collaboration/spectre pull request #3591
Opened 2021-10-11 18:33 UTC by yoonso0-0

## Proposed changes

Only the last commit is the net change.

Depends on  : 
- [x] #3546 
- [x] #3578 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-10-11 21:09 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_NeighborPackagedData.cpp
> +  // Q. do we need to go over all possible types of reconstructor / BCrr?
Would it be required for this test code to go through all possible combinations of reconstruction and boundary corrections?

2021-11-01 22:10 UTC, nilsdeppe requested changes

2021-11-01 22:10 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/NeighborPackagedData.hpp
> +        // U, NormalDotFlux<U>, AbsCharSpeed
doesn't this depend on the Riemann solver? Eg HLL doesn't use AbsCharSpeed, right? I'm somewhat worried that these comments will easily be incorrect since they are trying to solidify a derived quantity that's controlled elsewhere

2021-11-01 22:10 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/NeighborPackagedData.hpp
> +        Variables<dg_package_field_tags> packaged_data{0};
I think we can just default construct these two variables: `{}`. Let's do that. I realize GRMHD doesn't and you just copied it. That was poorly written code on my end, I think.

2021-11-01 22:10 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarAdvection/Subcell/NeighborPackagedData.hpp
> +          } else {
There's a lot of duplicated code between the 1d and 2d cases. Why not share all that? It seems like there's really only a couple lines that differ.

2021-11-01 22:10 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_NeighborPackagedData.cpp
> +  // Q. do we need to go over all possible types of reconstructor / BCrr?
In theory that would be nice, but I suspect it'll make the test take a long time, especially as the number of each of those increases :) I'd say just do 1 combination and that's fine. If you really want to be thorough, probably Rusanov+HLL, and then one reconstruction scheme :shrug:

2021-11-01 22:10 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_NeighborPackagedData.cpp
> +  using reconstruction_used_for_test = typename fd::MonotisedCentral<Dim>;
86 & 87 do camel case. These are used as classes rather than template metaprogramming variables :)

2021-11-01 22:10 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_NeighborPackagedData.cpp
> +    // revert normal vector
`revert` -> `reverse`

2021-11-03 17:55 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_NeighborPackagedData.cpp
> +  // Q. do we need to go over all possible types of reconstructor / BCrr?
Okay, I'll only use the simplest case (MC + Rusanov) here.

2021-11-03 17:56 UTC, yoonso0-0 commented on src/Evolution/Systems/ScalarAdvection/Subcell/NeighborPackagedData.hpp
> +        // U, NormalDotFlux<U>, AbsCharSpeed
Yeah, my bad :(  I forgot to delete these temporary help comments.

2021-11-03 18:18 UTC, yoonso0-0 commented
Rebased and pushed fixup :)

2021-11-03 19:10 UTC, nilsdeppe commented
LGTM, please squash

2021-11-03 20:10 UTC, yoonso0-0 commented
Squashed - thanks for the review :)

2021-11-03 22:47 UTC, nilsdeppe approved these changes

2021-11-04 05:21 UTC, merged