Derive advection solutions from the new ID base class
sxs-collaboration/spectre pull request #3600
Opened 2021-10-16 00:42 UTC by yoonso0-0

## Proposed changes

The last commit is the net change.

Derive analytic solutions of the ScalarAdvection system from the new initial data base class. All available solutions are listed in `PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Factory.hpp` with a type alias named `all_analytic_solutions` templated with dimension. Rather than listing all the types of analytic data or solution and their header files, it will be sufficient to include corresponding Factory.hpp and add its type aliases to factory classes in `EvolutionMetavars`.

Dependent on 
- [ ] #3599 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-10-19 22:04 UTC, nilsdeppe requested changes

2021-10-19 22:04 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Factory.hpp
> +
include `<cstddef>`

2021-10-19 22:04 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Krivodonova.hpp
> -  // NOLINTNEXTLINE(google-runtime-references)
please keep the `pup` you previously had. That's the more modern style we want to use

2021-10-19 22:04 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Krivodonova.hpp
> +  explicit Krivodonova(CkMigrateMessage* msg) : InitialData(msg) {}
can you move the definition of the migration constructor to the cpp file?

2021-10-19 22:04 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Kuzmin.hpp
> -  void pup(PUP::er& p);
keep old pup

2021-10-19 22:04 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Kuzmin.hpp
> +  explicit Kuzmin(CkMigrateMessage* msg) : InitialData(msg) {}
move to cpp?

2021-10-19 22:04 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Sinusoid.hpp
> -  void pup(PUP::er& p);
keep old pup

2021-10-19 22:04 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Sinusoid.hpp
> +  explicit Sinusoid(CkMigrateMessage* msg) : InitialData(msg) {}
move to cpp

2021-10-19 22:04 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Sinusoid.hpp
>  };
Can you add a test for each, something like
```cpp
const std::unique_ptr<InitialData> id = std::make_unique<Sinusoid>();
const std::unique_ptr<InitialData> deserialized_id = serialize_and_deserialize(id);
CHECK(dynamic_cast<Sinusoid*>(deserialized_id.get()) != nullptr);
```
but maybe with better variable names :) This is exactly the thing you want to have working, so I think it's important to test that.

2021-10-20 00:08 UTC, yoonso0-0 commented on src/PointwiseFunctions/AnalyticSolutions/ScalarAdvection/Sinusoid.hpp
>  };
Yep. I had a vague feeling that I missed some test that I did include for subcell reconstruction :joy:

2021-11-09 00:41 UTC, nilsdeppe approved these changes

2021-11-09 00:42 UTC, nilsdeppe commented
@nilsleiffischer did you want to look at this as well?

2021-11-09 07:57 UTC, nilsleiffischer approved these changes

2021-11-09 07:57 UTC, merged

2021-11-09 16:28 UTC, yoonso0-0 commented
Thanks for the review!