Remove composition time dep
sxs-collaboration/spectre pull request #3601
Opened 2021-10-16 03:31 UTC by knelli2

## Proposed changes

The previous composition time dependence was too general and only instantiated for specific compositions. This removes the old composition and creates two new explicit compositions. One for a composition between CubicScale and UniformRotationAboutZAxis and another for two UniformTranslations of the same dimension.

### Upgrade instructions

If you were creating a `Composition` from options with cubic scale and uniform rotation, just change the name like so:
```
Composition:  -> CompositionCubicScaleAndUniformRotationAboutZAxis:
```
You shouldn't need to change any of the underlying options.

If you were creating a `Composition` from options with two uniform translations, the way to do it now is
```
CompositionUniformTranslation:
  UniformTranslation:
    UniformTranslation:
      InitialTime: 1.3
      InitialExpirationDeltaT: 2.5
      Velocity: [0.5]
      FunctionOfTimeName: Translation
  UniformTranslation1:
    UniformTranslation:
      InitialTime: 1.3
      InitialExpirationDeltaT: 2.5
      Velocity: [1.5]
      FunctionOfTimeName: Translation1
```
Notice the `UniformTranslation1` as the second field. This is to make the uniform translations unique in the eyes of the factory.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-10-22 20:30 UTC, wthrowe requested changes

2021-10-22 20:30 UTC, wthrowe commented on src/Domain/FunctionsOfTime/CombineFunctionsOfTime.hpp
> +using FoTMap = std::unordered_map<std::string, std::unique_ptr<FunctionOfTime>>;
You need `<string>` in the header.

2021-10-22 20:30 UTC, wthrowe commented on src/Domain/FunctionsOfTime/CombineFunctionsOfTime.hpp
> +FoTMap combine_functions_of_time(const FoTMap& map_1, const FoTMap& map_2);
Is this worth having instead of using this snippet?
```c++
auto result = clone_unique_ptrs(map_1);
result.merge(clone_unique_ptrs(map_2));
```
Particularly as it looks like `map_1` and `map_2` are usually temporaries, so you can skip the `clone_unique_ptrs`?

2021-10-22 20:30 UTC, wthrowe commented on src/Domain/Creators/TimeDependence/CompositionCubicScaleAndUniformRotationAboutZAxis.hpp
> +  //               typename UniformRotationAboutZAxis<MeshDim>::maps_list>>>;
Remove.

2021-10-22 20:30 UTC, wthrowe commented on src/Domain/Creators/TimeDependence/CompositionUniformTranslation.hpp
> +  // static_assert(std::is_same_v<CoordMap, int> , "Hello I failed.");
Remove.

2021-10-22 20:30 UTC, wthrowe commented on src/Domain/Creators/TimeDependence/CompositionUniformTranslation.hpp
> +      OptionTags::TimeDependenceCompositionTag<UniformTranslation<MeshDim>, 1>>;
What would happen if you parsed these as a `std::pair`?  It might make the input file syntax less awkward.

2021-10-22 20:30 UTC, wthrowe commented on src/Domain/Creators/TimeDependence/OptionTags.hpp
> +  using type = std::unique_ptr<TimeDependence<TimeDep::mesh_dim>>;
Can you parse this as a concrete `TimeDep`?  It would require changing the places that use this, so it might not be possible, but it would be nice to enforce the correct type.

2021-10-22 20:30 UTC, wthrowe commented on src/Domain/Creators/TimeDependence/CompositionUniformTranslation.cpp
> +          dynamic_cast<UniformTranslation<MeshDim>&>(*uniform_translation0)
(Random occurrence.) It looks like in the current implementation these casts can fail if the input file is bad.  That should be caught and reported, preferably as a `PARSE_ERROR`.

2021-10-22 20:30 UTC, wthrowe commented on tests/Unit/Domain/Creators/TimeDependence/Test_CompositionCubicScaleAndUniformRotationAboutZAxis.cpp
> +        expected_block_maps[i]->operator()(grid_coords_dv,
(Optional) You might aesthetically prefer `(*foo)(...)` over `foo->operator()(...)`.

2021-10-25 23:17 UTC, knelli2 commented on src/Domain/FunctionsOfTime/CombineFunctionsOfTime.hpp
> +FoTMap combine_functions_of_time(const FoTMap& map_1, const FoTMap& map_2);
I was unaware of the `merge` member for unordered maps. That is sufficient. I put in a revert commit to get rid of these files as they were no longer needed.

2021-10-25 23:19 UTC, knelli2 commented on src/Domain/Creators/TimeDependence/OptionTags.hpp
> +  using type = std::unique_ptr<TimeDependence<TimeDep::mesh_dim>>;
Instead I just parse these as the actual time dependences that will be passed to the composition (i.e. `UniformTranslation`s for the CompositionUniformTranslation). This makes the the input file syntax look nicer as well.

2021-10-25 23:20 UTC, knelli2 commented on src/Domain/Creators/TimeDependence/CompositionUniformTranslation.hpp
> +      OptionTags::TimeDependenceCompositionTag<UniformTranslation<MeshDim>, 1>>;
See comment below.

2021-10-25 23:21 UTC, knelli2 commented on src/Domain/Creators/TimeDependence/CompositionUniformTranslation.cpp
> +          dynamic_cast<UniformTranslation<MeshDim>&>(*uniform_translation0)
This is taken care of by passing derived class of `TimeDependences`.

2021-10-29 17:27 UTC, wthrowe reviewed
Looks good.  Squash.

2021-11-04 18:21 UTC, knelli2 commented
After discussing with @nilsleiffischer, I found a better way to change the Composition time dependence without having to completely remove it. Thus this PR is no longer needed.

2021-11-04 18:21 UTC, closed without merging