Move YlmSpherepack to NumericalAlgorithms/SphericalHarmonics.
sxs-collaboration/spectre pull request #3617
Opened 2021-10-22 13:46 UTC by markscheel

This should fix #3573, and it does some of #3381

Just moves code around, changing nothing else except for where needed in CMakeLists and includes.

More code can be moved in the future, not sure if in this PR or subsequent PRs. (For example, maybe Strahlkorper can be moved too)

### Upgrade instructions

YlmSpherepack is now in the library NumericalAlgorithms/SphericalHarmonics.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-10-22 20:41 UTC, wthrowe requested changes

2021-10-22 20:41 UTC, wthrowe commented on src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp
> +#include "NumericalAlgorithms/SphericalHarmonics/YlmSpherepackHelper.hpp"
Alphabetize.

2021-10-22 20:41 UTC, wthrowe commented on src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
> +  SPHEREPACK
And `Utilities`, I think.

2021-10-22 22:31 UTC, nilsvu requested changes
Thanks for organizing these files 👍

2021-10-22 22:31 UTC, nilsvu commented on src/Domain/CoordinateMaps/TimeDependent/Shape.cpp
>  #include "ApparentHorizons/TagsTypeAliases.hpp"
Can this include be deleted? Same in the hpp. Then the lib is independent of ApparentHorizons.

2021-10-25 21:36 UTC, markscheel commented on src/Domain/CoordinateMaps/TimeDependent/Shape.cpp
>  #include "ApparentHorizons/TagsTypeAliases.hpp"
Why yes it can be deleted; seems to not be used (not sure why it was there in the first place).

2021-10-25 21:58 UTC, nilsvu submitted a review, later dismissed
Squash

2021-10-26 23:23 UTC, markscheel commented
Squashed.  I also added (and squashed) one more commit that simply added SphericalHarmonics to Domain/CoordinateMaps/CMakeLists.txt

2021-10-26 23:44 UTC, nilsvu approved these changes

2021-10-27 19:38 UTC, markscheel commented on src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt
> +  SPHEREPACK
added Utilities

2021-10-29 16:37 UTC, kidder commented
@wthrowe this has been squashed

2021-10-29 17:20 UTC, wthrowe approved these changes

2021-10-29 17:20 UTC, merged