Interpolate Ah quantities to 2 frames if desired.
sxs-collaboration/spectre pull request #3623
Opened 2021-10-26 22:22 UTC by markscheel

Previously, if we found the horizon in the grid frame, we could
run observers only in the grid frame, because the metric quantities
were computed on the horizon only in the grid frame.

Now, if we find the horizon in the grid frame, we can optionally
interpolate (and hence observe) quantities in the inertial frame as well
as in the grid frame.  Technically this means that we are now
allowed to specify quantities in both frames in DestTagList in
ComputeHorizonVolumeQuantities.hpp.

Note that if we don't want quantities in both frames, then those
quantities are not computed (except for any intermediate quantities
that are required to compute the desired output in the desired
frame).  And the computations are still done with minimal
memory allocations.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-10-28 22:04 UTC, kidder requested changes
you can squash immediately

2021-10-28 22:04 UTC, kidder commented on src/ApparentHorizons/ComputeHorizonVolumeQuantities.hpp
> +  using allowed_dest_tags_targetframe =
target_frame

2021-10-29 21:47 UTC, markscheel commented
squashed.

2021-11-01 23:17 UTC, kidder commented
@geoffrey4444 please review this for your BBHs

2021-11-01 23:17 UTC, kidder approved these changes

2021-11-02 01:03 UTC, geoffrey4444 approved these changes

2021-11-02 01:14 UTC, merged