GHGRMHD add FD directory and basic structure
sxs-collaboration/spectre pull request #3628
Opened 2021-10-28 16:26 UTC by nilsdeppe

## Proposed changes

- Add GHGRMHD FD subdir
- Add reconstructor base class for GHGRMHD
- Add registration files
- Add missing link library to GHGRMHD

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-10-28 21:54 UTC, kidder requested changes
can squash immediately

2021-10-28 21:54 UTC, kidder commented on src/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/Reconstructor.hpp
> +  virtual size_t ghost_zone_size() const = 0;
include for size_t

2021-10-28 21:54 UTC, kidder commented on src/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/Reconstructor.hpp
> +#include <pup.h>
could change this to a forward declaration

2021-11-01 17:16 UTC, yoonso0-0 submitted a review, later dismissed
No further comments from me

2021-11-01 22:32 UTC, nilsdeppe commented
rebased and squashed in the changes. Thanks for the reviews :)

2021-11-01 22:34 UTC, yoonso0-0 commented on src/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/Reconstructor.hpp
> +#include <size_t>
`<cstddef>`?

2021-11-01 22:48 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/Reconstructor.hpp
> +#include <size_t>
hah... yea... :( Thanks!

2021-11-01 23:15 UTC, kidder approved these changes

2021-11-02 18:28 UTC, merged