Add FixConservativesAndComputePrims to GH+GRMHD
sxs-collaboration/spectre pull request #3638
Opened 2021-11-04 05:18 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-11-10 18:13 UTC, yoonso0-0 reviewed
Q) Is this routine solely for atmosphere treatment, or does it work for handling any unreasonable situations in terms of primitive recovery?

2021-11-10 18:13 UTC, yoonso0-0 commented on src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/FixConservativesAndComputePrims.cpp
> +      tmpl::list<gr::Tags::SpatialMetric<3>, gr::Tags::InverseSpatialMetric<3>,
include `PointwiseFunctions/GeneralRelativity/Tags.hpp`

2021-11-10 18:13 UTC, yoonso0-0 commented on src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/FixConservativesAndComputePrims.cpp
> +  determinant_and_inverse(make_not_null(&sqrt_det_spatial_metric),
include `DataStructures/Tensor/EagerMath/DeterminantAndInverse.hpp`

2021-11-10 18:13 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +  const size_t num_pts = 1;
include `cstddef`

2021-11-10 18:13 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +  tnsr::aa<DataVector, 3, Frame::Inertial> spacetime_metric{num_pts, 0.0};
include `DataStructures/Tensor/Tensor.hpp`

2021-11-10 18:13 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +      sqrt(get(determinant(spatial_metric)))};
include for math expressions

2021-11-10 18:13 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +      std::unique_ptr<EquationsOfState::EquationOfState<true, 1>>{
include `memory`

2021-11-10 18:13 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +  using recovery_schemes = tmpl::list<
include `Utilities/TMPL.hpp`

2021-11-10 18:13 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +  grmhd::ValenciaDivClean::PrimitiveFromConservative<recovery_schemes, true>::
include for `ValenciaDivClean::PrimitiveFromConservative()`

2021-11-11 22:30 UTC, kidder requested changes

2021-11-11 22:30 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +  tnsr::aa<DataVector, 3, Frame::Inertial> spacetime_metric{num_pts, 0.0};
also DataVector

2021-11-11 22:30 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +      make_not_null(&box));
include gsl

2021-11-12 00:52 UTC, nilsdeppe reviewed
I've rebased and squashed. Thanks for the reviews :)

2021-11-12 00:52 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_FixConservativesAndComputePrims.cpp
> +      sqrt(get(determinant(spatial_metric)))};
`DataVector.hpp` covers this

2021-11-15 17:33 UTC, yoonso0-0 approved these changes

2021-11-15 18:12 UTC, kidder approved these changes

2021-11-15 18:12 UTC, merged