Enable subcell for Newtonian Euler
sxs-collaboration/spectre pull request #3648
Opened 2021-11-06 16:40 UTC by kidder

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-11-08 22:56 UTC, nilsdeppe requested changes
LGTM, just one request you can squash immediately. Thanks for doing this :)

2021-11-08 22:56 UTC, nilsdeppe commented on src/Evolution/Systems/NewtonianEuler/Subcell/NeighborPackagedData.hpp
> +                                       &nhbr_package_data, &nhbr_subcell_data,
I think we've been trying to spell out `neighbor` instead of using `nhbr` (my fault, sorry)

2021-11-09 22:24 UTC, nilsdeppe approved these changes, later dismissed

2021-11-19 23:51 UTC, kidder commented
@yoonso0-0 can you provide a second review for this?

2021-11-30 19:56 UTC, nilsdeppe commented
@yoonso0-0 can you please review this when you get a chance? Thanks!

@kidder it'll need a rebase

2021-12-13 18:26 UTC, yoonso0-0 commented
@kidder @nilsdeppe I'm currently reviewing this, but I'm not sure  if[this commit](https://github.com/sxs-collaboration/spectre/pull/3648/commits/72767107769ab14275e71111b0acf5ef4538bee0) would require another reviewer since I don't know well about coordinate tags.

2021-12-13 18:36 UTC, nilsleiffischer reviewed
I looked at the one commit that @yoonso0-0 pointed to

2021-12-13 18:36 UTC, nilsleiffischer commented on src/Evolution/DgSubcell/Actions/Initialize.hpp
> + *   - `subcell::Tags::Corodinates<Dim, Frame::Inertial>` (as compute tag)
typo `Coordinates`

2021-12-13 18:36 UTC, nilsleiffischer commented on tests/Unit/Evolution/DgSubcell/Actions/Test_Initialize.cpp
> -      tmpl::list<Initialization::Tags::InitialTime, domain::Tags::Mesh<Dim>,
Can you retrieve and check the computed inertial coordinates in this test?

2021-12-13 19:06 UTC, yoonso0-0 commented on src/Evolution/Systems/NewtonianEuler/Subcell/ComputeFluxes.hpp
> +template <size_t Dim, typename TagsList, typename... ReturnTags,
include for `size_t`

2021-12-13 19:06 UTC, yoonso0-0 commented on src/Evolution/Systems/NewtonianEuler/Subcell/ComputeFluxes.hpp
> + * \brief Helper function that calls `ComputeFluxes` by retrieving the return
This description goes better with the `detail::compute_fluxes_impl()` function above

2021-12-13 19:06 UTC, yoonso0-0 commented on src/Evolution/Systems/NewtonianEuler/Subcell/NeighborPackagedData.hpp
> +  template <size_t Dim, typename DbTagsList>
For ScalarAdvection system this struct and function are templated as `NeighborPackagedData<Dim>::apply<DbTagsList>`. Not sure which way might be clearer, but I think we need to keep it one way. Any suggestions?

2021-12-13 19:06 UTC, yoonso0-0 commented on src/Evolution/Systems/NewtonianEuler/Subcell/NeighborPackagedData.hpp
> +        Variables<dg_package_field_tags> packaged_data{0};
default construct this and the line above?

2021-12-13 19:06 UTC, yoonso0-0 commented on src/Evolution/Systems/NewtonianEuler/Subcell/NeighborPackagedData.hpp
> +            (void)dg_mesh;
Q. What is this line for?

2021-12-13 19:06 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_NeighborPackagedData.cpp
> +      std::unique_ptr<NewtonianEuler::fd::Reconstructor<Dim>>{
include `<memory>`

2021-12-13 19:06 UTC, yoonso0-0 commented on src/Evolution/Systems/NewtonianEuler/Subcell/TimeDerivative.hpp
> +  template <size_t Dim, typename DbTagsList>
Same issue as above (how to template)

2021-12-13 19:06 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TimeDerivative.cpp
> +#include "Evolution/DgSubcell/Tags/OnSubcellFaces.hpp"
Not used

2021-12-13 19:06 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TimeDerivative.cpp
> +#include "Parallel/Printf.hpp"
Not used

2021-12-13 19:06 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TimeDerivative.cpp
> +struct MetaVars {
[nitpick] rename to `SmoothFlowMetaVars` for a bit of clarity (since there is `LaneEmdenStarMetaVars` below)

2021-12-13 19:06 UTC, yoonso0-0 commented on tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TimeDerivative.cpp
> +  test_convergence<MetaVars<2>>();
Add test for 3D stationary smooth flow?

2021-12-13 19:07 UTC, yoonso0-0 reviewed
Please squash :)

2021-12-14 21:11 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/ComputeFluxes.hpp
> + * \brief Helper function that calls `ComputeFluxes` by retrieving the return
yes, but documentation doesn't render for code in a detail namespace

2021-12-14 21:18 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/NeighborPackagedData.hpp
> +            (void)dg_mesh;
it prevents a compiler warning that `dg_mesh` is unused

2021-12-14 21:31 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/NeighborPackagedData.hpp
> +  template <size_t Dim, typename DbTagsList>
As the only thing in the struct is the apply function, there is no need to template the struct.  Then both template parameters can be deduced from the function call, and don't need to be specified there.

2021-12-14 21:50 UTC, kidder commented on src/Evolution/Systems/NewtonianEuler/Subcell/TimeDerivative.hpp
> +  template <size_t Dim, typename DbTagsList>
same answer as above

2021-12-15 01:42 UTC, kidder commented
@yoonso0-0 @nilsdeppe @nilsleiffischer rebased and squashed

2021-12-15 01:49 UTC, nilsdeppe approved these changes

2021-12-15 17:51 UTC, yoonso0-0 approved these changes

2021-12-15 17:53 UTC, merged