Add FD ghost data to Burgers subcell
sxs-collaboration/spectre pull request #3659
Opened 2021-11-12 18:16 UTC by yoonso0-0

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2021-11-12 22:21 UTC, nilsdeppe requested changes
Overall LGTM, couple small requests. Please squash immediately

2021-11-12 22:21 UTC, nilsdeppe commented on src/Evolution/Systems/Burgers/Subcell/GhostData.hpp
> + * \note Called only by FD-solving elements.
I don't find the phrasing `FD-solving elements` particularly easy to understand. What do you think of `Only called on elements using FD.`?

2021-11-12 22:21 UTC, nilsdeppe commented on src/Evolution/Systems/Burgers/Subcell/GhostData.cpp
> +#include "Evolution/DgSubcell/Tags/Mesh.hpp"
do you need the tags includes here?

2021-11-15 17:21 UTC, yoonso0-0 commented
Rebased and squashed!

2021-11-15 18:01 UTC, nilsdeppe approved these changes

2021-11-15 21:41 UTC, merged