Move generic part of FakeVirtual to free function
sxs-collaboration/spectre pull request #366
Opened 2017-11-16 20:51 UTC by wthrowe

### Types of changes:

- [ ] Bugfix
- [X] New feature

### Component:

- [X] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."

### Further comments

2017-11-16 23:00 UTC, kidder requested changes

2017-11-16 23:00 UTC, kidder commented on src/Utilities/FakeVirtual.hpp
> +  /* If we want to allow creatable classses to return objects of */
// instead of /*

2017-11-16 23:00 UTC, kidder commented on tests/Unit/Utilities/Test_FakeVirtual.cpp
> +    int const_func() const { return 1; }
change to return a different value than the mutable_func

2017-11-17 04:47 UTC, kidder reviewed
looks good to me

2017-11-18 03:26 UTC, nilsdeppe approved these changes

2017-11-18 03:27 UTC, nilsdeppe commented
@kidder needs your approval

2017-11-18 04:20 UTC, kidder approved these changes

2017-11-18 04:21 UTC, merged