Construct measurement timescales using control sys info
sxs-collaboration/spectre pull request #3660
Opened 2021-11-12 19:49 UTC by knelli2

## Proposed changes

Use control system info to construct the measurement timescales. This doesn't change the default value they are set to, just how they are created.

First commit factors out some of the work of constructing the initial expiration times to its own function. The measurement timescales will need the exact same code.
Second commit moves the `control_system::Tags::MeasurementTimescales` tag to its own file. (`ControlSystem/Tags.hpp` was a bit crowded and `control_system::Tags::FunctionsOfTimeInitialize` has its own file as well)

This also factors out a bit of work from #3612 to keep it as small as possible.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-11-15 21:08 UTC, wthrowe requested changes

2021-11-15 21:08 UTC, wthrowe commented on src/ControlSystem/ConstructInitialExpirationTimes.hpp
> +struct ConstructInitialExpirationTimes {
Why is this a struct and not just a function?

2021-11-15 21:08 UTC, wthrowe commented on src/ControlSystem/Tags/MeasurementTimescales.hpp
> +struct MeasurementTimescales : db::SimpleTag {
Move the test too.

2021-11-15 23:56 UTC, knelli2 commented on src/ControlSystem/ConstructInitialExpirationTimes.hpp
> +struct ConstructInitialExpirationTimes {
Brain fart.

2021-11-15 23:57 UTC, knelli2 commented
Added an extra commit that moves the test of FunctionsOfTimeInitialize to a new file to match the tree structure in the src directory.

2021-11-17 22:35 UTC, wthrowe commented
Squash.

2021-11-24 10:24 UTC, nilsleiffischer requested changes
squash directly

2021-11-24 10:24 UTC, nilsvu commented on src/ControlSystem/ConstructInitialExpirationTimes.hpp
> +struct ConstructInitialExpirationTimes {
Looks like this got squashed into the wrong commit, please fix

2021-11-24 10:24 UTC, nilsleiffischer commented on src/ControlSystem/ConstructInitialExpirationTimes.hpp
> +          const double curr_timescale = min(tuner.current_timescale());
#include DataVector

2021-11-24 10:24 UTC, nilsleiffischer commented on src/ControlSystem/ConstructInitialExpirationTimes.hpp
> +              std::max(initial_time_step, initial_expiration_time);
#include <algorithm>

2021-11-24 10:24 UTC, nilsleiffischer commented on src/ControlSystem/ConstructInitialExpirationTimes.hpp
> +struct ConstructInitialExpirationTimes {
Also, note that we generally don't prepend verbs like "compute_" or "construct_" to function names when they can just be omitted, so I think `initial_expiration_times()` would be sufficient here.

2021-11-24 10:24 UTC, nilsleiffischer commented on src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp
> +    std::unordered_map<std::string, double> initial_expiration_times =
const

2021-11-24 10:24 UTC, nilsleiffischer commented on src/ControlSystem/Tags.hpp
> -#include <array>
Include `<cstddef>`, `<string>`, maybe more

2021-11-24 10:24 UTC, nilsleiffischer commented on src/ControlSystem/Averager.hpp
> +  double get_avg_timescale_frac() const { return avg_tscale_frac_; }
Also here you can omit the "get_".

2021-11-24 10:24 UTC, nilsleiffischer commented on src/ControlSystem/ConstructInitialExpirationTimes.hpp
> +std::unordered_map<std::string, double> construct_initial_expiration_times(
Add a docstring please

2021-11-24 10:24 UTC, nilsleiffischer commented on src/ControlSystem/Tags/MeasurementTimescales.hpp
> +          const DataVector curr_timescale = tuner.current_timescale();
const DataVector&

2021-11-24 19:47 UTC, knelli2 commented
Squashed in changes. Moved `construct_initial_expiration_times` to `initial_expiration_times` (along with file name as well). Also rebased on latest develop.

2021-11-24 20:10 UTC, nilsleiffischer approved these changes

2021-11-29 22:58 UTC, wthrowe approved these changes

2021-11-29 22:58 UTC, merged