Add temporary tags for repeated expressions in CCZ4 eqs
sxs-collaboration/spectre pull request #3668
Opened 2021-11-18 22:14 UTC by macedo22

## Proposed changes

This PR adds temporary simple tags for expressions that show up more than once in the CCZ4 evolution equations in [this paper](https://arxiv.org/pdf/1707.09910.pdf) (see ens 12a - 12m).

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-11-18 22:16 UTC, macedo22 commented on src/Evolution/Systems/Ccz4/TempTags.hpp
> + * four-vector along the normal direction, and \f$c\f$ is ???.
@nilsdeppe I wasn't sure how to describe what exactly c is in words. Let me know how you think this should be described!

2021-11-18 22:16 UTC, macedo22 commented on src/Evolution/Systems/Ccz4/TempTags.hpp
> + * normal direction, and \f$c\f$ is ???.
Same here

2021-11-19 23:14 UTC, nilsdeppe requested changes
you can squash

2021-11-19 23:14 UTC, nilsdeppe commented on src/Evolution/Systems/Ccz4/TempTags.hpp
> + * four-vector along the normal direction, and \f$c\f$ is ???.
`\f$c\f$ controls whether to include algebraic source terms proportional to \f$\Theta\f$.`

2021-11-29 23:54 UTC, macedo22 commented
Updated!

2021-11-30 00:45 UTC, nilsdeppe approved these changes

2021-11-30 02:34 UTC, merged