Add NeighborPackagedData to Burgers subcell
sxs-collaboration/spectre pull request #3674
Opened 2021-11-24 21:14 UTC by yoonso0-0

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-11-30 19:55 UTC, nilsdeppe requested changes
You can squash and rebase immediately

2021-11-30 19:55 UTC, nilsdeppe commented on src/Evolution/Systems/Burgers/Subcell/NeighborPackagedData.hpp
> +        // U, NormalDotFlux<U>, AbsCharSpeed
I think this comment depends on the Riemann solver

2021-11-30 19:55 UTC, nilsdeppe commented on src/Evolution/Systems/Burgers/Subcell/NeighborPackagedData.hpp
> +        Variables<dg_package_field_tags> packaged_data{0};
Just default construct this and on line 121 (2 lines below), no size needed

2021-12-02 17:45 UTC, yoonso0-0 commented
Rebased and squashed. Thanks!

2021-12-02 21:09 UTC, nilsdeppe approved these changes

2021-12-02 22:05 UTC, merged