Add Flattener to GRMHD
sxs-collaboration/spectre pull request #3696
Opened 2021-12-11 07:13 UTC by nilsdeppe

## Proposed changes

The flattener reduces the amount of oscillations in an element in an attempt to
guarantee that the primitive variables can be recovered.

This is from #3419 

Note: I didn't change the executable in this PR yet. If that's desirable (I'd say probably) then I can add a commit that uses the flattener instead of the pointwise fixer.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-12-15 19:30 UTC, kidder requested changes

2021-12-15 19:30 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +    const Options::Context& context)
`#include "Options/Options.hpp"`

2021-12-15 19:30 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +        const double volume_of_cell =
should there be a factor from  the spatial metric in these integrals?

2021-12-15 19:30 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +          ERROR("Invalid TildeD input to flattener. Got "
We require TildeD to have positive mean, but got "

2021-12-15 19:30 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.hpp
> +  /// \brief Cutoff below which \f$D = \rho W\f$ is set to MinimumValueOfD
See comment in the cpp file; I don't understand what this option (and therefore the one above) is for as the code does not do what the documentation says...

2021-12-15 19:30 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +    const double factor =
I don't understand `factor`.  If I have a function X with a mean X_m , and an extremum X_x violating bound X_b then I get the factor should be (X_m - X_b)/(X_m - X_x).  So in this formula you appear to be using a bound of zero, in which case you will be driving TildeD towards zero for positive values of TildeD below the cutoff.  I understand the safety factor.  I don't understand the ratio of the minimum over the cutoff.  I think you should either change line 142 to be min_d is negative or use the cutoff as the X_b and drop the minimum value of D option...  (Note if you use the cutoff as the bound, it also needs to be multiplied by sqrt_det_spatial_metric)

2021-12-15 19:30 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +        mean_tilde_tau + (safety / max_tilde_b_squared_over_2_tilde_tau) *
I don't understand this either given my formula above...

2021-12-15 19:30 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_Flattener.cpp
> +    CHECK_FALSE(tilde_d == original_mass_density_cons);
check that the means are conserved

2021-12-15 19:30 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_Flattener.cpp
> +    CHECK_ITERABLE_APPROX(tilde_d, expected_tilde_d);
check means are conserved for tilde_tau

2021-12-15 19:30 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Test_Flattener.cpp
> +    CHECK_FALSE(tilde_d == original_mass_density_cons);
why not check you get the values you expect?

2021-12-15 23:15 UTC, nilsdeppe reviewed
Rebased and pushed a fixup for everything except the tilde_tau rescaling like we talked about. Thanks for the review!

2021-12-15 23:15 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +        const double volume_of_cell =
The conserved variables have the factor of the spatial metric in them

2022-01-12 22:52 UTC, kidder requested changes

2022-01-12 22:52 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +  if (min_d < 0.) {
now that we've gotten rid of the minimum and cutoff for D; wouldn't it be better just to deal with tilde D and not D?  I.e. just find the minimum value of tilde_d and use that in the computation of factor.  Then you don't need the location of the minimum, or need to compute D

2022-01-12 22:52 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +          max((0.5 / one_minus_safety_factor_for_magnetic_field_) *
do you need this safety factor for the magnetic field?  Given the 0.95 safety I don't see how it can ever matter (assuming the small values you are setting it to...)

2022-01-13 22:10 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Flattener.cpp
> +        mean_tilde_tau + (safety / max_tilde_b_squared_over_2_tilde_tau) *
@nilsdeppe and I discussed this over a hangout and agreed on a better equation

2022-01-14 22:47 UTC, nilsdeppe commented
I've pushed another fixup commit. Cheers!

2022-01-14 23:36 UTC, kidder reviewed
squash

2022-01-14 23:41 UTC, nilsdeppe commented
Squashed. Thanks for the review :)

2022-01-14 23:50 UTC, kidder approved these changes

2022-01-18 18:22 UTC, merged