Combine time-dep rotation maps
sxs-collaboration/spectre pull request #3697
Opened 2021-12-12 03:29 UTC by knelli2

## Proposed changes

We have two different rotation maps in two separate files. One for 2D and one for 3D. This PR combines these maps into one `Rotation<Dim>` map that functions the same as the previous two for their respective dimensions.

Also the internals of QuaternionFunctionOfTime were changed to accommodate these changes. Essentially, previously the internal `PiecewisePolynomial` stored omega as a function of time. Now it stores the angle of rotation as a function of time (with omega being its first derivative). The main reason for this is because the control error for rotation (which will be added later) corresponds to an angle, not an angular velocity. Thus we want to update the nth derivative of a FunctionOfTime that represents an angle, not omega.

### Upgrade instructions

If you want to use the 3D rotation map that uses quaternions, use `Rotation<3>` now instead of `Rotation3D`.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2021-12-13 23:30 UTC, wthrowe requested changes

2021-12-13 23:30 UTC, wthrowe commented on src/Domain/FunctionsOfTime/QuaternionFunctionOfTime.hpp
> +  friend std::ostream& operator<<(  // NOLINT(readability-redundant-declaration
Close paren.

2021-12-13 23:30 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/TimeDependent/Test_Rotation.cpp
> +  Approx custom_approx = Approx::custom().epsilon(1.0).scale(1.0);
Put a comment here because it looks bad but isn't.

2021-12-14 00:44 UTC, knelli2 commented
Squashed directly.

2021-12-14 01:04 UTC, wthrowe approved these changes

2021-12-15 17:34 UTC, merged

2021-12-15 17:36 UTC, nilsleiffischer commented
@knelli2 Please make sure to put the upgrade instructions between the `<!-- UPGRADE_INSTRUCTIONS -->` fences in the PR description, so they get parsed correctly :)