Curved scalar wave initial data for scalar wave gr
sxs-collaboration/spectre pull request #3737
Opened 2022-01-11 12:57 UTC by nikwit

## Proposed changes

Currently the `ScalarWaveGr` class accepts only `ScalarWave` solutions and adjusts `Pi` to the background with spacetime quantities. There is no way to directly set `Pi` for the `CurvedScalarWave` initial data.

This PR adjusts `ScalarWaveGr` to recognize whether the wave solution//data comes from a `ScalarWave` solution where `Pi` needs to be adjusted with the background spacetime or directly from a `CurvedScalarWave` solution where `Pi` just needs to be forwarded.

depends on #3736

2022-01-11 15:04 UTC, nilsleiffischer requested changes
LGTM. Note that we're moving to a single executable per dimension for each system, so once it's time to migrate the CurvedScalarWave executable this `ScalarWaveGr` can factory-create the `ScalarField` and `Background` objects. At that point you'll probably have to rethink this implementation, since it's going to be a runtime choice. Still a few weeks off though.

2022-01-11 15:04 UTC, nilsvu commented on src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/ScalarWaveGr.hpp
> + * of the scalar field in curved spacetime:
Could you add a docstring to `CurvedScalarWave::Tags::Pi` with this definition in a separate commit, ideally pointing into a paper? It's missing for some reason. I think it's Eq. (14) in Holst2004wt (https://arxiv.org/abs/gr-qc/0407011).

2022-01-11 15:04 UTC, nilsvu commented on src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/ScalarWaveGr.hpp
> +  using evolved_field_vars_tags =
How about something like `scalar_wave_tags`? (squash directly if you change this name)

2022-01-11 20:08 UTC, nilsdeppe reviewed
overall LGTM, some suggestions you can squash in immediately if you like them

2022-01-11 20:08 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/ScalarWaveGr.hpp
> +    static constexpr Options::String help = {"Scalar field."};
[optional] Maybe expand to `The scalar field system data.` to make it clear it sets the subsystem?

2022-01-11 20:08 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/CurvedWaveEquation/ScalarWaveGr.hpp
> +  using evolved_field_vars_tags =
I'm okay with leaving as-is or with renaming. It's unclear to me if there should be a preference here until we couple in the GH evolution.

2022-01-11 20:08 UTC, nilsdeppe commented on tests/Unit/PointwiseFunctions/AnalyticData/CurvedWaveEquation/Test_ScalarWaveGr.cpp
> +
[optional] consider adding `const auto curved_scalar_wave_data = serialize_and_deserialize(..._from_opts);` and using that in the `CHECK` and the `test_kerr` call to verify serialization is working.

2022-01-12 12:54 UTC, nilsleiffischer approved these changes
I think the `==` operator of `ScalarWaveGr` is wrong, please check in a follow-up PR.

2022-01-12 12:57 UTC, nikwit commented
> I think the `==` operator of `ScalarWaveGr` is wrong, please check in a follow-up PR.

missing `scalar_wave_data_` comparison?

2022-01-12 12:59 UTC, nilsleiffischer commented
yep

2022-01-12 18:02 UTC, nilsdeppe approved these changes
LGTM! Let's defer the `operator==` since there might be issues with the ScalarWave solutions not having an `operator==` or something (I haven't checked). Some of those have `unique_ptr<BaseClass>` member variables

2022-01-12 18:03 UTC, merged