Add is_charm_aware function to GlobalCache
sxs-collaboration/spectre pull request #3740
Opened 2022-01-12 23:22 UTC by knelli2

## Proposed changes

In addition to adding the function, this removes one of the `Parallel::mutate` functions. Previously, there were two `Parallel::mutate` functions: 1) took a reference to the GlobalCache, intended to be used in the testing framework, and 2) took a proxy to the GlobalCache, intended to be used in charm runs. However, during a charm run, there was no protection against accidentally using 1) to mutate the local cache which wouldn't broadcast the mutation to other nodes. Now there is only one `Parallel::mutate` function, and using the is_charm_aware function, determines if it should broadcast the mutation (for charm runs) or just mutate the local cache (testing framework).

### Upgrade instructions

All calls to `Parallel::mutate` (in both testing framework and charm runs) take a reference to the local GlobalCache. This doesn't affect previous calls in the testing framework, but now in charm runs take a reference instead of a proxy to the GlobalCache.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-01-12 23:34 UTC, knelli2 commented
clang-tidy error comes from inside charm++. Is this something we are able to ignore?

2022-01-18 23:14 UTC, kidder reviewed
changes look fine, but I'm not a big fan of the name `is_charm_aware`.  Let's discuss at tomorrow's call

2022-01-20 02:03 UTC, knelli2 commented
Discussed at the Wednesday SpECTRE meeting:

Instead of having source files deal with testing details, it was decided that the `Parallel::mutate` that was intended to be used in the testing framework should actually be moved to the testing framework. I added it to the free functions for ActionTesting because that seemed the most appropriate. Also added some docs to ActionTesting on using `ActionTesting::mutate`.

2022-01-20 23:20 UTC, kidder approved these changes

2022-01-20 23:24 UTC, kidder requested changes
squash

2022-01-21 01:00 UTC, kidder approved these changes

2022-01-21 01:02 UTC, kidder commented
@markscheel @wthrowe @markscheel this has been updated to do what we discussed yesterday

2022-01-27 04:56 UTC, nilsdeppe approved these changes

2022-01-27 17:39 UTC, merged