Add Shell and test
sxs-collaboration/spectre pull request #375
Opened 2017-11-17 18:23 UTC by gsb76

## Proposed changes

A DomainCreator for the Shell, which is made of six wedges.
Allows for equiangular or equidistant coordinates.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."

### Further comments

2017-11-17 18:29 UTC, fmahebert requested changes

2017-11-17 18:29 UTC, fmahebert commented on src/Domain/DomainCreators/Shell.hpp
> +/// Create a 3D Domain consisting of six wedges and a central cube.
Fix this

2017-11-17 18:29 UTC, fmahebert commented on src/Domain/DomainCreators/Shell.hpp
> +        "Radius of the sphere circumscribing the inner cube."};
No cube

2017-11-17 18:29 UTC, fmahebert commented on src/Domain/DomainCreators/Shell.hpp
> +        "Whether to use equiangular or equidistant variables."};
variables -> coordinates

2017-11-17 18:31 UTC, osheamonn commented on tests/Unit/Domain/Test_DomainCreators.cpp
> +SPECTRE_TEST_CASE("Unit.Domain.DomainCreators.Shell.Separation",
Test that the neighbors, boundaries and maps are as expected.

2017-11-21 20:26 UTC, kidder requested changes
rebase, see comments on test of Disk and Sphere,

2017-12-12 20:41 UTC, kidder requested changes

2017-12-12 20:41 UTC, kidder commented on src/Domain/DomainCreators/Shell.hpp
> +        "Whether to use equiangular or equidistant coordinates."};
oops

2017-12-12 20:41 UTC, kidder commented on src/Domain/DomainCreators/Shell.hpp
> +      "Creates a 3D Shell with 6 Blocks. `use_equiangular_map_` has a default\n"
help text talks about public options, not private member data

2017-12-12 20:41 UTC, kidder commented on src/Domain/DomainCreators/Shell.hpp
> +#include "DataStructures/Tensor/IndexType.hpp"
move to cpp

2017-12-12 20:41 UTC, kidder commented on tests/Unit/Domain/DomainCreators/Test_Shell.cpp
> +}
add equidistant tests

2017-12-12 21:10 UTC, nilsdeppe submitted a review, later dismissed

2017-12-12 21:16 UTC, kidder approved these changes

2017-12-12 21:16 UTC, nilsdeppe approved these changes

2017-12-12 21:16 UTC, fmahebert approved these changes

2017-12-12 21:17 UTC, wthrowe approved these changes

2017-12-13 14:39 UTC, merged