Fix curved/scalar wave tags docs
sxs-collaboration/spectre pull request #3771
Opened 2022-01-28 08:54 UTC by nikwit

This documentation of the evolved variables meant for the `CurvedScalarWave` system was erroneously added to the `ScalarWave` system in #3737 .

This PR moves the documentation to the `CurvedScalarWave` system and adds the appropriate documentation to the `ScalarWave` system.

2022-01-28 09:39 UTC, nilsleiffischer approved these changes, later dismissed

2022-01-28 17:37 UTC, kidder requested changes

2022-01-28 17:37 UTC, kidder commented on src/Evolution/Systems/CurvedScalarWave/Tags.hpp
> + *     =&  \frac{1}{\alpha}\left(\beta^k \Phi_k - {\partial_t\Psi}\right),\\
I know you just moved this, but Phi_k should be \partial_k \Psi

2022-01-29 18:21 UTC, kidder approved these changes

2022-01-29 19:06 UTC, kidder commented
@nikwit can you rebase this; GitHub says the branch has conflicts but doesn't say where...  you may have to force-push again if there aren't any conflicts...

2022-01-29 19:12 UTC, closed without merging

2022-01-29 19:15 UTC, nikwit commented
It looks to me like it was merged. I force pushed and that seemed to close the PR somehow. Either way, the changes are on develop.

2022-01-29 21:02 UTC, kidder commented
strange... must have been a GitHub hiccup