Add ADER namespaces and ADER-DG spacetime predictor matrix
sxs-collaboration/spectre pull request #3778
Opened 2022-01-30 23:33 UTC by nilsdeppe

## Proposed changes

Another blob of code from years ago that I rebased. The main addition is the ADER-DG spacetime predictor matrix that is used in the implicit problem in the small. We might want to compute these at quad precision at some point in the future since they are a bit difficult to invert.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-01-31 20:08 UTC, kidder requested changes
haven't checked the second commit yet

2022-01-31 20:08 UTC, kidder commented on docs/GroupDefs.hpp
> + * \brief Functions and classes needed for ADER (Abitrary high-order using
Arbitrary

2022-02-11 19:48 UTC, nilsdeppe commented
rebased and squashed in typo fix. Thanks for the review :)

2022-02-18 20:45 UTC, kidder approved these changes

2022-02-21 18:18 UTC, merged