Add bool flag for using subcell boundary conditions
sxs-collaboration/spectre pull request #3779
Opened 2022-01-31 18:05 UTC by yoonso0-0

## Proposed changes

Add a bool type compile time constant `subcell_enabled_at_external_boundary` to the `EvolutionMetavars::SubcellOptions` struct. In the future we may want to make this as a runtime option.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2022-02-05 00:35 UTC, nilsdeppe requested changes
some small suggestions. Please squash immediately :)

2022-02-05 00:35 UTC, nilsdeppe commented on src/Evolution/DgSubcell/Actions/Initialize.hpp
> +        std::decay_t<decltype(db::get<Parallel::Tags::Metavariables>(
why can't you just do `Metavariables::SubcellOptions::...`? You have the metavariables as a template parameter to this function, I think that's all you need, then you don't need the tag

2022-02-05 00:35 UTC, nilsdeppe commented on src/Evolution/DgSubcell/Actions/TciAndRollback.hpp
> +        std::decay_t<decltype(db::get<Parallel::Tags::Metavariables>(
you also have `Metavariables` as a template parameter in the apply function :)

2022-02-07 17:42 UTC, yoonso0-0 commented
Fixed and squashed. I overlooked that `Metavariables` is provided as a template parameter

2022-02-10 15:44 UTC, nilsdeppe approved these changes

2022-02-10 15:44 UTC, merged