Refactor some of TryToInterpolate.hpp
sxs-collaboration/spectre pull request #3812
Opened 2022-02-17 21:19 UTC by markscheel

## Proposed changes

Move some of interpolate_data and small functions into new functions
in InterpolateTargetDetail.

This is so in my next PR I can use those functions in
InterpolateWithoutInterpComponent without duplicating code.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-02-17 22:13 UTC, nilsdeppe requested changes
LGTM, two minor requests. Please squash immediately!

2022-02-17 22:13 UTC, nilsdeppe commented on src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
> +    Parallel::GlobalCache<Metavariables>& cache,
I think the `cache` can be `const` if you are only retrieving items from it

2022-02-17 22:13 UTC, nilsdeppe commented on src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
> +    gsl::not_null<Variables<
`const gsl::not_null` (add `const`)

2022-02-18 01:14 UTC, knelli2 requested changes
Also squash immediately.

2022-02-18 01:14 UTC, knelli2 commented on src/ParallelAlgorithms/Interpolation/InterpolationTargetDetail.hpp
> +    TensorMetafunctions::any_index_in_frame<typename Tag::type, Frame>;
`#include DataStructures/Tensor/Metafunctions.hpp`

2022-02-18 03:20 UTC, knelli2 approved these changes

2022-02-18 15:54 UTC, nilsdeppe approved these changes

2022-02-19 16:12 UTC, merged