Add more parameters and functions to BinaryTrajectories
sxs-collaboration/spectre pull request #3818
Opened 2022-02-19 02:45 UTC by knelli2

These things will be helpful for testing control systems:
- `velocity` parameter. The CoM of the binary will move with this
  constant velocity. Default is zero velocity.
- `newtonian` bool to indicate using Newtonian trajectories instead
  of PN trajectories (Default is false, i.e. PN trajectory)
- `angulary_velocity` function. Returns the angular velocity.
- `positions_no_expansion` function. Regardless of Newtonian or PN,
  the orbit is circular, but the frequency of the orbit follows
  either Newtonain or PN, whetever was specified. (Note: these
  positions are not physical, just useful for testing control
  systems)

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-02-22 05:17 UTC, nilsdeppe commented
Can you specify what you're adding to `BinaryTrajectories` in the title? My view is if a PR does so much stuff it can't be succinctly described in the title it might be doing too much (not in this case, I think). I also don't know what `Newtonian` means in the PR description, maybe expand on that?

2022-02-22 17:47 UTC, knelli2 commented
Updated the title and description in both the PR and commit.

2022-02-23 21:15 UTC, wthrowe requested changes

2022-02-23 21:15 UTC, wthrowe commented on tests/Unit/Helpers/PointwiseFunctions/PostNewtonian/BinaryTrajectories.cpp
> +BinaryTrajectories::positions_no_expansion(const double time) const {
This differs by one line from the previous function.  Factor the common code into a helper.

2022-02-23 23:15 UTC, knelli2 commented
Squashed changes directly because they were short.

2022-02-24 19:45 UTC, wthrowe approved these changes

2022-03-15 02:09 UTC, geoffrey4444 approved these changes

2022-03-15 02:10 UTC, merged