Add a single variables slicing for subcell
sxs-collaboration/spectre pull request #3826
Opened 2022-02-21 22:11 UTC by yoonso0-0

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

I'm not sure `std::copy`ing from `std::vector<double>` into the returned variables object is the best one. There might be more efficient way, so welcome any suggestions.

2022-03-15 19:34 UTC, nilsdeppe requested changes

2022-03-15 19:34 UTC, nilsdeppe commented on src/Evolution/DgSubcell/SliceVariable.hpp
> + * `evolution::dg::subcell::detail::slice_data_impl` function, but note that the
I don't know how great it is to refer to a `detail` function in the documentation. It's a detail for a reason, not a public interface. Isn't the contrast to the other `slice_data`?

2022-03-15 19:34 UTC, nilsdeppe commented on src/Evolution/DgSubcell/SliceVariable.hpp
> +void slice_variable_for_subcell(
why add `for_subcell`, isn't that redundant with being in the `subcell` namespace? It's not clear what you are trying to differentiate here

2022-03-15 19:34 UTC, nilsdeppe commented on src/Evolution/DgSubcell/SliceVariable.hpp
> +    *sliced_subcell_vars = Variables<TagList>(num_sliced_pts);
`sliced_subcell_vars->initialize(num_sliced_pts);`

2022-03-15 19:34 UTC, nilsdeppe commented on src/Evolution/DgSubcell/SliceVariable.hpp
> +  std::vector<double> sliced_data{detail::slice_data_impl(
`const`?

2022-03-15 19:34 UTC, nilsdeppe commented on src/Evolution/DgSubcell/SliceVariable.hpp
> +      subcell_extents.slice_away(direction.dimension()).product() *
just pass the size into the variables constructor

2022-03-15 19:34 UTC, nilsdeppe commented on src/Evolution/DgSubcell/SliceVariable.hpp
> +#include <cstddef>
`<vector>`

2022-05-04 16:17 UTC, yoonso0-0 commented on src/Evolution/DgSubcell/SliceVariable.hpp
> + * `evolution::dg::subcell::detail::slice_data_impl` function, but note that the
Agree. I'll delete this paragraph.

2022-05-04 16:20 UTC, yoonso0-0 commented
Pushed a fixup. Thanks for the review :)

2022-05-05 17:51 UTC, nilsdeppe reviewed
LGTM, please rebase, squash, and ping me when you've done that :)

2022-05-05 17:57 UTC, yoonso0-0 commented
@nilsdeppe Rebased and squashed :)

2022-05-05 18:13 UTC, nilsdeppe approved these changes

2022-05-05 21:13 UTC, merged