Enable sleef support
sxs-collaboration/spectre pull request #3833
Opened 2022-02-24 18:45 UTC by nilsdeppe

## Proposed changes

Sleef enables vectorization of special functions like trig, exp, etc.

Unfortunately on my machine Blaze currently doesn't build when Sleef is enabled. I've filed an issue about this with Blaze.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-02-28 11:57 UTC, nilsvu requested changes
Look good! Just the one comment.

2022-02-28 11:57 UTC, nilsvu commented on cmake/SetupBlaze.cmake
> +  BLAZE_USE_SLEEF=${_BLAZE_USE_SLEEF}
Please delete the comment about SLEEF that I added above

2022-03-01 05:19 UTC, nilsdeppe reviewed
Rebased, removed, and squashed! Thanks for the review :)

2022-03-01 08:46 UTC, nilsvu approved these changes

2022-03-01 10:42 UTC, merged