Add block neighbors to excision spheres, make std::unordered_set<T, Hash> pupable
sxs-collaboration/spectre pull request #3872
Opened 2022-03-15 21:29 UTC by nilsvu

## Proposed changes

This is the information needed to figure out which elements face the excision boundary. Used for interpolations from element faces to a Strahlkorper representing the excision.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-03-15 21:38 UTC, nilsvu commented
@gsb76 @markscheel I needed this block neighbor information to get observations on excision boundaries to an (almost!) working state, and I remember we discussed adding this a while back. I hope this helps you as well.

2022-03-15 21:39 UTC, nilsvu commented
@nikwit ping because I think you are using something like this on a branch as well

2022-03-15 21:49 UTC, wthrowe commented
Why have you chosen a set here?  It looks like you are using it as a map.  (Iterating over all the pairs looking for a particular first entry.)

2022-03-15 22:03 UTC, nilsvu commented
I think you're absolutely right that a map makes more sense. Give me a sec to check.

2022-03-15 22:05 UTC, kidder requested changes

2022-03-15 22:05 UTC, kidder commented on src/Domain/Structure/ExcisionSphere.hpp
> +  /// \param block_neighbors the set of blocks that face the excision sphere.
face ->  abut

face just means oriented towards, while abut means touching

2022-03-15 22:05 UTC, kidder commented on src/Domain/Structure/ExcisionSphere.hpp
> +  std::optional<Direction<VolumeDim>> face_direction(
face_direction -> abutting_direction

2022-03-15 22:15 UTC, gsb76 reviewed
Do you know if there's any need to also keep track of the orientation/connectivity of the faces? All of excision boundary directions being lower zeta doesn't determine this and I wonder if knowing which excision boundary faces are neighboring each other is information you might need. Otherwise looks good!

2022-03-15 22:15 UTC, gsb76 commented on src/Domain/Creators/BinaryCompactObject.cpp
> +                          {{object_A_.x_coord, 0.0, 0.0}},
Maybe a small comment saying "Direction of faces given by [reference to either documentation or code]"

2022-03-15 22:49 UTC, nilsvu commented
I simplified this a lot since @wthrowe is absolutely right that a map is the right representation here. Thanks!

Also squashed in @kidder's and @gsb76's comments.

@gsb76 I believe we don't need orientations and connectivity. My current thought is: a surface integral over the excision boundary decomposes into the sum of the integrals over the individual abutting element faces. So to get the spherical harmonic coefficients we can integrate the spherical harmonics times the data over each abutting element face independently and sum the result. This can be expressed as a projection matrix I believe, but should only need information about the element face. Either way, if I'm wrong we can add the orientation information when we need it.

2022-03-15 23:01 UTC, gsb76 submitted a review, later dismissed
Looks good! :+1:

2022-03-16 18:35 UTC, wthrowe approved these changes

2022-03-17 17:29 UTC, nilsvu commented
@kidder please check if your comments have been addressed here.

2022-03-18 17:24 UTC, kidder approved these changes

2022-03-18 17:25 UTC, merged