Change sonarqube to sonarcloud
sxs-collaboration/spectre pull request #388
Opened 2017-11-23 18:29 UTC by nilsdeppe

## Proposed changes

SonarQUBE is moving to SonarCloud, so we need to adjust. I intentionally did not just the variable in Travis because that would cause builds to fail until this is merged and I figured that's better to do next week when it's easier to coordinate with people.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

2017-11-25 04:54 UTC, kidder requested changes

2017-11-25 04:54 UTC, kidder commented on .travis.yml
> +# compilation time. SonarCould, a static analysis tool (https://sonarcloud.io/)
Could -> Cloud

2017-11-27 17:38 UTC, nilsdeppe commented
Updated, I did a rebase since it was only the one change.

2017-11-27 22:23 UTC, kidder approved these changes

2017-11-27 22:26 UTC, wthrowe approved these changes

2017-11-28 14:48 UTC, merged