Mutating compute items
sxs-collaboration/spectre pull request #394
Opened 2017-11-27 17:20 UTC by nilsdeppe

## Proposed changes

Adds support for mutating compute items. The details of this is in the updated documentation for `db::ComputeItemTag`.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

2017-11-27 17:35 UTC, osheamonn commented on src/DataStructures/DataBoxTag.hpp
> + * (pointer). Mutating compute time tags must also contain a type alias named
time -> item

2017-11-27 17:35 UTC, osheamonn commented on tests/Unit/Utilities/Test_Deferred.cpp
> +void mutate_function(gsl::not_null<double*> t, const double t0) { *t = t0; }
Should gsl::not_null's be const?

2017-11-27 23:53 UTC, kidder requested changes

2017-11-27 23:53 UTC, kidder commented on src/Utilities/Deferred.hpp
> +struct get_type_from_deferred_impl {
remove_deferred

2017-11-27 23:53 UTC, kidder commented on src/Utilities/Deferred.hpp
> +  ptr->update_args(std::forward<Args>(args)...);
just call the second one

2017-11-27 23:53 UTC, kidder commented on tests/Unit/Utilities/Test_Deferred.cpp
> +  auto def_mutate_vector = make_deferred<std::vector<double>>(
huh?

2017-11-27 23:53 UTC, kidder commented on tests/Unit/Utilities/Test_Deferred.cpp
> +void mutate_function_vector(gsl::not_null<std::vector<double>*> t,
do not show this as an example and add a better example

2017-11-27 23:53 UTC, kidder commented on src/DataStructures/DataBoxTag.hpp
> + * Compute items come in two primary forms: mutating and non-mutating. Mutating
remove "primary"

2017-11-27 23:53 UTC, kidder commented on src/DataStructures/DataBoxTag.hpp
> + * `type` that is the type the function is mutating. The type must be default
`type` -> `return_type`

2017-11-27 23:53 UTC, kidder commented on tests/Unit/DataStructures/Test_DataBox.cpp
> +  if (t->number_of_grid_points() == 0) {
!= 10

2017-11-27 23:53 UTC, kidder commented on tests/Unit/DataStructures/Test_DataBox.cpp
> +void mutate_variables(
add to documentation

2017-11-27 23:53 UTC, kidder commented on tests/Unit/DataStructures/Test_DataBox.cpp
> +  CHECK(
// add comment checking that where the data is stored has not changed

2017-11-28 04:24 UTC, kidder reviewed
I am happy for you to squash

2017-11-28 14:47 UTC, nilsdeppe commented
Okay, done!

2017-11-28 16:41 UTC, kidder approved these changes

2017-11-28 21:00 UTC, kidder approved these changes

2017-11-28 21:01 UTC, wthrowe approved these changes

2017-11-28 21:13 UTC, merged