Allow DgElementArray to ignore certain procs when placing elements
sxs-collaboration/spectre pull request #3950
Opened 2022-04-29 20:40 UTC by knelli2

## Proposed changes

In preparation to add a new feature where we can place singletons on specific processors and have no DG-elements be placed on those processors, the DgElementArray needs to know which processors it can't place elements on. This PR changes the `allocate_array` function of both the evolution and elliptic DgElementArray so it can ignore specific processors.

The BlockZCurveProcDistribution allocator is also modified in a similar way to avoid placing elements on specific processors, but nothing about the Morton Z-order curve is changed.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-05-06 00:49 UTC, nilsdeppe requested changes

2022-05-06 00:49 UTC, nilsdeppe commented on src/Domain/ElementDistribution.cpp
> +    while (procs_to_ignore.find(current_proc_number) != procs_to_ignore.end()) {
why do you need the `current_proc_number` stuff? I would've expected that all you need is:
```
if (procs_to_ignore.find(i) != procs_to_ignore.end()) {
  continue;
}
```
but if you need the extra stuff, there should be a comment explaining why. Also, wouldn't the number of procs change if you're ignoring some? At least in so far as figuring out the number of elements per proc?

Okay, I see that the next commit changes how the `number_of_procs` is passed in. I think that needs to be documented, and maybe the variable should be renamed `number_of_procs_with_elements` or something?

2022-05-06 00:49 UTC, nilsdeppe commented on docs/DevGuide/Parallelization.md
> +    const std::unordered_set<size_t>& procs_to_ignore);
Could you document what `procs_to_ignore` is used for?

2022-05-06 00:49 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_PhaseChangeMain.cpp
> +    const size_t number_of_procs = static_cast<size_t>(sys::number_of_procs());
can we factor this round robin code out somewhere? It's getting increasing complicated and so not having to update in a bunch of places would be nice

2022-05-06 19:46 UTC, knelli2 commented
@nilsdeppe Added some fixups where I renamed some variables and added comments to clarify things.

While I agree it's getting hard to keep up with the round-robin code, if it's ok with you, I'd like to leave that refactor for a follow-up PR (which I'm more than happy to submit) as it's not crucial for my upcoming PRs (while these changes are). The refactor will just make some tests look prettier.

2022-05-09 15:46 UTC, nilsdeppe reviewed
LGTM, please squash and rebase.

I'm fine with deferring the factoring until later :)

2022-05-09 23:45 UTC, nilsdeppe approved these changes

2022-05-10 00:42 UTC, merged