Add parallel info to GlobalCache
sxs-collaboration/spectre pull request #3951
Opened 2022-04-30 04:47 UTC by knelli2

## Proposed changes

We have access to the GlobalCache almost everywhere in SpECTRE. Because of that, I think it makes sense for the GlobalCache to be aware of the parallel info like number of nodes/procs. This PR adds the parallel info functions that all other parallel components have as members of the GlobalCache. These new member functions will also work in the ActionTesting framework and with the `Parallel::number_of_nodes()` etc... functions.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-05-05 17:48 UTC, nilsdeppe requested changes
One small request, please rebase and squash immediately!

2022-05-05 17:48 UTC, nilsdeppe commented on src/Parallel/GlobalCache.hpp
> +    return sys::node_of(proc_index);
Is there an easy way to test this line? It looks like it is tested in `Test_AlgorithmGlobalCache`, right? If so, do you just want to `// LCOV_EXCL` this line and add a C++ comment that for some reason gcov isn't picking it up as being covered?

2022-05-06 00:08 UTC, nilsdeppe submitted a review, later dismissed

2022-05-06 16:56 UTC, nilsdeppe commented
@knelli2 looks like this needs a rebase to resolve a conflict. Please ping me once you've resolved it!

2022-05-06 20:30 UTC, knelli2 commented
@nilsdeppe Resolved! :)

2022-05-07 05:13 UTC, nilsdeppe approved these changes

2022-05-07 05:13 UTC, merged