Add Rotation control system
sxs-collaboration/spectre pull request #3965
Opened 2022-05-10 01:39 UTC by knelli2

## Proposed changes

Adds a rotation control system that controls the 3D quaternion rotation map.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-05-10 22:06 UTC, wthrowe requested changes

2022-05-10 22:06 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Rotation.hpp
> +    using horizon_label = ::ah::ObjectLabel;
CamelCase because this is used as a normal type.

2022-05-10 22:06 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Rotation.hpp
> +    const DataVector current_position_of_B = get<center_B>(measurements);
References for both of these.

2022-05-10 22:06 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Rotation.hpp
> + * are exactly along the x-axis.
You don't assume this in the code.

2022-05-10 22:06 UTC, wthrowe commented on src/ControlSystem/Systems/Rotation.hpp
> +                                       control_system::protocols::Measurement>);
Just `tt::conforms_to`.

2022-05-10 22:06 UTC, wthrowe commented on src/ControlSystem/Systems/Rotation.hpp
> +                control_error, control_system::protocols::ControlError>);
Again `tt::conforms_to`.

2022-05-10 22:06 UTC, wthrowe commented on tests/Unit/ControlSystem/ControlErrors/Test_Rotation.cpp
> +  CHECK(control_error == expected_control_error);
This test is a near copy-paste of the source being tested.  Instead of using random numbers and computing the expected answer in code, use specific inputs with a known result.

2022-05-10 22:06 UTC, wthrowe commented on tests/Unit/ControlSystem/ControlErrors/Test_Rotation.cpp
> +  double initial_time = 0.0;
`const`

2022-05-10 22:06 UTC, wthrowe commented on tests/Unit/ControlSystem/Systems/Test_Rotation.cpp
> +  double initial_time = 0.0;
`const`

2022-05-11 20:11 UTC, knelli2 commented
Rebased on develop and added fixups. @wthrowe Also applied some of the changes you requested here to the Expansion control system as well in a new commit.

2022-05-13 18:00 UTC, wthrowe approved these changes, later dismissed
Go ahead and squash.  Thanks for cleaning up the expansion code too.

2022-05-13 20:26 UTC, wthrowe submitted a review, later dismissed

2022-05-17 17:44 UTC, nilsdeppe commented
@markscheel would you mind taking a look at this? Your expertise would be really useful here!

2022-05-18 14:29 UTC, markscheel commented on src/ControlSystem/Systems/Rotation.hpp
> + * rotated through about each axis.
The 'Indirectly' and 'directly' phrases here are a bit confusing to me, because they made me think that either I should find some code in `Rotaton` that messes with the internals of QuaternionFunctionOfTime, or the user needs to be careful with where QuaternionFunctionOfTime is specified and where QuaternionFunctionOfTime's internal FunctionOfTime is specified.  But (I think) when the rotation control system is used, the user should simply use it with a QuaternionFunctionOfTime, and the user never needs to know that the QuaternionFunctionOfTime internally holds another PiecewisePolynomial.

So maybe this comment should be changed to something like:
"Controls the quaternion in the 3D Rotation coordinate map.  From the user's perspective, `Rotation` simply controls and updates a QuaternionFunctionOfTime.  (Internally, QuaternionFunctionOfTime holds a PiecewisePolynomial representing the angle through which the system has rotated, and the control error technically is the one for that internal PiecewisePolynomial.  However, QuaternionFunctionOfTime::update automatically does the correct update on its internal PiecewisePolynomial and recomputes the quaternion and its derivatives appropriately, in a way that is transparent to the user.)"

2022-05-18 17:55 UTC, knelli2 commented
@markscheel Added a `\note` to the docs of the Rotation control system detailing what you said and simplified the main description. Squashed directly.

Also rebased on develop.

2022-05-18 19:43 UTC, wthrowe approved these changes

2022-05-23 17:57 UTC, markscheel approved these changes

2022-05-23 17:59 UTC, merged