Add Raise and Lower
sxs-collaboration/spectre pull request #398
Opened 2017-11-28 04:45 UTC by osheamonn

## Proposed changes

Adds function to raise and lower index of Christoffel type tensors. 

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

2017-11-28 20:44 UTC, kidder requested changes

2017-11-28 20:44 UTC, kidder commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Test_IndexManipulation.cpp
> +  check_tensor_doubles_equals_tensor_datavectors(
oops

2017-11-28 20:44 UTC, kidder commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Test_IndexManipulation.cpp
> +  check_tensor_doubles_equals_tensor_datavectors(
oops oops

2017-11-28 20:44 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/IndexManipulation.hpp
> +template <size_t Dim, typename Frame, UpLo UpOrLo, IndexType TypeOfIndex,
simplify to eliminate the IndexManipulation_detail namespace

2017-11-29 22:10 UTC, kidder requested changes
rebase squash

2017-11-29 22:10 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/IndexManipulation.cpp
> +                            change_index_up_lo<Index0>>>& metric) {
noexcept

2017-11-29 22:10 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/IndexManipulation.cpp
>  #undef DIM
undefs match defines

2017-11-30 16:29 UTC, kidder reviewed
Need to fix a conflict.  Do we noexcept test functions?

2017-11-30 16:36 UTC, osheamonn commented
If we do need to noexcept test functions I'd rather do it in a seperate PR since it'll apply to all the functions I've added.

2017-11-30 23:18 UTC, kidder approved these changes

2017-12-01 00:00 UTC, nilsdeppe commented
I think we've generally been inconsistent with noexcept on test functions. It wouldn't be bad, but also not necessary.

2017-12-01 00:02 UTC, nilsdeppe approved these changes

2017-12-01 02:20 UTC, nilsdeppe commented
@wthrowe would you mind looking over this one and giving your feedback before we merge? Thanks :)

2017-12-01 02:29 UTC, wthrowe approved these changes
I guess in theory noexcept is good in tests, but I often don't bother with it myself so I'm certainly not going to make others do it.

2017-12-01 03:01 UTC, merged