Add WCNS-5Z reconstruction to finite difference
sxs-collaboration/spectre pull request #3986
Opened 2022-05-20 00:46 UTC by yoonso0-0

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-05-23 19:26 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Wcns5z.hpp
> +struct Wcns5zReconstructor {
I think we should template on the `Exponent` or `HalfExponent` if we can't `static_assert` the exponent is even.  We should also take the `epsilon` that you hard-coded to `2.0e-16` as an argument. This is done in `AoWeno.hpp`

2022-05-25 03:13 UTC, yoonso0-0 commented
Changed the reconstructor to a templated version so that user can specify nonlinear exponent and epsilon.

2022-06-01 20:13 UTC, nilsdeppe requested changes
Overall LGTM, some small suggestions you can squash immediately!

2022-06-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Wcns5z.hpp
> +    const std::array alpha_upper{nw_buffer[0], 10.0 * nw_buffer[1],
can you explain where these coefficients come from? My understanding is these are the linear coefficients, but the denominators cancel because of the normalization. That would be good to document with a code comment

2022-06-01 20:13 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/FiniteDifference/Wcns5z.py
> +    b0 = 0.25 * (q[j - 2 * s] - 4 * q[j - s] + 3 * q[j])**2 + (13. / 12) * (
12 -> 12. (several times), same with `4`, etc.

2022-06-01 20:13 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/FiniteDifference/Wcns5z.py
> +    e0 = 2e-16 * (1 + abs(q[j - 2 * s]) + abs(q[j - s]) + abs(q[j]))
1 -> 1. several times

2022-06-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Wcns5z.hpp
> +std::tuple<void (*)(gsl::not_null<std::array<gsl::span<double>, Dim>*>,
Can you make this a trailing return type? Changing it here and in aoweno should make the documentation render in a more readable fashion. Would you mind adding a commit that also changes aoweno to use trailing return type here?

2022-06-01 21:06 UTC, yoonso0-0 commented on src/NumericalAlgorithms/FiniteDifference/Wcns5z.hpp
> +std::tuple<void (*)(gsl::not_null<std::array<gsl::span<double>, Dim>*>,
Sure :)

2022-06-01 21:53 UTC, yoonso0-0 commented
Rebased and squashed fixups, added a separate commit for Aoweno.
Thank you!

2022-06-01 21:58 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Wcns5z.hpp
> +std::tuple<void (*)(gsl::not_null<std::array<gsl::span<double>, Dim>*>,
thanks!

2022-06-01 21:58 UTC, nilsdeppe approved these changes, later dismissed

2022-06-02 05:25 UTC, nilsdeppe commented
Needs a rebase now that develop is fixed

2022-06-02 18:44 UTC, yoonso0-0 commented
Rebased

2022-06-02 18:53 UTC, nilsdeppe submitted a review, later dismissed

2022-06-03 01:02 UTC, nilsdeppe approved these changes

2022-06-03 01:02 UTC, merged