Ignore some warnings from GCC 11
sxs-collaboration/spectre pull request #3987
Opened 2022-05-20 02:02 UTC by knelli2

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-05-20 16:04 UTC, wthrowe requested changes

2022-05-20 16:04 UTC, wthrowe commented on src/Utilities/StaticCache.hpp
> +#if defined(__GNUC__) && !defined(__clang__) && __GNUC__ > 10
Add `&& __GNUC__ < 12` so we'll check if they fix it in each version and can remove the pragmas someday if we don't support any affected versions.

2022-05-20 17:24 UTC, wthrowe approved these changes

2022-05-23 23:32 UTC, nilsdeppe approved these changes

2022-05-23 23:32 UTC, nilsdeppe commented
macOS test failure is unrelated to this PR

2022-05-23 23:33 UTC, merged