Add WCNS5Z + MC reconstruction to finite difference
sxs-collaboration/spectre pull request #4011
Opened 2022-06-01 21:41 UTC by yoonso0-0

## Proposed changes

First two commits are from 
* [ ] #3986 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-06-01 21:51 UTC, yoonso0-0 commented on src/NumericalAlgorithms/FiniteDifference/Wcns5zMc.hpp
> +      return wcns5z.pointwise(q, stride, epsilon);
I tried to avoid copy-pasting all the codes from Wcns5z and MC into here, but I also don't believe this is a very good way in terms of performance. So welcome any suggestions.

2022-06-02 15:02 UTC, nilsdeppe requested changes
You can squash immediately, just a few small changes.

2022-06-02 15:02 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Wcns5zMc.hpp
> +      return wcns5z.pointwise(q, stride, epsilon);
I think you can just do `Wcns5zReconstructor<NonlinearWeightExponent>::pointwise(q, stride, epsilon);` This will give equivalent performance to copy-paste (we'll have to see if that's good or bad later!)

2022-06-02 15:02 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Wcns5zMc.hpp
> +      return mc.pointwise(q, stride);
Same here, `MCR::pointwise..`

2022-06-02 15:02 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Wcns5zMc.hpp
> + * \brief Wcns5z + MC hybrid
Maybe a bit more documentation? :)

2022-06-02 18:55 UTC, yoonso0-0 commented on src/NumericalAlgorithms/FiniteDifference/Wcns5zMc.hpp
> + * \brief Wcns5z + MC hybrid
Sorry :joy: my bad...

2022-06-03 01:03 UTC, nilsdeppe commented
Could you rebase this now that the WCNS5Z PR is merged?

2022-06-03 01:16 UTC, yoonso0-0 commented
Rebased to develop

2022-06-03 01:18 UTC, nilsdeppe approved these changes

2022-06-03 16:29 UTC, merged