Bump compiler versions & reduce number of clang builds
sxs-collaboration/spectre pull request #4019
Opened 2022-06-05 18:07 UTC by nilsdeppe

## Proposed changes

- Bump to GCC 9.1 and clang 9 (allows backporting `std::is_constant_evaluated()` which helps reduce compile time)
- Reduce the number of clang builds we do. This is to make sure all our caches fit into GitHub's 10GB limit.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-06-05 18:22 UTC, kidder requested changes

2022-06-05 18:22 UTC, kidder commented on containers/Dockerfile.buildenv
>  # Install clang-11
update comment (or remove)

2022-06-05 18:31 UTC, nilsdeppe commented on containers/Dockerfile.buildenv
>  # Install clang-11
Done and squashed :)

2022-06-05 18:40 UTC, kidder approved these changes, later dismissed

2022-06-06 19:11 UTC, wthrowe requested changes

2022-06-06 19:11 UTC, wthrowe commented on cmake/CheckCompilerVersion.cmake
>      message(FATAL_ERROR "Clang version must be at least 8.0")
Update error message.

2022-06-07 16:21 UTC, nilsdeppe commented
Squashed and rebased. Thanks for catching that, @wthrowe!

2022-06-07 17:02 UTC, wthrowe approved these changes

2022-06-08 01:39 UTC, kidder approved these changes

2022-06-08 01:40 UTC, merged