Add a global enum class Phase
sxs-collaboration/spectre pull request #4033
Opened 2022-06-10 02:16 UTC by kidder

## Proposed changes

Replace enum class Phase in each executable metavariables with the global one.

- This eliminates a lot of code duplication
- This adds the ability to stream Phases and parse them from an input file
- This makes it easy to add a new phase to all executables
- This will allow the elimination of some template parameters for the phase type
- This will allow the elimination of templating some things on the metavariables if they were only used for getting the phase type

### Upgrade instructions

If you have defined an `enum class Phase` in a metavariables, instead  `#include "Parallel/Phase.hpp"` and replace the enum definition with `using Phase = Parallel::Phase;`

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-06-10 06:06 UTC, nilsdeppe requested changes

2022-06-10 06:06 UTC, nilsdeppe commented on src/Parallel/Phase.cpp
> +std::ostream& operator<<(std::ostream& os, const Parallel::Phase& phase) {
why not put the stream operator in the `Parallel` namespace so ADL works?

2022-06-10 20:06 UTC, nilsdeppe approved these changes
Thank you for doing this :) I think it's a nice simplification and will make it a lot easier to have fewer things templated on the metavariables!

2022-06-13 15:50 UTC, wthrowe approved these changes

2022-06-15 16:57 UTC, merged