Add compute gh quantities
sxs-collaboration/spectre pull request #404
Opened 2017-11-29 21:29 UTC by osheamonn

## Proposed changes

Adds compute pi and phi

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

2017-11-29 22:06 UTC, kidder requested changes

2017-11-29 22:06 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.hpp
> + * metric
formatting

2017-11-29 22:10 UTC, nilsdeppe requested changes
add noexcept's everywhere

2017-11-30 16:20 UTC, nilsdeppe approved these changes

2017-11-30 16:24 UTC, kidder approved these changes

2017-11-30 16:25 UTC, merged