Add inverse and choice of coordinates for Wedge2D
sxs-collaboration/spectre pull request #405
Opened 2017-11-29 22:12 UTC by gsb76

## Proposed changes

The equivalent changes made to Wedge3D are now made to Wedge2D:
Adding an inverse map.
Allowing for the use of equiangular and equidistant coordinates.
The corresponding tests are also added
This needs to be merged before Disk is because Disk needs to be updated to allow the choice of variables.
### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2017-11-29 22:35 UTC, kidder requested changes

2017-11-29 22:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> +/// by interpolating between a circular arc of radius `outer_radius` and a flat
use similar terminology as Wedge3D (i.e radius_of_other and radius_of_circle)

2017-11-29 22:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> +/// +/- x or y axis, and the choice of using either equiangular or equidistant
oriented along the .   end sentence after axis

2017-11-29 22:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
>    explicit Wedge2D(double inner_radius, double outer_radius,
no explicit

2017-11-29 22:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> +  std::array<std::decay_t<tt::remove_reference_wrapper_t<T>>, 2> inverse(
delete comment

2017-11-29 22:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.cpp
>  }
OOPS

2017-11-29 22:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.cpp
>  }
UH OH

2017-11-29 22:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +  ASSERT(direction_of_wedge_.axis() == Direction<2>::Axis::Xi or
we think you are able to remove the assertion about outer_radius > inner_radius

2017-11-29 22:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +  dxdxi = -0.5 * inner_radius_ / sqrt(2.0) + 0.5 * outer_radius_ * one_over_rho;
move all potential DataVectors (i.e. ReturnTypes) as far right as possible in the math

2017-11-29 22:35 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge2D.cpp
> +    CHECK(serialize_and_deserialize(map) == map);
after rebase  replace with test_serialization(map);

2017-12-01 19:09 UTC, kidder submitted a review, later dismissed

2017-12-02 16:16 UTC, nilsdeppe requested changes

2017-12-02 16:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +      with_equiangular_map_(with_equiangular_map) {
noexcept

2017-12-02 16:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +  ASSERT(radius_of_other > 0, "This radius must be greater than zero.");
add same checks as in 3D

2017-12-02 16:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +      0.5 * radius_of_other_ / sqrt(2.0) * (1 - x[0]) +
1 -> 1.0 (twice)

2017-12-02 16:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +      ERROR("Switch failed... somehow?.");
Please make error message explain why it failed

2017-12-02 16:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +                                       ? M_PI_4 * (1 + square(cap_eta))
1 -> 1.0

2017-12-02 16:16 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +      INFO(j);
Use `INFO("i: " << i << " j: " << j);` so that the logged values are useful

2017-12-04 17:56 UTC, nilsdeppe requested changes

2017-12-04 17:56 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
>    ASSERT(radius_of_circle > 0, "This radius must be greater than zero.");
0 -> 0.0

2017-12-04 17:56 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +  const auto cap_eta = with_equiangular_map_
Use a lambda to avoid the copy

2017-12-04 17:56 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +                           : static_cast<ReturnType>(x[1]);
derefence_wrapper

2017-12-04 17:56 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +  ASSERT(radius_of_circle > 0, "This radius must be greater than zero.");
0.0

2017-12-04 23:02 UTC, nilsdeppe requested changes

2017-12-04 23:02 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +    else {
remove else

2017-12-04 23:02 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +  } else {
remove else

2017-12-04 23:02 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +      dxdxi *= -1;
1 -> 1.0

2017-12-05 18:15 UTC, nilsdeppe requested changes

2017-12-05 18:15 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
>        return (direction_of_wedge_.side() == Side::Upper)
Indentation is wrong

2017-12-05 21:16 UTC, nilsdeppe requested changes

2017-12-05 21:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +        make_with_value<ReturnType>(dereference_wrapper(x[1]), 1.0));
replace this line with 1.0

2017-12-05 21:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +        M_PI_4 * (1.0 + square(tan(M_PI_4 * dereference_wrapper(x[1])))));
Use `ReturnType{M_PI_4 * (1.0 + square(tan(M_PI_4 * dereference_wrapper(x[1]))))}`

2017-12-05 21:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +                                      const ReturnType& cap_eta_deriv) {
`const auto&`

2017-12-05 21:16 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge2D.cpp
> +    CAPTURE_PRECISE(gsl::at(lower_right_corner, i));
CAPTURE_PRECISE doesn't work inside scope

2017-12-05 21:16 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge2D.cpp
> +    const std::array<double, 2> test_point{{xi, eta}};
move outside for loop

2017-12-05 22:54 UTC, nilsdeppe approved these changes

2017-12-05 23:54 UTC, wthrowe approved these changes

2017-12-06 04:03 UTC, nilsdeppe commented
The clang-tidy warning is fixed in #399 so I'm merging anyway.

2017-12-06 04:03 UTC, merged