Add get_data_by_element function to VolumeData
sxs-collaboration/spectre pull request #4054
Opened 2022-06-20 19:32 UTC by nilsdeppe

## Proposed changes

Allows retrieving data by each element from the H5 file.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-06-23 17:00 UTC, kidder requested changes

2022-06-23 17:00 UTC, kidder commented on src/IO/H5/VolumeData.cpp
> +  // for (size_t i = 0; i < result.size(); ++i) {
remove

2022-06-23 17:00 UTC, kidder commented on src/IO/H5/VolumeData.hpp
> +  /// \f$[start_observation_value, end_observation_value]\f$.
this does not render correctly as doxygen treats the `_` as subscript markers

2022-06-23 17:00 UTC, kidder commented on src/IO/H5/VolumeData.hpp
> +  auto get_data_by_element(std::optional<double> start_observation_value,
please document what is returned (the return type is not showing up in the detailed description).  Also nice to know what the tuple types correspond to.   Also note how everything is sorted.

2022-06-23 17:00 UTC, kidder commented on tests/Unit/Helpers/IO/VolumeData.cpp
> +      }
is the sorting checked anywhere?  if not please check it

2022-06-23 19:41 UTC, nilsdeppe commented
Squashed and rebased. Thanks for the review :)

2022-06-23 20:20 UTC, kidder submitted a review, later dismissed
LGTM except for the build error

2022-06-24 16:38 UTC, kidder approved these changes

2022-06-24 16:39 UTC, merged