Add MP5 reconstruction to finite difference
sxs-collaboration/spectre pull request #4064
Opened 2022-06-23 22:59 UTC by yoonso0-0

## Proposed changes

The first commit (moving minmod function in `Minmod.py`) is the same one present at #4058 and I included here as well because it's used for test here too.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-07-01 20:13 UTC, nilsdeppe requested changes

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> + * \epsilon \f$ where \f$\epsilon\f$ is a small tolerance value, use $q_{1/2}
what is a reasonable range for `epsilon` or a reasonable value? Having some starting point is useful. Is 1e-16 "reasonable"?

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> + *  q_{i+1/2} = \text{median}(q_{j+1/2}^\text{OR},  q^\text{min}, q^\text{max}).
can you define the `median` with an equation like they do in the paper?

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> +      return 0.5 * (copysign(1.0, x) + copysign(1.0, y)) * min(abs(x), abs(y));
why have an `sgn` function in the code. It's in `Utilities/Math.hpp`. Why not just use that?

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> +             min({abs(w), abs(x), abs(y), abs(z)});
how sure are you that this doesn't do a memory allocation? I would feel safer doing `min(abs(w), min(abs(x), min(abs(y), abs(z))))`

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> +    if ((result[1] - q[0]) * (result[1] - q_mp_plus) > epsilon) {
Can you avoid doing the work on lines 53-57 somehow in the case both upper and lower reconstruction don't need them?

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> + *  d_j     & = q_{j+1} + q_{j-1} - 2q_j        \\
These would be a lot easier to understand if they were written always in descending index order instead of `j+1, j-1, j`

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> +      double q_md = 0.5 * (q[0] + q[stride] - dm4_plus);
maybe add a comment like `// inline q^{AV}`?

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> +      double q_min = max(min({q[0], q[stride], q_md}), min({q[0], q_ul, q_lc}));
same worries here about allocations and copy elision.

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> +      double q_ul = q[0] + alpha * (q[0] - q[-stride]);
Make all these `const`?

2022-07-01 20:13 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> +      double q_ul = q[0] + alpha * (q[0] - q[stride]);
same comments as for above

2022-07-01 20:18 UTC, nilsdeppe commented
since we spell `monotonised_central`, etc. why not spell out this one?

2022-08-19 00:50 UTC, yoonso0-0 commented on src/NumericalAlgorithms/FiniteDifference/Mp5.hpp
> + * \epsilon \f$ where \f$\epsilon\f$ is a small tolerance value, use $q_{1/2}
Spec code is using 0.0 and the Mp5 paper suggests 1e-10. This`epsilon` tolerance is essentially no more than relaxing 'exactly zero' to 'almost equal to zero'.

I don't have a good idea of the answer to this.. I can try a couple of test problems to see how the value of `epsilon` matters. If it doesn't, I think we can just set to zero like spec.

2022-08-19 23:34 UTC, yoonso0-0 commented
@nilsdeppe I splitted fixup into three commits:

- Naming `mp5` -> `monotonicity_preserving_5`
- Other fixups
- Skipping evaluation of temporary `double` variables when limiting is not required for both upper and lower directions.

2022-08-22 16:31 UTC, nilsdeppe reviewed
LGTM, one small dox comment. Please rebase and squash everything including any new changes :)

2022-08-22 16:31 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/MonotonicityPreserving5.hpp
> + * 0\f$ where \f$\epsilon\f$ is a small tolerance value, use $q_{1/2}
Why change `epsilon` -> `0` and then say what `epsilon` is? I would say leave the previous sentence, but add `value (discussed below)`

2022-08-22 17:26 UTC, yoonso0-0 commented
Fixed and squashed. Thanks for the review!

2022-08-22 17:30 UTC, nilsdeppe approved these changes

2022-08-22 20:07 UTC, merged