Add TensorExpression support for assigning to doubles
sxs-collaboration/spectre pull request #4079
Opened 2022-06-29 13:34 UTC by macedo22

## Proposed changes

This PR enables the `TensorExpression` assignment of LHS tensor components to RHS `double`s. More specifically, it adds the overload: `tenex::evaluate<TensorIndices>(gsl::not_null<Tensor<...>*>, double)` and requires the input LHS tensor components already be sized.

Example uses:
1. Assigning all components to the same value
```
// \f$ L_{ab} = -0.5 \f$
tenex::evaluate<ti::a, ti::b>(L, -0.5);
```
2. Assigning different components different values
```
// Given \f$ L_a \f$, \f$ L_i = 1 , L_t = -1 \f$
tenex::evaluate<ti::i>(L, 1.0);
tenex::evaluate<ti::t>(L, -1.0);
```

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-06-29 15:14 UTC, nilsdeppe requested changes

2022-06-29 15:14 UTC, nilsdeppe commented on src/DataStructures/Tensor/Expressions/Evaluate.hpp
> +    auto lhs_multi_index =
I don't understand why you need any multi-index. the storage index is guaranteed to be unique. I'm not sure why you need an impl either, can't this just be:

```cpp
for (auto& component : *tensor) {
  component = rhs_value;
}
```
in the non-impl?

2022-06-29 15:14 UTC, nilsdeppe commented on tests/Unit/DataStructures/Tensor/Expressions/Test_MixedOperations.cpp
> +void test_case5(const DataType& used_for_size) {
maybe name `test_assign_double` or something that's descriptive?

2022-06-29 19:39 UTC, macedo22 commented on src/DataStructures/Tensor/Expressions/Evaluate.hpp
> +    auto lhs_multi_index =
The reason for the mutli-index is that when looping over the LHS indices, we only want to assign the indices requested, which is a subset of the indices if spatial spacetime indices or time indices are used, like in the unit test added and the PR description. I think it's more intuitive and maintainable to check whether a multi-index is evaluated than a storage index.

Example case where it matters:
```
// Given \f$ L_a \f$, \f$ L_i = 1 , L_t = -1 \f$
tenex::evaluate<ti::i>(L, 1.0);
tenex::evaluate<ti::t>(L, -1.0);
```

And now that I think about it, I should probably handle L_t, L_{tt}, L_{ttt}, etc. as a specific case and not loop over all indices. I'll probably add this special handling for this case in a separate PR since it isn't specific to this new `evaluate` overload

2022-06-29 20:30 UTC, macedo22 commented on tests/Unit/DataStructures/Tensor/Expressions/Test_MixedOperations.cpp
> +void test_case5(const DataType& used_for_size) {
I went and renamed all the test case functions because it didn't sit right with me to have the first 4 numbered and the 5th not :laughing:

2022-06-29 23:58 UTC, nilsdeppe reviewed
fixup LGTM. Did you want to add tests or capabilities for the time indices?

2022-06-30 00:12 UTC, macedo22 commented
@nilsdeppe  The unit test added to `Test_MixedOperations.cpp` includes assignment to time indices. Are you asking about additional testing?

2022-06-30 00:14 UTC, nilsdeppe commented
Nope, I misunderstood your comment, sorry!

2022-06-30 00:19 UTC, macedo22 commented
Ah my bad. Yah, above I was referring to short circuiting `evaluate` overloads when the LHS indices are all time indices by not looping over the LHS multi-indices because that's inefficient when we'll only be assigning one LHS component.

2022-06-30 00:50 UTC, nilsdeppe commented
Ah okay, yea, that makes sense. Thanks!

2022-06-30 00:50 UTC, nilsdeppe approved these changes

2022-06-30 01:24 UTC, wthrowe approved these changes

2022-07-01 14:05 UTC, merged