Add temperature to equations of state
sxs-collaboration/spectre pull request #4085
Opened 2022-06-30 12:29 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-06-30 15:37 UTC, kidder requested changes

2022-06-30 15:37 UTC, kidder commented on src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
> +   * Computes the specific internal energy \f$\epsilon\f$ from the rest mass
RIP

2022-06-30 15:37 UTC, kidder commented on src/PointwiseFunctions/Hydro/EquationsOfState/HybridEos.hpp
> + * T =
RIP

2022-06-30 19:16 UTC, kidder submitted a review, later dismissed

2022-06-30 19:30 UTC, teukolsky commented
Question: If p = rho epsilon (Gamma - 1), and p = rho T (ideal gas, p = n k T in usual units), then shouldn't we define T as (Gamma - 1) epsilon instead of just epsilon? Or are we supposed to remember to put the Gamma - 1 by hand afterward?

2022-06-30 19:47 UTC, nilsdeppe commented
I think that's just an arbitrary choice. The temperature has to scale with the specific internal energy. I'm happy to change the definition to include the `(Gamma - 1)` if you prefer (I think that would be more consistent with SpEC anyway)

2022-06-30 19:53 UTC, teukolsky commented
> 

I don't feel strongly about this - I was more concerned about documenting things more clearly. On balance, probably better to include the Gamma - 1. Then getting to Kelvins just involves fundamental constants, independent of Gamma.

2022-06-30 19:58 UTC, nilsdeppe commented
I think that's a good argument for including the `Gamma - 1` (and it'll just be less confusing in general). I'll make that change when I rebase after the test fix for develop is merged!

2022-07-01 14:09 UTC, nilsdeppe commented
Rebased and squashed in change of temperature definition for the ideal gas

2022-07-01 14:16 UTC, kidder approved these changes, later dismissed

2022-07-01 18:24 UTC, kidder approved these changes

2022-07-01 23:18 UTC, merged