Add CompOSE EOS table reader
sxs-collaboration/spectre pull request #4087
Opened 2022-07-01 00:01 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-08-07 23:01 UTC, kidder requested changes
squash

2022-08-07 23:01 UTC, kidder commented on src/IO/ComposeTable.cpp
> +    ERROR("File '" << filename << "' does not exist.");
test your ERRORs or exclude them from coverage

2022-08-09 23:18 UTC, nilsdeppe commented
Added tests for the errors. I needed `file_system::copy` for this and then changed most of our file system library to use `std::filesystem`. This means there's less we need to maintain and should make us more resilient to OS, compiler, etc. switches

2022-08-17 15:17 UTC, kidder requested changes
the failing test does do file manipulation so you need to investigate...

2022-08-17 15:17 UTC, kidder commented on src/Utilities/FileSystem.cpp
> +      // LCOV_EXCL_STOR
?

2022-08-18 17:18 UTC, kidder approved these changes

2022-08-18 21:25 UTC, merged