Monte carlo packets
sxs-collaboration/spectre pull request #4089
Opened 2022-07-01 20:14 UTC by ffoucart

## Proposed changes

Add packets for MC evolutions, and ability to evolve packets along a geodesic

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

Very preliminary; packets cannot at this point be included in actual evolution...

2023-02-27 19:41 UTC, kidder commented on tests/Unit/Evolution/Particles/MonteCarlo/CMakeLists.txt
> +  "Boost::boost;Evolution;Utilities"
you are missing `MonteCarlo` in this list

Better is to update this to the following (which is what we are slowly doing to all test directories):
- Change line 14 to just be an empty list `""`
- Add the following to the end of the file:
```
target_link_libraries(
  ${LIBRARY}
  PRIVATE
  Monte Carlo
  )
```

2023-03-15 17:16 UTC, ffoucart commented
@kidder : The code for the evolution of a single packet for a time step along a geodesic seems to pass the standard tests now. I'm not sure what a more appropriate test would be here; the one I implemented is obviously simplistic. I could write a python function reproducing the whole second-order time stepping, and compare results with random inputs, I guess? It's not clear to me whether we will actually perform time steps using this method, or incorporate the time-stepping within another part of the code once we try to actually move packets on a grid.

Apart from that, I think this PR is ready for review (and, obviously, fairly low priority...).

2024-02-12 21:06 UTC, nilsdeppe requested changes
Looks good! A few small comments you can squash right away when you rebase

2024-02-12 21:06 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +  std::vector<double> dpdt(3, 0);
Can you please change these to `std::array<double, 3>`?

2024-02-12 21:06 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +  const std::vector<double> bottom_coord_mesh{mesh_coordinates.get(0)[0],
Can you please change this and the next `std::vector` to `std::array<double, 3>`?

2024-02-12 21:06 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +    std::vector<size_t> closest_point_index_3d(3, 0);
Can you please change these to `std::array<size_t, 3>`?

2024-02-12 21:06 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.hpp
> +    const gsl::not_null<std::vector<double>*> dt_momentum, const Packet& packet,
When you rebase, clang-tidy may ask you to change this to just `gsl::not_null...` as in, remove the const. Same on lines 35 and 49below.

2024-02-15 16:26 UTC, ffoucart commented
@nilsdeppe More changes than I'd have liked in order to match the latest clang-tidy requirements, but this should be ready for you again. Note that I needed to add a default constructor to the packet struct -- clang-tidy was unhappy with packet creation that did not explicitly set the contents of the packet.

2024-02-15 16:26 UTC, ffoucart commented
(The failing test is some paraview thing... I'm guessing this has nothing to do with this PR)

2024-02-19 16:33 UTC, nilsdeppe approved these changes

2024-02-19 16:33 UTC, nilsdeppe commented
CI failure is some unrelated paraview thing.

2024-02-19 16:34 UTC, merged