Add check for using removed DataBox item
sxs-collaboration/spectre pull request #4123
Opened 2022-07-21 01:54 UTC by kidder

In a debug build, retrieving or mutating an item that was removed
(via RemoveOptionsAndTerminatePHase) will throw an exception.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-07-21 08:31 UTC, nilsdeppe requested changes
Looks good, couple small things. Please squash immediately

2022-07-21 08:31 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +  return get_item<item_tag>().invalidate();
`return` but the function returns `void`. What's going on here?

2022-07-21 08:31 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +  tmpl::for_each<full_mutated_items>([&box](auto tag) {
Wrap `for_each` in `#ifdef SPECTRE_DEBUG`?

2022-07-22 20:00 UTC, nikwit approved these changes
this looks great, probably saved us a lot of debugging hours in the future :+1:

2022-07-22 20:51 UTC, nilsdeppe approved these changes

2022-07-22 21:37 UTC, merged