Add absolute cutoff to ScalarAdvection subcell TCI
sxs-collaboration/spectre pull request #4141
Opened 2022-08-02 21:27 UTC by yoonso0-0

## Proposed changes

Add a TCI option `UCutoff` to the ScalarAdvection subcell. If the max magnitude of the scalar field U on the DG grid is smaller than this `double` type value, Persson TCI is ignored. This fixes "trailing" trouble cells not switching back to DG on the region with U being very small or zero.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2022-08-03 02:25 UTC, yoonso0-0 commented
I'll fix input file errors very soon

2022-08-03 10:48 UTC, nilsdeppe requested changes
LGTM, just one question about the input files. Squash immediately

2022-08-03 10:48 UTC, nilsdeppe commented on tests/InputFiles/ScalarAdvection/Krivodonova1D.yaml
> +  # ? Slabs:
why comment these out? Same question for other input files

2022-08-03 14:55 UTC, knelli2 commented
Thanks @yoonso0-0! I will need this for the ICERM tutorial for showing how we switch between DG and FD using Kuzim.

2022-08-03 22:36 UTC, yoonso0-0 commented
Fixed and squashed

2022-08-04 07:56 UTC, nilsdeppe approved these changes

2022-08-04 07:56 UTC, merged

2022-08-04 14:26 UTC, yoonso0-0 commented
Thanks for the quick review :)