Strahlkorper coords in inertial frame
sxs-collaboration/spectre pull request #4165
Opened 2022-08-15 21:18 UTC by markscheel

## Proposed changes

AH finder: compute inertial coords, not inertial strahlkorper.
    
We no longer need to compute the full Strahlkorper in the
inertial frame.  Computing merely the inertial-frame coords
of the Strahlkorper collocation points will be sufficient.
See #4132 for details.

Depends on (and includes) #4158.

### Upgrade instructions

The full Inertial-frame Strahlkorper is no longer available after horizon finds.  This is ok, because except for spin direction (see #4164) all observables are scalars should be computed in the frame that the Strahlkorper was found, which is more efficient and more straightforward.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-08-15 23:18 UTC, markscheel commented
@geoffrey4444 especially please look at changes to ObserveSurfaceData; the coords that are being output have now been changed.  If this is not ok, I can output the inertial coords again by grabbing the correct thing from the DataBox.

2022-08-16 03:07 UTC, geoffrey4444 commented
> @geoffrey4444 especially please look at changes to ObserveSurfaceData; the coords that are being output have now been changed.  If this is not ok, I can output the inertial coords again by grabbing the correct thing from the DataBox.
> 
> 

We do want inertial frame surface output for visualizing AHs. I'll review when I can but teaching workshop 9:39-4 every day this week. Thanks so much for doing this!

2022-08-16 19:20 UTC, knelli2 commented
I agree with @geoffrey4444 that we want the AH coords (and frame dependent quantities) in the inertial frame. That way we can make movies of inspirals.

2022-08-17 21:47 UTC, markscheel commented
@geoffrey4444 @knelli2 Ok, I agree.  I have changed ObserveSurfaceData back to outputting inertial coords.  I squashed because nobody has looked at this in detail yet.

By the way, note that this PR fixes a bug in ObserveSurfaceData:  Previously the coords that were output, "InertialCoordinates_x", "InertialCoordinates_y", and "InertialCoordinates_z", did not correspond to the same points that the scalars in ObserveSurfaceData were evaluated on (unless the map was a mixture of only scaling and translation, in which case the points agreed by coincidence.)

2022-08-18 00:48 UTC, knelli2 requested changes
You can squash while you're rebasing.

2022-08-18 00:48 UTC, knelli2 commented on src/ApparentHorizons/ObserveCenters.hpp
> + * of the InterpolationTarget.
`static_assert` this

2022-08-18 00:48 UTC, knelli2 commented on tests/Unit/ApparentHorizons/Test_ApparentHorizonFinder.cpp
> -// inertial-frame Strahlkorper should also be in the DataBox.  So this
Only one "the" in the first line.

2022-08-22 15:48 UTC, markscheel commented
Fixed typo, added static_asserts, squashed, rebased.

2022-08-22 15:52 UTC, markscheel commented
(Notice also that ObserveCenters hardcodes Grid frame, so it will need to change when we find horizons in the Distorted frame.  But other things will need to change then too, so waiting for a future PR)

2022-08-22 18:05 UTC, knelli2 submitted a review, later dismissed

2022-08-23 16:01 UTC, markscheel commented
(oops, messed up my static_asserts. fixed)

2022-08-23 16:41 UTC, nilsdeppe approved these changes

2022-08-23 19:30 UTC, merged