Fix frame of GH Tags from Grid to Inertial
sxs-collaboration/spectre pull request #417
Opened 2017-12-04 17:53 UTC by osheamonn

## Proposed changes

Fixes #416 

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

2017-12-04 22:20 UTC, kidder requested changes
Let's template on Frame with a default of Inertial

2017-12-05 19:08 UTC, nilsdeppe commented
:+1: on template parameter

2017-12-05 19:44 UTC, nilsdeppe submitted a review, later dismissed

2017-12-05 19:45 UTC, kidder submitted a review, later dismissed

2017-12-05 19:45 UTC, wthrowe submitted a review, later dismissed

2017-12-05 20:57 UTC, kidder commented
@osheamonn, the build is failing to compile...

2017-12-06 02:47 UTC, nilsdeppe approved these changes

2017-12-06 03:16 UTC, kidder approved these changes

2017-12-06 03:16 UTC, merged