Add executable to convert CompOSE EOS table to SpECTRE table
sxs-collaboration/spectre pull request #4176
Opened 2022-08-19 04:18 UTC by nilsdeppe

## Proposed changes

Add executable to convert CompOSE EOS ASCII table to SpECTRE hdf5 table.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-08-31 19:02 UTC, wthrowe requested changes

2022-08-31 19:02 UTC, wthrowe commented on src/Executables/ConvertComposeTable/ConvertComposeTable.cpp
> +         "HDF5 file. Must contain the .h5 extension.")
The test passes "/EosTable" for this argument, without any extension.

2022-09-01 16:26 UTC, nilsdeppe reviewed
Rebased and squashed the one change in. Thanks for the review @wthrowe!

2022-09-01 16:26 UTC, nilsdeppe commented on src/Executables/ConvertComposeTable/ConvertComposeTable.cpp
> +         "HDF5 file. Must contain the .h5 extension.")
Sigh... Yea, thanks for catching that :D

2022-09-01 18:47 UTC, wthrowe approved these changes

2022-09-01 20:54 UTC, merged