Add cell-centered FD derivatives
sxs-collaboration/spectre pull request #4206
Opened 2022-09-02 22:33 UTC by nilsdeppe

## Proposed changes

This are needed for computing the cell-centered spatial derivatives in the GH system.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-10-10 22:06 UTC, kidder requested changes
you can squash

2022-10-10 22:06 UTC, kidder commented on src/NumericalAlgorithms/FiniteDifference/PartialDerivatives.hpp
> + * `fd::logical_partial_derivative()` function.
derivatives

2022-10-10 22:06 UTC, kidder commented on src/NumericalAlgorithms/FiniteDifference/PartialDerivatives.cpp
> +    return {{0.8 * one_over_delta, 0.2 * one_over_delta,
it would have been easier to review if you kept to a consistent sign convention 😛

2022-10-10 22:06 UTC, kidder commented on src/NumericalAlgorithms/FiniteDifference/PartialDerivatives.cpp
> +      ASSERT(
can't this ASSERT be near the beginning (e.g. line 150) instead of inside the loop?

2022-10-11 14:18 UTC, nilsdeppe commented
Rebased and squashed. Thanks for the review!

2022-10-11 20:02 UTC, kidder approved these changes

2022-10-11 20:02 UTC, merged