Change default InitializeJ in input file for CharacteristicExtract
sxs-collaboration/spectre pull request #4211
Opened 2022-09-07 20:58 UTC by duetosymmetry

## Proposed changes

Keefe and Jordan found that the `ConformalFactor` method for `InitializeJ` works best.

Here we update the input file in `tests/InputFiles/Cce/CharacteristicExtract.yaml` to reflect good default settings for `InitializeJ`.

This PR partially addresses #4209.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-09-08 20:07 UTC, knelli2 requested changes
Thanks for fixing the docs! You can squash immediately.

2022-09-08 20:07 UTC, knelli2 commented on docs/Tutorials/CCE.md
> +    found to perform the better than the other schemes implemented so far.
`perform the better` -> `perform better`

2022-09-08 20:19 UTC, duetosymmetry commented on docs/Tutorials/CCE.md
> +    found to perform the better than the other schemes implemented so far.
Fixed, thanks!

2022-09-08 20:29 UTC, knelli2 approved these changes

2022-09-13 19:59 UTC, wthrowe approved these changes

2022-09-13 19:59 UTC, merged