Fix vector size bug in FreeOutflow boundary condition
sxs-collaboration/spectre pull request #4214
Opened 2022-09-08 18:06 UTC by yoonso0-0

## Proposed changes

* Include `SpatialMetric` and `SqrtDetSpatialMetric` as temporary tags in GRMHD time derivative.
* Move those two tags from gridless tags to temporary tags in FreeOutflow boundary condition class

Current implementation of DG FreeOutflow condition in GRMHD is loading spatial metric and its sqrt determinant from Databox as gridless tags, which means they are retrieved without being projected to an element face. This raises 'Vector size does not match` type of bug when computing conservatives from primitives.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2022-09-15 16:40 UTC, nilsdeppe requested changes
LGTM, one small request, please squash immediately :)

2022-09-15 16:40 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/BoundaryConditions/FreeOutflow.cpp
> +  determinant_and_inverse(make_not_null(&interior_sqrt_det_spatial_metric),
Maybe add a comment as to why this isn't just retrieved? I think I commented on the original PR asking about it :P

2022-09-16 23:37 UTC, yoonso0-0 commented
Rebased and squashed the fix :)

2022-09-17 00:08 UTC, nilsdeppe approved these changes

2022-09-17 03:43 UTC, merged