Allow TimescaleTuner to be initialized with arbitary number of timescales
sxs-collaboration/spectre pull request #4223
Opened 2022-09-13 02:31 UTC by knelli2

## Proposed changes

This will be necessary when we have shape control so we don't have to type out a bunch of the same number in an input file.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-09-13 20:20 UTC, wthrowe requested changes

2022-09-13 20:20 UTC, wthrowe commented on src/ControlSystem/TimescaleTuner.hpp
> +  struct TimescaleCreator {
Move this class to an anonymous namespace in the cpp file.

2022-09-13 20:20 UTC, wthrowe commented on tests/Unit/ControlSystem/Test_Tags.cpp
> +class FakeCreator : public DomainCreator<3> {
Can this test use the `FakeCreator` class added in the previous commit?  They look the same except the other one has option-parsing stuff.

2022-09-13 23:07 UTC, knelli2 commented
Squashed suggested changes directly and rebased.

2022-09-14 18:45 UTC, wthrowe submitted a review, later dismissed

2022-09-15 07:37 UTC, knelli2 commented
@wthrowe I realized I introduced a bug with these changes when I was testing it with the shape map. The `control_system::Tags::Controller` tag uses a timescale tuner when it is created from options, but that tuner wasn't initialized if the number of components hadn't been set yet. The fixup fixes this.

2022-09-16 20:32 UTC, wthrowe commented
OK, squash.

2022-09-16 20:53 UTC, wthrowe approved these changes

2022-09-17 00:37 UTC, merged