Make AlgorithmArray patch work with macOS 13
sxs-collaboration/spectre pull request #4238
Opened 2022-09-20 18:27 UTC by geoffrey4444

## Proposed changes

After upgrading to the macOS 13 public beta, I found that the charm patch for `AlgorithmArray.def.h` no longer worked; instead, I would get an error from the patch command that applying the patch failed.

The patch simply adds a pair of () on one line in `AlgorithmArray.def.h.`

I find that the following equivalent patch, differing only in updating the line numbers and in adding 3 lines of context on either side of the change, works for me on macOS 13.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-09-20 18:56 UTC, nilsdeppe requested changes
Please add a different patch file (might need to generalize CMake to do the check?) because the current patch took a while to get working. This change will break some build somewhere, either older versions of macOS, or some Linux builds. I don't remember if CMake has the ability to discover and check different OS patches, but that could be added.

2022-09-20 20:00 UTC, geoffrey4444 commented
> Please add a different patch file (might need to generalize CMake to do the check?) because the current patch took a while to get working. This change will break some build somewhere, either older versions of macOS, or some Linux builds. I don't remember if CMake has the ability to discover and check different OS patches, but that could be added.

I'll look into having cmake select a different patch file on macOS

2022-09-20 20:49 UTC, geoffrey4444 commented
> Please add a different patch file (might need to generalize CMake to do the check?) because the current patch took a while to get working. This change will break some build somewhere, either older versions of macOS, or some Linux builds. I don't remember if CMake has the ability to discover and check different OS patches, but that could be added.

@nilsdeppe I just force-pushed a change so that my changes are in a separate patch file, as you requested. That file is only used `if(APPLE)`...otherwise, it uses the existing patch file, which is now unchanged.

2022-09-22 06:26 UTC, nilsdeppe approved these changes

2022-09-22 06:26 UTC, merged