Remove Newton-Raphson from UniformCylindricalEndcap
sxs-collaboration/spectre pull request #4246
Opened 2022-09-23 22:36 UTC by markscheel

## Proposed changes

Newton-Raphson is going away, so this PR removes it from UniformCylindricalEndcap.

Newton-Raphson was previously used only for corner cases where the root was barely bracketed.
Now those cases are handled differently.

Also does a few small tweaks of restrictions on map parameters that make the unit tests more robust
(I ran them 20k times without encountering an error)

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-09-23 23:43 UTC, markscheel commented
Uses toms748 so it will fail clang-tidy.

2022-09-24 11:46 UTC, markscheel commented
codecov failure is an error that should never happen (failure of toms748)

2022-09-27 15:26 UTC, nilsdeppe requested changes
LGTM, squash the one thing right away please :)

2022-09-27 15:26 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +              : boost::math::copysign(
https://en.cppreference.com/w/cpp/numeric/math/copysign ?
We also have `sgn` in `Utilities/Math.hpp` depending on exactly what you want

2022-09-27 16:31 UTC, wthrowe reviewed
I have no additional comments.

2022-09-27 23:56 UTC, markscheel commented
changed to std::copysign and squashed.

2022-09-28 00:18 UTC, nilsdeppe approved these changes

2022-09-28 15:53 UTC, wthrowe approved these changes

2022-09-28 15:53 UTC, merged