Start adding support for specifying the initial data in the input file
sxs-collaboration/spectre pull request #4261
Opened 2022-09-28 16:21 UTC by nilsdeppe

## Proposed changes

This PR focuses on changes to generic code to support both the current hard-coded ID and to also support reading from the input file. Once the individual systems are converted we will have significant fewer executables and can much more easily add input file tests to CI since they won't increase build costs.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-10-15 00:30 UTC, kidder requested changes
you can squash the one requested change

you can optionally add test coverage for the clone functions

2022-10-15 00:30 UTC, kidder commented on src/Evolution/Initialization/SetVariables.hpp
> +          "Either ::Tags::AnalyticSolutionOrData or BLAH must be in the "
what is BLAH?

2022-10-24 20:56 UTC, nilsdeppe commented
I've rebased, filled in the tag name, and added tests of the clone functions. Thanks for the review!

2022-10-25 20:41 UTC, kidder approved these changes

2022-10-25 20:41 UTC, kidder commented
ignoring clang-tidy boost error

2022-10-25 20:42 UTC, merged