Add more documentation to YlmSpherepack.
sxs-collaboration/spectre pull request #4264
Opened 2022-09-29 18:44 UTC by markscheel

## Proposed changes

Describe how YlmSpherepack coefficients relate to
standard spherical-harmonic coefficients and real-valued
spherical-harmonic coefficients.

This PR has documentation only.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2022-10-03 19:07 UTC, knelli2 requested changes
You can squash these immediately.

2022-10-03 19:07 UTC, knelli2 commented on src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp
> + * ##### modal and nodal representations
Capitalize `Modal`

2022-10-03 19:07 UTC, knelli2 commented on src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp
> + * for example in Jackson's "Classical Electrodynamics".
Wrap `for example` in commas like `as defined, for example, in`

2022-10-03 19:07 UTC, knelli2 commented on src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp
> + * Jackson's "Classical Electrodynamics")
Same comment as above for `for example`

2022-10-03 19:07 UTC, knelli2 commented on src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp
> + * Note that if \f$g\f$ is real,
Make this a `\note`

2022-10-03 19:07 UTC, knelli2 commented on src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp
> + * ##### Relationship to standard spherical harmonics
Maybe only use four `####` for these headers (here and below)? When I rendered it locally, these headers had a smaller font than the actual text.

2022-10-04 22:08 UTC, markscheel commented
Made changes and squashed.

2022-10-04 22:39 UTC, knelli2 approved these changes

2022-10-07 20:10 UTC, nilsdeppe approved these changes

2022-10-07 20:10 UTC, merged