Add compute_trace.
sxs-collaboration/spectre pull request #429
Opened 2017-12-06 18:16 UTC by markscheel

## Proposed changes

Adds a function that takes the trace of a rank-2 tensor.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2017-12-06 21:21 UTC, kidder requested changes
compute_trace -> trace
check if <> are necessary for get<>
squash

2017-12-06 21:21 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/IndexManipulation.cpp
> +                                    INDEXTYPE(data)>& upper_metric);        \
noexcept

2017-12-06 21:21 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/IndexManipulation.cpp
>            upper_metric);
noexcept

2017-12-07 22:59 UTC, nilsdeppe approved these changes

2017-12-07 22:59 UTC, kidder approved these changes

2017-12-07 22:59 UTC, nilsdeppe commented
"Let's give him some positive feedback." - Larry

2017-12-08 01:06 UTC, merged