Elide DG->FD project when not needed
sxs-collaboration/spectre pull request #4291
Opened 2022-10-12 19:49 UTC by nilsdeppe

## Proposed changes

- Elides the project to FD when all neighbors are doing DG.
- Commit "Add support for receiving DG volume data" is in a separate PR
- Commits are marked as "fixup" because I need to squash them together to get them to compile. This is just easier to review.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-11-08 17:52 UTC, kidder requested changes
you can squash, after fixing the two documentation issues

2022-11-08 17:52 UTC, kidder commented on src/Evolution/DgSubcell/PrepareNeighborData.hpp
> + * `Variables` of the tensors send to the neighbors. The main reason for having
to send to

2022-11-08 17:52 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/PrimitiveGhostData.hpp
> +* \brief Computes the rest mass density \f$\rho\f$, electron fraction
don't delete the space

2022-11-08 18:14 UTC, nilsdeppe commented
Rebased, squashed, and squashed in the dox fixes. Thanks for the review!

2022-11-09 02:08 UTC, kidder approved these changes

2022-11-09 02:08 UTC, merged