Add `ObserveLineSegment` callback
sxs-collaboration/spectre pull request #4295
Opened 2022-10-13 20:12 UTC by nikwit

## Proposed changes

This adds the `ObserveLineSegment` post_interpolation_callback which observes data on a `LineSegment`. The test re-uses parts of `Test_ObserveTimeSeriesAndSurfaceData.cpp`, particularly the MockActionTesting part.

Note that this Action could technically be used on any `InterpolationTarget` since it is never specified in a post_interpolation_callback to be a `LineSegment`. During this week's spectre call the argument was made that more structural information such as quadrature and basis should be included for other InterpolationTargets and one post_interpolation_callback should be written for each one. I agree, that e.g. for a Strahlkorper it would be good to know the basis and quadrature of the inertial coordinates onto which it is interpolated but this will not allow you to fully re-construct the points in the domain since other parameters such as the radius are only given in the input file.

Also, I think that simply outputting data on the points of any interpolation target should be possible and simple. It is ensured that the information can be re-constructed by enforcing that the `InertialCoordinates` are always written to file as well. Some Interpolation targets such as `SpecifiedPoints` would require the exact same post_interpolation_callback since they also carry no structural information.  I would therefore argue that this action should be named something like `ObserveInterpolationTarget` and be used with any target.

2022-10-17 20:45 UTC, knelli2 requested changes
Squash directly.

I don't think this callback can be used generally as is because you hard code the basis and quadratures and that might be different for different targets. So I'd say keep the name for now and when we decide to make everything general we can revisit this an example of how to do so.

2022-10-17 20:45 UTC, knelli2 commented on tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveLineSegment.cpp
> +  // There should be four more threaded actions, so invoke them and check
Four or two?

2022-10-17 20:45 UTC, knelli2 commented on src/ParallelAlgorithms/Interpolation/Callbacks/ObserveLineSegment.hpp
> +        "from the reductions file alone.");
Maybe say `from the output file alone` to avoid explicitly saying reduction just to make it easier in the future when we rename things.

2022-10-18 20:01 UTC, nikwit commented
I squashed in your suggestions, thanks!

Writing volume data requires writing quadrature and basis which is sensible for DG elements and some `InterpolationTarget`s but not for others. For the `LineSegment` there is essentially no structure so I just use `FiniteDifference` and `CellCentered` (there are no cells). It's essentially just a filler since there is no real basis or quadrature to the points, so we need to write the coordinates anyway.

2022-10-18 21:39 UTC, knelli2 submitted a review, later dismissed

2022-11-11 18:37 UTC, markscheel reviewed
Looks good. One suggested change to an error message.  Please squash immediately.

2022-11-11 18:37 UTC, markscheel commented on src/ParallelAlgorithms/Interpolation/Callbacks/ObserveLineSegment.hpp
> +        "from the output file alone.");
I had to read this message a few times to understand what it meant (I first thought it was talking about observing grid coords instead of inertial coords).  How about:

"When observing tensors on a line segment, please include the inertial coordinates in TensorsToObserve.  This is so that the output file contains the coordinates, so then the output file is all that is needed for subsequent visualization or analysis of the output data."

2022-11-14 15:37 UTC, nikwit commented
I changed it to your version of the error message, thanks for your review @markscheel !

2022-11-14 17:50 UTC, knelli2 requested changes

2022-11-14 17:50 UTC, knelli2 commented on tests/Unit/ParallelAlgorithms/Interpolation/Test_ObserveLineSegment.cpp
> +#include "Domain/LogicalCoordinates.hpp"
`Domain/LogicalCoordinates.hpp` doesn't exist. I think you want `NumericalAlgorithms/Spectral/LogicalCoordinates.hpp`.

2022-11-15 17:27 UTC, knelli2 approved these changes

2022-11-17 05:09 UTC, nilsdeppe approved these changes

2022-11-17 05:10 UTC, merged