Remove use of tensor default constructor in GeneralRelativity
sxs-collaboration/spectre pull request #433
Opened 2017-12-07 16:01 UTC by osheamonn

## Proposed changes

Removes use of Tensor's default constructor

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

2017-12-07 16:49 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +      make_with_value<tnsr::aa<DataType, Dim, Frame>>(get<>(lapse), 0.);
@markscheel tested that `get(lapse)` works fine, so no need for the empty angle brackets

2017-12-07 18:08 UTC, kidder requested changes

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/Christoffel.cpp
> +          get<0, 0, 0>(d_metric), 0.);
you should just be able to pass d_metric instead of get<...>(d_metric);  you can pass any object that has the correctly sized underlying DataType

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +      make_with_value<tnsr::aa<DataType, Dim, Frame>>(get<>(lapse), 0.);
just pass lapse

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +      make_with_value<tnsr::AA<DataType, Dim, Frame>>(get<>(lapse), 0.);
just lapse

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +      -1.0 / (get<>(lapse) * get<>(lapse));
Nil's comment about get<> to get still applies to these type of statements

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +      make_with_value<tnsr::abb<DataType, Dim, Frame>>(get<>(lapse), 0.);
lapse

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +  auto phi = make_with_value<tnsr::iaa<DataType, SpatialDim, Frame>>(
deriv_lapse

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +      make_with_value<tnsr::aa<DataType, SpatialDim, Frame>>(get<>(lapse), 0.);
lapse

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/ComputeSpacetimeQuantities.cpp
> +      make_with_value<tnsr::A<DataType, SpatialDim, Frame>>(get<>(lapse), 0.);
lapse

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/IndexManipulation.cpp
> +      get<0, 0>(metric), 0.);
metric

2017-12-07 18:08 UTC, kidder commented on src/PointwiseFunctions/GeneralRelativity/IndexManipulation.cpp
> +          get<0, 0>(upper_metric), 0.);
upper_metric

2017-12-08 19:12 UTC, kidder requested changes
squash

2017-12-08 19:16 UTC, nilsdeppe approved these changes

2017-12-08 19:16 UTC, kidder approved these changes

2017-12-09 03:01 UTC, merged