Support runtime initial data and boundary conditions in ScalarWave
sxs-collaboration/spectre pull request #4336
Opened 2022-11-01 04:22 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-11-09 23:27 UTC, knelli2 requested changes

2022-11-09 23:27 UTC, knelli2 commented on src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
> +      tmpl::append<ScalarWave::Solutions::all_solutions<Dim>>;
[Nitpick] I don't think you need to wrap this in an `append`. It's already a list.

2022-11-09 23:27 UTC, knelli2 commented on src/Evolution/Systems/ScalarWave/BoundaryConditions/DirichletAnalytic.cpp
> +  return {};
`return std::nullopt`?

2022-11-10 20:31 UTC, nilsdeppe commented
Rebased and squashed in changes. thanks for the review!

2022-11-10 22:19 UTC, knelli2 approved these changes

2022-11-16 19:26 UTC, kidder approved these changes

2022-11-16 19:26 UTC, merged