Rename Numerical test tag to NumericalAlgorithms
sxs-collaboration/spectre pull request #436
Opened 2017-12-07 20:23 UTC by kidder

Fixes #434

## Proposed changes

Rename Numerical test tag to NumericalAlgorithms

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2017-12-07 21:28 UTC, nilsdeppe submitted a review, later dismissed

2017-12-07 21:33 UTC, wthrowe submitted a review, later dismissed

2017-12-08 13:08 UTC, nilsdeppe approved these changes

2017-12-08 13:13 UTC, nilsdeppe commented
Note: this "conflicts" with #437 and would require a rebase after that merges

2017-12-08 13:22 UTC, nilsdeppe commented
I'll also note that this one I'd be fine merging before the macOS builds were to complete if it gets rebased, #437 not.

2017-12-08 17:32 UTC, nilsdeppe requested changes
Needs rebase now. I'm requesting a change to prevent accidental merge

2017-12-08 21:59 UTC, nilsdeppe approved these changes

2017-12-08 22:16 UTC, merged