Write domain into H5 volume files
sxs-collaboration/spectre pull request #4378
Opened 2022-11-15 01:56 UTC by nilsvu

## Proposed changes

Reconstructing the domain from volume data files is needed for accurate interpolation onto another set of points (see #3937).

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-11-16 00:29 UTC, nilsdeppe requested changes
Overall LGTM, I just think we should write the domain as a dataset to avoid the size limits of attributes. Please squash immediately :)

2022-11-16 00:29 UTC, nilsdeppe commented on src/IO/H5/VolumeData.cpp
> +    h5::write_to_attribute(observation_group.id(), "domain",
attributes have to be pretty small, I think under 64KB. Are we sure we won't reach that for larger domains? E.g. if the functions of time are written we will probably exceed that with the Shape map. And I think it's the _total_ size of all attributes together needs to be under 64KB. Why not just write this into a dataset instead?

2022-11-16 23:03 UTC, nilsdeppe submitted a review, later dismissed

2022-11-17 17:11 UTC, nilsvu commented
ready for review now! First commit is #4388.

2022-11-17 17:18 UTC, nilsdeppe approved these changes

2022-11-19 19:39 UTC, merged