List Py dependencies in a requirements.txt file
sxs-collaboration/spectre pull request #4432
Opened 2022-11-29 22:49 UTC by nilsvu

## Proposed changes

Makes it easier for users to install the dependencies.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-11-29 23:36 UTC, wthrowe requested changes
Would it be possible to get the lists included in the documentation as snippets or something?  It's kind of nice only having to look in one place to see all the dependencies.  Not a big deal if it is hard.

2022-11-29 23:36 UTC, wthrowe commented on docs/Installation/Installation.md
> +  Make sure you are working in a [Python venv])(https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment)
Extra `)` breaking the link.

2022-11-29 23:36 UTC, wthrowe commented on docs/Installation/Installation.md
> +  Make sure you are working in a [Python venv])(https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment)
Extra paren again.

2022-11-30 05:22 UTC, nilsvu commented
Good idea @wthrowe, added a fixup

2022-11-30 18:14 UTC, wthrowe commented
I didn't know about the "details" thing.  That looks nice.  Squash.

2022-11-30 19:29 UTC, wthrowe approved these changes

2022-11-30 23:11 UTC, nilsdeppe approved these changes

2022-12-01 01:01 UTC, merged