Dump Interpolator volume data on failure
sxs-collaboration/spectre pull request #4437
Opened 2022-11-30 03:58 UTC by knelli2

## Proposed changes

I fixed the issues I was having with this before that prompted me to disable the feature before in #4404.

I added an overload to ContributeVolumeDataToWriter that allows it to be used from the Interpolator.

I also added a tag that allows you to toggle this feature just in case it causes issues in the future, so users can easily disable it.

### Upgrade instructions

If your executable uses the Interpolator parallel component, you'll need to add the following block to your input file:
```yaml
Interpolator:
  DumpVolumeDataOnFailure: false
```

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-12-13 19:05 UTC, nilsdeppe requested changes
You can squash

2022-12-13 19:05 UTC, nilsdeppe commented on src/IO/Observer/VolumeActions.hpp
> +      } else {
`if constexpr (tt::is_maplike_v<...>) {`? Because it looks like you're assuming the data structure is map-like. Having said that, I think the actual requirement is that `tt::is_a_v<std::pair, ...>`

2022-12-13 19:05 UTC, nilsdeppe commented on src/IO/Observer/VolumeActions.hpp
> +        for (const auto& id_and_element : volume_data) {
`const auto& [id, element]`

2022-12-13 19:05 UTC, nilsdeppe commented on src/IO/Observer/VolumeActions.hpp
> +        for (const auto& id_and_element : volume_data) {
`const auto& [id, element]`

2022-12-13 19:05 UTC, nilsdeppe commented on src/ParallelAlgorithms/Interpolation/Actions/DumpInterpolatorVolumeData.hpp
> +      return {Parallel::AlgorithmExecution::Continue, std::nullopt};
Is this actually not tested? If so, could you add a test please?

2022-12-13 19:21 UTC, knelli2 commented on src/IO/Observer/VolumeActions.hpp
> +      } else {
No here I'm trying to check if the "value" of the `std::unordered_map` represented by `VolumeDataAtObsId` is an `ElementVolumeData` or a `std::vector<ElementVolumeData>`. `tmpl::at_c<VolumeDataAtObsId, 1>` gets this "value" and then I check if it's an `ElementVolumeData`. The unordered map is a pair regardless.

2022-12-13 19:21 UTC, nilsvu requested changes
Sorry I forgot about this PR. Looks like a good solution 👍

2022-12-13 19:21 UTC, nilsvu commented on src/ParallelAlgorithms/Interpolation/Actions/DumpInterpolatorVolumeData.hpp
> +    if (not db::get<intrp::Tags::DumpVolumeDataOnFailure>(box)) {
Add `const_global_cache_tags = tmpl::list<intrp::Tags::DumpVolumeDataOnFailure>` to this action. Then you don't have to worry about this elsewhere.

2022-12-13 19:21 UTC, nilsvu commented on src/ParallelAlgorithms/Interpolation/Actions/InitializeInterpolator.hpp
> +  using initialization_tags = tmpl::list<Tags::DumpVolumeDataOnFailure>;
delete this line (see comment above)

2022-12-13 20:07 UTC, knelli2 commented
Rebased and squashed everything in.

2022-12-15 02:05 UTC, nilsdeppe approved these changes

2022-12-15 02:07 UTC, nilsvu approved these changes

2022-12-15 02:07 UTC, merged