Add LegendreGauss points and test
sxs-collaboration/spectre pull request #444
Opened 2017-12-11 17:48 UTC by trevor-vincent

## Proposed changes

1.Generalize CollocationPointsAndWeights class to handle any type of collocation points and weights by templating on the type of collocation point. I had to propagate this change around the code, so many files had to be changed.
2. Add LegendreGauss points as new type of collocation point
3. Add UnitTest for LegendreGauss points that tests in exactly the same was as LegendreGauss points.

### Types of changes:

- [ ] Bugfix
- [x ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [x ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [x ] Code has documentation and unit tests
- [x ] Private member variables have a trailing underscore
- [ x] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [x] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [x ] File lists in CMake are alphabetical
- [x ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [x ] Mark objects `const` whenever possible
- [x ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [x ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [x ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [x ] Prefix commits addressing PR requests with `fixup`

### Further comments

2017-12-11 17:52 UTC, nilsdeppe requested changes
Does not follow code review guidelines.

2017-12-11 23:20 UTC, nilsdeppe requested changes

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.hpp
> +enum class CollocationType { LegendreGauss, LegendreGaussLobatto };
rename to `Quadrature`

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.hpp
>  namespace lgl {
lgl -> `Legendre` and file name.

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.hpp
> +template <CollocationType ct>
Template parameters should be camel case and have useful names

2017-12-11 23:20 UTC, nilsdeppe commented on src/Domain/LogicalCoordinates.cpp
> +  constexpr Basis::lgl::CollocationType LGL =
snake_case

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearOperators/DefiniteIntegral.cpp
> +  constexpr Basis::lgl::CollocationType LGL =
snake_case

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/LinearOperators/DefiniteIntegral.cpp
> +  using Basis::lgl::quadrature_weights;
remove

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +template <CollocationType ct>
camel case template parameter names

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_LiftFlux.cpp
> +  using Basis::lgl::quadrature_weights;
nope

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_LiftFlux.cpp
> +  constexpr Basis::lgl::CollocationType LGL =
snake_case

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_DefiniteIntegral.cpp
> +  constexpr Basis::lgl::CollocationType LGL =
snake_case

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_Linearize.cpp
> +  constexpr Basis::lgl::CollocationType LGL =
snake_case

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_MeanValue.cpp
> +  constexpr Basis::lgl::CollocationType LGL =
snake_case

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_PartialDerivatives.cpp
> +  constexpr Basis::lgl::CollocationType LGL =
snake_case

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_PartialDerivatives.cpp
> +  using CT = Basis::lgl::CollocationType;
plz

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/LinearOperators/Test_PartialDerivatives.cpp
> +  using CT = Basis::lgl::CollocationType;
nerp

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +  DataVector& x = collocation_pts_;
really?

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +  int iter = 0;
move this to where it's used.

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +  constexpr double tol = 4.0 * std::numeric_limits<double>::epsilon();
`constexpr const`

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +  double step = 1.;
rename to `step_size`

move to where it's used

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +    b[i] = static_cast<double>(i) / (i + 1.0);
remove cast

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +    x[i] = x0[i] = -cos(M_PI * (.75 + i) / (0.5 + number_of_pts));
0.75

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +      L0[i] = 1.0;
use expression templates

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +      L1[j] = x[j];
can L0 and/or L1 be `double`s?

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +      step = -L[i] / dL[i];
"global" `step` -> `max_step`, `step` can be local to here

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +    double x2 = x[i] * x[i];
make `const`, fix elsewhere if applicable

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +    w[i] = 2.0 / ((1 - x2) * (dL[i] * dL[i]));
remove extra parens

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +        i % 2 == 0 ? sqrt((1 - x2) * w[i]) : -sqrt((1 - x2) * w[i]);
1 -> 1.0

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +    w[i] = 2.0 / ((1 - x2) * (dL[i] * dL[i]));
1 -> 1.0

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +  DataVector L1(number_of_pts);
move these down to where they're used

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.cpp
> +template <CollocationType ct>
camel case

2017-12-11 23:20 UTC, nilsdeppe commented on src/NumericalAlgorithms/Spectral/LegendreGaussLobatto.hpp
>  namespace lgl {
Then class template on `Quadrature` enum

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/Spectral/Test_LegendreGaussLobatto.cpp
> +  constexpr Basis::lgl::CollocationType LGL =
snake_case!!!!

2017-12-11 23:20 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/Spectral/Test_LegendreGaussLobatto.cpp
> +  constexpr Basis::lgl::CollocationType LG =
Be consistent with GL vs LG on line 18

2017-12-12 17:22 UTC, trevor-vincent commented
Closing this pull request because we are moving to a different design involving a Legendre class.

2018-03-15 14:22 UTC, nilsdeppe commented
This is stale and being superseded by #543

2018-03-15 14:22 UTC, closed without merging