Add dispatch function for gauge conditions
sxs-collaboration/spectre pull request #4441
Opened 2022-12-01 00:11 UTC by nilsdeppe

## Proposed changes

This handles forwarding the correct arguments to the gauge condition.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-12-01 01:48 UTC, knelli2 requested changes
Squash directly.

2022-12-01 01:48 UTC, knelli2 commented on tests/Unit/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Test_DampedHarmonic.cpp
> +  // gauge.
`don't need for DH`

2022-12-01 05:36 UTC, nilsdeppe commented
Fixed, squashed, and rebased. Thanks for the quick review! :D

2022-12-01 21:25 UTC, knelli2 approved these changes, later dismissed

2022-12-01 21:25 UTC, knelli2 commented on src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Dispatch.cpp
> +        "condition.");
[Optional] Add `LCOV` statements.

2022-12-01 23:33 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/Dispatch.cpp
> +        "condition.");
Done!

2022-12-02 00:47 UTC, knelli2 approved these changes

2022-12-02 00:48 UTC, kidder approved these changes

2022-12-02 03:59 UTC, merged