Add filters for FD, e.g. KO dissipation
sxs-collaboration/spectre pull request #4443
Opened 2022-12-01 19:41 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-12-02 18:01 UTC, nilsdeppe commented on src/NumericalAlgorithms/FiniteDifference/Filter.cpp
> +      ERROR("Cannot do finite difference derivative of order " << fd_order);
Change wording of error

2022-12-06 22:46 UTC, kidder requested changes
you can squash

2022-12-06 22:46 UTC, kidder commented on tests/Unit/NumericalAlgorithms/FiniteDifference/Test_Filter.cpp
> +      // Get only the KO dissipation term by subtracting off the volume
this is not KO so I am confused by the comment

2022-12-06 22:46 UTC, kidder commented on src/NumericalAlgorithms/FiniteDifference/Filter.hpp
> + *  \mathcal{D}^{(2)}f_i&=-\frac{\epsilon}{\Delta x}\epsilon
extra epsilon

2022-12-07 06:07 UTC, nilsdeppe commented
Rebased, fixed, and squashed. Thanks for the review :D

2022-12-07 18:34 UTC, kidder approved these changes

2022-12-08 17:08 UTC, merged