Use runtime gauge condition in GH
sxs-collaboration/spectre pull request #4450
Opened 2022-12-03 01:26 UTC by nilsdeppe

## Proposed changes

Switches GH to using a runtime gauge condition specified in the input file.

Only last two commits are new.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-12-06 21:47 UTC, kidder requested changes
you can squash

2022-12-06 21:47 UTC, kidder commented on src/Evolution/Systems/GrMhd/GhValenciaDivClean/TimeDerivativeTerms.hpp
> +      // db::const_item_type<GhArgTags, tmpl::list<>>... gh_args,
remove?

2022-12-07 06:08 UTC, nilsdeppe commented
Rebased and squashed. Thanks for the review!

2022-12-07 17:53 UTC, knelli2 reviewed
Couple comments. If you decide to make the changes you can squash directly.

2022-12-07 17:53 UTC, knelli2 commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp
> -                                                          Frame::Inertial>,
Will I still be able to observe the gauge and it's derivative? I see the compute tag is added to `non_tensor_compute_tags` below, but the gauge and deriv tags are removed from the `observe_fields` list.

2022-12-07 17:53 UTC, knelli2 commented on src/Evolution/Executables/GeneralizedHarmonic/GeneralizedHarmonicBase.hpp
> +          gr::Tags::SpatialMetric<volume_dim, frame, DataVector>,
If you add the gauge and deriv back to the BBH executable, can you also add them here?

2022-12-07 18:32 UTC, nilsdeppe commented
Done and added `GaugeH` to the Kerr input file so as to keep checking for it in the future

2022-12-07 18:38 UTC, knelli2 approved these changes

2022-12-07 18:38 UTC, kidder approved these changes

2022-12-07 23:21 UTC, merged