Add extra use case to UniformCylindricalSide
sxs-collaboration/spectre pull request #4453
Opened 2022-12-03 02:14 UTC by markscheel

## Proposed changes

 In the case where z_plane_plus_one=z_plane_plus_two or z_plane_minus_one=z_plane_minus_two, no longer demand that z_plane_plus_one and z_plane_minus_one are on the opposite sides of the equator of sphere_one.
    
 This is important for the case of the BBH cylindrical domain where there are extra cylindrical outer shells (what SpEC calls "SphereC"s).  We cannot make SphereCs without this PR.
    
This commit does not change the map at all: it changes only the set of allowed input parameters, the parameters that are used in the test, and the documentation. (Sorry I didn't realize I needed this use case until after UniformCylindricalSide was merged).

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2022-12-04 05:55 UTC, nilsdeppe approved these changes, later dismissed

2022-12-05 00:39 UTC, markscheel commented
I just made one change (and squashed it immediately):  I told codecov to ignore a lambda that for some reason it doesn't see even though the lambda is used in all the ASSERTs below it.

2022-12-05 00:45 UTC, nilsdeppe submitted a review, later dismissed

2022-12-05 16:36 UTC, knelli2 requested changes
One small dox change. Squash directly

2022-12-05 16:36 UTC, knelli2 commented on src/Domain/CoordinateMaps/UniformCylindricalSide.hpp
> + * \f$z^+_{\mathrm{P}1} &\geq z^-_{\mathrm{P}1}\f$.
Extraneous `&`. Docs not loading properly.

2022-12-05 22:41 UTC, markscheel commented
Fixed the `&` and squashed.

2022-12-05 22:48 UTC, nilsdeppe approved these changes

2022-12-05 23:01 UTC, knelli2 approved these changes

2022-12-06 02:11 UTC, merged