CylindricalBinaryCompactObject: use new maps.
sxs-collaboration/spectre pull request #4469
Opened 2022-12-07 18:00 UTC by markscheel

Now uses UniformCylindricalEndcap, UniformCylindricalSide, and UniformCylindricalFlatEndcap instead of the old maps CylindricalEndcap, CylindricalSide, CylindricalFlatEndcap.

Also now has the option to add an extra outer cylindered-sphere shell, and to add an extra inner cylindered-sphere shell for either of the excised regions.

Does not yet handle time-dependent maps in the way we want it to, but that can be the next PR.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2022-12-07 20:07 UTC, knelli2 requested changes
Just some minor dox things. Squash directly. Other than that, looks great! Excited to try this out soon!

2022-12-07 20:07 UTC, knelli2 commented on src/Domain/Creators/CylindricalBinaryCompactObject.hpp
> + *   blocks. They all border the inner boundary "B"if
Missing space between `"B"` and `if`

2022-12-07 20:07 UTC, knelli2 commented on src/Domain/Creators/CylindricalBinaryCompactObject.hpp
>   * The Blocks are named as follows:
The line below this is missing a comma. Can't reach it with code comments though. I know this isn't related to your changes but I just noticed it while reading the docs.

2022-12-07 21:28 UTC, markscheel commented
Made changes and squashed.
Also added a new fixup commit that removes some strange codecov errors.

2022-12-08 17:44 UTC, knelli2 reviewed
Fixups look good, you can squash. Yeah codecov occasionally does really stupid things like saying a function call is not tested when it most definitely is. No clue why.

2022-12-08 18:04 UTC, markscheel commented
Squashed.

2022-12-08 19:13 UTC, knelli2 approved these changes

2023-01-09 17:39 UTC, geoffrey4444 approved these changes
I don't have any further code suggestions to add. 

I tested this domain (with #4526 and #4491) and was able to evolve a BBH with it. I noticed constraints in the added inner spheres were large and did not converge well with increasing refinement there. I suspect we want something like the Logarithmic spacing option in BinaryCompactObject, but that would be for a future PR.

2023-01-12 04:50 UTC, nilsdeppe approved these changes

2023-01-12 16:10 UTC, merged