Eliminate remaining redundant computation from damped harmonic
sxs-collaboration/spectre pull request #4480
Opened 2022-12-08 17:15 UTC by nilsdeppe

## Proposed changes

Only `Pass Pi and Phi contracted with normals to DH` is new

I believe this eliminates the remaining redundant computations that the damped harmonic gauge ends up doing that are already done in the RHS. 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-12-09 18:18 UTC, kidder requested changes
squash

2022-12-09 18:18 UTC, kidder commented on src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp
> +  // d_t lapse / lapse = 0.5 * n^a n^b (alpha Pi_{ab} - shift^i Phi_{iab})
alpha -> lapse

2022-12-09 18:18 UTC, kidder commented on src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp
> +      // Note:  \f$ \partial_a n_b = {-\partial_a alpha, 0, 0, 0} \f$
alpha -> lapse

2022-12-09 18:18 UTC, kidder commented on src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp
> +  // d_t lapse / lapse = 0.5 * n^a n^b (alpha Pi_{ab} - shift^i Phi_{iab})
alpha -> lapse

2022-12-09 18:36 UTC, nilsdeppe commented
Rebased and squashed. No more `alpha` in the file :D Thanks for the review!

2022-12-09 18:40 UTC, kidder approved these changes

2022-12-09 23:11 UTC, knelli2 approved these changes
Just rebase develop.

2022-12-10 01:35 UTC, merged

2022-12-10 01:36 UTC, nilsdeppe commented
I'd rebased on the other branch, so the commits were identical :)