Add post interp callback to dump metric data in Bondi-Sachs form
sxs-collaboration/spectre pull request #4489
Opened 2022-12-09 20:24 UTC by knelli2

## Proposed changes

This adds a new PostInterpolationCallback that will take metric data on concentric extraction spheres, convert it to the Bondi-Sachs form, and dump it to a separate file for each extraction radius. The format of the output data and the filenames are chosen so that it can be read in with the CCE executable.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments
Depends on and includes #4460.

2022-12-16 20:04 UTC, wthrowe requested changes

2022-12-16 20:04 UTC, wthrowe commented on src/Evolution/Systems/Cce/OptionTags.hpp
> +      "Filename prefix for dumbing Bondi-Sachs data on worltube radii. Files "
"dumping"

2022-12-16 20:04 UTC, wthrowe commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +    ASSERT(sphere.angular_ordering == intrp::AngularOrdering::Cce,
ERROR, as this is controlled from the input file.

2022-12-16 20:04 UTC, wthrowe commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> + * - `::Tags::deriv<GeneralizedHarmonic::Tags::Phi>`
I don't see any uses of `deriv<Phi>`.  Why does it have to be there?

2022-12-16 20:04 UTC, wthrowe commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +    Variables<gh_source_vars_for_cce> tmp_buffer;
You never allocate any memory in this buffer.  It's not saving you anything, and I don't think changing the `data()` value in a `Variables`-backed `Tensor` is a supported operation.

2022-12-16 20:04 UTC, wthrowe commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +      ComplexModalVector goldberg_mode_buffer{square(l_max + 1)};
These two *are* allocations inside the loop, so moving them outside would help.

2022-12-16 20:04 UTC, wthrowe commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +      const std::vector<std::string> real_legend = build_legend(l_max, true);
These two lines may cause the majority of the allocations in this function.  Move them out of the loop.

2022-12-16 20:04 UTC, wthrowe commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +              for (int m = is_real ? 0 : -ell; m <= static_cast<int>(ell);
Cast the first `ell` too.

2022-12-17 05:37 UTC, knelli2 commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +    Variables<gh_source_vars_for_cce> tmp_buffer;
Well I need a `Variables` of g, pi, phi that only has one sphere's worth of points in order to pass to `create_bondi_data` for each extraction radius. Any suggestions on how to do that then without a copy? I already have all the data in `all_gh_vars` for all extraction spheres, Just need to split it up a bit.

2022-12-17 16:09 UTC, wthrowe commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +    Variables<gh_source_vars_for_cce> tmp_buffer;
You're not passing this to anything, and it has zero points.

Avoiding the copies with non-owning DataVectors is good.  I just don't understand why you want an empty temporary buffer.

2022-12-17 16:59 UTC, knelli2 commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +    Variables<gh_source_vars_for_cce> tmp_buffer;
Oh I see what you mean. I used a `Variables` just to easily get un-allocated tensors for g, pi, and phi so I could set their data refs when I loop over the radii. I guess I could have explicitly wrote out the unallocated tensors, but that was more lines so I didn't.

2022-12-17 17:14 UTC, wthrowe commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +    Variables<gh_source_vars_for_cce> tmp_buffer;
It's three lines instead of two.

2022-12-17 19:31 UTC, knelli2 commented on src/Evolution/Systems/Cce/Callbacks/DumpBondiSachsOnWorldtube.hpp
> +    Variables<gh_source_vars_for_cce> tmp_buffer;
Ok I changed it.

2023-01-06 19:51 UTC, wthrowe approved these changes, later dismissed
Looks good.  Squash.

2023-01-12 16:23 UTC, nilsdeppe approved these changes
I don't love that we need a new file for each extraction radius, but I assume that's a current requirement of CCE, right? I'm fine leave as-is for now, but we should probably combine them into the reductions file at some point (or maybe one CCE file with subfiles)

2023-01-12 16:23 UTC, nilsdeppe commented
CI failure is timeout in binary compact object test.

2023-01-12 16:23 UTC, merged

2023-01-12 17:46 UTC, knelli2 commented
@nilsdeppe Yes the reason I did it like this is because currently CCE is set up to read in metric data which is output from SpEC in a specific format (different files for each radius, named a certain way). I agree eventually it'd be nice to have CCE read in data from SpECTRE in our own format, but that's a whole change to CCE which is why I didn't bother doing it here. Just wanted to get waveforms working quickly.

2023-01-12 17:49 UTC, nilsdeppe commented
Okay, thanks for clarifying! I completely agree, getting it into one file is a much bigger change and very low priority :) Thanks!