FixedSpeedCubic: add stream operator.
sxs-collaboration/spectre pull request #4490
Opened 2022-12-09 22:16 UTC by markscheel

This makes it easier to debug things.
Other FunctionsOfTime have stream operators.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2022-12-09 23:54 UTC, knelli2 requested changes

2022-12-09 23:54 UTC, knelli2 commented on src/Domain/FunctionsOfTime/FixedSpeedCubic.cpp
> +std::ostream& operator<<(
Could you add a simple test? Just something that checks the output?

2022-12-10 01:38 UTC, knelli2 submitted a review, later dismissed
Looks good, you can squash.

2022-12-10 01:41 UTC, nilsdeppe reviewed
LGTM, please ping me when it's squashed and I'll merge :)

2022-12-12 17:47 UTC, markscheel commented
Squashed.

2022-12-12 17:59 UTC, knelli2 commented
@nilsdeppe Been squashed.

2022-12-12 18:13 UTC, nilsdeppe approved these changes

2022-12-12 21:18 UTC, merged