Add subcell observer Jacobian tags
sxs-collaboration/spectre pull request #4494
Opened 2022-12-10 19:17 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-12-10 19:41 UTC, kidder requested changes
squash

2022-12-10 19:41 UTC, kidder commented on tests/Unit/Evolution/DgSubcell/Test_Tags.cpp
> +      ::Events::Tags::ObserverCoordinates<Dim, Frame::Grid>>("GridCoordinates");
add calls to TestHelpers::db::test_compute_tag for your new compute tags

2022-12-11 02:06 UTC, nilsdeppe commented on tests/Unit/Evolution/DgSubcell/Test_Tags.cpp
> +      ::Events::Tags::ObserverCoordinates<Dim, Frame::Grid>>("GridCoordinates");
Done! Also added a test for moving mesh map

2022-12-11 02:17 UTC, kidder approved these changes

2022-12-12 20:09 UTC, merged