Fix a bug at roundoff error in block_logical_coords
sxs-collaboration/spectre pull request #4510
Opened 2022-12-13 01:58 UTC by nilsvu

This bug appeared when interpolating between two BBH domains with bulged frustums. Points at inner frustum edges were not mapped to the source domain because the frustum inverse reports logical coordinates outside [-1, 1] by roundoff error.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2022-12-13 02:03 UTC, kidder requested changes
please add a test that would fail/pass before/after this change

2022-12-13 15:11 UTC, markscheel commented
Should this bug be fixed in Frustrum instead?  (That is, should Frustrum be changed to never return logical coords outside of [-1,1]?  ).

I worry that this change ignores #3913 and similar places where we assume logical coords are 1.0 and/or -1.0 on the boundary.

2022-12-13 16:25 UTC, nilsvu commented
Many map inverses currently return values outside -1,1. Yea, maybe we should require all maps to ensure they return only values within their range. That's a lot of work though and needs to be tested thoroughly. Not all maps inverses return logical coords either, right? I haven't made up my mind on what's the best way to handle this.

2022-12-13 17:30 UTC, kidder commented
- So as @markscheel says checking exact vs checking within roundoff should probably be a choice of the user of this function.  
- The testing of maps needs to be done on the maps held by the Blocks, which are usually a composition of multiple maps, not individual maps.

2022-12-16 03:31 UTC, nilsvu commented
This is now ready to review for whoever wants to @kidder @markscheel @nilsdeppe @wthrowe

2022-12-16 04:30 UTC, nilsdeppe approved these changes
LGTM

2022-12-16 18:52 UTC, wthrowe approved these changes

2022-12-16 21:15 UTC, kidder approved these changes

2022-12-16 21:16 UTC, merged