Improvements and bug fixes for GHMHD evolutions, part 0
sxs-collaboration/spectre pull request #4602
Opened 2023-01-12 21:54 UTC by nilsdeppe

## Proposed changes

Communicate TCI decision to neighbors for halo FD elements (will be added in next PR).

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-01-13 16:34 UTC, kidder requested changes
you can squash

2023-01-13 16:34 UTC, kidder commented on src/Evolution/DgSubcell/Tags/TciStatus.hpp
> +/// Stores the status of the troubled cell indicator in the element as a.
as an int?

2023-01-16 06:40 UTC, nilsdeppe commented on src/Evolution/DgSubcell/Tags/TciStatus.hpp
> +/// Stores the status of the troubled cell indicator in the element as a.
done, rebased, squashed :)

2023-01-17 02:25 UTC, kidder approved these changes

2023-01-17 02:26 UTC, merged