Add Rusanov boundary correction to ForceFree system
sxs-collaboration/spectre pull request #4609
Opened 2023-01-13 20:41 UTC by yoonso0-0

## Proposed changes

The first commit is from #4440 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-01-21 20:33 UTC, nilsdeppe requested changes
You can squash immediately

2023-01-21 20:33 UTC, nilsdeppe commented on src/Evolution/Systems/ForceFree/BoundaryCorrections/Rusanov.cpp
> +Rusanov::Rusanov(CkMigrateMessage* /*unused*/) {}
`: BoundaryCorrection(msg) {}`

2023-01-24 00:15 UTC, yoonso0-0 commented
Squashed and rebased

2023-01-24 00:37 UTC, nilsdeppe approved these changes

2023-01-24 05:45 UTC, merged