Rename inputs to functions in CoordinateMaps
sxs-collaboration/spectre pull request #461
Opened 2017-12-15 22:09 UTC by gsb76

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2017-12-15 23:40 UTC, kidder requested changes
oh Gabe, make it better:  no frame

2017-12-15 23:40 UTC, kidder commented on src/Domain/CoordinateMaps/AffineMap.cpp
>  template std::array<double, 1> AffineMap::inverse(
inverse should take target_coords

2017-12-15 23:40 UTC, kidder commented on src/Domain/CoordinateMaps/AffineMap.cpp
>  template std::array<double, 1> AffineMap::inverse(
check them all

2017-12-15 23:40 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +Wedge3D::jacobian(const std::array<T, 3>& source_frame) const noexcept {
source_frame -> source_coords

2017-12-15 23:40 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +                     3>& /*source_coords*/) const noexcept;
inverse should take target_coords

2018-01-24 04:42 UTC, kidder requested changes

2018-01-24 04:42 UTC, kidder commented on src/Domain/CoordinateMaps/Rotation.cpp
> +    const std::array<std::reference_wrapper<const double>, 3>& source_coords)
target_coords

2018-01-24 04:42 UTC, kidder commented on src/Domain/CoordinateMaps/Rotation.cpp
> +    const std::array<double, 3>& source_coords) const;
target_coords

2018-01-24 04:42 UTC, kidder commented on src/Domain/CoordinateMaps/Rotation.cpp
> +        source_coords) const;
target_coords

2018-01-24 04:42 UTC, kidder commented on src/Domain/CoordinateMaps/Rotation.cpp
> +    const std::array<DataVector, 3>& source_coords) const;
target_coords

2018-01-25 23:00 UTC, kidder reviewed
Please rebase and squash

2018-01-26 21:48 UTC, wthrowe requested changes

2018-01-26 21:48 UTC, wthrowe commented on src/Domain/CoordinateMaps/Identity.cpp
> +                     2>& /*source_coords*/) const;
`target_coords`

2018-01-26 21:48 UTC, wthrowe commented on src/Domain/CoordinateMaps/Identity.cpp
> +    const std::array<double, 2>& /*source_coords*/) const;
`target_coords`

2018-01-26 21:48 UTC, wthrowe commented on src/Domain/CoordinateMaps/Identity.cpp
> +                     2>& /*source_coords*/) const;
`target_coords`

2018-01-26 21:48 UTC, wthrowe commented on src/Domain/CoordinateMaps/Identity.cpp
> +    const std::array<DataVector, 2>& /*source_coords*/) const;
`target_coords`

2018-01-26 21:48 UTC, wthrowe commented on src/Domain/CoordinateMaps/ProductMaps.hpp
> +    const std::array<T, Size>& source_coords, const Map1& map1,
This function is used with both `source_coords` and `target_coords` (for `operator()` and `inverse`, respectively).  Maybe just `coords`?

2018-01-27 02:16 UTC, kidder commented
please rename files in a separate commit

2018-01-29 22:13 UTC, kidder requested changes
fix the warning

2018-01-31 20:46 UTC, kidder requested changes
fix the commented arguments

2018-01-31 21:04 UTC, kidder reviewed
squash

2018-01-31 21:48 UTC, nilsdeppe approved these changes

2018-01-31 23:08 UTC, kidder approved these changes

2018-01-31 23:12 UTC, wthrowe approved these changes

2018-01-31 23:15 UTC, merged