Add the fast wave analytic solution to ForceFree system
sxs-collaboration/spectre pull request #4615
Opened 2023-01-17 23:22 UTC by yoonso0-0

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-01-24 18:17 UTC, yoonso0-0 commented
I don't have a good idea on how to fix this clang-tidy error..

2023-01-27 16:48 UTC, nilsdeppe requested changes
Please squash immediately

2023-01-27 16:48 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticSolutions/ForceFree/FastWave.cpp
> +DataVector FastWave::initial_profile(const DataVector& x) {
how about `x` -> `coords` and `xi` -> `x`? `xi` is the logical coordinate so I get very confused here. Or maybe `xi` -> `local_x`, or `xi` -> `x` & `x` -> `x_coords`. I kinda like the last.

2023-01-28 05:29 UTC, nilsdeppe approved these changes

2023-01-28 05:29 UTC, merged