Add Punctures analytic data and executable
sxs-collaboration/spectre pull request #4635
Opened 2023-01-21 01:12 UTC by nilsvu

## Proposed changes

This allows to solve for any set of superposed punctures.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-01-29 20:43 UTC, nilsdeppe requested changes
You can squash immediately

2023-01-29 20:43 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
> +        "The angular momentum S of the puncture"};
What are the bounds? Is this the dimensionless spin?

2023-01-29 20:43 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
> +        "The linear momentum P of the puncture"};
In what units?

2023-01-31 05:25 UTC, nilsvu commented on src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
> +        "The angular momentum S of the puncture"};
These are the Bowen-York linear and angular momentum parameters in the puncture equation. They are not dimensionless. I extended the help string a bit. These are the standard parameters in the punctures ID literature.

2023-01-31 05:26 UTC, nilsvu commented on src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
> +        "The linear momentum P of the puncture"};
See comment above

2023-01-31 06:02 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
> +        "The angular momentum S of the puncture"};
Isn't there a BH associated with the puncture that has a mass, spin and angular momentum? This thing has to have some form of units... What units are you using?

2023-01-31 17:44 UTC, nilsvu commented on src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
> +        "The angular momentum S of the puncture"};
I don't know what other units to put here than P scaling linearly in mass and S scaling quadratically. We're in c=G=1 so there's only a mass scale m, and you can choose it. P/m is dimensionless and S/m^2 is dimensionless. The punctures literature usually chooses P and S including mass factors. You would set P^x=mv for example. So I can't think of anything to add here.

2023-01-31 18:08 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
> +        "The angular momentum S of the puncture"};
Okay, that clarifies thing. I think the important thing is to clearly define that `P^x=mv` ,etc. Can you use the dimensionless spin instead? That's what we use everywhere else and is just easier to work with. I don't know about the linear momentum, but specifying the velocity in the range `[0, 1]` naively seems more intuitive to me, but I don't have any experience with the linear momentum. Is this the coordinate momentum then? So it is bounded above by the coordinate speed of light? These are all very important details that are currently not documented and, from experience, will make it challenging for someone to use. Getting units right usually ends up being a non-negligible part of the battle.

2023-01-31 18:50 UTC, nilsvu commented on src/PointwiseFunctions/AnalyticData/Punctures/MultiplePunctures.hpp
> +        "The angular momentum S of the puncture"};
Ok, using the dimensionless spin and momentum seem more useful to me too. The bare mass of each puncture is an unambiguous parameter, so it's easy to rescale spin and momentum when comparing to there codes. Pushed a fixup.

2023-01-31 22:58 UTC, nilsdeppe reviewed
LGTM, thanks for making the change! Please go ahead and squash&rebase

2023-02-03 17:21 UTC, nilsdeppe approved these changes

2023-02-03 17:21 UTC, merged