Add scalar wave rhs
sxs-collaboration/spectre pull request #464
Opened 2017-12-17 18:48 UTC by nilsdeppe

## Proposed changes

- Add ability to call specific constructor via `make_array`
- Change to the new `make_array` call in `Tensor`
- Add ScalarWave tags
- Add ScalarWave RHS

I'm planning on adding the flux equations in a separate PR that will be dependent on this PR.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

2017-12-17 22:09 UTC, wthrowe requested changes

2017-12-17 22:09 UTC, wthrowe commented on tests/Unit/Utilities/Test_MakeArray.cpp
> +    CHECK(vector_array1[0] == (std::vector<int>(3, 9)));
Again.

2017-12-17 22:09 UTC, wthrowe commented on tests/Unit/Utilities/Test_MakeArray.cpp
> +    CHECK(vector_array2[0] == (std::vector<int>{3, 9, 12, -10}));
Again.

2017-12-17 22:09 UTC, wthrowe commented on tests/Unit/Utilities/Test_MakeArray.cpp
> +    CHECK(noncopyable_vectors[0].get() == (std::vector<double>{2.3, 8.6, 9.7}));
Shouldn't this depend on the loop index somehow?

2017-12-17 22:09 UTC, wthrowe commented on src/Evolution/Systems/ScalarWave/Equations.hpp
> + * 159, or wikipedia.
`Wikipedia` (proper noun)

2017-12-17 22:09 UTC, wthrowe commented on src/Evolution/Systems/ScalarWave/System.hpp
> +#include "DataStructures/Variables.hpp"
These first two includes are unused.

2017-12-17 22:21 UTC, kidder requested changes

2017-12-17 22:21 UTC, kidder commented on src/Utilities/MakeArray.hpp
> +template <bool SizeZero>
please update the comment; there is no `indexes` or `value` or `size`

2017-12-17 22:21 UTC, kidder commented on src/Utilities/MakeArray.hpp
> + * \tparam T the type of the element is the array
is -> in

2017-12-17 22:21 UTC, kidder commented on src/Utilities/MakeArray.hpp
> + * \brief Create a `std::array<T, size>{{T(args...), T(args...), ...}}`
size -> Size

2017-12-17 22:21 UTC, kidder commented on src/Utilities/MakeArray.hpp
> + * \brief Create a `std::array<std::decay_t<T>, size>{{t, t, ...}}`
size -> Size

2017-12-17 22:21 UTC, kidder commented on tests/Unit/Utilities/Test_MakeArray.cpp
> +    CHECK(noncopyable_vectors[0].get() == (std::vector<double>{2.3, 8.6, 9.7}));
shouldn't this check all the elements of the array? i.e. `[0]` -> `[i]`

2017-12-17 22:21 UTC, kidder commented on tests/Unit/Utilities/Test_MakeArray.cpp
> +    CHECK(vector_array1[0] == (std::vector<int>(3, 9)));
ditto

2017-12-17 22:21 UTC, kidder commented on tests/Unit/Utilities/Test_MakeArray.cpp
> +    CHECK(vector_array2[0] == (std::vector<int>{3, 9, 12, -10}));
ditto

2017-12-17 22:21 UTC, kidder commented on src/Evolution/Systems/ScalarWave/Equations.hpp
> + * See Hesthaven and Warburton, Nodal Discontinuous Galerkin Methods, page
I think this comment should describe the first-order form of the scalar wave equation

2017-12-17 22:21 UTC, kidder commented on src/Evolution/Systems/ScalarWave/Tags.hpp
> +#include "DataStructures/DataBoxTag.hpp"
includes (or forward declarations) for size_t and DataVector

2017-12-17 22:21 UTC, kidder commented on src/Evolution/Systems/ScalarWave/System.hpp
> +#include "Evolution/Systems/ScalarWave/Equations.hpp"
first two not yet used

2017-12-17 22:21 UTC, kidder commented on src/Evolution/Systems/ScalarWave/System.hpp
> +
include for size_t

2017-12-17 22:21 UTC, kidder commented on src/Evolution/Systems/ScalarWave/System.hpp
> +namespace ScalarWave {
does this namespace have a doxygen comment anywhere?

2017-12-17 22:21 UTC, kidder commented on src/Evolution/Systems/ScalarWave/Equations.hpp
> +#include "Utilities/Gsl.hpp"
forward declaration sufficient?

2017-12-17 23:47 UTC, nilsdeppe commented
While addressing the comment about documenting the ScalarWave namespace I added a three commits. One adds a Doxygen group for evolution systems, another removes the currently unused and non-alphabetical ParallelComponentsGroup, and the last one adds GH to the evolution systems group.

2017-12-18 00:40 UTC, kidder requested changes
as far as I am concerned you can squash when making the latest changes

2017-12-18 00:40 UTC, kidder commented on src/Utilities/MakeArray.hpp
> +// We handle the zero size and case separately below because both for zero size
no and

2017-12-18 00:40 UTC, kidder commented on docs/GroupDefs.hpp
> + * \brief Contains namespace of all the available evolution systems.
the namespaces

2017-12-18 04:51 UTC, kidder approved these changes

2017-12-18 20:41 UTC, wthrowe approved these changes

2017-12-18 21:02 UTC, merged