Add FFE breakdown problem analytic data to ForceFree system
sxs-collaboration/spectre pull request #4640
Opened 2023-01-24 17:07 UTC by yoonso0-0

## Proposed changes

This analytic (initial) data demonstrates the breakdown of FF condition over time.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-01-25 19:16 UTC, yoonso0-0 commented
Included the first commit which is from #4615 since documentation `cite`s the bib entry added in it.

2023-01-27 16:51 UTC, nilsdeppe requested changes
You can squash immediately

2023-01-27 16:51 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/ForceFree/FfeBreakdown.cpp
> +    const double& xi = x.get(0)[i];
name `x` -> `coords` and then `xi` -> `x`. `xi` is the logical coordinate, so I worry this is confusing.

2023-01-28 05:30 UTC, nilsdeppe submitted a review, later dismissed

2023-01-28 05:34 UTC, nilsdeppe commented
Can you rebase this now that the other PR is merged?

2023-01-30 21:09 UTC, yoonso0-0 commented
@nilsdeppe Rebased on develop!

2023-01-30 21:13 UTC, nilsdeppe approved these changes

2023-02-02 18:28 UTC, merged