UniformTranslation: add distorted frame.
sxs-collaboration/spectre pull request #4652
Opened 2023-01-27 01:54 UTC by markscheel

## Proposed changes

Add distorted frame to UniformTranslation TimeDependence.

Also refactored tests in Test_UniformTranslation so as to re-use code for tests with and without
a distorted frame.

This is expected to be useful mostly for tests.
"Real" Domains with a distorted frame will not use a TimeDependence class.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-01-27 05:27 UTC, nilsvu requested changes

2023-01-27 05:27 UTC, nilsvu commented on src/Domain/Creators/TimeDependence/UniformTranslation.hpp
> +  UniformTranslation(
Please add some docs to the class explaining what's going on with the two velocities and the distorted frame

2023-01-27 18:53 UTC, knelli2 reviewed
Looks good. No additional change requests.

2023-01-28 00:34 UTC, nilsvu approved these changes, later dismissed
please squash

2023-01-28 02:24 UTC, markscheel commented
squashed

2023-01-28 03:01 UTC, knelli2 approved these changes

2023-01-28 04:28 UTC, nilsvu approved these changes

2023-01-29 03:12 UTC, markscheel commented
Failing test is a timeout of the shape map test.

2023-01-29 05:49 UTC, merged