Implicitly convert Numpy arrays to Tensors
sxs-collaboration/spectre pull request #4680
Opened 2023-02-01 19:21 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-02-01 19:21 UTC, nilsvu commented
@nikwit this seems to work well, so it's a start :)

2023-02-01 21:03 UTC, nikwit commented
Cool! Does that mean we can get rid of tensors and datavectors entirely on the python side?

2023-02-01 21:06 UTC, nilsvu commented
Bindings still return tensors and DataVectors, and I believe those can't implicitly convert to Numpy arrays

2023-02-01 21:26 UTC, nikwit commented
I still want to check if thats not possible somehow, that would be great!

2023-02-01 21:33 UTC, nilsvu commented
sure please try

2023-02-02 09:20 UTC, nilsvu commented
Maybe specializing `type_caster` has a chance of returning numpy arrays instead of tensors. I think that's how pybind11 implements Eigen types. Not sure if it's worth the effort to try, or if it's actually the right thing to do for tensors.

2023-02-03 14:11 UTC, nikwit commented
yes, it looks to be very similar to this: https://stackoverflow.com/questions/42645228/cast-numpy-array-to-from-custom-c-matrix-class-using-pybind11

I'm surprised it is this complicated, after all we only want it to call `np.asarray` whenever we return a tensor.

2023-02-03 16:11 UTC, nilsvu commented
Let's do the implicit conversion _from_ numpy arrays first, since it's a big improvement for convenience. Question: enable it for all Tensors, or only scalars and (co-)vectors? For higher-rank tensors (particularly with symmetries) the ordering of indices isn't obvious.

I'm not sure we want to return all tensors as numpy arrays. It's easy enough to convert in Python if you want to: `np.array(tensor)` does it. In many cases you can also duck-type the tensor or DataVector as an array. Tensor objects have useful features like access to component suffixes, symmetries, etc. And we'd have to get reference semantics right so the data isn't copied on the implicit conversion. Overall I see little benefit from implicitly converting tensors to Numpy arrays, but lots of benefit from implicitly converting arrays to tensors (scalars and vectors at least).

2023-02-03 17:17 UTC, nilsdeppe commented
I don't think we should go in this direction because the internal ordering of Tensor will not be intuitive for users. Scalar and Vector is fine, we allow this in C++ (array->Tensor, but explicitly), anything higher rank is just asking for trouble. If we end up realizing we should store things in a different order than we currently do, we would break a lot of Python code if they use numpy arrays for e.g. the metric.

2023-02-03 21:04 UTC, nikwit commented
I'm happy with the implicit conversion, definitely for scalars and vectors and also for other higher ranks. If we decide to change the storage order, then the only thing we should need to change is the buffer protocol so numpy knows how it is stored. On the python side there should not be any confusion about storage indices since we are always using arrays.

@nilsvu do you want to update #4646 and get rid of the typing in python? If yes, in a follow up PR or directly?

2023-02-03 21:13 UTC, nilsdeppe commented
I guess I don't see how it would work for higher rank tensors, but I don't know enough about numpy. For a rank 2 dim 3 symmetric tensor `gamma[1, 2]` might be the underlying location, but then `gamma[2, 1]` would have to alias to `gamma[1, 2]` (or whatever the aliasing we do is). If that can be done in a way that is agnostic to Tensor storage order I guess general bindings can work, I just don't know if it's possible. How would I create such an object in a numpy arary? Can I create symmetric rank 2 numpy arrays? If not, then we simply cannot use numpy arrays for higher ranks because they are fundamentally different.

2023-02-04 06:29 UTC, nilsvu commented
I agree and edited the PR so only scalars and vectors can be implicitly converted. I think that's already a big win for convenience.

2023-02-07 09:06 UTC, nikwit requested changes
numpy does not support symmetric tensors afaik. My suggestion was to always have full numpy arrays on the python side without symmetries. When converted to C++, we could just check that it satisfies the symmetries of the tensor that the user wants to convert to and copy. But this is fine with me.

2023-02-07 09:06 UTC, nikwit commented on src/DataStructures/Tensor/Python/Tensor.cpp
>                       "Tensor data is expected to be 2D with shape (size, "
the error message should tell you explicitly that you only allow scalars and vectors.

2023-02-07 09:06 UTC, nikwit commented on tests/Unit/DataStructures/Tensor/Python/Test_Tensor.py
> +        adm_mass_integrand(field=np.random.rand(4),
can you also test Vectors and an error test for tensors?

2023-02-07 17:48 UTC, nilsvu commented on src/DataStructures/Tensor/Python/Tensor.cpp
>                       "Tensor data is expected to be 2D with shape (size, "
You can, explicitly, construct higher-rank tensors from numpy arrays. The tensor gives you the index ordering (e.g. with `component_suffix`), so you know how to order the array. Only the implicit conversion is restricted to scalars and vectors. I edited the error message here a bit to include that scalars can be 1D numpy arrays.

2023-02-07 18:02 UTC, nilsvu commented on tests/Unit/DataStructures/Tensor/Python/Test_Tensor.py
> +        adm_mass_integrand(field=np.random.rand(4),
done

2023-02-08 07:01 UTC, nilsdeppe reviewed
I have no additional comments

2023-02-08 15:42 UTC, nilsvu commented
@nikwit please check the fixup

2023-02-08 15:52 UTC, nikwit approved these changes, later dismissed

2023-02-08 18:25 UTC, nilsdeppe approved these changes

2023-02-08 22:41 UTC, merged