Add electric current density (Ohm's law) to ForceFree system
sxs-collaboration/spectre pull request #4711
Opened 2023-02-08 23:23 UTC by yoonso0-0

## Proposed changes

* Rename `SpatialCurrentDensity` to `ElectricCurrentDensity`.
* Add free functions that evaluate J_drift (explicit) and J_parallel (implicit) part of electric current density J.
* Add a compute tag which evaluates the total J (`TildeJ`)

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-02-09 19:11 UTC, wthrowe requested changes

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> +void tilde_j_impl(
Remove this declaration.  It is definitely unused, since it doesn't match the definition in the cpp.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> +      const double parallel_conductivity, const Scalar<DataVector>& lapse,
Remove `const` on non-reference arguments in declarations that are not definitions.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> +      const double parallel_conductivity, const Scalar<DataVector>& lapse,
Again remove `const`.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.cpp
> +namespace detail {
Change to anonymous namespace.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.cpp
> +template <bool drift_current, bool parallel_current>
Template arguments should be `CamelCase`.  For boolean arguments, verbs are often clearer.  I suggest `IncludeDriftCurrent` and `IncludeParallelCurrent`.  I was confused about why they were separate arguments, and I think that makes it clearer.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.cpp
> +                         spatial_metric);
You could use these one-forms in B^2 at the start and in the parallel-current section to reduce the number of dot products with metrics, which are slower than dot products without metrics.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.cpp
> +      // assignment operations.
[optional] This might be clearer as an `else` block for the first `if constexpr`.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.cpp
> +template <bool drift_current, bool parallel_current>
`static_assert(drift_current or parallel_current);`  I don't think it makes sense to call this with both false.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.cpp
> +GENERATE_INSTANTIATIONS(INSTANTIATION, true, false)
Remove this whole instantiation section.  I think it isn't doing anything because this isn't the correct syntax (second and later arguments must be in parentheses) and the function in the `INSTANTIATION` macro doesn't match the function you're trying to instantiate.  Explicitly instantiating is unnecessary here because the function is only used in this file.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> +namespace Tags {
Include the tags above in the `Tags` namespace.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> + * \f$\eta\f$ is the parallel conductivity, and \f$\mathcal{R}(x,0) = \max
How does the `R(E^2-B^2)` in the formula above map onto the `R(x, 0)` defined here?

2023-02-09 19:11 UTC, wthrowe commented on tests/Unit/Evolution/Systems/ForceFree/Fluxes.py
> +from TestFunctions import levi_civita_symbol
This is changed back in the next commit.  Mistake in squashing, maybe?

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/Sources.cpp
> +    source_tilde_e->get(i) += -tilde_j_drift.get(i);
`-=`?  Don't know if it matters for efficiency, but seems clearer.

2023-02-09 19:11 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/Sources.hpp
> +      const double kappa_phi, const double parallel_conductivity,
No `const`s in non-definitions.  I may have missed some more of these.

2023-03-10 18:49 UTC, yoonso0-0 commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.cpp
> +                         spatial_metric);
Good point. Thanks

2023-03-10 18:49 UTC, yoonso0-0 commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> + * \f$\eta\f$ is the parallel conductivity, and \f$\mathcal{R}(x,0) = \max
Sorry, that extra argument was typo!

2023-03-10 18:49 UTC, yoonso0-0 commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> +namespace Tags {
@wthrowe Those two structs above are not `ComputeTag`s (don't have related SimpleTag and `base` type alias). Will it be clear if I remove the `Compute` prefix from names?

2023-03-10 18:54 UTC, yoonso0-0 commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> +namespace Tags {
I pushed a fixup only except for this. Let me know!

2023-03-10 18:55 UTC, wthrowe commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> +namespace Tags {
No, this is fine as-is.  Not sure why I thought they were tags.

2023-03-10 18:57 UTC, yoonso0-0 commented on src/Evolution/Systems/ForceFree/ElectricCurrentDensity.hpp
> +namespace Tags {
Thanks

2023-03-10 19:07 UTC, wthrowe commented
Looks good.  Squash.

2023-03-20 19:04 UTC, yoonso0-0 commented
Rebased on develop

2023-03-20 22:05 UTC, wthrowe approved these changes

2023-03-20 23:01 UTC, merged