Factor comoving magnetic field into free function
sxs-collaboration/spectre pull request #4715
Opened 2023-02-09 21:38 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-02-09 22:00 UTC, nilsdeppe submitted a review, later dismissed

2023-02-10 03:51 UTC, nilsvu commented
Added two commits with a few more point wise functions

2023-02-10 05:16 UTC, nilsdeppe requested changes

2023-02-10 05:16 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/StressEnergy.hpp
> + *   E_\mathrm{fluid} = \rho_0 h W^2 - P
I don't know what rho_0 is or what P is. We use `rho` for the baryon rest mass density and `D` for `rho W`, where `W` is the Lorentz factor. We use lower case `p` for the pressure.

2023-02-10 05:16 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/StressEnergy.hpp
> + *   S^i_\mathrm{fluid} = \rho_0 h W^2 v^i
same notation comment here

2023-02-10 05:16 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/StressEnergy.hpp
> + *   S_\mathrm{fluid} = 3 P + \rho_0 h (W^2 - 1)
same notation comment here

2023-02-13 05:17 UTC, nilsdeppe approved these changes

2023-02-13 17:46 UTC, merged