Add distorted frame to shape time dependence
sxs-collaboration/spectre pull request #4736
Opened 2023-02-15 00:07 UTC by knelli2

## Proposed changes

This is in preparation for using this time dependence with the shape control system.

Also adds a size function of time in the shape time dependence. This function of time doesn't control any maps, but is necessary if we want to use this time dependence with the shape control system (because the shape control error requires there to be a size function of time)

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-02-15 00:38 UTC, nilsvu requested changes

2023-02-15 00:38 UTC, nilsvu commented on src/Domain/Creators/TimeDependence/Shape.hpp
> + * shape map will go to the Distorted frame only and other maps will go to from
... go <s>to</s> from ...

2023-02-15 00:38 UTC, nilsvu commented on src/Domain/Creators/TimeDependence/Shape.hpp
> +                                        tmpl::list<ShapeMap, Identity>>;
delete `Identity` here? That should still work I think.

2023-02-15 22:55 UTC, wthrowe approved these changes, later dismissed
I have no additional comments.

2023-02-16 01:23 UTC, knelli2 commented
(hopefully) Fixed a linking error on macOS.

2023-02-16 22:11 UTC, knelli2 commented
After a discussion at the SpECTRE call on Thurs Feb. 16 2023, it was decided that we needed to fix the cyclic dependency of the TimeDependence library and move the ObjectLabel to DomainStructure. Both in separate PRs.

While I was at I also decided to move the renaming of excision spheres to another PR since it can be a stand-alone change.

Now this PR depends on and includes #4747, #4746, #4745.

2023-02-22 18:29 UTC, knelli2 commented
No longer dependent on #4747, #4746, #4745.

2023-02-22 19:12 UTC, nilsvu approved these changes

2023-02-22 19:54 UTC, wthrowe approved these changes

2023-02-23 06:59 UTC, merged