Add invoke and apply to TaggedContainers.hpp
sxs-collaboration/spectre pull request #4737
Opened 2023-02-16 03:14 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-02-17 21:04 UTC, wthrowe requested changes

2023-02-17 21:04 UTC, wthrowe commented on tests/Unit/DataStructures/Test_TaggedContainers.cpp
> +  using argument_tags = tmpl::list<Tags::MyDouble>;
Test with more than one entry in these lists.

2023-02-20 19:31 UTC, nilsdeppe commented
Update test to check all cases of 0,1,2 args and return tags. I squashed immediately because this basically changed the entire test.

Thanks for the review!

2023-02-21 19:10 UTC, wthrowe approved these changes

2023-02-21 19:10 UTC, merged