Have time steppers overwrite in update_u again
sxs-collaboration/spectre pull request #4748
Opened 2023-02-16 22:49 UTC by wthrowe

It turns out that it is sometimes difficult for the caller to determine the correct value to pass into the function.

This largely reverts bf4fd0a409c76996a104cb8750b4b9fb8e190c58.

Fixes #4399 

@geoffrey4444 This should remove the need for the dense output hack.  Can you test this and verify that your results look good?

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-02-20 17:10 UTC, nilsdeppe submitted a review, later dismissed

2023-02-20 21:17 UTC, geoffrey4444 commented
Sorry, but it looks to me like this PR does not fix the dense output bug #4399. I tried running a BBH with the 3-index constraint set to zero at t=0. I used [this branch](https://github.com/sxs-collaboration/spectre/compare/develop...geoffrey4444:spectre:BBH_020823_bugfix) at 3 different revisions: , and one of the following:

1: nothing (no additional commit) — revision 9200dd5633
2: the commit in this PR — revision 291a228ae9
3: the hack commit you previously suggested to fix the bug — revision b9fbf8e178

I verified that spectre.out reported the correct revision in each case. At t=0, here's the L2 norm of the 3-index constraint for each case:

1.  8.81945e-06
2. 8.81945e-06
3. 1.60104e-17

2023-02-21 02:40 UTC, wthrowe commented
OK, try now.  An old optimization was bypassing the fix when run at t=0.

This fix is not really related to the update_u changes, so I'm going to leave it as a separate commit.

2023-02-21 20:06 UTC, knelli2 requested changes

2023-02-21 20:06 UTC, knelli2 commented on src/Time/TimeSteppers/AdamsBashforth.cpp
> +    return;
I think this means if we are at the most recent history time, just return (i.e. don't do dense output), but I'm not 100% certain. Could you add a comment?

2023-02-21 23:29 UTC, wthrowe commented on src/Time/TimeSteppers/AdamsBashforth.cpp
> +    return;
You are correct.  I've added a comment.

2023-02-22 20:47 UTC, knelli2 approved these changes
I'm happy with the changes, but @geoffrey4444 should confirm again that these changes now fix the LTS dense output bug

2023-02-22 21:56 UTC, geoffrey4444 commented
> OK, try now. An old optimization was bypassing the fix when run at t=0.
> 
> This fix is not really related to the update_u changes, so I'm going to leave it as a separate commit.

I will try this again. Thanks!

2023-02-27 18:01 UTC, geoffrey4444 approved these changes
I did not review the code line by line but did try this again, and now the dense and not-dense output for the 3-index constraints agree, even at t=0. 

![image](https://user-images.githubusercontent.com/867015/221645769-2765ba87-1be4-4203-9d4d-d5cf10fcacdd.png)


Without this fix, the constraints are not zeroed correctly at t=0, and they level off to a larger value by time t=10 (though strangely even without the fix, I don't see the linear growth I saw back in November when I first spotted the symptoms of the bug this PR fixes).

I see small differences vs the hack fix, but I don't think they are significant.

So I'm happy to approve.

2023-02-27 18:56 UTC, nilsdeppe approved these changes

2023-02-27 18:56 UTC, merged

2023-02-27 19:10 UTC, wthrowe commented
If you're doing filtering, I'm guessing the hack and this version interact with that differently.  If not, I don't immediately see a reason they would differ, but I wouldn't worry about it for the moment.