Add ComputeCharacteristicSpeeds on ExcisionBoundary
sxs-collaboration/spectre pull request #4749
Opened 2023-02-17 00:03 UTC by gsb76

## Proposed changes

Adds the CharacteristicSpeedsCompute tag to the `compute_items_on_target` list of tags to compute on the Target (ExcisionBoundary). Also changes the Lapse, shift, and spatial metric to being computed in the volume in the grid frame before interpolating to the target, instead of interpolating the Frame::Inertial quantities to the target and changing frames there.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-02-17 04:42 UTC, nilsdeppe requested changes

2023-02-17 04:42 UTC, nilsdeppe commented on src/ApparentHorizons/ComputeExcisionBoundaryVolumeQuantities.hpp
> +      tmpl::list</*gr::Tags::SpacetimeMetric<3, Frame::Inertial>*/>;
remove completely instead of just commenting out?

2023-02-17 04:42 UTC, nilsdeppe commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicSingleBlackHole.hpp
> +        GeneralizedHarmonic::ConstraintDamping::Tags::ConstraintGamma1,
All these tags are wrong, just don't add them. You'll need to write a new tag to compute the char speed. Most of these tags are simple tags, not compute tags.

2023-02-17 17:53 UTC, nilsdeppe commented on src/ApparentHorizons/ComputeExcisionBoundaryVolumeQuantities.hpp
>        tmpl::list<gr::Tags::SpatialMetric<3, Frame::Inertial>,
We'll want `ConstraintGamma1` here as well and then handled correctly in the tpp

2023-02-17 17:53 UTC, nilsdeppe commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicSingleBlackHole.hpp
> +        tmpl::list<gr::Tags::Lapse<DataVector>, gr::Tags::Shift<3, Frame::Grid>,
add `ConstraintGamma1` here as well

2023-02-17 17:56 UTC, nilsdeppe commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicSingleBlackHole.hpp
> +        GeneralizedHarmonic::ConstraintDamping::Tags::ConstraintGamma1,
We need:
1. a compute tag to get InverseSpatialMetric from the grid SpatialMetric
2. Use `ah::Tags::OneOverOneFormMagnitudeCompute<3, Frame::Grid>`
3. Use `ah::Tags::UnitNormalOneFormCompute<Frame::Grid>`
4. A new `CharacteristicCompute` tag that uses `ah::Tags::UnitNormalOneForm<Frame::Grid>` as the normal covector

2023-02-17 22:56 UTC, nilsdeppe reviewed
LGTM, please squash! Nice work 😄

2023-02-17 23:51 UTC, nilsdeppe requested changes
You can squash

2023-02-17 23:51 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Characteristics.hpp
> +  };
don't need `;` here

2023-02-17 23:51 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Characteristics.hpp
> +struct CharacteristicSpeedsOnStrahlkorperCompute
document? Add compute tag test?

2023-02-17 23:51 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Characteristics.hpp
> +  using argument_tags = tmpl::list<
How can this compile? You have 5 arguments here but only 4 in the function.

2023-02-22 20:55 UTC, knelli2 reviewed
No additional comments

2023-03-04 06:08 UTC, nilsdeppe requested changes
Few small things. Looks great! You can squash and rebase immediately :D

2023-03-04 06:08 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Characteristics.hpp
> +  // using type = std::array<DataVector, 4>;
Remove?

2023-03-04 06:08 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Characteristics.hpp
> +template <typename Frame>
Document?

2023-03-04 06:08 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Characteristics.hpp
> +      //::StrahlkorperTags::OneOverOneFormMagnitude,
Remove

2023-03-04 06:08 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Characteristics.hpp
> +    // characteristic_speeds(make_not_null(&arr), ...);
Remove commented lines

2023-03-04 06:08 UTC, nilsdeppe commented on src/ParallelAlgorithms/Interpolation/Callbacks/ObserveSurfaceData.hpp
> +      // static_assert(std::is_same_v<typename Tag::type, Scalar<DataVector>>,
Remove and factor this change into its own commit in the end

2023-03-04 06:08 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_Characteristics.cpp
> +  TestHelpers::db::test_compute_tag<
Can you add a test for the simple tag too please?

2023-03-04 06:08 UTC, nilsdeppe commented on src/Evolution/Executables/GeneralizedHarmonic/EvolveGeneralizedHarmonicSingleBlackHole.hpp
> +  // The interpolator_source_vars need to be the same in both the Interpolate
Great comment! Whoever looks at this next will definitely appreciate it! :D

2023-03-07 16:52 UTC, nilsdeppe approved these changes

2023-03-07 16:53 UTC, merged

2023-03-07 18:51 UTC, nilsvu commented on src/ParallelAlgorithms/Interpolation/Callbacks/ObserveSurfaceData.hpp
>      // points on the surface).
@gsb76 Please update this comment