Add `CenteredFaceCoordinates` compute tag
sxs-collaboration/spectre pull request #4771
Opened 2023-02-24 12:44 UTC by nikwit

## Proposed changes
Adds a convenient compute tag that computes the grid coordinates of each element face abutting the worldtube

2023-02-24 18:15 UTC, nilsvu requested changes
only a couple of nitpicks, squash directly

2023-02-24 18:15 UTC, nilsvu commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
> + * abutting the worldtube. If the element does not abut the worldtube, it holds
"..., centered on the worldtube"

2023-02-24 18:15 UTC, nilsvu commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
> +/*!
(nitpick) add an empty line above while you're making changes

2023-02-24 18:15 UTC, nilsvu commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
> +struct ComputeCenteredFaceCoordinates : CenteredFaceCoordinates<Dim>,
`CenteredFaceCoordinatesCompute` (that's our convention for compute tags, helps with readability and alphabetically sorted lists)

2023-02-24 18:15 UTC, nilsvu commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.cpp
> +        res,
(nitpick) `result`

2023-02-24 18:15 UTC, nilsvu commented on tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/Test_Tags.cpp
> +#include "Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/InitializeElementFacesGridCoordinates.hpp"
(optional) If you want to shorten this I suggest you name the file `InitializeElementFaces.hpp`

2023-02-24 18:15 UTC, nilsvu commented on tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/Test_Tags.cpp
> +    // we create two Shells with different refinements
refinement -> resolution

2023-02-24 19:41 UTC, nikwit commented
thanks, I squashed it in :)

2023-02-25 18:57 UTC, nilsvu approved these changes

2023-02-25 18:57 UTC, merged