Send cell centered fluxes with FD.
sxs-collaboration/spectre pull request #4786
Opened 2023-02-28 03:49 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-02-28 21:07 UTC, kidder requested changes

2023-02-28 21:07 UTC, kidder commented on src/Evolution/DgSubcell/CellCenteredFlux.hpp
> +    if ((ComputeOnlyOnRollback and did_rollback) or not ComputeOnlyOnRollback) {
this is equivalent to `if(did_rollback or not ComputeOnlyOnRollback)`

2023-02-28 21:07 UTC, kidder commented on src/Evolution/DgSubcell/CellCenteredFlux.hpp
> +      const gsl::not_null<std::optional<Variables<tmpl::list<FluxTags...>>>*>
include for gsl::not_null

2023-02-28 21:07 UTC, kidder commented on src/Evolution/DgSubcell/CellCenteredFlux.hpp
> +#include "DataStructures/Tensor/Tensor.hpp"
don't think you need this one

2023-02-28 21:07 UTC, kidder commented on tests/Unit/Evolution/DgSubcell/Test_CellCenteredFlux.cpp
> +      (not ComputeOnlyOnRollback or (ComputeOnlyOnRollback and did_rollback))) {
same simplification as above

2023-02-28 22:54 UTC, nilsdeppe commented
Done, rebased, squashed. Thanks for the review :D

2023-02-28 22:56 UTC, kidder approved these changes, later dismissed

2023-02-28 23:53 UTC, nilsdeppe commented
Sorry, fixed another include and squashed...

2023-03-01 02:09 UTC, kidder approved these changes

2023-03-01 02:09 UTC, merged