Add distorted frame to BBH domains
sxs-collaboration/spectre pull request #4792
Opened 2023-02-28 23:11 UTC by knelli2

## Proposed changes

Also adds the size map to the CylBBH domain so it has the same time dependent maps as the regular BBH domains.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-03-07 16:09 UTC, nilsvu commented
The cyl BBH domain test timed out. Can we reduce its complexity somewhat like we have done recently with the Interval creator (just merged) and the Sphere (in #4772)?

2023-03-07 17:57 UTC, knelli2 commented
@nilsvu Do you have any ideas in mind? I'm not sure which parts would be unnecessary.

2023-03-07 18:09 UTC, nilsvu commented
What comes to mind is:

- Move parse error tests out of the cartesian product into `test_parse_errors` so they don't get called unnecessarily.
- Merge `test_binary_factory`, `test_bbh_time_dependent_factory`, and `test_connectivity` into one function so there's only one cartesian product. Will be easy with the tools added in #4772.

2023-03-07 18:30 UTC, nilsvu requested changes

2023-03-07 18:30 UTC, nilsvu commented on src/Domain/Creators/CylindricalBinaryCompactObject.cpp
> +    PARSE_ERROR(context,
Could you add a comment here why this limitation exists? If this is "not implemented yet" then mention that in the assert.

2023-03-07 18:30 UTC, nilsvu commented on tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp
>           (with_additional_outer_radial_refinement
I think the true and false branches of this conditional and the one below are reversed. You didn't introduce this here, but would you mind fixing it?

2023-03-07 18:30 UTC, nilsvu commented on src/Domain/Creators/CylindricalBinaryCompactObject.hpp
> +          domain::CoordinateMaps::TimeDependent::Rotation<3>>,
Use the aliases you defined above here? Same in the cubical BBH domain.

2023-03-07 18:30 UTC, nilsvu commented on src/Domain/Creators/CylindricalBinaryCompactObject.hpp
> +    static std::string name() { return "InitialData"; }
This is "InitialValues" in the cubical BBH domain. Make the two consistent. I think "InitialValues" is better than "InitialData" (neither name tells me what sort of values to put here, but that's out of scope for this PR). I understand that the cubical BBH domain has 3 separate tags for the value and two derivatives, but "InitialData" too strongly implies PDE volume initial data (maybe I'm biased because I've been working on that for a long time).

2023-03-07 19:04 UTC, knelli2 commented on src/Domain/Creators/CylindricalBinaryCompactObject.hpp
> +    static std::string name() { return "InitialData"; }
I was matching the name of the Expansion map options here. I can change both to be "InitialValues"

2023-03-07 19:05 UTC, nilsvu commented on src/Domain/Creators/CylindricalBinaryCompactObject.hpp
> +    static std::string name() { return "InitialData"; }
Oh I see. Yes I think that would be better.

2023-03-07 19:37 UTC, knelli2 commented
I'll refactor the test more once #4772 is merged

2023-03-07 19:48 UTC, nilsvu approved these changes

2023-03-08 00:10 UTC, nilsvu commented
@markscheel do you want to take a quick look before I merge this?

2023-03-08 23:35 UTC, markscheel reviewed
Looks good!   Eventually the size/shape (and cutX) maps will need to extend outside of the inner shells (and then the inner shells don't need to exist) but that is complicated and should be done later.

2023-03-08 23:35 UTC, markscheel approved these changes

2023-03-08 23:44 UTC, merged