Add radially compressed coordinates
sxs-collaboration/spectre pull request #4793
Opened 2023-03-01 19:39 UTC by nilsvu

## Proposed changes

Coordinates suitable for visualizing large radii by compressing them logarithmically or inversely.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-03-04 06:18 UTC, nilsdeppe requested changes
you can squash immediately

2023-03-04 06:18 UTC, nilsdeppe commented on src/Domain/RadiallyCompressedCoordinates.hpp
> +  void pup(PUP::er& p) {
Move to cpp?

2023-03-04 06:18 UTC, nilsdeppe commented on src/Domain/RadiallyCompressedCoordinates.hpp
> +struct RadiallyCompressedCoordinatesOptions {
Please document

2023-03-06 23:37 UTC, nilsvu commented
done 👍

2023-03-07 01:17 UTC, nilsdeppe approved these changes

2023-03-07 04:23 UTC, merged