Have get_output return "true"/"false" for bools instead of 1/0
sxs-collaboration/spectre pull request #4794
Opened 2023-03-01 19:39 UTC by knelli2

## Proposed changes

No need for all these custom `stringize` functions (even though they aren't hard to implement)

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-03-01 20:06 UTC, wthrowe requested changes
I don't think this is a good idea.  `get_output` is used in many places for testing that objects print correctly, or for finding the result of printing the object for some other reason.  Making it return something other than the plain result of streaming breaks that.

2023-03-01 20:06 UTC, wthrowe commented on src/Utilities/GetOutput.hpp
> +    return t ? "true" : "false";
The thing you're looking for is called `std::boolalpha`.

2023-03-01 20:22 UTC, knelli2 commented on src/Utilities/GetOutput.hpp
> +    return t ? "true" : "false";
Should I use `std::boolalpha` here then in the stream part, or just make a new `stringize` function in Utilities?

2023-03-01 23:00 UTC, nilsdeppe commented
I agree with @wthrowe This could lead to confusion. I'm not sure what the right answer is because I also agree that being able to control the output would be nice. Possible `get_output` should take a stream modifier object? I haven't looked into that, so it might just not be possible

2023-03-02 01:52 UTC, wthrowe commented
Sorry for the confusion.  The two parts of my comment were unrelated.  I don't think we should do this, but if we do, or add something similar, we should use the standard library functionality.

As to what to do, I think `(MakeString{} << std::boolalpha << flag)` would give the right result, and is probably simple enough to not need a wrapper function.

2023-03-02 04:49 UTC, knelli2 commented
Ok @wthrowe I left `get_output` alone and just added a global `stringize` function. I think it's worth having this because now all places that need to convert a bool to a string use the standard library functionality. Whereas previously none of them did

2023-03-03 19:47 UTC, wthrowe commented
I think "stringize" is a really generic name for something that only works on bool.  I suggest one of (a) rename it to make it's purpose clear, (b) allow it to take any type so it works on `vector<bool>` and similar (although then people will probably confuse it with `get_output`), or (c) inline it everywhere.

I think this is mostly used for creating option strings for tests, so a function to convert simple types to something the YAML parser will understand might be a general solution.  The yaml-cpp library probably has something to do that, but if we only care about a few things like bools and vectors writing our own is probably easier.

2023-03-03 19:53 UTC, nilsvu commented
Yea generating YAML output from types would be the way to go I think

2023-03-03 20:03 UTC, kidder commented
I agree with this, I was going to suggest something like `Options::to_yaml`

2023-03-03 20:57 UTC, wthrowe commented
As long as we don't want to do anything complicated so we care about indenting and stuff it looks like yaml-cpp makes that pretty easy: https://github.com/jbeder/yaml-cpp/wiki/How-To-Emit-YAML

2024-08-21 16:36 UTC, closed without merging