Return reconstruction order from ppao
sxs-collaboration/spectre pull request #4801
Opened 2023-03-03 17:11 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-03-07 18:58 UTC, kidder requested changes

2023-03-07 18:58 UTC, kidder commented on src/NumericalAlgorithms/FiniteDifference/PositivityPreservingAdaptiveOrder.hpp
> +  SPECTRE_ALWAYS_INLINE static rt pointwise(
return_type or return_t or something more descriptive

2023-03-07 18:58 UTC, kidder commented on src/NumericalAlgorithms/FiniteDifference/Reconstruct.tpp
> +      // recons_order_slice_offset + 1 (for left neighbor) + (volume_extents-1)
is there a way to factor out this code block that is repeated five times?  Also I don't understand the comments in the last two

2023-03-08 06:19 UTC, nilsdeppe commented
Rebased and squashed. Thanks for the review!

2023-03-08 15:32 UTC, kidder approved these changes

2023-03-08 15:32 UTC, merged