Add actions to send data from worldtube to abutting elements
sxs-collaboration/spectre pull request #4804
Opened 2023-03-03 19:21 UTC by nikwit

## Proposed changes
Adds the 0th order worldtube scheme final piece, where the worldtube sends the regular field to the abutting elements in `SendToElements` and the elements process it into boundary condition in `ReceveElementData`.

depends on #4798

2023-03-05 16:17 UTC, nilsvu requested changes

2023-03-05 16:17 UTC, nilsvu commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/Inboxes.hpp
> +               std::unordered_map<ElementId<Dim>, Variables<tags_to_send>>>;
You don't need the map over element IDs here because you send from a singleton.

2023-03-06 05:34 UTC, nilsvu submitted a review, later dismissed

2023-03-06 08:29 UTC, nikwit commented
thanks for your review, I squashed it in :)

2023-03-07 16:44 UTC, nilsdeppe approved these changes

2023-03-07 16:45 UTC, merged