High order fd for grmhd
sxs-collaboration/spectre pull request #4809
Opened 2023-03-05 06:35 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-03-07 19:10 UTC, kidder requested changes

2023-03-07 19:10 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
> +      db::wrap_tags_in<::Tags::Flux, typename System::flux_variables,
includes for wrap_tags_in and Tags::Flux

2023-03-07 19:10 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
> +    Variables<typename System::variables_tag::tags_list> cons{
includes for Variables

2023-03-08 06:28 UTC, nilsdeppe commented
Rebased and squashed. Thanks for the review!

2023-03-08 15:35 UTC, kidder submitted a review, later dismissed

2023-03-08 17:09 UTC, nilsdeppe commented
I increased the timeout of the time deriv test. It needs to be thorough so is a bit slow, inevitably...

2023-03-08 18:33 UTC, kidder approved these changes

2023-03-08 20:39 UTC, merged