Have the control system work in the Distorted frame
sxs-collaboration/spectre pull request #4813
Opened 2023-03-07 06:50 UTC by knelli2

## Proposed changes

Instead of the Grid frame. We'll need this for shape and size control.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments
Depends on and includes #4792.

2023-03-09 07:00 UTC, knelli2 commented
@ffoucart Just an FYI, with this PR, you'll have to have a distorted frame in your BNS domain because the control system works in the distorted frame. The Grid -> Distorted map will just be identity for BNS but it has to exist. I've chosen to do it this way because if we ever do BHNS, we will *have* to have the distorted frame (for the horizon), so it's easiest to just always require the control system to work in the distorted frame.

2023-03-09 20:00 UTC, ffoucart commented
Thanks. We haven't even started putting the control system in the input files, so... we should be able to take that into account when we get there :-)

2023-03-17 21:09 UTC, nilsvu requested changes

2023-03-17 21:09 UTC, nilsvu commented on src/ApparentHorizons/ObserveCenters.hpp
> +template <typename InterpolationTargetTag, typename Frame>
(optional) To avoid collision with the `Frame` namespace I've found it helpful to name template parameters like this more descriptively, like `ObservationFrame` in this case maybe.

2023-03-17 21:09 UTC, nilsvu commented on tests/Unit/ApparentHorizons/Test_ObserveCenters.cpp
> +                         StrahlkorperTags::CartesianCoords<::Frame::Inertial>,
(this is what you avoid with my previous comment)

2023-03-17 21:09 UTC, nilsvu commented on src/Domain/Creators/Tags/ObjectCenter.cpp
> +  tnsr::I<double, 3, Frame> result{};
(optional) you can short-circuit here with an `if constexpr (Frame is grid) { return center; } else { return as distorted frame }`

2023-03-17 21:09 UTC, nilsvu commented on src/Domain/Creators/Tags/ObjectCenter.hpp
> +template <ObjectLabel Label, typename Frame>
I think you can just drop this commit and work with the grid coords in the places where you retrieve this tag. Otherwise you should add the frame parameter also to `ObjectCenter` and that just complicates everything unnecessarily I think. As you said, per definition the grid and distorted frame excision centers are the same. Dropping this commit also removes quite a bit of unnecessary copying of tensors in the next commit I think.

2023-03-18 00:00 UTC, knelli2 commented
@nilsvu Dropped the suggested commit. Didn't do the optional change though about `Frame`.

2023-03-18 00:23 UTC, nilsvu requested changes

2023-03-18 00:23 UTC, nilsvu commented on tests/Unit/ControlSystem/ControlErrors/Test_Shape.cpp
> +  const tnsr::I<double, 3, Frame::Distorted> origin{0.0};
I think you can just drop this change and the origin_grid below

2023-03-18 00:23 UTC, nilsvu commented on tests/Unit/ControlSystem/Systems/Test_Shape.cpp
> +  const tnsr::I<double, 3, Frame::Grid>& grid_center = excision_sphere.center();
I think you can drop all this too

2023-03-18 00:24 UTC, nilsvu commented
@markscheel could you have a glance over this PR?

2023-03-21 21:50 UTC, markscheel reviewed
Looks good! Only one small dox change; ok to squash.

2023-03-21 21:50 UTC, markscheel commented on src/ApparentHorizons/ObserveCenters.hpp
>   * StrahlkorperTags::EuclideanAreaElement<Frame::Grid> to be in the DataBox
`EuclideanAreaElement<Frame>`

2023-03-21 22:46 UTC, nilsvu approved these changes

2023-03-21 23:52 UTC, merged

2023-03-22 20:18 UTC, knelli2 commented
Fixes #4593