Improve dox for Shape/Size maps.
sxs-collaboration/spectre pull request #4822
Opened 2023-03-09 21:57 UTC by markscheel

## Proposed changes

Documentation now clearly states what is stored in the FunctionOfTime for each map.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-03-10 00:45 UTC, knelli2 requested changes
Thank you for doing this. You can squash these directly.

I'll work on changing the control system to use these assumptions (Currently the control system makes different assumptions)

2023-03-10 00:45 UTC, knelli2 commented on src/Domain/CoordinateMaps/TimeDependent/SphericalCompression.hpp
> + * generalization of this map that changes region's shape as well as
`changes the region's shape`

2023-03-10 00:45 UTC, knelli2 commented on src/Domain/CoordinateMaps/TimeDependent/SphericalCompression.hpp
> + * See Shape for more details.
There are a lot of `Shape`s in the code (control sys, control erro, map, time dependence). Could you specify 
```
See the `domain::CoordinateMaps::TimeDependent::Shape` map for more details
```

2023-03-10 00:45 UTC, knelli2 commented on src/Domain/CoordinateMaps/TimeDependent/SphericalCompression.hpp
> + * term included here, can be found in the `Shape` map.
`domain::CoordinateMaps::TimeDependent::Shape` also

2023-03-10 14:05 UTC, markscheel commented
Addressed comments and squashed.

2023-03-10 17:26 UTC, knelli2 approved these changes

2023-03-13 23:45 UTC, nilsdeppe approved these changes

2023-03-13 23:45 UTC, merged