Events and Triggers
sxs-collaboration/spectre pull request #484
Opened 2018-01-19 00:27 UTC by wthrowe

### Types of changes:

- [ ] Bugfix
- [X] New feature

### Component:

- [X] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

I've gone with putting the Events and Triggers in the global cache, and as a result they cannot have state.  If we want stateful triggers moving them to the DataBox would not be difficult.

2018-01-23 19:26 UTC, wthrowe commented
Rebased to handle interaction with #485.

2018-01-29 23:41 UTC, kidder requested changes
rebase, fix, and squash

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/Completion.hpp
> +PUP::able::PUP_ID Completion::my_PUP_ID = 0;  // NOLINT
squash this away

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/Event.hpp
> +}
// namespace Events

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/Event.hpp
> +  ~Event() = default;
override

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/LogicalTriggers.hpp
> +// FIXME move to cpp
ditto

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/Trigger.hpp
> +}
// namespace

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/Trigger.hpp
> +  ~Trigger() = default;
override

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/Trigger.hpp
> +      tmpl::list<Triggers::Always, Triggers::Not, Triggers::And, Triggers::Or>;
alphabetize

2018-01-29 23:41 UTC, kidder commented on src/Options/Options.hpp
> +}
// namespace

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/Event.hpp
> +      tmpl::append<Event_detail::default_events<KnownEvents>,
check for duplicates

2018-01-29 23:41 UTC, kidder commented on src/Evolution/EventsAndTriggers/Trigger.hpp
> +      tmpl::append<Trigger_detail::logical_triggers<KnownTriggers>,
check for duplicates

2018-01-29 23:41 UTC, kidder commented on src/Time/Triggers/EveryNSlabs.hpp
> +  void pup(PUP::er& p) {  // NOLINT
noexcept

2018-01-29 23:41 UTC, kidder commented on tests/Unit/Time/Test_PastTime.cpp
> +  {
combine into lambda

2018-02-16 20:28 UTC, kidder requested changes
squash

2018-02-16 20:28 UTC, kidder commented on src/Options/ParseOptions.hpp
> +    // extract keys from maps before C++17.  One we require C++17 this
One -> once

2018-02-16 20:28 UTC, kidder commented on src/Evolution/EventsAndTriggers/Trigger.hpp
> +template <typename>
alphabetize

2018-02-16 20:28 UTC, kidder commented on tests/Unit/Evolution/EventsAndTriggers/Test_EventsAndTriggers.cpp
> +// triggers (Always, Not, And, and Or).
alphabetize

2018-02-16 20:28 UTC, kidder commented on src/Evolution/EventsAndTriggers/Actions/RunEventsAndTriggers.hpp
> +
use get from ConstGlobalCache with a base class

2018-02-16 20:28 UTC, kidder commented on tests/Unit/Evolution/EventsAndTriggers/Test_EventsAndTriggers.cpp
> +  auto box = db::create<db::AddTags<>>();
const

2018-02-16 20:28 UTC, kidder commented on src/Time/Triggers/EveryNSlabs.hpp
> +  explicit EveryNSlabs(const size_t interval, const size_t offset) noexcept
no explicit

2018-02-16 21:39 UTC, nilsdeppe approved these changes

2018-02-16 21:39 UTC, kidder approved these changes

2018-02-17 00:11 UTC, merged