Improve CSW characteristics calculations
sxs-collaboration/spectre pull request #4858
Opened 2023-03-21 16:27 UTC by nikwit

## Proposed changes
Fixes some outdated initialization and adds an overload to `characteristic_fields` that is a lot safer and looks more tidy.

There are now a lot of unused overloads that use variables directly and  unused compute tags  `EvolvedFieldsFromCharacteristicFieldsCompute`, `CharacteristicFieldsCompute` and `CharacteristicSpeedsCompute` in this file, should they be deleted?

2023-03-21 21:31 UTC, nilsdeppe requested changes
LGTM, one minor request. Please squash directly :)

2023-03-21 21:31 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Characteristics.cpp
> +  *v_minus = dot_product(unit_normal_vector, phi);
use `dot_product(v_minus, unit_normal_vector, phi);` to elide allocation+copy?

2023-03-22 10:31 UTC, nikwit commented
done, thanks!

2023-03-22 16:06 UTC, nilsdeppe approved these changes

2023-03-22 16:06 UTC, merged