Allow different boundary conditions in Brick
sxs-collaboration/spectre pull request #4875
Opened 2023-03-23 06:07 UTC by nilsdeppe

This is useful for testing 1d GRMHD problems where y & z are periodic.

## Proposed changes

### Upgrade instructions

Change input files from:
```
    BoundaryCondition: Periodic
```
to
```
    BoundaryConditionInX: Periodic
    BoundaryConditionInY: Periodic
    BoundaryConditionInZ: Periodic
```

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-03-23 15:23 UTC, nilsvu requested changes

2023-03-23 15:23 UTC, nilsvu commented on src/Domain/Creators/Brick.cpp
> +        boundary_condition_in_z_->get_clone();
This doesn't look like periodic boundary conditions in only a subset of the directions are handled correctly, or maybe I am missing something. Could you add a test for that? Line 155 returns empty boundary conditions if just the x-direction is periodic.

2023-03-24 16:29 UTC, nilsdeppe commented on src/Domain/Creators/Brick.cpp
> +        boundary_condition_in_z_->get_clone();
Yea, I think you're right. I've added tested and checks to resolve this. Thanks!

2023-03-25 18:07 UTC, nilsvu approved these changes, later dismissed

2023-03-25 19:32 UTC, nilsdeppe commented
I've rebased and squashed. Thanks so much for the review!

2023-03-26 14:58 UTC, nilsvu approved these changes

2023-03-26 14:58 UTC, merged