Make Worldtube use STF tensors
sxs-collaboration/spectre pull request #4881
Opened 2023-03-27 10:35 UTC by nikwit

## Proposed changes
Introduces a `STFTensor` tag that holds a symmetric trace free tensor of a given rank and makes the worldtube use it. This will be necessary for the second order implementation.

depends on #4866

2023-03-27 16:53 UTC, nilsdeppe requested changes
you can squash immediately. I only looked at the new commits

2023-03-27 16:53 UTC, nilsdeppe commented on src/NumericalAlgorithms/SphericalHarmonics/Tags.hpp
> +namespace STF::Tags {
While we don't have any strict policies on namespaces, we prefer either `Stf` or `stf`

2023-03-27 16:53 UTC, nilsdeppe commented on src/NumericalAlgorithms/SphericalHarmonics/Tags.hpp
> +struct STFTensor : db::SimpleTag {
`StfTensor` is the correct camel case for this

2023-03-27 16:53 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/SphericalHarmonics/Test_Tags.cpp
> +  struct DummyScalar : db::SimpleTag {
we have a function `TestHelpers::db::test_simple_tag<Tag>("TagName");` defined in `Helpers/DataStructures/DataBox/TestHelpers.hpp` that you should also use. It doesn't test what you do with the `static_assert`, it tests that the name matches, etc.

2023-03-28 16:08 UTC, nilsdeppe reviewed
LGTM, please squash and rebase

2023-03-28 16:08 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/ReceiveElementData.hpp
> +      tmpl::list<STF::Tags::STFTensor<Tags::PsiWorldtube, 0, Dim, Frame::Grid>,
missed renames here (that's why CI is unhappy)

2023-03-28 18:39 UTC, nikwit commented
done, thanks :)

2023-03-28 18:40 UTC, nilsdeppe submitted a review, later dismissed

2023-03-28 18:41 UTC, nikwit commented
sorry, I noticed a missing include and pushed again

2023-03-28 18:45 UTC, nilsdeppe approved these changes
Not a problem!

2023-03-28 23:51 UTC, merged