Enable worldtube evolution at 1st expansion order
sxs-collaboration/spectre pull request #4883
Opened 2023-03-27 21:45 UTC by nikwit

## Proposed changes
depends on #4881 #4866

2023-03-27 22:08 UTC, nikwit commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/ReceiveElementData.hpp
> +#include "Parallel/Printf.hpp"
rm

2023-03-28 16:31 UTC, nilsdeppe requested changes
new commit LGTM, marking as "requested changes" just so it doesn't accidentally get merged before the other PR. Please rebase once the other PRs are both merged and ping to merge :)

2023-03-29 15:01 UTC, nikwit commented
rebased, thanks for the review @nilsdeppe

2023-03-29 16:08 UTC, nilsdeppe approved these changes, later dismissed

2023-03-29 18:37 UTC, nikwit commented
had to be rebased again due to conflicts

2023-03-29 19:08 UTC, nilsdeppe approved these changes

2023-03-30 00:08 UTC, merged