Add tag for time deriv of strahlkorper
sxs-collaboration/spectre pull request #4884
Opened 2023-03-28 01:42 UTC by knelli2

## Proposed changes

This is needed for size control. Part of #4592.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-03-28 02:47 UTC, wthrowe commented
This seems to do a lot more than add a tag.

2023-03-28 02:51 UTC, knelli2 commented
Well it adds a compute tag. And the code I needed for part of the compute tag was in the averager (the FD coefficients). So I factored it out. And by the end of it all, it wasn't that many line changes overall so I just kept it in one PR.

2023-03-28 18:24 UTC, wthrowe requested changes

2023-03-28 18:24 UTC, wthrowe commented on src/NumericalAlgorithms/FiniteDifference/NonUniform1D.hpp
> + * `std::dequeue` where the zeroth element is the "most recent" in time and then
"deque"

2023-03-28 18:24 UTC, wthrowe commented on src/NumericalAlgorithms/FiniteDifference/NonUniform1D.hpp
> + * The reason that `times` was chosen to be monotonically decreasing is because
Not a change request, just want to make sure you're aware that the math doesn't care about anything except that the values are distinct.  Probably still worth asserting the ordering as a check against the caller going haywire.

2023-03-28 18:24 UTC, wthrowe commented on src/NumericalAlgorithms/FiniteDifference/NonUniform1D.hpp
> + * input times.
Which dimension is which?

2023-03-28 18:24 UTC, wthrowe commented on src/NumericalAlgorithms/FiniteDifference/NonUniform1D.hpp
> + * derivatives evaluated at `times[0]`.
What happens if `times.size() != StencilSize`?

2023-03-28 18:24 UTC, wthrowe commented on src/ApparentHorizons/Tags.hpp
> +  static void function(
Make this a free function.  It seems like it could be useful without a box.

2023-03-28 18:24 UTC, wthrowe commented on src/ApparentHorizons/Tags.hpp
> +struct TimeDerivStrahlkorper : db::SimpleTag {
[optional] We have a `Tags::dt<...>` representing time derivatives.

2023-03-28 18:24 UTC, wthrowe commented on tests/Unit/ApparentHorizons/Test_Tags.cpp
> +    // zero.
Test a case where the function actually does something.  One point with two times would be fine.

2023-03-28 18:24 UTC, wthrowe commented on src/ParallelAlgorithms/Interpolation/Callbacks/FindApparentHorizon.hpp
> +/// post_horizon_find_callback_example
Broke the docs.  Again below.

2023-03-29 05:00 UTC, knelli2 commented on src/NumericalAlgorithms/FiniteDifference/NonUniform1D.hpp
> + * derivatives evaluated at `times[0]`.
An error. There's an ASSERT

2023-03-29 06:50 UTC, knelli2 commented
Added a new commit where I add the free function, so the commit that adds the tag is a lot shorter.

2023-03-29 19:08 UTC, wthrowe requested changes

2023-03-29 19:08 UTC, wthrowe commented on src/NumericalAlgorithms/FiniteDifference/NonUniform1D.hpp
> + * derivatives evaluated at `times[0]`.
Document that.

2023-03-29 19:08 UTC, wthrowe commented on src/ApparentHorizons/TimeDerivStrahlkorper.cpp
> +static DataVector compute_coefs(
Anonymous namespace.

2023-03-29 19:08 UTC, wthrowe commented on src/ApparentHorizons/TimeDerivStrahlkorper.cpp
> +      const std::deque<double>&, const std::deque<const DataVector*>&);
You don't need to explicitly instantiate this, since it is only used in this file.

2023-03-30 17:59 UTC, wthrowe approved these changes

2023-03-30 18:00 UTC, merged