Transform time derivative of regular field to grid frame
sxs-collaboration/spectre pull request #4885
Opened 2023-03-28 11:17 UTC by nikwit

## Proposed changes
This transforms the time derivative of the regular field to the grid frame before sending it to the worldtube. The advective term needed for this is stored in an extra tag which is used to transform the worldtube solution back to the inertial frame before applying boundary conditions to the elements.

For the 0th and 1st order this does not matter but for 2nd order evolution this is required.

2023-03-28 19:51 UTC, nilsdeppe requested changes
LGTM, just one suggestion. Please squash right away

2023-03-28 19:51 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/SendToWorldtube.hpp
> +      auto& mesh_velocity_on_face =
Reading this I worry that you are overwriting `shift` with the velocity. Can you comment that this is okay and why, just for whoever looks at it in the future? Maybe even adding equations would be useful?

Also, should there be an `if (mesh_velocity.has_value())` to guard against errors on a static mesh?

2023-03-29 12:28 UTC, nikwit commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/SendToWorldtube.hpp
> +      auto& mesh_velocity_on_face =
Thank you. I added a check for the mesh velocity and a comment that the shift allocation is free at this point in the action.

2023-03-29 16:09 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/SendToWorldtube.hpp
> +      auto& mesh_velocity_on_face =
Thanks!

2023-03-29 16:09 UTC, nilsdeppe approved these changes

2023-03-29 17:31 UTC, merged