Add Alfven wave solution to ForceFree system
sxs-collaboration/spectre pull request #4893
Opened 2023-03-30 21:20 UTC by yoonso0-0

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-04-04 20:11 UTC, wthrowe requested changes

2023-04-04 20:11 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/ForceFree/AlfvenWave.cpp
> +         "The wave speed cannot be exactly -1.0 or 1.0");
Take an `Options::Context` as the last argument to the constructor and use `PARSE_ERROR` for this error.  That way it will be reported nicely if triggered by an input file.  (Search the code for "PARSE_ERROR" if you need an example.)

2023-04-04 20:11 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/ForceFree/AlfvenWave.cpp
> +  const auto& x_coord = x.get(0);
Prefer `get<N>(x)` over `x.get(N)` when `N` is a constant.  Change the rest of the occurrences as well.

2023-04-04 20:11 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/ForceFree/Test_AlfvenWave.cpp
> +      std::make_unique<AlfvenWave>();
Don't use a default-constructed object here, and then check that the deserialized object is equal to the original.

2023-04-04 20:11 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/ForceFree/AlfvenWave.hpp
> +  friend bool operator!=(const AlfvenWave& lhs, const AlfvenWave& rhs);
`!=` does not need to be a friend.

2023-04-08 00:38 UTC, yoonso0-0 commented
Rebased and pushed fixup

2023-04-11 01:45 UTC, wthrowe commented
Some stuff got moved from `Parallel` to `Utilities/Serialization` in #4917, so you'll need to fix your includes.  The fixup looks good, and you can squash that in as well.

2023-04-20 17:39 UTC, yoonso0-0 commented
Updated PR and squashed. Thank you!

2023-04-20 19:30 UTC, wthrowe approved these changes

2023-04-20 19:30 UTC, merged