Add InitializeSpacetimeTags mutator
sxs-collaboration/spectre pull request #4894
Opened 2023-03-30 21:21 UTC by nikwit

## Proposed changes
Adds a mutator that computes the inverse spacetime metric and the trace of the Christoffel symbols of the second kind. These will be needed for the 2nd order evolution of the worldtube.

2023-03-31 21:37 UTC, nilsdeppe requested changes
LGTM, couple small suggestions. Please squash immediately :)

2023-03-31 21:37 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/InitializeSpacetimeTags.hpp
> +  static auto apply(const gsl::not_null<tnsr::AA<double, Dim, Frame::Grid>*>
move definition to cpp?

2023-03-31 21:37 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/InitializeSpacetimeTags.hpp
> + * \details This assimes a circular orbit so the spacetime quantities are
`assimes` -> `assumes`?

2023-04-01 14:18 UTC, nikwit commented
thank you, I squashed it in

2023-04-01 16:17 UTC, nilsdeppe approved these changes

2023-04-01 20:57 UTC, nilsdeppe commented
CI failure is unrelated timeout

2023-04-01 20:57 UTC, merged