One d root finder
sxs-collaboration/spectre pull request #49
Opened 2017-06-21 23:54 UTC by osheamonn

2017-06-22 04:19 UTC, fmahebert commented on src/Numerical/RootFinding/CMakeLists.txt
> +    RootFinding/QuadraticEquation.cpp)
Moving the closing paren to the next line may reduce future conflicts (this shamelessly stolen from @nilsdeppe).

2017-06-22 04:46 UTC, fmahebert commented on src/Numerical/RootFinding/QuadraticEquation.cpp
> +  return x1;
The GSL [documentation](https://www.gnu.org/software/gsl/manual/html_node/Quadratic-Equations.html) indicates that if `gsl_poly_solve_quadratic` finds 0 or 1 real roots, then one or both of `x0`,`x1` will _not_ be modified. If this occurs then `x1` and potentially `x0` remain uninitialized. Spooky.

I would suggest,
* assigning  (`0`, `signaling_nan`, ...?) to both variables at declaration,
* adding an `ASSERT(numrealroots == 2, ...)` as in the function below.

2017-06-22 04:50 UTC, fmahebert commented on src/Numerical/RootFinding/QuadraticEquation.cpp
> +  return {{x0, x1}};
See above comment re: variable assignment. The `ASSERT` makes this code safe in some builds only.

2017-06-22 04:51 UTC, fmahebert commented on src/Numerical/RootFinding/RootFinder.hpp
> +/// Declares function find_root_by_brents_method
`find_root_of_function` ?

2017-06-22 04:52 UTC, fmahebert commented on tests/Unit/Numerical/RootFinding/CMakeLists.txt
> +  Numerical/RootFinding/Test_QuadraticEquation.cpp)
Paren

2017-06-22 04:54 UTC, fmahebert commented on tests/Unit/Numerical/RootFinding/Test_OneDRootFinder.cpp
> +  double rel_tol = 1e-5;
These tolerances seem very loose, I assume to make the test faster? I would suggest adding a comment to explain the reason for these values.

2017-06-22 10:16 UTC, nilsdeppe commented on src/Numerical/RootFinding/QuadraticEquation.cpp
> +  return x1;
As long as the GSL doesn't cause the `signaling_nan` to trigger that's the best way to go. If it doesn't play nice (which as a safety precaution we probably don't want to risk) is then we write it as:
```cpp
if (gsl_poly_solve_quadratic(a, b, c, &x0, &x1)) {
  return /*signaling_nan()*/;
}
```
We should make sure that `std::isnan` works as desired with `signaling_nan`

2017-06-22 16:51 UTC, fmahebert commented on src/Numerical/RootFinding/QuadraticEquation.cpp
> +  return x1;
Maybe you were being loose in your example, but note that the function is unsafe when `gsl_poly_solve_quadratic` returns 0 or 1, and is safe when it returns 2.

2017-06-22 20:11 UTC, kidder requested changes

2017-06-22 20:11 UTC, kidder commented on src/Numerical/RootFinding/QuadraticEquation.hpp
> + * \brief Returns the two positive roots of a quadratic equation ax^2 + bx + c =
two real roots

2017-06-22 20:11 UTC, kidder commented on tests/Unit/Numerical/RootFinding/Test_OneDRootFinder.cpp
> +}  // namespace
don't put the TEST_CASE in the namespace

2017-06-22 20:11 UTC, kidder commented on tests/Unit/Numerical/RootFinding/Test_QuadraticEquation.cpp
> +}
add a test that has two equal roots
add a test that has one positive, one real root
add a test that has no real roots and triggers the assert

2017-06-22 20:11 UTC, kidder commented on tests/Unit/Numerical/RootFinding/Test_QuadraticEquation.cpp
> +
add a test that has two equal positive roots and triggers the assert
add a test that has two positive roots and triggers the assert
add a test that has no positive roots and triggers the assert

2017-06-22 20:11 UTC, kidder commented on src/Numerical/RootFinding/QuadraticEquation.cpp
> +
license

2017-06-22 20:11 UTC, kidder commented on src/Numerical/RootFinding/QuadraticEquation.hpp
> +
license

2017-06-22 20:11 UTC, kidder commented on src/Numerical/RootFinding/RootFinder.hpp
> +
license

2017-06-22 20:11 UTC, kidder commented on tests/Unit/Numerical/RootFinding/Test_OneDRootFinder.cpp
> +
license

2017-06-22 20:11 UTC, kidder commented on tests/Unit/Numerical/RootFinding/Test_QuadraticEquation.cpp
> +
license

2017-06-22 20:11 UTC, kidder commented on tests/Unit/Numerical/RootFinding/Test_OneDRootFinder.cpp
> +}  // namespace
add a test that finds the root at the lower bound and another at the upper bound (this failed in older code)

2017-06-26 23:50 UTC, nilsdeppe approved these changes

2017-06-27 16:41 UTC, closed without merging