Add new flux communication actions
sxs-collaboration/spectre pull request #493
Opened 2018-01-25 20:53 UTC by nilsdeppe

## Proposed changes

This is on top of #491 
- The only new commit in this is "Add new flux communication Actions", which does as it says. This currently only works for hyperbolic (non-conservative) systems but will be pretty straight forward to generalize and merge the code from the current flux communication actions that does the slicing of the volume fluxes for conservative systems.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-01-29 21:53 UTC, kidder requested changes

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +        db::add_tag_prefix<Tags::dt, typename system::variables_tag>;
use the previous alias to save chars

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +        normal_dot_flux_tag,
get rid of system::

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +      db::item_type<
is there a type alias for the tag?

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +        db::create_from<db::RemoveTags<mortars_normal_dot_fluxes_tag,
std::move

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +             "h-adaptivity is not supported yet.\nDir: "
Direction, Dimension

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +        // differently.
add this will be improved later (also note that adaptivity does not affect this)

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +        receiver_proxy[ElementIndex<volume_dim>(neighbor)]
ElementIndex -> neighbor

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +    // return std::forward_as_tuple(box);
remove

2018-01-29 21:53 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication2.cpp
> +using Index_t = ElementIndex<volume_dim>;
IndexType

2018-01-29 21:53 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication2.cpp
> +    Metavariables, Index_t, tmpl::list<NumericalFluxTag>,
helper aliases for tmpl:list

2018-01-29 21:53 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication2.hpp
> +    using mortars_normal_dot_fluxes_tag = Tags::HistoryBoundaryVariables<
template type alias for mortars in detail namespace

2018-01-30 20:44 UTC, wthrowe approved these changes

2018-01-30 20:44 UTC, kidder approved these changes

2018-01-30 20:45 UTC, merged