Fix num orbits in BBH status
sxs-collaboration/spectre pull request #4930
Opened 2023-04-10 17:59 UTC by nilsvu

## Proposed changes

Assume the initial rotation angle is 0 for now. We can update this to read the initial rotation angle once we can read previous segments / checkpoints of a simulation.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-04-11 17:19 UTC, knelli2 requested changes

2023-04-11 17:19 UTC, knelli2 commented on tools/Status/ExecutableStatus/EvolveGhBinaryBlackHole.py
> +                covered_angle = rotation_z["Lambda"].iloc[-1]
`FunctionOfTime` now

2023-04-11 17:23 UTC, nilsvu commented on tools/Status/ExecutableStatus/EvolveGhBinaryBlackHole.py
> +                covered_angle = rotation_z["Lambda"].iloc[-1]
rebased 👍

2023-04-11 17:23 UTC, knelli2 approved these changes, later dismissed

2023-04-12 16:48 UTC, knelli2 approved these changes

2023-04-13 15:43 UTC, nilsdeppe approved these changes

2023-04-13 15:43 UTC, merged