Add versioning to all remaining domain and FoT classes, add docs
sxs-collaboration/spectre pull request #4938
Opened 2023-04-14 19:05 UTC by nilsvu

## Proposed changes

The domain will be serialized and written to output files so it can be used for interpolations, as are `domain::FunctionOfTime` classes. To be able to read in domains written by older versions of the code the `pup` function in this class and all `pup` functions it invokes support lightweight versioning. A `version` integer is written alongside the data when serializing, and read back in when deserializing.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-04-24 22:13 UTC, nilsvu commented
Clang-tidy failure is the unrelated TOMS748 issue

2023-04-26 18:56 UTC, wthrowe requested changes
I'm surprised that nothing gives a warning for checking that an unsigned integer is non-negative, but since nothing does I'm fine with the checks.

2023-04-26 18:56 UTC, wthrowe commented on src/Domain/Domain.hpp
> + * registered that were written by old versions of the code.
Should this sentence be the opposite?

2023-04-26 20:07 UTC, nilsvu commented on src/Domain/Domain.hpp
> + * registered that were written by old versions of the code.
Yep! Good catch.

2023-04-26 21:11 UTC, wthrowe approved these changes

2023-04-27 16:37 UTC, merged