Add GR SpEC initial data class
sxs-collaboration/spectre pull request #4949
Opened 2023-04-25 18:21 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-04-25 22:25 UTC, nilsvu commented
Discussing with @markscheel we came to the conclusion that trying to link with SpEC for testing this on CI is probably not worth the effort. Distributing the SpEC exporter in the public SpECTRE CI container may be problematic because SpEC is private (at the moment). We could distribute the SpEC exporter in another private container, or host the binary+header somewhere, but that's not trivial either. In practice, we will have SpEC installed on clusters and link to it. So, reluctantly, I suggest we merge this without tests.

2023-04-27 16:42 UTC, nilsdeppe requested changes
overall LGTM, some small thoughts

2023-04-27 16:42 UTC, nilsdeppe commented on cmake/SetupSpec.cmake
> +option(SPEC_ROOT "Path to the git directory of SpEC." OFF)
Can you document this in our build system docs where we describe "all" the CMake flags? Most of the notes in this file like MPI version & building the exporter manually should be somewhere in documentation. Maybe installation notes for the optional dependency or even a very. brief tutorial page? Not sure

2023-04-27 16:42 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/GeneralRelativity/InterpolateFromSpec.hpp
> +    spec_grid_coords[i] = std::vector<double>{get_element(get<0>(x), i),
you can remove the `<double>` if you want here

2023-04-27 16:42 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/GeneralRelativity/InterpolateFromSpec.hpp
> +  std::vector<std::vector<double*>> buffer_pointers{tmpl::size<Tags>::value};
std::vector constructors are silly, are you trying to create a 1-element vector or a vector of a given size? If given size, then `{}` -> `()` is safer

2023-04-27 16:42 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/GeneralRelativity/InterpolateFromSpec.hpp
> +    // WARNING: If the Tensor storage order changes for some reason, this
Would it be possible to add an assert based on the `component_suffix` function?

2023-04-27 16:42 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/GeneralRelativity/SpecInitialData.hpp
> +  static const inline std::vector<std::string> vars_to_interpolate_{
Make these an input file option? For doing BNS initial data we will need additional vars

2023-05-26 17:52 UTC, nilsvu commented on src/PointwiseFunctions/AnalyticData/GeneralRelativity/SpecInitialData.hpp
> +  static const inline std::vector<std::string> vars_to_interpolate_{
BNS ID is in a separate class, so I think this is ok.

2023-05-26 18:17 UTC, nilsvu commented
Updated with the requested changes. I think this is ready for review/merge. We still have to sort out some thread-safety issues in SpEC, but since we can only test things "in production" anyway it's easier to merge and fix issues when they come up.

2023-05-30 20:10 UTC, nilsvu commented
@nilsdeppe this is ready for another look

2023-05-30 20:19 UTC, nilsdeppe approved these changes

2023-05-30 20:20 UTC, merged