Add remaining AMR actions
sxs-collaboration/spectre pull request #4952
Opened 2023-04-26 03:00 UTC by kidder

## Proposed changes

- Adds an action that initializes the data on a new element created when joining multiple existing elements.  Currently, only the Element and Mesh are initialized, which is sufficient to test the infrastructure of AMR.
- Adds an action that collects the data from the existing elements that are being joined and sends them to the new element, as well as deleting the elements that have joined
- Adds an action that creates the new element when joining existing elements
- Adds an action that given the refinement flags for an element, will either call the AMR actions for creating new elements if the element wants to join or split (h-refinement), updates the Mesh if the element wants to change the number of grid points (p-refinement), and updates the Element based on the refinement flags of its neighbors.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

After this PR is merged:
- I will update `Executables/Examples/RandomAmr` which can be used to test all the AMR actions on an arbitrary Domain using random refinement.
- I will add mutators and projectors which will update the data used by an evolution system starting with scalar waves

2023-04-26 19:46 UTC, wthrowe requested changes

2023-04-26 19:46 UTC, wthrowe commented on src/Domain/Amr/NeighborsOfParent.cpp
> +  std::vector<ElementId<VolumeDim>> children_ids;
`reserve` space.

2023-04-26 19:46 UTC, wthrowe commented on src/ParallelAlgorithms/Amr/Actions/InitializeParent.hpp
> +  using tagged_tuple_t = typename helper<TagsList>::type;
Isn't this the same as `tagged_tuple_from_typelist`?

2023-04-26 19:46 UTC, wthrowe commented on src/ParallelAlgorithms/Amr/Actions/CollectDataFromChildren.hpp
> +  using tagged_tuple_t = typename helper<TagsList>::type;
Again, `tagged_tuple_from_typelist`.

2023-04-26 19:46 UTC, wthrowe commented on src/ParallelAlgorithms/Amr/Actions/CollectDataFromChildren.hpp
> +      auto id_to_check = ids_to_join.front();
`for (const auto& id_to_check : ids_to_join)`?

2023-04-26 19:46 UTC, wthrowe commented on tests/Unit/ParallelAlgorithms/Amr/Actions/Test_CollectDataFromChildren.cpp
> +                           {neighbor_3_id, neighbor_3_flags}};
I believe all these namespace-scope variables will be initialized every time `RunTests` is executed.  I'll let you judge whether they are expensive enough to worry about that.

2023-04-28 18:48 UTC, kidder commented
@wthrowe I pushed my fixups

2023-04-28 19:52 UTC, wthrowe commented
Squash.

2023-04-30 22:09 UTC, kidder commented
squashed and rebased

2023-05-02 17:21 UTC, kidder commented
@wthrowe please look at

2023-05-02 19:38 UTC, wthrowe approved these changes

2023-05-02 19:39 UTC, merged