Add Python Binding for Psi4Real
sxs-collaboration/spectre pull request #4965
Opened 2023-04-28 19:40 UTC by AlexCarpenter46

## Proposed changes

Add a python binding for Psi4Real

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-04-28 20:23 UTC, nilsvu requested changes

2023-04-28 20:23 UTC, nilsvu commented on src/PointwiseFunctions/GeneralRelativity/Python/Psi4Real.cpp
> +  m.def(
you can put bindings of pointwise functions directly in the `Bindings.cpp`, that reduces the number of boilerplate / files considerably.

2023-05-02 14:34 UTC, nilsvu requested changes
Looks great! One small thing. Please squash everything into one commit.

2023-05-02 14:34 UTC, nilsvu commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Python/Test_Bindings.py
> +        spatial_ricci = tnsr.ii[DataVector, 3, Frame.Inertial](num_points=1,
You can delete `Frame.Inertial` in all these

2023-05-02 17:38 UTC, nilsvu approved these changes

2023-05-02 17:38 UTC, nilsvu commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Python/Test_Bindings.py
> +class TestPsi4(unittest.TestCase):
name this `TestBindings`, but you can also do that in another PR.

2023-05-02 17:51 UTC, AlexCarpenter46 commented on tests/Unit/PointwiseFunctions/GeneralRelativity/Python/Test_Bindings.py
> +class TestPsi4(unittest.TestCase):
oh whoops, yeah I'll add that in the next pybinding PR for the gr functions

2023-05-03 16:46 UTC, merged