Speed up `GH::TimeDerivative` calculation for harmonic gauge
sxs-collaboration/spectre pull request #4970
Opened 2023-04-29 03:24 UTC by nikwit

## Proposed changes
When using harmonic gauge, some terms of the field equations can be set to zero and we can avoid calculating the second order Christoffel symbols and the sqrt of the determinant of the spatial metric alltogether.

This PR adds a check in `GH::TimeDerivative` whether the harmonic gauge is used and only computes these terms if it is not. The uncomputed variables are filled with NaNs.

Profiling showed this leads to a ~15% speed-up of the TimeDerivative::apply function on a single core on my laptop.

2023-07-18 13:05 UTC, nilsdeppe requested changes
LGTM, one small suggestion you can squash immediately

2023-07-18 13:05 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/TimeDerivative.cpp
> +    get(*sqrt_det_spatial_metric) =
Wrap in `#ifdef SPECTRE_DEBUG`? The rest of the code doesn't set `NaN`s in release

2023-07-20 13:49 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/TimeDerivative.cpp
> +    get(*sqrt_det_spatial_metric) =
Hmm, maybe my browser isn't refreshing right something went wrong during a push because I don't see the `ifdef`s

2023-07-20 14:56 UTC, nikwit commented on src/Evolution/Systems/GeneralizedHarmonic/TimeDerivative.cpp
> +    get(*sqrt_det_spatial_metric) =
sorry, I must have messed something up.

2023-07-20 15:04 UTC, knelli2 requested changes
Also update the PR description please.

2023-07-20 15:04 UTC, knelli2 commented on src/Evolution/Systems/GeneralizedHarmonic/TimeDerivative.hpp
> + * are not computed and instead filled with signaling NaNs.
"...in Debug mode"

2023-07-20 20:15 UTC, knelli2 approved these changes

2023-07-20 21:41 UTC, nilsdeppe approved these changes

2023-07-20 21:41 UTC, merged