Add some DataBox protocols
sxs-collaboration/spectre pull request #4983
Opened 2023-05-03 21:23 UTC by kidder

## Proposed changes

work towards #4761 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-05-03 21:24 UTC, kidder commented
@sxs-collaboration/spectre-core-devs I would appreciate some feedback before I proceed further...

2023-06-21 21:20 UTC, nilsvu requested changes
I think the mutator protocol looks great, that's exactly what we need more of. It has a clear name and documents a compile-time interface that people would otherwise have a lot of trouble understanding.

Example: Just yesterday Mike and I tried to figure out what the interface for "variable fixers" is. It's not documented (at least we didn't find any docs). Only when we read the source code of the FixVariables action did we realize that a `VariableFixer` just needs to be (1) a mutator and (2) option-creatable. It would be so much clearer if those two were protocols.

My suggestion: Can we limit this PR to the `Mutator` protocol and merge that first because it's very clear, then move on to the others?

2023-06-21 21:20 UTC, nilsvu commented on src/DataStructures/DataBox/Protocols/Mutator.hpp
> +        std::is_same_v<void, std::void_t<decltype(&ConformingType::apply)>>);
The apply function might be a template, in which case I think this won't work. Maybe do a quick test and delete this assert if it doesn't work? Also I think `db::mutate_apply` also works with `operator()`. Please add that to the docs.

2023-06-21 21:20 UTC, nilsvu commented on src/DataStructures/DataBox/Protocols/Mutator.hpp
> +///      - The additional arguments passed to `db::mutate_apply`
Add an example snippet please

2024-08-21 16:38 UTC, closed without merging