Allow extract-dat to extract single subfile to stdout
sxs-collaboration/spectre pull request #4988
Opened 2023-05-04 22:18 UTC by knelli2

## Proposed changes

Prints something like (for a 1 line dat file)
```
 Time  NumberOfPoints       Volume  L2Norm(GaugeConstraint)  L2Norm(ThreeIndexConstraint)
 0.02        154350.0 4.188761e+06             5.762183e-08                      0.000002
```

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-05-04 22:19 UTC, knelli2 commented
@wthrowe Does this seem like it'll do what you want?

2023-05-04 23:09 UTC, nilsvu requested changes

2023-05-04 23:09 UTC, nilsvu commented on src/IO/H5/Python/ExtractDatFromH5.py
> +              '-s',
`-d` for consistency with other tools

2023-05-04 23:09 UTC, nilsvu commented on src/IO/H5/Python/ExtractDatFromH5.py
> +        if num_cores > 1:
`out_dir and num_cores > 1`

2023-05-04 23:09 UTC, nilsvu commented on src/IO/H5/Python/ExtractDatFromH5.py
> +    else:
Don't need this else clause. The loop above is enough.

2023-05-04 23:11 UTC, nilsvu requested changes

2023-05-04 23:11 UTC, nilsvu commented on tests/Unit/IO/H5/Python/Test_ExtractDatFromH5.py
> +        self.failUnlessRaises(
This is nicer:

```
with self.assertRaises(ValueError):
    extract...
```

2023-05-05 00:17 UTC, nilsvu submitted a review, later dismissed

2023-05-05 17:07 UTC, wthrowe commented
Is there an option to set the precision?  Your example appears to only have 1 significant digit in one case, and being able to get full precision is useful in general.

2023-05-05 18:06 UTC, knelli2 commented
@wthrowe Like this?

```
Time                   NumberOfPoints         Volume                 L2Norm(GaugeConstraint) L2Norm(ThreeIndexConstraint)
2.0000000000000000e-02 1.5435000000000000e+05 4.1887614885579874e+06 5.7621831920527475e-08  2.4807265343400288e-06      
```

2023-05-05 18:36 UTC, wthrowe approved these changes
Yes, that's fine.  Thanks!

2023-05-05 19:50 UTC, nilsvu approved these changes

2023-05-06 02:19 UTC, merged