Add HalfWedge functionality to Wedge3D
sxs-collaboration/spectre pull request #499
Opened 2018-01-29 23:40 UTC by gsb76

## Proposed changes

Adds a constructor to Wedge3D allowing for the construction of half wedges.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-01-29 23:42 UTC, gsb76 commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +  if(using_half_wedge_){xi = (xi + (using_rhs_half_ ? 1.0 : -1.0))/2.0;}
Test inverse

2018-01-30 03:31 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> +  Wedge3D(double radius_of_other_surface, double radius_of_spherical_surface,
I have literally no idea what using_rhs_half means

2018-01-30 04:18 UTC, nilsdeppe commented
At a very quick glance, you have forgotten to add the new member variables to the pup function and operator==, possibly elsewhere.

2018-01-30 19:07 UTC, wthrowe requested changes

2018-01-30 19:07 UTC, wthrowe commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +          2.0;
`make_with_value<ReturnType>(xi, 0.5)`, etc. so you're doing double math rather than DataVector math.

2018-01-30 19:07 UTC, wthrowe commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +          2.0;
Again, math in the make_with_value argument.

2018-01-30 19:07 UTC, wthrowe commented on src/Domain/CoordinateMaps/Wedge3D.hpp
>     */
The documentation should be applied to both constructors, but since they have slightly different arguments I'm not sure the best way to do that.  You could change the last argument to an enum (UPPER, LOWER, BOTH) with a default argument so they could be combined.  I haven't looked at whether that actually works well in the implementation.

2018-01-30 19:07 UTC, wthrowe commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +                  "[Domain][Unit]") {
You need to test more than the Jacobians.

2018-01-30 22:00 UTC, kidder requested changes
do stuff, more tests

2018-02-13 20:06 UTC, kidder requested changes
address Will's comments and add documentation about the limited use cases of HalfWedge

2018-02-19 19:36 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> +   * full wedge, or the full wedge entirely. Half wedges are currently only
kng. ru xryd

2018-02-19 19:54 UTC, nilsdeppe requested changes

2018-02-19 19:54 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> +   * useful in constructing domains for binary systems, as blocks are
remove part after `,`

2018-02-19 19:54 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +        true,         CoordinateMaps::Wedge3D::WedgeHalves::LowerOnly};
serialize and deserialize the map, then call test_jacobian, etc. again on the deserialized copy

2018-02-19 19:54 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +        false,        CoordinateMaps::Wedge3D::WedgeHalves::LowerOnly};
ditto

2018-02-19 22:14 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +    xi -= make_with_value<ReturnType>(xi, 1.0);
fix `std::move(-BLAH)` -> `std::move(BLAH *= -1.0)`

2018-02-19 22:43 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +         lhs.with_equiangular_map_ == rhs.with_equiangular_map_ and
Use GENERATE_INSTATIATIONS

2018-03-16 19:43 UTC, gsb76 commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +    xi += make_with_value<ReturnType>(xi, 1.0);
Check += 1.0

2018-03-16 19:43 UTC, gsb76 commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +    xi += make_with_value<ReturnType>(xi, -1.0);
use -= 1.0

2018-03-16 19:43 UTC, gsb76 commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +    xi -= make_with_value<ReturnType>(xi, -1.0);
+= 1.0

2018-03-16 19:43 UTC, gsb76 commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +    xi -= make_with_value<ReturnType>(xi, -1.0);
everywhere

2018-03-16 19:43 UTC, gsb76 commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
>  }
indent

2018-03-16 21:09 UTC, nilsdeppe approved these changes

2018-03-16 21:09 UTC, kidder approved these changes

2018-03-16 21:14 UTC, wthrowe approved these changes

2018-03-17 02:23 UTC, merged