Get CaltechHPC up and running again
sxs-collaboration/spectre pull request #4993
Opened 2023-05-08 19:44 UTC by knelli2

## Proposed changes

- There were several python things I noticed when trying to use the `spectre status` CLI so I changed those
  - Pandas version
  - Backward support for old input files that don't have metadata
  - Parsing time format from SLURM 
- For some reason, `charmrun` didn't seem to recognize the `++runscript` options. Since we build with MPI on CaltechHPC, `charmrun` is just a thin wrapper around `mpirun` so I just used that instead.
- I edited the default number of cores to be 56 (with 2 charm nodes per physical node) so we can make use of our new reservation. If you decide to run on the 32 core nodes, you'll have to edit the submit script. Specifically, make the tasks per node only 1 now.
- Yaml-cpp told me to compile with `-fPIC` so I did.
- Load balancing doesn't work (as far as I know) with charm 7, so don't even bother including the Scotch LB in cmake
- Use system memory allocator so we can use pybindings.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-05-10 03:05 UTC, nilsvu approved these changes

2023-05-10 03:07 UTC, nilsvu commented
> Use system memory allocator so we can use pybindings.

Note: pybindings should also work with jemalloc.

2023-05-10 23:00 UTC, nilsvu requested changes

2023-05-10 23:00 UTC, nilsvu commented on support/Environments/caltech_hpc_gcc.sh
> +              -D CMAKE_CXX_FLAGS=-fPIC \
The "right" way to do this is `-D CMAKE_POSITION_INDEPENDENT_CODE=ON`

2023-05-10 23:00 UTC, nilsvu commented on support/Environments/caltech_hpc_gcc.sh
> +prepend-path PYTHONPATH ${VIRTUAL_ENV}/lib/python3.8/site-packages
delete this line (shouldn't be needed, or did you encounter some problem?)

2023-05-17 23:14 UTC, nilsvu reviewed
I'd say drop the first couple of commits that I moved to #5007. I think we can just merge this and keep testing. We can run a simulation with this.

2023-05-17 23:14 UTC, nilsvu commented on support/Environments/caltech_hpc_gcc.sh
>            -D OVERRIDE_ARCH=skylake-avx512 \
Add `-D MACHINE=CaltechHpc`

2023-05-18 02:09 UTC, knelli2 commented
Ok done!

2023-05-18 02:11 UTC, nilsvu approved these changes, later dismissed

2023-05-18 02:13 UTC, nilsvu approved these changes

2023-05-18 06:41 UTC, merged