Set default build type to Debug
sxs-collaboration/spectre pull request #5
Opened 2017-04-20 20:46 UTC by kidder

2017-04-21 02:25 UTC, nilsdeppe requested changes

2017-04-21 02:25 UTC, nilsdeppe commented on cmake/SetBuildType.cmake
> +  else()
This can be an `endif()` since if the predicate is true, then CMake aborts

2017-04-24 17:28 UTC, nilsdeppe approved these changes

2017-04-24 21:12 UTC, markscheel approved these changes

2017-04-24 21:29 UTC, merged