Add CLI endpoint to validate input files
sxs-collaboration/spectre pull request #5025
Opened 2023-05-20 07:40 UTC by nilsvu

## Proposed changes

Try it like this:

```
spectre validate INPUT_FILE
```

In particular, this will be used in #4996 to validate input files before scheduling runs.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-05-22 18:35 UTC, knelli2 requested changes
I think you can drop the build dir commit because it's already taken care of in #5023. Then I believe these can be merged simultaneously rather than having to rebase one.

2023-05-22 18:35 UTC, knelli2 commented on tools/ValidateInputFile.py
> +      lineno: Line number in the input file where the parse error occurred.
I think `line_number` is clearer and it's not that much longer.

2023-05-22 21:34 UTC, knelli2 submitted a review, later dismissed

2023-05-23 00:47 UTC, knelli2 requested changes
This test timed out a couple times, maybe because it takes a sec to get going? Probably should increase test timeout if possible

2023-05-23 19:04 UTC, knelli2 commented
Looks good, but I think you used black to format instead of yapf because of your other PR.

2023-05-24 01:07 UTC, knelli2 approved these changes

2023-05-24 16:56 UTC, nilsvu commented
@kidder @wthrowe can one of you take this one please?

2023-05-26 17:51 UTC, kidder approved these changes

2023-05-26 18:52 UTC, merged