Put AMR options in group, add verbosity, fix averages
sxs-collaboration/spectre pull request #5033
Opened 2023-05-23 18:25 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-05-23 18:48 UTC, kidder requested changes
I averaged over size_t as I found the doubles annoying to read, but I don't object to the change...

2023-05-23 18:48 UTC, kidder commented on src/ParallelAlgorithms/Amr/Actions/SendAmrDiagnostics.hpp
> +#include "IO/Logging/Verbosity.hpp"
alphabet

2023-05-23 18:49 UTC, kidder commented on src/ParallelAlgorithms/Amr/Actions/SendAmrDiagnostics.hpp
> +#include "IO/Logging/Verbosity.hpp"
also there is a failing check...

2023-05-23 21:09 UTC, nilsvu commented on src/ParallelAlgorithms/Amr/Actions/SendAmrDiagnostics.hpp
> +#include "IO/Logging/Verbosity.hpp"
fixed!

2023-05-23 21:41 UTC, kidder approved these changes, later dismissed

2023-05-23 21:56 UTC, nilsvu commented
Fixed the input file

2023-05-23 22:09 UTC, kidder submitted a review, later dismissed

2023-05-24 00:51 UTC, kidder approved these changes

2023-05-24 02:27 UTC, merged