Add subcell ghost data for ForceFree system
sxs-collaboration/spectre pull request #5034
Opened 2023-05-23 21:19 UTC by yoonso0-0

## Proposed changes

Side note : It turns out that we should not evaluate `TildeJ` on faces from the reconstructed values of `E, B, ..`, but reconstruct `TildeJ` itself for stable evolution.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-06-09 17:30 UTC, kidder requested changes
you can squash any changes

2023-06-09 17:30 UTC, kidder commented on src/Evolution/Systems/ForceFree/Subcell/GhostData.cpp
> +          (tilde_j.size() +
include for tensor

2023-06-09 17:30 UTC, kidder commented on src/Evolution/Systems/ForceFree/Subcell/GhostData.hpp
> +      const tnsr::I<DataVector, 3, Frame::Inertial>& tilde_j, size_t rdmp_size);
include for tensor/TypeAliases

2023-06-09 17:30 UTC, kidder commented on tests/Unit/Evolution/Systems/ForceFree/Subcell/Test_GhostData.cpp
> +#include "Domain/Tags.hpp"
not needed?

2023-06-09 17:30 UTC, kidder commented on tests/Unit/Evolution/Systems/ForceFree/Subcell/Test_GhostData.cpp
> +#include "Evolution/DgSubcell/Projection.hpp"
not needed?

2023-06-12 17:53 UTC, yoonso0-0 commented
Squashed and rebased

2023-06-13 01:17 UTC, kidder commented
@yoonso0-0 this needs a rebase

2023-06-15 16:37 UTC, yoonso0-0 commented
Rebased on develop

2023-06-15 19:47 UTC, kidder approved these changes

2023-06-15 19:48 UTC, merged