Add initial data TCI for ForceFree system
sxs-collaboration/spectre pull request #5040
Opened 2023-05-24 21:17 UTC by yoonso0-0

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-06-09 17:19 UTC, kidder requested changes
you can squash the changes

2023-06-09 17:19 UTC, kidder commented on src/Evolution/Systems/ForceFree/Subcell/InitialDataTci.hpp
> +    const Scalar<DataVector>& dg_tilde_e_mag,
- include for Tensor/TypeAliases
- forward declaration of DataVector

2023-06-12 18:20 UTC, yoonso0-0 commented
Squashed and rebased

2023-06-12 19:36 UTC, kidder approved these changes

2023-06-12 22:37 UTC, merged