Use correct mesh and jacobian for integrals with subcell
sxs-collaboration/spectre pull request #5051
Opened 2023-05-26 19:02 UTC by ffoucart

## Proposed changes

Modify ObserveVolumeIntegrals so that it uses the Dg or Subcell mesh as appropriate.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-05-26 19:08 UTC, knelli2 approved these changes

2023-05-26 19:27 UTC, knelli2 requested changes
I don't think all executables have the `Events::Tags::ObserverXXX` tags implemented. What if you didn't put these tags in the `argument_tags` list, but instead only had the observation box. Then inside the function, check if the observation box has the event tags; if it does, get that, if not, use the DG one?

2023-05-27 00:53 UTC, ffoucart commented
I guess it's that or updating all relevant executables... as this is an observer, ideally any executable that calls it could presumably use the more generic Events::Tag::XXX tags. I'm happy to go either way.

2023-05-27 02:26 UTC, knelli2 commented
@ffoucart I have no preference. Whichever is less work for you

2023-05-27 03:57 UTC, nilsvu requested changes

2023-05-27 03:57 UTC, nilsvu commented on src/ParallelAlgorithms/Events/ObserveVolumeIntegrals.hpp
> +                                           Frame::Inertial>,
Could you run clang-format over this? What I usually do is run git-clang-format when I have staged changes, or something like `git-clang-format HEAD~1` to format the last commit.

2023-05-30 14:44 UTC, nilsvu commented
There's a CI error. I think you have to add the ObserverDetInvJac tag to some executable.

2023-05-30 14:47 UTC, ffoucart commented
Yes; that's related to Kyle's comment, but I have not had the chance to fix it yet (yesterday was a holiday in the US)

2023-06-01 15:37 UTC, nilsvu approved these changes

2023-06-01 16:00 UTC, merged