Add RAII class for saving and restoring FPE state
sxs-collaboration/spectre pull request #5052
Opened 2023-05-26 19:29 UTC by wthrowe

We still can't reliably recover from an FPE because throwing exceptions from a signal handler isn't well supported, but this should make FPE-handling preserved when other errors occur.  It will also prevent code from unintentionally enabling FPEs if it temporarily disables them when they were already disabled.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-06-04 19:35 UTC, wthrowe commented
I think this is working now, but the gcc-11-release CI build keeps timing out, presumably because ccache is useless when you touch something used by ERROR and ASSERT.  Might still be a problem, though, since we can't populate the cache if we can't build.

2023-06-09 16:44 UTC, kidder requested changes
you can squash any changes

2023-06-09 16:44 UTC, kidder commented on tests/Unit/ErrorHandling/Test_FloatingPointExceptions.cpp
> +  // Stack unwinding from out FPE handler doesn't work on all
out -> our?

2023-06-09 16:44 UTC, kidder commented on tests/Unit/ErrorHandling/Test_FloatingPointExceptions.cpp
> +}
can you add CHECK_THROWS that test the ASSERTs?

2023-06-09 16:44 UTC, kidder commented on src/ApparentHorizons/StrahlkorperInDifferentFrame.cpp
> +  std::tie(r_min, r_max) = [&dest_cartesian_coords, &center_dest]() {
include <utility> for std::tie

2023-06-09 16:44 UTC, kidder commented on src/Domain/CoordinateMaps/UniformCylindricalEndcap.cpp
> +std::tuple<double, double> rhobar_min_max(
include <tuple>

2023-06-09 16:44 UTC, kidder commented on src/Domain/CoordinateMaps/UniformCylindricalFlatEndcap.cpp
> +std::tuple<double, double> rhobar_min_max(
include tuple

2023-06-09 16:44 UTC, kidder commented on tests/Unit/Framework/SetupLocalPythonEnvironment.cpp
> +    disable_fpes.restore_exceptions();
why do you need to explicitly call restore here?

2023-06-09 21:28 UTC, wthrowe reviewed
I also renamed the variables in macros to avoid potential name clashes.

2023-06-09 21:28 UTC, wthrowe commented on tests/Unit/ErrorHandling/Test_FloatingPointExceptions.cpp
> +  // Stack unwinding from out FPE handler doesn't work on all
I assume I intended "our", but it's not really related to anything particular to us, so I changed the phrase to "from a signal handler".

2023-06-09 21:28 UTC, wthrowe commented on tests/Unit/Framework/SetupLocalPythonEnvironment.cpp
> +    disable_fpes.restore_exceptions();
I don't really, but it felt like the other uses were intending to disable for the entire function while this was intending to do so only for the call to `init_numpy()`, so I added this so it would work as intended if more code was added below here.

2023-06-09 21:28 UTC, wthrowe commented on tests/Unit/ErrorHandling/Test_FloatingPointExceptions.cpp
> +}
Added at the start because that part should work on ARM builds.

2023-06-09 22:02 UTC, kidder commented on tests/Unit/Framework/SetupLocalPythonEnvironment.cpp
> +    disable_fpes.restore_exceptions();
okay

2023-06-09 22:04 UTC, kidder reviewed
looks good, squash

2023-06-10 17:18 UTC, kidder approved these changes

2023-06-12 19:34 UTC, kidder requested changes
The release builds are failing because these are checking that asserts are triggered.
I believe you need to surround them with a `#ifdef SPECTRE_DEBUG`

2023-06-12 21:20 UTC, wthrowe commented
Derp.  Also rebased for the db::mutate change.

2023-06-13 15:55 UTC, kidder commented
ignoring clang-tidy Boost failure, and build time out

2023-06-13 15:55 UTC, merged