Allow L2IntegralNorm for subcell
sxs-collaboration/spectre pull request #5053
Opened 2023-05-26 19:31 UTC by ffoucart

## Proposed changes

By getting the determinant of the jacobian on the correct grid (subcell or dg), we can take the L2IntegralNorm of a field when using the subcell code.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-07-06 13:26 UTC, nilsdeppe commented
This looks good. I'm not sure why the tests are failing, though

2023-07-06 17:05 UTC, ffoucart commented
Some executables need to get the correct event tag apparently.

2023-07-07 15:10 UTC, nilsvu submitted a review, later dismissed

2023-07-07 15:31 UTC, kidder requested changes
this doesn't work on a subcell grid (it always uses the DetInvJacobian from the DG grid).  You need to add an equivalent `evolution:dg::subcell::Tags` version of the `ObserverDetInvJacobianCompute` that picks the correct thing based on the ActiveGrid.  See Evolution/DgSubcell/Tags/ObserverCoordinates.hpp 
Also this PR needs a unit test

2023-07-07 17:12 UTC, ffoucart commented
Isn't this already handled by
`evolution::dg::subcell::Tags::ObserverJacobianAndDetInvJacobian<
                  volume_dim, Frame::ElementLogical, Frame::Inertial>`
in Evolution/DgSubcell/Tags/ObserverCoordinates.hpp, together with
`using non_tensor_compute_tags = tmpl::append<
      tmpl::conditional_t<
          use_dg_subcell,
          tmpl::list<
              evolution::dg::subcell::Tags::ObserverMeshCompute<volume_dim>,
              evolution::dg::subcell::Tags::ObserverInverseJacobianCompute<
                  volume_dim, Frame::ElementLogical, Frame::Inertial>,
              evolution::dg::subcell::Tags::ObserverJacobianAndDetInvJacobian<
                  volume_dim, Frame::ElementLogical, Frame::Inertial>>,
          tmpl::list<::Events::Tags::ObserverMeshCompute<volume_dim>,
                     ::Events::Tags::ObserverInverseJacobianCompute<
                         volume_dim, Frame::ElementLogical, Frame::Inertial>,
                     ::Events::Tags::ObserverJacobianCompute<
                         volume_dim, Frame::ElementLogical, Frame::Inertial>,
                     ::Events::Tags::ObserverDetInvJacobianCompute<
                         Frame::ElementLogical, Frame::Inertial>>>,`

2023-07-07 17:14 UTC, ffoucart commented
I could certainly add one that _only_ computes the determinant, but as the one computing the determinant and the jacobian is already in the observer box, I'm assuming the jacobian is actually used somewhere.

2023-07-07 17:18 UTC, ffoucart commented
(I'll look into a unit test, hopefully there is already one for other norms using subcell that I can adapt)

2023-07-07 17:26 UTC, kidder commented
ah, I didn't look at that tag as it doesn't follow our convention that compute tags have Compute at the end of their name.  Yes that should be fine as long as it is added to the `non_tensor_compute_tags`.  Having the above block of code in either an additional test for L2IntegralNorm or the upgrade instructions of the PR would be helpful

2023-07-08 03:08 UTC, ffoucart commented
Ok - I added upgrade instruction and tags to all the executables that seem to need them, and I updated the OberverNorm test so that it also uses L2IntegralNorm for finite difference (I also test the volume for FD now... that was made possible a while a go when we added the integration routines for FD, but this test was not updated at the time).

2023-07-09 03:22 UTC, nilsdeppe requested changes
LGTM! Just a formatting request you can squash in immediately

2023-07-09 03:22 UTC, nilsdeppe commented on tests/Unit/ParallelAlgorithms/Events/Test_ObserveNorms.cpp
> +  else{
could you clang-format this block please? The for and else brace spacing specifically, also a space before `{` on line 280

2023-07-10 15:18 UTC, nilsvu approved these changes

2023-07-12 01:24 UTC, nilsdeppe approved these changes

2023-07-12 03:42 UTC, kidder approved these changes

2023-07-12 03:42 UTC, merged