Add Interface Null Norm PyBinding
sxs-collaboration/spectre pull request #5069
Opened 2023-06-02 19:56 UTC by estherroselopez

## Proposed changes

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-06-07 23:37 UTC, nilsvu approved these changes, later dismissed

2023-06-07 23:38 UTC, nilsvu commented
Please rebase on the latest `develop` branch to resolve the conflicts. Note that we switched Python formatting recently, so look at the upgrade instructions in #3730 if that's an issue (or ask me).

2023-06-13 00:08 UTC, nilsvu approved these changes, later dismissed

2023-06-21 00:54 UTC, nilsvu requested changes
Please squash the two commits together.

2023-06-21 00:54 UTC, nilsvu commented on src/NumericalAlgorithms/Spectral/Spectral.hpp
> -    basis == Basis::FiniteDifference ? 24 : 12;
Please remove this change (we should probably do it, but in another PR)

2023-06-26 23:43 UTC, nilsvu approved these changes, later dismissed

2023-07-05 16:51 UTC, nilsdeppe reviewed
@nilsvu could you take a look at this please?

2023-07-05 17:51 UTC, nilsvu approved these changes

2023-07-05 17:56 UTC, merged

2023-07-05 17:56 UTC, nilsvu commented
Looks good! Thanks @estherroselopez. Since this is your first contribution we invite you to add your name to the author list of the code in the `Metadata.yaml` file. Just add an entry for yourself in `Authors.Contributors` and open a pull request with the change. Once the pull request is merged, your name will appear on the [SpECTRE DOI on Zenodo](https://doi.org/10.5281/zenodo.4290404) with the next public release.