Add more Pybindings for GR.
sxs-collaboration/spectre pull request #5074
Opened 2023-06-02 23:04 UTC by kenzenjones

## Proposed changes

This adds pybindings for the following in GR:

- DerivativesOfSpacetimeMetric
- InverseSpacetimeMetric
- SpacetimeMetric
- SpatialMetric
- TimeDerivativeOfSpacetimeMetric
- TimeDerivativeOfSpatialMetric

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-06-02 23:11 UTC, knelli2 commented
Could you add that list you have in the PR description into the commit message as well? Just add a blank line between "Add more Pybindings for GR." and the start of the list.

2023-06-02 23:34 UTC, nilsvu requested changes

2023-06-02 23:34 UTC, nilsvu commented on src/PointwiseFunctions/GeneralRelativity/Python/Bindings.cpp
> +  m.def("spacetime_deriv_spacetime_metric",
Please name this function `derivatives_of_spacetime_metric` like in C++

2023-06-03 06:59 UTC, knelli2 approved these changes

2023-06-03 15:21 UTC, nilsvu approved these changes
Looks good 👍

2023-06-03 15:21 UTC, merged