Write checkpoints to Checkpoints/ directory
sxs-collaboration/spectre pull request #5079
Opened 2023-06-06 18:01 UTC by nilsvu

## Proposed changes

Preparation for #4996.

### Upgrade instructions

Checkpoints are now written in the format `Checkpoints/Checkpoint_0123`.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-06-06 18:05 UTC, knelli2 requested changes
Small thing

2023-06-06 18:05 UTC, knelli2 commented on tests/InputFiles/ExampleExecutables/RandomAmr1D.yaml
> +  - Checkpoints/Checkpoint_000000
Too many zeros?

2023-06-06 21:50 UTC, nilsvu commented on tests/InputFiles/ExampleExecutables/RandomAmr1D.yaml
> +  - Checkpoints/Checkpoint_000000
Fixed. There's a bug in the CMake testing code that I'll try to fix in a separate PR. Edit: #5080

2023-06-07 21:30 UTC, knelli2 approved these changes

2023-06-09 15:24 UTC, nilsvu commented
@wthrowe could you take this one as well?

2023-06-09 19:14 UTC, wthrowe approved these changes, later dismissed

2023-06-09 19:15 UTC, wthrowe commented
Approved, but needs a rebase.

2023-06-09 20:46 UTC, nilsvu commented
done

2023-06-09 20:51 UTC, wthrowe approved these changes

2023-06-12 19:13 UTC, merged