Added pybindings for DerivativeSpatialMetric in GR
sxs-collaboration/spectre pull request #5088
Opened 2023-06-07 23:42 UTC by ajosorio3

## Proposed changes

Added pybinding for DerivativeSpatialMetric in GR.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-06-09 15:00 UTC, nilsvu requested changes

2023-06-09 15:00 UTC, nilsvu commented on src/PointwiseFunctions/GeneralRelativity/Python/Bindings.cpp
> +      "derivative_inverse_spatial_metric",
Please name this exactly like the C++ function: `deriv_inverse_spatial_metric` (it's easier to work with the pybindings if they mirror the C++ interface exactly)

2023-06-13 21:07 UTC, closed without merging

2023-06-13 22:36 UTC, nilsvu commented
Did you intend to close this PR? You can just keep it open while you're making changes. The PR updates when you push to the branch.

2023-06-13 22:41 UTC, ajosorio3 commented
HI Nils, I noticed my proposed changes were for the develop branch instead of my own branch. I'll be making a new PR with your proposed changes and provide the link here

2023-06-13 22:42 UTC, nilsvu commented
Ok!

2023-06-13 22:54 UTC, ajosorio3 commented
Here is the link for the new PR: https://github.com/sxs-collaboration/spectre/pull/5098