Fix a typo in Poisson system docs
sxs-collaboration/spectre pull request #5117
Opened 2023-06-22 17:53 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-06-23 23:37 UTC, knelli2 requested changes

2023-06-23 23:37 UTC, knelli2 commented on src/Elliptic/Systems/Poisson/FirstOrderSystem.hpp
> + * \f}
Add `&` to the `=` so things line up nicely like you do below?

2023-06-24 21:58 UTC, knelli2 approved these changes

2023-06-27 23:24 UTC, wthrowe approved these changes

2023-06-27 23:25 UTC, wthrowe commented
Ignoring obviously unrelated timeouts.

2023-06-27 23:25 UTC, merged