Boundary history class
sxs-collaboration/spectre pull request #512
Opened 2018-02-06 21:52 UTC by wthrowe

### Types of changes:

- [ ] Bugfix
- [X] New feature

### Component:

- [X] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-02-06 22:46 UTC, nilsdeppe requested changes

2018-02-06 22:46 UTC, nilsdeppe commented on src/Time/BoundaryHistory.hpp
> +  /// Modify history data on one of the sides.  See the corresponding
change comment

2018-02-06 22:46 UTC, nilsdeppe commented on src/Time/BoundaryHistory.hpp
> +  for (auto it = local_data_.begin(); it != first_needed.base(); ++it) {
Can the local and remote functions be combined?

2018-02-06 22:46 UTC, nilsdeppe commented on tests/Unit/Time/Test_History.cpp
> +      for (size_t i = 0; i < hist.local_size(); ++i) {
++i, ++it

2018-02-06 22:46 UTC, nilsdeppe commented on tests/Unit/Time/Test_History.cpp
> +      for (size_t i = 0; i < hist.remote_size(); ++i) {
++i, ++it

2018-02-06 22:46 UTC, nilsdeppe commented on tests/Unit/Time/Test_History.cpp
> +  const auto check_state = [](HistoryType& hist) noexcept {
turn into separate function

2018-02-07 20:51 UTC, kidder requested changes

2018-02-07 20:51 UTC, kidder commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +      // Latest of start of current step (otherwise was computed in a
Latest time from either the time of the start of the current step (...

2018-02-07 20:51 UTC, kidder commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +      // previous call) and the times of the side data being coupled
side -> remote (or remote side)

2018-02-07 20:51 UTC, kidder commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +      // Earliest of the end of the current step (since the step can't
Earliest time from either the time at the end of the current ...

2018-02-07 20:51 UTC, kidder commented on src/Time/TimeSteppers/AdamsBashforthN.hpp
> +      // depend on later data), and target_order steps after the
and the times of (something about the remote data)

2018-02-09 21:21 UTC, kidder reviewed
squash

2018-02-09 21:53 UTC, kidder approved these changes

2018-02-09 22:35 UTC, nilsdeppe approved these changes

2018-02-09 22:35 UTC, merged