Add pybinding for Spatial Ricci Tensor
sxs-collaboration/spectre pull request #5121
Opened 2023-06-23 21:51 UTC by ajosorio3

## Proposed changes

Add a pybinding for spatial ricci tensor

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-06-24 15:38 UTC, nilsvu requested changes

2023-06-24 15:38 UTC, nilsvu commented on src/DataStructures/Tensor/Python/tnsr.py
> +ijaa = TensorMeta("ijaa")
There a section with mixed-indices tensors a few lines below, move it there I think

2023-06-24 15:38 UTC, nilsvu commented on src/PointwiseFunctions/GeneralRelativity/GeneralizedHarmonic/Python/Bindings.cpp
> +     static_cast<tnsr::ii<DataVector,Dim> (*)(
Please run clang-format over the file. An easy way to do that is to run `git-clang-format HEAD~1` (this runs over the last commit)

2023-06-29 20:26 UTC, ajosorio3 commented
Made those changes, ran clang-format and rebased

2023-06-30 06:59 UTC, nilsvu approved these changes

2023-06-30 06:59 UTC, merged