Move LowerSpatialFourVelocity out of Xcts
sxs-collaboration/spectre pull request #5123
Opened 2023-06-26 15:47 UTC by ffoucart

## Proposed changes

Move LowerSpatialFourVelocityCompute from Xcts to PointwiseFunctions/Hydro. This should allow us to observe LowerSpatialFourVelocityCompute  if we want to write it on disk and restart using NumericInitialData.
The base tag was already in PointwiseFunctions/Hydro, so hopefully this does not create any new dependencies.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-06-26 18:20 UTC, nilsvu requested changes

2023-06-26 18:20 UTC, nilsvu commented on src/PointwiseFunctions/Hydro/LowerSpatialFourVelocity.cpp
> +#include "LowerSpatialFourVelocity.hpp"
full path

2023-06-26 18:20 UTC, nilsvu commented on src/PointwiseFunctions/Hydro/LowerSpatialFourVelocity.cpp
> -#include "Utilities/Gsl.hpp"
Keep this include (for `gsl::not_null`) and/or move the include to hpp

2023-06-26 18:20 UTC, nilsvu commented on src/PointwiseFunctions/Hydro/LowerSpatialFourVelocity.hpp
> +/// \brief Items related to hydrodynamic systems.
This should be documented elsewhere (also the Tags namespace)

2023-06-26 19:51 UTC, nilsvu requested changes
Please squash

2023-06-26 19:51 UTC, nilsvu commented on src/PointwiseFunctions/Hydro/LowerSpatialFourVelocity.hpp
> +/// %Tags for hydrodynamic systems.
Also delete this

2023-06-26 23:17 UTC, nilsvu commented on src/PointwiseFunctions/Hydro/LowerSpatialFourVelocity.hpp
> +#include "Options/String.hpp"
remove this, also remove EOS include

2023-06-27 13:09 UTC, ffoucart commented
Force-push removed the two includes pointed out as unnecessary by Nils Vu.

2023-06-27 17:16 UTC, nilsvu approved these changes

2023-06-27 17:17 UTC, merged