Gab bulged cube fixes
sxs-collaboration/spectre pull request #513
Opened 2018-02-06 23:25 UTC by gsb76

## Proposed changes

Add ASSERTs to RootFinding to make sure the tolerance is set in the appropriate range.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-02-06 23:28 UTC, nilsdeppe requested changes

2018-02-06 23:28 UTC, nilsdeppe commented on src/NumericalAlgorithms/RootFinding/RootFinder.hpp
> +  ASSERT(absolute_tolerance > std::numeric_limits<double>::epsilon(),
remove absolute error check

2018-02-06 23:28 UTC, nilsdeppe commented on src/NumericalAlgorithms/RootFinding/RootFinder.hpp
> +  ASSERT(relative_tolerance > std::numeric_limits<double>::epsilon(),
add to double version

2018-02-06 23:40 UTC, nilsdeppe approved these changes

2018-02-06 23:41 UTC, wthrowe submitted a review, later dismissed

2018-02-07 00:58 UTC, nilsdeppe commented
That's a quarter :P

2018-02-07 00:59 UTC, nilsdeppe requested changes

2018-02-07 00:59 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/BulgedCube.cpp
> +                              10 * std::numeric_limits<double>::epsilon(),
10 -> 10.0

2018-02-07 00:59 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/RootFinding/Test_OneDRootFinder.cpp
> +  const double rel_tol = 1e-15;
Gabe, plz....

2018-02-07 00:59 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/RootFinding/Test_OneDRootFinder.cpp
> +  const double rel_tol = 1e-16;
Change this to 0.5 * epsilon

2018-02-07 00:59 UTC, nilsdeppe commented on tests/Unit/NumericalAlgorithms/RootFinding/Test_OneDRootFinder.cpp
> +  const double rel_tol = 1e-15;
Change this to 0.5 * epsilon

2018-02-07 19:03 UTC, wthrowe approved these changes

2018-02-07 20:03 UTC, nilsdeppe approved these changes

2018-02-07 20:31 UTC, merged