Add size StateHistory
sxs-collaboration/spectre pull request #5141
Opened 2023-07-05 20:50 UTC by knelli2

## Proposed changes

This is useful for repopulating the Averager with previous control errors when a discontinuous change has occurred.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-07-07 20:05 UTC, wthrowe requested changes

2023-07-07 20:05 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Size/StateHistory.hpp
> +   * want to keep the most recent entry, which is at the "back")
How does returning a copy help with that?  If the caller wants a version to modify they can copy from a reference.

If you do keep the behavior, this seems a bit long and detailed for a "brief".

2023-07-07 20:05 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Size/StateHistory.cpp
> +    stored_control_errors_[current_state->number()];
Just `state.number()`.  After that this lambda is only one line, so you can just inline it below.

2023-07-07 20:05 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Size/StateHistory.cpp
> +    std::unique_ptr<State> current_state = std::make_unique<StateType>();
As above, just use `state` instead of doing an extra allocation.

2023-07-07 20:05 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Size/StateHistory.cpp
> +        .emplace_back(std::make_pair(time, control_error));
I think `make_pair` is unnecessary, and it undoes the advantage of `emplace_back` over `push_back`.

2023-07-07 20:05 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Size/StateHistory.cpp
> +    stored_control_errors_.at(state_number)
[optional] Store a reference to `stored_control_errors_.at(state_number)` so you don't do the map lookup four times.

2023-07-07 20:05 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Size/StateHistory.cpp
> +    size_t state_number) const {
`const` argument.

2023-07-07 20:05 UTC, wthrowe commented on tests/Unit/ControlSystem/ControlErrors/Test_StateHistory.cpp
> +  std::iota(times.begin(), times.end(), 0.0);
This vector seems to be a very complicated way to write `static_cast<double>`.  Is there some reason to have it?

2023-07-09 17:13 UTC, wthrowe approved these changes
Squash.

2023-07-10 18:47 UTC, knelli2 commented
@wthrowe Squashed and rebased.

2023-07-11 20:32 UTC, wthrowe approved these changes

2023-07-11 20:32 UTC, merged