Fix bug in computation of zero crossing predictor
sxs-collaboration/spectre pull request #5142
Opened 2023-07-05 21:13 UTC by knelli2

## Proposed changes

Zero was used as a sentinel value in too many places and sometimes had double meaning. This uses `std::optional`s where possible to clear things up.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-07-06 13:29 UTC, nilsdeppe submitted a review, later dismissed

2023-07-09 17:07 UTC, wthrowe requested changes

2023-07-09 17:07 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ZeroCrossingPredictor.cpp
> +      predictor.min_positive_zero_crossing_time(x_values.back()).has_value());
Update comment.

2023-07-09 17:07 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/Interpolation/Test_ZeroCrossingPredictor.cpp
> +      predictor.min_positive_zero_crossing_time(x_values.back()).has_value());
Update comment.

2023-07-10 18:48 UTC, knelli2 commented
@wthrowe Squashed and rebased

2023-07-11 20:33 UTC, wthrowe approved these changes

2023-07-12 01:23 UTC, merged