Add parameterized deleptonization, without entropy
sxs-collaboration/spectre pull request #5156
Opened 2023-07-08 00:30 UTC by pajkosmi

## Proposed changes

Allow electron fraction to evolve according to parameterized deleptonization scheme outlined in[ Liebendorfer 2005](https://iopscience.iop.org/article/10.1086/466517). 

### Upgrade instructions

This will only require changes to the CCSN yaml file under Variable fixing

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

This is the first of a few changes, as it only applies to the fixed spacetime CCSN executable.  Further changes will involve expanding to the ghgrmhd system, explicitly conserving entropy, and finally hook in to the tabulated 3D EoS call.

2023-07-09 03:59 UTC, nilsdeppe reviewed
Not a complete review but a quick glance. Overall looks good! A few suggestions

2023-07-09 03:59 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
> +  if (enable_) {
`if (LIKELY(enable)) {`

2023-07-09 03:59 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.hpp
> +// IWYU pragma: no_forward_declare EquationsOfState::EquationOfState
you can remove the `IWYU` stuff. We don't use it anymore because it was wrong as often is it was right. (IWYU==Include What You Use)

2023-07-09 03:59 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.hpp
> +  /// \brief Use an analytic expression or tabulated electron fraction vs rest
Remove or add in future PR?

2023-07-09 03:59 UTC, nilsdeppe commented on src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
> +  static constexpr bool evolve_ccsn =
Maybe name this `include_parameterized_deleptonization`? That at least makes it very clear what it does. Up to you! You could even do:
```cpp
using parameterized_deleptonization = tmpl::conditional_t<...>;
```
and then just use `parameterized_deleptonization`. That would reduce overall code length & complexity IMO

2023-07-21 13:00 UTC, nilsdeppe requested changes

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.hpp
> +  // things you want from data box I won't change
I would have a space between the above:
```cpp
// Quantities being mutated
using return_tags = ...;

// Things you want from DataBox that won't be change and are passed in as const-refs
using argument_tags = ...
```

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
> +// IWYU pragma: no_include <array>
you can just not add the `IWYU` stuff. We haven't used it in so long that if we tried, everything would need to be updated anyway

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
> +    size_t grid_index) const {
`const size_t`

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.hpp
> + * Based on Lienbendorfer (2005) spherically symmetric Boltzmann calculations,
can you add the citation into `docs/References.bib` and then use Doxygen's `\cite` command?

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
> +          (1.0 - abs(x_of_rho) +
I'm worried about the possibility of catastrophic cancellation at 1.0 and at 0.5 for `x_of_rho`. That is, if `x_of_rho` is close to these values, can it happen that the resulting accuracy of `electron_fraction_from_analytic` is limited by the cancellation errors or are other terms too dominant in that case?

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
> +  electron_fraction->get()[grid_index] += delta_ye;
I would do
```cpp
if (electron_fraction_from_analytic > electron_fraction->get()[grid_index])) {
  electron_fraction->get()[grid_index] = electron_fraction_from_analytic;
}
```
You avoid any floating point errors entering the result here

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
> +      0.5 * (electron_fraction_at_high_density_ +
[optional] You could store the averages of the high/lows as member variables to save computation during the evolution

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.hpp
> +  /// This will be added in the future.  If analytic is chosen (currently the
I think you'll be able to use `using options = tmpl::list<tmpl::list<A, B, ...>, tmpl::list<A, M>>` to switch between the two cases. We can chat about that when you add the table support

2023-07-21 13:00 UTC, nilsdeppe commented on tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
> +// IWYU pragma: no_include <array>
you can also omit the iwyu stuff here

2023-07-21 13:00 UTC, nilsdeppe commented on tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
> +  // brainstorming tests
this seems like a personal checklist that can be removed now?

2023-07-21 13:00 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.hpp
> +template <size_t Dim>
I don't see that any of the code depends on the spatial dim, only the thermodynamic dim. Can you remove this template parameter?

2023-07-21 13:00 UTC, nilsdeppe commented on tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
> +  test_variable_fixer<Dim>(variable_fixer, polytrope);
One way we sometimes structure this is:
```cpp
{
  INFO("Testing 1d/barotropic EOS");
  ...
}

{
  INFO("Testing 2d EOS");
  ...
}
```
Then you don need the `2` suffixes etc.

2023-07-21 13:00 UTC, nilsdeppe commented on tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
> +  Scalar<DataVector> expected_electron_fraction_low{electron_fraction_low};
This variable is never used. Is there another `CHECK_ITERABLE_APPROX` you meant to add?

2023-07-21 13:00 UTC, nilsdeppe commented on tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
> +  Scalar<DataVector> expected_electron_fraction{
Some potential for `const`s in these testing functions :)

2023-07-21 13:00 UTC, nilsdeppe commented on tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
> +  bool enable_param_delep = true;
`const` these, including `variable_fixer` and `polytrope`, etc.

2023-07-25 22:22 UTC, pajkosmi commented on tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
> +  Scalar<DataVector> expected_electron_fraction_low{electron_fraction_low};
Yes, I forgot to include it.

2023-07-25 23:56 UTC, pajkosmi commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
> +          (1.0 - abs(x_of_rho) +
This is a good point.  There are 2 limits in question:

1. In the limit `x_of_rho -> 1`, the expression for `electron_fraction_from_analytic -> electron_fraction_at_high_density_ + ~(0) * electron_fraction_correction_scale_`, so the `electron_fraction_at_high_density_` should dominate the contribution to calculating Ye.
2. In the limit `x_of_rho -> 1/2`, 
`electron_fraction_from_analytic -> 0.75 * electron_fraction_at_high_density_ + 0.25 * electron_fraction_at_low_density_ + ~(0.5) * electron_fraction_correction_scale_`. The cancellation error, when added to `0.5` (resulting with the `~(0.5)`), should be negligible.

2023-07-26 16:03 UTC, pajkosmi commented
@nilsdeppe your reviewer comments have been addressed.

2023-07-26 19:11 UTC, nilsdeppe reviewed
LGTM, please squash & rebase!

2023-07-26 20:28 UTC, pajkosmi commented
> LGTM, please squash & rebase!

Squashed

2023-07-26 20:28 UTC, nilsdeppe approved these changes

2023-07-27 00:01 UTC, merged