Allow periodic boundary conditions across multiple blocks
sxs-collaboration/spectre pull request #516
Opened 2018-02-07 21:05 UTC by gsb76

## Proposed changes

Allows the user to identify the face of one block with the face of another block in setting up
periodic boundary conditions.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-02-07 21:34 UTC, kidder requested changes

2018-02-07 21:34 UTC, kidder commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +  CHECK(get_output(neighbors_of_all_blocks) ==
don't check by comparing the output; compare actual Neighbors

2018-02-07 21:34 UTC, kidder commented on src/Domain/DomainHelpers.cpp
>  size_t find_block_id(
find_block_id_of_external_face

2018-02-07 21:34 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +    const std::vector<size_t>& global_corners_face,
global_corners_external_face

2018-02-07 21:34 UTC, kidder commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +  CHECK(get_output(neighbors_of_all_blocks) ==
same as above

2018-02-07 22:39 UTC, kidder requested changes

2018-02-07 22:39 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +// returns the corresponding id of the block with that face.
either remove the whole comment or `corresponding`

2018-02-07 22:39 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +  size_t id_of_found_block;
initialize to `std::numeric_limits<size_t>::max()`;

2018-02-07 22:39 UTC, kidder commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +  OrientationMap<3> aligned(mapped_directions);
default construct

2018-02-07 22:39 UTC, kidder commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +  OrientationMap<3> aligned(mapped_directions);
const

2018-02-07 22:48 UTC, kidder reviewed
squash

2018-02-08 02:41 UTC, kidder submitted a review, later dismissed

2018-02-08 02:54 UTC, nilsdeppe requested changes

2018-02-08 02:54 UTC, nilsdeppe commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +          {{Direction<3>::upper_zeta(), {0, aligned}}},
why the extra comma?

2018-02-08 02:54 UTC, nilsdeppe commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +           {Direction<3>::upper_zeta(), {0, aligned}}},
again comma

2018-02-08 02:54 UTC, nilsdeppe commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +  CHECK((neighbors_of_all_blocks)[0][Direction<3>::upper_xi()].orientation() ==
why is neighbors_of_all_blocks parenthesized?

2018-02-08 02:54 UTC, nilsdeppe commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +      (neighbors_of_all_blocks)[0][Direction<3>::lower_zeta()].orientation() ==
why is neighbors_of_all_blocks parenthesized?

2018-02-08 22:06 UTC, kidder approved these changes

2018-02-08 22:07 UTC, nilsdeppe approved these changes

2018-02-09 00:29 UTC, merged