Tensor changes
sxs-collaboration/spectre pull request #517
Opened 2018-02-08 22:27 UTC by nilsdeppe

## Proposed changes

- Add C++17 implementation of std::array. Can be removed once we have C++17
- Move from TMP to constexpr metaprogramming in Tensor where possible to allow for higher rank and higher dimensional Tensor's. This is required for #495 

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-02-13 20:38 UTC, kidder requested changes

2018-02-13 20:38 UTC, kidder commented on src/Utilities/ConstantExpressions.hpp
> +SPECTRE_ALWAYS_INLINE constexpr size_t factorial(
falling_factorial with x and n linked to MathWhatever

2018-02-13 20:38 UTC, kidder commented on src/Utilities/ConstantExpressions.hpp
> +  assert(divided_out > 0);                    // NOLINT
assert n<=x

2018-02-13 20:38 UTC, kidder commented on tests/Unit/Utilities/Test_ConstantExpressions.cpp
> +static_assert(factorial(3) == 6, "");
messages

2018-02-13 20:38 UTC, kidder commented on src/DataStructures/Tensor/Structure.hpp
> +        (factorial(dim_of_index - 1) * factorial(number_of_indices_with_symm));
use falling_factorial

2018-02-13 20:38 UTC, kidder commented on tests/Unit/DataStructures/Test_Tensor.cpp
> +  CHECK(symmetric_rank3_dim4.get(0, 0, 1) == symmetric_rank3_dim4.get(0, 1, 0));
loop over all first indices

2018-02-13 20:38 UTC, kidder commented
@wthrowe can you look at this

2018-02-13 23:07 UTC, wthrowe requested changes

2018-02-13 23:07 UTC, wthrowe commented on src/Utilities/ConstantExpressions.hpp
> +SPECTRE_ALWAYS_INLINE constexpr size_t factorial(
I find the argument names completely opaque.  (I think this is what the comment above is saying, but I'm not sure.)

2018-02-13 23:07 UTC, wthrowe commented on src/DataStructures/Tensor/Structure.hpp
> +                      : max_element;
`std::max(...)`

2018-02-13 23:07 UTC, wthrowe commented on tests/Unit/DataStructures/Test_Tensor.cpp
> +  CHECK(symmetric_rank2_dim4.get(2, 3) == symmetric_rank2_dim4.get(3, 2));
Add a check somewhere that some pair of entries that should be different are different.

2018-02-14 22:09 UTC, kidder requested changes
squash

2018-02-14 22:09 UTC, kidder commented on src/DataStructures/Tensor/Structure.hpp
> +    // clang-tidy: internal STL and gls::at (don't need at in constexpr)
need at -> need it

2018-02-14 22:09 UTC, kidder commented on src/DataStructures/Tensor/Structure.hpp
> +        static_cast<size_t>(symm[i] < 0 ? -symm[i] : symm[i]),  // NOLINT
use abs

2018-02-14 22:21 UTC, kidder approved these changes

2018-02-14 22:21 UTC, wthrowe approved these changes

2018-02-14 23:47 UTC, merged