Add cartesian axes to Direction
sxs-collaboration/spectre pull request #522
Opened 2018-02-09 22:18 UTC by gsb76

## Proposed changes

Extents Direction from logical to logical and cartesian axes.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-02-09 22:34 UTC, kidder requested changes

2018-02-09 22:34 UTC, kidder commented on src/Domain/Direction.hpp
> +#include "DataStructures/Tensor/IndexType.hpp"
"Darn I don't need that"

2018-02-09 22:34 UTC, kidder commented on src/Domain/Direction.hpp
> +#include "DataStructures/Tensor/IndexType.hpp"
Below, change the constructor that takes `dimension` to `logical_dimension` and update the comment.

2018-02-09 22:34 UTC, kidder commented on src/Domain/Direction.cpp
> +  ASSERT(0 == dimension or 1 == dimension or 3 == dimension or 4 == dimension or
this constructor should only work for the logical directions

2018-02-09 22:34 UTC, kidder commented on src/Domain/Direction.cpp
> +                  << ", for Direction<1> only dim = 0, 3, 4, or 5 is allowed.");
only logical directions

2018-02-09 22:34 UTC, kidder commented on src/Domain/Direction.cpp
> +  ASSERT(dimension < 6, "dim = " << dimension
only logical directions

2018-02-09 22:34 UTC, kidder commented on tests/Unit/Domain/Test_Direction.cpp
> +  auto lower_x_1 = Direction<1>(3, Side::Lower);
you'll need to pass the enum

2018-02-09 22:34 UTC, kidder commented on tests/Unit/Domain/Test_Direction.cpp
> +  auto lower_x_1 = Direction<1>(3, Side::Lower);
const all the new stuff that is const

2018-02-09 22:34 UTC, kidder commented on tests/Unit/Domain/Test_Direction.cpp
> +  auto lower_y_1 = Direction<1>(4, Side::Lower);
4 -> enum

2018-02-09 22:34 UTC, kidder commented on tests/Unit/Domain/Test_Direction.cpp
> +  auto lower_z_1 = Direction<1>(5, Side::Lower);
5 -> enum

2018-02-12 00:06 UTC, wthrowe requested changes

2018-02-12 00:06 UTC, wthrowe commented on src/Domain/Direction.cpp
> +  axis_ = 0 == logical_dimension ? Axis::Xi : Axis ::Eta;
Formatting glitch.

2018-02-12 00:06 UTC, wthrowe commented on src/Domain/Direction.cpp
> +  ASSERT(logical_dimension < 3,
You ERROR on effectively the same condition below, so how about moving the assertion message to the ERROR (since it's more informative then the current one) and getting rid of the ASSERT.

2018-02-12 00:06 UTC, wthrowe commented on src/Domain/Direction.hpp
> +  /// The logical-coordinate names of each logical_dimension
I think this was a find-replace fail.

2018-02-12 00:06 UTC, wthrowe commented on src/Domain/Direction.hpp
> +  size_t logical_dimension() const noexcept {
I don't like this global dimension -> logical_dimension change.  The new term doesn't appear to be defined anywhere and the meaning isn't obvious.  Several functions (like this one) look like they will work on any direction, not just one of the logical ones, but were changed anyway.

2018-02-12 00:06 UTC, wthrowe commented on src/Domain/Direction.hpp
> +  static_assert(VolumeDim == 3, "VolumeDim must be 3.");
I thought you wanted all of X,Y,Z to be available in all dimensionalities.

2018-02-12 00:06 UTC, wthrowe commented on src/Domain/OrientationMap.hpp
> + * neighbor. \tparam VolumeDim the logical_dimension of the blocks.
Formatting

2018-02-12 00:06 UTC, wthrowe commented on src/Domain/OrientationMap.hpp
>      return direction.side() == Side::Upper
ASSERT you're getting a direction that won't segfault.

2018-02-12 00:06 UTC, wthrowe commented on tests/Unit/Domain/DomainTestHelpers.cpp
> +// Iterates over the logical corners of a VolumeDim-logical_dimensional cube.
More find-replaces that don't make sense.

2018-02-12 00:51 UTC, kidder commented
I think we should discuss this tomorrow.  The more I think about these changes to Direction, the less I like them.  I think we are making this class too complicated for little gain.

2018-02-16 19:13 UTC, kidder commented
In the end, we decided this was the wrong way to go

2018-02-16 19:13 UTC, closed without merging