Add dirichlet boundary condition for CSW
sxs-collaboration/spectre pull request #5243
Opened 2023-07-26 14:08 UTC by guilara

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-08-01 21:02 UTC, nilsdeppe requested changes
LGTM, please squash the minor suggestions immediately

2023-08-01 21:02 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/BoundaryConditions/AnalyticConstant.cpp
> +AnalyticConstant<Dim>::AnalyticConstant(const double amplitude) {
You should prefer list initialization whenever possible:
```cpp
AnalyticConstant<Dim>::AnalyticConstant(const double amplitude) : amplitude_(amplitude) {}
```

2023-08-01 21:02 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/CurvedScalarWave/BoundaryConditions/Test_AnalyticConstant.cpp
> +      "  Amplitude: 0.0\n",
what about setting the Amplitude to some non-zero & non-1 number, e.g. `2.3` and then just hard-code the same number in the python file

2023-08-02 08:10 UTC, guilara commented
@nilsdeppe Thanks for the review. I've implemented the suggestions and rebased

2023-08-02 12:09 UTC, nilsdeppe approved these changes

2023-08-02 12:10 UTC, merged