Add ScalarTensor initial data for Kerr plus scalar wave
sxs-collaboration/spectre pull request #5257
Opened 2023-07-28 14:53 UTC by guilara

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-08-01 20:55 UTC, nilsdeppe requested changes
LGTM! A few minor suggestions. You can squash any fixes in immediately :)

2023-08-01 20:55 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/GhScalarTensor/Factory.hpp
> +namespace gh::AnalyticData {
I would flip the namespaces, `gh::ScalarTensor::AnalyticData`. Probably need:
```cpp
/// ScalarTensor solutions wrapped for GH
namespace gh::ScalarTensor::AnalyticData {
``` 
I'm not sure why GRMHD is done this way, that needs to get fixed but not your fault :) (looks like it's my fault, actually :( sigh...)

2023-08-01 20:55 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/ScalarTensor/KerrSphericalHarmonic.cpp
> +// IWYU pragma:  no_include "DataStructures/Tensor/TypeAliases.hpp"
[optional] We stopped using IWYU a while back, so you can just exclude these if you want. up to you :)

2023-08-01 20:55 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/ScalarTensor/KerrSphericalHarmonic.cpp
> +    double mass, const std::array<double, 3>& dimensionless_spin,
`const double` x 4 & 1 `const std::pair`

2023-08-01 20:55 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/ScalarTensor/KerrSphericalHarmonic.cpp
> +  get(pi) = exp(-get(pi) * get(pi) / width_sq_);
[optional] `get(pi) * get(pi)` -> `square(get(pi))`

2023-08-01 20:55 UTC, nilsdeppe commented on src/PointwiseFunctions/AnalyticData/ScalarTensor/KerrSphericalHarmonic.cpp
> +  get(pi) *= real(spherical_harmonic.evaluate(theta, phi, sin(theta / 2.),
`theta / 2.` -> `0.5 * theta` Division is ~ 25x slower than multiplication, and doing scalar math to the farthest left allows Blaze to do some optimizations (not always and I think not here, but just a good habit)

2023-08-01 20:55 UTC, nilsdeppe commented on tests/Unit/PointwiseFunctions/AnalyticData/ScalarTensor/Test_KerrSphericalHarmonic.cpp
> +#include "Parallel/Printf.hpp"
remove

2023-08-02 09:36 UTC, guilara commented
@nilsdeppe thanks for the review. I've implemented all the suggestions and improved a bit the doc

2023-08-02 12:12 UTC, nilsdeppe approved these changes

2023-08-02 12:29 UTC, merged