Evaluate background metric variables on FD grids
sxs-collaboration/spectre pull request #5259
Opened 2023-07-29 00:40 UTC by yoonso0-0

## Proposed changes

Add a new mutator for initializing and updating background metric variables on cell-centered and face-centered FD grids. This is a follow-up work of #5028.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-08-07 20:21 UTC, wthrowe requested changes

2023-08-07 20:21 UTC, wthrowe commented on tests/Unit/Evolution/DgSubcell/Test_BackgroundGrVars.cpp
> +template <bool mesh_is_moving>
`MeshIsMoving`

2023-08-07 20:21 UTC, wthrowe commented on tests/Unit/Evolution/DgSubcell/Test_BackgroundGrVars.cpp
> +          bool compute_only_on_rollback>
Camel-case all of these.

2023-08-07 20:21 UTC, wthrowe commented on tests/Unit/Evolution/DgSubcell/Test_BackgroundGrVars.cpp
> +template <bool test_moving_mesh, bool test_runtime_initial_data>
Camel-case again.

2023-08-07 23:16 UTC, yoonso0-0 commented
Pushed the fixup. Also pushed another commit making same changes to the DG code.

2023-08-08 17:16 UTC, wthrowe commented
Thanks for fixing that one too.  Go ahead and squash.

2023-08-10 21:59 UTC, wthrowe approved these changes

2023-08-10 21:59 UTC, merged