Add initialization action ScalarTensor
sxs-collaboration/spectre pull request #5265
Opened 2023-07-31 15:16 UTC by guilara

## Proposed changes

Add initialization of compute tags required for the evolution. This is done in exactly the same way as for the Generalized Harmonic system, but we add extra spacetime tags needed for CurvedScalarWave.

Note: 
- For now, we add the trace of the extrinsic curvature and trace of christoffel as compute tags. In a future PR the idea would be to replace these for their computation directly in `ScalarTensor::TimeDerivative::apply`. (In testing, the current implementation did not seem significantly slower than just GH.)

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-07-31 15:42 UTC, wthrowe commented
> * For now, we add the trace of the extrinsic curvature and trace of christoffel as compute tags. In a future PR the idea would be to replace these for their computation directly in `ScalarTensor::TimeDerivative::apply`. (In testing, the current implementation did not seem significantly slower than just GH.)

Just to clarify, the issue with compute tags isn't speed, it's memory use.

2023-08-02 08:16 UTC, guilara commented
> > * For now, we add the trace of the extrinsic curvature and trace of christoffel as compute tags. In a future PR the idea would be to replace these for their computation directly in `ScalarTensor::TimeDerivative::apply`. (In testing, the current implementation did not seem significantly slower than just GH.)
> 
> Just to clarify, the issue with compute tags isn't speed, it's memory use.

Oh, I see. For my isolated BH tests the memory seemed manageable. But I'm not sure about more challenging sims.

2023-08-02 13:31 UTC, nilsdeppe commented
Yea, the memory issue is sort of a problem of scale. 1 or 2 tensors isn't a big deal, but all the GH temporaries are ~250 tensor components, and that adds a lot of memory usage. When you include derivatives, etc. you get closer to 400 components, which then really does use a lot more memory. In terms of speed, I wouldn't expect there to be even a measurable difference between compute tag vs. in RHS.

2023-08-02 17:08 UTC, nilsdeppe requested changes
You can squash immediately

2023-08-02 17:08 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarTensor/Initialize.hpp
> +struct InitializeScalarTensorAnd3Plus1Variables {
Would you mind adding some doxygen documentation?

I think you can also turn this into a mutator instead of an action. Then you can use `Initialization::Actions::InitializeItems` in `ParallelAlgorithms/Actions/InitializeItems.hpp` It looks like examples are `evolution::dg::Initialization::Domain` `Initialization::TimeStepperHistory` and `Initialization::TimeStepping`. This should make adding a test quite easy, while you can then just using `db::tag_is_retrievable_v<Tag, db::DataBox<Tags>>` to verify the correct tags are added.

2023-08-02 17:08 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarTensor/Initialize.hpp
> +  static constexpr size_t Dim = 3_st;
`Dim` -> `dim` (variable not template parameter)

2023-08-07 09:50 UTC, guilara commented on src/Evolution/Systems/ScalarTensor/Initialize.hpp
> +struct InitializeScalarTensorAnd3Plus1Variables {
Thanks for the suggestion. I was trying to implement this actually, but maybe a cleaner way is one @nikwit suggested to me of just adding these tags directly in the executable with `Initialization::Actions::AddComputeTags`. So maybe in this file what we could write is just the list of tags to add. What do you think?

2023-08-07 14:22 UTC, nilsdeppe commented on src/Evolution/Systems/ScalarTensor/Initialize.hpp
> +struct InitializeScalarTensorAnd3Plus1Variables {
That sounds good to me :)

2023-08-07 18:38 UTC, nilsdeppe reviewed
I like this list approach. Do you just want to squash the two commits together? I think this is good to go then.

2023-08-07 18:39 UTC, guilara commented on src/Evolution/Systems/ScalarTensor/Initialize.hpp
> +struct InitializeScalarTensorAnd3Plus1Variables {
Good. Then I have changed the content of this PR to just include the list of compute tags to add.

2023-08-07 18:40 UTC, nilsdeppe approved these changes
🎉

2023-08-08 10:18 UTC, guilara commented
Thanks. It seems some tests timed out here

2023-08-08 13:39 UTC, merged