Make DG-FD executables to start on FD
sxs-collaboration/spectre pull request #5283
Opened 2023-08-02 00:35 UTC by nilsdeppe

## Proposed changes

- Couple minor cleanup things (happy to factor out if people want)
- The majority of it is the new actions that do the FD grid initialization. This does communication to set up RDMP and TCI decisions correctly.
- Removes & renames some code that is no longer needed or should be named differently.
- This will allow BNS mergers in develop from SpEC initial data.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-08-02 20:16 UTC, kidder requested changes
you can squash

2023-08-02 20:16 UTC, kidder commented on src/Evolution/DgSubcell/Actions/Initialize.hpp
> + * or because it or one of its neighbors has been mark as DG-only.
mark -> marked

2023-08-02 22:31 UTC, nilsdeppe commented
Done and rebased on develop. Thanks for the review!

2023-08-03 00:13 UTC, kidder approved these changes

2023-08-03 04:05 UTC, merged