Upgrade Catch2 to version 3+
sxs-collaboration/spectre pull request #5286
Opened 2023-08-02 08:17 UTC by nilsvu

## Proposed changes

Preparation to replace `RunTests` with one test exec for each library.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-08-02 15:45 UTC, wthrowe requested changes
Haven't tested it, but looks reasonable.

2023-08-02 15:45 UTC, wthrowe commented on docs/DevGuide/BuildSystem.md
> +existing one for `Brigand` if you're adding a header-only
"after the existing one"

2023-08-02 15:45 UTC, wthrowe commented on tests/Unit/Parallel/Test_AlgorithmCore.cpp
> -#define CATCH_CONFIG_RUNNER
Remove dangling comment here and in several other places.

2023-08-02 18:09 UTC, kidder submitted a review, later dismissed
When building with on my desktop with clang16 and `BUILD_SHARED_LIBS=ON` I am getting multiple undefined `Catch::Approx` symbols in tests that have their own executable (e.g. Test_AlgorithmParallel.)  RunTests builds fine.

2023-08-02 18:10 UTC, nilsvu commented
Thanks for checking @kidder! I'll take a look at those.

2023-08-02 18:10 UTC, nilsvu commented
This is ARM macOS?

2023-08-02 18:12 UTC, kidder commented
> This is ARM macOS?

No this is a linux desktop with Fedora38, catch version 3.3.2

2023-08-02 18:23 UTC, nilsvu commented
Was an easy fix. I also updated the Dockerfile but haven't built or pushed the container yet because it takes so long to build on my ARM mac (it has to emulate x86).

2023-08-02 19:21 UTC, kidder commented
> Was an easy fix. I also updated the Dockerfile but haven't built or pushed the container yet because it takes so long to build on my ARM mac (it has to emulate x86).

you need a similar fix in `tests/Unit/IO/Importers/CMakeLists.txt`

2023-08-04 03:18 UTC, kidder reviewed
LGTM

2023-08-06 19:07 UTC, nilsvu commented
Container is now pushed and fixups squashed. CI failures are timeouts.

2023-08-07 16:59 UTC, wthrowe approved these changes

2023-08-09 21:45 UTC, nilsdeppe reviewed
Seems to mostly work. I get segfaults in:
```
 627 - Unit.Evolution.Systems.GeneralizedHarmonic.BCBjorhus.Cls (Failed)
 636 - Unit.Evolution.Systems.GeneralizedHarmonic.Characteristics (Failed)
 644 - Unit.GhValenciaDivClean.BoundaryConditions.ConstraintPreservingFreeOutflow (Failed)
 647 - Unit.GhValenciaDivClean.BoundaryConditions.ProductOfConditions (Failed)
```

2023-08-09 23:19 UTC, nilsvu commented
Could you post backtraces or do you understand what's segfaulting there?

2023-08-10 00:23 UTC, nilsdeppe commented
Heh, ignore, something went weird on my machine

2023-08-10 04:14 UTC, nilsvu commented
Ok, ready to get this in? Then I can open the next PR that splits up RunTests.

2023-08-10 13:34 UTC, nilsdeppe approved these changes

2023-08-10 13:34 UTC, merged