Add MC reconstructor to ForceFree subcell
sxs-collaboration/spectre pull request #5310
Opened 2023-08-03 22:44 UTC by yoonso0-0

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-08-28 14:02 UTC, nilsdeppe requested changes
Overall LGTM, some suggestions, please squash and rebase immediately :)

2023-08-28 14:02 UTC, nilsdeppe commented on src/Evolution/Systems/ForceFree/FiniteDifference/ReconstructWork.tpp
> +  ASSERT(Mesh<3>(subcell_mesh.extents(0), subcell_mesh.basis(0),
If you rebase, there's now a `is_isotropic(mesh)` function :)

2023-08-28 14:02 UTC, nilsdeppe commented on src/Evolution/Systems/ForceFree/FiniteDifference/ReconstructWork.tpp
> +    DataVector buffer{VarTildeJ::number_of_independent_components *
Memory leak, remove this like and just do `VarTildeJ var{volume_num_pts};`

2023-08-28 14:02 UTC, nilsdeppe commented on src/Evolution/Systems/ForceFree/FiniteDifference/ReconstructWork.tpp
> +  VarTildeJ var_tilde_j{volume_num_pts};
squash into earlier commit instead

2023-08-28 14:02 UTC, nilsdeppe commented on src/Evolution/Systems/ForceFree/FiniteDifference/MonotonisedCentral.cpp
> +// FIXME : review header files
do this?

2023-08-29 16:42 UTC, yoonso0-0 commented
Squashed and rebased on develop. Thanks for the review!

2023-08-29 17:52 UTC, nilsdeppe commented
It looks like the changes didn't get pushed? It looks like this was only rebased with no fixes

2023-08-29 18:51 UTC, yoonso0-0 commented
oh no....

2023-08-29 20:26 UTC, yoonso0-0 commented
@nilsdeppe Pushed with fixes

2023-08-29 21:06 UTC, nilsdeppe approved these changes

2023-08-29 22:48 UTC, merged