Add example executable for ScalarTensor
sxs-collaboration/spectre pull request #5321
Opened 2023-08-07 13:52 UTC by guilara

## Proposed changes

Given that ScalarTensor uses the generalized harmonic system, we add an executable that closely follows the structure of that system. We include an example Input file (Kerr BH + scalar wave) to run it.

This PR needs:
- Boundary Corrections (#5220)
- Initialization (#5265)
- It will need a fix for the parsing of observables with the same name (e.g. Phi in Gh and Phi in CurvedScalarWave)

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-08-18 14:48 UTC, nilsdeppe commented
@guilara would you mind rebasing this with all the recent changes on develop, just to make sure it works?

2023-08-18 15:03 UTC, guilara commented
> @guilara would you mind rebasing this with all the recent changes on develop, just to make sure it works?

Will do

2023-08-18 15:33 UTC, guilara commented
@nilsdeppe I have rebased the code. Seems to compile and run, just changed a few includes.

2023-08-19 03:00 UTC, nilsdeppe requested changes
Looks good, some suggestions in the input file for reducing runtime and the amount of data being dumped. Please squash immediately :)

2023-08-19 03:00 UTC, nilsdeppe commented on tests/InputFiles/ScalarTensor/KerrSchildSphericalHarmonic.yaml
> +    InitialRefinement: [0, 0, 4]
Would it be reasonable to reduce this to say lev 2 to reduce test time?

2023-08-19 03:00 UTC, nilsdeppe commented on tests/InputFiles/ScalarTensor/KerrSchildSphericalHarmonic.yaml
> +          Values: [10]
Can you decrease this to 5 and still have the test be good?

2023-08-19 03:00 UTC, nilsdeppe commented on tests/InputFiles/ScalarTensor/KerrSchildSphericalHarmonic.yaml
> +          Interval: 1
Dumping every timestep seems a bit aggressive for volume data. Can this be reduced in frequency?

2023-08-19 03:00 UTC, nilsdeppe commented on tests/InputFiles/ScalarTensor/KerrSchildSphericalHarmonic.yaml
> +          FloatingPointTypes: [Double]
`Float` and above. There's rarely a reason to need to know the output to 16 digits for data visualization. This is an easy way to reduce output file size by 2

2023-08-20 16:24 UTC, nilsdeppe commented on tests/InputFiles/ScalarTensor/KerrSchildSphericalHarmonic.yaml
> +  Timeout: 8
Looks like this is still timing out, maybe bump to 20 seconds?

2023-08-21 13:18 UTC, guilara commented on tests/InputFiles/ScalarTensor/KerrSchildSphericalHarmonic.yaml
> +  Timeout: 8
I bumped to 20s, but then needed to also lower the output freq again and domain parameters.

2023-08-21 14:34 UTC, nilsdeppe approved these changes

2023-08-21 14:48 UTC, merged