Add hydro version of Kastaun Con2Prim.
sxs-collaboration/spectre pull request #5328
Opened 2023-08-08 07:26 UTC by ermost

This adds the pure hydro version (B = 0 ) of the Kastaun Con2Prim (see Appendix C of https://arxiv.org/abs/1306.4953).

This requires only one root find, and the upper bound of the root bracket directly corresponds to the maximum Lorentz factor. 

Note that this routine is algorithmically different from the MHD version of Kastaun et al. in the B=0 limit.

2023-08-08 07:27 UTC, ermost commented
I still need to update documentation and comments.

2023-08-30 16:06 UTC, kidder requested changes

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.hpp
> + * Furthermore, the algorithm iterates over \f$Z\f$, which is the Lorentz factor
Z -> z

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.hpp
> + * r = & \frac{\gamma^{kl} {\tilde S}_k {\tilde S}_l}{{\tilde D}^2} \\
r -> r^2

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.hpp
> + * density, momentum density, specific internal energy density, and magnetic
remove magnetic field

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservative.hpp
> +  //! Use Kastaun hydro inversion if B is dynamically unimportant
remove `!`

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.hpp
> +#include "Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveRecoveryData.hpp"
this can just be a forward declaration of PrimitiveRecoveryData

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
> +#include "DataStructures/Tensor/Tensor.hpp"
don't need

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
> +#include "Utilities/ErrorHandling/Error.hpp"
don't need

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
> +  double upper_bound = 1.e-8 + k / std::sqrt(1. - k * k);
comment on where 1.e-8 comes from

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
> +  // Need to limit k
Remove if this won't be used

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
> +  // Compute Lorentz factor, note that Z = lorentz * v
lower-case Z

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
> +  // Z is W * v  (Lorentz factor * velocity)
use lower-case Z in comment and variable below

2023-08-30 16:06 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/KastaunEtAlHydro.cpp
> +    // Bracket for master function, see Sec. II.F
update comment or remove

2023-08-30 16:07 UTC, kidder commented
don't worry about the clang-tidy failure, it's in boost code and we have not found a way to suppress it

2023-08-31 09:28 UTC, ermost commented
Thank you for the review, @kidder!
I pushed a fixUp commit.

2023-08-31 21:01 UTC, kidder reviewed
looks good, squash!

2023-08-31 21:56 UTC, ermost commented
Done.

2023-09-06 02:35 UTC, kidder approved these changes

2023-09-06 02:35 UTC, kidder commented
ignoring clang-tidy error in boost

2023-09-06 02:35 UTC, merged