Add some documentation about SpECTRE's use of Travis
sxs-collaboration/spectre pull request #533
Opened 2018-02-15 04:32 UTC by kidder

## Proposed changes

Add documentation about Travis

Fix #201 

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

2018-02-15 16:39 UTC, nilsdeppe commented
Here's the built documentation: http://nilsdeppe.com/spectre/pr_533/

2018-02-15 17:21 UTC, wthrowe requested changes

2018-02-15 17:21 UTC, wthrowe commented on docs/DevGuide/Travis.md
> +time you push to a branch on your fork of SpECTRE.  For pull requests,
It will?  How can I see the results?

2018-02-15 17:21 UTC, wthrowe commented on docs/DevGuide/Travis.md
> +  - A `c++` file (i.e. `*.hpp` or `*.cpp` file) contains a line over 80
This should also include `*.tpp`, and I will submit a pull request momentarily to make that actually true.

2018-02-16 01:04 UTC, kidder commented on docs/DevGuide/Travis.md
> +you can see view the Travis CI build by clicking on `Details` next to
see or view

2018-02-16 01:04 UTC, kidder commented on docs/DevGuide/Travis.md
> +time you push to a branch on your fork of SpECTRE.  For pull requests,
Apparently I set it up this way; I will document how (if anyone can) or remove the comment (if it required administrator priv)

2018-02-16 01:04 UTC, kidder commented on docs/DevGuide/Travis.md
> +credentials in order to cancel your builds and enable additional
remove and enable... (requires super admin privs)

2018-02-16 01:04 UTC, kidder commented on docs/DevGuide/Travis.md
> +green check mark if it passes, or a red `X` if it has failed.
or a yellow binary if the build is in progress

2018-02-19 20:14 UTC, kidder commented on docs/DevGuide/Travis.md
> +  in doxygen)
capitalize

2018-02-19 20:14 UTC, kidder commented on docs/DevGuide/Travis.md
> +* The `gcc Debug` build will fail if there are `doxygen` warnings.
capitalize

2018-02-19 20:14 UTC, kidder commented on docs/DevGuide/Travis.md
> +* Travis caches some things between builds.  Occasionally this may
only available to admins

2018-02-19 20:14 UTC, kidder commented on docs/DevGuide/Travis.md
> +Travis (e.g. it times out).  Clicking on the icon on the far right of
circular arrow icon

2018-02-19 20:14 UTC, kidder commented on docs/DevGuide/Travis.md
> +time you push to a branch on your fork of SpECTRE.  For pull requests,
Go to Travis, click on your name in the upper right corner, and then towards the bottom, enable testing on your fork of spectre

2018-02-20 00:01 UTC, nilsdeppe approved these changes

2018-02-20 00:01 UTC, wthrowe approved these changes

2018-02-20 01:08 UTC, merged