Add quick exit from cons 2 prim routine
sxs-collaboration/spectre pull request #5347
Opened 2023-08-14 13:24 UTC by ffoucart

## Proposed changes

Add a new set of input files options, passed to PrimitiveFromConservative.
Currently, only use these options to skip Con2Prim recovery in the atmosphere (inverting low-density points that are later overwritten by FixAtmosphere can be costly)

### Upgrade instructions

Input files for all executables based of ValenciaDivClean and GhValenciaDivClean need to provide the new option.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2023-08-14 17:47 UTC, ffoucart commented
(I'm off traveling this week, so if this needs a more in depth discussion, let's get back to it next week))

2023-08-14 18:49 UTC, nilsdeppe requested changes
LGTM, couple small suggestions. You can squash immediately

2023-08-14 18:49 UTC, nilsdeppe commented on tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
> +  CutoffDForInversion: 2.0e-12
Should these match something in `VariableFixing`? E.g. `CutoffD` and `DensityCutoff`? If so, maybe use the `*density_cutoff` and similarly define a `&cutoff_d` and `*density_cutoff` to guarantee things stay in sync? Same of the other input files.

2023-08-14 18:49 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PrimitiveFromConservativeOptions.hpp
> +class PrimitiveFromConservativeOptions {
Can you add short doxygen comment just so it shows up in the dox?

2023-08-22 13:00 UTC, ffoucart commented on tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
> +  CutoffDForInversion: 2.0e-12
Not entirely clear at this point, but I tied the default to similar options in FixConservatives for now, and let the user choose to be more aggressive in the use of this option if needed.

2023-08-22 15:00 UTC, nilsdeppe commented on tests/InputFiles/GrMhd/GhValenciaDivClean/BinaryNeutronStar.yaml
> +  CutoffDForInversion: 2.0e-12
Sounds good, thank you!

2023-08-22 15:01 UTC, nilsdeppe approved these changes

2023-08-22 15:01 UTC, merged