Print more information when an exception is caught by DistributedObject
sxs-collaboration/spectre pull request #5353
Opened 2023-08-15 21:44 UTC by kidder

## Proposed changes

Print the component, array index, phase, and algorithm step in addition to the exception message and type.

Fix #5101 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-08-15 22:02 UTC, nilsdeppe submitted a review, later dismissed

2023-08-15 22:44 UTC, knelli2 requested changes

2023-08-15 22:44 UTC, knelli2 commented on src/Parallel/DistributedObject.hpp
> +                   << pretty_type::get_name<parallel_component>() << "\n"
`pretty_type::name<parallel_component>()` or else all control system (or interpolation target) singletons will have the same name.

2023-08-16 14:37 UTC, kidder commented on src/Parallel/DistributedObject.hpp
> +                   << pretty_type::get_name<parallel_component>() << "\n"
that's not true.  this prints out the full type name including all template arguments...
but `name` is less verbose so I'll make the change since one of the template arguments for DgElementArray is the PDAL

2023-08-16 17:49 UTC, knelli2 approved these changes

2023-08-17 02:58 UTC, merged