Add p-refinement criterion based on constraints
sxs-collaboration/spectre pull request #5375
Opened 2023-08-23 02:36 UTC by nilsvu

## Proposed changes

Based on Sec. 6.1.4 in Szilagy 2014. When testing this in the wild we may want to add some h-refinement criterion based on constraints, and try to eliminate the coarsening factor.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-08-31 03:28 UTC, nilsdeppe requested changes
sorry for being a bit brief, wanted to get this to you finally...

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.hpp
> +template <size_t Dim, typename TensorTags>
Are these going to be evaluated using the `ObservationBox`? I don't want to store the 2 & 4-index constraints in the DataBox. We don't have enough RAM for that.

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.hpp
> +  using compute_tags_for_observation_box = tmpl::list<>;
Set to `TensorTags`

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.hpp
> +  std::array<Flag, Dim> operator()(const db::DataBox<DbTagsList>& box,
`DataBox` -> `ObservationBox`

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.hpp
> +    if (alg::find(vars_to_monitor_, tag_name) == vars_to_monitor_.end()) {
`if (not alg::found)`

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.hpp
> +  DataVector buffer{};
set the size correctly here so it doesn't get resized later

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.hpp
> +      domain::Tags::Jacobian<Dim, Frame::ElementLogical, Frame::Inertial>>(box);
Please make this work with FD by using the `Events` version of this tag

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.cpp
> +                                   sqrt(logical_constraints.begin()->size());
precompute the sqrt part (sqrt is super expensive) outside of loop

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.cpp
> +      *buffer += square(jacobian.get(i, k));
Can you precompute this for _all_ constraints once?

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.hpp
> + * index must be a lower spatial index that originates from a derivative.
add a static_assert to enforce?

2023-08-31 03:28 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Criteria/Constraints.hpp
> + * \Epsilon_\hat{k} = \frac{1}{N_\hat{k}} \sqrt{\sum_{a\ldots} \left(\sum_{i}
&= 2x to align equations

2023-09-01 18:35 UTC, nilsvu commented
Fixup pushed

2023-09-01 21:42 UTC, nilsdeppe reviewed
LGTM, please squash!

2023-09-01 23:40 UTC, nilsvu commented
Done

2023-09-02 00:03 UTC, nilsdeppe approved these changes

2023-09-05 17:43 UTC, nilsvu commented
@kidder do you want to take a look at this before we merge it?

2023-09-05 20:22 UTC, merged