Add Frustum CoordinateMap
sxs-collaboration/spectre pull request #544
Opened 2018-02-19 21:04 UTC by gsb76

## Proposed changes

The map obtained by linearly interpolating between rectangles that are parallel to each other. The rectangles are confined to lie perpendicular to one of the three Cartesian axes.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-02-19 22:52 UTC, nilsdeppe requested changes

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +/// Defines the class Frustum.
remove

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +/// \ingroup CoordinateMaps
CoordinateMapsGroup

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +/// `face_vertices` values are determined cyclically. For example, for a
Explain all three axes so it's clear what you mean by cyclically

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +/// `face_vertices` values are determined cyclically. For example, for a
Test along all axes and directions and stuff and then explain cyclicality when the direction is -y

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +/// the corresponding value for `face_vertices` is `{{{{2.0,3.0}},{{3.0,5.0}},
SPAAAAACCCCEEEEEEEE

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +  explicit Frustum(std::array<std::array<double, 2>, 4> face_vertices,
derp (not explicit)

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +      const std::array<T, 3>& xi) const noexcept;
RIP (target_coords and source_coords)

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +  double x1_{};
Halp.... What? "I literally can't even"

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +#include <pup.h>
forward declare PUP::er

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +#include "DataStructures/Tensor/Tensor.hpp"
type aliases instead

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +#include "DataStructures/MakeWithValue.hpp"
Tensor.hpp
pup.h

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +#include "Domain/Direction.hpp"
TypeTraits.hpp

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +Frustum::Frustum(const std::array<std::array<double, 2>, 4> face_vertices,
face_vertices to two arrays of arrays, one for upper and one for lower faces orthogonal to the direction of the frustum

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +    : x1_(face_vertices[0][0]),
instead of all these things, have two arrays of arrays and just have the constructor eat the inputs

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +                                            std::move(-physical_y),
std::move(physical_y *= -1.0)
Apply liberally throughout

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  if (direction_of_frustum_.axis() == Direction<3>::Axis::Zeta) {
See if you can factor all these conditionals into a function and then use it in Wedge too

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  switch (direction_of_frustum_.axis()) {
See how BulgedCube is implemented with a lambda and use that approach when you factor things to get rid of the extra copies

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  dx_dxi = 0.25 * ((-x1_ + x2_) * (1.0 - zeta) + (-x3_ + x4_) * (1.0 + zeta));
use other 8 variables if possible and store them

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  if (direction_of_frustum_ == Direction<3>::lower_zeta()) {
factor these conditionals too if possible

2018-02-19 22:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +template std::array<double, 3> Frustum::operator()(
use GENERATE_INSTANTIATIONS

2018-02-19 22:52 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +//#include "Domain/CoordinateMaps/Wedge3D.hpp"
RIP

2018-02-19 22:52 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +  for (const auto& direction : Direction<3>::all_directions()) {
See if you can factor this into a function that can be used in other tests
Loop over vector of test points
You could pass random test numbers to the factored out function, then remove the last test in this file

2018-02-19 22:52 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +    test_jacobian(map, test_point1);
Also test this stuff with the serialize_deserialize map

2018-02-19 22:52 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +  const std::array<std::array<double, 2>, 4> face_vertices{
factor all the below code so you don't have LOTS of copies of it

2018-02-19 22:52 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +  // Test that the logical axes point along the expected directions in
"This test tests"

2018-03-16 21:05 UTC, nilsdeppe requested changes

2018-03-16 21:05 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +
squash last commit that changes Wedge3D into this one

2018-03-16 21:05 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +    if (index_ % two_to_the(VolumeDim) == 0) {
use `vci_()` to check this condition

Set a bool once you're on the last permutation of `dims_`. Use said bool in `operator bool()`

2018-03-16 21:05 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +// Iterates over all possible OrientationMaps.
Write Doxygen comment for this similar to the ones in the above code (group)

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +namespace PUP {
`/// \cond`

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +/// `upper_bound` values correspond to the extents of the frustum along this
use a different word for `extents`

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +/// {{1.0,1.5}}, {{2.0,3.0}}}}`. The user may reorient the frustum by passing
don't use (2, 3) twice. An image would probably help a lot :)

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +  Tensor<std::decay_t<tt::remove_reference_wrapper_t<T>>,
make it not long (Hint: Johnny has 3 apples)

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +  double lower_x_lower_base_{};
line to separate from friend function

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  sum_midpoint_x_ = 0.5 * (lower_x_upper_base_ + upper_x_upper_base_ +
use `const double& lower_... = face_vertices[?][?];`

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +  double upper_y_lower_base_{};
You will be removing all the variables before OrientationMap

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.hpp
> +  double sum_midpoint_x_{};
NaN these bad boys

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +                 const OrientationMap<3> orientation_of_frustum) noexcept
No `const`!

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +      lower_bound_(std::move(lower_bound)),
We'll survive not `std::move` the doubles

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +Frustum::Frustum(const std::array<std::array<double, 2>, 4> face_vertices,
const std::array&

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  dif_midpoint_x_ = 0.5 * (lower_x_upper_base_ + upper_x_upper_base_ -
check rectangles and frustum are not insane

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  const std::array<ReturnType, 3> physical_coords =
non-const, name it `coords`

```
/// discrete_rotation will return physical coords
std::array<ReturnType, 3> coords = discrete_rotation(...);
```

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  const ReturnType physical_x = physical_coords[0];
remove next 3

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  ReturnType zeta = (physical_z - midpoint_z_) / half_length_z_;
```
// We want to not do an extra allocation, so we reuse coords. This will now be {xi, eta, zeta}
coords[2] = (coords[2] - midpoint_z_) / half_length_z_;
coords[0] = (2.0 * coords[0] - sum_midpoint_x_ - dif_midpoint_x_ * coords[2]) /
                   (sum_half_length_x_ + dif_half_length_x_ * coords[2]);
coords[1] = (2.0 * coords[1] - sum_midpoint_y_ - dif_midpoint_y_ * coords[2]) /
                  (sum_half_length_y_ + dif_half_length_y_ * coords[2]);
return coords;
```

2018-03-16 21:05 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  auto jacobian_matrix = make_with_value<
make it shorter

2018-03-16 21:05 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +std::array<OrientationMap<3>, 6> all_wedge_directions() {
Have 0 or 1 of these functions in the code

2018-03-16 21:05 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +  test_frustum_all_directions();
just put the function body in here if it's only used once

2018-03-16 21:05 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +  const std::array<double, 3> lowest_physical_corner_upper_zeta{
append `lowest_physical_corner_in_map_upper_zeta`

2018-03-16 21:05 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Frustum.cpp
> +      {{{-1.0, -1.0}}, {{1.0, 1.0}}, {{-2.0, -2.0}}, {{2.0, 2.0}}}};
"That's not great" don't have +/-1 as face vertices

2018-03-17 03:09 UTC, gsb76 commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  ReturnType zeta = (physical_z - midpoint_z_) / half_length_z_;
why not return stdmove of coords at the end?

2018-03-17 03:14 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  ReturnType zeta = (physical_z - midpoint_z_) / half_length_z_;
return value optimization is not possible when you call `std::move`

2018-03-22 20:36 UTC, nilsdeppe requested changes

2018-03-22 20:36 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  std::uniform_real_distribution<> real_dis(-1, 1);
1.0

2018-03-22 20:36 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +                                                          {{1.0, 1.0, 1.0}},
all corners

2018-03-22 20:36 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  const auto map2 = serialize_and_deserialize(map);
`CHECK(map2 == map);`

2018-03-22 20:36 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  bool next_permutation_ = true;
name something other than `next_permutation_`, eg `not_done_` or `not_at_end_`

2018-03-22 20:36 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
>    size_t index_ = 0;
remove

2018-03-22 20:36 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +    if (!vci_) {
`not vci_`

2018-03-22 20:36 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  auto jacobian_matrix = make_with_value<Tensor<
Johnny has 3(!!!!) apples Gabe. 3!

2018-03-22 20:36 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  half_length_z_ = 0.5 * (upper_bound - lower_bound);
use `ASSERT` to check that Johnny has 3 apples, no more, no fewer.

2018-03-23 20:16 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Frustum.cpp
> +  ASSERT(upper_x_lower_base > lower_x_lower_base,
add tests for the asserts

2018-03-23 20:47 UTC, nilsdeppe submitted a review, later dismissed

2018-03-24 00:33 UTC, nilsdeppe commented
tests are failing

2018-03-24 15:12 UTC, nilsdeppe approved these changes
@kidder this is ready to be merged

2018-03-24 15:18 UTC, kidder approved these changes

2018-03-24 15:18 UTC, merged