Ignore length of variables in clang-tidy
sxs-collaboration/spectre pull request #5454
Opened 2023-09-14 23:03 UTC by knelli2

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-09-14 23:06 UTC, kidder approved these changes, later dismissed

2023-09-15 01:11 UTC, wthrowe requested changes

2023-09-15 01:11 UTC, wthrowe commented on .clang-tidy
> +# We have lots of "x", "p", & "os" variable names
According to the comment at the top of this file, this line has to end with a comma.

2023-09-15 03:21 UTC, wthrowe submitted a review, later dismissed

2023-09-15 19:05 UTC, nilsvu approved these changes

2023-09-15 19:20 UTC, wthrowe approved these changes

2023-09-15 23:17 UTC, kidder commented
Ignoring CCE timeouts and failure to build EvolveGhBinaryBlackHole

2023-09-15 23:17 UTC, merged