Add transport velocity tag to namespace Hydro and insert Temperature tag to RotatingStar
sxs-collaboration/spectre pull request #5464
Opened 2023-09-15 23:30 UTC by ncorsobh

## Proposed changes

Adds a transport velocity tag into namespace `Hydro`, and implements this as an alternative velocity for use in the first time derivative of the quadrupole moment.

In addition, previous work on the `RotatingStar` analytic solution had caused its build to crash since it expected to record a temperature tag, but its full implementation was not provided. The second commit in this PR is geared toward filling in the gap there by finishing the implementation.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`. **(I am having issues with `make doc` currently that are not limited to my branch. If someone else would like to test it to confirm on my behalf that the documentation has rendered properly, that would be helpful.)**
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

If having two separate commits is undesirable I can combine them, but I figured their objectives were distinct enough to warrant their separation.

@ermost I believe the issue that I'm fixing with `RotatingStar` is somewhat related to #5229 (`RotatingStar` is not one of the test solutions, so it wouldn't have been caught in unit tests), so if you would be willing to confirm that I properly implemented the changes you were adding there, that would be very helpful!

2023-09-16 10:23 UTC, ermost commented
Hi @ncorsobh,

thanks a lot for catching this, the temperature routine looks great to me!

Regarding the transport velocity, many papers define this as u^i /u^0 = alpha * v^i -beta^i (test particles on top of the fluid move with dx^i / dt = u^i /u^0 ), whereas you seem to need v^i/alpha -beta. 

Could you maybe add a comment on the different definition when defining the tag ?

2023-09-21 20:52 UTC, ncorsobh commented
Hey @ermost, thanks for your feedback! The transport velocity issue was a matter of me not properly checking my sources. The implementation is now fixed to the proper definition.

2023-09-21 21:08 UTC, ermost commented
Sounds great! Thanks for looking into and fixing it!

2023-09-27 13:42 UTC, nilsdeppe requested changes

2023-09-27 13:42 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/TransportVelocity.hpp
> +struct TransportVelocity : db::SimpleTag {
I would park the simple tag (for better or worse) in `Hydro/Tags.hpp`. We are going to do a big refactor that changes things to `Hydro/Tags/TransportVelocity.hpp`, but that's for the future.

2023-09-27 13:42 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/TransportVelocity.hpp
> +struct TransportVelocityCompute
Move to `Hydro/TransportVelocity.hpp`. This doesn't depend on the GRMHD variables, unlike the quadrupole which used `TildeD`

2023-09-27 13:42 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/QuadrupoleFormula.hpp
> +    return "QuadrupoleMomentDerivative" + db::tag_name<VelocityTag>();
I find `QuadrupoleMomentDerivative(" + db::tag_name<VelocityTag>() + ")";` easier to read in input files. What do you think?

2023-09-27 13:42 UTC, nilsdeppe commented on src/Evolution/Executables/GrMhd/GhValenciaDivClean/GhValenciaDivCleanBase.hpp
>  #include "Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/SetInitialRdmpData.hpp"
This commit should be 

1. Add Transport velocity function & tag (no executable changes, etc.)
2. Change quadrupole moment and executables

2023-09-28 16:15 UTC, nilsdeppe approved these changes, later dismissed
In a followup PR can you replace the local `TransportVelocity` tag used in the hydro RHS with this one?

2023-10-02 13:58 UTC, nilsdeppe approved these changes

2023-10-02 13:58 UTC, merged