Remove special-casing of Variables from DataBox
sxs-collaboration/spectre pull request #547
Opened 2018-02-20 21:10 UTC by wthrowe

### Types of changes:

- [ ] Bugfix
- [X] New feature

### Component:

- [X] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-02-20 22:45 UTC, kidder requested changes

2018-02-20 22:45 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +/// Struct that can be specialized to allow BataBox items to have
DataBox

2018-02-20 22:45 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +/// * A function evaluating a sub-item of a ComputeItem:
compute item

2018-02-20 22:45 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +/// * A function to initialize a sub-item of a non-ComputeItem:
simple item

2018-02-20 22:45 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +/// * A function to initialize a sub-item of a non-ComputeItem:
A static member function

2018-02-20 22:45 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +/// * A function evaluating a sub-item of a ComputeItem:
A static member function

2018-02-20 22:45 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +// the items and all their subitems
all of

2018-02-20 22:45 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +  // being mutated and if so add it the parent to the list of tags
add the parent

2018-02-21 04:32 UTC, kidder reviewed
Looks good to me

2018-02-21 22:33 UTC, nilsdeppe approved these changes

2018-02-21 22:34 UTC, kidder approved these changes

2018-02-21 22:34 UTC, merged