Clean up Wedge3D
sxs-collaboration/spectre pull request #550
Opened 2018-02-20 21:59 UTC by gsb76

## Proposed changes

There is a large amount of duplication in the Wedge3D tests - this is addressed.
Minor changes in Wedge3D itself are also made.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### Further comments

2018-02-20 23:30 UTC, gsb76 commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +      const std::array<std::reference_wrapper<const DTYPE(data)>, 3>&    \
double, DV, ref of double, ref of DV

2018-02-20 23:30 UTC, gsb76 commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +void test_wedge3d_all_directions(bool with_equiangular_map) {
const bool

2018-02-20 23:30 UTC, gsb76 commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +void test_wedge3d_alignment(bool with_equiangular_map) {
const all bools in these tests

2018-02-20 23:30 UTC, gsb76 commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +    test_jacobian(map, point);
indentation

2018-02-20 23:30 UTC, gsb76 commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +    test_jacobian(map, point);
space after for loop (parentheses)

2018-02-20 23:30 UTC, gsb76 commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +  CHECK_ITERABLE_APPROX(map_upper_zeta(lowest_corner),lowest_physical_corner_upper_zeta);
spaces after commas

2018-02-20 23:30 UTC, gsb76 commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +    serialize_and_deserialize(map);
map2 = , and test map2 below

2018-02-22 17:37 UTC, nilsdeppe requested changes
I'm fine with you squashing after this fix

2018-02-22 17:37 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +void test_wedge3d_all_directions(const bool with_equiangular_map) {
stick in anonymous namespace (apply to all of the free functions in this file)

2018-02-26 23:35 UTC, kidder requested changes
squash

2018-02-26 23:35 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +  template Tensor<std::decay_t<tt::remove_reference_wrapper_t<DTYPE(data)>>, \
`std::decay ... wrapper_t` -> `tt::remove_cvref_wrap_t` multiple times

2018-02-27 20:33 UTC, gsb76 commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +  template Tensor<tt::remove_cvref_wrap_t<DTYPE(data)>,                       \
remove_cvref_wrap everywhere and use type alias Ij

2018-02-27 23:15 UTC, nilsdeppe approved these changes

2018-02-28 03:44 UTC, kidder approved these changes

2018-02-28 22:19 UTC, merged