Temperature updates for param delep 3D EoS
sxs-collaboration/spectre pull request #5534
Opened 2023-10-03 23:55 UTC by pajkosmi

## Proposed changes

Make parameterized deleptonization compatible with 3D eos and update the temperature in the 3D eos case.   Fixes 2nd half of issue #5520.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

The temperature only needs to be updated for 3D eos cases because a change in electron fraction will not affect the other primitives for 1D/2D eos cases.

2023-10-04 00:07 UTC, nilsdeppe requested changes

2023-10-04 00:07 UTC, nilsdeppe commented on src/Evolution/VariableFixing/ParameterizedDeleptonization.cpp
>          get(equation_of_state.pressure_from_density_and_energy(
In the 1d and 2d case, is there even an EOS call needed? And why don't you need to adjust pressure in the 3d case? If I remember correctly, ultimately you want to keep entropy constant and change Y_e, which would mean pressure, epsilon, and T change. Here it looks like you're wanting to fix epsilon and then vary T and p

2023-10-04 00:07 UTC, nilsdeppe commented on tests/Unit/Evolution/VariableFixing/Test_ParameterizedDeleptonization.cpp
> +
Also check that the values you expect to change, change. E.g. epsilon is the same and T&p change or something

2023-10-05 17:01 UTC, nilsdeppe reviewed
LGTM please squash!

2023-10-05 18:02 UTC, pajkosmi commented
Squashed

2023-10-05 18:07 UTC, nilsdeppe approved these changes

2023-10-05 18:37 UTC, merged