Add option to output matrix in elliptic solver
sxs-collaboration/spectre pull request #5540
Opened 2023-10-05 03:54 UTC by nilsvu

## Proposed changes

Allows to build the explicit matrix representation of the linear operator column-by-column. This is useful for debugging and analysis. Here's how to do it (@PunJustice):

1. See the last commit in this PR for how to add `BuildMatrix` as an optional phase to the executable. It currently just builds the matrix once, but we can add a feature to build it in every step of an outer iteration if needed.
2. Read the matrix from the H5 files in Python like this:

```py
import spectre.IO.H5 as spectre_h5
import matplotlib.pyplot as plt
from spectre.Elliptic.ReadH5 import read_matrix

with spectre_h5.H5File("Volume0.h5", "r") as h5file:
    matrix_file = h5file.get_vol("/Matrix")
    matrix = read_matrix(matrix_file)

plt.spy(matrix, precision=1e-10)
```

Output:

![65b3d0a0-8176-4216-82b4-7925c4dfde35](https://github.com/sxs-collaboration/spectre/assets/746230/c8bedacf-4a78-4511-b805-10412c474ab9)

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-10-09 20:19 UTC, nilsvu commented
@wthrowe would you be willing to review this?

2023-10-09 22:19 UTC, wthrowe requested changes

2023-10-09 22:19 UTC, wthrowe commented on src/ParallelAlgorithms/LinearSolver/Actions/BuildMatrix.hpp
> +  using option_tags = tmpl::list<MatrixSubfileName>;
As far as I know, the discussion in #1345 has not been superseded and simple tags and option tags are supposed to be distinct and in different namespaces.

2023-10-09 22:19 UTC, wthrowe commented on src/ParallelAlgorithms/LinearSolver/Actions/BuildMatrix.hpp
> +/// \brief The total number of grid points (size of the matrix) and the index of
Documentation doesn't show up in detail namespaces.  You've done a good job documenting this stuff, so maybe make it non-detail?

2023-10-09 22:19 UTC, wthrowe commented on src/ParallelAlgorithms/LinearSolver/Actions/BuildMatrix.hpp
> +                       std::to_string(total_num_points) + ".\n");
```c++
Parallel::printf(
    "Building explicit matrix representation of size %zu x %zu.\n",
    total_num_points, total_num_points);
```

2023-10-09 22:44 UTC, nilsvu commented on src/ParallelAlgorithms/LinearSolver/Actions/BuildMatrix.hpp
> +/// \brief The total number of grid points (size of the matrix) and the index of
Not sure, these functions aren't intended to be part of the public interface, so no need to make them public IMO. I just wanted to document them and Doxygen syntax is pretty good for that, and consistent with other docs. I think it's fine to use Doxygen syntax even if detail things are filtered out. Makes it easy to make functions public if we decide to do so later.

2023-10-09 22:47 UTC, nilsvu commented
Pushed a fixup. Thanks for reviewing @wthrowe !

2023-10-10 00:38 UTC, wthrowe approved these changes
Sounds good.  Squash.

2023-10-11 01:11 UTC, merged