Add identity matrix and test
sxs-collaboration/spectre pull request #557
Opened 2018-02-26 21:25 UTC by mgiesler

## Proposed changes

Add identity matrix and tests

### Types of changes:

- [ ] Bugfix
- [X] New feature

### Component:

- [X] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-02-26 21:56 UTC, osheamonn commented on src/DataStructures/Tensor/Identity.hpp
> +      identity_matrix{make_with_value<
Instead of `Tensor <...> = identity_matrix{make_with_value<...>}` use `auto identity_matrix = make_with_value<Tensor<...>>{used_for_size[0], 0.})`

2018-02-26 21:56 UTC, osheamonn commented on src/DataStructures/Tensor/Identity.hpp
> +identity(const std::array<DataType, Dim>& used_for_size) {
Since the array is only used for size why pass the array and not just the DataType? I'm guessing it's relevant for some future PR.

2018-02-26 23:28 UTC, kidder requested changes

2018-02-26 23:28 UTC, kidder commented on src/DataStructures/Tensor/Identity.hpp
> +identity(const std::array<DataType, Dim>& used_for_size) {
pass an object of `const DataType& used_for_size`

2018-02-26 23:28 UTC, kidder commented on src/DataStructures/Tensor/Identity.hpp
> +Tensor<std::decay_t<tt::remove_reference_wrapper_t<DataType>>,
remove the decay and remove_reference_wrapper

2018-02-26 23:28 UTC, kidder commented on src/DataStructures/Tensor/Identity.hpp
> +  Tensor<std::decay_t<tt::remove_reference_wrapper_t<DataType>>,
again no decay and remove...

2018-02-26 23:28 UTC, kidder commented on tests/Unit/DataStructures/Test_Identity.cpp
> +      static_for<0, d>::apply([&](auto i) {
turn these into runtime loops with .get instead of get

2018-02-26 23:28 UTC, kidder commented on tests/Unit/DataStructures/Test_Identity.cpp
> +      static_for<0, d>::apply([&](auto i) {
then take the whole body into 
```
namespace {
template <size_t Dim>
void test_identity(...);
}
```
and call it for each dim in the `SPECTRE_TEST_CASE`

2018-02-27 18:38 UTC, osheamonn commented on src/DataStructures/Tensor/Identity.hpp
> +/// \file
I'd just remove the file description

2018-02-27 18:38 UTC, osheamonn commented on tests/Unit/DataStructures/Test_Identity.cpp
> +void test_identity() {
You should template this on DataType and make sure it works with both DataVectors and doubles. See how it was done at the end of https://github.com/sxs-collaboration/spectre/blob/develop/tests/Unit/PointwiseFunctions/GeneralRelativity/Test_Ricci.cpp

2018-02-27 18:38 UTC, osheamonn commented on tests/Unit/DataStructures/Test_Identity.cpp
> +  const std::array<double, Dim> used_for_size = make_array<Dim>(0.0);
There's no point constructing the array since you only use the 0th component of it.

2018-02-27 21:12 UTC, mar-celine requested changes

2018-02-27 21:12 UTC, gsb76 commented on src/DataStructures/Tensor/Identity.hpp
> +Tensor<DataType, tmpl::integral_list<std::int32_t, 2, 1>,
You can use a tnsr::Ij type alias here

2018-02-27 21:12 UTC, gsb76 commented on src/DataStructures/Tensor/Identity.hpp
> +      Tensor<DataType, tmpl::integral_list<std::int32_t, 2, 1>,
and here

2018-02-27 21:12 UTC, gsb76 commented on tests/Unit/DataStructures/Test_Identity.cpp
> +      identity<double, Dim>(dereference_wrapper(used_for_size[0]))};
dereference wrapper not needed for double

2018-02-27 21:12 UTC, gsb76 commented on src/DataStructures/Tensor/Identity.hpp
>  template <typename DataType, size_t Dim>
swap the order on these because DataType can be inferred

2018-02-27 22:20 UTC, osheamonn submitted a review, later dismissed

2018-02-27 22:30 UTC, mar-celine requested changes

2018-02-27 22:30 UTC, gsb76 commented on tests/Unit/DataStructures/Test_Identity.cpp
> +  const DataVector dv(1);
should not be testing a size one datavector (use size 5 like test_ricci does)

2018-02-27 22:30 UTC, gsb76 commented on src/DataStructures/Tensor/Identity.hpp
>  /// Defines the function identity
remove this (this is part of the \file comment)

2018-02-27 22:30 UTC, gsb76 commented on src/DataStructures/Tensor/Identity.hpp
> +tnsr::iJ<DataType, Dim, Frame::NoFrame> identity(
You had Up, Lo originally (corresponding to tsnr::Ij)

2018-02-27 22:30 UTC, gsb76 commented on src/DataStructures/Tensor/Identity.hpp
> +  auto identity_matrix{make_with_value<tnsr::iJ<DataType, Dim, Frame::NoFrame>>(
and here

2018-02-27 22:30 UTC, gsb76 commented on tests/Unit/DataStructures/Test_Identity.cpp
> +      identity<Dim, DataType>(dereference_wrapper(used_for_size))};
since DataType can be inferred, the second parameter here can be left out. Also remove dereference_wrapper (used_for_size is not a reference_wrapper)

2018-02-27 23:04 UTC, nilsdeppe requested changes
please squash as you make these changes

2018-02-27 23:04 UTC, nilsdeppe commented on src/DataStructures/Tensor/Identity.hpp
> +
I'd remove this blank line here

2018-02-27 23:04 UTC, nilsdeppe commented on src/DataStructures/Tensor/Identity.hpp
> +#include "Utilities/DereferenceWrapper.hpp"
remove this include

2018-02-27 23:04 UTC, nilsdeppe commented on src/DataStructures/Tensor/Identity.hpp
> +    const DataType& used_for_type) {
noexcept!

2018-02-28 04:09 UTC, kidder requested changes

2018-02-28 04:09 UTC, kidder commented on tests/Unit/DataStructures/Test_Identity.cpp
> +
need to include limits, cstddef, DataVector

2018-02-28 04:09 UTC, kidder commented on src/DataStructures/Tensor/Identity.hpp
> +
need to include cstddef

2018-02-28 16:19 UTC, nilsdeppe approved these changes

2018-02-28 16:21 UTC, nilsdeppe requested changes
Please squash

2018-02-28 16:21 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_Identity.cpp
> +#include "Utilities/MakeArray.hpp"
MakeWithValue, not MakeArray

don't need array

2018-02-28 20:38 UTC, mar-celine approved these changes

2018-02-28 21:10 UTC, kidder approved these changes

2018-02-28 21:11 UTC, nilsdeppe approved these changes

2018-02-28 22:19 UTC, merged