Enable p-refinement for ScalarWave executables
sxs-collaboration/spectre pull request #5573
Opened 2023-10-18 14:48 UTC by kidder

## Proposed changes

Enable p-refinement for ScalarWave executables.
Currently only works for global time-stepping.
Only the example input files for 1D actually do AMR during the evolution.  See them if you want to use AMR in 2D or 3D.

### Upgrade instructions

ScalarWave input files need to have additional options, as well as now using global time-steppers instead of local time-steppers.  (See the diff of `tests/InputFiles/ScalarWave/PlaneWave1D.yaml`)

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-10-18 18:12 UTC, wthrowe submitted a review, later dismissed

2023-10-18 18:12 UTC, nilsvu requested changes

2023-10-18 18:12 UTC, nilsvu commented on src/Evolution/DiscontinuousGalerkin/Initialization/Mortars.hpp
> +        const auto& new_neighbor_mesh = neighbor_info.at(neighbor).new_mesh;
```
orientation.inverse()(neighbor_info.at(neighbor_id).new_mesh)
```

Then you can remove the mesh orientation and construction code below (note that you didn't orient the basis/quadrature below).

2023-10-18 18:12 UTC, nilsvu commented on src/Evolution/DiscontinuousGalerkin/Initialization/Mortars.hpp
>          mortar_data->emplace(mortar_id, MortarData<dim>{1});
What's the 1 here actually?

2023-10-18 18:12 UTC, nilsvu commented on src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
> +        ::amr::projectors::DefaultInitialize<
Can you move some/all of these to the corresponding projectors? Would be easier if these are handled by the code that adds the tags, so you don't have to worry about them in the metavars.

2023-10-19 21:10 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/Initialization/Mortars.hpp
>          mortar_data->emplace(mortar_id, MortarData<dim>{1});
the number of buffers used by a MortarData...

2023-10-19 21:12 UTC, kidder commented on src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
> +        ::amr::projectors::DefaultInitialize<
I can, but will defer doing so until I implement the h-refinement overloads for the projectors as what is default initialized may change...

2023-10-20 05:58 UTC, nilsvu commented on src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
> +        ::amr::projectors::DefaultInitialize<
I'm not sure I understand, the way these are handled might change with adding h-refinement, but moving the responsibility to the projectors (which live next to the initializer that adds the tag) already now seems easier than doing so later.

2023-10-20 17:24 UTC, kidder commented on src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
> +        ::amr::projectors::DefaultInitialize<
It is psychological; replacing 5 lines of code with multiple commits adding dozens of lines now seems a waste of my time.  On the other hand, I can easily make the changes across multiple PRs when implementing h-refinement.

2023-10-20 17:30 UTC, nilsvu commented on src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
> +        ::amr::projectors::DefaultInitialize<
ok!

2023-10-20 17:32 UTC, nilsvu commented on src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
> +        ::amr::projectors::DefaultInitialize<
We have to add these to every executable though when we add support for AMR. If you prefer that fine with me, just checking.

2023-10-20 20:06 UTC, nilsvu approved these changes

2023-10-20 20:06 UTC, nilsvu commented on src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp
> +        ::amr::projectors::DefaultInitialize<
Merging now, this can be done ina follow-up as well when adding AMR to more executables

2023-10-23 15:00 UTC, merged