Limit time step to prevent control-system deadlocks
sxs-collaboration/spectre pull request #5593
Opened 2023-10-25 02:17 UTC by wthrowe

## Proposed changes

### Upgrade instructions

Executables with control systems and global time-stepping will now work with any time stepper, not just AdamsBashforth.  When using a non-AdamsBashforth time stepper the step size will gradually decrease, so you should include the ChangeSlabSize event to increase it again.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-10-30 19:19 UTC, knelli2 requested changes
Have you tested this will all the executables you've changed here that have control systems? (Namely BH, BBH, BNS, STBH). While the code looks ok, I'm worried some strange deadlock could occur if this isn't fully tested for each with large numbers of elements.

2023-10-30 19:19 UTC, knelli2 commented on src/ControlSystem/Actions/LimitTimeStep.hpp
> +  static Parallel::iterable_action_return_t apply(
Add
```cpp
static_assert(Metavariables::local_time_stepping, "The control system LimitTimeStep
    Action can only be used with global time stepping");
```
inside the action?

2023-10-30 19:19 UTC, knelli2 commented on src/ControlSystem/Actions/LimitTimeStep.hpp
> +      auto& measurement_times =
Rename to `future_measurements`? Having both `measurement_times` and `measurement_timescales` was a bit confusing.

2023-10-30 19:19 UTC, knelli2 commented on src/ControlSystem/Actions/LimitTimeStep.hpp
> +          *db::get<Tags::FutureMeasurements<group>>(box).next_update();
[optional] `.value()` instead?

2023-10-30 19:19 UTC, knelli2 commented on tests/Unit/ControlSystem/Actions/Test_LimitTimeStep.cpp
> +  ASSERT(fot_updatesC.size() > 1, "Bad argument");
Do you really need these? Usually for a test we just assume function arguments are correct because we are the ones creating a test. If you decide we do want these because it makes debugging easier, maybe use `REQUIRE` since we want to catch this in Release mode as well? The errors are probably self explanatory and "Bad argument" isn't a great error message.

2023-10-30 19:19 UTC, knelli2 commented on tests/Unit/ControlSystem/Actions/Test_LimitTimeStep.cpp
> +       {{0.0, arbitrary}, {4.0, nan}},  // goal range [2, 4]
Question: Does it matter that the measurement timescales expire before the FoT expiration time? Or that the number of measurements technically don't line up with the measurement timescale and measurement expiration? Or are you just forcing it to test the FoT expiration time code? (Same question for several others below)

2023-10-30 19:19 UTC, knelli2 commented on tests/Unit/ControlSystem/Actions/Test_LimitTimeStep.cpp
> +       {{0.0, arbitrary}, {50.0, nan}},  // goal range [20, 50]
What is this goal range? The 50 seems somewhat self explanatory, but the 20 doesn't. Could you add a comment before this about what the goal range is supposed to represent?

2023-10-30 21:01 UTC, wthrowe reviewed
Fixup pushed.

> Have you tested this will all the executables you've changed here that have control systems? (Namely BH, BBH, BNS, STBH). While the code looks ok, I'm worried some strange deadlock could occur if this isn't fully tested for each with large numbers of elements.

I have tested with `EvolveGhSingleBlackHole`.  I don't know how to run BBH or BNS.

As far as I am aware, this problem is independent of the domain decomposition.

2023-10-30 21:01 UTC, wthrowe commented on tests/Unit/ControlSystem/Actions/Test_LimitTimeStep.cpp
> +  ASSERT(fot_updatesC.size() > 1, "Bad argument");
As the one writing the test, I got the arguments wrong (requiring two entries is unusual), so I put in an assertion.  We always use ASSERT to check function arguments.  I agree the message isn't useful, but the message field is required and I have nothing to add to the text of the test.

2023-10-30 21:01 UTC, wthrowe commented on tests/Unit/ControlSystem/Actions/Test_LimitTimeStep.cpp
> +       {{0.0, arbitrary}, {4.0, nan}},  // goal range [2, 4]
This code is not supposed to care when the measurement timescales expire (except that it needs enough to evaluate them).  Making it late means I didn't have to tune it to be between the update and next measurement each time, particularly in the later cases covering multiple FoT updates.

The measurements and expirations won't line up exactly in the real case because of floating-point error.  Testing this way makes any problem from that obvious.

2023-10-30 23:27 UTC, knelli2 commented
It's not domain composition that directly affects this. If there was a roundoff bug regarding expiration times (not saying that there is), then it's possible we wouldn't catch it with a smaller number of elements/nodes. This is because there'd be less charm communication latency and so FoTs would be updated before any elements reached that time. But with more nodes/elements this problem gets worse (as I've seen for BBH).

I think it would be a good idea to have @geoffrey4444 and @ffoucart do some standard runs for their respective problems with GTS RK (or DP) methods. Maybe also include the event that periodically resets the timestep size based on the cfl.

(You can squash the fixup in)

2023-11-11 04:14 UTC, nilsdeppe approved these changes
BNS mergers seem to still run. I have an AB run going still, but also tried an RK3. The RK3 run was about 10x _slower_ than AB3. It's here `/home/nils/ds09/spectre/BnsRuns/GtsControlSystem` My guess is that for some reason the control system is way too tight for rotation, but I don't know how to check that or how to adjust that. AB run is here `/home/nils/ds09/spectre/BnsRuns/GtsControlSystemAb`. both are on Wheeler

@knelli2 @wthrowe any insights into the huge slowdown of RK methods would be appreciated. Naively I would've expected these runs not to be limited by the control system

2023-11-11 19:36 UTC, knelli2 approved these changes
Ok so after discussing with @nilsdeppe, he just had to increase the initial damping timescale and the run was back to it's normal speed. So it appears the BNS is working as expected. I also know @geoffrey4444 has a student testing the BBH with GTS, but since the BBH executable is still LTS on develop, this PR won't affect it. Therefore, I'm satisfied this PR works and it can be merged.

Ignoring known test failures.

2023-11-11 19:37 UTC, merged