Update installation instructions for Spack, Charm++, SpECTRE
sxs-collaboration/spectre pull request #56
Opened 2017-06-24 07:22 UTC by fmahebert

* Slight cleanup of dependencies list
* Update Spack instructions...
  *  Point to Spack docs for OpenSSL directions
  *  Update instructions to set up user environment with modules from Spack
* Update Charm++ and SpECTRE instructions for clarity

2017-06-24 20:06 UTC, nilsdeppe requested changes

2017-06-24 20:06 UTC, nilsdeppe commented on docs/MainSite/Installation.md
> +    and `git checkout vx.y.z` to switch to a recent release.
I would prefer we actually specify a required version and update this. Charm++ updates rather slowly and each update breaks lots of things...

2017-06-24 20:06 UTC, nilsdeppe commented on docs/MainSite/Installation.md
> +    correct target architecture is likely to be `mpi-linux-x86_64`
For 6.7.1 on personal machines it should be `multicore-...`

2017-06-24 20:06 UTC, nilsdeppe commented on docs/MainSite/Installation.md
>  spack install libxsmm
Would you mind adding GSL to this list?

2017-06-24 20:06 UTC, nilsdeppe commented on docs/MainSite/Installation.md
>  * [HDF5](https://support.hdfgroup.org/HDF5/) (non-mpi version on macOS)
Would you mind adding GSL to this list?

2017-06-24 20:06 UTC, nilsdeppe commented on docs/MainSite/Installation.md
> +    correct target architecture is likely to be `mpi-linux-x86_64`
We should also note that we will be providing specific instructions for various HPC systems

2017-06-27 03:22 UTC, nilsdeppe approved these changes

2017-06-27 03:59 UTC, fmahebert commented
I will squash some of these commits and update the PR

2017-06-27 14:42 UTC, merged