Add function for contracting the first N indices of two Tensors
sxs-collaboration/spectre pull request #5602
Opened 2023-10-27 03:13 UTC by macedo22

## Proposed changes

This PR adds a function that contracts the first N indices of two `Tensor`s

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-10-27 19:44 UTC, wthrowe requested changes
Doxygen is annoyed about something, but otherwise this looks good.  (The other CI failures are unrelated to these changes.)

I have tested this in my local code and it seems to work fine.

2023-10-27 20:36 UTC, macedo22 commented
@wthrowe Is there something I need to do regarding doxygen? I only saw doxygen errors for other code, but maybe I'm not seeing something else that you're seeing

2023-10-27 21:42 UTC, wthrowe approved these changes, later dismissed
You're right.  I didn't look closely at the error.

2023-10-30 17:06 UTC, wthrowe commented
Needs a rebase for conflicts.

2023-10-31 18:51 UTC, wthrowe commented
Test failures are unrelated to this PR.

2023-10-31 18:51 UTC, merged