Uplow bc pr
sxs-collaboration/spectre pull request #5611
Opened 2023-11-01 16:25 UTC by jyoo1042

## Proposed changes
Enable different upper and lower boundary conditions in Brick.

2023-11-01 19:27 UTC, kidder requested changes

2023-11-01 19:27 UTC, kidder commented on tests/Unit/Domain/Creators/Test_Brick.cpp
> +  using var_wrap = std::variant<
rename var_wrap to VariantType

2023-11-01 19:27 UTC, kidder commented on tests/Unit/Elliptic/DiscontinuousGalerkin/SubdomainOperator/Test_SubdomainOperator.cpp
> +  using var_wrap = std::variant<
var_wrap -> VariantType

2023-11-01 19:27 UTC, kidder commented on tests/Unit/Elliptic/DiscontinuousGalerkin/Test_DgOperator.cpp
> +  using var_wrap = std::variant<
var_wrap -> VariantType

2023-11-01 19:27 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/FiniteDifference/Test_BoundaryConditionGhostData.cpp
> +  using var_wrap = std::variant<
var_wrap -> VariantType

2023-11-01 19:27 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/FiniteDifference/Test_BoundaryConditionGhostData.cpp
> +  using var_wrap = std::variant<
var_wrap -> VariantType

2023-11-08 06:58 UTC, yoonso0-0 commented
This looks like a very nice feature to add.

2023-11-08 15:04 UTC, kidder approved these changes

2023-11-08 15:04 UTC, merged