Clean up concrete CoordinateMaps
sxs-collaboration/spectre pull request #562
Opened 2018-02-28 05:43 UTC by gsb76

## Proposed changes

Clean up more CoordinateMaps by using type aliases and GENERATE_INSTANTIATIONS

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-03-05 20:52 UTC, nilsdeppe requested changes

2018-03-05 20:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Identity.cpp
> +      dereference_wrapper(source_coords[0]), 0.0);
Can this now use the identity function Matt added?

2018-03-05 20:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Identity.cpp
> +
Again about using the identity function

2018-03-05 20:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/ProductMaps.hpp
> +    std::integer_sequence<size_t, Js...> /*meta*/) {
noexcept, apply liberally throughout, including lambdas

2018-03-05 20:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/ProductMaps.hpp
>      std::integer_sequence<size_t, Js...> /*meta*/) {
noexcept

2018-03-05 20:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/ProductMaps.hpp
>        const std::array<T, dim>& source_coords) const;
noexcept all

2018-03-05 20:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Rotation.cpp
> +  tnsr::Ij<tt::remove_cvref_wrap_t<T>, 2, Frame::NoFrame> jac{
you are inconsistently moving `jac` -> `jacobian_matrix`

2018-03-05 20:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Rotation.cpp
> +  tnsr::Ij<tt::remove_cvref_wrap_t<T>, 2, Frame::NoFrame> inv_jac{
you are inconsistently moving `inv_jac` to `inv_jacobian_matrix`

2018-03-05 20:52 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge2D.cpp
>                                        const auto& cap_eta_deriv) {
noexcept the lambda, apply liberally

2018-03-05 20:58 UTC, kidder requested changes

2018-03-05 20:58 UTC, kidder commented on src/Domain/CoordinateMaps/Identity.cpp
> +tnsr::Ij<tt::remove_cvref_wrap_t<T>, Dim, Frame::NoFrame>
use the new function in `Tensor/Identity.hpp`

2018-03-05 20:58 UTC, kidder commented on src/Domain/CoordinateMaps/Identity.cpp
> +    inv_jacobian_matrix.get(i, i) = 1.0;
and here too

2018-03-05 20:58 UTC, kidder commented on src/Domain/CoordinateMaps/Identity.hpp
> +  return false;
keep the old one (in case operator== changes)

2018-03-05 20:58 UTC, kidder commented on src/Domain/CoordinateMaps/ProductMaps.hpp
> +std::array<tt::remove_cvref_wrap_t<T>, Size> apply_call(
noexcept everything

2018-03-05 22:07 UTC, kidder requested changes

2018-03-05 22:07 UTC, kidder commented on src/Domain/CoordinateMaps/Identity.cpp
> +  return identity<Dim, tt::remove_cvref_wrap_t<T>>(source_coords[0]);
`return identity<Dim>(dereference_wrapper(source_coords[0]));`

2018-03-05 22:07 UTC, kidder commented on src/Domain/CoordinateMaps/Identity.cpp
> +  return identity<Dim, tt::remove_cvref_wrap_t<T>>(source_coords[0]);
and again

2018-03-05 23:13 UTC, kidder submitted a review, later dismissed

2018-03-06 00:37 UTC, nilsdeppe submitted a review, later dismissed

2018-03-06 17:54 UTC, nilsdeppe approved these changes

2018-03-06 17:55 UTC, nilsdeppe commented
@kidder @wthrowe can you look at this?

2018-03-06 18:21 UTC, wthrowe approved these changes

2018-03-06 20:37 UTC, merged