Fix curved mesh support for FD
sxs-collaboration/spectre pull request #5628
Opened 2023-11-17 03:11 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-11-17 15:35 UTC, kidder requested changes

2023-11-17 15:35 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> +        "You will at least update the high-order boundary correction code to "
need to

2023-11-17 15:35 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> +        "You will at least update the high-order boundary correction code to "
is the assumption on line 61 still being made?

2023-11-17 15:35 UTC, kidder commented on src/Evolution/DgSubcell/Actions/ReconstructionCommunication.hpp
> +        // two blocks have the same may but different orientation. Since this
I don't understand this line of the comment...

2023-11-17 15:35 UTC, kidder commented on tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TimeDerivative.cpp
> +           DO::Two  // , DO::Four, DO::Six, DO::Eight, DO::Ten
add comment here why higher order is commented out

2023-11-17 15:35 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> +          " Same care needs to be taken since we also get F^j from our "
some care

2023-11-17 15:35 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TimeDerivative.hpp
> +                  evolution::dg::subcell::fd::project_to_face(
rename project_to_faces (as I was confused about how what the target of the projection is)

2023-11-18 00:30 UTC, nilsdeppe commented
Rebased and squashed. Thanks for the review!

2023-11-18 04:24 UTC, kidder approved these changes

2023-11-18 04:24 UTC, merged