WorldtubeBufferUpdater and WorldtubeDataManager for CCE
sxs-collaboration/spectre pull request #5640
Opened 2023-11-27 03:54 UTC by Sizheng-Ma

## Proposed changes

This PR aims to pave the path for dealing with the worldtube data of the Klein-Gordon CCE system. Two major changes are introduced to the current infrastructure

1. The current `WorldtubeDataManager` is hard-coded to handle `Tags::characteristic_worldtube_boundary_tags<Tags::BoundaryValue>`. This can be relaxed so that it can be used to deal with other worldtube data (say a scalar field).
2. There are repeated contents in `WorldtubeBufferUpdater` and `WorldtubeDataManager`, and will be more once they are extended to handle the Klein-Gordon system. I extract some common parts into functions to avoid more copy and paste.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-11-27 04:00 UTC, Sizheng-Ma commented
I've tested the executable `CharactersiticExtract` with a BBH system. All the waveform outputs are not impacted by the changes.

2023-11-27 18:19 UTC, knelli2 requested changes

2023-11-27 18:19 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeBufferUpdater.hpp
> +void get_modal_data_for_bondi_and_klein_gordon(
We don't want to have to keep renaming this function every time a new CCE system is added. Maybe `update_buffer_with_modal_data`?

2023-11-27 18:19 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeBufferUpdater.hpp
> +                              const h5::Dat& data);
This should probably be `set_time_buffer_and_lmax` since this function doesn't return anything. (The other function `get_text_radius` is fine because it actually returns something)

2023-11-27 18:19 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeDataManager.hpp
>  class WorldtubeDataManager : public PUP::able {
Add a line in the dox that `BoundaryTags` is a `tmpl::list` of tags on the worldtube boundary

2023-11-27 18:19 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeDataManager.hpp
> +void puper(size_t& time_span_start, size_t& time_span_end,
Rename to `set_non_pupped_members`. Also since this doesn't actually use the pupper, take all the reference arguments as `gsl::not_null`.

2023-11-27 18:19 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeDataManager.hpp
> +void constructor(size_t& buffer_depth,
Rename to `initialize_buffers`. Also take the reference arguments as `gsl::not_null`

2023-11-28 02:21 UTC, Sizheng-Ma commented
Done!

2023-11-28 03:30 UTC, knelli2 requested changes
Looks good. Squash all the fixups including these last few changes.

2023-11-28 03:30 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeDataManager.cpp
> +    gsl::not_null<Variables<InputTags>*> interpolated_coefficients,
Make these `const gsl::not_null` here in the cpp file only.

2023-11-28 03:30 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeDataManager.cpp
> +    gsl::not_null<Variables<InputTags>*> coefficients_buffers,
Same here, `const gsl::not_null` only in cpp.

2023-11-28 13:50 UTC, Sizheng-Ma commented
Done. I noticed that the first argument of `set_time_buffer_and_lmax` was also a reference. I switched it to `gsl::not_null` in the last commit.

2023-11-28 16:01 UTC, knelli2 reviewed
Nice catch. You can squash the final fixup

2023-11-28 17:34 UTC, Sizheng-Ma commented
Ok, squashed.

2023-11-28 18:44 UTC, knelli2 approved these changes

2023-12-05 16:54 UTC, merged