Add IMEX SolveImplicitSector mutator
sxs-collaboration/spectre pull request #5653
Opened 2023-12-05 21:12 UTC by wthrowe

This is the actual solver for the IMEX code.  The remaining stuff to submit is mostly actions and other similar wrappers.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-12-11 15:28 UTC, nilsdeppe requested changes
This is great! Thanks for all your hard work on the IMEX code! I have a few suggestions/comments/questions. Please feel free to rebase and squash directly since I don't think any of them are major.

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/Tags/Mode.hpp
> +struct ImexMode {
Do you want to add Doxygen comments for the tags, mostly for discoverability?

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/Tags/Mode.hpp
> +  using group = evolution::OptionTags::Group;
Would it be useful to add an `Imex` subgroup into `Evolution` to group the options together? [later in a separate PR is totally fine if you think it's a good idea!]

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/Tags/SolveTolerance.hpp
> +struct ImexImplicitSolveTolerance {
same doxygen question

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/SolveImplicitSector.hpp
> +      tmpl::push_front<attempt_tags,
Is it possible `tmpl::append` here to combine the two lists? If not, maybe a comment why?

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/SolveImplicitSector.tpp
> +  bool had_failure = true;
I think I would find reading the code easier if this was `solve_succeeded` or something like that. `not had_failure` I think is `success` and I would find it easier to read
```cpp
if (solve_succeeded) {
  return;
}
```

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/SolveImplicitSector.tpp
> +          auto correction_array = solver(initial_guess);
I'm a bit unclear on what memory allocations are being done in the `SemiImplicit` solve. Does this `solver` call and the `jacobian()` call below do memory allocations? I think the `lapack::general_matrix_linear_solve` call also does a `std::vector` allocation inside. If we are doing those three allocations, could they be combine or shared between grid points? If that's already being done, would a comment or two in this part of the switch statement be useful?

Edit: from looking at the above code I think there aren't any allocations, other than maybe inside `general_matrix_linear_solve`? Maybe a few comments here would help make that clear?

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/SolveImplicitSector.tpp
> +  bool do_solve() const { return implicit_weight_ != 0.0; }
the function name makes me think it does some computation. Maybe rename to something like `solved_needed`?

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/SolveImplicitSector.tpp
> +                  "ImplicitSolver was passed a temporary.");
Could you expand this error message? I'm not sure what I should do if I were to get this.

2023-12-11 15:28 UTC, nilsdeppe commented on src/Evolution/Imex/SolveImplicitSector.tpp
> +class ImplicitSolver {
Would some overview documentation be useful here? Not necessarily for doxygen, but to get a quick overview of what the different functions do and why? Maybe also for `ImplicitEquation`?

2023-12-11 15:28 UTC, nilsdeppe commented on tests/Unit/Helpers/Evolution/Imex/TestSector.hpp
> +  static void function(gsl::not_null<typename ReadOnly::type*> dest,
`const gsl::not_null`?

2023-12-11 15:28 UTC, nilsdeppe commented on tests/Unit/Evolution/Imex/Test_SolveImplicitSector.cpp
> +// [initial_guess]
Do you want this `initial_guess` to be around the `AnalyticSolution` or the `InitialGuess` class below? Right now I think it's around the `AnalyticSolution`

2023-12-13 21:33 UTC, wthrowe reviewed
This is now dependent on (and includes the commits from) #5657.

2023-12-13 21:33 UTC, wthrowe commented on src/Evolution/Imex/SolveImplicitSector.hpp
> +      tmpl::push_front<attempt_tags,
Renamed a thing and added some comments to try to make this clearer.  Not sure if it's enough.

2023-12-13 21:33 UTC, wthrowe commented on src/Evolution/Imex/SolveImplicitSector.tpp
> +                  "ImplicitSolver was passed a temporary.");
You should stop passing a temporary.  I've added a brief explanation of why.

2023-12-13 21:33 UTC, wthrowe commented on src/Evolution/Imex/SolveImplicitSector.tpp
> +          auto correction_array = solver(initial_guess);
There weren't supposed to be any after the first point, but you're right that I missed one in the LAPACK wrapper, so I fixed that.

I've made the types of some variables and temporaries explicitly arrays, so it should be clear that there are no allocations in them.

2023-12-13 21:33 UTC, wthrowe commented on tests/Unit/Evolution/Imex/Test_SolveImplicitSector.cpp
> +// [initial_guess]
This is intentional.  They are both valid "initial_guess" structs (the example chooses between them with a `tmpl::conditional_t`), but this one does a reasonable calculation while `InitialGuess` just does some nonsensical modifications to the data.

2023-12-13 21:33 UTC, wthrowe commented on src/Evolution/Imex/Tags/Mode.hpp
> +  using group = evolution::OptionTags::Group;
Done, and renamed some tags both to avoid duplicating the group name and for consistency.

2023-12-14 02:38 UTC, nilsdeppe reviewed
LGTM, please go ahead and squash!

2023-12-15 03:15 UTC, wthrowe commented
@nilsdeppe I think this is ready to go.

2023-12-15 03:23 UTC, nilsdeppe approved these changes

2023-12-15 03:23 UTC, merged