Move frame transformations to Tensor lib, add function to transform flux tensors to logical frame
sxs-collaboration/spectre pull request #5654
Opened 2023-12-07 19:25 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-12-11 16:44 UTC, nilsdeppe requested changes
Thanks for doing this! Some suggestions, please squash immediately :)

2023-12-11 16:44 UTC, nilsdeppe commented on tests/Unit/DataStructures/Tensor/EagerMath/Test_FrameTransform.cpp
>  SPECTRE_TEST_CASE("Unit.PointwiseFunctions.GeneralRelativity.Transform",
I think you forgot to update the test name when you moved it in the first commit

2023-12-11 16:44 UTC, nilsdeppe commented on src/DataStructures/Variables/FrameTransform.hpp
> +namespace Tags {
dox for the namespace and/or tag?

2023-12-11 16:44 UTC, nilsdeppe commented on src/DataStructures/Variables/FrameTransform.hpp
> +ResultVars first_index_to_different_frame(
dox so it can be found in doxygen?

2023-12-11 16:44 UTC, nilsdeppe commented on src/DataStructures/Variables/FrameTransform.hpp
> +void first_index_to_different_frame(
dox?

2023-12-11 18:10 UTC, nilsvu commented
Fixed, thanks for reviewing 👍

2023-12-11 18:30 UTC, nilsdeppe approved these changes

2023-12-12 16:32 UTC, nilsvu commented
Merging now, @markscheel let me know if you have any comments on this and I can do a follow-up.

2023-12-12 16:32 UTC, merged