Convert Tags::TimeStepper to not be a base tag
sxs-collaboration/spectre pull request #5657
Opened 2023-12-07 23:16 UTC by wthrowe

First commit is IMEX changes that would have major conflicts with this redesign.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-12-08 23:07 UTC, kidder requested changes
you can squash the changes

2023-12-08 23:07 UTC, kidder commented on src/Time/Tags/TimeStepper.hpp
> +/// List of Tags::TimeStepperRef specializations needed then adding a
then -> when

2023-12-08 23:07 UTC, kidder commented on src/Time/Tags/TimeStepper.hpp
> +/// The evolution TimeStepper.
Add something like:
`/// \detail StepperType can be either a concrete type (e.g. in a test) or the abstract base type (e.g. in an executable that lets you select the concrete type from the input file)`

2023-12-08 23:07 UTC, kidder commented on src/Time/Tags/TimeStepper.hpp
> +template <typename StepperInterface>
add something like 
`/// \detail This tag should only be used for fetching (i.e. calling get or in an argument_tags list).  This tag should not be directly added to a DataBox or the ConstGlobalCache.  Instead add the appropriate ConcreteTimeStepper and TimeStepperRef tags (which can be obtained with time_stepper_ref_tags).`

2023-12-09 01:49 UTC, nilsdeppe commented
I have no additional comments. Please merge once Larry's happy. No need to wait for me :)

2023-12-12 01:06 UTC, knelli2 commented
I was trying to get the GH+CCE executable compiling again an ran into an issue with two time steppers being added to the box (one for GH, one for CCE) that had the same base tag `Tags::TimeStepper<>`. I think this PR will fix my issue.

2023-12-12 01:19 UTC, wthrowe reviewed
I also changed the tests to use the `time_stepper_ref_tags` alias instead of adding the tags directly, and added a test of that.

2023-12-12 01:19 UTC, wthrowe commented on src/Time/Tags/TimeStepper.hpp
> +/// The evolution TimeStepper.
I decided to stop using concrete types, since it was unnecessarily confusing.  (The only benefit was that you didn't need static casts when creating DataBoxes.)

2023-12-12 02:16 UTC, kidder reviewed
fixup looks good, squash

2023-12-12 03:25 UTC, kidder requested changes
sorry missed this

2023-12-12 03:25 UTC, kidder commented on src/Time/Tags/TimeStepper.hpp
> +/// \detail This tag cannot be added directly to the DataBox of
`\details`

2023-12-14 03:59 UTC, kidder approved these changes

2023-12-14 03:59 UTC, merged