Add copy of vector of EaDT from options to cache
sxs-collaboration/spectre pull request #5664
Opened 2023-12-11 22:09 UTC by knelli2

## Proposed changes

Even though the EventsAndDenseTriggers object itself is mutated inside the element DataBox, the actual dense triggers and events aren't changed and can therefore, in theory, be available in the GlobalCache. This PR adds a new mutable cache tag that stores the vector of dense triggers and events. The reason it is mutable is because EaDT has a method `add_trigger_and_events` where you can add more triggers/events during execution. This means that in order to keep the cache tag up to date, it will have to be mutated. The mutation is left to whatever adds the new triggers/events. Currently, this PR doesn't add any of the special mutations that are needed (basically the control system triggers/events).

This PR will be needed for interpolation framework changes.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-12-12 02:27 UTC, wthrowe requested changes
> the actual dense triggers and events aren't changed

I think what you meant here is that the identities of the dense triggers and events aren't changed?  Because the dense trigger objects themselves are.

I'd like more information about how you intend to use this.  What will update it, and what will read it?  It can't be used in the way we've used mutable cache tags in the past, since there is no way to handle an is_ready call.

Do you actually need the dense triggers, or would just a list of events be enough?

2023-12-12 02:27 UTC, wthrowe commented on src/Evolution/EventsAndDenseTriggers/Tags.hpp
> +            type{deserialize<
I don't think you need to go through the serialization framework twice.  You already have an rvalue after the inner deserialize.

2023-12-12 05:12 UTC, knelli2 commented
> I think what you meant here is that the identities of the dense triggers and events aren't changed? Because the dense trigger objects themselves are.

Ah yes that is what I meant, and is much clearer.

So at the end of the day, what I need is a vector of events (interpolation events, which I have a way of distinguishing)  that are going to be run during the simulation. I will then use this vector of events in the `allocate_array` function of an Array chare to initialize one element of the array for each event (using a unique string for each event as the array index). Basically the only thing that can be guaranteed to exist in `allocate_array` is the GlobalCache. Since the EaTs are already stored in the cache, it is simple to get the EaTs, check if the event is an interpolation, and add it to the vector. The EaDTs are not as simple because we can add more dense triggers/events during the initialization phase with the `add_trigger_and_events` method of EaDT.

So yes, I technically only need the events from the EaDTs available in the `allocate_array` function. I believe it's too complicated to try and create more array elements after initialization has started which is why I would like to get everything done in the `allocate_array` function, but I'm not really sure that is possible.

2023-12-12 19:41 UTC, wthrowe commented
The `allocate_array` functions used to be able to take arguments, but that appears to have been removed in #1650 (since `Main` and `DistributedObject` now both use `component::simple_tags_from_options`).  I think that's really what you want here?  @kidder I haven't read through that entire PR discussion, but do you remember if there was a reason for that decision?

2023-12-12 20:28 UTC, kidder commented
- The `allocate_array` functions are passed a tagged tuple of initialization_items which can be constructed from the input file options (and the metavariables) via the `simple_tags_from_options` typelist.  Is there other information needed?  If so, where is it coming from?

2023-12-12 20:31 UTC, wthrowe commented
Unless I'm misreading the code, that same list is also used to compute the DataBox, though.

2023-12-12 21:04 UTC, kidder commented
- yes, that is true.  It could be easily changed if needed.  In the past there was a separate `array_allocation_tags` that could be reinstated for anything only needed inside the `allocate_array` function.  
- anything in the const global cache is also available during the `allocate_array` function
- I'm not clear on what this array component is, and what information you want to pass the `allocate_array` function

2024-01-10 01:57 UTC, knelli2 commented
Closing this in favor of re-implementing the `array_allocation_tags` method. This was discussed with the reviewers offline.

2024-01-10 01:57 UTC, closed without merging