Change worldtube scheme to inertial frame
sxs-collaboration/spectre pull request #5668
Opened 2023-12-14 15:39 UTC by nikwit

Changes the internal worldtube solution from the grid frame to the inertial frame which is required for the inspiral evolution.
The singleton component now sends the _coefficients_ of the series of the regular field (required for the boundary conditions) and each element evaluates the series on their own inertial coordinates. This should also make the worldtube scheme compatible with p-refinement.

depends on #5666

2024-01-10 18:51 UTC, knelli2 reviewed
Looks good. Just a couple dox things. You can squash them

2024-01-10 18:51 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/ReceiveWorldtubeData.hpp
> + * regular field have been send by the worldtube. If so, the series is evaluated
[nitpick] "have been sent"

2024-01-10 18:51 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/ElementActions/ReceiveWorldtubeData.hpp
> + * at the face coordinates and the puncture field is added to it to obtain the
"at the face coordinates in the inertial frame"

2024-01-11 20:18 UTC, nikwit commented
done, thanks for the review!

2024-01-11 21:51 UTC, knelli2 requested changes
The docs changes look good, but now CI is unhappy for some reason.

2024-01-12 14:57 UTC, nikwit commented
issue with the rebase, fixed it.

2024-01-12 21:09 UTC, knelli2 commented
Ignoring clang-tidy errors about `hdf5.h`

2024-01-12 21:09 UTC, merged