Support weak form in elliptic DG
sxs-collaboration/spectre pull request #5679
Opened 2023-12-16 00:16 UTC by nilsvu

## Proposed changes

Almost gets the elliptic solver to work on large sphere domains! The attached `Lorentzian.yaml` configuration works, only BBH ID needs some more treatment (next PR).

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2023-12-16 03:58 UTC, nilsdeppe requested changes
LGTM! A couple suggestions. Feel free to squash & rebase right away!

2023-12-16 03:58 UTC, nilsdeppe commented on src/Elliptic/DiscontinuousGalerkin/Initialization.cpp
> +  // When I tried (NV, Dec 2022) the DG residuals diverged on a sphere domain
Q: Dec. 2022 or Dec. 2023?

2023-12-16 03:58 UTC, nilsdeppe commented on src/Elliptic/DiscontinuousGalerkin/DgOperator.hpp
> +          lhs[i] += sign * 0.5 * rhs[i];
[optional] consider precomputing `sign * 0.5` outside the loop. That multiplication is 1/3 the FLOPS in this expression. At least a few years ago, compilers weren't doing that automatically :(

2023-12-17 00:03 UTC, nilsvu commented on src/Elliptic/DiscontinuousGalerkin/Initialization.cpp
> +  // When I tried (NV, Dec 2022) the DG residuals diverged on a sphere domain
Oops 👍

2023-12-17 00:44 UTC, nilsdeppe approved these changes

2023-12-17 00:54 UTC, merged