Add puncture field for arbitrary geodesic orbits
sxs-collaboration/spectre pull request #5689
Opened 2024-01-03 15:55 UTC by nikwit

## Proposed changes
Implements a puncture field for general geodesic orbits, lifting the relaxation for strictly circular orbits. 

depends on #5688 #5681 #5677 #5666

2024-01-23 21:01 UTC, knelli2 requested changes
Just a couple things I noticed when skimming the puncture calculations. You can squash directly.

2024-01-23 21:01 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/PunctureFieldOrder0.cpp
> +  const auto& z = get<2>(centered_coords);
Why are these `Dx` and `Dy` and not `Dz`? Is it because the orbit is in the xy-plane? If so, maybe a comment would be good.

2024-01-23 21:01 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/PunctureFieldOrder0.cpp
> +      2.0 * ypdot * (-dv_24 * yp + dv_3 * dv_51);
[Small optimization] Factor out the `2.0`

2024-01-23 21:01 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/PunctureFieldOrder0.cpp
> +      (4.0 * M * dv_16 * (d_15 + d_16) * (-dv_34 + dv_8 * (d_3 + rp)) -
[Small optimization] Use 0.5

2024-01-23 21:01 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/PunctureFieldOrder0.cpp
> +      (4.0 * M * dv_12 - d_18 * dv_25 * dv_26 + d_20 * dv_32 - 2.0 * dv_10 +
[Small optimization] Use 0.5

2024-01-23 21:01 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/PunctureFieldOrder0.cpp
> +      (-2 * d_21 * d_23 * dv_37 * dv_45 - 7.0 * d_26 * dv_36 * dv_38 +
Could do `-dv_59 / (d_21 * d_23) * ...`

2024-01-23 21:01 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/PunctureFieldOrder1.cpp
> +           16.0 * xpdot *
[Small optimization] Factor out `16.0`

2024-01-23 21:01 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/PunctureFieldOrder1.cpp
> +               1.0 / 24.0 * d_21 * dv_195 * dv_45 + 1.0);
`0.5`?

2024-01-26 14:56 UTC, nikwit commented
I included all your suggestions, thanks for the review!

2024-01-26 19:31 UTC, knelli2 requested changes

2024-01-26 19:31 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/PunctureFieldOrder0.cpp
> +  const double d_38 = 2.0 * d_10 + 2.0 * d_36 + 2.0 * d_37 + 2.0 * d_9 - rpdot;
Sorry, missed this one. Factor out `2.0`. (but not from `rpdot`)

2024-02-01 17:22 UTC, knelli2 approved these changes

2024-02-01 17:22 UTC, merged