Add function to create a spacetime tensor from time and spatial ones.
sxs-collaboration/spectre pull request #5692
Opened 2024-01-05 20:59 UTC by ncorsobh

## Proposed changes

The function combines the desired time component of a tensor with the desired spatial components of a tensor to produce one spacetime tensor. For instance, it could combine a time derivative with a spatial derivative to produce a spacetime derivative.

If there are locations throughout the code where this could be usefully applied to replace existing code, please suggest them!

### Upgrade instructions

### Code review checklist

- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [x] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-01-08 23:07 UTC, wthrowe requested changes

2024-01-08 23:07 UTC, wthrowe commented on src/DataStructures/Tensor/CreateView.hpp
> +    gsl::not_null<TensorMetafunctions::prepend_spacetime_index<
`#include "Utilities/Gsl.hpp"`

2024-01-08 23:07 UTC, wthrowe commented on src/DataStructures/Tensor/CreateView.hpp
> +  for (size_t storage_index = 0;
`#include <cstddef>`

2024-01-08 23:07 UTC, wthrowe commented on src/DataStructures/Tensor/CreateView.hpp
> +void create_view(
This should have a more descriptive name.  Something that mentions spacetime or similar.  Mentioning "view" is good, though.  The documentation should also mention the "view" nature.

2024-01-08 23:07 UTC, wthrowe commented on src/DataStructures/Tensor/CreateView.hpp
> +/// produce a spacetime tensor.
Is this only for vectors and covectors, or how does it handle mixed components?

2024-01-08 23:07 UTC, wthrowe commented on tests/Unit/DataStructures/Tensor/Test_CreateView.cpp
> +  create_view<SpatialDim, UpLo::Lo, Frame::Inertial>(
Can the compiler infer the template arguments?  If not, document what they mean.

2024-01-09 20:55 UTC, wthrowe commented on src/DataStructures/Tensor/CreateView.hpp
> +    if constexpr (std::is_same_v<DataType, DataVector>) {
One more thing: add a test of the DataVector version.

2024-01-11 16:15 UTC, ncorsobh commented on src/DataStructures/Tensor/CreateView.hpp
> +void create_view(
Do you think `combine_spacetime_view` is a better name or is it still not specific enough? Struggling to think of one that isn't too long. Happy to take suggestions too if you have a better idea.

2024-01-12 00:41 UTC, wthrowe commented on src/DataStructures/Tensor/CreateView.hpp
> +void create_view(
I think that's fine.

2024-01-16 19:23 UTC, wthrowe approved these changes
Looks good.  Squash.

2024-01-16 20:32 UTC, merged