Modify check_with_randome_values
sxs-collaboration/spectre pull request #5710
Opened 2024-01-19 20:03 UTC by jyoo1042

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-01-19 20:44 UTC, kidder reviewed
Please explain why you made this change

2024-01-19 20:45 UTC, kidder requested changes
and fix the spelling of the commit message

2024-01-19 21:19 UTC, jyoo1042 commented
Took the results out to make it more efficient.

2024-01-22 18:32 UTC, kidder approved these changes

2024-01-22 18:32 UTC, merged