Add IMEX ImplicitDenseOutput mutator
sxs-collaboration/spectre pull request #5711
Opened 2024-01-19 23:14 UTC by wthrowe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-01-21 21:23 UTC, nilsdeppe approved these changes

2024-01-23 23:42 UTC, wthrowe commented
Please hold off on merging.  There is a bug somewhere in the IMEX dense output code that needs tracking down.  I don't know if it in this PR or somewhere else.

2024-01-23 23:43 UTC, nilsdeppe requested changes
Waiting on Will. This way it can't get accidentally merged :)

2024-01-26 03:57 UTC, wthrowe commented
I haven't figured out what's going on yet, but I'm pretty much convinced that it's not related to this code, so I think we can merge this.  I've added a check that the dense output returned success and rebased on develop.

2024-01-26 17:07 UTC, nilsdeppe approved these changes

2024-01-26 17:07 UTC, merged