Add solution of Einstein's equations for a generic gauge plane wave
sxs-collaboration/spectre pull request #5712
Opened 2024-01-22 18:31 UTC by kidder

## Proposed changes

This adds a generic dynamic solution of Einstein's equations.  It should be useful for testing AMR.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-01-26 22:34 UTC, wthrowe requested changes

2024-01-26 22:34 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/GaugePlaneWave.hpp
> + * \gamma^{ij} & = 1 - \frac{H k^i k^j}{1 + H \omega^2},\\
`1` -> `\delta^{ij}`

2024-01-26 22:34 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Test_GaugePlaneWave.cpp
> +struct GaugePlaneWaveProxy : gr::Solutions::GaugePlaneWave<Dim> {
This appears to be the infrastructure for a python test, but there's no python test.  I don't know if you intended to write one or if this just got left in.

2024-02-02 21:36 UTC, wthrowe approved these changes
Looks good.  Squash.

2024-02-05 22:07 UTC, kidder commented
squashed

2024-02-05 23:09 UTC, merged