Add two elliptic AMR projectors
sxs-collaboration/spectre pull request #5721
Opened 2024-01-26 18:33 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-02-02 21:50 UTC, nilsvu commented
@kidder I made this PR very small now, and will open follow-ups later. Could you review this please?

2024-02-03 02:26 UTC, kidder requested changes
you should test the projectors

2024-02-03 02:26 UTC, kidder commented on .clang-tidy
> +# Access specifies can be useful to structure code,
specifies -> specifiers

2024-02-17 01:40 UTC, nilsvu commented
@kidder Updated and added a test for p-AMR in action. h-AMR isn't supported by the action-testing framework yet as we discussed, so I can enable that once we have added support.

Please ignore the first two commits (cherry-picked from #5163 and #5781).

2024-02-23 03:00 UTC, kidder submitted a review, later dismissed
needs a rebase

2024-02-23 18:52 UTC, nilsvu commented
Rebased. Thanks for reviewing.

2024-02-23 19:17 UTC, kidder approved these changes

2024-02-23 19:17 UTC, merged