Change return type of magnitude to Scalar
sxs-collaboration/spectre pull request #573
Opened 2018-03-04 23:01 UTC by osheamonn

## Proposed changes

Changes return type of magnitude from DataVector to Scalar

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

2018-03-05 21:28 UTC, nilsdeppe requested changes

2018-03-05 21:28 UTC, nilsdeppe commented on src/DataStructures/Tensor/EagerMath/Magnitude.hpp
> +    const Tensor<DataType, Symmetry<1>, tmpl::list<Index>>& tensor) noexcept {
I made a similar open question on Geoffrey's PR: I personally would find it better if the name `tensor` were changed to `vector`. I'm not sure if this should be part of the same PR as a separate commit or not.

2018-03-05 21:28 UTC, nilsdeppe commented on tests/Unit/DataStructures/TensorEagerMath/Test_Magnitude.cpp
> +    CHECK(get(magnitude(one_d_covector)) == two);
Should use `CHECK_ITERABLE` so that more digits are in the output if one values fails. (apply liberally throughout)

2018-03-06 15:11 UTC, geoffrey4444 commented on src/DataStructures/Tensor/EagerMath/Magnitude.hpp
> +    const Tensor<DataType, Symmetry<1>, tmpl::list<Index>>& tensor) noexcept {
I like vector for the name instead of tensor, and I made that change in dot_product.*pp

2018-03-06 15:30 UTC, osheamonn commented on src/DataStructures/Tensor/EagerMath/Magnitude.hpp
> +    const Tensor<DataType, Symmetry<1>, tmpl::list<Index>>& tensor) noexcept {
I agree. I'm going to go through the DotProduct pull request and apply any of the other relevant requested changes here too.

2018-03-06 22:11 UTC, kidder approved these changes

2018-03-07 02:16 UTC, nilsdeppe approved these changes

2018-03-07 02:16 UTC, merged