Support a different elastic material in each block
sxs-collaboration/spectre pull request #5737
Opened 2024-02-02 23:34 UTC by nilsvu

## Proposed changes

Getting code merged that's used in the thermal noise paper (https://arxiv.org/abs/2111.06893). This PR adds support for layered materials, but the DG scheme still needs an update to support this (next PR).

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-02-08 18:05 UTC, nilsdeppe requested changes

2024-02-08 18:05 UTC, nilsdeppe commented on src/Domain/Creators/ExpandOverBlocks.hpp
> +template <typename T>
Could we move the definitions to a `tpp` and instantiate STL types maybe in `ExpandOverBlocks.cpp`? We can then also instantiate specific other types in other places as necessary. I'd us to continue to reduce code in header files. In this case I worry a bit that it'll be transitively included in a decent number of places.

2024-02-08 18:05 UTC, nilsdeppe commented on src/Domain/Creators/ExpandOverBlocks.hpp
> +    std::vector<T> expanded{};
`Utilities/CloneUniquePtrs.hpp` has code to do this. Can you just use that?

2024-02-08 18:05 UTC, nilsdeppe commented on src/Domain/Creators/ExpandOverBlocks.hpp
> +      std::unordered_map<std::string, T> copy{};
Again, can we use `Utilities/CloneUniquePtrs.hpp`?

2024-02-08 18:05 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
>  #include "Utilities/ErrorHandling/Error.hpp"
I don't understand how this change allows observing anything per material layer. It just allows you to name `ObserveNorms` something else. Couldn't this be achieved with compute tags filtering on the layer?

This needs tests regardless, but I'm not sure this is the right solution to the problem. Maybe we can discuss in the tech call?

2024-02-08 18:05 UTC, nilsdeppe commented on src/Domain/Creators/BlockGroups.hpp
> +std::unordered_set<std::string> expand_block_groups(
maybe add `_to_block_names`? It isn't clear to me from the current name what it does, and while documented, the extra clarity seems worth it to me :shrug:

2024-02-08 18:05 UTC, nilsdeppe commented on src/Elliptic/Systems/Elasticity/Actions/InitializeConstitutiveRelation.hpp
> +// Distributed under the MIT License.
Are there tests for these?

2024-02-13 17:01 UTC, geoffrey4444 requested changes
Just one quick thing I saw so far…haven’t finished reviewing yet

2024-02-13 17:01 UTC, geoffrey4444 commented on .clang-tidy
> +# Access specifies can be useful to structure code,
specifies -> specifiers?

2024-02-13 17:34 UTC, geoffrey4444 requested changes
Maybe I missed it, but is there a unit test anywhere that actually uses different constitutive relations in different blocks? If not, would it be hard to add one>?

2024-02-26 22:41 UTC, nilsvu commented on src/ParallelAlgorithms/Events/ObserveNorms.hpp
>  #include "Utilities/ErrorHandling/Error.hpp"
As discussed in a meeting recently, yes, this only provides a name for the event in the input file. It's needed when you have multiple `ObserveNorms` events in the same executable (here you have one for norms over the full domain and one for norms over each material layer). I think passing along a label struct is consistent with other parts of the code where we do that, e.g. `Options::Auto<T, Label>`. I added some docs to explain.

2024-02-26 23:53 UTC, nilsvu commented on src/Domain/Creators/BlockGroups.hpp
> +std::unordered_set<std::string> expand_block_groups(
squashed this rename in

2024-02-26 23:54 UTC, nilsvu commented
I squashed in the split of ExpandOverBlocks into a tpp file, and added a test.

2024-02-29 17:06 UTC, nilsdeppe reviewed
LGTM, please squash!

2024-03-01 00:41 UTC, nilsvu commented
@geoffrey4444 do you want to take another look?

2024-03-01 15:14 UTC, geoffrey4444 approved these changes

2024-03-01 15:24 UTC, nilsdeppe approved these changes

2024-03-01 15:30 UTC, merged