Feature/make with random value
sxs-collaboration/spectre pull request #574
Opened 2018-03-05 03:55 UTC by kidder

## Proposed changes

Add a helper function for unit testing that fills a data structure with random values

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

2018-03-05 20:30 UTC, nilsdeppe requested changes

2018-03-05 20:30 UTC, nilsdeppe commented on tests/Unit/DataStructures/TestHelpers.hpp
> +    for (auto it = data.begin(); it != data.end(); ++it) {
why not use a range-based loop?

2018-03-05 20:30 UTC, nilsdeppe commented on tests/Unit/DataStructures/TestHelpers.hpp
> +    T& data, const gsl::not_null<UniformRandomBitGenerator*> generator,
Shouldn't this be taken as a `const gsl::not_null<T*>`? And then propagate that forward

2018-03-05 20:30 UTC, nilsdeppe commented on tests/Unit/DataStructures/TestHelpers.hpp
> +#include <cstddef>
what's being used from cstddef?

2018-03-05 20:30 UTC, nilsdeppe commented on tests/Unit/DataStructures/TestHelpers.hpp
> +#include <type_traits>
Should we only include our TypeTraits.hpp?

2018-03-05 20:30 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_MakeWithValue.cpp
> +  std::unordered_set<double> values;
Sorry, it's not clear to me what `values` is supposed to do. Could you explain? Thanks!

2018-03-05 21:13 UTC, kidder commented on tests/Unit/DataStructures/TestHelpers.hpp
> +#include <type_traits>
okay

2018-03-05 21:13 UTC, kidder commented on tests/Unit/DataStructures/TestHelpers.hpp
> +#include <cstddef>
`std::nullptr_t`

2018-03-05 21:13 UTC, kidder commented on tests/Unit/DataStructures/TestHelpers.hpp
> +R make_with_random_values(
`R` -> `ReturnType`

2018-03-05 21:13 UTC, kidder commented on tests/Unit/DataStructures/Test_MakeWithValue.cpp
> +  std::unordered_set<double> values;
values tests that you get unique random values (I'll add a comment)

2018-03-05 21:13 UTC, kidder commented on tests/Unit/DataStructures/Test_MakeWithValue.cpp
> +  const DataVector dv(5);
move to where it is used

2018-03-05 21:16 UTC, nilsdeppe commented on tests/Unit/DataStructures/TestHelpers.hpp
> +#include <cstddef>
Okay, thanks!

2018-03-06 03:36 UTC, nilsdeppe submitted a review, later dismissed
I'm happy for you to squash

2018-03-06 18:39 UTC, nilsdeppe approved these changes
@wthrowe could you look at this one as well?

2018-03-06 19:02 UTC, wthrowe approved these changes

2018-03-06 19:04 UTC, merged