Add mbot installation shell script
sxs-collaboration/spectre pull request #5750
Opened 2024-02-10 05:08 UTC by nilsdeppe

This compiles all the modules needed on mbot.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-02-12 16:46 UTC, nilsvu commented
I sure hope we can replace this sort of thing with Spack at some point :)

2024-02-16 19:23 UTC, markscheel reviewed
I tried running this on Frontera, and it dies with

```
help2man: can't get `--help' info from automake-1.16
Try `--no-discard-stderr' if option outputs to stderr
make: *** [doc/automake-1.16.1] Error 255
```

2024-02-16 19:23 UTC, markscheel commented on support/Environments/setup/mbot_install.sh
> +    echo "You must pass one argument to spectre_setup_modules, which"
spectre_setup_modules -> mbot_install

2024-02-27 22:09 UTC, markscheel commented on support/Environments/setup/mbot_install.sh
> +# GCC Begin
GCC End

2024-02-27 22:12 UTC, markscheel commented
I noticed (while running it on Expanse) that this script also installs things like emacs and tmux, and maybe other things that are of course useful but are not really spectre or spec dependencies.  Should there be a flag to control whether the script installs such "optional" things?

2024-02-28 03:04 UTC, markscheel commented
I tried running this on Expanse, starting with the standard modules loaded.  It chugged along for about 5 hours with no problem, and eventually died with the error
```
gcc -o bin/libxsmm_gemm_generator obj/intel64/libxsmm_generator_gemm_driver.o -L
/home/ux450022/software/spectre/libxsmm-1.16.1/lib/ -lxsmmgen \
        -Wl,--gc-sections -Wl,-z,relro,-z,now -lm -lrt -ldl -s -pthread
/tmp/cc6TTKi2.s: Assembler messages:
/tmp/cc6TTKi2.s:17249: Error: no such instruction: `vcvtne2ps2bf16 %zmm15,%zmm14,%zmm7'
/tmp/cc6TTKi2.s:17258: Error: no such instruction: `vcvtne2ps2bf16 %zmm1,%zmm2,%zmm0'
/tmp/cc6TTKi2.s:17267: Error: no such instruction: `vcvtne2ps2bf16 %zmm3,%zmm4,%zmm6'
                ...
[ ... many more lines like this... ]
                ...
/tmp/ccIQK6il.s:98827: Error: no such instruction: `vcvtne2ps2bf16 %zmm11,%zmm10,%zmm4'
/tmp/ccIQK6il.s:98831: Error: no such instruction: `vcvtne2ps2bf16 %zmm13,%zmm12,%zmm14'
make: [Makefile:782: obj/intel64/libxsmm_dnn_rnncell_forward.o] Error 1 (ignored)
--------------------------------------------------------------
In case of assembler error, perhaps the Binutils are outdated.
See https://github.com/hfp/libxsmm#outdated-binutils
--------------------------------------------------------------
make: *** [Makefile:783: obj/intel64/libxsmm_dnn_rnncell_forward.o] Error 1
```

2024-02-28 14:12 UTC, markscheel commented on support/Environments/setup/mbot_install.sh
> +    git clone git@github.com:UIUC-PPL/charm.git ${LOCATION}
Can this be cloned with https instead of ssh?  Fails if I don't have an ssh key.

2024-02-28 14:12 UTC, markscheel commented on support/Environments/setup/mbot_install.sh
> +    git clone git@github.com:UIUC-PPL/charm.git ${LOCATION}-tracing
Same clone problem.

2024-02-28 14:33 UTC, markscheel commented on support/Environments/setup/mbot_install.sh
> +    echo "charm version ${_CHARM_VERSION} already installed"
This should say spectre-python instead of charm.

2024-08-21 16:49 UTC, knelli2 commented
@nilsdeppe will rebase once @kidder is back

2025-02-18 01:12 UTC, kidder requested changes

2025-02-18 01:12 UTC, kidder commented on support/Environments/setup/mbot_install.sh
> +        # wget https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.19.0.tar.gz
remove or add comment explaining why it's commented out

2025-02-18 01:12 UTC, kidder commented on support/Environments/setup/mbot_install.sh
> +        # wget https://github.com/libffi/libffi/archive/refs/tags/v3.4.4.tar.gz
remove or add comment

2025-02-18 22:44 UTC, nilsdeppe commented
Done and squashed! Thanks for the reviews!

2025-02-19 21:35 UTC, kidder approved these changes

2025-02-19 21:36 UTC, merged