Add Rk3Pareschi IMEX time stepper
sxs-collaboration/spectre pull request #5760
Opened 2024-02-13 22:15 UTC by wthrowe

Note to @yoonso0-0: I've renamed the class since the last version I gave you.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-02-14 18:17 UTC, teukolsky commented on src/Time/TimeSteppers/Rk3Pareschi.cpp
> +      {0.0, 0.0, 0.0, 0.0, 1.0},
It's probably better to use a non-zero value of x so the error estimate samples the y-values across the interval. x=1/4 looks good. Using only the last value is probably not robust. This is the reason, by the way, that Dormand-Prince is 853 and not, say 87 or 86. These 'simpler' error estimates turned out not to sample the interval very well.

2024-02-27 16:50 UTC, nilsdeppe requested changes
LGTM, one small question that might be a typo. Please squash and rebase immediately :)

2024-02-27 16:50 UTC, nilsdeppe commented on src/Time/TimeSteppers/Rk3Pareschi.hpp
> + * \brief A fourth-order Runge-Kutta method with IMEX support.
fourth -> third?

2024-02-28 21:24 UTC, wthrowe commented on src/Time/TimeSteppers/Rk3Pareschi.hpp
> + * \brief A fourth-order Runge-Kutta method with IMEX support.
Yep.  Fixed.

2024-02-28 21:25 UTC, nilsdeppe approved these changes

2024-02-29 16:36 UTC, nilsdeppe commented
CI failure is unrelated.

2024-02-29 16:36 UTC, merged