Prevent NumGridPointsAndGridSpacing element dist when using GTS
sxs-collaboration/spectre pull request #5769
Opened 2024-02-15 19:19 UTC by knelli2

## Proposed changes

Also prevent using NumGridPointsAndGridSpacing in the elliptic code as well.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-02-15 22:09 UTC, wthrowe requested changes

2024-02-15 22:09 UTC, wthrowe commented on src/Domain/ElementDistribution.hpp
> +    uses_lts<Metavariables, has_local_time_stepping_v<Metavariables>>::value;
This is `CREATE_GET_STATIC_MEMBER_VARIABLE_OR_DEFAULT`.

2024-02-15 22:09 UTC, wthrowe commented on src/Domain/ElementDistribution.hpp
> +            "When using global time stepping, you cannot use "
"using GTS" -> "not using LTS" to include elliptic.

2024-02-15 22:09 UTC, wthrowe commented on src/Domain/Tags/ElementDistribution.hpp
> +/// NumGridPointsAndGridSpacing when using GTS, an error will occur.
Again, GTS -> not LTS

2024-02-17 00:55 UTC, knelli2 commented
I squashed directly

2024-02-17 17:44 UTC, wthrowe approved these changes

2024-02-17 17:44 UTC, merged