Added DataOnSlice with test.
sxs-collaboration/spectre pull request #58
Opened 2017-06-26 22:04 UTC by osheamonn

2017-06-26 22:14 UTC, nilsdeppe requested changes

2017-06-26 22:14 UTC, nilsdeppe commented on src/DataStructures/VariablesHelpers.hpp
> +class Index;
don't need the forward declaration since we are including the header

2017-06-26 22:14 UTC, nilsdeppe commented on src/DataStructures/VariablesHelpers.hpp
> + *  \brief Slices the data within evolved_vars to a codimension 1 slice in the
Should we rename `evolved_vars` to `vars`?

2017-06-26 22:14 UTC, nilsdeppe commented on src/DataStructures/VariablesHelpers.hpp
> + * sliced_dim dimension. Which surface to slice to is determined by slice_point.
`sliced_dim` with ticks, same for `slice_point`

2017-06-26 22:14 UTC, nilsdeppe commented on src/DataStructures/VariablesHelpers.hpp
> +      *(interface_vars_data + si.slice_offset() + i * interface_grid_points) =
we can just use `interface_vars_data[...]`

2017-06-26 22:21 UTC, fmahebert commented on src/DataStructures/VariablesHelpers.hpp
> + * sliced_dim dimension. Which surface to slice to is determined by slice_point.
This is highly subjective of course... but I think the brief would be clearer if phrased more like this:
Slices the data within evolved_vars to a codimension 1 slice. The slice has a constant grid coordinate in direction `sliced_dim`, and slices the volume through grid point `slice_point` of this coordinate.

2017-06-26 22:22 UTC, fmahebert commented on src/DataStructures/VariablesHelpers.hpp
> + * sliced_dim dimension. Which surface to slice to is determined by slice_point.
(maybe that's too long for a brief....)

2017-06-26 23:34 UTC, nilsdeppe commented on src/DataStructures/VariablesHelpers.hpp
> + * sliced_dim dimension. Which surface to slice to is determined by slice_point.
Yea, it would probably only show the first sentence in Doxygen (though I like the wording)

2017-06-26 23:40 UTC, osheamonn commented on src/DataStructures/VariablesHelpers.hpp
> + * sliced_dim dimension. Which surface to slice to is determined by slice_point.
Yeah it could be clearer, what Francois said sounds good so I'll just use that.

2017-06-27 02:30 UTC, nilsdeppe commented on src/DataStructures/VariablesHelpers.hpp
> +                                const size_t& sliced_dim,
don't need to take fundamentals by const (this is a residual thing from BitBucket, will probably have a lot of these)

2017-06-27 02:30 UTC, nilsdeppe commented on src/DataStructures/VariablesHelpers.hpp
> +template <std::size_t VolumeDim, typename TagsLs>
Did you want this to be `TagsList` instead?

2017-06-27 14:43 UTC, nilsdeppe approved these changes

2017-06-27 14:43 UTC, merged