Replace Kerr-Schild with Spherical-Kerr-Schild for FishboneMoncriefDisk
sxs-collaboration/spectre pull request #5800
Opened 2024-02-23 18:13 UTC by jyoo1042

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-02-23 19:05 UTC, wthrowe requested changes
I'm confused about what is going on with the mass and spin.  It seems that some places are being hardcoded to 1 and 0, but not all places.

2024-02-23 19:05 UTC, wthrowe commented on src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
> +          error_tags, dt_tags,
Observing the time derivatives is a bad idea.  You don't get the current value, but rather whatever the last RHS evaluation was, which was probably at a different time and possibly on a substep.

2024-02-23 19:05 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/SphericalKerrSchild.hpp
> +  // Overload and call the second one.
I don't understand this comment.

2024-02-23 19:05 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedFmDisk.cpp
> +          sqrt(r_squared + square(fm_disk_.bh_spin_a_)) / radius;
Drop spin term?  You seem to be changing it to zero everywhere else.

2024-02-23 19:05 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedFmDisk.cpp
> +            get_element(magnetic_field_ks.get(i), s);
This doesn't need to be done pointwise.

2024-02-23 19:05 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedFmDisk.cpp
> +  const double bh_mass = 1.;
Revert?  Drop comment?

2024-02-23 19:05 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedFmDisk.py
> +        # normalization = 1.3686080052126354811292686 # 255 after the change.
"the change"?

2024-02-23 19:05 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedFmDisk.cpp
> +  //   // correctly forwards to the background solution of the base class.
Change back.

2024-02-23 19:05 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedFmDisk.cpp
> +    CHECK_THROWS_WITH(
Something went wrong with the formatting in this section.  The original version looked correct.

2024-02-23 19:05 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
> +                       make_not_null(&vars->sph_kerr_schild_cache)))
Compute this outside the loop.  I think it can even go outside the lambda.

2024-02-23 19:05 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
> +                              make_not_null(&vars->sph_kerr_schild_cache)))),
Same as for the shift.

2024-02-27 19:42 UTC, jyoo1042 commented on src/Evolution/Executables/GrMhd/ValenciaDivClean/EvolveValenciaDivClean.hpp
> +          error_tags, dt_tags,
removed this commit.

2024-02-27 19:43 UTC, jyoo1042 commented on src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedFmDisk.cpp
> +            get_element(magnetic_field_ks.get(i), s);
changed it.

2024-02-27 19:49 UTC, jyoo1042 commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedFmDisk.cpp
> +    CHECK_THROWS_WITH(
Are you talking about the extra indentation?

2024-02-27 23:06 UTC, wthrowe requested changes

2024-02-27 23:06 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticData/GrMhd/MagnetizedFmDisk.cpp
> +          sqrt(r_squared + square(fm_disk_.bh_spin_a_)) / radius;
This is correct.  I was confused before.

2024-02-27 23:06 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
> +                       make_not_null(&vars->sph_kerr_schild_cache)))
Ping.  Also move `inv_jacobians`, now that I look harder.

2024-02-27 23:06 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
> +                              make_not_null(&vars->sph_kerr_schild_cache)))),
Ping.

2024-02-27 23:06 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedFmDisk.cpp
> +    CHECK_THROWS_WITH(
Yes.

2024-02-28 15:25 UTC, jyoo1042 commented on src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
> +                              make_not_null(&vars->sph_kerr_schild_cache)))),
done.

2024-02-28 15:25 UTC, jyoo1042 commented on src/PointwiseFunctions/AnalyticSolutions/RelativisticEuler/FishboneMoncriefDisk.cpp
> +                       make_not_null(&vars->sph_kerr_schild_cache)))
done.

2024-02-28 15:25 UTC, jyoo1042 commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedFmDisk.cpp
> +    CHECK_THROWS_WITH(
done.

2024-02-28 15:26 UTC, jyoo1042 commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedFmDisk.cpp
> +  const double bh_mass = 1.;
dropped the comment and changed the mass from 1.

2024-02-28 19:22 UTC, wthrowe approved these changes
Please push fixup commits in the future.

2024-02-28 19:23 UTC, merged