Add InverseJacobianInertialToFluidCompute
sxs-collaboration/spectre pull request #5811
Opened 2024-02-27 23:15 UTC by ffoucart

## Proposed changes

Implement a ComputeTag that calculates the inverse jacobian of the map between the inertial frame and an orthonormal tetrad comoving with the fluid.

### Upgrade instructions

NA

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

I needed to add a new frame (Frame::Fluid) -- should it be in the same file as the other frames, or defined separately in the MC code?

2024-02-28 18:13 UTC, ffoucart commented
Changed the accuracy required in the test; the default worked in Release mode on wheeler (at least every tie I tried it) but consistently failed in Debug mode and for many of the tests.

2024-02-28 19:53 UTC, wthrowe requested changes

2024-02-28 19:53 UTC, wthrowe commented on src/Evolution/Particles/MonteCarlo/InverseJacobianInertialToFluidCompute.hpp
> +                const tnsr::I<DataVector, 3>& spatial_velocity,
Fix formatting.

2024-02-28 19:53 UTC, wthrowe commented on src/Evolution/Particles/MonteCarlo/InverseJacobianInertialToFluidCompute.cpp
> +  // Then, the other members of the tetrad are constructed using Gram-Shmidt
"Schmidt"

2024-02-28 19:53 UTC, wthrowe commented on src/Evolution/Particles/MonteCarlo/InverseJacobianInertialToFluidCompute.cpp
> +                                          temp_dot_product, temp_dot_product};
Instead of using this temporary, write the result directly into the `inv_jacobian` matrix.  That saves four memory allocations, which is good for both speed and memory use.

2024-02-28 19:53 UTC, wthrowe commented on src/Evolution/Particles/MonteCarlo/InverseJacobianInertialToFluidCompute.cpp
> +  DataVector temp_dot_product = get(lapse) * 0.0;
```c++
auto temp_dot_product = make_with_value<DataVector>(lapse, 0.0);
```

2024-02-29 20:25 UTC, wthrowe requested changes
Other changes look good.  Squash, including this last request.

2024-02-29 20:25 UTC, wthrowe commented on src/Evolution/Particles/MonteCarlo/InverseJacobianInertialToFluidCompute.cpp
> +      inv_jacobian->get(i, d) = make_with_value<DataVector>(lapse, 0.0);
Do `set_number_of_grid_points(&inv_jacobian->get(i, d), lapse)` (from `Utilities/SetNumberOfGridPoints.hpp`) and then `= 0.0` (or the `?:` expression you had before).  This avoids a DataVector allocation.  Might need a `make_not_null`.

2024-02-29 20:57 UTC, ffoucart commented
Squashed with last requested change.

2024-02-29 21:32 UTC, wthrowe approved these changes

2024-03-01 01:03 UTC, wthrowe requested changes
Test failed in CI:
```
2024-02-29T23:23:33.9252167Z Unit.Evolution.Particles.MonteCarlo.InverseJacobianInertialToFluid
2024-02-29T23:23:33.9253216Z -------------------------------------------------------------------------------
2024-02-29T23:23:33.9255545Z ../../../../../../tests/Unit/Evolution/Particles/MonteCarlo/Test_InverseJacobianInertialToFluid.cpp:22
2024-02-29T23:23:33.9256689Z ...............................................................................
2024-02-29T23:23:33.9257210Z 
2024-02-29T23:23:33.9257566Z ../../../../../../tests/Unit/Framework/TestingFramework.hpp:116: FAILED:
2024-02-29T23:23:33.9258285Z   CHECK( a == appx(b) )
2024-02-29T23:23:33.9258704Z with expansion:
2024-02-29T23:23:33.9259514Z   -0.00000000000212888 == Approx( 0.0 )
2024-02-29T23:23:33.9260039Z with messages:
2024-02-29T23:23:33.9260650Z   Seed is: 2708572239 from ../../../../../../tests/Unit/Evolution/Particles/
2024-02-29T23:23:33.9261452Z   MonteCarlo/Test_InverseJacobianInertialToFluid.cpp:26
2024-02-29T23:23:33.9262207Z   ../../../../../../tests/Unit/Evolution/Particles/MonteCarlo/
2024-02-29T23:23:33.9263027Z   Test_InverseJacobianInertialToFluid.cpp:88: dot_product ==
2024-02-29T23:23:33.9263727Z   expected_dot_product
2024-02-29T23:23:33.9264480Z   a := (-1.55761e-14,3.35154e-17,1.85832e-16,-1.83013e-16,-2.12888e-12)
2024-02-29T23:23:33.9265165Z   b := (0,0,0,0,0)
2024-02-29T23:23:33.9265402Z 
2024-02-29T23:23:33.9265916Z 0.001 s: Unit.Evolution.Particles.MonteCarlo.InverseJacobianInertialToFluid
2024-02-29T23:23:33.9266854Z ===============================================================================
2024-02-29T23:23:33.9267485Z test cases:   1 |   0 passed | 1 failed
2024-02-29T23:23:33.9268385Z assertions: 127 | 126 passed | 1 failed
```

2024-03-01 04:16 UTC, ffoucart commented
Is there a way to force the use of that seed in the test locally?
I could just raise the tolerance a bit (it fails the comparison by 2e-12 when the tolerance is 1e-12), but unless it's somehow using weird random values for the metric/velocity, I'd expect higher accuracy.

2024-03-01 19:09 UTC, wthrowe commented
```
2024-02-29T23:23:33.9260650Z   Seed is: 2708572239 from ../../../../../../tests/Unit/Evolution/Particles/
2024-02-29T23:23:33.9261452Z   MonteCarlo/Test_InverseJacobianInertialToFluid.cpp:26
```
That line should have a `MAKE_GENERATOR` call on it.  That macro takes an optional second argument of the seed.

2024-03-01 19:29 UTC, ffoucart commented
I changed the epsilon from 1e-12 to 5e-12.
The failing point had a Lorentz factor of 20.8. The maximum allowed by the RNG is 21.1, and it makes sense that the calculation would loose accuracy for high Lorentz factors so... in my view it's ok for now.

2024-03-05 01:15 UTC, wthrowe approved these changes
OK, sounds good.

2024-03-05 01:15 UTC, merged