Skeleton of full MC time step
sxs-collaboration/spectre pull request #5820
Opened 2024-03-02 02:16 UTC by ffoucart

## Proposed changes

Lays down the main steps required to evolve Monte-Carlo packets within a given element, once we include absorption and elastic scattering. The PR does not actually change the behavior of the code so far (most steps are placeholders that need to be implemented), but it serves to remind me of what needs to be done to match the SpEC algorithm.

### Upgrade instructions

NA

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-03-08 00:12 UTC, nilsdeppe requested changes, later dismissed
Looks good! A few minor suggestions. Please squash right away :)

Reviewers: @kidder @nilsdeppe

2024-03-08 00:12 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +void compute_opacities(double& absorption_opacity, double& scattering_opacity,
`double&` -> `const gsl::not_null<double*>` (but not the `const double&` below)

2024-03-08 00:12 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +void scatter_packet(gsl::not_null<Packet*> /*packet*/) {
`const gsl...`

2024-03-08 00:12 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +void diffuse_packet(gsl::not_null<Packet*> /*packet*/,
`const gsl...`

2024-03-08 00:12 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +      dt_cell_check = 10.0 * dt_end_step;
Could you add a C++ code comment where the `10.0 * X` numbers come from? Specifically, why 10? Even if the answer is "it seems to work well in practice," just so that if we edit this file in the future we have some guidance for these numbers

2024-03-08 00:12 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +      // Absorption comes first; delete the packet
Could you elaborate just to be extra clear:
```cpp
// Handle absorption before emission
//
// To remove this packet we swap the current and last packet,
// then pop the last packet from the end of the vector of packets.
// We then decrease the counter `p` so that we check the packet
// from the end that we just swapped into the current slot.
//
// Note: This works fine even if p==0 since unsigned ints (size_t)
// wrap at zero.
```

2024-03-08 00:12 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +        (*packets)[p] = (*packets)[n_packets - 1];
`std::swap((*packets)[p], (*packets)[n_packets - 1]);`

2024-03-08 00:12 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +        if (scattering_optical_depth > 3.0) {
Can you expand on the above comment why the number 3? Even if it's just "in practice this works well" that would be good to have noted

2024-03-08 17:15 UTC, ffoucart commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +      dt_cell_check = 10.0 * dt_end_step;
This one is part of the "TO DO"; this is not what we want, but depends on the opacities which I have not implemented yet. For now, it just needs to be > dt_end_step

2024-03-08 17:17 UTC, ffoucart commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +        if (scattering_optical_depth > 3.0) {
I'll put a comment here; practically this is a parameter of the "diffusion" method for high-scattering region, which will be coded as a const member of a struct in a coming PR (the next one to be submitted)

2024-03-08 17:57 UTC, ffoucart commented
Addressed comments and squashed.

2024-03-09 02:16 UTC, kidder approved these changes

2024-03-09 02:17 UTC, merged