Fix OptimizerHacks for clang 17
sxs-collaboration/spectre pull request #5823
Opened 2024-03-04 15:02 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-03-04 19:54 UTC, knelli2 requested changes

2024-03-04 19:54 UTC, knelli2 commented on src/Utilities/OptimizerHacks.cpp
>  // clang v15+ fails to instantiate the following std library templates if
Update code comment as well?

2024-03-04 20:57 UTC, wthrowe requested changes
It works with clang 16 without the hack now, so this is probably a change in SpECTRE, not a change in clang.  I'd delete the whole section and see if it breaks for anyone.

2024-03-04 22:50 UTC, nilsdeppe commented
Okay, deleted the code block. Thanks for reviewing!

2024-03-04 22:54 UTC, wthrowe approved these changes

2024-03-04 22:59 UTC, kidder commented
works for me

2024-03-05 05:26 UTC, knelli2 approved these changes
Good enough for me

2024-03-05 05:26 UTC, merged