Scatter packet
sxs-collaboration/spectre pull request #5827
Opened 2024-03-04 21:51 UTC by ffoucart

## Proposed changes

Add function to scatter packets at constant fluid-frame energy

### Upgrade instructions

NA

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-03-04 21:52 UTC, ffoucart commented
Built on top of #5820

2024-03-08 00:33 UTC, nilsdeppe requested changes

2024-03-08 00:33 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/EvolveMonteCarloPackets.cpp
> +    std::mt19937& random_number_generator, const Mesh<3>& mesh,
can you make the `random_number_generator` a `gsl::not_null<std::mt19937*>`?

2024-03-08 00:33 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/ScatteringMonteCarlo.hpp
> +// Elastic scattering, which is just redrawing the momentum from
`///` or `/*!` for doxygen comment

2024-03-08 00:33 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/ScatteringMonteCarlo.cpp
> +#include "ScatteringMonteCarlo.hpp"
`#include "Evolution/Particles/MonteCarlo/ScatteringMonteCarlo.hpp"`

2024-03-08 00:33 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/ScatteringMonteCarlo.cpp
> +    gsl::not_null<Packet*> packet, std::mt19937& random_number_generator,
`const gsl`, make `std::mt...` a `const gsl::not_null<std::mt...*>`

2024-03-08 00:33 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/ScatteringMonteCarlo.cpp
> +  std::array<double, 4> four_momentum_fluid{fluid_frame_energy, 0.0, 0.0, 0.0};
I would move this down to line 28 and do:
```cpp
const std::array<double, 4> four_momentum_fluid{fluid_frame_energy,
sin_theta * cos(phi) * fluid_frame_energy,
sin_theta * sin(phi) * fluid_frame_energy,
cos_theta * fluid_frame_energy};
```
(pardon my poor indentation)

2024-03-08 00:33 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/ScatteringMonteCarlo.cpp
> +    packet->momentum.get(d) = (-1.0) * gsl::at(four_momentum_fluid, 0) *
I think `-gsl::at(four_momentum_fluid, 0)` should compile fine without the multiplication

2024-03-11 22:51 UTC, ffoucart commented
Last commit did NOT address code review comments; only rebased against latest branch (I pushed the wrong branch...)

2024-03-12 04:35 UTC, ffoucart commented
Ok, now the last commit is meant to address code review...

2024-03-14 21:42 UTC, kidder reviewed
you can squash into a single commit

2024-03-14 23:16 UTC, ffoucart commented
Large number of seg-faulting tests in clang 14 DEBUG... is this a known issue?

2024-03-15 01:21 UTC, wthrowe commented
> Large number of seg-faulting tests in clang 14 DEBUG... is this a known issue?

Yes.  Things are going wrong with that configuration on a number of PRs.  Don't know why yet.

2024-03-15 18:43 UTC, nilsdeppe approved these changes

2024-03-15 18:43 UTC, merged