Move EventsAndDenseTriggers lib to ParallelAlgorithms
sxs-collaboration/spectre pull request #5844
Opened 2024-03-13 00:53 UTC by knelli2

## Proposed changes

EaDT mirrors EaT very closely so it makes sense that these two should be side-by-side in the directory tree. Unfortunately we can't combine EaDT and EaT because 1) The elliptic code depends on EaT 2) EaDT depends on `Time` 3)  We don't want elliptic code to depend on `Time`. Therefore they have to stay separate. I believe this was the original reason it was put in evolution. Also, I will be using EaDT in my interpolation framework changes, and it felt wrong to include files from the evolution directory in the ParallelAlgorithms directory.

This also moves EaDT out of the `evolution` namespace as well, similar to EaT.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-03-13 19:00 UTC, wthrowe requested changes

2024-03-13 19:00 UTC, wthrowe commented on src/IO/Observer/CMakeLists.txt
> +  EventsAndDenseTriggers
Alphabetize.

2024-03-13 19:00 UTC, wthrowe commented on tests/Unit/ParallelAlgorithms/LinearSolver/Gmres/CMakeLists.txt
> +  LinearSolverHelpers
Alphabetize.

2024-03-13 19:00 UTC, wthrowe commented on src/Time/Tags/TimeAndPrevious.hpp
> +namespace Tags {
[optional] Merge the duplicate `Tags` forward-declaration namespaces.  They occur in other files as well.

2024-03-13 22:17 UTC, knelli2 commented
Squashed in the changes because there were only a couple

2024-03-15 21:55 UTC, wthrowe approved these changes

2024-03-15 21:56 UTC, merged