Add scalar self force and derivatives calculations
sxs-collaboration/spectre pull request #5869
Opened 2024-03-19 13:55 UTC by nikwit

These quantities are mostly longer derivatives computed from applying the chain rule several times. They are needed for the computing the acceleration terms of the puncture  field.

2024-04-15 18:09 UTC, knelli2 requested changes
Just some dox things. Please rebase and squash

2024-04-15 18:09 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SelfForce.hpp
> + */
Can you reference the `self_force_per_mass` function in the docs so it's clear what we are doing the chain rule on?

2024-04-15 18:09 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SelfForce.hpp
> + * by applying the chain rule.
Same here

2024-04-15 18:09 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SelfForce.hpp
> + * $\frac{d}{dt}u^\beta \nabla_\beta f^\alpha$.
Reference `Du_self_force_per_mass` here as well. Also, you have the word "along" inside the tex. Move that outside please.

2024-04-19 21:14 UTC, nikwit commented
@knelli2 done, thanks for the review!

2024-04-19 21:15 UTC, knelli2 approved these changes

2024-04-19 21:16 UTC, merged