Add calculation and use of opacities in MC
sxs-collaboration/spectre pull request #5870
Opened 2024-03-19 16:44 UTC by ffoucart

## Proposed changes

Add function to interpolate opacities from discrete values at given fluid energies
Add use of opacities to compute time to next scattering / absorption event
Template evolve_packets on number of species/energy group
Move function evolving packets along geodesic out of detail namespace
Split test of packet and packet evolution
Add test of opacity calculation

### Upgrade instructions

NA

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-03-19 16:50 UTC, ffoucart commented
Note: in the `evolve_packets `function, the only real changes (besides moving the function to the TemplatedLocalFunctions struct) are:
- Modified input variables (add opacities and energy bins)
- Create rng for uniform distribution on L103
- Calculate and use absorption/scattering opacities (L145-172 and L222)
- Add GR corrections to opacity on L207
- Add comments on work needed for GW on L257 and above, and avoid changing cell index mid time step (as in SpEC)
Similarly, `Test_EvolvePackets `is not new, but just moved out of `Test_Packet`

On the other hand, `interpolate_opacities_at_fluid_energy` and `Test_InterpolateOpacities` are new.

2024-03-19 16:52 UTC, ffoucart commented
There will certainly be some conflicts between this and #5851 , but nothing too hard to handle I think. Once those two PRs are in, the main local MC functions should be complete (emit_packets and evolve_packets).

2024-04-15 21:13 UTC, kidder requested changes
please provide a `fixup` commit with your changes

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
> +   * following the methods of Foucart+ 2021 (ApJ 920 82).
Please add the INSPIRE bibtex entry for this paper into `docs/References.bib` and then in the documentation here use `\cite Foucart:2021mcb`

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
> +      const double& final_time, const Mesh<3>& mesh,
`double final_time`

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
> +      const double& fluid_frame_energy, const size_t& species,
`double fluid_frame_energy, size_t species,`

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
> +      const size_t& index,
`size_t index`

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
> +  // when kappa = opacity_floor
kappa or log(kappa) = opacity_floor?

2024-04-15 21:13 UTC, kidder commented on tests/Unit/Evolution/Particles/MonteCarlo/CMakeLists.txt
> +  Test_EvolvePackets.cpp
These should be in alphabetical order

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +        const double& fluid_frame_energy, const size_t& species,
`const double fluid_frame_energy, const size_t species`

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +        const size_t& index,
const size_t index

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +  if (fluid_frame_energy <= gsl::at(energy_at_bin_center, 0)) {
Start with `const auto upper_bracket = std::lower_bound(energy_at_bin_center.begin(), energy_at_bin_center.end(), fluid_frame_energy);`.    This gives an iterator to the first element of `energy_at_bin_center` that is <= `fluid_frame_energy` (and scales logarithmically with the number of EnergyBins).

Then the first if checks `if (upper_bracket == energy_at_bin_center.begin())`

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +    if (fluid_frame_energy >= gsl::at(energy_at_bin_center, EnergyBins - 1)) {
check here `if(upper_bracket == energy_at_bin_center.end())`

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +      }
replace these three lines with
```
const auto lower_bracket = std::prev(upper_bracket);
const size_t lower_index = std::distance(energy_at_bin_center.begin(), lower_bracket);
const size_t upper_index = lower_index + 1;
```

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +      *absorption_opacity_packet =
and in the next two equations, replace `ne-1` with `lower_index` and `ne` with `upper_index`

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +    const double& final_time, const Mesh<3>& mesh,
const double final_time

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +      // with eps used to avoid NaNs in case the rng draws a 0.
I think you can remove the comments about eps since the rng can't draw a zero.

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +            // To do once we have opacities: calculate dt_scattering
remove this comment?

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePackets.cpp
>      const gsl::not_null<Packet*> packet, const double& time_step,
const double time_step

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePackets.hpp
> +    gsl::not_null<Packet*> packet, const double& time_step,
double time_step

2024-04-15 21:13 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/CMakeLists.txt
>    Packet.hpp
This list should be alphabetical

2024-04-16 13:51 UTC, ffoucart commented
@kidder I think this commit addresses all code review comments, but let me know if that's not what you had in mind...

2024-04-16 15:35 UTC, kidder requested changes
Looks good; just a couple of `const` to insert which you can do when squashing the fixup

2024-04-16 15:35 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePackets.cpp
> +    const gsl::not_null<Packet*> packet, double time_step,
this should be `const double time_step`. For function arguments of type double, int, size_t that are constant, a function declaration in a header file should omit the `const`, but the definition should have the `const`

2024-04-16 15:35 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/EvolvePacketsInElement.tpp
> +        double fluid_frame_energy, size_t species,
put the `const` back for these 3 arguments

2024-04-16 16:34 UTC, ffoucart commented
Sounds good; I added the const back and squashed everything...

2024-04-16 16:35 UTC, kidder approved these changes

2024-04-16 17:56 UTC, merged