Add pretty-printer for Variables, VectorImpls, gsl::span, Tensor for GDB
sxs-collaboration/spectre pull request #5879
Opened 2024-03-21 17:37 UTC by nilsdeppe

## Proposed changes

Allows GDB to print some of our data structures in a format that's easier to read. For example, currently we print a `gsl::span` and `DataVector` as:

```
 $1 = {static extent = <optimized out>, storage_ = {<gsl::detail::extent_type<-1l>> = {size_ = 2},
 data_ = 0x7fffef622020}}
 $2 = {<VectorImpl<double, DataVector, 0ul>> = {<blaze::CustomVector<double, blaze::unaligned, blaze::unpadded, false, blaze::GroupTag<0ul>, DataVector>> = {<blaze::DenseVector<blaze::CustomVector<double, blaze::unaligned, blaze::unpadde\
 d, false, blaze::GroupTag<0ul>, DataVector>, false>> = {<blaze::Vector<blaze::CustomVector<double, blaze::unaligned, blaze::unpadded, false, blaze::GroupTag<0ul>, DataVector>, false>> = {
 static transposeFlag = false}, <No data fields>}, static simdEnabled = <optimized out>,
 static smpAssignable = <optimized out>, static SIMDSIZE = <optimized out>, size_ = 2,
 v_ = 0x7fffef622020}, <MarkAsVectorImpl> = {<No data fields>}, static transpose_flag = false,
 static static_size = <optimized out>, owned_data_ = std::unique_ptr<double []> = {get() = 0x7fffef622020},
     static_owned_data_ = {_M_elems = {<No data fields>}}, owning_ = true}, <No data fields>}
```

With the changes this becomes:

```
$1 = gsl::span<double> size: 2 values  = {10, 10}
$2 = DataVector owning: true size: 2 values  = {10, 10}
```

Variables are printed as:

```
 $1 = Variables: (true,2,11x2)  = {[hydro::Tags::RestMassDensity<DataVector>] = Tensor = {
 [] = DataVector owning: false size: 2 values  = {10, 10}},
 [gr::Tags::SpacetimeMetric<DataVector, 3ul, Frame::Inertial>] = Tensor = {
 [tt] = DataVector owning: false size: 2 values  = {10, 10},
 [xt] = DataVector owning: false size: 2 values  = {10, 10},
 [yt] = DataVector owning: false size: 2 values  = {10, 10},
 [zt] = DataVector owning: false size: 2 values  = {10, 10},
 [xx] = DataVector owning: false size: 2 values  = {10, 10},
 [yx] = DataVector owning: false size: 2 values  = {10, 10},
 [zx] = DataVector owning: false size: 2 values  = {10, 10},
 [yy] = DataVector owning: false size: 2 values  = {10, 10},
 [zy] = DataVector owning: false size: 2 values  = {10, 10},
 [zz] = DataVector owning: false size: 2 values  = {10, 10}}}
```

Note: You will need to add

```
add-auto-load-safe-path /path/to/spectre/
```

to your `~/.gdbinit` file. GDB will yell at you that you are trying to load an untrusted file otherwise.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-03-28 18:00 UTC, wthrowe requested changes
This is a very nice improvement to debugging.

I found one edge case that breaks, but it's not a vary important one so up to you what do do about it.

2024-03-28 18:00 UTC, wthrowe commented on tools/SpectrePrettyPrinters.py
> +    "Print a VectorImpl, including"
Needs more or fewer words.

2024-03-28 18:00 UTC, wthrowe commented on tools/SpectrePrettyPrinters.py
> +            + str(self.val["owning_"])
Trying to print a Variables with no tags gives "Python Exception <class 'gdb.error'>: There is no member or method named owning_."  I don't consider this critical, since there's no data to print in that case, but if it's easy to avoid that would be nice.

2024-04-02 01:00 UTC, nilsdeppe commented
I rebased and squashed in fixes for the two requests. Thanks for the review!

2024-04-02 20:00 UTC, wthrowe approved these changes

2024-04-02 20:01 UTC, merged