Fix a bug in Equilibrium3D EoS
sxs-collaboration/spectre pull request #5882
Opened 2024-03-22 22:54 UTC by isaaclegred

## Proposed changes

There was a "bug" (a mistake) in the previous version of the sound speed calculation involved in the promotion of 2-d to 3-d EoSs. The previous version *may* have been right but if it was I have no idea why.    Essentially the wrong variable was being held constant in a partial derivative.  I have:

1.  Added docs the EoS class to explicitly clarify what needs to be computed in terms of variables that we use elsewhere 
2. Fixed the thing that was being computed incorrectly, it is now computed correctly
3.  Changed the test to use an `IdealFluid` EoS where the sound speed can be computed "by hand"

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

Someone should probably check the math in the docs, (thermodynamics is hard :( )

2024-03-27 21:35 UTC, nilsdeppe requested changes
Thanks for doing this! A few comments on the documentation that you can squash directly :)

2024-03-27 21:35 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
> +   * \frac{\partial p}{\rho} |_{e, Y_e} \neq \chi \equiv \frac{\partial
Should the `\rho` in the denominator be `\partial \rho` (also on the next line)? Also in the first equation above

2024-03-27 21:35 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
> +   * as defined in the 2-d EoS above. By definition `
remove the tick at the end of the line?

2024-03-27 21:35 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
> +   * \frac{\partial p}{\rho} |_{e, Y_e} = \frac{\partial e}{\partial
Same about `\partial \rho`

2024-03-27 21:35 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
> +   * by using \f$ \frac{\pd e}{\pd \epsilon}|_{\rho, Y_e} = 1 \f$
tex is complaining that `\pd` is undefined

2024-03-27 21:35 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
> +   * \frac{1}{\rho} \frac{\partial p}{\partial epsilon}|_{\rho, Y_e} \left(
`epsilon` -> `\epsilon`

2024-03-27 21:35 UTC, nilsdeppe commented on src/PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp
> +   * \frac{\rho}{h}\frac{\partial p}{\rho} |_{\epsilon, Y_e} +
Same about `\partial \rho`

2024-04-01 15:38 UTC, isaaclegred commented
@nilsdeppe this is updated when you get the chance!

2024-04-01 15:41 UTC, nilsdeppe approved these changes
Awesome! Thank you very much for doing this :D

2024-04-01 15:41 UTC, merged