Add hydro coupling bookkeeping to emission function in MC
sxs-collaboration/spectre pull request #5903
Opened 2024-04-09 20:02 UTC by ffoucart

## Proposed changes

This PR begins the process of keeping track of energy/momentum/lepton number exchange between neutrinos and the fluid. Here, I only consider the "emit" function, as it is already merged.
My current plan is to keep the total energy/momentum/lepton number in the various coupling_* containers, then divide by the coordinate volume at the end of a timestep to get the actual coupling terms used in the GhValenciaDivClean equations.

### Upgrade instructions

None

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-04-29 22:20 UTC, kidder requested changes
you can squash the changes

2024-04-29 22:20 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
> +const double proton_mass_MeV = 938.272046;
- Add the proton_mass to `PointwiseFunctions/Hydro/Units.hpp` in the same manner as neutron_mass
- remove this
- include and use `proton_mass` in the tpp file above

2024-04-29 22:20 UTC, kidder commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_EmitPackets.cpp
> +    = make_with_value< Scalar<DataVector> >(zero_dv, W_boost);
clang-format this file (there should be no spaces between angle braces)

2024-04-29 22:20 UTC, kidder commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_EmitPackets.cpp
> +  expected_coupling_tilde_s.get(1) = -4.0*sqrt(3);
3 -> 3.0

2024-05-01 15:23 UTC, ffoucart commented
I believe this should address all comments so far.

2024-05-01 16:25 UTC, kidder approved these changes

2024-05-01 18:42 UTC, merged