Draft function to take full MC step
sxs-collaboration/spectre pull request #5907
Opened 2024-04-10 17:52 UTC by ffoucart

## Proposed changes

Adds function responsible for taking a full MC time step during evolution

### Upgrade instructions

None

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-04-10 17:54 UTC, ffoucart commented
Currently only here as a guide to see how the various functions and variables are supposed to interact, and to see what remains to be coded. This PR depends on #5902  and #5904, and will conflict with #5851, #5870, and #5903.

2024-05-24 14:17 UTC, ffoucart commented
Rebased against 5902 and ready for review.

2024-06-04 13:28 UTC, kidder requested changes
you can squash the changes

2024-06-04 13:28 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
> +#include "Evolution/Particles/MonteCarlo/NeutrinoInteractionTable.hpp"
Anything with a `std::` in this file needs the appropriate include.  All of the spectre includes should just be forward declarations and an include of `DataStructures/Tensor/TypeAliases.hpp`.  You may need to add these includes to the cpp file.

2024-06-04 13:28 UTC, kidder commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_TakeTimeStep.cpp
> +}
is there any property of the result that you can CHECK the value of?

2024-06-04 13:28 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TakeTimeStep.tpp
> +#include "Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp"
make this the first include, with a blank line after it. 

Also add the appropriate includes

2024-06-04 13:28 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TakeTimeStep.tpp
> +        const double& start_time, const double& target_end_time,
const double& -> const double

2024-06-04 13:28 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp
> +      const double& start_time, const double& target_end_time,
const double& -> double

2024-06-04 14:42 UTC, ffoucart commented
Rebased, addressed code review comments, and squashed.

2024-06-04 14:59 UTC, kidder approved these changes

2024-06-04 15:32 UTC, merged