Add coupling to scattering
sxs-collaboration/spectre pull request #5927
Opened 2024-04-19 14:19 UTC by ffoucart

## Proposed changes

Add bookkeeping for hydro-MC coupling in diffusion approximation

### Upgrade instructions

None

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-04-19 14:20 UTC, ffoucart commented
Needs to be updated after we finish #5920

2024-05-06 16:11 UTC, ffoucart commented
@kidder : I did some changes after rebasing here (mainly moving the coupling function to a separate file), so I kept the changes in a separate PR (hence the failing test due to a "rebase" PR). For some reason I had in mind that you had looked at this, but I don't see any comment so... my memory might be wrong. If you don't care about the difference between the new and old version, I can merged this into a single commit.

2024-05-06 17:57 UTC, ffoucart commented
Ok, everything has been merged in one commit now and passes the test; should be ready for review.

2024-05-07 17:28 UTC, kidder requested changes
you can squash the changes

2024-05-07 17:28 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/CouplingTermsForPropagation.hpp
> +#include "DataStructures/DataVector.hpp"
- include only `DataStructures/Tensor/TypeAliases.hpp` and `IndexType.hpp`
- forward declare not_null, DataVector, Packet
- move the includes to the cpp file

2024-05-07 17:28 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/CouplingTermsForPropagation.hpp
> +#include <vector>
array not vector

2024-05-07 17:28 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/CouplingTermsForPropagation.hpp
> +/// absorption and scattering opacities absorption_opacity,
I think you can shorten this by omitting the text after opacities

2024-05-07 17:28 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/CouplingTermsForPropagation.hpp
> +/// \details We consider total momentum exchances, not
exchanges?

2024-05-08 20:47 UTC, ffoucart commented
I think all the comments are addressed here.

2024-05-09 17:37 UTC, kidder approved these changes

2024-05-09 17:37 UTC, merged