Handle substeps in LTS error control
sxs-collaboration/spectre pull request #5943
Opened 2024-04-25 19:33 UTC by wthrowe

Preparation for adding LTS substep methods.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-04-27 17:43 UTC, nilsdeppe requested changes
LGTM, a couple minor suggestions you can squash immediately

2024-04-27 17:43 UTC, nilsdeppe commented on src/Time/StepperErrorEstimate.hpp
> +struct StepperErrorEstimate {
Could you please add doxygen documentation to this?

2024-04-27 17:43 UTC, nilsdeppe commented on src/Time/StepperErrorEstimate.hpp
> +  void pup(PUP::er& p) {
Move out of line?

2024-04-29 23:30 UTC, wthrowe commented
Done.  Also changed the initializer for `TimeDelta step_size{{}, 0};` to plain `{}` because that weirdness was left over from an earlier attempt.

2024-04-30 00:53 UTC, wthrowe commented on src/Time/StepChoosers/ErrorControl.hpp
> +                          new_step >= previous_step or l_inf_error <= 1.0);
Wait, this is backwards.

2024-04-30 01:02 UTC, wthrowe commented on src/Time/StepChoosers/ErrorControl.hpp
> +                          new_step >= previous_step or l_inf_error <= 1.0);
Actually, no, it's the right way, but it does need an `abs`.

2024-04-30 02:32 UTC, wthrowe commented on src/Time/StepChoosers/ErrorControl.hpp
> +                          new_step >= previous_step or l_inf_error <= 1.0);
Pushed a fixup for this and updated the test so it would have been caught.

2024-04-30 19:56 UTC, wthrowe commented
And added a small commit fixing a preexisting bug in the test.

2024-05-01 19:52 UTC, nilsdeppe reviewed
LGTM! Please go ahead and squash!

2024-05-05 02:17 UTC, nilsdeppe approved these changes

2024-05-05 02:17 UTC, merged