KerrSchild: Fix dimensionless vs dimensionful spin bug.
sxs-collaboration/spectre pull request #595
Opened 2018-03-14 00:33 UTC by markscheel

## Proposed changes

Fixes bug where dimensionless spin was used where Kerr parameter `a` should have been used.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-03-14 01:04 UTC, nilsdeppe requested changes
Could you add a test that catches this bug?

2018-03-14 17:42 UTC, markscheel commented
Also Geoffrey has another test in his upcoming PR that will test KerrSchild (this is how the bug was found).

By the way, one reason the bug was not found earlier is that KerrSchild with an incorrect value of spin still satisfies Einstein's equations (and the main KerrSchild test verifies that it solves Einstein's equations).

2018-03-14 20:51 UTC, nilsdeppe approved these changes

2018-03-15 01:00 UTC, kidder approved these changes

2018-03-15 01:43 UTC, merged