corrected tildeB sources and fluxes in ValenciaDivClean
sxs-collaboration/spectre pull request #5960
Opened 2024-05-01 15:24 UTC by norafl

## Proposed changes

Corrects the sources and fluxes in magnetic field evolution. 

Currently, the code has made the simplification
$$\partial_i(B^j\beta^i) = B^j\partial_i\beta^i,$$
which can introduce errors in handling the divergence of the magnetic field. This update removes the resulting $B^j\partial_i\beta^i$ from the magnetic field source terms and adds a corresponding $B^j\beta^i$ to the corresponding flux terms. This handling is consistent with eq. 20 of https://arxiv.org/pdf/2004.00870 and eq. 32 of https://arxiv.org/pdf/1806.04182.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-05-01 18:42 UTC, wthrowe requested changes
This still needs updates to the documentation (in `src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp` as well as the `Fluxes.hpp` and `Sources.hpp` files) and the tests.  I haven't checked these specific ones, but most of the tests for this sort of thing have the equations reimplemented in python, which should be the main thing that needs fixing there.

2024-05-01 18:42 UTC, wthrowe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Fluxes.cpp
> +                        transport_velocity->get(j) * tilde_b.get(i));
Should no longer be multiplied by the lapse, I believe.

2024-05-01 20:47 UTC, wthrowe requested changes

2024-05-01 20:47 UTC, wthrowe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Fluxes.cpp
> +                        transport_velocity->get(j) * tilde_b.get(i);
Reorder these terms to match the docs, just for readability.

2024-05-01 20:47 UTC, wthrowe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp
> + * \note The fluxes and sources of {\tilde B} follow eq. 20 of
Need $s around the math.

2024-05-01 20:47 UTC, wthrowe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/System.hpp
> + * \cite Palenzuela2018 rather than eq. 89 of \cite Moesta2014
The equation numbers for both papers look wrong.

2024-05-05 02:16 UTC, nilsdeppe commented
Can you change your wording in commits to be present tense? E.g. `Fix blah` or `Update blah`. It might help to review our contributing guidelines: https://spectre-code.org/contributing_to_spectre.html and the commit message part is noted https://spectre-code.org/contributing_to_spectre.html#git-commit-messages

2024-05-07 01:33 UTC, wthrowe requested changes
This looks good.  Two more things: code formatting, which I've commented on as a line-comment, and squashing.  This PR is pretty much an atomic change, so it should be squashed into a single commit.  Google "git interactive rebase" if you don't know how to do that.  As noted by @nilsdeppe, make sure your resulting commit message follows our guidelines.

I think the CI error is just some random failure, so ignore that if it doesn't happen again after you push the squashed version.

2024-05-07 01:33 UTC, wthrowe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/Fluxes.cpp
> +        get(lapse) * (get(tilde_phi) * inv_spatial_metric.get(i, j));
Run this though clang-format.  Their documentation has instructions on how to use it through emacs or git: https://clang.llvm.org/docs/ClangFormat.html .  (Our repo has style options configured in a top-level `.clang-format` file, so you shouldn't need to configure anything yourself.)

2024-05-08 02:18 UTC, wthrowe commented
Formatting looks good now, but something went wrong during your rebase.  Probably easiest to just sort it out in person tomorrow.

2024-05-09 18:24 UTC, wthrowe approved these changes

2024-05-09 18:25 UTC, merged