Update documentation and env for mbot
sxs-collaboration/spectre pull request #5974
Opened 2024-05-08 15:48 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-05-08 18:29 UTC, knelli2 requested changes

2024-05-08 18:29 UTC, knelli2 commented on docs/Installation/InstallationOnClusters.md
> +`spectre_run_cmake_clang -D SPECTRE_DEBUG=ON` (you can also us gcc). The second
`us` -> `use`

2024-05-08 20:45 UTC, nilsdeppe commented on docs/Installation/InstallationOnClusters.md
> +`spectre_run_cmake_clang -D SPECTRE_DEBUG=ON` (you can also us gcc). The second
Thanks! Done and rebased :)

2024-05-09 01:42 UTC, knelli2 approved these changes

2024-05-09 17:34 UTC, kidder approved these changes

2024-05-09 17:34 UTC, merged