Mc high ka corrections
sxs-collaboration/spectre pull request #5977
Opened 2024-05-09 19:26 UTC by ffoucart

## Proposed changes

Add corrections to high absorption opacity regions needed for implicit Monte-Carlo

### Upgrade instructions

NA

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-05-09 19:26 UTC, ffoucart commented
Depends on #5902

2024-05-24 14:19 UTC, ffoucart commented
Rebased against 5902 and ready for review.

2024-06-04 17:14 UTC, kidder requested changes
you can squash the change when rebasing

2024-06-04 17:14 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/ImplicitMonteCarloCorrections.tpp
> +#include "Evolution/Particles/MonteCarlo/TemplatedLocalFunctions.hpp"
make this the first include followed by a blank line

2024-06-04 17:14 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/ImplicitMonteCarloCorrections.tpp
> +  // at constant T as measured of how 'impactfull' neutrino
as a measure of how impactful

2024-06-06 20:20 UTC, ffoucart commented
Latest PR addressed code review requests, but also rebased against #6037 to avoid future conflicts. This PR now depends on #6037 (only for minor changes to the interface of the neutrino table when adding GZs)

2024-06-14 21:04 UTC, kidder approved these changes

2024-06-14 21:04 UTC, merged