More helper code for nodegroups, eg AtomicInboxBoundaryData, number_of_block_boundaries for an ElementId
sxs-collaboration/spectre pull request #5997
Opened 2024-05-15 17:29 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-05-15 21:29 UTC, wthrowe submitted a review, later dismissed

2024-05-20 21:12 UTC, kidder requested changes
you can squash

2024-05-20 21:12 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/AtomicInboxBoundaryData.hpp
> +   * is the side in the logical dimension \f$d\f$ with a vlaue of 1 for upper
value

2024-05-20 21:12 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/AtomicInboxBoundaryData.hpp
> +   * dimension of the neighbor from the element whose inbox this is, \f$s\f$
dimension of the direction to the neighbor of the element

2024-05-20 21:12 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/AtomicInboxBoundaryData.hpp
> +   * and 0 for lower, and \f$e\f$ is the element segment hash. The element
is a hash of the index of the SegmentId%s of the neighbor's ElementId for the dimensions other than \f$d\f$.  In particular:  for \f$D = 1\f$; for  \f$D=1\f$, \f$e\f$ is 0 (1) if the SegmentId index along the face is even (odd); and for \f$D = 3\f$ \f$e\f$ is 0 (1, 2, 3) if the SegmentId indices along the face are both even (lower dim odd, higher dim odd, both dims odd).

2024-05-20 21:12 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/AtomicInboxBoundaryData.hpp
> +  std::array<Parallel::StaticSpscQueue<
can you add a code comment on where `20` comes from

2024-05-21 14:48 UTC, nilsdeppe commented
Okay, rebased and squashed in the changes. Thanks for the reviews!

2024-05-21 16:10 UTC, kidder submitted a review, later dismissed

2024-05-22 13:46 UTC, nilsdeppe commented
Rebased since there were conflicts in the `ElementId` code

2024-05-22 16:33 UTC, wthrowe approved these changes

2024-05-23 14:18 UTC, merged