Addition of Direction and Direction test
sxs-collaboration/spectre pull request #60
Opened 2017-06-27 15:59 UTC by gsb76

2017-06-27 16:34 UTC, osheamonn commented on src/Domain/CMakeLists.txt
>  set(LIBRARY_SOURCES
Alphabetise.

2017-06-27 16:34 UTC, osheamonn commented on src/Domain/Direction.cpp
> +Direction<1> Direction<1>::createDirection(const size_t dimension,
create_direction

2017-06-27 16:34 UTC, osheamonn commented on src/Domain/Direction.cpp
> +  ASSERT(0 == dimension || 1 == dimension, "dim = " << dimension);
Replace || with `or`

2017-06-27 16:34 UTC, osheamonn commented on src/Domain/Direction.hpp
> +  Axis mAxis{Axis::Xi};
mAxis, mSide -> axis_, side_

2017-06-27 16:34 UTC, osheamonn commented on src/Domain/Direction.hpp
> +  static_assert(VolumeDim == 2 || VolumeDim == 3, "VolumeDim must be 2 or 3.");
Replace || to `or`

2017-06-27 18:27 UTC, nilsdeppe requested changes

2017-06-27 18:27 UTC, nilsdeppe commented on src/Domain/Direction.hpp
> +  static Direction<VolumeDim> create_direction(size_t dimension, Side side);
Why is this not a constructor? It acts exactly like a constructor

2017-06-27 18:27 UTC, nilsdeppe commented on src/Domain/Direction.cpp
> +    os << "+";
Should be tested

2017-06-27 18:27 UTC, nilsdeppe commented on src/Domain/Direction.hpp
> +  static Direction<VolumeDim> lower_xi();
Since the Axis can be accessed publicly, these function should be tested explicitly

2017-06-27 19:31 UTC, fmahebert commented on src/Domain/Direction.cpp
> +// // See LICENSE.txt for details.
Double comment

2017-06-27 19:31 UTC, fmahebert commented on src/Domain/Direction.cpp
> +  return Direction<3>(Axis::Zeta, side);
Why not `if ... else if ... else` ?

2017-06-27 19:31 UTC, fmahebert commented on tests/Unit/Domain/Test_Direction.cpp
> +  CHECK(upper_xi.opposite().sign() == -1.0);
Is there any reason not to explicitly check all coordinates in all dims?

2017-06-28 04:02 UTC, nilsdeppe requested changes

2017-06-28 04:02 UTC, nilsdeppe commented on src/Domain/Direction.hpp
> +// Needed in order to address warning:
Should add "Ignorning `-Wpedantic` is needed" in case the comment gets lost from the code at some point

2017-06-28 04:02 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Direction.cpp
> +#include <sstream>
You should need sstream anymore, I think

2017-06-28 04:02 UTC, nilsdeppe commented on tests/Unit/Domain/Test_Direction.cpp
> +// Distributed under the MIT License.
You should look at the codecov report here:
https://codecov.io/gh/sxs-collaboration/spectre/pull/60/diff

and make sure you are covering things :)

2017-06-28 23:58 UTC, nilsdeppe requested changes

2017-06-28 23:58 UTC, nilsdeppe commented on src/Domain/Direction.hpp
> +  size_t dimension() const { return static_cast<size_t>(axis_); }
We can mark all the retrieving functions noexcept

2017-06-29 15:15 UTC, nilsdeppe approved these changes

2017-06-29 15:15 UTC, merged