Register initial magnetic field in EvolveGhValenciaDivClean with Charm.
sxs-collaboration/spectre pull request #6004
Opened 2024-05-17 13:56 UTC by ncorsobh

## Proposed changes

Registers `InitialMagneticField` with Charm in EvolveGhValenciaDivClean. Necessary for evolving a magnetized TOV star with GH.

### Upgrade instructions

### Code review checklist

- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [x] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-05-17 18:33 UTC, wthrowe requested changes
Instead of doing this, switch the class to use the `factory_creation` struct in the metavariables instead of the deprecated `creatable_classes` feature.  Look at how it's done for `TimeStepper`, for example.

2024-05-18 21:08 UTC, nilsdeppe commented
This was intentionally not using the factory creation. I think it should stay as-is. The factory creation struct is tedious when you know all the derived classes ahead of time. We've discussed that the creatable classes is _not_ deprecated a long time ago and serves a distinct purpose from the factory class approach. There's a lot of code that intentionally doesn't use that and I think should stay that way.

2024-05-18 21:08 UTC, nilsdeppe approved these changes, later dismissed
Looks great! Thanks for doing this!

2024-05-18 23:45 UTC, wthrowe commented
> This was intentionally not using the factory creation. I think it should stay as-is. The factory creation struct is tedious when you know all the derived classes ahead of time. We've discussed that the creatable classes is _not_ deprecated a long time ago and serves a distinct purpose from the factory class approach. There's a lot of code that intentionally doesn't use that and I think should stay that way.

Who's "we"?  I don't recall being involved in any such conversation.  The code clearly marks it as a legacy interface.

The `factory_creation` method requires, depending on how you count, either less code or about the same as `creatable_classes`, so I don't see how it's more tedious.

2024-05-21 16:05 UTC, nilsdeppe commented
This was discussed in either the Thursday or Monday call maybe 3-4 years ago. Definitely quite a while ago and you were present. My objection to removing the `using createable_classes` is that there are places in the code where we can currently do explicit instantiations because we know all the derived classes _without_ the metavariables. Requiring the metavariables means more code can only get compiled as part of the executable. I'm fine with using the factory struct being used as `tmpl::pair<Base, typename Base::createable_classes>` but I don't like forcing everything to have typelists outside of the base class. That is useful in some cases where we want different derived classes depending on the executable (e.g. it's fantastic for initial data and events), but things like boundary corrections and boundary conditions are quite universal. Being able to have a `call_with_dynamic_type` over those in an explicit instantiation in the `System` directory is very nice. Keeping the registration with Charm++ through the `factory_creation` struct seems good to me, though.

So if your suggestion is change the `factory_creation` struct in the metavariables to have `tmpl::pair<Base, typename Base::createable_classes>` then I'm in favor. If the suggestion is to move the `createable_classes` typelist into a separate file, then I'm opposed, certainly in the general case, but currently also in the specific case.

2024-05-22 17:11 UTC, wthrowe commented
(Your time estimates are presumably off.  This code was only added a bit over 3 years ago.)

You can't explicitly instantiate a factory, and that's the only thing that is directly tied to the `factory_creation` struct.  The argument to `call_with_dynamic_type` doesn't have to come from the `factory_creation` struct if you have a list by some other means, so in those cases having the list available from the base class may make sense, yes.

In any case, that's irrelevant for this PR, since there's no reason to use `call_with_dynamic_type` with `InitialMagneticField`, and nothing is doing anything fancy with option parsing.  What's the advantage of having the list in the base class?  You still need to have the list of headers in a `Factory.hpp`, so it means the same information has to be maintained in two places, and there's very little you can do with the list without including the class's `Factory.hpp`.

2024-05-28 12:48 UTC, nilsdeppe commented
I talked about this with @wthrowe on Friday and the conclusion was that in this case moving the list of magnetic fields from the base class to `Factory.hpp` is fine. The plan is to make that the convention whenever possible. I've had trouble finding where the lists are located, particularly with initial data, so trying to standardize that (not in this PR!) would be useful.

2024-05-28 18:00 UTC, ncorsobh commented
Force-pushed since the previous version was just a one-liner that got removed anyway. Let me know if this is the idea you're asking for or if I should do something else.

2024-05-28 18:22 UTC, wthrowe reviewed
Yes, that's what I had in mind.  Tests need fixing, though.

2024-05-28 18:22 UTC, wthrowe commented on src/PointwiseFunctions/AnalyticData/GrMhd/InitialMagneticFields/InitialMagneticField.hpp
> -  using creatable_classes = tmpl::list<Poloidal, Toroidal>;
Remove the forward declarations from this file.

2024-06-07 18:02 UTC, wthrowe requested changes

2024-06-07 18:02 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/Test_MagnetizedTovStar.cpp
> -          evolution::initial_data::OptionTags::InitialData,
Don't change this so much.  You've lost the test of the `get_clone()` method and possibly the option tag (not sure if that one's important here).  Just switch `test_option_tag_factory_creation` to `test_option_tag` and pass the metavariables.

2024-06-07 18:02 UTC, wthrowe commented on tests/Unit/PointwiseFunctions/AnalyticData/GrMhd/InitialMagneticFields/Test_Poloidal.cpp
> +  register_factory_classes_with_charm<Metavariables>();
[optional] I think the only change you need in this file is making this line `register_classes_with_charm<InitialMagneticFields::Poloidal>();`.  The version you've written isn't wrong, but it's a lot more verbose than necessary.

Same for `Test_Toroidal.cpp`.

2024-06-21 21:40 UTC, wthrowe commented
OK, looks good.  Squash.

2024-06-24 20:24 UTC, wthrowe approved these changes

2024-06-24 20:24 UTC, merged