More minor code for nodegroup elements
sxs-collaboration/spectre pull request #6027
Opened 2024-05-24 02:30 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-05-24 17:11 UTC, kidder requested changes
you can squash

2024-05-24 17:11 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/InboxTags.hpp
> + * unordered container for the inbox, then transfer the data into an order map
ordered

2024-05-25 20:17 UTC, knelli2 requested changes

2024-05-25 20:17 UTC, knelli2 commented on src/Evolution/DiscontinuousGalerkin/InboxTags.hpp
> +    // Note: This assumes the neighbor_id is oriented into our (the elment
[nitpick] `elment` -> `element`

2024-05-25 20:17 UTC, knelli2 commented on src/Evolution/DiscontinuousGalerkin/InboxTags.hpp
> +  static size_t insert_into_inbox(const gsl::not_null<type_spsc*> inbox,
You've changed the return type of this function. Could you add some docs about what the `size_t` represents? From the looks of it, it's just the new size of the inbox

2024-05-25 20:17 UTC, knelli2 commented on src/Evolution/DiscontinuousGalerkin/InboxTags.hpp
> + * unordered container for the inbox, then transfer the data into an order map
[nitpick] also `using` -> `use`

2024-05-28 13:02 UTC, nilsdeppe commented
I've rebased and pushed fixups. I added a decent number of words for the return type being `size_t` since that is important. I'll need to clean this class up a bit after everything is working, mostly just the documentation. I also added `value_type` as a type alias since this is actually what the STL uses. It's not used right now, though.

2024-05-28 14:09 UTC, kidder reviewed
fixups LGTM

2024-05-29 00:42 UTC, knelli2 approved these changes
Fixups look good. Squash

2024-05-29 02:16 UTC, nilsdeppe commented
Done! Thanks!

2024-05-29 02:18 UTC, kidder approved these changes

2024-05-29 05:02 UTC, merged