Unify analytic solutions interface more
sxs-collaboration/spectre pull request #604
Opened 2018-03-18 03:07 UTC by nilsdeppe

## Proposed changes

- Add `assign_subset(TaggedTuple)` 
- Use a `TaggedTuple<Tags...> variables(x, t, tmpl::list<Tags...>)` method to replace `evolution_variables` and `dt_evolution_variables` in `ScalarWave::PlaneWave` analytic solution. This interface will allow us to overload the `variables` function for retrieving different variables. For example, in EinsteinSolutions we can overload it for the 3+1 variables and the GH variables.
- Adds the `variables` function to Minkowski and KerrSchild einstein solutions
- Use unified interface to reduce the size of `Test_Strahlkorper.cpp` 

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-03-19 20:52 UTC, kidder requested changes

2018-03-19 20:52 UTC, kidder commented on tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
> +  Variables<tmpl::list<Var>> variables(const tnsr::I<DataVector, Dim>& x,
should return TaggedTuple

2018-03-19 20:52 UTC, kidder commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/WaveEquation/Test_PlaneWave.cpp
> +  CHECK_ITERABLE_APPROX(
can you factor out these

2018-03-19 20:52 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/KerrSchild.hpp
> +  tuples::TaggedTupleTypelist<tags<DataType>> variables(
do this for all functions

2018-03-19 20:52 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/EinsteinSolutions/Minkowski.hpp
> +#include "NumericalAlgorithms/LinearOperators/PartialDerivatives.hpp"
comment why

2018-03-19 20:52 UTC, kidder commented on tests/Unit/ApparentHorizons/Test_StrahlkorperGr.cpp
> +  const double mass = 1.0;
also test non-unit mass (check if Geoffrey did this in his #598)

2018-03-22 20:59 UTC, nilsdeppe commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/WaveEquation/Test_PlaneWave.cpp
> +                    const std::array<DataVector, Dim + 1>& expected,
`expected_second_derivs` and add comment

2018-03-22 20:59 UTC, nilsdeppe commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/WaveEquation/Test_PlaneWave.cpp
> +    check_solution<1>(
indentation

2018-03-23 16:37 UTC, kidder approved these changes

2018-03-23 20:11 UTC, wthrowe approved these changes

2018-03-23 20:19 UTC, merged