Add DgElementArrayMember
sxs-collaboration/spectre pull request #6042
Opened 2024-05-29 19:30 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-05-31 19:09 UTC, kidder requested changes
nolint the clang-tidy error?

a lot of this code looks like it is copied from a DistributedObject.   Should these functions be factored out?


you can squash any changes

2024-05-31 19:09 UTC, kidder commented on src/Parallel/ArrayCollection/DgElementArrayMember.hpp
> +  /// List off all the Tags that can be received into the Inbox
off -> of

2024-06-01 00:43 UTC, nilsdeppe commented
1. added nolint for one. I don't know what to do about the other. The code seems to compile with clang so I don't know why clang-tidy is having issues.
2. Probably in the long run. I didn't mostly because we'll also need to test switching to a group instead of nodegroup to get it working with Kokkos, so just a lot of imminent changes that I don't know what they will require.
3. I've rebased and squashed. Thanks for the review!

2024-06-01 01:31 UTC, kidder approved these changes

2024-06-01 13:42 UTC, merged