Add LTS support to Adams-Moulton time steppers
sxs-collaboration/spectre pull request #6043
Opened 2024-05-29 21:35 UTC by wthrowe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-05-30 16:31 UTC, nilsdeppe requested changes
LGTM, a few clarifying suggestions. Please squash and rebase immediately :)

2024-05-30 16:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +         "Implemented Adams-based methods have no more than one substep.");
Maybe `"The implemented... If you implemented a new method, you should..."`? So then if someone adds one they have some guidance on what to do?

2024-05-30 16:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +      "FIXME just deduce?");
Did you mean to leave these `FIXME`s?

2024-05-30 16:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +    std::transform(local_ids.begin(), local_ids.end(),
[optional] `alg::transform`?

2024-05-30 16:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +           "Missed step start iterating over small steps.");
Could you expand on this message a bit? As a user I'm not sure what I should do if I hit this. Maybe also print out `current_small_step` and `start_time` so if it does show up at least someone can give us those values for their simulation?

2024-05-30 16:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +          "Multiple-small-step dense output is not supported.  Split into an "
Sorry, I'm also not entirely sure what I should change if I hit this error :(

2024-05-30 16:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +  ASSERT(not step_coefficients.empty(), "Generated no coefficients");
maybe add `"... This an algorithmic bug. Please file an issue."`?

2024-05-30 16:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +  std::transform(control_ids.begin(), control_ids.end(), control_times.begin(),
[optional] `alg::transform`?

2024-05-30 16:31 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +  std::transform(control_times.begin(), control_times.end(),
[optional] `alg::transform`?

2024-05-31 21:04 UTC, wthrowe commented on src/Time/TimeSteppers/Factory.hpp
> +    tmpl::list<AdamsBashforth, AdamsMoultonPc<false>, AdamsMoultonPc<true>>;
Note to myself: Make the GH executables only accept the non-deadlocking time steppers in LTS mode.

2024-06-11 01:56 UTC, wthrowe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +         "Implemented Adams-based methods have no more than one substep.");
They'd have to code in how big the extra substeps are, I guess?  Assuming the value for substep 1 still agreed with AM?  I'm not sure what you're asking for.  I don't think there's anything subtle going on here.  This is just the calculation of `id.substep_time()` but as a `Time` instead of a `double`.

2024-06-11 01:56 UTC, wthrowe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +      "FIXME just deduce?");
Rebase fail.  Removed altogether instead of adding in one commit and deleting later.

2024-06-11 01:56 UTC, wthrowe commented on src/Time/TimeSteppers/Factory.hpp
> +    tmpl::list<AdamsBashforth, AdamsMoultonPc<false>, AdamsMoultonPc<true>>;
Added `monotonic_lts_time_steppers` in a new commit.

2024-06-11 04:17 UTC, knelli2 requested changes
Couple clang-tidy things and also some timeouts in the AB tests, but other than that the code looks ok. But to be honest, I didn't really understand it all that much (nor am I going to try to). I will say that this PR could have benefited from being split up into a few smaller PRs.

2024-06-11 13:50 UTC, nilsdeppe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +         "Implemented Adams-based methods have no more than one substep.");
Oh, I see. I think what would've helped is the phrasing `"The currently implemented.... If you've implemented one that has more substeps then you must generalize this code."`

2024-06-11 20:00 UTC, wthrowe reviewed
Added two more fixups.  One of the clang-tidy errors was for a feature our compilers don't support yet, so I disabled the check for now.

2024-06-11 20:00 UTC, wthrowe commented on src/Time/TimeSteppers/AdamsLts.cpp
> +         "Implemented Adams-based methods have no more than one substep.");
Decided to replace it with a check that the result is correct, instead of a whitelist on the input.

2024-06-11 20:52 UTC, nilsdeppe reviewed
fixups LGTM. Please rebase and squash!

2024-06-12 22:56 UTC, knelli2 approved these changes

2024-06-12 22:59 UTC, nilsdeppe approved these changes

2024-06-12 22:59 UTC, merged