Fix NumPy API working for multiple cpp files, also refactor Christoffel to use Pypp.
sxs-collaboration/spectre pull request #607
Opened 2018-03-19 20:44 UTC by osheamonn

## Proposed changes

The NumPy API didn't work when used in several cpp files. The solution was to refactor where the `import_numpy` call was happening into a cpp file and add some macros which are used by the python internals. To make sure it now works with multiple cpp files I refactored the Christoffel tests. 

### Types of changes:

- [x] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

2018-03-19 21:02 UTC, kidder submitted a review, later dismissed

2018-03-19 21:02 UTC, nilsdeppe approved these changes

2018-03-19 23:31 UTC, nilsdeppe requested changes
Just `// NOLINT` the clang-tidy warning, it's safe because the function name is generated for the file and library name.

Please squash the fixup right away :)

2018-03-19 23:31 UTC, nilsdeppe commented on tests/Unit/Pypp/SetupLocalPythonEnvironment.cpp
> +#include <numpy/arrayobject.h>
My guess is you need `#include <Python.h>` to get it to build on macOS.

2018-03-20 03:31 UTC, nilsdeppe approved these changes

2018-03-20 03:33 UTC, nilsdeppe commented
@kidder can you re-approve?

2018-03-20 03:47 UTC, kidder approved these changes

2018-03-20 04:06 UTC, merged