ElementID: assert max refinement level
sxs-collaboration/spectre pull request #6074
Opened 2024-06-07 22:11 UTC by nilsvu

## Proposed changes

I ran into this when loading existing data on latest develop. Just got a silent overflow.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-06-08 03:37 UTC, nilsdeppe submitted a review, later dismissed

2024-06-11 04:25 UTC, knelli2 requested changes
Tests need to be fixed

2024-06-11 18:00 UTC, nilsvu commented
Fixed

2024-06-11 19:33 UTC, knelli2 approved these changes

2024-06-11 19:34 UTC, merged