Support ComplexDataVector in observations
sxs-collaboration/spectre pull request #6075
Opened 2024-06-07 23:52 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-06-11 21:32 UTC, wthrowe requested changes

2024-06-11 21:32 UTC, wthrowe commented on src/NumericalAlgorithms/Interpolation/RegularGridInterpolant.hpp
> +  ComplexDataVector interpolate(const ComplexDataVector& input) const;
Test these.

2024-06-13 19:19 UTC, nilsvu commented on src/NumericalAlgorithms/Interpolation/RegularGridInterpolant.hpp
> +  ComplexDataVector interpolate(const ComplexDataVector& input) const;
Added a test

2024-06-13 20:18 UTC, wthrowe reviewed
Tests look fine.  A lot of the CI jobs are failing, though.

2024-06-17 20:16 UTC, wthrowe approved these changes

2024-06-17 20:16 UTC, merged

2024-06-18 02:25 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveFields.hpp
> +            const auto& tensor, const FloatingPointType floating_point_type,
This is not meant to be a late review or anything.

Just an FYI, in C++20 you can now do
```cpp
[&record_tensor_component_impl, &interpolant]<typename TensorType>(const TensorType&, ...)
```
to get template parameters in lambdas. You could also do
```cpp
[&record_tensor_component_impl, &interpolant]<typename X, typename Y, typename Z>(const Tensor<X,Y,Z>&, ...)
```
with better names than X,Y,Z :)