Add dev guide for AMR
sxs-collaboration/spectre pull request #6078
Opened 2024-06-11 01:18 UTC by kidder

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-06-11 22:23 UTC, wthrowe requested changes
Seems clear.  Found a few typos.

2024-06-11 22:23 UTC, wthrowe commented on docs/DevGuide/Amr.md
> +of the elements that are joining.
Typo.  Probably "on the one of" -> "on one of".

2024-06-11 22:23 UTC, wthrowe commented on docs/DevGuide/Amr.md
> +Each criteria must be an option-creatable class derived from
"Each criterion"

2024-06-11 22:23 UTC, wthrowe commented on docs/DevGuide/Amr.md
> +amr::projectors::DefaultInitialize which value intializes the items
"initializes"

2024-06-11 22:23 UTC, wthrowe commented on docs/DevGuide/Amr.md
> +- The addition of the mutator `amr::Initialization:Initialize` to the
Single colon -> double colon.

2024-06-11 22:23 UTC, wthrowe commented on docs/DevGuide/Amr.md
> +          Interval: 1
Regridding after every step seems a bit over-aggressive.

2024-06-12 21:16 UTC, knelli2 requested changes
Most just checking links

2024-06-12 21:16 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +amr::Info) based on decisions (or other information in amr::Info) sent
Not for this PR (or maybe, depends on what you want to do), but `amr::Info` doesn't have any documentation so wasn't really sure what to get out of it.

2024-06-12 21:16 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +amr::Info) of the element changes, the element will send an its
Remove `an`?

2024-06-12 21:16 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +  code for communicating boundary corrections assumes 2:1 balance.  In
`as it as the` -> `as the`

2024-06-12 21:16 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +  Spectral::Basis of the Mesh.  For the refinement level, the minimum
So the link to `Spectral::Basis` doesn't actually tell you what these extrema are. Maybe we should link `Spectral::minimum_number_of_points` and `Spectral::maximum_number_of_points` instead?

2024-06-12 21:16 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +  `ElementId::max_refinement_level`.
This link didn't show up. Maybe because `max_refinement_level` isn't documented? Could just link `ElementId` instead.

2024-06-12 21:16 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +The how is controlled by the option group `Amr`.  Here you list the
Could you add quotes around "how"? Thought this was a typo when I first looked at it

2024-06-12 21:16 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +When AMR happens is contolled by specifying a Trigger and a list of
Then "When" here also

2024-06-12 21:16 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +      - VisitAndReturn(AdjustDomain)
I think you probably stated it above already, but maybe reiterate here that **BOTH** of these, in this order, are required for AMR to work.

2024-06-17 18:02 UTC, knelli2 approved these changes
Fixups look good to me

2024-06-17 20:18 UTC, wthrowe approved these changes
Looks good.  Squash.

2024-06-17 23:43 UTC, wthrowe commented
Test failures are the numpy compatibility issue fixed in #6095.  (Beats me why it only affects gcc 10 debug.)

2024-06-17 23:44 UTC, merged

2024-06-18 00:09 UTC, nilsvu commented
@wthrowe the reason for only the one build being affected is that CI only installs Py dependencies if a specific Py version is being tested, otherwise the Py installation in the container is used. gcc-10 debug tests Py 3.9.

2024-06-18 00:11 UTC, wthrowe commented
Makes sense.  Thanks.