Euclidean tensors
sxs-collaboration/spectre pull request #609
Opened 2018-03-21 17:36 UTC by wthrowe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-03-21 18:31 UTC, wthrowe commented
I've pushed this for discussion, but I'm not really happy with how it worked out in practice.  In particular, there are still requirements to do tensor operations that do not make sense from an index point of view.  This can be seen in ComputeNormalDotFluxes::apply where a lower-index tensor (interface_unit_normal) is assigned to a Euclidean tensor (phi_normal_dot_flux).  Worse things will happen with the Euclidean Laplacian if we ever care about that.

I also couldn't come up with a satisfying index placement for the analytic solution.  The derivative indices currently don't match those used in the evolution.

2018-03-22 01:02 UTC, kidder requested changes

2018-03-22 01:02 UTC, kidder commented on src/DataStructures/Tensor/IndexType.hpp
> +      return ul;
assert();

2018-03-22 01:02 UTC, kidder commented on src/DataStructures/Tensor/IndexType.hpp
> +/// Euclidean (::UpLo), and the ::Frame the index is in.  \tparam
reformat

2018-05-29 19:07 UTC, wthrowe commented
I don't think this is the correct direction to go here.  The information should be encoded in the Frames rather than directly in the tensors.  I have done some work in that direction, but I don't have time to finish it at the moment.  I will open a new PR when that is ready.

2018-05-29 19:07 UTC, closed without merging