Update Mbot instructions and hitchhiker's guide
sxs-collaboration/spectre pull request #6105
Opened 2024-06-20 20:08 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-06-20 20:52 UTC, knelli2 requested changes

2024-06-20 20:52 UTC, knelli2 commented on docs/Installation/InstallationOnClusters.md
> +3. Run `cd $SPECTRE_HOME && mkdir build && cd build`
I'd remove these. No need to repeat them, you already say follow steps 1-3. (also these can very easily get out of sync if we update the instructions)

2024-06-20 20:52 UTC, knelli2 commented on docs/Tutorials/BeginnersTutorial.md
> +*Note* on compute clusters you should use the cluster-specific instructions for
`\note` instead of \*Note\*

2024-06-20 21:46 UTC, nilsdeppe commented
Done and squashed! Thanks for the review :)

2024-06-21 15:38 UTC, knelli2 approved these changes

2024-06-21 15:38 UTC, merged