Add FromVolumeFile time dependent option
sxs-collaboration/spectre pull request #6109
Opened 2024-06-24 17:01 UTC by knelli2

## Proposed changes

First in a series of PRs that revamp the time dependent options of the Sphere and BCO domain creators.

Adds an option (not used yet) that can read functions of time that have been serialized in the volume data of an H5 file. The most recent commit of this PR contains the bulk of the changes. The other commits are just some organizational ones and don't contain any real changes.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-06-29 00:00 UTC, nilsvu requested changes

2024-06-29 00:00 UTC, nilsvu commented on src/Domain/Creators/TimeDependentOptions/FromVolumeFile.hpp
> +#include <brigand/brigand.hpp>
delete this line

2024-06-29 00:00 UTC, nilsvu commented on src/Domain/Creators/TimeDependentOptions/FromVolumeFile.cpp
> +  if (is_quat_fot) {
You could get rid of this option by checking the result of the dynamic cast. As a user I wouldn't know what value to choose for this option.

2024-06-29 00:00 UTC, nilsvu commented on src/Domain/Creators/TimeDependentOptions/FromVolumeFile.cpp
> +        conj(quats[0]) * (2.0 * quats[2] - quats[1] * datavector_to_quaternion(
where do these computations come from? Please add a comment point to some docs

2024-06-29 00:00 UTC, nilsvu commented on tests/Unit/Domain/Creators/TimeDependentOptions/Test_FromVolumeFile.cpp
> +        "\nTime: 0.0\nIsQuaternionFunctionOfTime: False\n");
Doesn't this read the same quat FoT as above?

2024-06-29 00:00 UTC, nilsvu commented on tests/Unit/Domain/Creators/TimeDependentOptions/Test_FromVolumeFile.cpp
> +  test<domain::creators::time_dependent_options::names::Rotation>();
This is missing shape/size, no?

2024-07-02 18:23 UTC, knelli2 commented
@nilsvu Because of discussions over the past few days about reading in the FoTs exactly, I added a new commit that exposes all derivatives of a FoT. I then use that for the rotation and size FoTs in a fixup commit.

2024-07-02 18:50 UTC, nilsvu commented
squash

2024-07-04 21:06 UTC, nilsvu approved these changes

2024-07-04 21:06 UTC, merged