Dc time dep opts 3
sxs-collaboration/spectre pull request #6114
Opened 2024-06-25 04:11 UTC by knelli2

## Proposed changes

This is tangentially related to the PRs revamping the time dependent options for the Sphere and BCO domain creators.

This adds the ability to read the shape coefficients from a SpEC ID horizons dat file (not a dat file within an H5 file, but an actual dat file). If we are starting from SpEC ID (which we can do), then this is an important feature to have.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

Depends on and includes #6109.

2024-07-09 02:32 UTC, knelli2 commented
No longer dependent. Also added a commit that adds `FromVolumeFile` to the shape map options

2024-08-21 18:03 UTC, nilsdeppe requested changes
LGTM. A few small requests. Please squash immediately

2024-08-21 18:03 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependentOptions/ShapeMap.hpp
> +
Unfortunately nvcc chokes on this stuff. Could you add
```cpp
YlmsFromSpEC();
YlmsFromSpEC(...);
```
constructors? I would put the definitions in the cpp.

2024-08-21 18:03 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependentOptions/ShapeMap.cpp
> +
Maybe `ASSERT(square(l_max+1) == total_col, "...");`? sqrt is a floating point op and so rounding can break.

2024-08-21 18:03 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependentOptions/ShapeMap.cpp
> +        l_max = sqrt(total_col) - 1;
Do you want a floor or round of the double? Currently this will floor, I think.

2024-08-21 18:03 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependentOptions/ShapeMap.cpp
> +        ERROR_NO_TRACE("Spec dat file has no l_max!");
Wait, isn't the error here that we were unable to find the requested time within the requested tolerance?

2024-08-21 18:03 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependentOptions/ShapeMap.cpp
> +      // Set l=0 for shape map to 0 because size is going to be used
`because SizeControl will adjust l=0` would be easier to understand

2024-08-21 18:03 UTC, nilsdeppe commented on src/Domain/Creators/TimeDependentOptions/ShapeMap.cpp
> +#include <iostream>
include `istream` instead? What do you need from `iostream`?

2024-09-07 02:39 UTC, knelli2 commented
@nilsdeppe Squashed everything in. Thanks for the review

2024-09-07 02:50 UTC, nilsdeppe approved these changes, later dismissed
LGTM! Thanks for doing this :D

2024-09-07 02:52 UTC, nilsdeppe commented
Wat, clang-tidy now doesn't want you to use `l` because it looks like `I`? Nobody should use font that doesn't allow you to tell the difference when writing code. My vote is disable that warning.

2024-09-07 03:28 UTC, knelli2 commented
Done!

2024-09-07 05:47 UTC, nilsdeppe approved these changes

2024-09-07 05:47 UTC, merged