Stop storing volume time-stepper errors
sxs-collaboration/spectre pull request #6123
Opened 2024-06-26 19:43 UTC by wthrowe

## Proposed changes

Instead, calculate the error norm we use immediately and store that (a double).

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-06-27 17:44 UTC, kidder requested changes
you can squash the change

2024-06-27 17:44 UTC, kidder commented on tests/Unit/Time/Tags/Test_StepperErrorTolerances.cpp
> +#include "Helpers/DataStructures/TestTags.hpp"
not needed

2024-06-28 09:43 UTC, nilsdeppe commented on src/Time/StepChoosers/ErrorControl.hpp
> +            "tolerances.");
Would it be helpful to print the variables tag name at the end of the error? that way users can at least know what to look at in the input file a bit better.

2024-07-01 22:30 UTC, wthrowe commented
Squashed both directly.

2024-07-02 22:40 UTC, kidder approved these changes

2024-07-02 22:40 UTC, merged