Add tags for ghost zone communication in MC
sxs-collaboration/spectre pull request #6138
Opened 2024-07-01 19:51 UTC by ffoucart

## Proposed changes

Add tags and structures to hold ghost zone data for MC.

### Upgrade instructions

None

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-07-01 19:52 UTC, ffoucart commented
@nilsdeppe @kidder : rough draft of the first structures needed for GZ communication in MC... if this is not what you had in mind, let me know.

2024-08-26 23:01 UTC, nilsdeppe requested changes
Overall this looks great! Sorry, I didn't take a minute to get an overview and started reviewing commits from the start. My biggest request is more doxygen comments, but I think everything looks good! Please go ahead and squash into a single commit :)

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunicationTags.hpp
> +struct McGhostZoneDataTag : db::SimpleTag {
Can you add a doxygen comment for this tag?

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp
> +enum CommunicationStep { PreStep, PostStep };
doxygen here and the actions too please. You can also dox the individual values:
```cpp
/// Blah
enum class CommunicationStep {
  /// PreStep represents BLAH
  PreStep,
  /// PostStep represents BLAH
  PostStep
};
```

Can you make this an `enum class` please? That prevents implicit casts to ints

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp
> +    volume_data_to_slice = 3.0;
Why are you setting this to 3?

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Packet.hpp
> +  Packet() {
Clang tidy wants:
```cpp
Packet() :      species{0},
     number_of_neutrinos{0},
     index_of_closest_grid_point{0},
     time{-1.0},
     momentum_upper_t{0.0},
     coordinates{0.0, 0.0, 0.0},
     momentum{0.0, 0.0, 0.0} {}
```

2024-08-26 23:01 UTC, nilsdeppe commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_CommunicationTags.cpp
> +  /*const auto& ghost_data_from_box =
Maybe this is added in a later commit, but this should be uncommented since this actually checks that the data you sent and received is what you thought you were sending and receiving.

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp
> +    // using ::operator<<;
Sorry, why comment this line out?

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunicationTags.hpp
> +struct CellLightCrossingTime : db::SimpleTag {
Could you add a dox comment for this tag?

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/MortarData.hpp
> +struct MortarData {
dox comment

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/MortarData.hpp
> +struct MortarDataTag : db::SimpleTag {
dox comment

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Packet.hpp
>    // Default constructor needed to make Packet puppable
Should these be dox comments? I.e. triple slash instead of double?

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Packet.hpp
> +  size_t species = 10;
why 10 as a default? If you want to check for errors I recommend `std::numeric_limits<size_t>::max()`

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Packet.hpp
> +  double number_of_neutrinos = 0.0;
A good defalut for debugging is `std::numeric_limits<double>::signaling_NaN();`

Same for time and momentum upper t

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp
> +          packets_to_send.value() = all_packets_ghost_zone.at(direction);
remove the `.value()` so that even if `packets_to_send` is empty you can assign to it.

2024-08-26 23:01 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunicationTags.hpp
> +enum CommunicationStep { PreStep, PostStep };
I would create a separate file for this. Then you don't have to worry about moving it around :) And at some point we'll want to print it's value, etc. so a separate file could be handy.

2024-08-27 13:28 UTC, ffoucart commented
Sorry for the messy commit history. As far as I can tell, the initialization of volume_data_to_slice, unnecessary commented code, and use of ` packets_to_send.value() = all_packets_ghost_zone.at(direction);` where fixed in later commits. The rest should be addressed within my next push (once I have recompiled, run the test, and fixed inevitable clang-format issues...)

2024-08-27 14:39 UTC, nilsdeppe commented
Thanks for addressing my comments! Something's wrong in the test, but I haven't looked yet. It seems to be failing on a few different targets

2024-08-27 15:25 UTC, ffoucart commented
Yes, I'll fix the obvious clang-format comments first and see whether
anything else still fails...

On Tue, Aug 27, 2024 at 10:39 AM Nils Deppe ***@***.***>
wrote:

> Thanks for addressing my comments! Something's wrong in the test, but I
> haven't looked yet. It seems to be failing on a few different targets
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sxs-collaboration/spectre/pull/6138#issuecomment-2312756604>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLFTIXF2SX5GSCWSZ6NOHDZTSFR7AVCNFSM6AAAAABKGF6N76VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJSG42TMNRQGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-27 21:18 UTC, nilsdeppe approved these changes

2024-08-27 21:18 UTC, merged