Allow to read numerical initial data for CurvedScalarWave
sxs-collaboration/spectre pull request #6154
Opened 2024-07-16 16:41 UTC by guilara

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-12-14 10:13 UTC, guilara commented
@nikwit I just rebased this. But haven't figured out yet how to include it in the CSW executable. I've only used it for the ScalarTensor system (which mimics the Gh system) and where we use the `evolution::initial_data::InitialData` class (e.g. https://github.com/sxs-collaboration/spectre/blob/e7e48dcf12563599779422624a8c148a8755f091/src/Evolution/Executables/GeneralizedHarmonic/EvolveGhBinaryBlackHole.hpp#L446).

2025-05-14 15:50 UTC, guilara commented
I've rebased this. Hopefully we can merge it.

2025-05-15 19:23 UTC, nilsdeppe requested changes

2025-05-15 19:23 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +                      //   , DensityCutoff
remove

2025-05-15 19:23 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +  ~NumericInitialData() = default;
clang-tidy is right here, sohuld be `~NumericInitialData() override = default;`

2025-05-15 19:23 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +  }
Can you move the definition to the cpp?

2025-05-15 19:23 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.cpp
> +PUP::able::PUP_ID NumericInitialData::my_PUP_ID = 0;
Could you add a line above with:
```cpp
// NOLINTNEXTLINE(cppcoreguidelines-avoid-non-const-global-variables)
```
to silence clang-tidy?

2025-05-16 10:09 UTC, guilara commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +                      //   , DensityCutoff
Thanks for catching that. Removed.

2025-05-16 10:09 UTC, guilara commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +  ~NumericInitialData() = default;
Changed

2025-05-16 10:10 UTC, guilara commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +  }
I've moved it to the cpp file. But did you mean just the definition for this function?

2025-05-16 10:10 UTC, guilara commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.cpp
> +PUP::able::PUP_ID NumericInitialData::my_PUP_ID = 0;
Added

2025-05-16 14:19 UTC, nilsdeppe commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +  }
Yes, exactly what you did :)

2025-05-16 14:19 UTC, nilsdeppe commented
LGTM, please squash!

2025-05-16 17:21 UTC, guilara commented
@nilsdeppe I've squashed

2025-05-16 20:20 UTC, nilsdeppe approved these changes
@nilsvu did you want to look too?

2025-05-21 00:17 UTC, nilsvu commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +struct ReadNumericInitialData {
Have you actually enabled this in an executable? Note that the GH and GHMHD executables use an action called `SetInitialData` that looks at the option-created initial data class (numeric or analytic) and based on that decides whether to load numeric ID or evaluate analytic ID. See `src/Evolution/Systems/GeneralizedHarmonic/Actions/SetInitialData.hpp`.

2025-05-21 09:28 UTC, guilara commented on src/Evolution/Systems/CurvedScalarWave/Actions/NumericInitialData.hpp
> +struct ReadNumericInitialData {
@nilsvu  That's supposed to happen in the next PR #6155 . I did not intend to use this on Csw on itself, only for ScalarTensor. So I just want the NumericInitialData class here mainly an intermediate step. Not entirely sure if some of the logic in the Csw executables might need to change (since there are things like `CurvedScalarWave::Actions::CalculateGrVars `in there)

2025-05-21 15:13 UTC, merged