Python test using random values
sxs-collaboration/spectre pull request #616
Opened 2018-03-24 15:11 UTC by nilsdeppe

## Proposed changes

- Move MakeWithRandomValues from `tests/Unit/DataStructures/TestHelpers.hpp` to `tests/Utilities`. I'm not sure where exactly we want to house utilities for tests. I worry that `tests/Unit/TestHelpers.hpp` will end up growing a lot. I also found it very difficult to find out which header to include for `make_with_random_values`. We should think about what would be easiest and most maintainable.
- Add a type trait `function_info` that allows you to get the argument types, return type, and the class type (for non-static member functions).
- Add `check_with_random_values` to `pypp` namespace that wraps the generation of random numbers, calling the C++ and python functions, and comparing the results. This works for both return-by-value and return-by-not_null.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-03-24 19:43 UTC, nilsdeppe commented
I'm addressing the unrelated build failure in a PR I'm currently working on.

2018-03-24 21:32 UTC, osheamonn commented on tests/Unit/Pypp/CheckWithRandomValues.hpp
> + * \param upper_bound The upper bound  for the randomly generated numbers
Remove extra space between bound and for

2018-03-24 21:32 UTC, osheamonn commented on tests/Unit/Pypp/Test_Pypp.cpp
> +  DataVector dv(5);
Can these be const?

2018-03-25 18:46 UTC, nilsdeppe commented
I'm fixing what @osheamonn suggested and also decided that we'll need the ability to specify bounds on a per-variable basis since I could see us sometimes need one variable to be in some range (say positive) and another in a different range (say always negative)

2018-03-26 22:13 UTC, kidder requested changes
squash

2018-03-26 22:13 UTC, kidder commented on tests/Unit/Pypp/CheckWithRandomValues.hpp
> +  // The Requires is used so that we can call the std::vector<std::string> with
move closer to Requires

2018-03-26 22:13 UTC, kidder commented on tests/Unit/Pypp/PyppPyTests.py
> +
DataVector (i.e. lose the s)

2018-03-26 23:15 UTC, kidder submitted a review, later dismissed

2018-03-26 23:25 UTC, kidder commented
@wthrowe if you have a chance, can you take a look at this

2018-03-27 02:20 UTC, wthrowe requested changes

2018-03-27 02:20 UTC, wthrowe commented on src/Utilities/TypeTraits.hpp
> +struct function_info_impl<Ret (*const)(Args...)> {
The `(*const)`, `(*const volatile)`, and `(*volatile)` function pointer specializations are unused because you `std::remove_cv_t` the function before passing it to the impl.

2018-03-27 13:23 UTC, nilsdeppe commented on src/Utilities/TypeTraits.hpp
> +struct function_info_impl<Ret (*const)(Args...)> {
They were used, I've removed the misleading `remove_cv_t`. I'm not sure why that doesn't remove the `cv` things in this case.

2018-03-28 17:37 UTC, wthrowe approved these changes

2018-03-28 17:43 UTC, kidder commented
merging as Travis mac builds are having trouble with timeouts;

2018-03-28 17:43 UTC, merged