Add actions GetItemFromDistributedObject, SimpleActionOnElement, and PrintDgElementArray (nodegroup support)
sxs-collaboration/spectre pull request #6161
Opened 2024-07-18 21:22 UTC by nilsdeppe

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-07-18 21:29 UTC, kidder requested changes

2024-07-18 21:29 UTC, kidder commented on src/ParallelAlgorithms/Actions/GetItemFromDistributedObject.hpp
> + * \brief A local synchronous action that rreturns a pointer to the tag.
returns a pointer to the item specified by the tag

2024-07-18 21:29 UTC, kidder commented on src/ParallelAlgorithms/Actions/GetItemFromDistributedObject.hpp
> + * retrieved tag must be ensure by the user.
ensured

2024-07-18 21:34 UTC, nilsdeppe commented
Done and squashed. Thanks!

2024-07-19 16:59 UTC, knelli2 approved these changes

2024-07-19 17:08 UTC, kidder approved these changes

2024-07-19 17:08 UTC, merged