Reorganize build system docs
sxs-collaboration/spectre pull request #6171
Opened 2024-07-20 00:03 UTC by knelli2

## Proposed changes

And also move them under `Installation` instead of the `Developers Guide`.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

Depends on #6164

2024-07-20 00:16 UTC, kidder requested changes

2024-07-20 00:16 UTC, kidder commented on docs/Installation/Installation.md
> +spectre_build_system pag. For instructions on installing SpECTRE on clusters
page

2024-07-30 23:49 UTC, knelli2 commented
Marking priority because this should be merged before the workshop

2024-07-31 21:03 UTC, knelli2 commented
@kidder could you take a look at this again?

2024-07-31 21:51 UTC, kidder requested changes

2024-07-31 21:51 UTC, kidder commented on docs/Installation/BuildSystem.md
> +alphabetical order):
while you're touching the file, alphabetize the list (BUILD_DOCS, DOCS_ONLY, the CMAKE_*, SPECTRE_DEBUG)

2024-07-31 21:51 UTC, kidder commented on docs/Installation/BuildSystem.md
> +set(LIBRARY_SOURCES
this is not true anymore.  we have `spectre_target_sources` and `spectre_target_headers`

2024-07-31 21:51 UTC, kidder commented on docs/Installation/BuildSystem.md
> +set(LIBRARY_SOURCES
see above

2024-08-01 01:21 UTC, knelli2 commented
@kidder posted a fixup since I edited a couple more things

2024-08-01 03:20 UTC, kidder reviewed
looks good, squash

2024-08-01 03:54 UTC, kidder approved these changes

2024-08-01 04:19 UTC, merged