Include what you use
sxs-collaboration/spectre pull request #618
Opened 2018-03-25 18:44 UTC by nilsdeppe

## Proposed changes

- Use LLVM5 and IWYU 0.9 with Travis
- Add mapping files for IWYU (see https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md)
- Run IWYU over entire source code and fix issues
- Make the `tests/Unit/TestingFramework.hpp` be the first include in all test source files. This resolves the ADL troubles we occasionally run into with some source files.

I'll add documentation on how to use the tools we supply in a dev guide entry later.

### Types of changes:

- [x] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [x] Build system
- [x] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-03-28 22:13 UTC, kidder requested changes
you can squash

2018-03-28 22:13 UTC, kidder commented on tools/Iwyu/iwyu.imp
> +  { symbol: ["gr::Tags::InverseSpacetimeMetric", private,
remove the two tags

2018-03-28 22:13 UTC, kidder commented on tools/Iwyu/iwyu.imp
> +  { include: ["<numpy/__multiarray_api.h>", private,
use consistent quoting for private and public

2018-03-28 22:13 UTC, kidder commented on .travis/RunIncludeWhatYouUse.sh
> +IWYU is still not yet fully mature and  provides incorrect suggests\n\
suggestions

2018-03-28 22:13 UTC, kidder commented on .travis/RunIncludeWhatYouUse.sh
> +  Have a header TagsDeclarations.hpp that declares\n\
have

2018-03-28 22:13 UTC, kidder commented on .travis/RunIncludeWhatYouUse.sh
> +  the default template parameters in more than one place, which is not\n\
missing "including"

2018-03-29 19:43 UTC, kidder approved these changes

2018-03-29 19:53 UTC, wthrowe approved these changes

2018-03-29 21:38 UTC, kidder commented
tests do not pass because of timeout of clang-tidy since every file was touched

2018-03-29 21:38 UTC, merged