Monte Carlo time stepping action
sxs-collaboration/spectre pull request #6198
Opened 2024-08-05 20:05 UTC by ffoucart

## Proposed changes

Add an action to take a single MC time step, and a test of using this action within the mock run environment.
Only the last commit is actually relevant; all others are from PR #6138 , which is a prerequisite to this PR.

### Upgrade instructions

None

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-08-27 00:14 UTC, nilsdeppe requested changes
LGTM, a few suggestions. You can squash them directly

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Actions/TimeStepActions.hpp
> +#include "Parallel/Printf/Printf.hpp"
remove? Leftover from debugging?

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Actions/TimeStepActions.hpp
> +
Need:
```cpp
#include <array>
#include <cstddef>
#include <optional>
#include <random>
#include <vector>
```

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Actions/TimeStepActions.hpp
> +// Mutator advancing neutrinos by a single step
triple slash for dox comment

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Actions/TimeStepActions.hpp
> +          single_packet_energy,
`const gsl::not_null`

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Actions/TimeStepActions.hpp
> +struct TakeTimeStep {
please add short dox comment :)

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Actions/TimeStepActions.hpp
> +#include "Evolution/DgSubcell/Tags/Coordinates.hpp"
Add include:
```cpp
#include "Evolution/DgSubcell/Tags/ActiveGrid.hpp"
```

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/NeutrinoInteractionTable.hpp
> +  void pup(PUP::er& p);
```cpp
void pup(PUP::er& p) override;
```

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/NeutrinoInteractionTable.cpp
> +  p | table_data;
Please add as first line:
```cpp
PUP::able::pup(p);
```
I think we need that for charm

2024-08-27 00:14 UTC, nilsdeppe commented on src/Evolution/Particles/MonteCarlo/Tags.hpp
> +struct RandomNumberGenerator : db::SimpleTag {
dox 3x

2024-08-28 12:57 UTC, ffoucart commented
Ok, I had missed a few initially, but I think now all comments have been addressed...

2024-08-28 22:07 UTC, nilsdeppe approved these changes

2024-08-28 22:07 UTC, nilsdeppe commented
CI is timeout in Cylindrical BBH domain, which is unrelated.

2024-08-28 22:07 UTC, merged