Extend test_map3d to other dimensions
sxs-collaboration/spectre pull request #623
Opened 2018-03-28 22:13 UTC by gsb76

## Proposed changes

In preparation for the future Affine2D map, I extended test_map3d to be able to work with 1 and 2 dimensional maps as well.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-03-28 23:04 UTC, kidder requested changes

2018-03-28 23:04 UTC, kidder commented on tests/Unit/Domain/DomainTestHelpers.hpp
> -          2 * get_nth_bit(index_, i) - 1 == 1 ? Side::Upper : Side::Lower;
leave this as it was (we don't like to compare doubles to ints)

2018-03-28 23:04 UTC, kidder commented on tests/Unit/Domain/DomainTestHelpers.hpp
> -          2 * get_nth_bit(index_, i) - 1 == 1 ? Side::Upper : Side::Lower;
is there a test for VolumeCornerIterator?  If not, make one; if yes, test your new function

2018-03-28 23:04 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> + * \brief Given a Map `map`, tests the map functions, including map inverse,
squash this commit with the previous one

2018-03-28 23:04 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  for (size_t i = 0; i < Map::dim; i++) {
get rid of xi, eta, zeta, origin3D and random_point3D and just inline (capture the seed instead of the values)

2018-03-31 02:50 UTC, nilsdeppe requested changes
I'm fine for you to squash my change requests

2018-03-31 02:50 UTC, nilsdeppe commented on tests/Unit/Domain/Test_DomainTestHelpers.cpp
> +#include <catch.hpp>
move TestingFramework.hpp to the top, remove catch

2018-03-31 02:50 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> -    test_inverse_map(map, point);
Let's implement this as:
```cpp
  const auto test_helper = [&origin, &random_point](const auto& lmap) noexcept {
  test_serialization(lmap);
  CHECK_FALSE(lmap != lmap);
  test_coordinate_map_argument_types(lmap, origin);

  test_jacobian(lmap, origin);
  test_inv_jacobian(lmap, origin);
  test_inverse_map(lmap, origin);

  for (VolumeCornerIterator<Map::dim> vci{}; vci; ++vci) {
    test_jacobian(lmap, vci.coords_of_corner());
    test_inv_jacobian(lmap, vci.coords_of_corner());
    test_inverse_map(lmap, vci.coords_of_corner());
  }

  test_jacobian(lmap, random_point);
  test_inv_jacobian(lmap, random_point);
  test_inverse_map(lmap, random_point);
  };
  test_helper(map);
  const auto map2 = serialize_and_deserialize(map);
  CHECK(map2 == map);
  test_helper(map2);
```

2018-04-02 15:51 UTC, nilsdeppe commented
IWYU is unhappy

2018-04-02 15:54 UTC, nilsdeppe requested changes
I'm fine for you to squash the one change

2018-04-02 15:54 UTC, nilsdeppe commented on tests/Unit/Domain/Test_DomainTestHelpers.cpp
> +void test_vci_1d() {
anonymous namespace

2018-04-02 20:06 UTC, kidder requested changes

2018-04-02 20:06 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  const auto seed = rd();
```
const auto seed  = std::random_device{}()
std::mt19937 gen(seed);
```

2018-04-02 20:06 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +      [&origin, &random_point ](const auto& lmap) noexcept {
lmap -> map_to_test

2018-04-02 20:06 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/TestMapHelpers.hpp
> +  test_helper(map2);
CHECK(map2(random_point) == map(random_point) or an existing function that does the same thing but doesn't do it by calling operator== or != . try check_if_maps_are_equal

2018-04-02 22:28 UTC, kidder approved these changes

2018-04-02 22:42 UTC, nilsdeppe approved these changes

2018-04-03 01:06 UTC, merged