Fix compatibility with Numpy 2.1
sxs-collaboration/spectre pull request #6232
Opened 2024-08-19 18:34 UTC by nilsvu

## Proposed changes

Something about symbol visibility changed in Numpy 2.1: https://numpy.org/doc/stable/reference/c-api/array.html#c.NPY_API_SYMBOL_ATTRIBUTE

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-08-19 18:47 UTC, knelli2 approved these changes

2024-08-19 22:23 UTC, knelli2 requested changes
The boost from Homebrew was updated from 1.85.0 to 1.86.0 and this is causing things to fail in macOS CI. Can you fix that as well here and update the installation page if we have to keep boost below 1.86.0?

2024-08-20 18:20 UTC, nilsvu commented
Added a fix for Boost v1.86.

2024-08-20 19:05 UTC, knelli2 approved these changes

2024-08-20 20:46 UTC, merged