Add single BH control system
sxs-collaboration/spectre pull request #6247
Opened 2024-08-24 21:28 UTC by knelli2

## Proposed changes

Controls object to the origin of the domain.

### Upgrade instructions

Must now specify a `Translation:` control system in `EvolveGhSingleBlackHole` input files.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-08-30 20:20 UTC, wthrowe requested changes

2024-08-30 20:20 UTC, wthrowe commented on src/ControlSystem/ControlErrors/Translation.cpp
> +template struct Translation<2_st>;
These don't do anything useful because the class is entirely defined in the hpp.

2024-08-30 20:20 UTC, wthrowe commented on support/Pipelines/Bbh/Ringdown.yaml
> +    IsActive: false
Did you want to turn this on?

2024-09-06 22:43 UTC, knelli2 commented
Squashed everything in

2024-09-09 20:57 UTC, wthrowe submitted a review, later dismissed
clang-tidy timed out for no obvious reason.  Rerunning to see if it was some sort of glitch.  If it still times out I'm not going to worry about it.

2024-09-09 21:39 UTC, knelli2 commented
@wthrowe I've seen clang-tidy time out on several PRs lately for what seems like no good reason (not that many files changed). I haven't tried to figure out why though

2024-09-10 17:31 UTC, wthrowe commented
Sounds like you fixed it in #6282.  Want to rebase to pick that up?

2024-09-10 18:07 UTC, knelli2 commented
I don't think #6282 was the issue as I'm pretty sure the clang-tidy timeouts were happening before I introduced that, but I rebased just in case.

2024-09-10 18:14 UTC, wthrowe commented
Actually, looks like your fix broke it more.  CI is spewing errors.

2024-09-10 18:17 UTC, wthrowe commented
And then reporting itself as passed.

2024-09-11 01:03 UTC, wthrowe approved these changes
Looks like that fixed clang-tidy.  One of the errors there is legitimate, but it wasn't introduced in this PR and we should get the fix in quickly, so I'm not going to worry about it.

2024-09-11 01:04 UTC, merged