Support complex numbers in DG routines
sxs-collaboration/spectre pull request #6252
Opened 2024-08-27 17:05 UTC by nilsvu

## Proposed changes

This completes the support for complex numbers in the DG code and tests it with the elliptic DG operator.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-08-30 17:41 UTC, nilsvu commented
@wthrowe would you be able to take this one?

2024-08-30 17:44 UTC, nilsvu commented
I also have a full integration test using the elliptic DG operator on a complex equation. I was going to add that in the next PR, but could push it here too if you prefer.

2024-08-30 18:09 UTC, wthrowe requested changes

2024-08-30 18:09 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_NormalDotFlux.cpp
> +    Tensor<DataType, Symm,
Call the test function with the new type.

2024-08-30 20:49 UTC, nilsvu commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Test_NormalDotFlux.cpp
> +    Tensor<DataType, Symm,
done

2024-08-30 21:15 UTC, wthrowe commented
I think you messed up rebasing or something.  You added a bunch of new commits that don't seem to compile.

2024-08-30 22:11 UTC, nilsvu commented
Oh sorry here's the fixup

2024-09-03 18:44 UTC, wthrowe commented
Looks good.  Squash.

2024-09-04 01:42 UTC, merged