Add outer_sphericity to Wedge3D
sxs-collaboration/spectre pull request #626
Opened 2018-04-02 16:05 UTC by gsb76

## Proposed changes

Also adds ASSERT tests

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-04-02 21:07 UTC, kidder requested changes

2018-04-02 21:07 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge3D.hpp
> + *  flat (a sphericity of 0) or spherical (a sphericity of 1).
or any value in between

2018-04-02 21:07 UTC, kidder commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +  CAPTURE_PRECISE(inner_sphericity);
capture the seed

2018-04-03 18:23 UTC, fmahebert commented
Since I missed some recent discussions: What prompted reversing the "one side is always spherical" design? Will this change also be made in 2D?

2018-04-03 18:39 UTC, mar-celine commented
@fmahebert Having an inner-spherical/outer-flat wedge makes it possible to wrap the cubed sphere in an enveloping cube - the BBH domain will use two cube-enveloped cubed-spheres

This could have been accomplished in other ways but I think this way is the cleanest and easiest to understand.

Updating the 2D one is at a lower priority, if it is updated I would prefer to do it once the 3D one is more or less finished as there are still being large changes made.

2018-04-03 19:22 UTC, wthrowe commented
Doesn't inner-spherical/outer-flat already work in the current version?  (Until you ASSERT that it isn't allowed in #621.)

2018-04-03 20:19 UTC, mar-celine commented
@wthrowe It is possible in the current version but that requires inverting the inner and outer surfaces which leads to a left handed coordinate system and then negating the x or y axes to go back to a right handed system (if we want to keep trying to only use right handed coordinate systems in domains). In the proposed version the user just needs to specify the outer sphericity. I would say this pull request isn't so much adding a new feature as it is making easier for the user to create a particular Wedge3D without worrying about possible consequences on the orientation.

2018-04-03 23:57 UTC, wthrowe commented
We are already using left-handed coordinate systems in domains.  In particular, RotatedIntervals.  As far as I am aware nothing should ever care about the orientation of the logical coordinates.

2018-04-04 01:42 UTC, gsb76 commented
You are right, there is nothing actually broken or missing with the current Wedge3D - all the wedges we want are possible and both left and right handed coordinate systems work. The orientations of the logical coordinates do matter only in one scenario which is in the DomainCreator. In my opinion it would be easier to work with the proposed Wedge3D as opposed to the current one. But, are there strong reasons for opposing this change?

2018-04-04 03:34 UTC, wthrowe commented
I think it's reasonable, and yes ease of use is a good argument.  I just wanted to make sure we understood what we were doing.

Another thought I just had: For BNS domains would we want to replace the cubes containing the holes with single blocks or bulged cubes surrounded by wedges?  This would be needed for the latter, but I'm not sure which domain is actually likely to perform better.

2018-04-04 04:22 UTC, mar-celine commented
I have also been wondering about what the difference is between a bulged cube versus a cube wrapped in wedges (since even a spherical-outer/flat-inner wedge has an interior which could be thought of as similar to that of a bulged cube's surface) or what the bulged cube accomplishes that can't be approximated using cubes and wedges - but I don't know the answer. @fmahebert and I talked in one pull request #334 about possible things to explore in future NS domains.

2018-04-05 16:02 UTC, nilsdeppe requested changes

2018-04-05 16:02 UTC, nilsdeppe commented on src/Domain/CoordinateMaps/Wedge3D.cpp
> +  ASSERT(sphericity_outer >= 0 and sphericity_outer <= 1,
0.0 and 1.0

2018-04-05 16:02 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> +  CAPTURE_PRECISE(inner_sphericity);
still need to do this

2018-04-05 16:02 UTC, nilsdeppe commented on tests/Unit/Domain/CoordinateMaps/Test_Wedge3D.cpp
> -      wedge_directions[5], 0, with_equiangular_map);
capture seed here too

2018-04-05 22:01 UTC, nilsdeppe submitted a review, later dismissed

2018-04-05 22:21 UTC, kidder submitted a review, later dismissed

2018-04-05 22:22 UTC, kidder commented
@wthrowe we think this is ready

2018-04-05 23:34 UTC, wthrowe requested changes

2018-04-05 23:34 UTC, wthrowe commented on src/Domain/CoordinateMaps/Wedge3D.hpp
>     */
There is a remaining reference to the "spherical surface" at the start of the above documentation.

2018-04-05 23:34 UTC, wthrowe commented on src/Domain/CoordinateMaps/Wedge3D.hpp
>   *  and the third to the radial coordinate.
There are references to the "spherical face" and the "bulged face" in the next paragraph.  (Outside the diff.)

2018-04-05 23:34 UTC, wthrowe commented on src/Domain/CoordinateMaps/Wedge3D.hpp
>   *  surface and outer surface. The inner surface can be given a curvature
"Each surface can be given..."

2018-04-06 20:02 UTC, kidder submitted a review, later dismissed

2018-04-07 01:38 UTC, nilsdeppe submitted a review, later dismissed
@wthrowe whenever you have a minute do you want to see if you have any more requests for this PR?

2018-04-07 08:09 UTC, fmahebert commented on src/Domain/CoordinateMaps/Wedge3D.hpp
>   *  radius `radius_of_outer_surface`, where the radius of the bulged face
I think it is clearer to say "the radius of each bulged face", as this is more consistent with having more than one bulged face.

2018-04-07 14:38 UTC, nilsdeppe approved these changes
@kidder yet again....

2018-04-07 20:15 UTC, kidder approved these changes

2018-04-08 22:32 UTC, wthrowe approved these changes

2018-04-08 23:13 UTC, merged