Add `UpdateFunctionsOfTime` action
sxs-collaboration/spectre pull request #6264
Opened 2024-09-03 12:58 UTC by nikwit

Adds the action that adjusts the functions of time according to the motion of the particle.

depends on #6255 #6261

2024-11-07 23:30 UTC, knelli2 requested changes

2024-11-07 23:30 UTC, knelli2 commented on tests/Unit/Helpers/Evolution/Systems/CurvedScalarWave/Worldtube/TestHelpers.cpp
> +      "      LMax: 2\n"
Why reduce l_max? For speed?

2024-11-07 23:30 UTC, knelli2 commented on tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/Test_Tags.cpp
>    const double angular_vel = 0.1;
[random line] Capitalize "Template" in commit message

2024-11-07 23:30 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/InitializeEvolvedVariables.hpp
> +    *expiration_time = initial_time + 1e-10;
Please add a comment why you chose this value.

2024-11-07 23:30 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
> +struct WorldtubeRadius : db::SimpleTag {
Is this tag only used in a test? Or will it also be used in source code later?

2024-11-07 23:30 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/UpdateFunctionsOfTime.hpp
> +                     control_system::UpdateMultipleFunctionsOfTime>(
If you want to avoid adding a dependency of the CSW system on the ControlSystem, you can just forward declare `control_system::UpdateMultipleFunctionsOfTime`. Then you can just add the dependency in the final exec (or test).

Probably we actually want to move `UpdateMultipleFunctionsOfTime` to some other common place like `ParallelAlgorithms`, but that's beyond this PR

2024-11-07 23:30 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/UpdateFunctionsOfTime.hpp
> +    expansion_update[1] = radial_vel / grid_radius_particle;
Rather than initializing a non-const DV, and then assigning afterwards, do
```cpp
const DataVector angular_update{atan2(y, x), (x * ydot - y * xdot) / square(r)};
```
and same for the other variables

2024-11-07 23:30 UTC, knelli2 commented on tests/Unit/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/Test_UpdateFunctionsOfTime.cpp
> +void test_particle_motion() {
This test could do with a couple more comments explaining what's happening

2024-11-12 14:37 UTC, nikwit commented on tests/Unit/Helpers/Evolution/Systems/CurvedScalarWave/Worldtube/TestHelpers.cpp
> +      "      LMax: 2\n"
yes, the worldtube always has to be spherical so the shape map is never used. This is the minimum l_max allowed by the shape map.

2024-11-12 15:47 UTC, nikwit commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/Tags.hpp
> +struct WorldtubeRadius : db::SimpleTag {
I included a use case in the fixup which uses the correct worldtube radius to compute the coefficients.

2024-11-12 18:52 UTC, knelli2 reviewed
Except for the clang-tidy errors and some missing tags in the tests, looks good.

2024-11-13 09:32 UTC, nikwit commented
My bad, I accidentally left out some of the changes. I pushed a new fixup.

2024-11-13 17:24 UTC, knelli2 approved these changes
Looks good, squash

2024-11-13 18:52 UTC, nikwit commented
done, thanks for the review!

2024-11-17 03:35 UTC, merged