Fix FPEs in tests
sxs-collaboration/spectre pull request #6265
Opened 2024-09-03 20:11 UTC by nilsdeppe

## Proposed changes

There are a couple MC neutrino tests I commented out because they're too hard for me to fix. That code isn't currently being used in simulations and will need a lot more debugging and testing in general. I'll talk with Francois Foucart about getting that fixed separately. My main goal is to just get FPEs on again in tests.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-09-03 21:12 UTC, wthrowe requested changes
Thanks for going through all these.  I agree we can deal with the MC problems later.

2024-09-03 21:12 UTC, wthrowe commented on src/NumericalAlgorithms/RootFinding/TOMS748.hpp
> +  // T d(std::numeric_limits<T>::quiet_NaN());
Remove.

2024-09-03 21:12 UTC, wthrowe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.cpp
> +    // set the result to zero by dividing by the max double.
It looks like you decided on a different implementation than this, without the max double part.

2024-09-03 21:12 UTC, wthrowe commented on src/Time/ChooseLtsStepSize.cpp
> +      desired_step == std::numeric_limits<double>::infinity()
This needs an `abs()`, since the step can be negative, or check for `desired_step_count == 0.0` instead.

2024-09-04 02:45 UTC, nilsdeppe commented
I made the changes. Since they are pretty small I just went ahead and squashed it. Partly to get this in before more FPEs appear 🙃

2024-09-04 17:51 UTC, wthrowe approved these changes
Looks good.  I would have requested a direct squash if I'd thought of it.

2024-09-04 17:51 UTC, merged