Observe worldtube position, velocity and acceleration
sxs-collaboration/spectre pull request #6272
Opened 2024-09-05 18:57 UTC by nikwit

2024-09-11 17:46 UTC, knelli2 requested changes
Squash immediately

2024-09-11 17:46 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SingletonActions/ObserveWorldtubeSolution.hpp
> +                    "Velz", "Accx", "Accy", "Accz", "Psi0", "dtPsi0"};
To keep this consistent with our other output of 3-vectors, can you do `Position_{x,y,z}`, `Velocity_{x,y,z}`, and `Acceleration_{x,y,z}`?

2024-09-16 09:07 UTC, nikwit commented
thanks for the review, I have squashed and rebased.

2024-09-16 23:39 UTC, knelli2 approved these changes

2024-09-17 17:16 UTC, knelli2 commented
Ignoring the clang-13 KerrSchild XCTS error because it's unrelated

2024-09-17 17:16 UTC, merged