Communicate volume mesh in boundary data
sxs-collaboration/spectre pull request #6293
Opened 2024-09-17 18:29 UTC by kidder

## Proposed changes

- Adds tag `evolution::dg::subcell::Tags::MeshForGhostData` which holds the volume mesh used by each neighbor for communicating subcell ghost data.  This information was previously held by `domain::Tags::NeighborMesh<Dim>` which will now always hold the mesh of the neighbor.
- Add the volume mesh to what is communicated via `BoundaryData`.  This is needed for reactive adaptive mesh refinement. 

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-09-17 18:31 UTC, kidder commented
@nilsdeppe please test this for a BNS

2024-09-17 19:02 UTC, nilsdeppe requested changes
Looks mostly reasonable. I'll give this a test.

2024-09-17 19:02 UTC, nilsdeppe commented on src/Evolution/DiscontinuousGalerkin/InboxTags.hpp
> -      auto& [volume_mesh_of_ghost_cell_data, face_mesh, ghost_cell_data,
Please also update `retrieve_boundary_data_spsc` in `src/Evolution/DiscontinuousGalerkin/Actions/ApplyBoundaryCorrections.hpp`

2024-09-23 21:20 UTC, kidder commented
@nilsdeppe 
- added a fixup which fixed a problem with blast wave.
- can you point me to a BNS setup I can test this on
- On line 111 of PrepareNeighborData, in the `alg::all_of(neighbor_meshes,...)`  should the meshes be the actual mesh of the neighbor or the ghost_data_mesh ?

2024-09-26 18:05 UTC, nilsdeppe approved these changes

2024-09-26 18:05 UTC, merged