Add test to evolve packet on Kerr background
sxs-collaboration/spectre pull request #6297
Opened 2024-09-18 19:19 UTC by SamanthaRath

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-09-18 19:20 UTC, SamanthaRath commented
@ffoucart

2024-09-19 14:49 UTC, ffoucart requested changes
Looks good to me, just add a few comments I think.

2024-09-19 14:49 UTC, ffoucart commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_EvolvePackets.cpp
> +}
This is from my own code but... could we add a comment here of the type

// We setup the inertial coordinates such that the element used for the evolution is centered on (6,0,0), and the jacobian matrix is the identity matrix

2024-09-19 14:49 UTC, ffoucart commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_EvolvePackets.cpp
> +  // Getting N and CFL constant
I think "Getting N" is not needed here.

2024-09-19 14:49 UTC, ffoucart commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_EvolvePackets.cpp
> +void test_evolve_kerr(const size_t mesh_size_1d) {
Add here a comment of the type
// Evolve a single Monte-Carlo packet along a geodesic of Kerr, and check that final position matches expectations.

2024-09-25 17:08 UTC, ffoucart submitted a review, later dismissed

2024-09-25 17:09 UTC, ffoucart commented
@nilsdeppe @kidder I reviewed this, not sure what is the process for others to have a look (I'm not a maintainer so the tests won't run just based on my review)

2024-09-25 17:52 UTC, ffoucart commented
@SamanthaRath Please look at the output of the test and fix as appropriate. For some of this, you'll want to compile your code in debug mode (some errors are just missing const and type conversions, but there is an array access out of bounds, which likely comes from some tensors being defined on the mesh without ghost zone when they need ghost zones)

2024-10-28 16:57 UTC, ffoucart commented
Note that this replaces #6008

2024-10-28 17:01 UTC, ffoucart commented
@kidder @nilsdeppe Could we run the test on this? Samantha uploaded changes that should handle the errors we got after rebasing against the new ghost zone code.
[Let me know if in the future I can just click 'run test' myself... it says maintainers only...]

2024-10-28 17:25 UTC, kidder commented
Okay, I've never seen this message before

2024-10-28 17:29 UTC, ffoucart commented
Alright, I'll ignore it then. I don't see why we shouldn't run the test...

2024-10-31 15:48 UTC, ffoucart approved these changes
Good for me now!

2024-10-31 15:49 UTC, ffoucart commented
@nilsdeppe @kidder Should be ready for someone else to look at it if desired.

2024-11-21 20:07 UTC, ffoucart commented
@nilsdeppe @kidder Ping on this (I reviewed the PR, but probably shouldn't commit... especially as I wrote part of the submitted code...)

2025-01-07 20:09 UTC, nilsdeppe approved these changes
Looks great! My apologies for taking unacceptably long to look at this!

2025-01-07 20:09 UTC, merged