Strahlkorper documentation
sxs-collaboration/spectre pull request #630
Opened 2018-04-04 22:53 UTC by markscheel

## Proposed changes

Improve documentation of StrahlkorperTags functions.  No code changes; only documentation.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-04-05 21:40 UTC, fmahebert commented
@geoffrey4444 and @haraldp271: You may want to look at this, because these documentation changes were motivated by a Slack discussion you participated in.

2018-04-10 16:28 UTC, geoffrey4444 submitted a review, later dismissed

2018-04-18 20:31 UTC, kidder commented
@haraldp271  please look at this;

2018-04-25 15:43 UTC, nilsdeppe requested changes
I think you can do all of this as one commit :) I'm also happy for you to squash my requested change right away.

2018-04-25 15:43 UTC, nilsdeppe commented on src/ApparentHorizons/StrahlkorperDataBox.hpp
> +/// \f$(\theta,\phi)\f$. \f$\partial/\partial q^0\f$ means
Could you end the "brief" part of the documentation at this period? This means just adding a `///` line after the period. The brief is extreme long in this case.

2018-04-25 17:45 UTC, nilsdeppe approved these changes

2018-04-25 17:45 UTC, nilsdeppe commented
@geoffrey4444 @kidder @wthrowe could you look at this one last time?

2018-04-28 02:21 UTC, kidder approved these changes

2018-04-30 13:42 UTC, geoffrey4444 approved these changes

2018-04-30 16:33 UTC, merged