Allow observing only some blocks in ObserveFields
sxs-collaboration/spectre pull request #6305
Opened 2024-09-25 14:58 UTC by nilsdeppe

## Proposed changes

This is useful for visualizations, e.g. in a BNS simulation we only care about the stars, not the matter in the wave zone.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-09-27 20:33 UTC, kidder approved these changes

2024-09-27 20:33 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveFields.hpp
> +  /// Set to `All` to observer everywhere.
observe

2024-09-27 20:34 UTC, kidder requested changes
squash the requested change

2024-09-27 20:40 UTC, nilsdeppe commented
Done and rebased. Thanks for the review!

2024-09-27 20:54 UTC, nilsvu submitted a review, later dismissed
Nice!

2024-09-27 20:56 UTC, kidder submitted a review, later dismissed

2024-09-28 01:31 UTC, nilsdeppe commented
Sorry, had to fix a silent conflict with include file names.

2024-09-28 01:32 UTC, kidder approved these changes

2024-09-28 03:35 UTC, merged