Avoid running out of disk space on CI
sxs-collaboration/spectre pull request #6313
Opened 2024-09-27 22:53 UTC by nilsvu

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-09-27 22:54 UTC, knelli2 approved these changes

2024-09-27 23:51 UTC, knelli2 requested changes
Hmm clang-14 Debug still ran out of space...

2024-09-28 01:09 UTC, knelli2 requested changes

2024-09-28 01:09 UTC, knelli2 commented on .github/workflows/Tests.yaml
> +          rm bin/Test_*
```
rm -f bin/Test_*
```

Maybe also add a `pwd` so it's easy to know which directory we are seeing (I know it's build but I'll forget next week)

2024-09-28 07:01 UTC, knelli2 approved these changes

2024-09-28 16:04 UTC, kidder approved these changes

2024-09-28 16:04 UTC, merged