Enable p-refinement via an Event
sxs-collaboration/spectre pull request #6320
Opened 2024-10-02 01:30 UTC by kidder

## Proposed changes

This PR will allow p-refinement to be done as an Event.
This requires the DG scheme to reactively check if the communicated mortar data is on the correct Mesh.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-10-02 16:41 UTC, wthrowe requested changes
clang-tidy errors are not in our code and probably wrong, so nothing to do for those.

2024-10-02 16:41 UTC, wthrowe commented on src/Evolution/DiscontinuousGalerkin/BoundaryData.hpp
>   * 3. the mesh of the neighboring element's face (not the mortar mesh!)
Renumber the later entries.  (The numbering being wrong actually confuses doxygen, which surprises me.)

2024-10-02 16:41 UTC, wthrowe commented on src/Evolution/DiscontinuousGalerkin/InboxTags.hpp
>   * 3. the mesh of the neighboring element's face (not the mortar mesh!)
Again, fix numbering.

2024-10-02 16:41 UTC, wthrowe commented on src/NumericalAlgorithms/DiscontinuousGalerkin/MortarHelpers.cpp
> +           "face_mesh1 is "
[optional] formatting

2024-10-02 16:41 UTC, wthrowe commented on src/ParallelAlgorithms/Amr/Events/Events.hpp
> +/// \brief %Eventss for adaptive mesh refinement
Sspelling.

2024-10-02 16:41 UTC, wthrowe commented on src/Evolution/DiscontinuousGalerkin/Actions/ApplyBoundaryCorrections.hpp
> +                  project_boundary_mortar_data);
Call `boundary_data_history->at(mortar_id).clear_coupling_cache()`.

2024-10-02 16:41 UTC, wthrowe commented on src/Evolution/DiscontinuousGalerkin/Actions/ApplyBoundaryCorrections.hpp
> +                  project_boundary_mortar_data);
Again, clear the cache, unless this is only modifying the entry that was just inserted, in which case add a comment that you don't have to clear the cache.

2024-10-02 16:41 UTC, wthrowe commented on src/Evolution/DiscontinuousGalerkin/Actions/ApplyBoundaryCorrections.hpp
> +                     "RIP\n");
Better message?  Probably print out the values.

2024-10-02 16:41 UTC, wthrowe commented on src/ParallelAlgorithms/Amr/Events/Events.hpp
> +namespace amr::Events {}  // namespace amr::Events
Move reformatting to the commit where it was added.  Also remove the same-line closing comment.

2024-10-02 16:41 UTC, wthrowe commented on tests/Unit/Evolution/DiscontinuousGalerkin/Actions/Test_ApplyBoundaryCorrections.cpp
> +      const evolution::dg::BoundaryData<Dim> data{mesh,
Move to appropriate commit.

2024-10-02 18:25 UTC, nilsdeppe requested changes

2024-10-02 18:25 UTC, nilsdeppe commented on src/NumericalAlgorithms/DiscontinuousGalerkin/MortarHelpers.cpp
> +           "but "
Combine lines

2024-10-02 18:25 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Events/RefineMesh.hpp
> +  explicit RefineMesh(CkMigrateMessage* /*unused*/) {}
move to cpp

2024-10-02 18:25 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Events/RefineMesh.hpp
> +  RefineMesh() = default;
move to cpp

2024-10-02 18:25 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Events/RefineMesh.hpp
> +
Do you need a `pup` function?

2024-10-02 18:25 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Events/RefineMesh.hpp
> +        }
Should we choose p-refine if we get split? And p-coarsen if we get Join? Or just ignore for now? It might be good to have an ERROR since this would indicate a decision is being ignored.

2024-10-02 18:25 UTC, nilsdeppe commented on src/Evolution/DiscontinuousGalerkin/Actions/ApplyBoundaryCorrections.hpp
> +                     "RIP\n");
A bit more info would be helpful :)

2024-10-02 20:56 UTC, knelli2 reviewed
No need to wait for my approval

2024-10-02 20:56 UTC, knelli2 commented on src/Evolution/DiscontinuousGalerkin/Initialization/Mortars.hpp
> +    const ::dg::MortarMap<Dim, Mesh<Dim>>& neighbor_mesh,
Should these changes go in a different commit?

2024-10-05 03:02 UTC, nilsdeppe submitted a review, later dismissed
My requests have been addressed. I don't need to look at this again before it's merged.

2024-10-07 20:25 UTC, wthrowe commented
Still missing the LTS cache management.  Have you tested this in an LTS evolution?

2024-10-16 03:03 UTC, wthrowe approved these changes

2024-10-16 03:05 UTC, wthrowe commented
We discussed some methods of testing this elsewhere.  I assume you've done some of those?

2024-10-17 21:05 UTC, wthrowe commented
Discussed elsewhere.  The tests have been done.

2024-10-17 21:05 UTC, merged