Allow three extra refinement levels for an ElementId
sxs-collaboration/spectre pull request #6347
Opened 2024-10-21 21:36 UTC by kidder

This is done by using a compact representation of a SegmentId. Also fix some clang-tidy errors.

## Proposed changes

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-10-22 21:45 UTC, nilsdeppe requested changes

2024-10-22 21:45 UTC, nilsdeppe commented on src/Utilities/StdHelpers/Bit.hpp
> +}  // namespace std
We should only be adding this into the std namespace if it's not defined in the standard, otherwise we hit UB. There's is identically 0 chance that people will correctly place the if-else checks for the includes in all the right places.

Also, please make adding this a separate commit.

Make sure to add a code comment into this file explaining why this was necessary.

2024-10-22 21:45 UTC, nilsdeppe commented on src/Domain/Structure/SegmentId.cpp
> +  ASSERT(refinement_level <= max_refinement_level,
Just remove this check. It's not a constraint on `SegmentId` but a constraint on `ElementId`

2024-10-22 21:45 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.cpp
> +#endif
This check should be in the `Bit.hpp` file. Nobody will know to do this magic when including that file.

2024-10-22 21:45 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.cpp
> +              SegmentId::max_refinement_level);
I think we can remove these checks since there's no actual restriction on `SegmentId`

2024-10-22 21:45 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.cpp
> +  return SegmentId{get_refinement_level(compact_segment_id),
Add the `ASSERT` here too about  undefined compact segment id?

2024-10-22 21:45 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.cpp
> +size_t get_index(uint16_t compact_segment_id) {
`const uint16_t`?

2024-10-22 21:45 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.cpp
> +size_t get_refinement_level(uint16_t compact_segment_id) {
`const uint16_t`?

2024-10-22 21:45 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.cpp
> +  return 16 == std::countl_zero(compact_segment_id) +
I would find this easier to read as `16 == (...)`

2024-10-22 21:45 UTC, nilsdeppe commented on src/Domain/Structure/ElementId.cpp
> +                                uint16_t compact_segment_id_zeta)
`const uint?_t`

2024-10-24 04:17 UTC, nilsvu submitted a review, later dismissed
This is pretty cool 😎 thanks for doing this.

2024-10-24 16:58 UTC, nilsdeppe reviewed
LGTM, could you move the adding of `std::bit_*` into a separate commit as you squash?

2024-10-24 21:48 UTC, nilsdeppe approved these changes

2024-11-04 21:06 UTC, merged