Executable for MC: initialize background
sxs-collaboration/spectre pull request #6355
Opened 2024-10-30 14:44 UTC by ffoucart

## Proposed changes

Create base MC executable

### Upgrade instructions

None so far

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-10-30 14:44 UTC, ffoucart commented
Work in progress -- first commit creates the background fluid and metric variables, EoS and neutrino table.

2024-10-30 14:46 UTC, ffoucart commented
@nilsdeppe Not sure if we want one big PR for the MC code, or to commit partial work once we have something useful. I'm keeping the work we have done so far (slightly cleaned up for compatibility with other executables) here.

2024-12-06 16:01 UTC, ffoucart commented
Rebased on develop to fix minor conflict with RunEventsAndTriggers (template change, option renamed)

2024-12-23 15:17 UTC, ffoucart commented
Rebased to make dependent on #6424 . The first commit is now from that PR, the second commit creates the executable; the final part to make it work with input files is in #6403

2025-01-24 18:48 UTC, ffoucart commented
Rebased on develop after merging #6424

2025-01-24 19:38 UTC, kidder requested changes

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Executables/RadiationTransport/MonteCarlo/EvolveMonteCarlo.hpp
> +          evolution::dg::Initialization::Domain<volume_dim>  //,
remove the comment at the end of the line

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Executables/RadiationTransport/MonteCarlo/EvolveMonteCarlo.hpp
> +                  Actions::AdvanceTime,
comment why these actions are repeated and if you plan to change how this works in the future

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/Actions/InitializeMonteCarlo.hpp
> +          const size_t num_grid_points =
You've already retrieved this above, so just capture it in the lambda

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/Actions/InitializeMonteCarlo.hpp
> +    const size_t num_grid_points =
This assumes that Tags::ActiveGrid is ActiveGrid::Subcell.  Instead check what the value is and either ERROR or update to handle correctly if it is ActiveGrid::Dg

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/Actions/InitializeMonteCarlo.hpp
> +        std::random_device{}();  // static_cast<unsigned long>(time(NULL));
remove commented code

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/Actions/TimeStepActions.hpp
> +    tnsr::iJJ<DataVector, 3, Frame::Inertial> d_inv_spatial_metric =
call the existing function in PointwiseFunctions/GeneralRelativity/DerivativeSpatialMetric.hpp

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp
> +                // REQUIRE(received_data[directional_element_id]
remove

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp
> +                // REQUIRE(received_data[directional_element_id]
remove

2025-01-24 19:38 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/System.hpp
> +  // Hydro tags needed for background metric
why metric?

2025-01-24 21:53 UTC, ffoucart commented on src/Evolution/Executables/RadiationTransport/MonteCarlo/EvolveMonteCarlo.hpp
> +                  Actions::AdvanceTime,
Good catch.
This is because MC only occurs after a full step, not intermediate step, and I am using a RK3 time stepper. That's not a good reason of course. What I should have here is some way to loop over all intermediate time steps of the time stepper and for each step do (AdvanceTime, RunEvents). Is there a simple way to do that for a generic timestepper with arbitrary number of intermediate steps?
We could also require MC to use forward Euler when not coupled to the fluid/metric. As that's what the code is actually doing at the moment, regardless of the choice of timestepper in the input files.

2025-01-25 00:55 UTC, kidder commented on src/Evolution/Executables/RadiationTransport/MonteCarlo/EvolveMonteCarlo.hpp
> +                  Actions::AdvanceTime,
Okay I discussed with @nilsdeppe and we think you should be able to use something like the `Actions::Label` that are used to switch between Dg actions and subcell actions.  So you would surround the MC actions with two labels (e.g. BeginMonteCarlo and EndMonteCarlo).  Then you can add an action immediately before the BeginMonteCarlo label similar to `evolution::dg::subcell::Actions::SelectNumericalMethod` that will test whether the time substep is 0 and choose which label to jump to.  This then will be independent of the time stepper choice.

2025-01-27 15:59 UTC, ffoucart commented on src/Evolution/Executables/RadiationTransport/MonteCarlo/EvolveMonteCarlo.hpp
> +                  Actions::AdvanceTime,
Thanks. I got it to work, but please look at the new Labels.hpp and TriggerMonteCarlo.hpp files as well as the action list to check that it is what you had in mind. These are the main changes in the new version of the PR (the other comments were fairly simple to take care of).

2025-01-27 16:06 UTC, kidder reviewed
Looks good to me, you can squash

2025-01-27 16:09 UTC, ffoucart commented
Thanks. Will wait for the tests to complete here, then work on rebasing the next PR against these changes.

2025-01-28 01:39 UTC, ffoucart commented
Tests only failing due to Timeout in an unrelated test (I tried to rerun, but the same test failed twice)

2025-01-28 01:41 UTC, merged