Fix bugs in RefineMesh Event
sxs-collaboration/spectre pull request #6358
Opened 2024-11-01 01:22 UTC by knelli2

## Proposed changes

Also adds an option in the input file to choose whether the code should error if it tries to refine beyond the limits (but is stopped by enforcing the limits) since this could be an indicator of something going wrong. Currently, I set it to *not* error in all the executables to keep the original behavior. If we decide this is something we want to turn on in certain executables, we can do so later.

### Upgrade instructions

Must add a new option `ErrorBeyondLimits: False` to the AMR limits section, i.e.

```yaml
Amr:
  ...
  Policies:
    ...
    Limits:
      ...
      ErrorBeyondLimits: False
```

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-11-04 17:28 UTC, kidder requested changes
you can squash the fix

2024-11-04 17:28 UTC, kidder commented on src/ParallelAlgorithms/Amr/Policies/Limits.hpp
> +        "If p-refinement tries to go beyind the RefinementLevel or "
p-refinement -> adaptive mesh refinement
beyind -> beyond

2024-11-04 18:52 UTC, knelli2 commented on src/ParallelAlgorithms/Amr/Policies/Limits.hpp
> +        "If p-refinement tries to go beyind the RefinementLevel or "
Done!

2024-11-04 19:30 UTC, nilsvu requested changes

2024-11-04 19:30 UTC, nilsvu commented on src/ParallelAlgorithms/Amr/Policies/EnforcePolicies.hpp
> +///   `amr::Limits::LimitType`s that were obeyed in each direction. Otherwsie,
typo "otherwise"

2024-11-04 19:30 UTC, nilsvu commented on src/ParallelAlgorithms/Amr/Policies/Limits.hpp
> +///   Mesh. There is no error for attemtping to go beyind the limits.
typo "attempting", "beyond"

2024-11-04 19:30 UTC, nilsvu commented on src/ParallelAlgorithms/Amr/Actions/EvaluateRefinementCriteria.hpp
> +      ERROR("Tried refining beyond the AMR limits in element "
Throw this error inside `amr::enforce_policies`. Then you don't need to return anything, don't need the enum, don't have to repeat the error, and it just seems easier overall.

2024-11-04 19:30 UTC, nilsvu commented on docs/DevGuide/Amr.md
>  "When" AMR happens is contolled by specifying a Trigger and a list of
typo "controlled" (not yours but might as well fix)

2024-11-04 20:09 UTC, knelli2 commented
@nilsvu That simplified things a bit

2024-11-04 20:20 UTC, nilsvu requested changes

2024-11-04 20:20 UTC, nilsvu commented on docs/DevGuide/Amr.md
> +"When" AMR happens is conrtolled by specifying a Trigger and a list of
oops :D

2024-11-04 20:20 UTC, nilsvu commented on docs/DevGuide/Amr.md
> +limits set by the code. Also note that if a criteria tries to refine beyond the
"criteria try"

2024-11-04 20:20 UTC, nilsvu commented on src/ParallelAlgorithms/Amr/Policies/EnforcePolicies.hpp
> +///   `amr::Limits::LimitType`s that were obeyed in each direction. Otherwise,
update docs

2024-11-04 20:26 UTC, knelli2 commented on docs/DevGuide/Amr.md
> +"When" AMR happens is conrtolled by specifying a Trigger and a list of
Oops...

2024-11-05 17:54 UTC, kidder requested changes
you can squash

2024-11-05 17:54 UTC, kidder commented on src/ParallelAlgorithms/Amr/Policies/Limits.hpp
> +#include <ostream>
don't need this include

2024-11-05 17:54 UTC, kidder commented on src/ParallelAlgorithms/Amr/Policies/Limits.cpp
> +#include <ostream>
don't need this include

2024-11-05 18:19 UTC, kidder approved these changes

2024-11-05 19:19 UTC, nilsvu approved these changes

2024-11-05 19:20 UTC, merged