Add characteristics for the Newtonian Euler system
sxs-collaboration/spectre pull request #636
Opened 2018-04-05 21:24 UTC by carmaza

## Proposed changes

Add the characteristic decomposition for the Newtonian Euler system.

- Add `State` `IndexType`, which denotes that the object lives in an Euclidean space of dimension equal to the dimension of the state vector of the system. This is the space where the characteristic decomposition lives.
- The characteristic decomposition is tested using normal vectors along randomized directions, as well as normal vectors along the coordinate axes.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-04-06 03:16 UTC, osheamonn requested changes

2018-04-06 03:16 UTC, osheamonn commented on tests/Unit/Evolution/Systems/NewtonianEuler/TestFunctions.py
> +    for i in range(0, dim):
This can be done using numpy array slicing as `result[1:,0] = velocity - sound_speed_times_normal` without the for loop

2018-04-06 03:16 UTC, osheamonn commented on tests/Unit/Evolution/Systems/NewtonianEuler/TestFunctions.py
> +        for i in range(0, dim):
`result[1:,1] = tang_1`, and pretty much anywhere else you use a `for` loop below.

2018-04-06 21:58 UTC, gsb76 commented on src/Evolution/Systems/NewtonianEuler/Characteristics.hpp
> +void left_eigenvectors(
We dont think you need to have the left and right eigenvectors coded up explicitly, things like the marquina flux should be specialized to the system

2018-04-07 01:46 UTC, nilsdeppe commented
So following today's discussion with Will and Larry, we do want the characteristics speeds, but it's really not at all clear to us the matrices are useful. We think it'll be important to specialize numerical fluxes like the Marquina and Roe flux to the individual systems to be able to optimize performance since we will be computing numerical fluxes quite a bit. A Slack discussion with @fmahebert makes me think that computing the characteristic variables would be useful for limiting. Specifically, I think it will be very important to compare how limiting characteristic variables compares with conservatives, especially for higher-order limiters and higher-order elements.

2018-04-23 21:50 UTC, osheamonn requested changes

2018-04-23 21:50 UTC, osheamonn commented on src/Evolution/Systems/NewtonianEuler/Characteristics.cpp
> +  auto characteristic_speeds = make_array<Dim + 2>(DataVector(normal_velocity));
Inline normal_velocity construction

2018-04-23 21:50 UTC, osheamonn commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
> +tnsr::i<DataVector, Dim> normal_along_axis(
Factor this into a file, possible in DomainHelpers.hpp and do every direction using the `Direction<Dim>` type.

2018-04-23 21:50 UTC, osheamonn commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
> +
Do for loop over `all_directions` for each dimension.

2018-05-01 19:39 UTC, mar-celine reviewed
squash

2018-05-01 19:39 UTC, gsb76 commented on tests/Unit/Domain/DomainTestHelpers.cpp
> +template <size_t SpatialDim, typename SpatialFrame>
change name to euclidean_basis_vector

2018-05-01 19:39 UTC, gsb76 commented on tests/Unit/Domain/Test_DomainTestHelpers.cpp
> +  for (size_t i = 0; i < directions.size(); ++i) {
`for(const auto& direction : Direction<SpatialDim>::all_directions()){
...
}`
you wont need line 92 nor line 95

2018-05-01 19:39 UTC, gsb76 commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_Characteristics.cpp
> +  for (size_t i = 0; i < 2 * Dim; ++i) {
also use range based for loop here

2018-05-01 23:02 UTC, mar-celine approved these changes
@kidder @osheamonn let's approve this

2018-05-02 01:26 UTC, nilsdeppe approved these changes

2018-05-02 03:39 UTC, osheamonn approved these changes

2018-05-02 04:51 UTC, kidder approved these changes

2018-05-02 04:51 UTC, merged

2018-05-02 06:37 UTC, wthrowe commented
I would appreciate being given a chance to give input on things like this if I ask for changes in the code review meeting.  The issue I pointed out still stands.  This is incompatible with our evolution code in its current form because the normal vectors have the wrong valence.

2018-05-02 16:05 UTC, kidder commented
@wthrowe sorry, I wasn't at the code review meeting, and I did not see a comment asking for this, but I probably should let someone at Cornell push the merge button when I am traveling...