Add event to observe AMR criteria
sxs-collaboration/spectre pull request #6369
Opened 2024-11-09 01:48 UTC by kidder

## Proposed changes

This adds an event to observe the decisions of AMR criteria.  It can be used independently of actually refining the grid.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2024-11-11 16:33 UTC, nilsdeppe commented
:( Needs a rebase

2024-11-12 14:59 UTC, nilsdeppe requested changes
LGTM, some suggestions. Please squash immediately.

2024-11-12 14:59 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveConstantsPerElement.hpp
> +class ObserveConstantsPerElement : public Event {
Bruh, document the class.

2024-11-12 14:59 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveConstantsPerElement.hpp
> +               const ObservationValue& observation_value) const;
Since these are all part of the API, could you please document them a bit? When should a derived class call what?

2024-11-12 14:59 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveConstantsPerElement.hpp
> +  ::FloatingPointType floating_point_type_ = ::FloatingPointType::Double;
Can these not be private with const accessors?

2024-11-12 14:59 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveConstantsPerElement.cpp
> +    CkMigrateMessage* /*unused*/) {}
pass to base: `: Event(msg)`

2024-11-12 14:59 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveConstantsPerElement.hpp
> +  std::vector<TensorComponent> allocate_and_insert_coords(
What does this allocate? All this seems to do is give the corner points in a data structure. Maybe just name it `get_corner_coordinates`?

2024-11-12 14:59 UTC, nilsdeppe commented on src/ParallelAlgorithms/Amr/Events/ObserveAmrCriteria.hpp
> +/// - 5.0 is for splitting the element
Question/suggestion: Have positive and negative numbers is sort of nice for visualization. You could do something like `static_cost<double>(...) - 3.0`. For the TCI we have negative and positive and it makes it easy to see at a quick glance what's going on.

2024-11-12 18:58 UTC, knelli2 commented on src/ParallelAlgorithms/Amr/Events/ObserveAmrCriteria.hpp
> +/// - 5.0 is for splitting the element
Just a drive by comment, but I like this suggestion. 0.0 is very natural for "no change" and having positive = "more" and negative = "fewer" is also very intuitive.

2024-11-12 20:18 UTC, kidder commented
@wthrowe did you want to look at this before I push fixups?

2024-11-12 21:28 UTC, wthrowe commented
Looks fine.  I have no additional comments.

2024-11-12 22:32 UTC, kidder commented on src/ParallelAlgorithms/Events/ObserveConstantsPerElement.hpp
> +  std::vector<TensorComponent> allocate_and_insert_coords(
it also reserves the correct size for the components; do you still want the rename?

2024-11-13 01:54 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveConstantsPerElement.hpp
> +  std::vector<TensorComponent> allocate_and_insert_coords(
that's fine, just make sure it's clearly documented

2024-11-13 19:13 UTC, nilsdeppe reviewed
LGTM, please fix the typo when you squash.

2024-11-13 19:13 UTC, nilsdeppe commented on src/ParallelAlgorithms/Events/ObserveConstantsPerElement.hpp
> +  /// that will observed.  These are added by calling add_constant
`will observed` -> `will be observed` (missing `be`)

2024-11-14 15:04 UTC, nilsdeppe approved these changes

2024-11-14 15:05 UTC, merged