Add self force turn on function
sxs-collaboration/spectre pull request #6385
Opened 2024-11-23 10:23 UTC by nikwit

Adds the turn on function used to continuously turn on the self force.

2024-11-25 18:13 UTC, knelli2 requested changes
These and clang-tidy. You can squash directly

2024-11-25 18:13 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SelfForce.hpp
> + * the timescale over which it is turned on. The function is $\mathcal{C}^3$,
Wait is $t$ a single time, or is it just the current time? Seems like it's $t = t_{\mathrm{cur}} - t_{\mathrm{ON}}$. Update somehow to make this clearer.

2024-11-25 18:13 UTC, knelli2 commented on src/Evolution/Systems/CurvedScalarWave/Worldtube/SelfForce.cpp
> +         square(square(turn_on_timescale));
[optional] Less operations
```cpp
  const double t_over_timescale_quart = square(square(time / turn_on_timescale));
  return 4. * t_over_timescale_quart * exp(-t_over_timescale_quart) / time;
```

2024-11-26 16:24 UTC, nikwit commented
done. Thanks for the review!

2024-11-27 00:18 UTC, knelli2 approved these changes

2024-11-27 00:18 UTC, merged