Add features to CCE worldtube buffer updaters
sxs-collaboration/spectre pull request #6397
Opened 2024-12-05 08:23 UTC by knelli2

## Proposed changes

This PR allows CCE to be able to read in metric modal, metric nodal, bondi modal, and bondi nodal data from disk. 
Another feature addition is that data can be read in in time-varies-fastest form which is useful for time interpolation, or in modes/nodes-varies-fastest which is more useful for just reading in data at specific times. There is no functionality change to the current CCE code, only new features.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

Depends on and includes #6396 .

2024-12-12 23:37 UTC, nilsdeppe requested changes

2024-12-12 23:37 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/WorldtubeBufferUpdater.cpp
> +    }
What's the compiler warning? Can you make this a ternary or does that cause issues?

2024-12-12 23:37 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/WorldtubeBufferUpdater.cpp
> +          // If this quantity is real we don't expect to write the imaginary m=0
`write` -> `store`? I was trying to figure out if this writes a file, which I guess sort of? But the local code here just handles the data

2024-12-12 23:37 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/WorldtubeBufferUpdater.cpp
> +      // in the real and imaginary components
Hold up, I'm confusing. Is this nodal Bondi data? Not nodal metric data, right? To be clear, `read_data` is either modal or nodal Bondi data, always?

2024-12-12 23:37 UTC, nilsdeppe commented on src/Evolution/Systems/Cce/WorldtubeBufferUpdater.cpp
> +  // We require these to be the same since for nodal data since we can't easily
remove second `since` (`since we can't easily` -> `we can't easily`)

2024-12-13 17:40 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeBufferUpdater.cpp
> +      // in the real and imaginary components
Yes in this function only Bondi data is used. So it's used for both modal and nodal Bondi

2024-12-13 18:08 UTC, knelli2 commented on src/Evolution/Systems/Cce/WorldtubeBufferUpdater.cpp
> +    }
I think that comment was there previously so I'm not sure what the warning was. I made it a ternary and clang-tidy passed locally so we'll go with that

2024-12-13 18:08 UTC, knelli2 commented
@nilsdeppe pushed a short fixup

2024-12-13 18:28 UTC, nilsdeppe reviewed
LGTM! Please squash! Thanks for doing a fixup! Made it easy to find :D

2024-12-13 22:07 UTC, nilsdeppe approved these changes

2024-12-13 22:08 UTC, nilsdeppe commented
CI failure is unrelated elliptic thing.

2024-12-13 22:08 UTC, merged