Mc optically thick sphere
sxs-collaboration/spectre pull request #6403
Opened 2024-12-10 20:39 UTC by ffoucart

## Proposed changes

Add initial conditions for a homogeneous sphere (fluid variables only determined by whether we are inside or outside the sphere)

### Upgrade instructions

None

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

2024-12-10 20:39 UTC, ffoucart commented
Depends on #6355 (first five commits are from that PR)

2024-12-26 18:25 UTC, ffoucart commented
Updated so that first two commits match #6355 and third commit is the new work.
Note that in addition of creating input file options for MC, this PR fixes a bug in the initialization of the MortarData.

2025-02-20 18:56 UTC, kidder requested changes
please make changes in a fixup commit

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Executables/RadiationTransport/MonteCarlo/EvolveMonteCarlo.hpp
> +      tmpl::list<evolution::dg::subcell::Tags::ObserverCoordinatesCompute<
you should make the tags of ObserverCoordinates conditional on `use_dg_subcell` like is done in EvolveValenciaDivClean

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Executables/RadiationTransport/MonteCarlo/EvolveMonteCarlo.hpp
> +      tmpl::list<evolution::dg::subcell::Tags::ObserverMeshCompute<volume_dim>,
again conditional on `use_dg_subcell`

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/CellCrossingTime.cpp
> +  get(*cell_light_crossing_time) = DataVector(n_pts,0.0);
just need number of points, don't have to initialize to a value as it is overwritten

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp
> +                    Packet& packet = received_data_packets.value()[p];
I think this can be simplified a lot as the computation is done in ElementLogicalCoordinates.
In each dimension there are n = extents[d] subcells of uniform size and the grid points are at cell centers.  Therefore you just need to determine which cell they are in which is given by  cell_index[d] = `std::floor(packet.coordinate[d] + 1.0)/(2*n)` and then `index_of_closest_grid_point = collapsed_index(cell_index, extents)`.  I guess you need to add a special case if the packet coordinate is 1.0

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.cpp
> +#include <cmath>
don't need

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.cpp
> +#include <hdf5.h>
don't need

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.cpp
> +#include <string>
don't need

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/CMakeLists.txt
> +  NeutrinoMomentsFromMC.cpp
MC -> MonteCarlo

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/CMakeLists.txt
> +  NeutrinoMomentsFromMC.hpp
MC->MonteCarlo

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.hpp
> +#include <pup.h>
forward declare

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.hpp
> +class MonteCarloOptions : public PUP::able {
I don't think you need to derive from PUP::able as this is not a base class for anything

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.hpp
> +#include "Utilities/Serialization/CharmPupable.hpp"
shouldn't need this

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.hpp
> +  explicit MonteCarloOptions(CkMigrateMessage* msg) : PUP::able(msg) {}
remove `: PUP::able(msg)`

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.hpp
> +  using PUP::able::register_constructor;
remove

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.hpp
> +  WRAPPED_PUPable_decl_template(MonteCarloOptions);
remove

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/MonteCarloOptions.hpp
> +  void pup(PUP::er& p) override;
remove `override`

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/NeutrinoMomentsFromMC.hpp
> +// Distributed under the MIT License.
rename file with MC->MonteCarlo

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/NeutrinoMomentsFromMC.cpp
> +// Distributed under the MIT License.
rename file with MC->MonteCarlo

2025-02-20 18:56 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/RadiationTransport/MonteCarlo/Solutions.hpp
> + * \brief Holds classes providing background fluid/metric for MC
MC -> MonteCarlo

2025-02-20 18:56 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/RadiationTransport/MonteCarlo/CMakeLists.txt
> +  Factory.hpp
alphabetize

2025-02-20 18:56 UTC, kidder commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_CommunicationTags.cpp
> +  // Logical coordinates
are you trying to compute the logical coordinates on the subcell mesh?  If so you just call `logical_coordinates(subcell_mesh)`

2025-02-20 18:56 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/RadiationTransport/MonteCarlo/HomogeneousSphere.hpp
> +#include <limits>
unused

2025-02-20 18:56 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/RadiationTransport/MonteCarlo/HomogeneousSphere.hpp
> +// Distributed under the MIT License.
you need to add a test for this solution

2025-02-20 18:56 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/RadiationTransport/MonteCarlo/HomogeneousSphere.cpp
> +  const double radius = sqrt((x.get(0) * x.get(0)) + (x.get(1) * x.get(1)) +
I believe we have a Euclidean magnitude function in `DataStructures/Tensor/EagerMath/Magnitude.hpp`

2025-02-20 18:56 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/RadiationTransport/MonteCarlo/HomogeneousSphere.cpp
> +  const DataVector radius = sqrt((x.get(0) * x.get(0)) + (x.get(1) * x.get(1)) +
here too use Euclidean magnitude function

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/Tags.hpp
> +  using type = std::unique_ptr<
I don't think this needs to be a unique_ptr, but just the class

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/NeutrinoMomentsFromMC.hpp
> +      const Scalar<DataVector>& det_inv_jacobian_logical_to_inertial) {
move the function definition to the cpp file

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/NeutrinoMomentsFromMC.cpp
> +  get(*fluid_frame_energy_density) = 0.0 * get(lapse);
just use `*fluid_frame_energy_density = make_with_value<Scalar<DataVector>>(lapse, 0.0);`

2025-02-20 18:56 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/Actions/InitializeMonteCarlo.hpp
> +    const Element<dim>& element = db::get<::domain::Tags::Element<dim>>(box);
Do you need to do this initialization?  please check

2025-03-03 17:13 UTC, ffoucart commented on tests/Unit/Evolution/Particles/MonteCarlo/Test_CommunicationTags.cpp
> +  // Logical coordinates
Yeah... I used that function in every line around that section, yet apparently decided to recompute the coordinates by hand...

2025-03-03 17:57 UTC, ffoucart commented on src/Evolution/Particles/MonteCarlo/Actions/InitializeMonteCarlo.hpp
> +    const Element<dim>& element = db::get<::domain::Tags::Element<dim>>(box);
@kidder Do you mean the element, or the entire mortar_data? I initialize the mortar_data largely to have buffers of the correct size preassigned. 
If that's a concern, it would likely be possible to get the same information on the fly from the mesh around L329 of 
`src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp`, at least as long as we do not have mesh refinement. Overall the idea was to avoid figuring out every time what the size of the communication buffer / ghost zone region should be and just use reserved space for the GZ data.

2025-03-03 22:58 UTC, kidder commented on src/Evolution/Particles/MonteCarlo/Actions/InitializeMonteCarlo.hpp
> +    const Element<dim>& element = db::get<::domain::Tags::Element<dim>>(box);
the entire mortar_data;  It is not a concern, there are two possibe ways to do this: 1) you need to initialize here with the correct sizes and there is at most an ASSERT that checks they are the correct size; 2) you default initialize here, and whatever uses it first checks the size and resizes if necessary.  The first is fine if you don't expect to p-refine (and currently we don't plan to do so for regions using subcell).

2025-03-05 15:50 UTC, ffoucart commented
Ok, I'll add an ASSERT on the sizes in GhostZoneCommunication.hpp then.

On Mon, Mar 3, 2025 at 5:59 PM Lawrence Kidder ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/Evolution/Particles/MonteCarlo/Actions/InitializeMonteCarlo.hpp
> <https://github.com/sxs-collaboration/spectre/pull/6403#discussion_r1978358556>
> :
>
> >      using MortarData =
>          typename Particles::MonteCarlo::Tags::MortarDataTag<dim>::type;
>      MortarData mortar_data;
> +    const Element<dim>& element = db::get<::domain::Tags::Element<dim>>(box);
>
> the entire mortar_data; It is not a concern, there are two possibe ways to
> do this: 1) you need to initialize here with the correct sizes and there is
> at most an ASSERT that checks they are the correct size; 2) you default
> initialize here, and whatever uses it first checks the size and resizes if
> necessary. The first is fine if you don't expect to p-refine (and currently
> we don't plan to do so for regions using subcell).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sxs-collaboration/spectre/pull/6403#discussion_r1978358556>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLFTITTJKPUMVV36GUPJ7D2STNEFAVCNFSM6AAAAABTMAC3WOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDMNJVGUZTOMJQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-03-10 18:31 UTC, ffoucart commented
@kidder I think this should address most of your comments. A few notes:
(1) As we discussed on Slack, I kept the dependence of the MonteCarloOptions class on pup for now
(2) For the mortar_data, I only added L333-334 in `src/Evolution/Particles/MonteCarlo/GhostZoneCommunication.hpp`
(3) I added a test for HomogeneousSphere, largely based on the similar test for M1_Constant. Let me know if that does not cover what you wanted to see.

2025-03-10 18:46 UTC, kidder reviewed
Looks good!  Go ahead and squash

2025-03-10 19:07 UTC, ffoucart commented
Looks like there is an issue in the copy constructor for some reason... let me rebase against develop to see if I can reproduce this locally (I didn't get that error on my side...)

2025-03-10 19:18 UTC, kidder commented
> Looks like there is an issue in the copy constructor for some reason... let me rebase against develop to see if I can reproduce this locally (I didn't get that error on my side...)

You need to add ': evolution::initial_data::InitialData(rhs),' at the beginning of your initializer list.  You will may need to do the same with the constructor that takes a charm message

2025-03-10 20:19 UTC, ffoucart commented
> > Looks like there is an issue in the copy constructor for some reason... let me rebase against develop to see if I can reproduce this locally (I didn't get that error on my side...)
> 
> You need to add ': evolution::initial_data::InitialData(rhs),' at the beginning of your initializer list. You will may need to do the same with the constructor that takes a charm message

Do you know why this error would not be reproduceable on mBot?
I am compiling with debug flags and don't see this even after rebasing (when compiling either EvolveMonteCarlo or Test_MonteCarloSolutions, which should both use the HomogeneousSphere solution).

2025-03-10 21:07 UTC, kidder commented
- it's a warning that CI converts into an error as we want to avoid compiler warnings as much as possible
- it may also only happen for gcc (and sometimes only for certain versions of gcc) so you could try building with gcc on mbot if it triggers for all the gcc builds

2025-03-12 18:03 UTC, ffoucart commented
The remaining error is because gcc 9 does not allow the use of [[unlikely]] in

```
if (closest_point_index_3d[d] == extents[d])
                          [[unlikely]] {
```

Apparently this was an error fixed in later version, as far as I understand what I found online.
As we allow gcc9 though, that's likely a problem. Should I just remove the [[unlikely]] statement, or does anyone know of a good alternative here?

2025-03-12 18:12 UTC, kidder commented
> The remaining error is because gcc 9 does not allow the use of [[unlikely]] in
> 
> ```
> if (closest_point_index_3d[d] == extents[d])
>                           [[unlikely]] {
> ```
> 
> Apparently this was an error fixed in later version, as far as I understand what I found online. As we allow gcc9 though, that's likely a problem. Should I just remove the [[unlikely]] statement, or does anyone know of a good alternative here?

Ah, we have a macro that handles that.   `if (UNLIKELY(cond)) {`.   You'll need to include `Utilities/Gsl.hpp` to use it

2025-03-12 18:30 UTC, ffoucart commented
Ah great... let's hope this works now. I don't have a gcc9 version, so debugging this is tricky.

2025-03-12 20:48 UTC, ffoucart commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/RadiationTransport/MonteCarlo/Test_HomogeneousSphere.cpp
> +  const HomogeneousSphere soln(
Change in commit on 3/12, ~4:45pm is making this 'const'

2025-03-13 01:48 UTC, ffoucart commented
Ok, with that last "const" added, seems like the tests finally pass.

2025-03-13 04:36 UTC, kidder approved these changes

2025-03-13 04:36 UTC, merged