Improve Kokkos support
sxs-collaboration/spectre pull request #6425
Opened 2024-12-28 00:29 UTC by nilsvu

## Proposed changes

A few things that allowed me to compile with Kokkos.

### Upgrade instructions

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Further comments

2025-01-07 19:27 UTC, nilsdeppe requested changes
LGTM, just a few questions!

2025-01-07 19:27 UTC, nilsdeppe commented on cmake/SetupKokkos.cmake
> +    # and we can't set properties on alias targets
Do you know if this is kokkos version dependent? Because this had worked for me previously. We might need to pin to kokkos versions like we do for blaze anyway. I'm not asking you to change anything, just curious if you know. "No" is totally fine :)

2025-01-07 19:27 UTC, nilsdeppe commented on tests/Unit/Utilities/Test_TMPLDocumentation.cpp
> +#ifndef __CUDACC__
Do you know why some of these fail with nvcc? It looks like a lot of them work from the any section. I'm worried we use these features and nvcc fails.

Would it make sense to move the ifndef outside the doxygen snippet statements?

2025-01-07 19:27 UTC, nilsdeppe commented on cmake/SetupKokkos.cmake
>        )
Remove "fixup disable another test" from commit message?

2025-01-07 19:27 UTC, nilsdeppe commented on tests/Unit/DataStructures/CMakeLists.txt
> +# The following test is disabled for nvcc because nvcc can't handle it.
maybe specify what fails? E.g. it just runs out of RAM?

2025-01-07 19:27 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/CMakeLists.txt
> +# The following test is disabled for nvcc because nvcc can't handle it.
maybe specify what fails? E.g. it just runs out of RAM?

2025-01-07 21:35 UTC, nilsvu commented on cmake/SetupKokkos.cmake
> +    # and we can't set properties on alias targets
Looks like the `Kokkos::kokkos` target can either be an alias or not, depending on how it was installed (pointing to source tree vs installed on system), so I think we have to support both. I'm thinking, can we just remove these two `set_property` calls? The first I already moved to `EnableWarnings.cmake` anyway, and the second (the one with `-Wno-unknown-cuda-version`) we could also either move to `EnableWarnings.cmake` or delete altogether. The mapping of clang to cuda versions is not so straightforward anyway, so we might as well emit the warning if the versions are marked incompatible. What do you think?

2025-01-07 21:42 UTC, nilsvu commented on tests/Unit/Utilities/Test_TMPLDocumentation.cpp
> +#ifndef __CUDACC__
Yes I know what's happening here. Brigand has a special code branch for nvcc (here: https://github.com/sxs-collaboration/spectre/blob/develop/external/brigand/include/brigand/brigand.hpp#L951). Unfortunately it behaves slightly different to the standard code branch, in that it returns `std::true_type` where the standard branch returns `tmpl::true_type`. Therefore I put a warning in the docs saying the behavior may depend on the compiler. As long as we always use `::value` this should not matter, and I checked and found that we never use `tmpl::true_type` or `tmpl::false_type` in the code, so we should be fine.

2025-01-07 21:44 UTC, nilsvu commented on tests/Unit/Utilities/Test_TMPLDocumentation.cpp
> +#ifndef __CUDACC__
Note that I also tried to remove the special code branch in Brigand for nvcc and it compiled fine, so maybe this was only necessary in Brigand for an old version of nvcc. But it was easier to modify our tests since we never rely on `std::true_type` vs `tmpl::true_type` in our code anyway, than to change upstream Brigand or patch it.

2025-01-07 22:08 UTC, nilsvu commented on tests/Unit/Utilities/Test_TMPLDocumentation.cpp
> +#ifndef __CUDACC__
I kept the ifndef inside the snippet to emphasize in the docs that it can be compiler-dependent

2025-01-10 02:19 UTC, nilsdeppe submitted a review, later dismissed
LGTM! Please squash. Thanks for doing this!!

2025-01-14 13:58 UTC, nilsdeppe approved these changes

2025-01-14 14:00 UTC, merged