Add RotatedRectangles
sxs-collaboration/spectre pull request #649
Opened 2018-04-18 03:38 UTC by gsb76

## Proposed changes

The extension of RotatedIntervals to 2D. Useful for testing.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-04-19 00:49 UTC, nilsdeppe reviewed
Dox: http://gh.nilsdeppe.com/spectre/pr_649/index.html

2018-04-19 00:49 UTC, nilsdeppe commented on src/Domain/DomainCreators/RotatedRectangles.hpp
> +/// Defines class RotatedRectangles.
remove

2018-04-19 00:49 UTC, nilsdeppe commented on src/Domain/DomainCreators/RotatedRectangles.hpp
> +/// The lower right block has its logical \f$\xi\f$axis aligned with
add a dash `-` between xi and axis

2018-04-19 00:49 UTC, nilsdeppe commented on src/Domain/DomainCreators/RotatedRectangles.hpp
> +/// The upper right block has its logical \f$\xi\f$axis opposite to
add a dash `-` between xi and axis

2018-04-19 00:49 UTC, nilsdeppe commented on src/Domain/DomainCreators/RotatedRectangles.hpp
> +/// The upper left block has its logical \f$\xi\f$-axis opposite to
Did you want these 4 to show up as a list? Because they don't :)

2018-04-19 00:49 UTC, nilsdeppe commented on src/Domain/DomainCreators/RotatedRectangles.hpp
> +/// This is useful for testing code that deals with unaligned blocks.
This DomainCreator is

2018-04-23 15:31 UTC, nilsdeppe requested changes

2018-04-23 15:31 UTC, nilsdeppe commented on src/Domain/DomainCreators/RotatedRectangles.hpp
> +/// This DomainCreator is useful for testing code that deals with
add an extra blank line so it shows up in the doc the way you want: http://gh.nilsdeppe.com/spectre/pr_649/classDomainCreators_1_1RotatedRectangles.html#details

2018-04-23 21:25 UTC, osheamonn requested changes

2018-04-23 21:25 UTC, osheamonn commented on src/Domain/DomainCreators/RotatedRectangles.hpp
> +      "RotatedRectangles creates the rectangle [LowerX,UpperX]x\n"
Space and same line for the cartesian product of the intervals.

2018-04-23 21:25 UTC, osheamonn commented on src/Domain/DomainCreators/RotatedRectangles.cpp
> +  return Domain<2, TargetFrame>(std::move(coord_maps), corners);
move corners or inline

2018-04-23 21:25 UTC, osheamonn commented on tests/Unit/Domain/DomainCreators/Test_RotatedRectangles.cpp
> +#include "Domain/Block.hpp"          // IWYU pragma: keep
Check if block is needed

2018-04-23 21:25 UTC, osheamonn commented on src/Domain/DomainCreators/RegisterDerivedWithCharm.cpp
> +using Affine = CoordinateMaps::Affine;
Split into seperate commit

2018-04-25 16:05 UTC, nilsdeppe commented
@gsb76 what's the status here? Why is the Fix translation test commit in here?

2018-04-25 17:12 UTC, gsb76 commented
@nilsdeppe I am not sure how that happened... I want the changes in that commit though, so I just reworded it to something more appropriate.

2018-04-25 17:19 UTC, nilsdeppe requested changes
You should not have @mgiesler be blamed for adding the first commit, so change that. Other than that I'm happy with this.

2018-04-25 17:19 UTC, nilsdeppe commented on src/Domain/DomainCreators/RegisterDerivedWithCharm.cpp
> +      SINGLE_ARG(::CoordinateMap<Frame::Logical, Frame::Inertial, Affine>));
move to previous commit

2018-04-25 17:44 UTC, nilsdeppe approved these changes
@kidder @wthrowe @osheamonn could you look at this?

2018-04-25 22:05 UTC, osheamonn approved these changes

2018-04-25 22:06 UTC, kidder approved these changes

2018-04-25 22:07 UTC, merged