Fix/653
sxs-collaboration/spectre pull request #657
Opened 2018-04-21 04:19 UTC by kidder

## Proposed changes

Update installation notes and add a missing build dependency.
Fixes #653 

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [x] Documentation
- [x] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-04-21 05:02 UTC, fmahebert submitted a review, later dismissed

2018-04-21 05:08 UTC, wthrowe requested changes

2018-04-21 05:08 UTC, wthrowe commented on docs/Installation/Installation.md
> +[instructions](https://spack.readthedocs.io/en/latest/getting_started.html#openssl).  You may need to install the development version of OpenSLL:
OpenSSL

Also line wrap.

2018-04-21 05:42 UTC, kidder commented
@wthrowe fixed and squashed

2018-04-21 05:51 UTC, wthrowe approved these changes

2018-04-22 23:52 UTC, nilsdeppe approved these changes

2018-04-22 23:52 UTC, merged