Additions for RotatedBricks 2
sxs-collaboration/spectre pull request #671
Opened 2018-05-01 16:02 UTC by gsb76

## Proposed changes

Allows for the rotation of blocks "in place" within the context of domain creation:
Given a (n,m,l) edifice of aligned blocks, a user can select one or more blocks and change their orientation relative to the edifice - the ordered graph algorithm will then deduce the correct relative orientations between all of these blocks and their neighbors.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-03 21:03 UTC, kidder requested changes
split first commit into move then edits

2018-05-03 21:03 UTC, kidder commented on src/Domain/OrientationMap.hpp
> +  /// The correct ordered graph of global corners for a block having
free your function (into DomainHelpers)

2018-05-03 21:03 UTC, kidder commented on src/Domain/OrientationMap.hpp
> +  /// The corresponding logical corners in the neighbor.
remove

2018-05-09 22:17 UTC, kidder requested changes

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +  explicit VolumeCornerIterator(size_t initial_local_corner_number) noexcept
whitespace

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +  const std::array<Direction<VolumeDim>, VolumeDim>& directions_of_corner() const noexcept{
... and put it here

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +      const auto side =
inline this on the next line and use the array on 202

2018-05-09 22:17 UTC, kidder commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +  CHECK(vci.directions_of_corner() ==
add test that catches your previous bug

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +/// given the ordered graph the block would have if it were aligned.
ordered graph -> corner numbering

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +/// Returns the correct ordering of global corner numbers for a block
give a concrete example, and what it is useful for

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +      const auto side = 2 * get_nth_bit(local_corner_number_, i) - 1 == 1
merge formatting changes into previous commit

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +      [&]() {
capture what you use

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +            gsl::at(directions_of_mapped_corner, i) = new_direction;
inline new_direction

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +      [&]() {
noexcept

2018-05-09 22:17 UTC, kidder commented on tests/Unit/Domain/Test_DomainHelpers.cpp
> +  CHECK(std::array<size_t, 8>{{9, 0, 12, 3, 10, 1, 13, 4}} ==
blank line here

2018-05-09 22:17 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +      CoordinateMaps::ProductOf3Maps<Map, Map, Map>(maps[0], maps[1], maps[2]));
use tuples instead of arrays

2018-05-18 20:27 UTC, kidder reviewed
squash

2018-05-22 19:58 UTC, kidder approved these changes

2018-05-22 20:03 UTC, wthrowe approved these changes

2018-05-22 20:05 UTC, merged