Add DataVector dot product
sxs-collaboration/spectre pull request #673
Opened 2018-05-02 16:53 UTC by nilsleiffischer

## Proposed changes

This PR adds a `dot_product` overload that takes two `DataVector`s and computes their Euclidean inner product. This is to begin wrapping BLAS calls (in this case `ddot_`) with functions that abstract away knowledge of the memory layout that should be private to `DataVector`. The wrapper is used in `DefiniteIntegral.cpp` to give an example of how it simplifies the code. Further work to wrap `Matrix` algebra is being discussed in #666.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-02 17:27 UTC, nilsdeppe requested changes

2018-05-02 17:27 UTC, nilsdeppe commented on src/DataStructures/DataVector.hpp
> + * `DataVector`s also support a `dot_product` between themselves and with a
Why is Matrix mentioned here at all?

2018-05-02 17:27 UTC, nilsdeppe commented on src/DataStructures/DataVector.hpp
> +  SPECTRE_ALWAYS_INLINE friend decltype(auto) dot_product(
You should provide overloads for expressions and a DataVector as well.

2018-05-02 17:27 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_DataVector.cpp
> +  CHECK_ITERABLE_APPROX(dot_product(t1, t2), -2.0);
Test expressions in the left and right slots too

2018-05-02 17:27 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_DataVector.cpp
> +  CHECK_ITERABLE_APPROX(magnitude_square(t1), 14.0);
test for expressions too

2018-05-02 17:27 UTC, osheamonn commented on src/DataStructures/DataVector.hpp
> + * `Matrix`, as well as a `magnitude` which is the square root of the dot
`dot_product` as you've defined it in this PR is for two `DataVectors`, not for a `DataVector` and a `Matrix`

2018-05-03 15:12 UTC, geoffrey4444 submitted a review, later dismissed
Other than nils's suggestions, I think this looks good.

2018-05-04 14:20 UTC, nilsleiffischer commented on src/DataStructures/DataVector.hpp
> +  return dot(expression, expression);
Blaze implements `sqrLength` (as used above in the `magnitude_square` function for a `DataVector`) only for `blaze::DenseVector` and `blaze::SparseVector` (see https://bitbucket.org/blaze-lib/blaze/wiki/Vector%20Operations#!length-sqrlength). Can someone clarify for me why that is? And what's the best way to wrap it?

2018-05-04 15:08 UTC, nilsdeppe requested changes
I'm happy for you to squash this :)

2018-05-06 14:02 UTC, nilsleiffischer commented
I was thinking that we may actually want to wait with merging this, since I'm not entirely sure that we want `DataVector` to have a `dot_product` at all. I do need one for the elliptic solver, but could work with `blaze::DynamicVector` directly where it makes sense. Perhaps we could discuss this some time in a hangout.

2018-05-09 14:44 UTC, nilsleiffischer commented
Closing this for now, refer to #696 for further discussion.

2018-05-09 14:44 UTC, closed without merging