Add functions to compute K_ij and d_k g_ij from GH variables.
sxs-collaboration/spectre pull request #679
Opened 2018-05-04 00:23 UTC by markscheel

## Proposed changes

Add new functions to compute extrinsic curvature and derivative of spatial metric, given
generalized harmonic variables.

This will be useful for horizon finding, and for computing spatial christoffel symbols in the
generalized harmonic evolution.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-04 02:42 UTC, osheamonn submitted a review, later dismissed

2018-05-04 18:22 UTC, fmahebert commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +  auto deriv_spatial_metric =
Looks like this one can also be default-initialized, rather than set by `make_with_value`.

2018-05-04 18:30 UTC, osheamonn commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +  auto deriv_spatial_metric =
I think default initialisation of Tensors of DataVectors will be disallowed in the future, right @nilsdeppe?

2018-05-04 18:35 UTC, fmahebert commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +  auto deriv_spatial_metric =
Hm, indeed, looks like it: #413. So we prefer to set values twice?

2018-05-04 18:41 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +  auto deriv_spatial_metric =
Yes, @osheamonn is correct, only a `Scalar<DataVector>` could reasonably support default initialization.

@fmahebert the reason is that it is the memory allocations that are expensive, not setting the values to 0 :) We can optimize the memory allocation for a `Tensor` by allocating all components at once.

2018-05-04 18:43 UTC, fmahebert commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.cpp
> +  auto deriv_spatial_metric =
@markscheel Best to ignore this and my comments on #676 as well

2018-05-08 22:12 UTC, nilsdeppe requested changes
please squash this once you've fixed the documentation

2018-05-08 22:12 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
> + * \details If \f$ \Pi_{ab} \f$ and \$f \phi_{iab} \f$ are the generalized
you should have `\f$` (please check documentation locally first :) )

2018-05-08 22:12 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
> + * \details If \$f \phi_{kab} \f$ is the generalized
Mark please... :)

2018-05-09 03:14 UTC, kidder submitted a review, later dismissed

2018-05-09 13:23 UTC, nilsdeppe requested changes

2018-05-09 13:23 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
> + * \details If \f$ \Pi_{ab} \f$ and \f$ \phi_{iab} \f$ are the generalized
is it normally `\Phi`? (capitalization?) same below

2018-05-09 17:32 UTC, markscheel commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
> + * \details If \f$ \Pi_{ab} \f$ and \f$ \phi_{iab} \f$ are the generalized
It is `\phi` in all of the other documentation for the other functions, and has been for a while.  Keep as `\phi` or change to `\Phi` everywhere?

2018-05-09 17:35 UTC, nilsdeppe commented on src/PointwiseFunctions/GeneralRelativity/ComputeGhQuantities.hpp
> + * \details If \f$ \Pi_{ab} \f$ and \f$ \phi_{iab} \f$ are the generalized
My vote is for being consistent with the GH papers, which use Phi

2018-05-09 17:50 UTC, markscheel commented
Ok, I added phi->Phi as a new (unsquashed) commit since it touches things not in the original PR.  I can squash if you want, but it seems it should be a separate commit.

2018-05-09 18:44 UTC, nilsdeppe approved these changes

2018-05-09 18:45 UTC, kidder approved these changes

2018-05-10 01:38 UTC, nilsdeppe commented
@wthrowe if you're happy with this feel free to merge it :)

2018-05-10 02:10 UTC, wthrowe approved these changes

2018-05-10 02:11 UTC, merged