Add Cylinder Domain
sxs-collaboration/spectre pull request #681
Opened 2018-05-04 19:53 UTC by gsb76

## Proposed changes

A useful Domain for testing.
Also revamps Wedge2D to be more similar in functionality to Wedge3D

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-09 03:17 UTC, kidder commented
@gsb76 fix, squash, and remove in progress label before we look...

2018-05-09 21:39 UTC, kidder requested changes

2018-05-09 21:39 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> +/// and 1 (for circular). These arcs extend \f$\pi/2\f$ in angle, and can be
explain how to get from the 3d case to the 2d case

2018-05-09 21:39 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +         "object where the "
formatting

2018-05-09 21:39 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +  ReturnType xi = (physical_x - x_0) / x_1;
inline x_0 and x_1

2018-05-09 21:39 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +         lhs.radius_outer_ == rhs.radius_outer_ and
uh oh -Gabe

2018-05-09 21:39 UTC, kidder commented on src/Domain/DomainCreators/Cylinder.hpp
> +/// surrounded by four wedge2d prisms.
better description than wedge2d prisms (maybe a picture)

2018-05-09 21:39 UTC, kidder commented on src/Domain/DomainCreators/Cylinder.cpp
> +  using Affine3DPrism = CoordinateMaps::ProductOf2Maps<Affine2D, Affine>;
use ProductOf3Maps

2018-05-09 21:39 UTC, kidder commented on src/Domain/DomainCreators/Cylinder.cpp
> +      CoordinateMaps::ProductOf2Maps<Equiangular2D, Affine>;
again

2018-05-17 19:41 UTC, kidder requested changes
squash
Group review by Nils D, Will, Larry

2018-05-17 19:41 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> + * A_0 &= \frac{1}{2} \big\{ s_{outer}R_{outer} + c_{inner}R_{inner}\big\}\\
s to c

2018-05-17 19:41 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> + *  \f[\vec{x}(\xi,\eta) =
define rho and H

2018-05-17 19:41 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> + * of the variables defined in Wedge2D (the circularity \f$c\f$ and the radius
In terms of the circularity ...

2018-05-17 19:41 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> + *  \f[\vec{x}(\xi,\eta) =
define H and rho

2018-05-17 19:41 UTC, kidder commented on src/Domain/DomainCreators/Cylinder.hpp
> +/// is a square surrounded by four Wedge2Ds.
surrounded by four two-dimensional wedges (see ref to Wedge2D)

2018-05-17 19:41 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.hpp
> + * in the radial direction is zeta, and one may set either of the two other
\zeta and mention that \xi is the radial direction here

2018-05-17 19:46 UTC, kidder requested changes

2018-05-17 19:46 UTC, kidder commented on src/Domain/CoordinateMaps/Wedge2D.cpp
> +  annulus_rate_ = 0.5 * (circularity_outer * radius_outer -
move these fixes to a different commit

2018-05-17 22:12 UTC, kidder approved these changes

2018-05-18 01:57 UTC, nilsdeppe approved these changes

2018-05-18 16:14 UTC, merged