Split ComputeBoundaryFlux action into receiving and computing parts
sxs-collaboration/spectre pull request #686
Opened 2018-05-06 20:57 UTC by wthrowe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-09 18:37 UTC, kidder requested changes

2018-05-09 18:37 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication.hpp
> +  using LocalData = Variables<tmpl::remove_duplicates<tmpl::append<
comment what LocalData is

2018-05-09 18:37 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/ApplyBoundaryFluxesGlobalTimeStepping.hpp
> +                    tuples::TaggedTuple<InboxTags...>& /*inboxes*/,
const

2018-05-09 18:37 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/FluxCommunicationTypes.hpp
> +  using PackagedData = Variables<
document these

2018-05-09 18:37 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication.hpp
> +    using types = FluxCommunicationTypes<Metavariables>;
change types to flux_comm_types everywhere

2018-05-09 18:37 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ApplyBoundaryFluxesGlobalTimeStepping.cpp
> +class NumericalFlux {
can you put some of this stuff in a helpers if it is duplicated across tests

2018-05-09 18:37 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication.cpp
> +using CommunicationTypes = dg::FluxCommunicationTypes<Metavariables>;
be consistent with above

2018-05-09 18:37 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication.cpp
> +    check_mortar(std::make_pair(Direction<2>::lower_xi(), west_id),
can you clean this up (i.e. reuse or use reorient)

2018-05-15 18:50 UTC, wthrowe commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_ApplyBoundaryFluxesGlobalTimeStepping.cpp
> +class NumericalFlux {
Unfortunately, while there is quite a bit of textural duplication here, it turns out most of it can't be factored out because it depends on the metavariables, and the metavariables for different tests contain different actions.  The metavariables can't be combined by templating on the actions because some of the actions are templated on the metavariables.

It looks like all that can be pulled out are a few tag structs and the system, which doesn't seem worth it.

2018-05-15 18:57 UTC, kidder reviewed
these changes can be squashed

2018-05-16 19:04 UTC, wthrowe commented
@nilsleiffischer The last commit has the changes you requested in #706.

2018-05-16 22:25 UTC, kidder reviewed
code review by Nils D and Larry
squash

2018-05-19 01:21 UTC, kidder approved these changes

2018-05-22 20:01 UTC, kidder commented
@nilsdeppe this is ready and just needs your approval

2018-05-23 01:02 UTC, nilsdeppe approved these changes

2018-05-23 01:02 UTC, merged