Construct Strahlkorper from options.
sxs-collaboration/spectre pull request #692
Opened 2018-05-08 19:04 UTC by markscheel

Currently only constructs a spherical Strahlkorper.

## Proposed changes

Now you can construct a Strahlkorper from Options.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-08 20:24 UTC, kidder requested changes
squash

2018-05-08 20:24 UTC, kidder commented on tests/Unit/ApparentHorizons/Test_Strahlkorper.cpp
> +struct StrahlkorperFromOpt {
move this to the Strahlkorper.hpp , put it in the OptionTags namespace,  and remove the FromOpt

2018-05-09 00:44 UTC, nilsdeppe requested changes
I'm happy with this once it's documented :)

2018-05-09 00:44 UTC, nilsdeppe commented on src/ApparentHorizons/Strahlkorper.hpp
> +template <typename Frame>
maybe document this in SurfacesGroup?

2018-05-09 20:11 UTC, kidder approved these changes

2018-05-09 20:20 UTC, nilsdeppe approved these changes

2018-05-09 20:21 UTC, kidder commented
@wthrowe this also is ready for you to merge if you are happy with it

2018-05-10 02:00 UTC, wthrowe approved these changes

2018-05-10 02:00 UTC, wthrowe commented on src/ApparentHorizons/Strahlkorper.hpp
> +struct Strahlkorper {
I suspect this won't be how we want to handle this tag in the long term, but since I'm not sure how we will want to I say we leave it for now.

2018-05-10 02:00 UTC, merged