Add a base tag mechanism and function template support to DataBox
sxs-collaboration/spectre pull request #695
Opened 2018-05-08 21:29 UTC by nilsdeppe

## Proposed changes

This adds 2 major and very closely related functionalities to DataBox:
- Compute items can now be function templates. This is done by having the
  function member be a function template, which then forwards to the free
  function.
- It is now possible to retrieve tags from the DataBox via a base tag
  mechanism. This is supported via two different styles: base tags and compute
  tags deriving off of a simple tag.
  For base tags the tag contains no members and must derive off of
  db::BaseDataBoxTags. It is then possible to retrieve the base tag MyBaseTag
  using db::get<MyBaseTag>(box). Note that it is also possible to mutate base
  tags (only if they are a simple item) by using db::mutate<MyBaseTag>(Box, ...)

  For compute items that derive off of simple tags the same approach applies,
  except that it is not possible to mutate the compute items (this rule hasn't
  changed)

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-09 20:06 UTC, kidder requested changes

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +struct Array : virtual db::DataBoxTag, ArrayBase<I> {
no virtual

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +struct Array : virtual db::DataBoxTag, ArrayBase<I> {
DataBoxTag -> db::SimpleTag

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +struct VectorBase : db::BaseDataBoxTag {};
db::BaseTag

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +struct ArrayComputeBase : Array<I>, db::ComputeItemTag {
ComputeItemTag -> db::ComputeTag

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +  // - `get`ing a compute item by pure base tag
remove pure and rename "impure" base to simple

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +  auto box = db::create<db::AddSimpleTags<TestTags::Vector<0>>,
intersperse comments with checks

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +  auto box = db::create<db::AddSimpleTags<TestTags::Vector<0>>,
add global documentation to the DataBoxGroup and make these \snippets

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +    count++;
remove count

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +  db::mutate<TestTags::FirstBase<0>>(
also test mutating the sub-item collection

2018-05-09 20:06 UTC, kidder commented on tests/Unit/DataStructures/Test_DataBox.cpp
> +      box, [](test_subitems::Boxed<double> & x) noexcept { *x = 12.; });
don't change

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> + * tags which must contain the type information. Pure base tags should be used
remove sparingly sentence

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +struct DataBoxPrefix : virtual DataBoxTag {};
try to remove virtual

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +template <typename TagList, typename Tag>
put these 3 into detail namespace

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +                            not cpp17::is_base_of_v<db::DataBoxTag, Tag>>>
and not compute tag

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +      typename item_type_impl<TagList, first_matching_tag<TagList, Tag>>::type;
comment why no check for only one tag

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +      "list<PassedTags...>>')");
fix this to show typelist of argument types and typelist of argument tags

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +#ifdef SPECTRE_DEBUG
debug_static_assert

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +      check_compute_item_is_invokable<
(void)

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +struct dep_items_impl;
dep_items -> expand_subitems

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +  return pack_size >= 4 ? 3 : pack_size >= 2 ? 2 : static_cast<int>(pack_size);
comment what this is doing and implied of limit of items in DataBox

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> + * Once the `CompuetTagsList` is turned into a parameter pack, the
Compute

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> + * computation. This recursive nature limits us to about 200 items in the
200 -> 800

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +struct expanded_list_from_full_list_impl<tmpl::list<>> {
can you be smarter about this?

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +template <typename TagList, typename Tag>
why is this being added?

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +  /// A list of the simple items that are subitems, without expanding the
that are subitems -> that have subitems

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +  template <typename FullTagList, typename ComputeItem,
// mutating vs // non-mutating

2018-05-09 20:06 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +      "Cannot mutate a compute item");
should check uniqueness

2018-05-10 15:46 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +template <typename TagList, typename Tag>
It was moved into a detail namespace

2018-05-10 17:09 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +template <typename TagList, typename Tag>
moved into a detail namespace

2018-05-10 22:11 UTC, nilsdeppe commented on tests/Unit/DataStructures/Test_BaseTags.cpp
> +struct Array : virtual db::DataBoxTag, ArrayBase<I> {
Turns out it's necessary otherwise GCC complains about it being an inaccessible base class

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * DataBox is a heterogeneous compile-time hash map with lazy evaluation of
hash map -> associative container

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * The compile-time keys are `struct`s called Tags, while the values are called
Tags -> tags (throughout)

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * tag, and inherit from `db::SimpleTag`. Compute tags must also have a `static
New sentence at `, and`
New paragraph before Compute tags

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * Finally, a compute tag with an overloaded function and a function template
Add examples of:
- Overload on the type
- Overload on the number of args
- Simple function template like ComputeLambda0
- Crazy example

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * the collection. The infrastructure that allows for this is call *Subitems*.
`call` -> `called`

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * A simple or compute tag might also hold a collection of data, such as a bunch
bunch -> container

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * Subitems are controlled not by the tag, but by the type of the tag. Let's say
Explain that this is done by a requirement on the input tag

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * that are related to a different item by a linear operator. Specifically, say
by a linear operator -> by some operation

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * If you want to mutate the value of an item in the DataBox use `db::mutate`.
an item -> a simple item

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * parameters, a `gsl::not_null` of the DataBox whose items to mutate, an
to mutate -> will be mutated

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * #### The Base Tags Mechanism
move header above

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * tag. A base tag is an empty `struct` that inherits from `db::BaseTag`. Any
tag. -> tags.

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * \snippet Test_BaseTags.cpp base_simple_and_compute_mutate
add white space in example

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * \snippet Test_BaseTags.cpp base_simple_and_compute_mutate
Add comments to the example to highlight the different CHECK calls

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * Notice that we are ably to retrieve `ArrayComputeBase<0>` with `ArrayBase<0>`
ably -> able

2018-05-15 21:56 UTC, nilsdeppe commented on docs/GroupDefs.hpp
> + * the function. Compute tags must inherit from `db::ComputeTag`.
compute items must take `const &`

2018-05-15 21:56 UTC, kidder requested changes
Cornell group code review

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +  using simple_only_expand_subitems_tags = tmpl::flatten<tmpl::transform<
undo this

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> + * Base tags do not need to even contain type information, unlike simple
remove even

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> + * To use the base mechanism the base tag must inherit off of
remove "To ... mechanism"

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +      "brigand::list<item_type<Passedtags>...>>')");
remove first )

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBoxTag.hpp
> +      "brigand::list<item_type<Passedtags>...>>')");
PassedTags

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +            Requires<!cpp17::is_same_v<std::decay_t<T>, DataBoxLeaf> &&
ands and nots

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +    (void)this;  // Compiler bug wars this unused
warns

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +      (static_cast<void>(helper(Subtags{})), '0')...});
write the macro

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +    Args&&... args) {
noexcept

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +  // Merge old tags, including all ComputeItems even though they might be
remove the comment

2018-05-15 21:56 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +    Args&&... args) noexcept(DataBox_detail::
kill this noexcept and the comment about it

2018-05-16 22:30 UTC, wthrowe approved these changes

2018-05-16 22:53 UTC, kidder approved these changes

2018-05-17 00:09 UTC, merged