Add Isentropic Vortex
sxs-collaboration/spectre pull request #699
Opened 2018-05-11 04:41 UTC by carmaza

## Proposed changes

- Add Tags for the Newtonian Euler system
- Add Isentropic Vortex solution

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-11 17:15 UTC, osheamonn requested changes

2018-05-11 17:15 UTC, osheamonn commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +    static type default_value() { return 5.0 / 3.0; }
Do we want a default value for this? it doesn't seem like 5/3 is obviously the "default" value for the index

2018-05-11 17:15 UTC, osheamonn commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +    static type default_value() { return {{1.0, 1.0, 1.0}}; }
Again I think this shouldn't have a default

2018-05-11 17:15 UTC, osheamonn commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +    static type default_value() { return {{0.0, 0.0, 0.0}}; }
This is a reasonable default I think

2018-05-11 17:15 UTC, osheamonn commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +    static type default_value() { return 3.0; }
Again remove the default_value

2018-05-11 17:15 UTC, osheamonn commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +  double adiabatic_index_ = 5.0 / 3.0;
Remove the defaults

2018-05-11 17:15 UTC, osheamonn commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/TestFunctions.py
> +            (8.0 * adiabatic_index * np.pi * np.pi))
`np.pi * np.pi` -> `np.pi**2`

2018-05-11 17:15 UTC, osheamonn commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.cpp
> +      center_(center),
`center_(std::move(center))`

2018-05-11 17:15 UTC, osheamonn commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.cpp
> +      mean_velocity_(mean_velocity),
std::move

2018-05-11 18:38 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> + * The well known analytic solution to the 2-D Newtonian Euler system
No need to say "well known"

2018-05-11 18:38 UTC, fmahebert commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> + * The initial condition is the superposition of a mean uniform flow and a small
"The initial condition is the superposition of a mean uniform flow with a gaussian-profile vortex."

2018-05-17 20:33 UTC, kidder requested changes

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +  IsentropicVortex(const IsentropicVortex& /*rhs*/) = default;
delete

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +  IsentropicVortex& operator=(const IsentropicVortex& /*rhs*/) = default;
delete

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +#include <pup.h>
move to the cpp

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +namespace NewtonianEuler {
remove these

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +  inline constexpr double adiabatic_index() const noexcept {
don't need to mark these inline (as they are defined within the class definition)

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +  inline constexpr Center::type center() const noexcept { return center_; }
constexpr const Center::type&  and similarly for mean velocity

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> + * representing the slow advection of an incompressible, isentropic vortex [1].
markdown footnote

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.cpp
> +  if (adiabatic_index_ <= 1.0 or adiabatic_index_ >= 2.0) {
Parsing errors are already handled by specifying the bounds of the option, so these can be turned into ASSERTs for when the object is created without specifying options

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.cpp
> +                            const double& t) const noexcept {
const double t

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.cpp
> +  get<MassDensity<DataType>>(result) = Scalar<DataType>(density);
inline density

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.cpp
> +      Scalar<DataType>(pow(std::move(density), adiabatic_index_minus_one) /
and instead of moving, `get<MassDensity...`

2018-05-17 20:33 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.cpp
> +
add a function to return conserved variables

2018-05-17 20:33 UTC, kidder commented on tests/Unit/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/Test_IsentropicVortex.cpp
> +struct Vortex {
try to use TestCreation.hpp

2018-06-20 16:20 UTC, osheamonn submitted a review, later dismissed

2018-06-20 22:05 UTC, kidder requested changes

2018-06-20 22:05 UTC, kidder commented on src/PointwiseFunctions/AnalyticSolutions/NewtonianEulerSolutions/IsentropicVortex.hpp
> +// IWYU pragma: no_forward_declare CkMigrateMessage
yes you do need it; remove forward decl of PUP

2018-06-22 20:23 UTC, kidder reviewed
squash

2018-06-27 02:46 UTC, kidder commented
@nilsdeppe please look at

2018-06-28 00:56 UTC, nilsdeppe approved these changes

2018-06-28 21:21 UTC, kidder approved these changes

2018-06-28 21:21 UTC, merged