Add documentation and support for Singularity
sxs-collaboration/spectre pull request #701
Opened 2018-05-11 20:14 UTC by nilsdeppe

## Proposed changes

Singularity is a container alternative to Docker and can use Docker
containers. It integrates more readily with the host OS and does not require
root privileges to get set up.

The documentation is built and will be available at: 

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-11 21:19 UTC, markscheel requested changes

2018-05-11 21:19 UTC, markscheel commented on docs/Installation/Installation.md
> +   in your home directory. Clone SpECTRE into `WORKDIR/SPECTRE_ROOT`.
Does it really need to be in your home directory? Or just someplace user-writeable?

2018-05-11 21:19 UTC, markscheel commented on docs/Installation/Installation.md
> +3. Run `singularity build spectre.img
When I do the singularity build command it says

ERROR UNAUTHORIZED: authentication required
ERROR Check existence, naming, and permissions

2018-05-11 21:30 UTC, markscheel commented on docs/Installation/Installation.md
> +5. To set up Charm++ run `mv /work/charm ./ && cd ./charm`
Should this be /PATH/TO/CHARM (which is used below)?

2018-05-12 01:38 UTC, markscheel requested changes

2018-05-12 01:38 UTC, markscheel commented on docs/Installation/Installation.md
> +- You can safely ignore any warnings about the locale settings.
If locale warnings are gone you don't need this anymore.

2018-05-17 22:43 UTC, kidder submitted a review, later dismissed

2018-05-17 22:43 UTC, nilsdeppe commented
@markscheel can you look at this? The only thing missing is pushing the new image, but that'll break all currently travis builds...

2018-05-18 15:03 UTC, markscheel submitted a review, later dismissed

2018-05-18 20:21 UTC, kidder approved these changes

2018-05-18 20:23 UTC, wthrowe approved these changes

2018-05-18 20:23 UTC, merged