Addition of SegmentId and test
sxs-collaboration/spectre pull request #71
Opened 2017-06-29 16:08 UTC by gsb76

2017-06-29 16:39 UTC, osheamonn commented on src/Domain/SegmentId.hpp
> +  /// Construct from the refinement level and an index.
Redundant comment.

2017-06-29 16:39 UTC, osheamonn commented on src/Domain/SegmentId.hpp
> +  /// The refinement level.
Redundant, I'm gonna stop commenting on things like this in this file

2017-06-29 16:39 UTC, osheamonn commented on src/Domain/SegmentId.hpp
> +    return SegmentId(refinement_level_ + 1, index_ << 1);
Maybe I'm just dumb but I find it hard to parse bit manipulations quickly, I think anywhere we do something like this we should comment why.

2017-06-29 16:59 UTC, nilsdeppe commented on src/Domain/SegmentId.hpp
> +    return SegmentId(refinement_level_ + 1, index_ << 1);
Maybe both ;)

2017-06-29 18:15 UTC, wthrowe requested changes

2017-06-29 18:15 UTC, wthrowe commented on src/Domain/SegmentId.hpp
> +  // left-shifting index_ by 1 gives us floor(index_/2).
right-shifting

2017-06-29 18:15 UTC, wthrowe commented on src/Domain/SegmentId.hpp
> +    // right-shifting index_ by 1 gives us index*2.
left-shifting

2017-06-29 18:15 UTC, wthrowe commented on src/Domain/SegmentId.hpp
> +  // right-shifting index_ by 1, followed by OR with 1, gives us index*2 +1.
left-shifting

2017-06-29 18:15 UTC, wthrowe commented on tests/Unit/Domain/Test_SegmentId.cpp
> +      CHECK(id.refinement_level() ==
All these checks are duplicating the equality operator logic.  How about testing the equality operator and then using it in the later checks?

2017-06-29 18:57 UTC, wthrowe commented on tests/Unit/Domain/Test_SegmentId.cpp
> +  SegmentId level_2_index_3(2ul, 3ul);
No `ul`s.

2017-06-30 15:51 UTC, nilsdeppe requested changes

2017-06-30 15:51 UTC, nilsdeppe commented on src/Domain/SegmentId.hpp
> +  SegmentId();
make this `= default` and move the default values set in the constructor into the class definition

2017-06-30 15:51 UTC, nilsdeppe commented on tests/Unit/Domain/Test_SegmentId.cpp
> +  SegmentId test_id;
Should check the default values that are set if testing this.

2017-06-30 17:17 UTC, nilsdeppe requested changes

2017-06-30 17:17 UTC, nilsdeppe commented on src/Domain/SegmentId.hpp
> +  void pup(PUP::er& p);  // NOLINT
should check that `pup` works correctly. See `TestHelpers.hpp`, which has a `serialize_and_deserialize` function.

2017-06-30 17:17 UTC, nilsdeppe commented on src/Domain/SegmentId.cpp
> +
Wrap this function in `// LCOV_EXCL_START` and `// LCOV_EXCL_STOP` since we don't want to have to worry about it during testing.

2017-06-30 18:55 UTC, nilsdeppe approved these changes

2017-06-30 19:37 UTC, nilsdeppe approved these changes

2017-06-30 19:53 UTC, merged