Add Conservative from Primitive for Newtonian Euler
sxs-collaboration/spectre pull request #712
Opened 2018-05-18 16:45 UTC by carmaza

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-18 19:19 UTC, kidder requested changes

2018-05-18 19:19 UTC, kidder commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_ConservativeFromPrimitive.cpp
> +
In CheckWithRandomValues.hpp add 3 macros
```
# define CHECK_FOR_DATAVECTORS(...) \
const DataVector dv(5); \
__VA_ARGS__<1>(dv); \
...
```
and also CHECK_FOR_DOUBLES and CHECK_FOR_DOUBLES_AND_DATAVECTORS

2018-06-11 21:36 UTC, kidder submitted a review, later dismissed

2018-06-11 21:37 UTC, kidder commented
@nilsdeppe please take a look

2018-06-11 21:41 UTC, wthrowe submitted a review, later dismissed

2018-06-12 10:20 UTC, nilsdeppe requested changes
I'm happy for you to squash immediately :)

2018-06-12 10:20 UTC, nilsdeppe commented on tests/Unit/Pypp/CheckWithRandomValues.hpp
> +#include <boost/vmd/detail/is_empty.hpp>
For some of these, specifically the `detail` ones, you should modify the IWYU map file in `tools/Iwyu/boost-all.imp` (just append to the end). For example,
```
{ include: ["<boost/vmd/detail/is_empty.hpp>", private,
                "<boost/vmd/is_empty.hpp>", public]},
```

2018-06-12 10:20 UTC, nilsdeppe commented on tests/Unit/Evolution/Systems/NewtonianEuler/Test_ConservativeFromPrimitive.cpp
> +  GENERATE_UNINITIALIZED_DOUBLE_AND_DATAVECTOR;
Just move this into the previous commit :)

2018-06-15 19:35 UTC, kidder submitted a review, later dismissed

2018-06-15 21:02 UTC, kidder commented
@nilsdeppe please look at

2018-06-16 00:42 UTC, nilsdeppe submitted a review, later dismissed

2018-06-16 00:42 UTC, nilsdeppe commented on tests/Unit/Pypp/CheckWithRandomValues.hpp
> +#include <boost/vmd/detail/is_empty.hpp>
ping ping ping

2018-06-19 20:51 UTC, mar-celine approved these changes

2018-06-19 20:52 UTC, kidder approved these changes

2018-06-19 20:52 UTC, merged

2018-06-20 00:49 UTC, nilsdeppe commented
No, get this working.

2018-06-20 00:49 UTC, nilsdeppe commented
It's a matter of reading, come on, it's not hard.

2018-06-20 01:24 UTC, nilsdeppe reviewed
I'm requesting this change...

2018-06-20 01:24 UTC, nilsdeppe commented on tests/Unit/Pypp/CheckWithRandomValues.hpp
> +#include <boost/preprocessor/detail/check.hpp>
- `preprocessor/list/adt.hpp`
- `preprocessor/facilities/apply.hpp`
- `parameter/preprocessor.hpp`

Are the interfaces. I did:
```
$ rg 'check.hpp'
detail/is_binary.hpp
16:# include <boost/preprocessor/detail/check.hpp>

detail/is_nullary.hpp
16:# include <boost/preprocessor/detail/check.hpp>

detail/is_unary.hpp
16:# include <boost/preprocessor/detail/check.hpp>
$ rg 'is_binary.hpp'
list/adt.hpp
18:# include <boost/preprocessor/detail/is_binary.hpp>
$ rg 'is_unary.hpp'
facilities/apply.hpp
17:# include <boost/preprocessor/detail/is_unary.hpp>
$ rg 'detail/is_nullary.hpp'
parameter/preprocessor.hpp
35:# include <boost/preprocessor/detail/is_nullary.hpp>
```