Clean up various algorithm-related tag things
sxs-collaboration/spectre pull request #713
Opened 2018-05-18 18:26 UTC by wthrowe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-18 19:04 UTC, kidder requested changes

2018-05-18 19:04 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
> +  struct const_global_cache_tags<
elevate this to somewhere that any component can use it

2018-05-18 19:04 UTC, kidder commented on src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp
> +  struct const_global_cache_tags<
add some documentation to the ParallelizationGroup

2018-05-21 19:47 UTC, nilsleiffischer commented
Will this break code using the const global cache (or anything else)? If so, could you briefly describe what people that rebase on this need to pay attention to?

2018-05-21 21:35 UTC, wthrowe commented
I believe the main breakage here will be if someone wrote a new executable using DgElementArray, where they will now have to change `dg_element_array_add_to_cache` to `const_global_cache_tag_list` in their metavariables, and preferably check whether some of the things in it should be removed.

I believe everything else is straightforward: SendDataForFluxes gained a template parameter, a few things I think are unlikely to have been used were removed as indicated in the commit messages (replacements are described there in prose, existing use cases can be checked for code versions).

2018-05-23 21:14 UTC, kidder commented
@nilsdeppe this is ready for you to look at; if you are happy then Will can squash

2018-05-24 12:22 UTC, nilsdeppe submitted a review, later dismissed
I'm assuming you guys verified the dox renders as expected :)

2018-05-25 15:49 UTC, kidder approved these changes

2018-05-25 15:49 UTC, kidder commented
@nilsdeppe this just needs your approval again after Will squashed

2018-05-26 02:01 UTC, nilsdeppe approved these changes

2018-05-26 02:01 UTC, merged