Allow Parallel::printf to print an enum class.
sxs-collaboration/spectre pull request #717
Opened 2018-05-21 18:52 UTC by markscheel

## Proposed changes

If you have an enum class with a stream operator, Parallel::printf can now print it.

Previously it wouldn't compile because of conditions that excluded an enum class.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-21 19:34 UTC, wthrowe submitted a review, later dismissed

2018-05-21 19:47 UTC, geoffrey4444 submitted a review, later dismissed

2018-05-21 19:49 UTC, kidder submitted a review, later dismissed

2018-05-22 02:31 UTC, nilsdeppe requested changes

2018-05-22 02:31 UTC, nilsdeppe commented on tests/Unit/Parallel/Test_Parallel.cpp
> +enum class TestEnum { Value1 = 1, Value2 = 2 };
Don't explicitly specify the values

2018-05-22 20:46 UTC, kidder approved these changes
@nilsdeppe this is ready for you to look at

2018-05-22 20:47 UTC, wthrowe approved these changes

2018-05-23 00:59 UTC, nilsdeppe approved these changes

2018-05-23 00:59 UTC, merged