Fix compute item missing-argument assertion
sxs-collaboration/spectre pull request #718
Opened 2018-05-21 22:23 UTC by wthrowe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-22 02:48 UTC, nilsdeppe requested changes

2018-05-22 02:48 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +template <typename TagList, typename ComputeTag>
A comment explaining what the different parts of this are doing would probably be helpful

2018-05-22 02:48 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
>    using partial_sub_tree =
I'm not sure this is still the best name for this variable. maybe something like `compute_tag_argument_edges`?

2018-05-22 02:48 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +  using argument_check_assertion = tmpl::transform<
Let's only enable this check in debug mode

2018-05-22 02:48 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +                "A compute item's argument cannot be found in the DataBox.  "
Wouldn't this also be triggered if there are two of the same base tags in the DataBox? If so, then the message should mention that

2018-05-22 02:48 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +template <typename Caller, typename Argument, typename IsOk>
"IsOk" is not the most helpful variable name. Maybe "FoundComputeArgumentInBox"?

2018-05-22 02:48 UTC, nilsdeppe commented on src/DataStructures/DataBox/DataBox.hpp
> +template <typename Caller, typename Argument, typename IsOk>
Since these are tags, maybe `ComputeTag` and `ArgumentTag`?

2018-05-28 21:46 UTC, wthrowe commented
I found a few more places that needed similar warnings, so I'm just adding them to this PR.

2018-06-01 19:14 UTC, wthrowe commented
There are some related failures in db::item_type (passing a base tag with either no list or a list that does not contain anything valid), but I can't find a good way to deal with them.

2018-06-01 21:47 UTC, kidder requested changes
squash and ping @nilsdeppe

2018-06-01 21:47 UTC, kidder commented on src/DataStructures/DataBox/DataBox.hpp
> +  // values of it's arguments.
its

2018-06-02 03:01 UTC, nilsdeppe submitted a review, later dismissed

2018-06-02 03:37 UTC, kidder commented
@wthrowe this just needs squashing your fixups

2018-06-06 03:21 UTC, kidder approved these changes

2018-06-06 03:22 UTC, kidder commented
@nilsdeppe should just need your approval

2018-06-06 20:52 UTC, mar-celine approved these changes

2018-06-06 20:52 UTC, kidder commented
@nilsdeppe you approved before Will squashed, so we will just merge

2018-06-06 20:52 UTC, merged