Added Identity embedding map + test
sxs-collaboration/spectre pull request #72
Opened 2017-06-29 16:32 UTC by osheamonn

2017-06-29 18:28 UTC, wthrowe requested changes

2017-06-29 18:28 UTC, wthrowe commented on src/Domain/EmbeddingMaps/Identity.hpp
> +  void pup(PUP::er& /*p*/) override {}  // NOLINT
I believe this needs to call the base class pup function.

2017-06-29 19:25 UTC, nilsdeppe commented on src/Domain/EmbeddingMaps/Identity.hpp
> +  void pup(PUP::er& /*p*/) override {}  // NOLINT
Yes, this is at least what the Charm++ documentation claims...

2017-06-30 18:49 UTC, nilsdeppe approved these changes

2017-06-30 18:56 UTC, nilsdeppe submitted a review, later dismissed

2017-06-30 23:41 UTC, nilsdeppe approved these changes

2017-06-30 23:41 UTC, merged