Boundary items
sxs-collaboration/spectre pull request #726
Opened 2018-05-28 18:08 UTC by osheamonn

## Proposed changes

Adds `BoundaryDirections` Tag so that interface items works on external boundaries of Elements. 

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-28 20:34 UTC, nilsleiffischer commented
Thanks for getting this in so quickly!

I have one potential issue: For a lot of use cases we'll want to compute quantities on both internal and external boundaries I think, so this would lead to code duplication. For instance the majority of code to compute boundary contributions to variables is the same for internal and external boundaries, only for external boundaries no input from remote elements is necessary (but perhaps from the cache). So can we unify this somehow to have a mechanism to get the data on all boundaries from the databox; is perhaps the base tag mechanism capable of this?

2018-06-08 18:05 UTC, kidder requested changes
you can squash

2018-06-08 18:05 UTC, kidder commented on tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
> +  using magnitude_tag =
this is duplicated from line 220

2018-06-12 21:04 UTC, mar-celine submitted a review, later dismissed

2018-06-12 21:04 UTC, gsb76 commented
@nilsdeppe please look at this

2018-06-13 12:00 UTC, nilsdeppe submitted a review, later dismissed

2018-06-13 12:00 UTC, nilsdeppe commented
Just needs a squash

2018-06-14 20:56 UTC, kidder approved these changes

2018-06-15 21:04 UTC, wthrowe approved these changes

2018-06-15 21:05 UTC, merged