Additions for RotatedBricks 3
sxs-collaboration/spectre pull request #729
Opened 2018-05-29 00:43 UTC by gsb76

## Proposed changes

The final piece allowing for the general construction of rectilinear multicube domains
that have nontrivial orientations and identifications. Useful for testing purposes.

Corner numberings are now almost entirely an implementation detail for these domains
except in the cases where the user wants to set non-periodic identifications on the boundaries 
(e.g. identifying the edges of the cube net to obtain an S2 topology).

Also catches and fixes a bug in RotatedRectangles where the domain was malformed.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/DomainHelpers.hpp
> +/// in an otherwise aligned edifice of blocks, given the OrientationMap an
a block aligned

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/DomainHelpers.hpp
> +/// orientation of each block relative to an aligned edifice. This is used when
of the edifice relative to each block

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/DomainHelpers.cpp
> +        while (opposite_block.find(opposite_block_direction) !=
can write this as a for loop

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/DomainHelpers.cpp
> +        // of `block`, so we identify them. Note that `opposite_block` and
we identify the faces of those blocks that were external boundaries as now being periodic

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/DomainHelpers.cpp
> +        // The face corners in both blocks should be in ascending order
This shortcut only works in the special case where the global corners are increasing in each cartesian direction of the domain

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/DomainHelpers.cpp
> +    // neighbors, set these Directions to external_boundaries.
these directions are external boundaries, so we proceed in the opposite direction to find the block we wish to identify boundaries with (also move this comment inside the direction for loop)

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/DomainHelpers.cpp
> +        set_periodic_boundaries(
this modifies the BlockNeighbors of both the current block and the block it found to be its neighbor

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/Domain.hpp
> +   * the edifice from a cube to sometime more non-trivial, such as an L-shape
something

2018-05-30 20:10 UTC, mar-celine commented on src/Domain/Domain.hpp
> +   * The `identifications` parameter is used when identifying the faces of
mention corners are still needed for identifications / also mention that {} is shorthand for "all aligned"

2018-05-30 20:10 UTC, gsb76 commented on src/Domain/DomainCreators/RotatedRectangles.hpp
> +/// - The lower right block is rotated a half-turn relative to the
180 degrees

2018-06-13 02:41 UTC, wthrowe commented on src/Domain/DomainHelpers.cpp
> +        // size_t neighbor_counter = 0;
Leftover comment.

2018-06-24 02:17 UTC, nilsdeppe commented
I guess this can be squashed and rebased once #758 is merged, then gone through?

2018-06-28 21:55 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +// constructing non-trivial domains for testing such as RotatedBricks.
put in an anonymous namespace

2018-06-28 21:55 UTC, kidder commented on src/Domain/DomainHelpers.cpp
> +            // this assumption is wrong. LCOV_EXCL_START
check if LCOV_EXCL_START works like this

2018-06-29 18:43 UTC, kidder commented
squash

2018-07-02 21:44 UTC, kidder submitted a review, later dismissed
@nilsdeppe please look at

2018-07-03 02:05 UTC, nilsdeppe requested changes

2018-07-03 02:05 UTC, nilsdeppe commented on src/Domain/DomainHelpers.cpp
> +    const auto orientation_of_block = orientations_of_all_blocks[block_id];
Why not a `const auto&`?

2018-07-03 02:05 UTC, nilsdeppe commented on src/Domain/DomainHelpers.cpp
> +          if (opposite_block.find(opposite_block_direction) !=
I would find all this a lot clearer if you just did the opposite logic:
```
if (opposite_block.find(...) == opposite_block.end()) {
  continue;
}
....
```

2018-07-03 02:05 UTC, nilsdeppe commented on src/Domain/DomainHelpers.hpp
> +// Iterates over the 2^(VolumeDim-1) logical corners of the face of a
All should be doxygen comment

Is there a test?

2018-07-09 22:03 UTC, gsb76 commented
@nilsdeppe changes have been addressed and I have been asked to squash the fixes in code review. If there aren't any changes left to be made please approve :)

2018-07-10 00:23 UTC, nilsdeppe approved these changes
:+1: noice

2018-07-10 01:35 UTC, kidder approved these changes

2018-07-10 01:35 UTC, merged