Add mass operator
sxs-collaboration/spectre pull request #737
Opened 2018-06-01 14:53 UTC by nilsleiffischer

## Proposed changes

This PR adds a linear operator that applies the mass matrix to a `DataVector` in the diagonal mass matrix approximation. This is needed to make the operator in elliptic equations symmetric, which helps with their iterative solution. If there are alternatives to this approach, please let me know.

I'll add tests and a compute item tag, too.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files) or `tests/Unit/TestingFramework.hpp` (only in tests)
  2. Blank line (only in cpp files and tests)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### Further comments

2018-06-01 22:40 UTC, kidder commented
It is not clear to either @wthrowe  or myself what this function is needed for.  Can you provide an example...  preferably in the missing test...,  and we don't like the name `mass` no matter it does

2018-06-01 22:54 UTC, nilsleiffischer commented
Yes I'll do that in about a week from now, since I'm at a conference next week. For now: E.g. the strong DG formulation of a simple Poisson eqn -laplace(u)=f is a linear eqn A.u=b where A=(-laplace(u),phi_k)=-M.D.D.u-M.lift(boundary) and b=(f,phi_k)=M.f. In this form A is symmetric, but M_inv.A is not. Since it's easier to solve Ax=b for A symmetric I need the mass operator. I can make this more precise when I'm back if you need more information.

Regarding the name, do you have a suggestion?

2018-06-12 19:27 UTC, geoffrey4444 requested changes
I had just minor comments, mostly asking to clarify the documentation. But where is the test for this code?

2018-06-12 19:27 UTC, geoffrey4444 commented on src/NumericalAlgorithms/LinearOperators/Mass.cpp
> +#include <ostream>
The code guidelines say to #include Parallel/Printf.hpp, which is safe to use in parallel, instead of <iostream>.

2018-06-12 19:27 UTC, geoffrey4444 commented on src/NumericalAlgorithms/LinearOperators/Mass.hpp
> +/// Defines function mass.
This comment does not clearly tell me what this code is supposed to do. Can you please clarify?

2018-06-12 19:27 UTC, geoffrey4444 commented on src/NumericalAlgorithms/LinearOperators/Mass.hpp
> + * \brief Applies the mass matrix.
Change to "Applies the mass matrix to a DataVector."

2018-06-12 19:27 UTC, geoffrey4444 commented on src/NumericalAlgorithms/LinearOperators/Mass.hpp
> + */
Can you please expand this comment to say more about what this code is doing? Something along the lines of what you put in the PR, e.g. "A linear operator that applies the mass matrix to a DataVector in the diagonal mass matrix approximation. This is needed to make the operator in elliptic equations symmetric, which helps with their iterative solution. For details on the diagonal mass matrix approximation, please see spectre/src/NumericalAlgorithms/DiscontinuousGalerkin/LiftFlux.hpp." It's fine to refer to other comments, but I'd like to be able to know what the function does when I first look at the hpp file.

2018-08-13 21:05 UTC, nilsleiffischer commented
Closing this for now, will revisit when we want to make operators symmetric for better linear solve properties, possible in a primal formulation as discussed in #767

2018-08-13 21:05 UTC, closed without merging