Add GrMhd directory structure and simple DataBox tags
sxs-collaboration/spectre pull request #742
Opened 2018-06-08 06:11 UTC by kidder

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-08 18:18 UTC, kidder reviewed
@nilsdeppe do we want the name of a tensor to include its frame?

2018-06-08 19:17 UTC, nilsdeppe commented
Do you mean in a function argument or the tag? For the tag case if the frame is already a template parameter I don't see a need (or way). If the tag is not then it could be useful if the frame is not the inertial frame, I think. By default we should do as SpEC does and use the inertial frame.

2018-06-08 19:41 UTC, kidder commented
sorry, I meant should `static std::string name()` of a tag struct for a tensor use the frame as part of its name?  I plan to default the frames of tag structs to `Frame::Inertial`

2018-06-08 19:44 UTC, nilsdeppe commented
Ah, sorry! This depends on whether we want to be able to observe tensors not in the inertial frame (probably?). We could have `psi` be inertial, and say `psi<Grid>` for grid. That would make the observer code cleaner, while making input files only somewhat more verbose :) Thoughts?

2018-06-08 19:56 UTC, kidder commented
Yes, I was thinking something along those lines.  For the inertial frame, just the short name and something   else if in a different frame.  Possible choices would be (where Frame = Grid, Distorted, Logical, ... and Name is the short name (e.g. SpatialMetric, SpatialVelocity, ...)

- `FrameName`
- `NameFrame`
- `Frame_Name`
- `Name_Frame`
- `Frame::Name`

Any preference?

2018-06-09 11:01 UTC, nilsdeppe commented
I personally like something separating the names, so of the ones you listed I like `Frame::Name`, but I also like `Name<Frame>`. Even `Name::Frame` is fine by me. I don't like the `FrameName` styles. Could you set up a Doodle poll and send it to the SpECTRE list to see what other people think? This is really a question for end users, but I would very strongly discourage not have `::` or `<>`, or `[]` or something like that to denote where the frame and name are separate. Underscores are not great because in snake_case it's not a prefix.

2018-06-09 14:33 UTC, kidder commented
What is this string being used for?  '<' and '>' cannot (or should not) be used in file names for example...

2018-06-09 20:38 UTC, nilsdeppe commented
Ah, they'll be used as groups inside H5 files. Let's stick to path-safe names then. This would lead me to `Frame::Name` as probably clearest, while `Frame_Name` is most file system friendly. Being somewhat scared of what H5 and future file systems will do with colons, I'm inclined to do `Frame_Name`.

2018-06-11 22:45 UTC, kidder reviewed
@nilsdeppe please look at

2018-06-11 22:48 UTC, wthrowe submitted a review, later dismissed

2018-06-12 10:26 UTC, nilsdeppe requested changes
Please squash immediately :)

2018-06-12 10:26 UTC, nilsdeppe commented on src/DataStructures/Tensor/IndexType.hpp
> +/// name function of a tag.
We should mention what the prefix will be. That in all cases except `Inertial` it will be just `Frame_` since this will be used for getting `Tensor`s to disk :)

2018-06-12 20:48 UTC, mar-celine approved these changes

2018-06-12 20:55 UTC, wthrowe approved these changes

2018-06-12 21:35 UTC, kidder commented
@nilsdeppe please look at this

2018-06-13 01:59 UTC, nilsdeppe approved these changes

2018-06-13 01:59 UTC, merged