Simplify Tags::Normalized using tag inheritance
sxs-collaboration/spectre pull request #746
Opened 2018-06-11 19:49 UTC by wthrowe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-11 22:48 UTC, kidder requested changes

2018-06-11 22:48 UTC, kidder commented on src/DataStructures/Tensor/EagerMath/Magnitude.hpp
> +  static std::string name() noexcept { return "Magnitude"; }
Magnitude of what?

2018-06-11 22:48 UTC, kidder commented on src/DataStructures/Tensor/EagerMath/Magnitude.hpp
>    static std::string name() noexcept { return "Normalized"; }
of what?

2018-06-12 18:21 UTC, kidder approved these changes

2018-06-12 18:21 UTC, kidder commented
@nilsdeppe please look at this

2018-06-13 12:10 UTC, nilsdeppe approved these changes

2018-06-13 12:10 UTC, merged