Fix Git hooks and have Travis check formatting
sxs-collaboration/spectre pull request #75
Opened 2017-06-29 19:39 UTC by nilsdeppe

- Git hooks are no longer run erroneously on all files if no files were modified or added.
- Travis checks basic formatting on the entire repository.

2017-06-29 20:09 UTC, wthrowe requested changes

2017-06-29 20:09 UTC, wthrowe commented on tools/Hooks/pre-commit.sh
> +if [ -z "$commit_files" ]; then
There's another check for this later in the script, which can now be removed.

2017-06-29 20:15 UTC, nilsdeppe commented on tools/Hooks/pre-commit.sh
> +if [ -z "$commit_files" ]; then
Okay, removed!

2017-06-29 23:15 UTC, fmahebert approved these changes

2017-06-30 20:06 UTC, osheamonn approved these changes

2017-06-30 23:38 UTC, merged