Extend Sphere to allow for EquatorialCompression
sxs-collaboration/spectre pull request #750
Opened 2018-06-13 17:00 UTC by gsb76

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-13 20:28 UTC, osheamonn submitted a review, later dismissed

2018-06-14 22:52 UTC, kidder submitted a review, later dismissed
@nilsdeppe please look at

2018-06-15 00:16 UTC, nilsdeppe commented on src/Domain/DomainCreators/Shell.hpp
> +    static type default_value() { return 1.0; }
noexcept constexpr

2018-06-15 10:58 UTC, nilsdeppe submitted a review, later dismissed
Go ahead and squash, then merge without me re-approving :)

2018-06-15 19:50 UTC, kidder requested changes
squash

2018-06-15 19:50 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +/// The argument to `aspect_ratio` sets the equatorial compression factor,
remove to

2018-06-15 19:50 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +/// if `aspect_ratio` is set to something other than one, the default value.
Start a new sentence

2018-06-15 20:57 UTC, kidder requested changes

2018-06-15 20:57 UTC, kidder commented on tests/Unit/Domain/DomainCreators/Test_Shell.cpp
> +  }
else instead of two ifs

2018-06-15 20:58 UTC, kidder requested changes
squash

2018-06-15 20:58 UTC, kidder commented on src/Domain/DomainHelpers.hpp
> +/// This is done if `aspect_ratio` is set to something other than one,
other than the default value of one.

2018-06-17 16:35 UTC, nilsdeppe commented
please rebase this on develop to resolve the conflict

2018-06-19 20:48 UTC, kidder approved these changes

2018-06-19 20:49 UTC, carmaza approved these changes

2018-06-19 20:50 UTC, merged