Add ConservativeNormalDotFlux compute tag
sxs-collaboration/spectre pull request #753
Opened 2018-06-14 04:43 UTC by wthrowe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-15 18:12 UTC, kidder requested changes

2018-06-15 18:12 UTC, kidder commented on tests/Unit/Evolution/Conservative/Test_Tags.cpp
> +void copy_into(const gsl::not_null<OutTensor*> out, const InTensor& in,
please add comment what this is doing

2018-06-19 21:22 UTC, kidder approved these changes

2018-06-19 21:22 UTC, kidder commented
@nilsdeppe please look at

2018-06-20 01:31 UTC, nilsdeppe approved these changes

2018-06-20 01:31 UTC, merged