LTS communication
sxs-collaboration/spectre pull request #757
Opened 2018-06-14 22:11 UTC by wthrowe

## Proposed changes

Adds the code required for communicating fluxes between elements taking steps at different times.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-15 19:11 UTC, kidder requested changes
squash

2018-06-15 19:11 UTC, kidder commented on src/Time/TimeId.hpp
> +  TimeId(bool time_runs_forward, size_t slab_number, const Time& step_time,
document parameters

2018-06-15 19:11 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication.hpp
> +              "Received data that depends on the step being taken");
Shouldn't receive data that depended upon the step being taken" , and then print out the appropriate values

2018-06-15 19:11 UTC, kidder commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication.hpp
> +        try {
replace with two finds

2018-06-15 19:11 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication.cpp
> +  // Global step 0 -> 2 with left element taking second step
2 should be 1

2018-06-15 19:11 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication.cpp
> +  run_lts_case(1, {0, 1, 2}, {0, 1});
note to Will: convince yourself this is doing the right thing

2018-06-15 19:11 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication.cpp
> +  run_lts_case(3, {0, 1, 3, 4}, {0, 1, 2, 4});
again

2018-06-15 19:11 UTC, kidder commented on tests/Unit/NumericalAlgorithms/DiscontinuousGalerkin/Actions/Test_FluxCommunication.cpp
> +  // No receives from one or both sides
(because one or more neighbors have already made it to the desired time)

2018-06-19 21:17 UTC, kidder approved these changes

2018-06-19 21:17 UTC, kidder commented
@nilsdeppe please look at

2018-06-20 01:26 UTC, nilsdeppe approved these changes

2018-06-20 01:26 UTC, nilsdeppe commented on tools/FileTestDefs.sh
> +    is_c++ "$1" && grep '^[^#].\{80,\}' "$1" | grep -Ev 'https?://' | \
I'm quite surprised we just ran into this now. :+1:

2018-06-20 01:26 UTC, nilsdeppe commented on src/NumericalAlgorithms/DiscontinuousGalerkin/Actions/FluxCommunication.hpp
> +          // prevents gcc-7.3.0 from segfaulting.
huh, this is the opposite to what GCC normally does with lambdas: it segfaults when you  have them... :/ RIP

2018-06-20 01:26 UTC, merged