ABN local time stepping simplification
sxs-collaboration/spectre pull request #759
Opened 2018-06-15 05:09 UTC by wthrowe

## Proposed changes

Replaces the local time stepping equation implemented in the AdamsBashforthN class with an equivalent simpler one.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-15 19:31 UTC, kidder requested changes
squash

2018-06-18 21:34 UTC, wthrowe commented
I was there for the review session, but I can't figure out what I was supposed to squash.

2018-06-18 21:45 UTC, kidder approved these changes

2018-06-18 21:46 UTC, kidder commented
@nilsdeppe please look at

2018-06-18 21:47 UTC, kidder commented
@wthrowe I think I was tired after all of those reviews, there doesn't seem to be anything I requested...

2018-06-19 21:09 UTC, kidder commented
@nilsdeppe please look at

2018-06-20 00:48 UTC, nilsdeppe approved these changes

2018-06-20 00:48 UTC, merged