Fix line wraps in GitHub PR template
sxs-collaboration/spectre pull request #768
Opened 2018-06-19 12:56 UTC by nilsleiffischer

## Proposed changes

Removes the 80 char line wraps in the `.github/` templates to render them better on GitHub.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-19 12:58 UTC, nilsleiffischer commented on .github/ISSUE_TEMPLATE.md
> -### Desired feature:
This is unused in most issues, so I removed it.

2018-06-19 20:57 UTC, kidder commented
@nilsdeppe please look at

2018-06-20 00:52 UTC, nilsdeppe approved these changes

2018-06-20 01:38 UTC, nilsdeppe requested changes
I take it back, don't remove that.

2018-06-21 13:28 UTC, nilsleiffischer commented
done and squashed

2018-06-22 01:39 UTC, kidder approved these changes

2018-06-22 01:40 UTC, kidder commented
@nilsdeppe please look at

2018-06-22 02:08 UTC, nilsdeppe commented on .github/ISSUE_TEMPLATE.md
> +Add as an attachment `$SPECTRE_BUILD_DIR/LibraryVersions.txt` or add its contents here.
No

2018-06-22 02:08 UTC, nilsdeppe commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For instructions on how to perform the CI checks locally refer to the [Dev guide on the Travis CI](https://spectre-code.
No

2018-06-22 02:08 UTC, nilsdeppe commented on .github/PULL_REQUEST_TEMPLATE.md
> +If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
No

2018-06-22 02:09 UTC, nilsdeppe commented
Closing this because it only makes the lines over 80 chars long.

2018-06-22 02:09 UTC, closed without merging

2018-06-25 14:47 UTC, nilsleiffischer commented
Apparently, GitHub chooses to render Markdown soft line breaks as hard line breaks in comments (including PR descriptions), see https://github.com/github/markup/issues/1050. It not a bug, it's a feature ;) So I think we should adhere to that. Thoughts?

2018-06-26 01:31 UTC, nilsdeppe commented
Like I said before, feel free to file a bug report if they don't want to adhere to markdown standards. I still don't see how there are any issues with the way it renders currently.