Add a script to render docs from a PR
sxs-collaboration/spectre pull request #781
Opened 2018-06-23 18:12 UTC by wthrowe

This will only work on PRs that have the CMakeLists.txt changes included here applied.  At the moment that is just this PR.

There is OSX-specific code in the rendering script that I cannot test.  I will need someone else to do that for me.

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-23 18:56 UTC, mar-celine requested changes
Also document the existence of this script in Doxygen and show an example of how to run the script :+1:

2018-06-23 20:41 UTC, nilsdeppe requested changes
This will be great to have. I just tested this and encountered a couple issues, mostly documentation-ish.

If it's alright with you, once this is in I'll adapt it to work with Jenkins (copy-paste into Jenkins to avoid security issues) to build and display the docs for every PR.

2018-06-23 20:41 UTC, nilsdeppe commented on tools/pr-docs
> +spectre=$(git rev-parse --show-toplevel)
This script assumes it's run from inside the source directory and I get the error `fatal: not a git repository (or any of the parent directories): .git` which may not be helpful. Is there a way to catch this error and print a message explaining the issue to the user?

2018-06-23 20:41 UTC, nilsdeppe commented on tools/pr-docs
> +cmake -D DOCS_ONLY=TRUE source
If I run this in a new directory that has never built anything it fails inside SetupCharm. Is this intentional? If so could you add a comment saying something about this?

2018-06-26 04:07 UTC, wthrowe reviewed
(I haven't done the documentation update yet.)

You're welcome to adapt this for Jenkins, but most of this script is to avoid trashing the user's working tree.  That's probably not relevant on Jenkins, so you could just fetch && checkout && cmake(?) && make doc

Also, if this is all going to be done by Jenkins I'm not sure this script is useful to have in the repo.

2018-06-26 04:07 UTC, wthrowe commented on tools/pr-docs
> +cmake -D DOCS_ONLY=TRUE source
It doesn't know anything about your build directory, so I'm not sure how that could matter.  Were you running against this PR?  As mentioned above, this is the only one it will work on at the moment.

2018-07-23 21:02 UTC, kidder commented
@nilsdeppe please look at the latest comment

2018-07-31 11:26 UTC, nilsdeppe requested changes
Small documentation comment. Feel free to squash :)

2018-07-31 11:26 UTC, nilsdeppe commented on tools/pr-docs
> +    echo "Render documentation from a pull request" >&2
I think this needs more documentation. Where can I run it from (I'd just say people should run it from SPECTRE_HOME to make your life easier)? Will it set up a full build tree or just dump the docs right into the output directory?

I'm not sure where in the Doxygen documentation we should point people to this file. Maybe the code review guidelines?

2018-08-07 22:00 UTC, wthrowe commented
I'm going to hold off on addressing any of the review comments until we come to a decision on whether we actually want this script or not.

2018-08-16 16:53 UTC, nilsdeppe commented
I personally don't see a reason not to have this script, even if we have Jenkins or some CI render the docs for PRs I can see potential use for it. Definitely the option to only run Doxygen is something we should get in sooner rather than later.

2018-08-21 12:55 UTC, nilsdeppe commented
We won't be moving to Jenkins until November/December, so this will certainly be useful until then (and still likely longer) :)

2018-08-27 21:07 UTC, wthrowe commented
I've added documentation mentioning the script to the Travis page.  I did not add anything to the code review page because there didn't seem to be anywhere there that it fit.

2018-08-27 21:45 UTC, kidder approved these changes

2018-08-27 23:08 UTC, nilsdeppe approved these changes

2018-08-28 00:54 UTC, kidder commented
@gsb76 please look at

2018-08-28 03:40 UTC, mar-celine approved these changes

2018-08-28 12:07 UTC, nilsdeppe commented
travis failures are timeouts.

2018-08-28 12:08 UTC, merged