Extend DomainTestHelpers to generic Frames
sxs-collaboration/spectre pull request #783
Opened 2018-06-24 02:52 UTC by gsb76

## Proposed changes

DomainTestHelpers currently hard-codes Frame::Inertial into its tests.
As BinaryCompactObject will have Frame::Grid we need to extend DomainTestHelpers.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-06-25 20:18 UTC, kidder requested changes
squash

2018-06-25 20:18 UTC, kidder commented on tests/Unit/Domain/DomainTestHelpers.cpp
> +    const Domain<VolumeDim, SpatialFrame>& domain,
SpatialFrame->Fr

2018-06-25 20:18 UTC, kidder commented on tests/Unit/Domain/DomainTestHelpers.cpp
> +    const Domain<VolumeDim, SpatialFrame>& domain,
and in a separate commit do this for `euclidean_basis_vector`

2018-06-26 18:31 UTC, kidder approved these changes
@nilsdeppe please look at

2018-06-27 00:05 UTC, nilsdeppe approved these changes

2018-06-27 03:27 UTC, merged