Setup Elliptic systems directory structure
sxs-collaboration/spectre pull request #789
Opened 2018-06-26 13:17 UTC by nilsleiffischer

## Proposed changes

This PR adds the `Elliptic/Systems/` directory structure with three systems that we plan to implement. Adding this allows @geoffrey4444 and me to start contribute code.

2018-06-26 16:02 UTC, kidder requested changes
Please make this look very similar to #742 
That is add the CMake files, add tests for the names of the tags, introduce an EllipticSystems doxygen group, document the namespaces

2018-06-28 22:03 UTC, kidder reviewed
squash these

2018-07-01 13:24 UTC, nilsvu commented
👍

2018-07-02 21:54 UTC, kidder approved these changes
@nilsdeppe please look at

2018-07-02 22:01 UTC, kidder requested changes

2018-07-02 22:01 UTC, kidder commented on tests/Unit/Elliptic/Systems/XCTS/CMakeLists.txt
> +  "XCTS"
this needs to be the empty string `""`until a library is actually created

2018-07-02 22:01 UTC, kidder commented on tests/Unit/Elliptic/Systems/ThermalNoise/CMakeLists.txt
> +  "ThermalNoise"
`""` until the library exists

2018-07-02 22:01 UTC, kidder commented on tests/Unit/Elliptic/Systems/Poisson/CMakeLists.txt
> +  "Poisson"
`""` until the library exists

2018-07-03 10:25 UTC, nilsdeppe requested changes

2018-07-03 10:25 UTC, nilsdeppe commented on src/Elliptic/Systems/XCTS/CMakeLists.txt
> +set(LIBRARY XCTS)
`Xcts` both the lib name and the directory. What you currently have is not CamelCase.

2018-07-03 10:25 UTC, nilsdeppe commented on src/Elliptic/Systems/XCTS/Tags.hpp
> +namespace XCTS {
`xcts` will be much easier to type, but the other allowed alternative is `Xcts`

2018-07-03 10:25 UTC, nilsdeppe commented on src/Elliptic/Systems/XCTS/Tags.hpp
> +class DataVector;
You need to `/// \cond` and `/// \endcond` around the forward decls

2018-07-03 10:25 UTC, nilsdeppe commented on tests/Unit/Elliptic/Systems/XCTS/Test_XCTSTags.cpp
> +// Distributed under the MIT License.
`Test_XctsTags.cpp`

2018-07-10 16:33 UTC, nilsleiffischer commented
👍

2018-07-11 00:43 UTC, nilsdeppe requested changes

2018-07-11 00:43 UTC, nilsdeppe commented on src/Elliptic/Systems/Poisson/Tags.hpp
> +class DataVector;
cond

2018-07-11 00:43 UTC, nilsdeppe commented on src/Elliptic/Systems/ThermalNoise/Tags.hpp
> +class DataVector;
cond

2018-07-12 14:38 UTC, nilsleiffischer commented
fixed

2018-07-14 02:16 UTC, kidder approved these changes

2018-07-14 02:16 UTC, kidder commented
@nilsdeppe please look at

2018-07-14 02:33 UTC, nilsdeppe approved these changes

2018-07-14 02:39 UTC, merged