Add SpecialMobius CoordinateMap
sxs-collaboration/spectre pull request #798
Opened 2018-06-29 04:56 UTC by gsb76

## Proposed changes

The current BinaryCompactObject Domain (#709) has its compact objects located at the centers of two cubes. By construction, these objects can neither be translated nor scaled along the x-axis - they are frozen in place at the center of each cube. One problem that this causes is that the center of mass is not necessarily located at the origin of domain. SpecialMobius is a conformal map with analytic inverse that can be used to shift the center of mass to the origin while still preserving the spherical shapes of the wave zone and the two compact objects.

The name comes from the fact that it is a special case of the more general Mobius family of conformal transformations. Rename suggestions are welcome.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-07-03 19:44 UTC, kidder reviewed
Determine a good limit for mu and enforce it

2018-07-09 22:04 UTC, gsb76 commented
@kidder Changes have been addressed

2018-07-14 02:20 UTC, kidder reviewed
squash

2018-08-01 21:58 UTC, kidder requested changes

2018-08-01 21:58 UTC, kidder commented on src/Domain/CoordinateMaps/SpecialMobius.cpp
> +      -(mu_squared * (2.0 * x * x - r_squared) - 2.0 * mu * x + 1.0) *
square(x)

2018-08-01 21:58 UTC, kidder commented on src/Domain/CoordinateMaps/SpecialMobius.cpp
> +      -(mu_squared * (r_squared - 2.0 * y * y) - 2.0 * mu * x + 1.0) *
square(y)

2018-08-01 21:58 UTC, kidder commented on src/Domain/CoordinateMaps/SpecialMobius.cpp
> +      -(mu_squared * (r_squared - 2.0 * z * z) - 2.0 * mu * x + 1.0) *
square(z)

2018-08-01 21:58 UTC, kidder commented on src/Domain/CoordinateMaps/SpecialMobius.cpp
> +  const double mu_squared = mu * mu;
square(mu)

2018-08-01 21:58 UTC, kidder commented on src/Domain/CoordinateMaps/SpecialMobius.hpp
> + *
mention limit of mu (for accuracy)

2018-08-01 21:58 UTC, kidder commented on src/Domain/CoordinateMaps/SpecialMobius.hpp
> + * - \f$(\mu,0) = 0\f$.
fix this

2018-08-16 19:28 UTC, nilsdeppe commented
@osheamonn could you look at this one? I have the dox rendered: http://gh.nilsdeppe.com/spectre/pr_798/classCoordinateMaps_1_1SpecialMobius.html

2018-08-16 19:41 UTC, nilsdeppe approved these changes

2018-08-16 19:48 UTC, osheamonn approved these changes

2018-08-20 21:37 UTC, kidder approved these changes

2018-08-20 21:37 UTC, kidder commented
@wthrowe please look at

2018-08-21 16:24 UTC, wthrowe approved these changes

2018-08-21 16:25 UTC, wthrowe commented
Travis failures are the usual timeouts.

2018-08-21 16:25 UTC, merged