Add ElementId and test
sxs-collaboration/spectre pull request #81
Opened 2017-06-30 20:19 UTC by gsb76

2017-06-30 20:36 UTC, nilsdeppe requested changes

2017-06-30 20:36 UTC, nilsdeppe commented on tests/Unit/Domain/Test_ElementId.cpp
> +  static_cast<void>(test_id);
don't need this cast since it's being used

2017-06-30 20:36 UTC, nilsdeppe commented on src/Domain/ElementId.cpp
> +namespace std {
Probably want to ignore this in LCOV

2017-06-30 23:43 UTC, nilsdeppe submitted a review, later dismissed

2017-06-30 23:47 UTC, nilsdeppe commented
@gsb76  It turns that GitHub's interactive edits for merge conflict resolution is not as nice as I'd hope... Could you do a rebase locally and then force push over the edit on GH?

2017-07-01 22:17 UTC, wthrowe commented on tests/Unit/Domain/Test_ElementId.cpp
> +  CHECK(element_three != block_2_3d);
Check != for two different elements in the same block.

2017-07-07 02:38 UTC, osheamonn approved these changes

2017-07-07 02:50 UTC, merged