Work around broken libc++ array implementation
sxs-collaboration/spectre pull request #841
Opened 2018-07-26 19:11 UTC by wthrowe

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-07-26 20:51 UTC, kidder submitted a review, later dismissed
@nilsdeppe please look at

2018-07-27 02:35 UTC, nilsdeppe requested changes

2018-07-27 02:35 UTC, nilsdeppe commented on tests/Unit/Utilities/Test_MakeArray.cpp
>    // Check make_array with an rvalue sequence
I don't understand the commit message.

2018-07-27 02:35 UTC, nilsdeppe commented on CMakeLists.txt
>  include(SetupListTargets)
The commit message should both describe the bug and link to the libc++ bug.

2018-07-27 21:35 UTC, kidder commented on tests/Unit/Utilities/Test_MakeArray.cpp
>    // Check make_array with an rvalue sequence
maybe "address clang-tidy complaint"

2018-07-30 20:30 UTC, kidder approved these changes
@nilsdeppe please look at

2018-07-31 00:44 UTC, nilsdeppe approved these changes

2018-07-31 00:44 UTC, merged