Add DenseVector make_with_value
sxs-collaboration/spectre pull request #857
Opened 2018-08-10 10:26 UTC by nilsleiffischer

### Types of changes:

- [x] New feature

### Component:

- [x] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

2018-08-10 16:45 UTC, wthrowe requested changes
No need for a fixup commit.  Just squash.

2018-08-10 16:45 UTC, wthrowe commented on src/DataStructures/DenseVector.hpp
> +    const DenseVector<double>& input, const double value) {
noexcept

2018-08-10 19:29 UTC, osheamonn submitted a review, later dismissed

2018-08-13 18:21 UTC, wthrowe approved these changes

2018-08-16 16:54 UTC, nilsdeppe approved these changes

2018-08-16 16:55 UTC, merged