Add analytic solutions Doxygen group, closes #858
sxs-collaboration/spectre pull request #879
Opened 2018-08-20 13:01 UTC by nilsleiffischer

## Proposed changes

### Types of changes:

- [x] New feature

### Component:

- [x] Documentation

2018-08-20 13:11 UTC, nilsdeppe requested changes
In #858: I don't see why we would want this.

I think we should have the design decision discussion on the issue so that at least it's in one place.

2018-08-20 13:34 UTC, nilsleiffischer commented
Fixed so that the namespaces are listed, not all analytic solutions within

2018-08-21 12:53 UTC, nilsdeppe approved these changes

2018-08-21 13:58 UTC, kidder approved these changes

2018-08-21 13:58 UTC, kidder commented
travis failure is timeout

2018-08-21 13:58 UTC, merged