Update wheeler environments to load Python
sxs-collaboration/spectre pull request #894
Opened 2018-08-24 17:12 UTC by osheamonn

We now require NumPy 1.10 which is greater than the wheeler system NumPy version, so load the module on wheeler which satisfies this requirement (loads NumPy 1.13)

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-08-24 17:17 UTC, wthrowe requested changes

2018-08-24 17:17 UTC, wthrowe commented on support/Environments/wheeler_gcc.sh
> +    module load python/anaconda2-4.1.1
unload

2018-08-24 17:24 UTC, osheamonn commented on support/Environments/wheeler_gcc.sh
> +    module load python/anaconda2-4.1.1
Indeed

2018-08-24 17:26 UTC, mar-celine approved these changes

2018-08-24 17:29 UTC, wthrowe approved these changes

2018-08-24 18:17 UTC, kidder approved these changes

2018-08-24 18:17 UTC, kidder commented
@nilsdeppe please look at

2018-08-24 18:19 UTC, nilsdeppe approved these changes

2018-08-25 00:29 UTC, nilsdeppe commented
travis failures are timeouts

2018-08-25 00:29 UTC, merged