Additions to AddSpectreExecutable
sxs-collaboration/spectre pull request #917
Opened 2018-09-03 21:34 UTC by gsb76

- Add an HPP_NAME parameter for when the executable name
  does not match the name of the hpp file.
- Include a HPP_NAMEFwd.hpp for forward declaring the
  metavariables struct. This is useful for when the
  metavariables is templated on a parameter that needs
  to be known by the `charm_init_node_funcs` function,
  for example.

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-04 00:04 UTC, nilsdeppe requested changes
I'm fine for you to squash

2018-09-04 00:04 UTC, nilsdeppe commented on cmake/AddSpectreExecutable.cmake
> -function(add_spectre_executable EXECUTABLE_NAME SUBDIR_NAME METAVARS LINK_LIBS)
Please document the new argument above

2018-09-04 18:07 UTC, wthrowe approved these changes

2018-09-04 21:32 UTC, kidder approved these changes

2018-09-04 21:32 UTC, kidder commented
@nilsdeppe I think this is ready

2018-09-07 20:01 UTC, nilsdeppe approved these changes

2018-09-07 20:03 UTC, nilsdeppe commented
Travis failures are timeouts, all tests passed.

2018-09-07 20:03 UTC, merged