Refactor interface items
sxs-collaboration/spectre pull request #921
Opened 2018-09-07 05:46 UTC by osheamonn

## Proposed changes

Refactors the InterfaceItem infrastructure to make better use of base tags, so that decisions about how quantities are computed on the interface are made when adding the Tag to the DataBox (is this a SimpleTag, a ComputeTag, or does it slice variables from the volume?) rather than at the level of the Tags inside of variables which is done now. 

Most of the significant changes occur in src/Domain/Tags.hpp. 
- InterfaceBase and InterfaceImpl removed. 
- InterfaceComputeItem and Slice added.
- Interface is now a simple item, which can be used as a base tag for the above two items. 

Breaks: 
- Anything that touches the Interface part of the Initialization code, the user must now specify 
whether Interface tags are simple, compute items or slices. Before, using the tag Interface worked for everything. 
- If `should_be_sliced_to_boundary` was being defined in any Tags, it now doesn't do anything. Whether the Tag should be sliced is specified by adding it to the DataBox using `Slice`. 

There are some TODO's scattered around which are questions I have for people, regarding using `tmpl::contains_v<TagsList, Tag>` to determine whether a Tag is in the DataBox, since it now fails for the compute tags or slice tags on the interface. 

The last commit (remove sliced_to...) should probably be squashed into the previous one, but I thought it would make reviewing easier.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-07 18:23 UTC, kidder requested changes

2018-09-07 18:23 UTC, kidder commented on src/Domain/Tags.hpp
> +/// ComputeTag which slices a VariablesTag in the volume to an Interface, then
Interface is desired,

2018-09-07 18:23 UTC, kidder commented on tests/Unit/Evolution/DiscontinuousGalerkin/Test_InitializeElement.cpp
> +// TODO: Because now (almost) all Interface tags are retrieved by base tags,
want to keep a runtime check

2018-09-07 21:02 UTC, osheamonn commented
Rebased and squashed. `tag_is_retrievable` is now done using a type trait which is checked at runtime.

2018-09-07 21:14 UTC, kidder submitted a review, later dismissed

2018-09-08 03:42 UTC, osheamonn commented
Had to rebase due to IWYU @kidder

2018-09-08 03:46 UTC, kidder approved these changes

2018-09-08 03:53 UTC, mar-celine approved these changes

2018-09-09 21:32 UTC, nilsdeppe commented
travis failures are test timeouts. @wthrowe feel free to merge if you're happy with this :)

2018-09-09 23:55 UTC, wthrowe approved these changes

2018-09-09 23:55 UTC, merged