Fix small Averager issues
sxs-collaboration/spectre pull request #937
Opened 2018-09-12 20:22 UTC by mgiesler

## Proposed changes

Make averaged_values_ member variable a non boost::optional.
This fixes the error associated with trying to specify noexcept on the 
move constructor in FunctionOfTimeUpdater (since Averager is a member 
variable of FunctionOfTimeUpdater).

### Types of changes:

- [x] Bugfix
- [ ] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-13 14:01 UTC, nilsdeppe requested changes
I'm happy for you to squash the changes :)

2018-09-13 14:01 UTC, nilsdeppe commented on src/ControlSystem/Averager.cpp
> +  // NOTE: here we return a copy. If this is not desired, then we need two boost
Since it is an array of DataVector the copy will be fairly expensive. I'd be fine with having a second variable that is the `boost::none`.

2018-09-13 14:01 UTC, nilsdeppe commented on tests/Unit/ControlSystem/Test_Averager.cpp
> +  auto new_averager(std::move(averager));
I believe another useful test to make sure things are noexcept would [be](https://en.cppreference.com/w/cpp/types/is_move_constructible) `static_assert(std::is_nothrow_move_constructible<Averager>, "");` and similar for

2018-09-13 14:01 UTC, nilsdeppe commented on tests/Unit/ControlSystem/Test_Averager.cpp
> +  CHECK(avg_time == new_averager.average_time(0.9));
Can you also check move assignment?

2018-09-13 14:01 UTC, nilsdeppe commented on src/ControlSystem/Averager.hpp
> +  Averager& operator=(Averager&&) noexcept;
I think this is missing a definition. Maybe I missed it.

2018-09-15 05:01 UTC, mgiesler commented
@nilsdeppe ok, squashed. I added the checks you suggested and I believe I have fixed the copy issue in the call operator -- but, please let me know if I am mistaken. Thanks!!

2018-09-15 19:02 UTC, nilsdeppe requested changes
I'm happy for you to squash these last few minor things :)

2018-09-15 19:02 UTC, nilsdeppe commented on tests/Unit/ControlSystem/Test_Averager.cpp
> +  auto new_averager2 = std::move(new_averager);
This still tests move construction. You want something like:

```
Averager new_averager2{};
new_averager2 = std::move(new_averager);
```

2018-09-15 19:02 UTC, nilsdeppe commented on src/ControlSystem/Averager.hpp
> +  Averager& operator=(Averager&& A) noexcept {
The definition can go in the cpp file and we have been using `rhs` as the variable, not `A` (same variable change for move constructor)

2018-09-15 19:02 UTC, nilsdeppe commented on src/ControlSystem/Averager.cpp
>  boost::optional<std::array<DataVector, DerivOrder + 1>> Averager<DerivOrder>::
Can this return a `const boost::optional<...>&` now?

2018-09-15 19:02 UTC, nilsdeppe commented on src/ControlSystem/Averager.hpp
> +  boost::optional<std::array<DataVector, DerivOrder + 1>> averaged_values_;
Is this change (removing `{}`) actually necessary?

2018-09-15 19:02 UTC, nilsdeppe commented on src/ControlSystem/Averager.hpp
> +  Averager(const Averager&) = delete;
This class used to be copyable, are you sure you don't want it to be anymore? I think the `default` copy semantics would work fine if you needed them. (Note: Not a change request, just confirming this is what you want :) )

2018-09-16 04:22 UTC, mgiesler commented on tests/Unit/ControlSystem/Test_Averager.cpp
> +  auto new_averager2 = std::move(new_averager);
Ahh, of course, I need to construct before assigning. Thanks for catching that.

2018-09-16 04:22 UTC, mgiesler commented on src/ControlSystem/Averager.hpp
> +  boost::optional<std::array<DataVector, DerivOrder + 1>> averaged_values_;
Nope, that was unintentional, thanks for pointing that out.

2018-09-16 04:26 UTC, mgiesler commented on src/ControlSystem/Averager.hpp
> +  Averager(const Averager&) = delete;
Yeah, I meant to do this one. We made the other components of the control system non-copyable, so I made the Averager non-copyable as well.

2018-09-16 04:32 UTC, mgiesler commented
@nilsdeppe, thanks for the review -- squashed again.

2018-09-16 22:29 UTC, nilsdeppe submitted a review, later dismissed

2018-09-17 14:38 UTC, kidder submitted a review, later dismissed

2018-09-18 01:57 UTC, kidder commented
@wthrowe any comments on this?

2018-09-18 03:12 UTC, wthrowe commented
Code looks fine, but Travis OSX has a non-timeout failure that I'm not sure what to make of.

2018-09-18 03:55 UTC, kidder commented
os x failure looks to be from #896

2018-09-19 23:40 UTC, nilsdeppe commented
This just needs a rebase on develop and it should be ready to go :+1:

2018-09-20 01:02 UTC, mgiesler commented
Ok, rebased.

2018-09-20 02:10 UTC, nilsdeppe approved these changes

2018-09-20 06:25 UTC, kidder approved these changes

2018-09-20 11:47 UTC, merged