Variable Fixing Action
sxs-collaboration/spectre pull request #939
Opened 2018-09-14 02:11 UTC by gsb76

## Proposed changes

Wraps the RadiallyFallingFloor struct in an Action.
Tests this Action using the new Action testing framework

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-14 04:36 UTC, wthrowe requested changes

2018-09-14 04:36 UTC, wthrowe commented on src/Evolution/VariableFixing/Actions.hpp
> +/// - Modifies: DensityTag, PressureTag
What are these?

2018-09-14 04:36 UTC, wthrowe commented on src/Evolution/VariableFixing/Actions.hpp
> +  // using fixing_scheme = typename Metavariables::fixing_scheme;
Leftover code?

2018-09-14 04:36 UTC, wthrowe commented on src/Evolution/VariableFixing/Actions.hpp
> +///   - Metavariables::fixing_scheme::return_tags
I think all these `Metavariables::fixing_scheme` references are suppose to be `VariableFixer`.

2018-09-14 04:36 UTC, wthrowe commented on tests/Unit/Evolution/VariableFixing/Test_Actions.cpp
> +#include "tests/Unit/TestingFramework.hpp"
Should be first.

2018-09-14 04:36 UTC, wthrowe commented on tests/Unit/Evolution/VariableFixing/Test_Actions.cpp
> +  const DataVector z{-2.0, -1.0, 0.0, 1.0, 2.0};
Are these intentionally all the same?

2018-09-14 05:11 UTC, gsb76 commented on tests/Unit/Evolution/VariableFixing/Test_Actions.cpp
> +  const DataVector z{-2.0, -1.0, 0.0, 1.0, 2.0};
Yes, but they can be changed if that's wanted. (This is also done to match the test done for the struct RadiallyFallingFloor.) If they should match is also something I'm open to discussion about.

2018-09-14 21:20 UTC, wthrowe requested changes

2018-09-14 21:20 UTC, wthrowe commented on tests/Unit/Evolution/VariableFixing/Test_Actions.cpp
> +// IWYU pragma; no_forward_declare ApplyVariableFixer
`;` -> `:` and add namespace, although this line may become unnecessary once the other IWYU complaints are resolved.

2018-09-14 21:49 UTC, nilsdeppe reviewed
I'm happy for you to squash this once @wthrowe is happy with it :)

2018-09-16 03:41 UTC, gsb76 commented on tests/Unit/Evolution/VariableFixing/Test_Actions.cpp
> +// IWYU pragma; no_forward_declare ApplyVariableFixer
Sorry, I don't know what you mean by "add namespace" - are you referring to the anonymous namespace on line 25? Should it be named?

2018-09-16 04:03 UTC, kidder commented on tests/Unit/Evolution/VariableFixing/Test_Actions.cpp
> +// IWYU pragma; no_forward_declare ApplyVariableFixer
ApplyVariableFixer is in the namespace Actions

2018-09-18 20:30 UTC, kidder commented
rebase when squashing...

2018-09-18 20:36 UTC, wthrowe submitted a review, later dismissed
Squash, rebase.

2018-09-18 21:14 UTC, nilsdeppe submitted a review, later dismissed

2018-09-18 22:21 UTC, nilsdeppe approved these changes

2018-09-18 22:27 UTC, kidder approved these changes

2018-09-18 22:37 UTC, wthrowe approved these changes

2018-09-19 14:06 UTC, merged