Volume observer PR1
sxs-collaboration/spectre pull request #954
Opened 2018-09-18 02:26 UTC by nilsdeppe

## Proposed changes

Adds some classes and functions that'll be necessary for volume observers

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-18 20:57 UTC, kidder requested changes

2018-09-18 20:57 UTC, kidder commented on src/IO/Observer/TemporalId.hpp
> + * \brief A type-erased temporal identifier that combines the identifiers type
identifier's

2018-09-18 20:57 UTC, kidder commented on src/IO/Observer/TemporalId.hpp
> + * The identifier must also have `value()` method that returns a double
have a

2018-09-18 20:57 UTC, kidder commented on src/IO/Observer/TemporalId.hpp
> + * represent the current "time".
representing

2018-09-18 20:57 UTC, kidder commented on src/IO/Observer/TemporalId.hpp
> + * A specialization of `std::hash` is provided to allow using `ArrayComponentId`
TemporalId

2018-09-18 20:57 UTC, kidder commented on src/IO/Observer/TemporalId.hpp
> +  explicit TemporalId(const Id& t);
noexcept

2018-09-18 20:57 UTC, kidder commented on src/DataStructures/Tensor/TensorData.hpp
> +  TensorComponent(std::string n, DataVector d)
noexcept

2018-09-18 20:57 UTC, kidder commented on src/DataStructures/Tensor/TensorData.hpp
> +                             std::vector<TensorComponent> components)
noexcept

2018-09-19 02:41 UTC, nilsdeppe commented
Rebased and addressed fixups.

2018-09-19 02:44 UTC, kidder commented on src/IO/Observer/TemporalId.hpp
> + * represent the current "time".
🛎

2018-09-19 02:51 UTC, nilsdeppe commented on src/IO/Observer/TemporalId.hpp
> + * represent the current "time".
:( Okay, got it for real I think :P

2018-09-19 02:55 UTC, kidder reviewed
you can squash

2018-09-19 02:57 UTC, nilsdeppe commented
Done! :)

2018-09-19 03:02 UTC, kidder submitted a review, later dismissed

2018-09-19 04:14 UTC, wthrowe requested changes

2018-09-19 04:14 UTC, wthrowe commented on src/IO/Observer/TemporalId.hpp
> +class TemporalId {
What is this class for?  Why not just use a double (or simple wrapper around same)?

I don't think we want observations associated with a TemporalId (in the evolution sense) anyway, but just a (little 't') time (double).

2018-09-19 04:14 UTC, wthrowe commented on src/DataStructures/Tensor/TensorData.hpp
> + * `element_volume_data.vol/[ElementIdName]/psi_xx`.
This may become obvious once we actually start producing output, but are the "H5 file" and the "volume file" the same thing?

2018-09-19 17:29 UTC, nilsdeppe commented
@wthrowe I made the renames we discussed.

2018-09-19 17:43 UTC, wthrowe approved these changes

2018-09-19 19:21 UTC, kidder approved these changes

2018-09-20 01:50 UTC, merged