Volume observer PR2 (Does not depend on #954)
sxs-collaboration/spectre pull request #956
Opened 2018-09-18 03:40 UTC by nilsdeppe

## Proposed changes

**Note:** Does not depend on #954 

- Adds various HDF5 related helper functions
- Removes specific helper functions and uses the added generic ones instead.
- There are still missing noexcept, factoring in/out of detail namespaces, etc. in the H5 code that needs to be done, but I will clean this up in a later PR since the whole H5 code helper code could use an overhaul.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-18 21:28 UTC, kidder submitted a review, later dismissed

2018-09-19 02:51 UTC, nilsdeppe commented
rebased on develop

2018-09-19 02:56 UTC, kidder submitted a review, later dismissed

2018-09-19 04:32 UTC, wthrowe requested changes

2018-09-19 04:32 UTC, wthrowe commented on tests/Unit/Utilities/Test_Algorithm.cpp
> +                     [](const int t) { return t == 1; }));
Check the false cases.

2018-09-19 17:48 UTC, wthrowe approved these changes

2018-09-19 19:52 UTC, kidder approved these changes

2018-09-20 06:00 UTC, merged