Add another GRMHD primitive to conservative scheme
sxs-collaboration/spectre pull request #961
Opened 2018-09-18 21:42 UTC by kidder

## Proposed changes

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-19 00:50 UTC, fmahebert reviewed
Small comments on dox, can be squashed directly.

2018-09-19 00:50 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.cpp
> +    const EquationsOfState::EquationOfState<true, ThermodynamicDim>&
Indentation problem here

2018-09-19 00:50 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.hpp
> + * In the Palenzuela paper, `total_energy_density` is \f$D (1+q)\f$,
Here I am not totally clear whether you are defining the code's input variables in terms of the variables in the Palenzuela paper, or in terms of "our" variables.

2018-09-19 00:50 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.hpp
> + * s = & \frac{\gamma_{mn} {\tilde B}^m {\tilde B}^n}{{\tilde D}\sqrt{\gamma}}
As far as I can tell, q,r,t,s are not visible to the user of this class. Should this paragraph be made a Doxygen detail, or perhaps even moved to the .cpp?

2018-09-19 03:00 UTC, kidder commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.hpp
> + * In the Palenzuela paper, `total_energy_density` is \f$D (1+q)\f$,
I state "In the Palenzuela paper...", so what would make it more clear?

2018-09-19 03:12 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.hpp
> + * s = & \frac{\gamma_{mn} {\tilde B}^m {\tilde B}^n}{{\tilde D}\sqrt{\gamma}}
Oh, I see now that these are likely intended to define the q,r,t,s in the other doxygen comment. Can the two comments be combined into one?

2018-09-19 03:20 UTC, fmahebert commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.hpp
> + * In the Palenzuela paper, `total_energy_density` is \f$D (1+q)\f$,
I want to know if the "rhs" (in "X is Y" statements) D is the same D as what we use, or different.

If it is the same, then I am not sure what the statement  "In the Palenzuela paper..." is trying to tell me (because it sounds like it's telling me it's different). In this scenario, I would find it clearer to remove this statement.

If it is different, then I would either rewrite the equations in terms of our variables, or make explicit (as you have below for h) that D is not our D, and give the relation between the two.

2018-09-19 19:31 UTC, nilsdeppe requested changes
I'm happy for you to squash my comments

2018-09-19 19:31 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.hpp
> +  static const std::string name() noexcept { return "Newman Hamlin"; }
Oops... `Newman Hamlin` -> ...

2018-09-19 19:31 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.cpp
> +class FunctionOfX {
I would've found a short comment `// Note: the variable x is defined in the documentation` useful since `x` is usually a spatial coordinate.

2018-09-19 19:31 UTC, nilsdeppe commented on src/Evolution/Systems/GrMhd/ValenciaDivClean/PalenzuelaEtAl.hpp
> +
These comments should be joined.

2018-10-10 15:19 UTC, fmahebert submitted a review, later dismissed

2018-10-10 15:19 UTC, nilsdeppe submitted a review, later dismissed

2018-10-10 15:20 UTC, nilsdeppe commented
@wthrowe could you please look at this one when you get a chance? Thanks!

2018-10-10 22:14 UTC, fmahebert approved these changes

2018-10-10 22:16 UTC, nilsdeppe approved these changes

2018-10-11 00:58 UTC, nilsdeppe commented
Travis timeouts when building last executables

2018-10-11 00:58 UTC, merged