Small fixes in GrTags, including adding SpatialChristoffelSecondKind.
sxs-collaboration/spectre pull request #962
Opened 2018-09-18 21:44 UTC by markscheel

## Proposed changes

Add SpatialChristoffelSecondKind to GrTags, and also make other
things in GrTags consistent.

(This used to be part of the horizon finder PR but it is really independent so I pulled it out)

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-18 22:21 UTC, nilsdeppe requested changes
I'm happy for it to be squashed :)

2018-09-18 22:21 UTC, nilsdeppe commented on src/Evolution/Systems/GeneralizedHarmonic/Tags.hpp
> +#include "TagsDeclarations.hpp"
Haven't we been having everything have the full path?

2018-09-20 06:30 UTC, kidder approved these changes

2018-09-20 11:51 UTC, nilsdeppe approved these changes

2018-09-20 18:46 UTC, wthrowe approved these changes

2018-09-20 18:47 UTC, merged