Volume observer pr3
sxs-collaboration/spectre pull request #973
Opened 2018-09-20 13:03 UTC by nilsdeppe

## Proposed changes

- Replace the current `VolumeDataFile` class with a new `VolumeData` class that is a subfile rather than a separate H5 file.
- Add a couple tags needed for IO

*Note:* Does not depend on anything else currently open.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### Further comments

2018-09-20 19:47 UTC, wthrowe requested changes

2018-09-20 19:47 UTC, wthrowe commented on src/IO/H5/File.hpp
> +    return dynamic_cast<ObjectType&>(*current_object_);
Why not `convert_to_derived`?

2018-09-20 19:47 UTC, wthrowe commented on tests/Unit/IO/Test_H5.cpp
> +      my_file.try_insert<h5::Dat>("/L2_errors", legend, version_number);
Pass different arguments to verify that it doesn't overwrite.

2018-09-20 19:47 UTC, wthrowe commented on src/IO/H5/VolumeData.cpp
> +    const std::vector<int> connectivity = [&extents]() {
noexcept

2018-09-20 20:58 UTC, kidder requested changes

2018-09-20 20:58 UTC, kidder commented on src/IO/H5/VolumeData.cpp
> +    const Header header(true, detail::OpenGroup{}, volume_file_root_group_.id(),
add error if input version doesn't match version_, (and maybe a comment about backwards compatibility when we have more than one version)

2018-09-20 20:58 UTC, kidder commented on src/IO/H5/File.hpp
> +  hid_t group_id = std::get<1>(exists_group_name).id();
what is different between the two cases?

2018-09-20 22:38 UTC, kidder commented on tests/Unit/IO/Test_H5.cpp
> +  // pass bad values to make sure it aren't overridden.
they aren't or it isn't

2018-09-21 13:13 UTC, nilsdeppe commented on tests/Unit/IO/Test_H5.cpp
> +  // pass bad values to make sure it aren't overridden.
Okay, rebased and fixed (hopefully :P )

2018-09-21 14:40 UTC, kidder approved these changes

2018-09-21 16:28 UTC, wthrowe approved these changes

2018-09-21 16:29 UTC, merged